### ISSUE TITLE
ImageList_Create should be in WithSetLastError?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1000]
Comparing it in `Rust`, but the metadata for the "`Result`" is based on what's defined in `WithSetLastError.rsp`

It returns a `HIMAGELIST` which has the `is_invalid()` function.
And it will be invalid when the function fails.

Should be similar to have `CreateFile2` is defined, it returns a `Result<HANDLE>`

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Controls/fn.ImageList_Create.html
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/fn.CreateFile2.html

https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-imagelist_create

**Comment by kennykerr** [comment]
I think the problem is that this API does not necessarily use `SetLastError` to provide more error information. Having a quick glance at the implementation, it doesn't appear to propagate error information at all. So, you may just have to use `is_invalid` to check for failure.

**Comment by Zerowalker** [comment]
Don't you always need to do that, and once you know it's invalid you check what the error was?
Isn't that how other similar functions are handled?

Or do you mean it just doesn't set any error ever?
Cause noticed when checking the documentation that it doesn't meantion "use `GetLastError`", which might be what you meant.
If that's the case an `Option` makes more sense i guess, you either get a result or you don't (or just get a null, depending on how it can be handled in different languages).

**Comment by kennykerr** [comment]
Yes, it may be possible to fall back to using `Option` in Rust if the resulting handle type defines invalid values but doesn't provide error information.

**Comment by Zerowalker** [comment]
Nice, then my issue wasn't another miss I guess:)

**Comment by mikebattista** [comment]
Could you clarify the proposed change to the metadata?

**Comment by Zerowalker** [comment]
Of course:)

`ImageList_Create` should throw an error in case it's 0 basically.
Not really sure how it's done in the metadata as it's not bound to a language in that way,
but there are similar functions which is does treat this way, so was hoping pointing there would help get the idea of what i am talking about.

**Comment by mikebattista** [comment]
@kennykerr could you clarify? The 3 levers that might be relevant here:

* Set SetLastError = true
* Set invalid values for HIMAGELIST
* Set PreserveSig

It's not clear what the ask is or if there is another option being proposed.

**Comment by Zerowalker** [comment]
really sorry for this, clearly didn't made an issue about something I didn't have enough knowledge about.
If it's just wasting everyone time there's no hard feelings if you choose to close the issue,
taking valuable time from the projects is the last thing I want to do.

**Comment by mikebattista** [comment]
Going to close for now as it's unclear what the requested change is. Feel free to reopen if you have more details on the change you want.
