### ISSUE TITLE
`CRED_MAX_USERNAME_LENGTH` is missing (wincred.h)

### ISSUE THREAD

**Issue by arlosi** [microsoft/win32metadata#1002]
Most constants from `wincred.h` are present, however several are missing. For example:
`CRED_MAX_USERNAME_LENGTH`
`CRED_MAX_CREDENTIAL_BLOB_SIZE`

May be relevant that these missing constants have computed values in their definitions in `wincred.h`, while other constants (which are present) defined next to them do not.
```
#define CRED_MAX_STRING_LENGTH 256 // present
#define CRED_MAX_CREDENTIAL_BLOB_SIZE (5*512) // missing
#define CRED_MAX_USERNAME_LENGTH (256+1+256) // missing
```

**Comment by kennykerr** [comment]
Yep, that's odd that those are missing.

**Comment by riverar** [comment]
Current metadata tooling doesn't support evaluating expressions, so we'll have to add these manually.

**Comment by mikebattista** [comment]
Windows.Win32.Security.Credentials.Apis.CRED_MAX_CREDENTIAL_BLOB_SIZE not found in 1st winmd
Windows.Win32.Security.Credentials.Apis.CRED_MAX_USERNAME_LENGTH not found in 1st winmd
Windows.Win32.Security.Credentials.Apis.CRED_MAX_DOMAIN_TARGET_NAME_LENGTH not found in 1st winmd
Windows.Win32.Security.Credentials.Apis.CREDUI_MAX_DOMAIN_TARGET_LENGTH not found in 1st winmd
Windows.Win32.Security.Credentials.Apis.CREDUI_MAX_USERNAME_LENGTH not found in 1st winmd
