### ISSUE TITLE
Feature request: PAUTHZ_CLIENT_CONTEXT_HANDLE in functions should be a pointer or &mut AUTHZ_CLIENT_CONTEXT_HANDLE

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1004]
### Motivation

Prevents having to cast to `*const/mut isize` and makes it consistent with the functions.

say: https://docs.microsoft.com/en-us/windows/win32/api/authz/nf-authz-authzinitializecontextfromsid
If i am not mistaken it will always give you a ` AUTHZ_CLIENT_CONTEXT_HANDLE` at the out parameter `phAuthzClientContext`.
And if so it doesn't make much sense for it to be a neutral `isize`, actually find it weird it's that and not `c_void` though.
Looking at the metadata it looks like it's seens as a `*AUTHZ_CLIENT_CONTEXT_HANDLE`.

### Drawbacks

If it's not actually not always a `&mut/cont AUTHZ_CLIENT_CONTEXT_HANDLE` and some other data can be written in the/some functions then the typing will break that.

### Rationale and alternatives

The current design makes you able to pass any `isize` (in a nutshell any `HANDLE.0`) which makes it "confusing" for no reason.
If it's just a single type, then it's better to just utilize that to make rust do it's thing without extra steps.

### Additional context

Current art is kinda like this:

```rust
    let mut client_context = AUTHZ_CLIENT_CONTEXT_HANDLE::default();
            unsafe {
                AuthzInitializeContextFromSid(
                    0,
                    ...,
                    ...,
                    null_mut(),
                    LUID::default(),
                    null_mut(),
                    &mut client_context.0,
                )
            }
            .ok().unwrap();
```

**Comment by Zerowalker** [comment]
Oh, was looking at the wrong place, probably cause i looked at the type itself (which doesn't exist in Rust),
and it came up in the meta.

Glad i could help.

**Comment by mikebattista** [comment]
Windows.Win32.Security.Authorization.Apis.AuthzInitializeContextFromToken : phAuthzClientContext...IntPtr* => AUTHZ_CLIENT_CONTEXT_HANDLE*
Windows.Win32.Security.Authorization.Apis.AuthzInitializeContextFromSid : phAuthzClientContext...IntPtr* => AUTHZ_CLIENT_CONTEXT_HANDLE*
Windows.Win32.Security.Authorization.Apis.AuthzInitializeContextFromAuthzContext : phNewAuthzClientContext...IntPtr* => AUTHZ_CLIENT_CONTEXT_HANDLE*
Windows.Win32.Security.Authorization.Apis.AuthzInitializeCompoundContext : phCompoundContext...IntPtr* => AUTHZ_CLIENT_CONTEXT_HANDLE*
Windows.Win32.Security.Authorization.Apis.AuthzAddSidsToContext : phNewAuthzClientContext...IntPtr* => AUTHZ_CLIENT_CONTEXT_HANDLE*
