### ISSUE TITLE
Fixed size array parameters decay to pointers

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1006]
For example, `ID3D12GraphicsCommandList::ClearRenderTargetView` is defined as follows in the Windows SDK:

```C++
virtual void STDMETHODCALLTYPE ClearRenderTargetView( 
    _In_  D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView,
    _In_  const FLOAT ColorRGBA[ 4 ],
    _In_  UINT NumRects,
    _In_reads_(NumRects)  const D3D12_RECT *pRects) = 0;
```

Unfortunately, the metadata seems to lose the fact that `ColorRGBA` is in fact a pointer to array of 4 elements:

```C#
unsafe void ClearRenderTargetView([In] D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView, [In][Const] float* ColorRGBA, [In] uint NumRects, [In][Const][NativeArrayInfo(CountParamIndex = 2)] RECT* pRects);
```

**Comment by tannergooding** [comment]
ClangSharp captures this as a string in `NativeTypeName` (which you can see in the `ArrayParameterTest` tests).

ClangSharp will surface the `const float color[4]` as a `ConstantArray: const float[4]` and if we needed/desired surfacing the info another way, it could be done.

`microsoft/win32metadata` is, I believe, quite a bit behind of "current" ClangSharp and there is at least one issue that was introduced a ways back that hasn't been resolved yet: https://github.com/microsoft/win32metadata/issues/498

If this issue is resolved, then it would be much easier to move win32metadata onto the latest version and include any additional fixes necessary (such as tracking the length of such "constant arrays").

**Comment by riverar** [comment]
@tannergooding Thanks a bunch! I didn't realize we were so far behind, will work on getting caught up.

**Comment by tannergooding** [comment]
Thanks! Please feel free to loop me in if any issues crop up. The validation job for dotnet/clangsharp had to be disabled a while back and while I've tried to ensure that things don't regress, its possible something was missed in the past 18 months or so.

**Comment by mikebattista** [comment]
@sotteson1 may have some thoughts on moving clangsharp forward. Last we chatted, I believe there were some challenges there.

**Comment by riverar** [comment]
Fair. Moving forward isn't needed for this issue, I discovered. The NativeTypeName is coming through, we just need more array-related work on that front.

**Comment by sotteson1** [comment]
FYI, I've caught up our project to use 14.0.0-beta3 and I'm working on using 14.0.0-rc1.

**Comment by riverar** [comment]
@sotteson1 Sweet!

**Comment by mikebattista** [comment]
@sotteson1 @chenss3 are we caught up on clangsharp now?

Can this issue and #498 mentioned above be resolved now?

**Comment by kennykerr** [comment]
The parameter is still a pointer in the latest published version.

**Comment by mikebattista** [comment]
My question was if we have the latest tooling now to be able to fix the issues.

**Comment by riverar** [comment]
@mikebattista There's no tooling blocker. `NativeTypeName` is coming through great, we just need to beef up our end 💪

**Comment by mikebattista** [comment]
I've linked several issues related to function pointers in structs only being emitted as IntPtr though the NativeTypeName does have the context about the function pointer.

Is there a general approach we should take to solve all of these NativeTypeName issues or do we need to handle each signature separately?

**Comment by mikebattista** [comment]
The problematic cases seemed to be where the constant size couldn't be determined from the `CppAttributeList` (SAL annotations).

In those cases, we'll fallback to the `NativeTypeName` attribute and add `NativeArrayInfo(CountConst = N)` like below.

```
unsafe void ClearRenderTargetView([In] D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView, [In][Const][NativeArrayInfo(CountConst = 4)] float* ColorRGBA, [In] uint NumRects, [Optional][In][Const][NativeArrayInfo(CountParamIndex = 2)] RECT* pRects);
```
