### ISSUE TITLE
`BCRYPT_HANDLE` is missing and should be convertible

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1011]
Original declarations for BCRYPT handles:

```C++
typedef PVOID BCRYPT_HANDLE;
typedef PVOID BCRYPT_ALG_HANDLE;
typedef PVOID BCRYPT_KEY_HANDLE;
typedef PVOID BCRYPT_HASH_HANDLE;
typedef PVOID BCRYPT_SECRET_HANDLE;
```

The various handles are all convertible to `BCRYPT_HANDLE` so that they can all be used with functions like `BCryptGetProperty` and `BCryptSetProperty`. 

Unfortunately, the `AlsoUsableFor` is not present on these handles and `BCRYPT_HANDLE` is not defined at all. `BCryptGetProperty` for examples is declared as follows:

```C++
_Must_inspect_result_
NTSTATUS
WINAPI
BCryptGetProperty(
    _In_                                        BCRYPT_HANDLE   hObject,
    _In_                                        LPCWSTR pszProperty,
    _Out_writes_bytes_to_opt_(cbOutput, *pcbResult) PUCHAR   pbOutput,
    _In_                                        ULONG   cbOutput,
    _Out_                                       ULONG   *pcbResult,
    _In_                                        ULONG   dwFlags);
```

But the metadata just uses `void*`:

```C#
[DllImport("bcrypt", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern NTSTATUS BCryptGetProperty([In] void* hObject, [In][Const] PWSTR pszProperty, [Optional][Out][MemorySize(BytesParamIndex = 3)] byte* pbOutput, [In] uint cbOutput, [Out] uint* pcbResult, [In] uint dwFlags);
```

This makes using these APIs very difficult as the handles don't even have the same underlying type (`IntPtr` vs `void*`).

**Comment by mikebattista** [comment]
Windows.Win32.Security.Cryptography.BCRYPT_ALG_HANDLE : [RAIIFree(BCryptCloseAlgorithmProvider),InvalidHandleValue(0),NativeTypedef] => [RAIIFree(BCryptCloseAlgorithmProvider),AlsoUsableFor(BCRYPT_HANDLE),InvalidHandleValue(0),NativeTypedef]
Windows.Win32.Security.Cryptography.BCRYPT_KEY_HANDLE : [RAIIFree(BCryptDestroyKey),InvalidHandleValue(0),NativeTypedef] => [RAIIFree(BCryptDestroyKey),AlsoUsableFor(BCRYPT_HANDLE),InvalidHandleValue(0),NativeTypedef]
Windows.Win32.Security.Cryptography.BCRYPT_HASH_HANDLE not found in 1st winmd
Windows.Win32.Security.Cryptography.BCRYPT_SECRET_HANDLE not found in 1st winmd
Windows.Win32.Security.Cryptography.BCRYPT_HANDLE not found in 1st winmd
Windows.Win32.Security.Cryptography.Apis.BCryptGetProperty : hObject...Void* => BCRYPT_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptSetProperty : hObject...Void* => BCRYPT_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptSetProperty : hObject : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptDestroySecret : hSecret...Void* => BCRYPT_SECRET_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptDestroySecret : hSecret : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptSecretAgreement : phAgreedSecret...Void** => BCRYPT_SECRET_HANDLE*
Windows.Win32.Security.Cryptography.Apis.BCryptDeriveKey : hSharedSecret...Void* => BCRYPT_SECRET_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptCreateHash : phHash...Void** => BCRYPT_HASH_HANDLE*
Windows.Win32.Security.Cryptography.Apis.BCryptHashData : hHash...Void* => BCRYPT_HASH_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptHashData : hHash : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptFinishHash : hHash...Void* => BCRYPT_HASH_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptFinishHash : hHash : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptCreateMultiHash : phHash...Void** => BCRYPT_HASH_HANDLE*
Windows.Win32.Security.Cryptography.Apis.BCryptProcessMultiOperations : hObject...Void* => BCRYPT_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptProcessMultiOperations : hObject : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptDuplicateHash : hHash...Void* => BCRYPT_HASH_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptDuplicateHash : phNewHash...Void** => BCRYPT_HASH_HANDLE*
Windows.Win32.Security.Cryptography.Apis.BCryptDestroyHash : hHash...Void* => BCRYPT_HASH_HANDLE
Windows.Win32.Security.Cryptography.Apis.BCryptDestroyHash : hHash : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Apis.BCryptDeriveKeyCapi : hHash...Void* => BCRYPT_HASH_HANDLE
