### ISSUE TITLE
Don't conflate BCrypt and NCrypt

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1012]
These are similar but distinct APIs. Unfortunately in some places the types are a little mixed up. For example, `BCryptEncrypt` expects a `NCRYPT_FLAGS` parameter. This enum also mixes BCrypt and NCrypt flags, which isn't right.

**Comment by kennykerr** [comment]
There are also various flags like `BCRYPT_BLOCK_PADDING` that aren't part of the enum.

**Comment by riverar** [comment]
Not sure _distinct_ is the word I'd use. `ncrypt.h` brings in `bcrypt.h`, shares a bunch of types, and creates a bunch of type aliases between the two. Definitely need some untangling!
