### ISSUE TITLE
ICU functions should be `cdecl`

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/win32metadata#1013]
The ICU functions provided in `Windows.Win32.Globalization` should be `cdecl`, but they are now marked as `winapi`, aka `stdcall`.

**Comment by riverar** [comment]
```cpp
#elif defined(_MSC_VER)
#   define U_EXPORT2 __cdecl
...
U_CAPI UChar32 U_EXPORT2
utf8_nextCharSafeBody(const uint8_t *s, int32_t *pi, int32_t length, UChar32 c, UBool strict);
```

**Comment by mikebattista** [comment]
I see `CallingConvention = CallingConvention.Cdecl` inside the `DllImport` attribute on all these APIs.

Closing out for now. Reactivate if you have more specifics on any requested metadata changes.

**Comment by riverar** [comment]
Believe this was fixed with https://github.com/microsoft/win32metadata/pull/1201
