### ISSUE TITLE
`VARIANT` in wrong namespace?

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1019]
Starting working on https://github.com/microsoft/windows-rs/issues/539 and I find it a little strange that `VARIANT` is defined in `Win32.System.Com` while all of the functions for manipulating this type are in `Win32.System.Ole` - is this intentional?

**Comment by mikebattista** [comment]
There are VARIANT-related functions in COM as well like `VARIANT_UserMarshal`. Where do you recommend they all go? Should these all be COM APIs or OLE APIs?

**Comment by sotteson1** [comment]
If VARIANT goes into the Ole namespace, it will cause some namespace cycles with other namespaces. Maybe all those manipulation functions should go into Com, though.

**Comment by kennykerr** [comment]
Not critical - I'll just close this for now.

**Comment by kennykerr** [comment]
Tried again to fix https://github.com/microsoft/windows-rs/issues/539 but it's really not practical to support when VARIANT and its associated functions aren't in the same namespace. 

Regarding cycles, I've never been able to make that work so I'm less interested in breaking that. 

I'll reopen as @riverar suggested this could be fixed.

**Comment by mikebattista** [comment]
What's the recommendation here?

**Comment by riverar** [comment]
One idea we were kicking around was putting VARIANT and associated structs/functions into a new variant-only namespace (e.g. `Win32.System.Variant`). Think that'll work well?

**Comment by mikebattista** [comment]
Sure if that works for you.

**Comment by mikebattista** [comment]
Does PROPVARIANT belong together with VARIANT?

**Comment by kennykerr** [comment]
Although similar, the structs are independent and `PROPVARIANT` is specific to structured storage.

**Comment by mikebattista** [comment]
Thanks. I'm moving all PROPVARIANT APIs to Windows.Win32.System.Com.StructuredStorage as part of this change. VARIANT APIs will be in Windows.Win32.System.Variant.

**Comment by AArnott** [comment]
The move to a new namespace just hit CsWin32. It's easy to accommodate, but `VARIANT` is the only struct in the new namespace (accompanied by 4 enums), it leaves me wondering why it needs its very own namespace. Seems like the `Foundation` namespace might have been more suitable.

**Comment by mikebattista** [comment]
There are a bunch of methods there as well.

**Comment by AArnott** [comment]
Ah, I hadn't noticed that. Although for CsWin32 that makes no difference since we always generate all methods onto the one `PInvoke` class. So for .NET this is a bit weird, but it's better for other projections, I guess we win some, we lose some. Not a huge deal.

**Comment by kennykerr** [comment]
I think I'll just close this for now - I have a workaround and simply moving these types won't necessarily make the issue less problematic because `Windows.Win32.System.Variant.VARIANT` itself depends on `Windows.Win32.System.Com` and `Windows.Win32.System.Ole` so the web of dependencies between `VARIANT` and `PROPVARIANT` is just the tip of the iceberg.
