### ISSUE TITLE
Consider Changing CombineRgn Return Type to Enum

### ISSUE THREAD

**Issue by lonitra** [microsoft/win32metadata#1024]
**Is your feature request related to a problem? Please describe.**
The current return type of `CombineRgn` is an `int`, which affects code readability since getting a 0 as a return may not immediately signify to the reader that there was an error, and no region was created. To work around this, users could create their own enum type, but even then they would still need to cast their enum type everywhere they want to check the return of `CombineRgn`.

**Describe the solution you'd like**
Have `CombineRgn` return an enum type for readability and cleanliness. Perhaps something like:
```c#
internal enum RegionType : int
    {
        ERROR = 0,
        NULLREGION = 1,
        SIMPLEREGION = 2,
        COMPLEXREGION = 3,
    }
```
This enum type could also be used for the return type of other methods such as `GetClipBox`, `GetRgnBox`, `IntersectClipRect` etc.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Gdi.GDI_REGION_TYPE not found in 1st winmd
Windows.Win32.Graphics.Gdi.Apis.ERROR...System.UInt32 => System.Int32
Windows.Win32.Graphics.Gdi.Apis.NULLREGION not found in 2nd winmd
Windows.Win32.Graphics.Gdi.Apis.SIMPLEREGION not found in 2nd winmd
Windows.Win32.Graphics.Gdi.Apis.COMPLEXREGION not found in 2nd winmd
Windows.Win32.Graphics.Gdi.Apis.RGN_ERROR not found in 2nd winmd
Windows.Win32.Graphics.Gdi.Apis.CombineRgn : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.ExcludeClipRect : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.GetClipBox : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.GetRgnBox : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.IntersectClipRect : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.OffsetClipRgn : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.OffsetRgn : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.SelectClipRgn : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.ExtSelectClipRgn : return...Int32 => GDI_REGION_TYPE
Windows.Win32.Graphics.Gdi.Apis.SetMetaRgn : return...Int32 => GDI_REGION_TYPE

**Comment by mikebattista** [comment]
I left ERROR separate for now and added RGN_ERROR to the enum which was an existing alias for ERROR.

**Comment by mikebattista** [comment]
I'm planning to ship a metadata update later this week so if there are other issues affecting WinForms, let me know.
