### ISSUE TITLE
SetWindowLong argument type mismatch

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/win32metadata#1026]
The SetWindowLong method takes an int dwNewLong, but the enum that is used here is an unsigned int. So calling this method by the method signature produces an error...

```
SetWindowLong(Handle, WINDOW_LONG_PTR_INDEX.GWL_STYLE, (int)(WS_VISIBLE | WS_POPUP));
```

Is this a 32 bit function? - reading the documentation - it's superceded by SetWindowLongPtr for 64bit - but that method isn't generated when requested.

No matter, the argument type here is wrong, it should be uint.

## Context ##
* CsWin32 version: 0.2.10-beta
* Target Framework: net6.0-windows10.0.19041.0
* Active Sln Platform: x64
* Exe Architecture: x64
* Lib Architecture: AnyCpu (this is where my Win32 code resides)

**Comment by mikebattista** [comment]
I guess is the 90% case unsigned or signed? Looking at the [docs](https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-setwindowlonga), other than potentially GWL_USERDATA, all other values appear to be unsigned.

If someone's going to need to cast, I'd rather it be the 10%. As long as it's possible to pass in values in all scenarios, I think we should optimize for the 90% case.

**Comment by Gavin-Williams** [comment]
I know this isn't the way Microsoft can operate - but I say do it the proper way and people can update their code. After all, 90% of historical usage is only 10% of future usage.

**Comment by mikebattista** [comment]
I don't follow. What do you mean by proper way? No change?

**Comment by Gavin-Williams** [comment]
The enum (in the projection) is a uint, the parameter type is a nint - that's the mismatch - the function SetWindowLongPtr should be changed (in the projection) to take a uint in the third parameter. That's a change.

**Comment by elachlan** [comment]
> A corollary here is - what's a 'nint'?

Native signed integer (32-bit in 32-bit platforms, and 64-bit on 64-bit platforms).
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types
https://docs.microsoft.com/en-us/dotnet/api/system.nint?view=xamarin-ios-sdk-12

**Comment by mikebattista** [comment]
The metadata is defined below.

```
[DllImport("USER32", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.0")]
[SupportedArchitecture(Windows.Win32.Interop.Architecture.X64 | Windows.Win32.Interop.Architecture.Arm64)]
public static extern IntPtr SetWindowLongPtrW([In] HWND hWnd, [In] WINDOW_LONG_PTR_INDEX nIndex, [In] IntPtr dwNewLong);
```

The original header is:

```
LONG_PTR SetWindowLongPtrA(
  [in] HWND     hWnd,
  [in] int      nIndex,
  [in] LONG_PTR dwNewLong
);
```

Is IntPtr the right representation in the metadata for LONG_PTR? Is the projection working as expected for parameters of type IntPtr? If we change IntPtr to uint in the metadata, will that have unintended consequences?

**Comment by AArnott** [comment]
`IntPtr` is pointer-sized, so switching it to `uint` would break it on 64-bit. The bug was about `SetWindowLong`, which is 32-bit so we can decide on `int` vs. `uint`. For SetWindowLongPtr we could go between `IntPtr` and `UIntPtr` to match. I don't know if enums are allowed to derive from IntPtr or if that would even make sense. `SetWindowLongPtr` was created because the 3rd arg can be 64-bits long, so that suggests to me that enums are certainly not entirely the solution for it since presumably 32-bits was enough for an enum.

**Comment by Gavin-Williams** [comment]
But it's not a pointer (I see that via this methods absolute C weirdness it might be in some cases?), the whole design here is janky, perfect example of terrible C era API's. As I see it, WINDOW_STYLE is a uint enum and SetWindowLongPtr is just a terribly named method - and should 100% be changed. We don't have to live with the legacy of bad naming. And it should take the enum as a parameter if possible, alternatively, and it's a poor choice, take a uint or uint64.

You could also split the method into 2 or more distinct methods, that more clearly communicate what the method is doing. And Win32 is just missing API's. For example, why doesn't it have a ToggleFullscreen method? And why is WS_POPUP 'code' for fullscreen? It's all very garbled and patchwork.

If you're going to have methods like this, maybe C# needs a new type Mixed64 or something to clearly indicate that the type can be interpreted in different ways - sometimes as a pointer, sometimes as a value.

Fixing this is probably beyond the scope of this project or CsWin32 as well. Maybe we need a new C library, rewrite the whole base layer. We've had to tolerate so many rewrites of .net and modern windows - maybe it's time to give us a Win32 -> Win64 rewrite too and just fix all this stuff.

So frustrating to see API's going backwards like this.

**Comment by AArnott** [comment]
win32metadata and CsWin32 exposes Win32 APIs. They do not rewrite them. This isn't an opportunity to redesign the win32 API, but to expose them as-is. Using an enum where the header files used `int` or `uint` is nearly the extent of what we can do to improve things. Switching out `IntPtr` for `int` is simply a no-go, as that would lead to a process crash because it doesn't match the ABI of the method. Replacing the `IntPtr` with `UIntPtr` or an `IntPtr`-derived enum is a possibility.

**Comment by AArnott** [comment]
@marler8997 Feel free to repeat your question in the CsWin32 discussions tab. Others may be interested in the same thing. The dotnet/pinvoke project *may* be a place for such things, if/when it switches over to CsWin32 projected APIs.
