### ISSUE TITLE
Add enums for IME Constants

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1028]
Some are used by this api:
https://docs.microsoft.com/en-au/windows/win32/api/imm/nf-imm-immgetconversionstatus

All listed here:
https://docs.microsoft.com/en-us/windows/win32/intl/input-method-manager-constants

**Comment by elachlan** [comment]
@mikebattista this is another blocking winforms.

**Comment by elachlan** [comment]
ImmGetCompositionString also has an unnamed parameter that should be an enum. The documentation is terrible. but it maps to GSC_.
https://docs.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immgetcompositionstringa
http://pinvoke.net/default.aspx/imm32.ImmGetCompositionString
https://docs.microsoft.com/en-us/windows/win32/intl/ime-composition-string-values

**Comment by elachlan** [comment]
Winforms also has an enum for these constants:
https://docs.microsoft.com/en-us/windows/win32/intl/input-method-manager-commands

**Comment by mikebattista** [comment]
Thanks. These should be easy to add via enums.json.
