### ISSUE TITLE
MAKEINTRESOURCE integers should be 16-bit not 32-bit

### ISSUE THREAD

**Issue by meowtec** [microsoft/win32metadata#1029]
### Which crate is this about?

windows

### Crate version

0.39

### Summary

`TD_WARNING_ICON` was missing in older version and introduced in v0.39 (REF: https://github.com/microsoft/win32metadata/issues/968), but it seems that the value (`PCWSTR(-1i32 as _)`) is not correct and can cause `STATUS_ACCESS_VIOLATION` error when running.

```
Running `target\debug\message-custom-buttons.exe`
error: process didn't exit successfully: `target\debug\message-custom-buttons.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

Instead, use `PCWSTR(-1i32 as u16 as _)` would work correctly.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\berto\.rustup

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-gnu
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)

### Reproducible example

1. git clone `git@github.com:PolyMeilex/rfd.git`
2. edit https://github.com/PolyMeilex/rfd/blob/master/src/backend/win_cid/message_dialog.rs#L116 and replace `PCWSTR(main_icon_ptr as *const u16)` with `windows::Win32::UI::Controls::TD_WARNING_ICON`
3. cd `examples/message-custom-buttons`
4. cargo run

### Expected behavior

Should show a task dialog

### Actual behavior

error: process didn't exit successfully: `target\debug\message-custom-buttons.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by riverar** [comment]
```
#define IS_INTRESOURCE(_r) ((((ULONG_PTR)(_r)) >> 16) == 0)
#define MAKEINTRESOURCEA(i) ((LPSTR)((ULONG_PTR)((WORD)(i))))
#define MAKEINTRESOURCEW(i) ((LPWSTR)((ULONG_PTR)((WORD)(i))))
```

**Comment by sotteson1** [comment]
I don't agree that MAKEINTRESOURCE values should be 16-bit. They're passed to functions that are expecting a LPCWSTR or LPSTR. But I don't know enough about the rust projection to know why the repro steps failed to compile. It seems like they should have worked.

**Comment by riverar** [comment]
@sotteson1 The MAKEINTRESOURCE macros (see above) cast to WORD before doing additional arithmetic. IS_INTRESOURCE also shifts right 16 bits. Am I missing something?

**Comment by sotteson1** [comment]
The final cast is to a string. They are meant to be used in functions that take a string.

**Comment by sotteson1** [comment]
IS_INTRESOURCE takes a string and sees of the high word is 0. If it is, you know it’s a 16-bit int resource that has been cast to a string to be used in the resource functions.

**Comment by kennykerr** [comment]
I'm not sure this is a metadata bug - the metadata represents this as follows:

```C#
public const PWSTR TD_WARNING_ICON = -1;
```

This is completely invalid but also a fairly accurate representation of what the Windows SDK declares. It may be up to the languages to coerce this properly.

**Comment by riverar** [comment]
When I said we should treat "MAKEINTRESOURCE integers as WORDs" in the original issue, I was referring to the integer input into the macro. Right now, when we scrape `MAKEINTRESOURCE(xxx)`, we treat the xxx as a 32-bit integer before it is natively labeled a PCSTR/PCWSTR. I'm not suggesting we change the string type.

**Comment by kennykerr** [comment]
Makes sense.

**Comment by sotteson1** [comment]
Oh, that makes sense. We should fix that.

**Comment by riverar** [comment]
For curious minds, that `STATUS_ACCESS_VIOLATION` is a result of the integer constant getting sign-extended to fit in a pointer-sized variable/register. That `0xffffffffffffffff` value is then ferried up the stack, eventually entering `user32!FindExistingCursorIcon` where a squirrelly "pointer check" is performed (`val & FFFF FFFF FFFF 0000 != 0`). Our sign-extended value passes this check, so the function happily tries to RtlInitUnicodeString thinking the pointer is valid 💥

**Comment by kennykerr** [comment]
Thanks for the analysis @riverar - in the meantime I have a workaround here: https://github.com/microsoft/windows-rs/pull/2007

**Comment by mikebattista** [comment]
Is the fix here just to cast to ushort below?

https://github.com/microsoft/win32metadata/blob/efe67e99723bb5391fbffc8395338061be141dab/sources/MetadataUtils/ConstantsScraper.cs#L720

Or does the fix need to be plumbed through in more places?

**Comment by riverar** [comment]
@mikebattista That sounds right, let's see if we can do some plumbing work here to get a test wired up.

**Comment by riverar** [comment]
So I've made some changes that now emits the constant as `int16`, example IL:

```
.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.Foundation.PWSTR TD_WARNING_ICON = int16(-1)
```

**Comment by kennykerr** [comment]
Reopening as these constants need to be unsigned to avoid sign extension.
