### ISSUE TITLE
microsoft/cppwin32 was archived -- what's current status?

### ISSUE THREAD

**Issue by Lindurion** [microsoft/win32metadata#1033]
Hey folks, your README here still points to https://github.com/microsoft/cppwin32 as the C++ projection, but it looks like that repo was quietly archived with no explanation.

Even if the answer is transitionally messy, can you update your README to steer someone who wants to call Win32 APIs from a modern C++ application in the right direction?

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/pull/1249#issuecomment-1245700394.
