### ISSUE TITLE
Feature request: No IORING_SQE in Win32_Storage_FileSystem?

### ISSUE THREAD

**Issue by victoryang00** [microsoft/win32metadata#1034]
### Motivation

I'm writing a windows rust IORing lib just like tokio-rs/iouring. I'm considering using windows-rs because this repo is Microsoft maintained. But it seems it lacks some of the APIs like in https://github.com/CarterLi/libwinring/blob/master/include/ioringnt.h. Could you help us by adding IORING_SQE and other missing APIs for IORings?

### Drawbacks

No promising drawbacks.

**Comment by mikebattista** [comment]
This API is not in the Windows SDK so closing out. See https://github.com/microsoft/win32metadata/issues/1034#issuecomment-1208354766 for how to use the official API.
