### ISSUE TITLE
Add COLORREF to CsWin32

### ISSUE THREAD

**Issue by fernandanavamoya** [microsoft/win32metadata#1035]
**Is your feature request related to a problem? Please describe.**
We refer to `COLORREF` many times inside our code therefore it would be very useful if it was defined in CsWin32.

**Describe the solution you'd like**
Add `COLORREF` to CsWin32
- [Link to COLORREF documentation](https://docs.microsoft.com/en-us/windows/win32/gdi/colorref)

**Describe alternatives you've considered**
We've been using our [own COLORREF struct](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/Interop.COLORREF.cs)

**Comment by elachlan** [comment]
@mikebattista Do I just add this to https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/autoTypes.json?

**Comment by elachlan** [comment]
Might as well add [LOGPALETTE](https://docs.microsoft.com/en-us/windows/win32/api/Wingdi/ns-wingdi-logpalette) and [PALETTEENTRY](https://docs.microsoft.com/en-us/previous-versions//dd162769(v=vs.85)) while we are at it.

**Comment by sotteson1** [comment]
> Might as well add [LOGPALETTE](https://docs.microsoft.com/en-us/windows/win32/api/Wingdi/ns-wingdi-logpalette) and [PALETTEENTRY](https://docs.microsoft.com/en-us/previous-versions//dd162769(v=vs.85)) while we are at it.

Both of those structs are already in the metadata.

**Comment by elachlan** [comment]
Thanks, I should have checked ILSpy.
