### ISSUE TITLE
Feature request: sa_family_t and socklen_t types

### ISSUE THREAD

**Issue by Thomasdezeeuw** [microsoft/win32metadata#1041]
### Motivation

We need them in Socket2:
https://github.com/rust-lang/socket2/blob/66690648402e7d6cff33192f353bfe372b7245c9/src/sys/windows.rs#L60-L63. We currently work around it with defining it ourselves.

**Comment by mikebattista** [comment]
```
[NativeTypedef]
public struct socklen_t
{
	public int Value;
}

[NativeTypedef]
public struct sa_family_t
{
	public ushort Value;
}

Windows.Win32.Networking.WinSock.Apis.getnameinfo : SockaddrLength...Int32 => socklen_t
Windows.Win32.Networking.WinSock.Apis.GetNameInfoW : SockaddrLength...Int32 => socklen_t
Windows.Win32.Networking.WinSock.sa_family_t added
Windows.Win32.Networking.WinSock.socklen_t added
```

Is this what you had in mind?

**Comment by Thomasdezeeuw** [comment]
@mikebattista I'm not familiar with the syntax, nor the Windows API, but in case the question was aimed at me, yes `socklen_t` as signed 32 bit integer and `sa_famility_t` as 16 bit unsigned integer is what I would expect (and what Socket2 currently uses).
