### ISSUE TITLE
Update to the 22621 SDK

### ISSUE THREAD

**Issue by plafosse** [microsoft/win32metadata#1049]
The last field `GuardMemcpyFunctionPointer` seems to be missing.

**Comment by riverar** [comment]
@sotteson1 This is new to the 22621 SDK, which appears to already be live on docs/download. 

https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
https://docs.microsoft.com/windows/win32/api/winnt/ns-winnt-image_load_config_directory32
