### ISSUE TITLE
COM interfaces with thiscall methods are not represented correctly in metadata

### ISSUE THREAD

**Issue by weltkante** [microsoft/win32metadata#1053]
The RTF/richedit APIs have a few COM interfaces where _some_ methods are thiscall instead of stdcall (i.e. the underlying IUnknown is using stdcall as usual, but the interface methods don't). Probably a historic mistake that couldn't been fixed due to compatibility so we're stuck with it. Using the interfaces with the wrong calling convention results in crashes.

The interfaces I came across while interop'ing with the RTF APIs are `ITextHost` and `ITextServices` in `textserv.h`, not sure if there are more.

**Comment by elachlan** [comment]
Are we able to tell from the headers or will we need to manually tag each method we come across?

**Comment by weltkante** [comment]
You should be able to tell from the header, but its kind of reversed, interfaces using stdcall are annotated in the headers, so you have to detect the lack of an annotation to differentiate. If thats hard you could also special case by interface name instead of special casing the interface methods maybe?

**Comment by elachlan** [comment]
In win32API, is there just thiscall and stdcall? I know there are a few more in https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.callingconvention?view=net-6.0

Is it safe to assume that if it isn't marked with stdcall that it would be thiscall and not one of the others?

**Comment by weltkante** [comment]
Yes, an interface method in C/C++ not annotated with a modifier should be thiscall by default.
