### ISSUE TITLE
Multiple functions with params with `IN`/`OUT`/`OPTIONAL` have incorrect `[In, Out]` in metadata

### ISSUE THREAD

**Issue by beevvy** [microsoft/win32metadata#1059]
I saw #1039 (fixing #941, cc @sotteson1) in changelog and thought the fix was not wide enough, so I looked into the metadata and found multiple signatures coming from 6 distinct Windows SDK headers that have incorrect `[In, Out]` markings in metadata:

```cs
[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public unsafe delegate void PVIDEO_WIN32K_CALLOUT([In][Out] void* Params);
```
^ `Params` should be `[In]`.

```cs
[DllImport("RPCRT4", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern RPC_STATUS I_RpcNsInterfaceExported([In] uint EntryNameSyntax, [In][Out] ushort* EntryName, [In][Out] RPC_SERVER_INTERFACE* RpcInterfaceInformation);
```
^ `EntryName` and `RpcInterfaceInformation` should be `[In]`.

```cs
[Guid(3284991412u, 28552, 4562, 163, 206, 0, 192, 79, 177, 120, 42)]
[SupportedOSPlatform("windows5.1.2600")]
public interface ISecurityInformation2 : IUnknown
{
	unsafe BOOL IsDaclCanonical([In][Out] ACL* pDacl);

	unsafe HRESULT LookupSids([In] uint cSids, [In][Out] PSID* rgpSids, [Out] IDataObject* ppdo);
}
```
^ `rgpSids` should be `[In]`.

```cs
[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public unsafe delegate HRESULT FNCERTSRVBACKUPGETDYNAMICFILELISTW([In][Out] void* hbc, [In][Out] ushort** ppwszzFileList, [In][Out] uint* pcbSize);
```
^ `hbc` should be `[In]`, `ppwszzFileList` and `pcbSize` should be `[Out]`.

```cs
[DllImport("clfsw32", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern BOOL SetLogFileSizeWithPolicy([In] HANDLE hLog, [In][Out] ulong* pDesiredSize, [In][Out] ulong* pResultingSize);
```
^ `pDesiredSize` should be `[In]`, `pResultingSize` should be `[Out]`.

```cs
[DllImport("clfsw32", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern BOOL FlushLogBuffers([In][Out] void* pvMarshal, [In][Out] OVERLAPPED* pOverlapped);
```
^ `pvMarshal` should be `[In]`, `pOverlapped` should be `[Optional][In][Out]`.

PS. Another set is reported in #911.

**Comment by mikebattista** [comment]
Windows.Win32.Devices.Display.PVIDEO_WIN32K_CALLOUT.Invoke : Params : [In,Out] => [In]
Windows.Win32.Security.Authorization.UI.ISecurityInformation2.IsDaclCanonical : pDacl : [In,Out] => [In]
Windows.Win32.Security.Authorization.UI.ISecurityInformation2.LookupSids : rgpSids : [In,Out] => [In]

**Comment by mikebattista** [comment]
Used the technique from #1039 for a few of these. It didn't work quite so well for other partitions so should manually address the rest. Either the change made no difference or it caused APIs to change that shouldn't have.

**Comment by mikebattista** [comment]
Windows.Win32.Security.Cryptography.Certificates.FNCERTSRVBACKUPGETDYNAMICFILELISTW.Invoke : hbc : [In,Out] => [In]
Windows.Win32.Security.Cryptography.Certificates.FNCERTSRVBACKUPGETDYNAMICFILELISTW.Invoke : pcbSize : [In,Out] => [Out]
Windows.Win32.Security.Cryptography.Certificates.FNCERTSRVBACKUPGETDYNAMICFILELISTW.Invoke : ppwszzFileList : [In,Out] => [Out]
Windows.Win32.Storage.FileSystem.Apis.FlushLogBuffers : pOverlapped : [In,Out] => [In,Optional,Out]
Windows.Win32.Storage.FileSystem.Apis.FlushLogBuffers : pvMarshal : [In,Out] => [In]
Windows.Win32.Storage.FileSystem.Apis.SetLogFileSizeWithPolicy : pDesiredSize : [In,Out] => [In]
Windows.Win32.Storage.FileSystem.Apis.SetLogFileSizeWithPolicy : pResultingSize : [In,Out] => [Out]
Windows.Win32.System.Rpc.Apis.I_RpcNsInterfaceExported : EntryName : [In,Out] => [In]
Windows.Win32.System.Rpc.Apis.I_RpcNsInterfaceExported : RpcInterfaceInformation : [In,Out] => [In]
