### ISSUE TITLE
Consider Updating LOGFONTW

### ISSUE THREAD

**Issue by lonitra** [microsoft/win32metadata#1060]
[`LOGFONTW` docs](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfontw) outline enum-like typed values for certain members of its struct e.g. `lfOutPrecision`,`lfQuality`. It would be nice to update the definition to return an enum type for these members for readability.
For example, with `lfOutPrecision`, something like:
```c#
public enum OUT_PRECIS : byte
{
    DEFAULT = 0,
    STRING = 1,
    CHARACTER = 2,
    STROKE = 3,
    TT = 4,
    DEVICE = 5,
    RASTER = 6,
    TT_ONLY = 7,
    OUTLINE = 8,
    SCREEN_OUTLINE = 9,
    PS_ONLY = 10
}
```

The docs also outline an `LF_FACESIZE`, which indicates the size of `lfFaceName`. Currently, the type of `lfFaceName` has a property `Length` which is essentially the `LF_FACESIZE`, but it would be nice to have this defined as an `internal const` in `LOGFONTW` to be able to reference this without having to first create one i.e. reference this value by calling `LOGFONTW.LF_FACESIZE`.

**Comment by elachlan** [comment]
CC: @AArnott

**Comment by elachlan** [comment]
For `FONT_WEIGHT` its is defined as `LONG  lfWeight`.

The structures CHARFORMAT2W/CHARFORMAT2A have a `WORD wWeight` field. The description says:
> this member is the same as the lfWeight member of the LOGFONT structure. To use this member, set the CFM_WEIGHT flag in the dwMask member.

If I include it, the build fails.

Similar issue with FONTDIFF/IFIMETRICS and their field `USHORT usWinWeight`.

@sotteson1 How do you reconcile that difference?

**Comment by AArnott** [comment]
An enum can only have one size, so if the enum would tend to apply to sites that individually vary in size, we cannot share an enum between them. We could define the enum twice (with names to suggest their length), but I think we usually leave the enum undefined in such cases since it's perhaps not as cut-and-dry that it's a well-defined type.
