### ISSUE TITLE
Consider using `SYS_COLOR_INDEX` enum on `GetSysColor` and `GetSysColorBrush` `nIndex` parameters

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1069]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolorbrush
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsyscolor

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by chenss3** [comment]
@elachlan Is this what you're referencing? I believe `GetSysColor`'s parameter `nIndex` is already of type `SYS_COLOR_INDEX`. `GetSysColorBrush` still needs this update though. Maybe we can update the title to omit `GetSysColor`. 

https://github.com/microsoft/win32metadata/blob/244937798d21a5cae07daf0a952e8917649e86a6/generation/WinSDK/enums.json#L14784-L14938

**Comment by elachlan** [comment]
Yes, I believe so.
