### ISSUE TITLE
Consider adding enums for UI Automation Constants (`UIA_` ) from UIAutomationClient.h

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1074]
Probably should be split into individual enums based on the ranges. I am unsure if that can be done via the autopopulate.
**Enum Values:**
https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-entry-constants

**Functions:**
- https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiaraiseautomationevent
- https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/nf-uiautomationcoreapi-uiaraiseautomationpropertychangedevent

**Structures:**
- https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/ns-uiautomationcoreapi-uiapropertychangedeventargs
- https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcoreapi/ns-uiautomationcoreapi-uiapropertycondition

**Interfaces:**
- https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nn-uiautomationcore-irawelementprovidersimple

Winforms tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by chenss3** [comment]
@mikebattista Is it possible to filter enums other than using prefixes? Or would the best option here just be to manually input the names?

**Comment by elachlan** [comment]
It is possible. You can use regex on both the `value` property under `members` or you can use it in the `autoPopulate` `filter` property.

Example:
https://github.com/microsoft/win32metadata/blob/77059802a630bec1bb25891655fe7228bef3ca66/generation/WinSDK/enums.json#L30058-L30061
