### ISSUE TITLE
`DWebBrowserEvents2` interface missing all methods

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1081]
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa768283(v=vs.85)

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by sotteson1** [comment]
This interface is a pure IDispatch-only interface. The only way to call its "methods" is using IDispatch methods.
