### ISSUE TITLE
Consider adding enums for `IRichEditOleCallback`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1082]
`QueryAcceptData` `reco` parameter
https://docs.microsoft.com/en-us/windows/win32/api/richole/nf-richole-iricheditolecallback-queryacceptdata

`GetDragDropEffect` `grfKeyState` and `pdwEffect` parameters
https://docs.microsoft.com/en-us/windows/win32/api/richole/nf-richole-iricheditolecallback-getdragdropeffect

`grfKeyState` values from winuser.h
```
/*
 * Key State Masks for Mouse Messages
 */
#define MK_LBUTTON          0x0001
#define MK_RBUTTON          0x0002
#define MK_SHIFT            0x0004
#define MK_CONTROL          0x0008
#define MK_MBUTTON          0x0010
#if(_WIN32_WINNT >= 0x0500)
#define MK_XBUTTON1         0x0020
#define MK_XBUTTON2         0x0040
#endif /* _WIN32_WINNT >= 0x0500 */

#endif /* !NOKEYSTATES */
```

Winforms tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by chenss3** [comment]
grfKeyState enum seems to be fixed through #1125
