### ISSUE TITLE
Consider using enums on `OleAuto` `varformat` functions

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1086]
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformat
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatcurrency
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatdatetime
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatfromtokens
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatnumber
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatpercent
- https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-vartokenizeformatstring
- https://docs.microsoft.com/en-us/windows/win32/api/vbinterf/nf-vbinterf-ivbformat-format

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by chenss3** [comment]
Currently working on adding an enum for the flags. 

I'm also looking at in VarFormat there are a set of values for iFirstDay and iFirstWeek. Has WinForms built a custom enum for this? If that's the case, it might make sense to do the same in the metadata since we don't currently have any constants defined in the headers for those values.

**Comment by elachlan** [comment]
Yes, Here you go.

https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.VarFormatFirstDayOfWeek.cs#L9-L19

https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.VarFormatFirstWeekOfYear.cs#L9-L15

**Comment by elachlan** [comment]
@chenss3 can you please also look into ivbformat?
https://docs.microsoft.com/en-us/windows/win32/api/vbinterf/nf-vbinterf-ivbformat-format

**Comment by chenss3** [comment]
@elachlan I also see that [VarFormatPercent ](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varformatcurrency)and other functions use a similar set of values for iIncLead, iUseParens, and iGroup. Do you know if WinForms has also built custom enums for these values?

**Comment by elachlan** [comment]
For that example I suggest creating an enum. Its limited to three separate values, which is perfect for an enum.

As far as what is used by winforms, its just `varformat` and `ivbformat`. I added the rest as a guide for myself to add enums to related methods/structs when I was going to go back through and complete this.
