### ISSUE TITLE
`OleCreateFontIndirect` has incorrect `[in]`/`[out]` parameters

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1089]
https://docs.microsoft.com/en-us/windows/win32/api/olectl/nf-olectl-olecreatefontindirect
```csharp
[DllImport("OLEAUT32", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows5.0")]
public unsafe static extern HRESULT OleCreateFontIndirect([In][Out] FONTDESC* lpFontDesc, [In][Const] Guid* riid, [In][Out] void** lplpvObj);
```

Should be:
```csharp
[DllImport("OLEAUT32", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows5.0")]
public unsafe static extern HRESULT OleCreateFontIndirect([In] FONTDESC* lpFontDesc, [In][Const] Guid* riid, [Out] void** lplpvObj);
```

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468
Related: #1059

**Comment by sotteson1** [comment]
It looks like all of the functions in OleCtl.h need to be updated with proper in/out since none of these have any SAL annotations.

**Comment by elachlan** [comment]
Is that something we do manually? or is the upstream header updated and we pull that in?
