### ISSUE TITLE
Consider adding enum for `DISPID_` constants

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1090]
Should include: MEMBERID_NIL

Used by:
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-funcdesc
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-iolecontrol-onambientpropertychange
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-ipropertynotifysink-onchanged
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-ipropertynotifysink-onrequestedit
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-typeattr
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-vardesc
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-dispparams
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-getidsofnames
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-invoke
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nn-ocidl-iperpropertybrowsing (multiple methods)
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-iprovidemultipleclassinfo-getinfoofindex
- https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-itypeinfo (multiple methods)
- https://docs.microsoft.com/en-us/windows/win32/api/olectl/ns-olectl-ocpfiparams
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.icategorizeproperties.mappropertytocategory?view=visualstudiosdk-2022
- https://docs.microsoft.com/en-us/windows/win32/devnotes/iprovidepropertybuilder-mappropertytobuilder
- https://docs.microsoft.com/en-us/windows/win32/devnotes/iprovidepropertybuilder-executebuilder
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.designer.interfaces.ivsmdperpropertybrowsing.getpropertyattributes?view=visualstudiosdk-2022
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsperpropertybrowsing?view=visualstudiosdk-2022 (multiple methods)

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by elachlan** [comment]
Here is a screenshot of where it is used in winforms. A discussion will need to take place around its usage on `memid` fields and methods, as they might not be closed values.
![image](https://user-images.githubusercontent.com/2433737/187448123-b9f21305-e22b-49e3-b477-eb83a44beb34.png)

**Comment by elachlan** [comment]
@chenss3 I am currently investigating this and OLE enums in general. I will put up a PR hopefully soon.

**Comment by sotteson1** [comment]
DISPID's are open-ended. I don't think these should be in an enum.

**Comment by elachlan** [comment]
@lonitra, winforms will need to use the `DISPID_` constants for DispatchID.

**Comment by elachlan** [comment]
> DISPID's are open-ended. I don't think these should be in an enum.

Closing due to above.
