### ISSUE TITLE
`GetExitCodeThread` should return `NTSTATUS` struct/enum

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1105]
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodethread

Possibly consider changing NTSTATUS to an ENUM based on the `STATUS_` constants?

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by ChrisDenton** [comment]
I don't think the exit code is limited to `NTSTATUS` codes. A thread can exit with any user (or runtime) provided value and as far as I'm aware there's no documentation to suggest it should be an `NTSTATUS` value.

**Comment by elachlan** [comment]
Chris is right, I think this is an open value not a closed value. So it probably shouldn't be limited to an enum. So we should use the existing struct instead. I do believe creating an enum or having the constants in `NTSTATUS` would be helpful.

**Comment by riverar** [comment]
Current definition:
```csharp
public unsafe static extern BOOL GetExitCodeThread([In] HANDLE hThread, [Out] uint* lpExitCode);
```

Docs:
> The GetExitCodeThread function returns a valid error code defined by the application [...]

Doesn't look like there's any work to do here, closing. If you believe this is in error, let me know!

**Comment by elachlan** [comment]
Shouldn't it still use the `NTSTATUS` Struct? It holds the value and **isn't** an enum and would help encapsulate constants.

**Comment by riverar** [comment]
I don't think so, as it would incorrectly communicate to downstream folks that it's restricted to returning NTSTATUS values. The documentation states it's "defined by the application" so not sure there's anything else we can do here. I'm happy to re-open this if you want a second opinion from Microsoft.

See also:
* ExitProcess https://docs.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitprocess
* ExitThread https://docs.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-exitthread
* exit https://docs.microsoft.com/cpp/c-runtime-library/reference/exit-exit-exit?view=msvc-170

**Comment by elachlan** [comment]
Ok, Can we pivot this issue to provide the constants against the NTSTATUS struct or add an NTSTATUS enum instead? 

This is where it is used in winforms:
https://github.com/dotnet/winforms/blob/035b80230d4dee1a713b7f52e7d9b30916ba52e2/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L116-L117

**Comment by riverar** [comment]
Like HRESULT, NTSTATUS has customer and Microsoft defined variants, which makes it unsuitable for an enumeration. That said, _Microsoft-defined_ NTSTATUS values should be in metadata. At a glance, they appear to all be defined in the `Windows.Win32.Foundation` namespace (e.g. `Windows.Win32.Foundation.Apis.STATUS_PENDING`). If metadata is missing any, do open an issue for that!

See also: 
* NTSTATUS specification https://docs.microsoft.com/openspecs/windows_protocols/ms-erref/87fba13e-bf06-450e-83b1-9241dc81e781
* Defining New NTSTATUS Values https://docs.microsoft.com/windows-hardware/drivers/kernel/defining-new-ntstatus-values
* Previous discussion at #136

**Comment by elachlan** [comment]
@riverar I have checked some the generated code in CsWin32 and it looks like we add the constants as static fields. So I am happy to have this issue resolved.
