### ISSUE TITLE
Feature request: Lsa functions should "always?" use LsaHandle

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1106]
### Motivation

Lsa functions that use a "Handle" are always (i think?) going to be an LsaHandle.
Now ordinarily it's the same thing as the HANDLE type, but as the metadata for it seems to exist,
and also identifies the `CloseApi` it feels compelling to utilize it.
https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/autoTypes.json#L523

```json
  {
    "Name": "LsaHandle",
    "ValueType": "IntPtr",
    "CloseApi": "LsaDeregisterLogonProcess",
    "InvalidHandleValues": [ -1, 0 ]
  },
```

Now if possible having LsaHandle `impl Drop` with `LsaDeregisterLogonProcess`, perhaps as an optional feature would be very neat.

Just to bring that to the table:)

### Drawbacks

If the it's not always going to be an "LsaHandle" it might not be a good idea.
Other than that I don't think there is any?

### Rationale and alternatives

It makes use of the available win32metadata to improve safety and simplicity of handling the functions correctly.
Any way to do this with types and similar is something that I feel should be embraced when possible as Rust allows to do so much as long as you provide it with enough information.

### Additional context

It's used sometimes and sometimes not.
This is taken from a post I made at another issue but it wasn't relevant to that itself hence where this issue comes in:

microsoft/windows-rs#1945 
------
hmm looking at these functions i notice that some expects `HANDLE` others `LsaHandle`?
Think that's a metadata issue, where `HANDLE LsaHandle` is treated as `LsaHandle`,
but `PHANDLE LsaHandle` is treated as `HANDLE`?
```
_IRQL_requires_same_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
NTAPI
LsaRegisterLogonProcess (
    _In_ PLSA_STRING LogonProcessName,
    _Out_ PHANDLE LsaHandle,
    _Out_ PLSA_OPERATIONAL_MODE SecurityMode
    );
```
```
_IRQL_requires_same_
_IRQL_requires_max_(PASSIVE_LEVEL)
NTSTATUS
NTAPI
LsaDeregisterLogonProcess (
   _In_ HANDLE LsaHandle
   );
```
though it does say this in emitter.settings.rsp

LsaRegisterLogonProcess::LsaHandle=LsaHandle*

**Comment by mikebattista** [comment]
Windows.Win32.Security.Authentication.Identity.Apis.LsaAddAccountRights : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaClose : ObjectHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaCreateTrustedDomainEx : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaCreateTrustedDomainEx : TrustedDomainHandle...Void** => LSA_HANDLE*
Windows.Win32.Security.Authentication.Identity.Apis.LsaDeleteTrustedDomain : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaDeregisterLogonProcess : LsaHandle...LsaHandle => HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaEnumerateAccountRights : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaEnumerateAccountsWithUserRight : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaEnumerateTrustedDomains : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaEnumerateTrustedDomainsEx : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaLookupNames : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaLookupNames2 : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaLookupSids : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaLookupSids2 : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaOpenPolicy : PolicyHandle...Void** => LSA_HANDLE*
Windows.Win32.Security.Authentication.Identity.Apis.LsaOpenTrustedDomainByName : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaOpenTrustedDomainByName : TrustedDomainHandle...Void** => LSA_HANDLE*
Windows.Win32.Security.Authentication.Identity.Apis.LsaQueryDomainInformationPolicy : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaQueryForestTrustInformation : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaQueryInformationPolicy : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaQueryTrustedDomainInfo : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaQueryTrustedDomainInfoByName : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaRegisterLogonProcess : LsaHandle...LsaHandle* => HANDLE*
Windows.Win32.Security.Authentication.Identity.Apis.LsaRemoveAccountRights : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaRetrievePrivateData : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaSetDomainInformationPolicy : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaSetForestTrustInformation : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaSetInformationPolicy : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaSetTrustedDomainInfoByName : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaSetTrustedDomainInformation : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.Apis.LsaStorePrivateData : PolicyHandle...Void* => LSA_HANDLE
Windows.Win32.Security.Authentication.Identity.LSA_HANDLE added
Windows.Win32.Security.Authentication.Identity.LsaHandle removed
