### ISSUE TITLE
Duplicate functions

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#112]
Functions like `BSTR_UserFree64` and `VARIANT_UserFree64` appear in multiple namespaces. There are a bunch of `BSTR_*` and `VARIANT_*` functions that appear multiple times in various namespaces. They should appear just once in the `Automation` namespace.

**Comment by sotteson1** [comment]
All the duplicated functions should be gone now. I have a test case that is meant to keep this from happening again.
