### ISSUE TITLE
Consider using enum `MONITOR_FROM_FLAGS` on `dwflags` parameter of `MonitorFromWindow`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1123]
It is already used on `MonitorFromRect` and `MonitorFromPoint`.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by chenss3** [comment]
@elachlan It seems that `MonitorFromWindow`'s parameter `dwflags` does already have the type `MONITOR_FROM_FLAGS`. Are you referencing something else? 

https://github.com/microsoft/win32metadata/blob/c6966a1ea5dca4c9e39eb4da11a1a92a9a724c51/generation/WinSDK/enums.json#L10458-L10485

**Comment by elachlan** [comment]
You are correct, it looks like its already added.
