### ISSUE TITLE
Consider using `ADVF`/`DVASPECT`/`DVASPECT2` enums on `IViewObject`/`IViewObject2`/`IOleObject` interface method parameters

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1129]
https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nn-oleidl-iviewobject
https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nn-oleidl-iviewobject2
https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nn-oleidl-ioleobject

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by elachlan** [comment]
@lonitra/@mikebattista
winforms uses `DVASPECT` on:
- https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-iviewobject-draw
- https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-iviewobject2-getextent

But its possible to pass a value from `DVASPECT2`.
> Possible values are taken from the [DVASPECT](https://docs.microsoft.com/en-us/windows/desktop/api/wtypes/ne-wtypes-dvaspect) and [DVASPECT2](https://docs.microsoft.com/en-us/windows/desktop/api/ocidl/ne-ocidl-dvaspect2) enumerations. Note that newer objects and containers that support optimized drawing interfaces support the DVASPECT2 enumeration values. Older objects and containers that do not support optimized drawing interfaces may not support DVASPECT2.

It seems like `DVASPECT2` is an extension of `DVASPECT` values. Can we combine them into a single enum and leave it up to the user to pass the appropriate values?
https://docs.microsoft.com/en-us/windows/win32/api/wtypes/ne-wtypes-dvaspect
https://docs.microsoft.com/en-us/windows/win32/api/ocidl/ne-ocidl-dvaspect2

**Comment by elachlan** [comment]
I should clarify. I still think `DVASPECT` makes sense, since some methods limit their values by that. Its just `DVASPECT2` should probably include the `DVASPECT` values or we add a new enum with the combined values.

**Comment by lonitra** [comment]
> Can we combine them into a single enum and leave it up to the user to pass the appropriate values? 

FWIW, WinForms has values for `DVASPECT`/`DVASPECT2` combined into a single enum.

**Comment by mikebattista** [comment]
We can't have two enums with similarly named members. That will cause issues with some projections like Rust.

Typically in cases like this we'll combine the values into one enum, and sounds like WinForms does that already, so let's go with that.
