### ISSUE TITLE
Metadata needs to report calling convention correctly

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1133]
> Examples of discrepancies where there are no numbers in the .lib in the SDK

Those are likely because those functions aren't `stdcall` at all - many are likely `cdecl`. It would be most helpful if those are reported to the [win32metadata](https://github.com/microsoft/win32metadata) repo since the metadata would need to indicate the calling convention before the Rust project can do anything about it. 

As of now, we just assume all functions are `stdcall` since the metadata doesn't appear to set the [CallingConvention](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.callingconvention?view=net-6.0) field.

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/issues/1985#issuecomment-1227250926_

**Comment by kennykerr** [comment]
Examples include functions like `DtcGetTransactionManagerExW` and `LdapGetLastError` that are `cdecl` rather than `stdcall`. Currently the metadata doesn't appear to capture this information.

**Comment by sotteson1** [comment]
> I checked the latest CI build and it doesn't seem to capture anything to do with calling convention - still reports stdcall/winapi. Was hoping the ClangSharp update would have automagically fixed this. 😜

I just figured out I was feeding ClangSharp something that was forcing everything to be winapi. Now I'm properly seeing cdecl so I can add it to the metadata. One side effect is now methods/delegates previously reported as winapi are stdcall. If I see a stdcall should I report them as winapi, or use stdcall?

**Comment by sotteson1** [comment]
I'm going to leave stdcall functions as winapi to reduce the noise.

**Comment by kennykerr** [comment]
> I'm going to leave stdcall functions as winapi to reduce the noise.

I believe `winapi` implies `stdcall`.

**Comment by sotteson1** [comment]
> > I'm going to leave stdcall functions as winapi to reduce the noise.
> 
> I believe `winapi` implies `stdcall`.

Right. It's weird the enum has both winapi and stdcall.

**Comment by kennykerr** [comment]
Here are the options in ECMA335:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/9845234/187698573-054292bd-f9d3-45c6-96fb-382716074a42.png">

I suspect `winapi` maps to "CallConvPlatformapi" above and basically means the default calling convention for the platform, which is `stdcall` for Windows.
