### ISSUE TITLE
Consider adding enum for `PICTYPE_` constants for use on `PICTDESC`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1143]
- https://docs.microsoft.com/en-us/windows/win32/api/olectl/ns-olectl-pictdesc
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nn-ocidl-ipicturedisp
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nn-ocidl-ipicture
- https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-ipicture-get_type

Note: we **cannot** use it on `IPictureDisp` or `IPicture` because the type field on those are `short` and not `uint`. We will have to reconcile this difference, possibly with a separate enum.

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by elachlan** [comment]
@mikebattista this will require a decision from the team.

**Comment by elachlan** [comment]
@AArnott have you got any ideas on these other uses of `PICTYPE`?

**Comment by AArnott** [comment]
I don't know these APIs well. I only noticed PICTYPE because the latest metadata update broke CsWin32 generation of it (I fixed it there, and you addressed the flags bug too).

I don't know of a precedent in the metadata for enums that are used in different contexts with divergent sizes yet. Maybe we could define the enums multiple times, with the number of bits for each unique size added as a suffix?

**Comment by mikebattista** [comment]
Can we not make this work everywhere somehow by changing the type of the enum to short?

**Comment by elachlan** [comment]
No, I tried it and win32metadata complains because the type doesn't match the method signature.

**Comment by mikebattista** [comment]
Well uint seems clearly wrong since -1 is a valid value in the set, and the majority of the APIs you linked use short. If the metadata tooling didn't complain here, would projections work correctly if the enum were typed as short?

**Comment by elachlan** [comment]
@sotteson1 There was a issue a couple months ago where the datatype differences "broke" the apis for the rust projection. This lead to you adding the type checking on parameters. I think you could answer the question better than I with regards to Mike's question above.

**Comment by AArnott** [comment]
The size of a method parameter or struct field is determined by the type (of enum). So a given enum can only be represented as a particular size. It cannot change based on the method that is using it. In C++, the methods just took `int` or `short` and you passed in constants that were then shoe-horned into the size determined by the parameter type.

So in the metadata we can either:
1. Define the enum once with the more popular size, and avoid using that enum where the size mismatches the required parameter or field length.
2. Define the enum multiple times, with length suffixes in the name to keep them unique, then use the appropriate enum type at each use. This keeps enum convenience everywhere, but the type doesn't interop well across those APIs, so the same enum value may not be applicable to multiple APIs.
3. Define the enum just once, and add an attribute in the metadata where it's used with a mismatches size so the projections can patch up the length in their code gen. This is the most obtuse way to do it for the metadata and projections, but may lead to the best customer experience.

Number 3 deserves some elaboration:
Suppose we have a set of constants that are often used together, and this set is common to several APIs. We would declare an enum for this. Unfortunately, while most of the APIs use 4 bytes to collect these constants, a few use only 2 bytes. The constants all fit within 2 bytes (i.e. all their values are 0xffff or less).
So we define the enum as 4 bytes. And in the APIs where it must only use 2 bytes, we annotate with `[ActualSize(2)]` at the usage site.
The C# projection could then do something like this:

```cs
internal static void SomeMethod(My4ByteEnum options)
{
    SomeMethodExtern((ushort)options);
    [DllImport("kernel32")]
    extern void SomeMethodExtern(ushort options);
}
```

Notice that the API we expose to the user uses the enum, but internally we truncate it to 2 bytes before calling the extern method.
This is simple when we're talking about parameters. It's less simple with struct fields, which might look like this:

```cs
internal struct MyStruct
{
   private ushort _Options;
   internal My4ByteEnum Options
   {
     get => (My4ByteEnum)_Options;
     set => _Options = (ushort)value;
   }
}
```

The above doesn't look too bad, and it works. But by hiding the field and exposing a property, there are some narrow cases that are no longer allowed. For example the user can no longer get the pointer to the field, and a pointer to the property isn't allowed or useful.

**Comment by mikebattista** [comment]
I definitely don't want to define the enum twice as I don't want to deviate from the original constant names and two enums can't have members with the same name.

**Comment by riverar** [comment]
Think I'm missing something, what's wrong with the enum as it stands now? Just fix up `IPictureDisp`/`IPicture`? 

```
public enum PICTYPE
{
	PICTYPE_UNINITIALIZED = -1,
	PICTYPE_NONE,
	PICTYPE_BITMAP,
	PICTYPE_METAFILE,
	PICTYPE_ICON,
	PICTYPE_ENHMETAFILE
}
```

**Comment by mikebattista** [comment]
As part of fixing https://github.com/microsoft/win32metadata/issues/1502, I'm thinking to make this enum `short` and apply it directly to the `short` APIs. The `uint` API can then be decorated with the attribute that allows projections to use the enum in that location if they want.

**Comment by AArnott** [comment]
That sounds great. CsWin32 can create a friendly overload that takes the enum and casts it to the `short` before passing it into the `extern` method.
