### ISSUE TITLE
Add `OLEVERBATTRIB` and `MENU_ITEM_FLAGS` enum to `OLEVERB`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1146]
https://docs.microsoft.com/en-us/windows/win32/api/oleidl/ns-oleidl-oleverb

lVerb can also be mapped to `OLEIVERB_` constants, but this will need to be investigated. As it might be an open value parameter and not closed, which would mean an enum would not be required.

There is a "Cyclical dependent namespaces" issue with `MENU_ITEM_FLAGS`
Windows.Win32.UI.WindowsAndMessaging.MENU_ITEM_FLAGS
Windows.Win32.System.Ole.OLEVERB

Winforms Tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by elachlan** [comment]
@mikebattista, this will require a decision from the team on where `MENU_ITEM_FLAGS` should reside namespace wise.

**Comment by mikebattista** [comment]
MENU_ITEM_FLAGS seems to already be in its natural location. Is this the only usage of it inside the OLE namespace?

**Comment by elachlan** [comment]
I don't know, I just ran into a namespace circular reference issue and wasn't able to resolve it super easily when I tried.
