### ISSUE TITLE
MainAVIHeader.dwReserved is missing fixed array length annotation

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#118]
Metadata defines the field as

```cs
	public uint[] dwReserved;
```

But the native definition is

```cpp
    DWORD		dwReserved[4];
```

This means the metadata doesn't define the accurate size of the struct, among other things.

**Comment by sotteson1** [comment]
This looks right when looking at IL using ILSpy:

```.field public uint32[0...3] dwReserved```
