### ISSUE TITLE
Duplicate constants

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1202]
I thought I'd give #1201 a try and while I see the calling conventions in metadata 🥳 I also see duplicate constants. For example, `CODECAPI_ALLSETTINGS` appears both as a constant inside the `Apis` class and as a `struct` of its own.

I just grabbed the internal Azure build but perhaps that's missing some post processing and I should just wait for the nuget release. Anyway, just wanted to make sure you're aware of this as it prevents me from ingesting this build.

**Comment by sotteson1** [comment]
Hmm, I don't know why we haven't seen this before. The header does define both for some reason.

**Comment by BenJKuhn** [comment]
This seems like a place where, when both are present, we should pick a winner to avoid a name collision.

**Comment by sotteson1** [comment]
> This seems like a place where, when both are present, we should pick a winner to avoid a name collision.

Yep. That's what we'll have to do.

**Comment by AArnott** [comment]
FYI this broke a real scenario. These structs were useful. See #1212.
