### ISSUE TITLE
Missing struct HDWP from WinUser.h

### ISSUE THREAD

**Issue by atynagano** [microsoft/win32metadata#1208]
```cs
namespace Windows.Win32.UI.WindowsAndMessaging;

public static extern IntPtr BeginDeferWindowPos([In] int nNumWindows);

public static extern IntPtr DeferWindowPos(
      [In] IntPtr hWinPosInfo,
      [In] HWND hWnd,
      [In, Optional] HWND hWndInsertAfter,
      [In] int x,
      [In] int y,
      [In] int cx,
      [In] int cy,
      [In] SET_WINDOW_POS_FLAGS uFlags);

public static extern BOOL EndDeferWindowPos([In] IntPtr hWinPosInfo);
```

These `IntPtr` parameters should be `HDWP` struct.

[BeginDeferWindowPos function (winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-begindeferwindowpos)
[DeferWindowPos function (winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-deferwindowpos)
[EndDeferWindowPos function (winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enddeferwindowpos)

**Comment by mikebattista** [comment]
Windows.Win32.UI.Shell.IExplorerBrowser.SetRect : phdwp...IntPtr* => HDWP*
Windows.Win32.UI.WindowsAndMessaging.Apis.BeginDeferWindowPos : return...IntPtr => HDWP
Windows.Win32.UI.WindowsAndMessaging.Apis.DeferWindowPos : hWinPosInfo...IntPtr => HDWP
Windows.Win32.UI.WindowsAndMessaging.Apis.DeferWindowPos : return...IntPtr => HDWP
Windows.Win32.UI.WindowsAndMessaging.Apis.EndDeferWindowPos : hWinPosInfo...IntPtr => HDWP
Windows.Win32.UI.WindowsAndMessaging.HDWP added
