### ISSUE TITLE
Collect more constants under enums

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#121]
There are many `WM_` prefixed constants. Can we collect them under an enum, and then update APIs that deal with Windows messages to take the enum type instead of `int`?

More prefixed constants are similar. Here is a list:

Prefix | Proposed enum name
--|--
`WM_` | `WindowMessage`
`BS_` | `ButtonStyle`
`CBS_`  | `ComboBoxStyle`
`DS_` | `DialogStyle`
`ES_` | `EditControlStyle`
`LBS_` | `ListBoxStyle`
`PBS_` | `ProgressBarStyle`
`SBS_` | `ScrollBarStyle`
`SS_` | `StaticControlStyle`

For all the styles, we might use a "WindowStyle" suffix instead of just "Style".

**Comment by dotMorten** [comment]
> Keep in mind that user-defined window messages need to be supported.

It's a shame the 'partial' keyword isn't supported for enums in C# :(

**Comment by mikebattista** [comment]
Many of these have enums now, but they aren't applied anywhere.

Is there an easy way to figure out where these enums should be applied?

**Comment by weltkante** [comment]
Be careful with `EM_*` constants which are defined incompatibly for RichTextBox and TextBox but use the same prefix (also see #527 for an actual bug in the winmd file regarding this). These constants should go into different enums based on the header in which they are defined.

**Comment by AArnott** [comment]
Given all the "style" constants tend to get bitwise-OR'd together, grouping them under several enums actually makes it harder in C# to do because each one will have to be explicitly cast to `uint` to make C# happy.
If no projection exists that benefits from these being enums without adding tax to actually *using* them, we should probably *undo* what we've already done and close this issue as Won't Fix.

**Comment by AArnott** [comment]
The `WM_` constants represent an open set of values as well. Since enums work best for closed sets of values, we should probably leave the `WM_` constants as constants as well.
