### ISSUE TITLE
`LdapMapErrorToWin32` should return `WIN32_ERROR` and accept `LDAP_RETCODE`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1211]
Instead it returns `uint`.

**Comment by kennykerr** [comment]
I should also be able to pass LDAP error codes like `LDAP_BUSY` (from `LDAP_RETCODE`) but instead it expects `uint` values.

**Comment by elachlan** [comment]
Docs: https://docs.microsoft.com/en-us/windows/win32/api/winldap/nf-winldap-ldapmaperrortowin32

**Comment by elachlan** [comment]
I think the type mismatch between `uint` and `int` is because the win32API isn't consistent. Some of the functions are returning `int` instead of `uint`.
https://docs.microsoft.com/en-us/windows/win32/api/winldap/nf-winldap-ldap_parse_vlv_controlw

**Comment by riverar** [comment]
@elachlan Not quite. LdapMapErrorToWin32 is returning a Win32 error code. `ldap_parse_vlv_controlw` is returning an LDAP error code.

**Comment by mikebattista** [comment]
Windows.Win32.Networking.Ldap.Apis.LdapMapErrorToWin32 : LdapError...UInt32 => LDAP_RETCODE
Windows.Win32.Networking.Ldap.Apis.LdapMapErrorToWin32 : return...UInt32 => WIN32_ERROR
