### ISSUE TITLE
Consider Renaming Constants/Enum Values

### ISSUE THREAD

**Issue by lonitra** [microsoft/win32metadata#1224]
Some constants/enum values defined in the metadata present some redundancies when using them. For example, with `DPI_AWARENESS_CONTEXT` constants, in order to use the `unaware` constant defined in this struct, user would need to call `DPI_AWARENESS_CONTEXT.DPI_AWARENESS_CONTEXT_UNAWARE`. It would be much more concise and cleaner to be able to refer to this constant as just `DPI_AWARENESS_CONTEXT.UNAWARE` and similarly for the other constants.

There are other constants/enum values that have this redundant naming. A few that I am aware of are: `R2_MODE`, `DIB_USAGE`,`OBJ_TYPE`,`ETO_OPTIONS`,`HDC_MAP_MODE`,`FONT_QUALITY` but there could be others that I have not run into.

**Comment by AArnott** [comment]
It's a fair point you raise. However doing so presents a few challenges, primarily around matching documentation and code found elsewhere. There is a lot of value to having the enum value name match the constant in the docs. If we declared `DPI_AWARENESS_CONTEXT.UNAWARE` in the metadata, a search for this wouldn't turn anything up on docs.microsoft.com, or samples or other help sites the way `DPI_AWARENESS_CONTEXT_UNAWARE` would. 

Also, the name of the enum type itself may not appear in all languages. In fact in C where the original .h header files are written, the enum doesn't even exist. So all these enum wrappers around constants are a fabrication designed to make projections a bit easier to consume. 

As I suspect you're working with C#, if the redundancy is getting you down, you can use this:

```cs
using static Windows.Win32.ui.HiDpi.DPI_AWARENESS_CONTEXT;
```

Now you can use `DPI_AWARENESS_CONTEXT_UNAWARE` all by itself, the way C did it.
![image](https://user-images.githubusercontent.com/3548/188745608-ea03bd6d-fdda-4649-b478-75f2686ffc1b.png)

**Comment by mikebattista** [comment]
+1 to Andrew. We can't simplify names in enums for lots of reasons. In addition to Andrew's reasons, projections like Rust project enum members to global constants, and simplifying enum member names will most definitely result in naming conflicts that break these scenarios. It's better to match the documentation and ensure enum member names are unique.

**Comment by lonitra** [comment]
Gotcha, makes total sense. Thank you for the background information on this. (:
