### ISSUE TITLE
Validation For Constants Scraper

### ISSUE THREAD

**Issue by chenss3** [microsoft/win32metadata#1227]
Would be useful to add something to the ConstantsScrapers logic so that it can validate malformed enums and produce the appropriate error message. For example, in a situation where if struct or field have a null and if method or parameter have a null. 

# Example Repro

1. Add a malformed enum with incorrectly formatted uses: 
`      {
        "function": "SHGetPathFromIDListEx",
        "parameter": "uOpts"
      }
`
2. Function is not a valid member. The valid members (interface, method, struct) will be null, and ConstantsScraper continue looking for a null namespace until it throws ArgumentNullException. 
3. The error message the compiler provides is not helpful, and you will waste time debugging going through the aforementioned step.

**Comment by elachlan** [comment]
This would somewhat be solved if we had a json schema, we can then use the schema to validate the JSON.
https://www.newtonsoft.com/json/help/html/JsonSchema.htm

Related: #1226

**Comment by elachlan** [comment]
I think this was fixed by #1228
