### ISSUE TITLE
GetSysColorBrush() should take a SYS_COLOR_INDEX

### ISSUE THREAD

**Issue by Serentty** [microsoft/win32metadata#1239]
The function `GetSysColorBrush()` takes a parameter of type `i32`, and yet the constants meant to be passed to it (such as COLOR_3DFACE) are all of the type `SYS_COLOR_INDEX`. On top of that, the field in `SYS_COLOR_INDEX` is a `u32` instead of an `i32`.

I suppose that when the headers were originally written for C, the implicit conversion between these types made this seamless, but in Rust it is a bit of an annoyance. It seems like the developer needs to do something like this:

```rust
hbrBackground: gdi::GetSysColorBrush(wm::COLOR_3DFACE.0 as _),
```

The same thing applies to a few other functions that in principle take this type, but do not according to the function prototype.

**Comment by kennykerr** [comment]
> The same thing applies to a few other functions that in principle take this type, but do not according to the function prototype.

It may not be obvious what other functions may be affected. Please list them out as that should help to get them all fixed.

**Comment by Serentty** [comment]
The other one I saw was `GetSysColor()`.

**Comment by elachlan** [comment]
`uint` is the default for enums.

@sotteson1 should this have come up as a build failure due to the type change from `int32` to `uint`?
