### ISSUE TITLE
`DWriteCreateFactory` has incorrect parameter type

### ISSUE THREAD

**Issue by chris-steema** [microsoft/win32metadata#1248]
Could I please request an example of how to use DirectWrite? I'm working with a Direct2D project, and although the direct2d sample has been very useful to me it doesn't draw any text. 

Specifically, I have this:
```
fn create_write_factory() -> Result<IUnknown> {
    unsafe { 
        let result = DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, &IDWriteFactory1::IID)?;
       
        Ok(result)
    }
}
```
And would like to return a `Result<IDWriteFactory1>`, but I'm not sure how to cast the `IUnknown`. The `D2D1CreateFactory` called in [the direct2d sample](https://github.com/microsoft/windows-rs/blob/master/crates/samples/direct2d/src/main.rs#L405) makes such a cast unnecessary, as the method is generic and returns ID2D1Factory1 without the need for a cast.

**Comment by kennykerr** [comment]
For the cast workaround, I mean something like this:

```
[dependencies.windows]
version = "0.39"
features = [
    "Win32_Graphics_DirectWrite",
]
```

```rust
use windows::core::*;
use windows::Win32::Graphics::DirectWrite::*;

fn main() -> Result<()> {
    unsafe {
        let factory: IDWriteFactory =
            DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, &IDWriteFactory::IID)?.cast()?;
        let typo = factory.CreateTypography()?;
        println!("feature count: {}", typo.GetFontFeatureCount());
        Ok(())
    }
}
```

Once this metadata issue has been resolved, the trailing `.cast()?` won't be needed.

**Comment by chris-steema** [comment]
That's perfect, thank you.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.DirectWrite.Apis.DWriteCreateFactory : factory...IUnknown* => Void**
