### ISSUE TITLE
GlobalAddAtomW incorrectly attributes its only parameter as [Optional]

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#125]
Per [the docs](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globaladdatomw), there is no hint that the parameter is optional.

Actual

```cs
[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
public unsafe static extern ushort GlobalAddAtomW([Optional][In][Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* lpString);
```

Expected

```cs
[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
public unsafe static extern ushort GlobalAddAtomW([In][Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* lpString);
```

**Comment by sotteson1** [comment]
The headers say it's optional.

```C
WINBASEAPI
ATOM
WINAPI
GlobalAddAtomA(
    _In_opt_ LPCSTR lpString
    );
WINBASEAPI
ATOM
WINAPI
GlobalAddAtomW(
    _In_opt_ LPCWSTR lpString
    );
```

**Comment by AArnott** [comment]
Does it make sense for this parameter to be optional? The function could not possibly perform its operation with a null argument.

How should we handle cases like this?

**Comment by kennykerr** [comment]
I guess it depends what optional means in this case. The string is optional, but some value must still be provided to call the function. That value is used to construct an "atom" even if it is a zero value. So in that sense optional is accurate since you can use this API with a null value and it will succeed.

**Comment by AArnott** [comment]
In that case I guess we'll close. But as there is a difference between an _empty_ string and a `null` pointer, and the docs only talk about passing in strings, I don't know what folks should expect from passing in `null`.
