### ISSUE TITLE
`AddAccessAllowedAce` parameter type

### ISSUE THREAD

**Issue by niluxv** [microsoft/win32metadata#1253]
`AddAccessAllowedAce`, `AddAccessDeniedAce` and friends currently take for `dwAceRevision` and `AccessMask` the DWORD type. Shouldn't these be `ACE_REVISION` and `PROCESS_ACCESS_RIGHTS` types respectively?

(Note: I'm using the Rust language projections)

**Comment by mikebattista** [comment]
Is PROCESS_ACCESS_RIGHTS the right access flags? Or is this API more general purpose to accept other kinds of flags? We have several "access rights" enums for threading, filesystem, etc.

**Comment by mikebattista** [comment]
Ok. I guess which "access rights" enum should we apply here? Or should we leave it open ended as it is?

**Comment by mikebattista** [comment]
GENERIC_ constants are just loose constants right now. For domain specific enums like PROCESS_ACCESS_RIGHTS, THREAD_ACCESS_RIGHTS, etc. they have their own fully qualified versions of those values (like FILE_GENERIC_READ).

**Comment by niluxv** [comment]
Ah, sorry, I was only having my use case in mind, where the ACL was for a process object. Thanks for changing the `dwAceRevision` parameter type. Would it make sense to make the same change for the `dwAceRevision` parameter of `AddAce`, `AddAuditAccessAce`, `AddAuditAccessAceEx`, `AddAuditAccessObjectAce`, `AddResourceAttributeAce` and `AddScopedPolicyIDAce`?

**Comment by mikebattista** [comment]
Windows.Win32.Security.Apis.AddAce : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddAuditAccessAce : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddAuditAccessAceEx : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddAuditAccessObjectAce : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddConditionalAce : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddResourceAttributeAce : dwAceRevision...UInt32 => ACE_REVISION
Windows.Win32.Security.Apis.AddScopedPolicyIDAce : dwAceRevision...UInt32 => ACE_REVISION

**Comment by mikebattista** [comment]
I added ACE_REVISION to I believe the rest of the related APIs. Given the generic use of various access flags for ACCESSMASK, I believe that should remain an open type.
