### ISSUE TITLE
CRT functions mapped to vertdll.dll

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1255]
These are rightly CRT functions, It's odd that they're mapped to vertdll. Though the vcruntime will likely come earlier in linker search order so it's likely not an issue in practice.

https://github.com/microsoft/win32metadata/blob/aed52b8e3b36ef452c62ec08f00c3cb18e7c3d15/generation/WinSDK/libMappings.rsp#L24347-L24349

**Comment by kennykerr** [comment]
Why does this mapping even exist at all? These aren't Windows APIs.
