### ISSUE TITLE
`TrackPopupMenu()` `prcRect` parameter isn't optional

### ISSUE THREAD

**Issue by ryancerium** [microsoft/win32metadata#1259]
The `prcRect` parameter to the `TrackPopupMenu` is documented as optional, and ignored. 
 https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenu#parameters

The metadata appears to only mark it as reserved. 
 https://github.com/marlersoft/win32json/blob/main/api/UI.WindowsAndMessaging.json#L15780

Please add the `optional` annotation to the metadata.

**Comment by kennykerr** [comment]
We could treat the `Reserved` attribute as meaning the same as `Optional`. I wonder if that would suffice, since the original headers only indicate that it is reserved rather than optional.

**Comment by ryancerium** [comment]
For the Rust projection, would passing in `Default::default()` be The Right Thing to do?

**Comment by kennykerr** [comment]
The trouble is that many of the reserved parameters are pointers are `Default` is not implemented for pointers so we'd have to produce additional types so we may as well use `Option`. Of course, `Option` implements `Default` so you can still use that if you prefer: 

https://github.com/microsoft/windows-rs/pull/2039/commits/62287d2213dde4b775da2380d4fa41edb07ee483

**Comment by mikebattista** [comment]
Windows.Win32.UI.WindowsAndMessaging.Apis.TrackPopupMenu : prcRect : [Const,In,Reserved] => [Const,Optional,Reserved]

**Comment by mikebattista** [comment]
Is it expected that In is removed when Optional is added?

**Comment by kennykerr** [comment]
Parameters should always be in or out. And I don't think we need both Optional and Reserved. That doesn't make sense.

**Comment by mikebattista** [comment]
Windows.Win32.UI.WindowsAndMessaging.Apis.TrackPopupMenu : prcRect : [Const,In,Reserved] => [Const,In,Optional]
