### ISSUE TITLE
Bug: couldn't call QueryDisplayConfig except QDC_DATABASE_CURRENT, with 0.40.0

### ISSUE THREAD

**Issue by topia** [microsoft/win32metadata#1260]
### Which crate is this about?

windows

### Crate version

0.40.0

### Summary

I don't know that this is an issue by win32metadata, or by windows-rs, or by design.

By [its definition](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-querydisplayconfig), QueryDisplayConfig's last parameter must be `NULL` for `QDC_DATABASE_CURRENT`, but must not be `NULL`  otherwise.

Current win32metadata (checked with 32.0.17-preview), it defined as `[Out] DISPLAYCONFIG_TOPOLOGY_ID* currentTopologyId`.
without microsoft/windows-rs#1939, I called the function with `null_mut()`. but for now, I don't know how I can call it.
I found I can call it with `#[allow(deref_nullptr)] &mut *null_mut::<DISPLAYCONFIG_TOPOLOGY_ID>()` while writing this issue. Is this the correct way?

I saw the conditional is used in [its definition](https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/WinUser.h#L13145-L13147), but I don't believe win32metadata can utilize it.

Could you help me? I want to know a workaround and/or the long-term solution for that.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  D:\data\depot\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-linux-android
aarch64-unknown-linux-gnu
nvptx64-nvidia-cuda
wasm32-unknown-emscripten
wasm32-unknown-unknown
wasm32-wasi
x86_64-apple-darwin
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)

### Reproducible example

```rust
use std::ptr::null_mut;
use windows::core::HRESULT;
use windows::Win32::Devices::Display::{DISPLAYCONFIG_MODE_INFO, DISPLAYCONFIG_PATH_INFO, GetDisplayConfigBufferSizes, QueryDisplayConfig};
use windows::Win32::Foundation::{ERROR_INSUFFICIENT_BUFFER, ERROR_SUCCESS, WIN32_ERROR};
use windows::Win32::Graphics::Gdi::QDC_ONLY_ACTIVE_PATHS;

pub fn main() -> windows::core::Result<()> {
    let flags = QDC_ONLY_ACTIVE_PATHS;
    loop {
        let mut num_path_array_elements = u32::MAX;
        let mut num_mode_info_array_elements = u32::MAX;
        let ret: WIN32_ERROR = unsafe {
            std::mem::transmute(GetDisplayConfigBufferSizes(
                flags,
                &mut num_path_array_elements,
                &mut num_mode_info_array_elements,
            ))
        };
        if ret != ERROR_SUCCESS {
            break Err(HRESULT::from(ret).into());
        }
        let mut paths =
            Vec::<DISPLAYCONFIG_PATH_INFO>::with_capacity(num_path_array_elements as usize);
        let mut modes =
            Vec::<DISPLAYCONFIG_MODE_INFO>::with_capacity(num_mode_info_array_elements as usize);
        let ret: WIN32_ERROR = unsafe {
            std::mem::transmute(QueryDisplayConfig(
                flags,
                &mut num_path_array_elements,
                paths.as_mut_ptr(),
                &mut num_mode_info_array_elements,
                modes.as_mut_ptr(),
                null_mut(),  // this line
            ))
        };
        if ret == ERROR_INSUFFICIENT_BUFFER {
            continue;
        } else if ret != ERROR_SUCCESS {
            break Err(HRESULT::from(ret).into());
        }
        unsafe {
            paths.set_len(num_path_array_elements as usize);
            modes.set_len(num_mode_info_array_elements as usize);
        }
        for path in paths {
            println!("path_info: {:?}", path.flags)
        }
        for mode in modes {
            println!("mode_info: {:?}: {:?}", mode.id, mode.infoType)
        }
        break Ok(());
    }
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.40"
features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
]
```

### Expected behavior

Can compile and run correctly.

### Actual behavior

failed to compile with expected `&mut DISPLAYCONFIG_TOPOLOGY_ID`, found *-ptr error.

### Additional comments

By the way, using ref over pointer is an awesome change. Thank you for your work and I'm migrating it happily.

**Comment by kennykerr** [comment]
Yes, I think I'll have to remove the pointer to reference conversion in Rust as these sorts of metadata bugs are pretty widespread.

**Comment by kennykerr** [comment]
As of https://github.com/microsoft/windows-rs/pull/2036 you can now once again call this API and pass a null pointer. I'll leave this issue to deal with the SAL parsing bugs.
