### ISSUE TITLE
IBackgroundCopyJobHttpOptions.GetClientCertificate has conflicting attributes

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1263]
The `ppCertHashBlob` parameter has both `NativeArrayInfo(CountConst = 20)` which, at least to me, implies that the caller must provide a fixed size buffer of 20 elements and `FreeWith("CoTaskMemFree")` which implies that the caller must *not* provide a buffer at all and instead provide a pointer that will receive the address of a buffer allocated by the callee.

**Comment by mikebattista** [comment]
The docs say use CoTaskMemFree to free the blob, so that part seems correct. The header also has the below annotation.

```
        virtual HRESULT STDMETHODCALLTYPE GetClientCertificate( 
            /* [ref][out] */ __RPC__out BG_CERT_STORE_LOCATION *pStoreLocation,
            /* [ref][out] */ __RPC__deref_out_opt LPWSTR *pStoreName,
            /* [ref][size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(20) byte **ppCertHashBlob,
            /* [ref][out] */ __RPC__deref_out_opt LPWSTR *pSubjectName) = 0;
```

Is this a bug in the original header?

**Comment by kennykerr** [comment]
Yes, the RPC annotation is either incorrect or only intended for RPC, as languages cannot do anything with this information.

**Comment by mikebattista** [comment]
Windows.Win32.Networking.BackgroundIntelligentTransferService.IBackgroundCopyJobHttpOptions.GetClientCertificate : ppCertHashBlob : [FreeWith(CoTaskMemFree),NativeArrayInfo(CountConst=20),Out] => [FreeWith(CoTaskMemFree),Out]
