### ISSUE TITLE
`IWbemServices::ExecQuery` flags are hard to use

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1265]
The API flags are meant to be combined and should be unsigned but the API expects a signed value and the flags themselves are typed as `WBEM_GENERIC_FLAG_TYPE` while the API expects `int`.

**Comment by mikebattista** [comment]
What's the recommended change here? Add flags to the enum and update the API parameter to accept the enum?

**Comment by kennykerr** [comment]
Yep the flags are already grouped in an enum. The enum just needs the `flags` attribute and then the API parameter needs to use the enum type rather than a primitive type.

**Comment by mikebattista** [comment]
Windows.Win32.System.Wmi.IWbemServices.ExecQuery : lFlags...Int32 => WBEM_GENERIC_FLAG_TYPE
Windows.Win32.System.Wmi.WBEM_GENERIC_FLAG_TYPE :  => [Flags]
Windows.Win32.System.Wmi.WBEM_GENERIC_FLAG_TYPE.value__...System.Int32 => System.UInt32
