### ISSUE TITLE
`PICTYPE` is _not_ a flags enum. 

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1269]
I think this is wrong. `PICTYPE` is _not_ a flags enum. From the headers:

```c
/////////////////////////////////////////////////////////////////////////////
// PICTDESC structure

#define PICTYPE_UNINITIALIZED (-1)
#define PICTYPE_NONE            0
#define PICTYPE_BITMAP          1
#define PICTYPE_METAFILE        2
#define PICTYPE_ICON            3
#ifdef _WIN32
#define PICTYPE_ENHMETAFILE     4
#endif
```

We can see these aren't bit-aware constants. They increment by one and they use -1 as a value.

_Originally posted by @AArnott in https://github.com/microsoft/win32metadata/pull/1198#discussion_r977061535_

**Comment by AArnott** [comment]
@elachlan can you fix this please?

**Comment by elachlan** [comment]
Building now.

**Comment by elachlan** [comment]
The underlying type has `uint` as its type. Should we change back to that from `int`?

**Comment by AArnott** [comment]
It should be `int` I think, given it uses `-1` as a value. But when I look at the v33 metadata, it looks like it's already `int`:

```
.class public auto ansi sealed Windows.Win32.System.Ole.PICTYPE
	extends [netstandard]System.Enum
{
	.custom instance void [netstandard]System.FlagsAttribute::.ctor() = (
		01 00 00 00
	)
	// Fields
	.field public specialname rtspecialname int32 value__
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_UNINITIALIZED = int32(-1)
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_NONE = int32(0)
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_BITMAP = int32(1)
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_METAFILE = int32(2)
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_ICON = int32(3)
	.field public static literal valuetype [Windows.Win32.winmd]Windows.Win32.System.Ole.PICTYPE PICTYPE_ENHMETAFILE = int32(4)

} // end of class Windows.Win32.System.Ole.PICTYPE
```

**Comment by elachlan** [comment]
Enum is currently `int`, but `PICTDESC` has it defined as `UINT picType`. It being `int` shouldn't break anything right?

**Comment by AArnott** [comment]
int and uint have exactly the same size and handling contract. It's just how the processor will interpret them, so yes you can switch them without breaking stuff. That said, I see `PICTDESC.picType` defined as `PICTYPE` rather than `int` or `uint`, so it should inherit the `int` type that the enum already uses.
