### ISSUE TITLE
IUIAutomation6 using invalid types in methods

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#127]
`IUIAutomation6` has method parameters that are TypeRefs to nonexistent nested types, `IUIAutomation6.ConnectionRecoveryBehaviorOptions` and `IUIAutomation6.CoalesceEventsOptions`.

The two types exist, but at namespace scope, not as nested types. @sotteson1 believes the scraper is getting confused in UIAutomationClient.h when it encounters the `enum` keyword in a method parameter list.

**Comment by marler8997** [comment]
Just FYI, I ran into this issue today.

**Comment by kennykerr** [comment]
Any chance we can fix this? Bogus type signatures like this are a challenge to deal with.
