### ISSUE TITLE
Missing COLE_DEFAULT_PRINCIPAL, COLE_DEFAULT_AUTHINFO constants

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1271]
Originally posted in https://github.com/microsoft/windows-rs/issues/2055.

Missing constants
```
#define	COLE_DEFAULT_PRINCIPAL	( ( OLECHAR * )( INT_PTR  )-1 )
#define	COLE_DEFAULT_AUTHINFO	( ( void * )( INT_PTR  )-1 )
```

**Comment by AArnott** [comment]
These would look like:

```cs
    unsafe static char* COLE_DEFAULT_PRINCIPAL = (char*) -1;
    unsafe static void* COLE_DEFAULT_AUTHINFO = (void*) -1;
```

Assuming the OLECHAR should be considered 16-bit.

**Comment by mikebattista** [comment]
I did my best to define these.

I believe COLE_DEFAULT_PRINCIPAL is correct and aligns with the expected type in the API (PWSTR).

Less confident about COLE_DEFAULT_AUTHINFO (void*). I tried various combinations of definitions and most wouldn't make it to the winmd.
