### ISSUE TITLE
Add `GLOBAL_ALLOC_FLAGS` enum to `OleDuplicateData`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1281]
https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-oleduplicatedata

**Comment by mikebattista** [comment]
Windows.Win32.System.Ole.Apis.OleDuplicateData : uiFlags...UInt32 => GLOBAL_ALLOC_FLAGS
