### ISSUE TITLE
`ReleaseStgMedium` `pmedium` parameter should possibly not be marked `[In]`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1282]
https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-releasestgmedium

From winforms interop code:
```csharp
// Even though the windows headers indicate that STGMEDIUM is input only this is not true,
// ReleaseStgMedium will clear the fields it released. It is important for classic marshaling
// to *NOT* mark the argument as input parameter because otherwise .NET will not transfer
// ownership of the COM pointers correctly. This defeats the purpose of calling this method.
```
https://github.com/dotnet/winforms/blob/452377436df51bf010a5ac0832c9f66a81e9fceb/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.ReleaseStgMedium.cs

Current output from ILSpy
```csharp
[DllImport("OLE32.dll", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows5.0")]
public unsafe static extern void ReleaseStgMedium([In] STGMEDIUM* param0);
```

**Comment by elachlan** [comment]
@AArnott is this something that metadata has to handle or CsWin32 (based on if marshaling is enabled)?

**Comment by AArnott** [comment]
This should be fixed in the metadata. It will likely impact all projections.

**Comment by mikebattista** [comment]
So we just need to remove [In] here?

**Comment by elachlan** [comment]
I am not sure. Is it [in]/[out] or no attributes?

**Comment by mikebattista** [comment]
We could add `[Out]` if that will result in what you want.

**Comment by elachlan** [comment]
I think removing it should work base on how winforms does it.

**Comment by mikebattista** [comment]
I think we need some combination of [in]/[out] on all APIs in the metadata. Would [in]/[out] solve the problem?

**Comment by elachlan** [comment]
This is what is in winforms. I think the PInvoke changes the values of the passed in object and the removal of the attribute is so that it doesn't do that. You essentially don't want to receive the object back with cleared values. I think `[in][out]` would do that and break it for winforms.
```csharp
[DllImport(Libraries.Ole32, ExactSpelling = true)]
public static extern void ReleaseStgMedium(ref STGMEDIUM pmedium);
```

CC: @JeremyKuhne

**Comment by AArnott** [comment]
From the WinForms comment it sounds to me like the Win32 API changes the arg, and the caller needs to observe this. So in fact this is an `[In, Out]` parameter, despite what the headers may say. Applying both (that is, *adding* `[Out]` to the existing parameter) will lead CsWin32 to emit a `ref` parameter, which matches what WinForms has today.

**Comment by JeremyKuhne** [comment]
Yeah, this needs to be `[In, Out]`

**Comment by mikebattista** [comment]
Windows.Win32.System.Ole.Apis.ReleaseStgMedium : param0 : [In] => [In,Out]
