### ISSUE TITLE
DeleteObject should take HGDIOBJ instead of IntPtr

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#129]
Can we have metadata that describes how HGDIOBJ is related to its "derived types"? If so, I can emulate polymorphism the same way System.Reflection.Metadata does for its structs.

For example: HBITMAP, HBRUSH, etc could have an attribute pointing to `HGDIOBJ` as their "base type".
Ideally the attributes could appear on both the base and derived types, otherwise I will have to scan all types and attributes to build up a map before starting any code generation.

**Comment by sotteson1** [comment]
This was fixed a while ago and I missed updating this issue.
