### ISSUE TITLE
IDropSource::[QueryContinueDrag|GiveFeedback] needs PreserveSig treatment

### ISSUE THREAD

**Issue by littleBugHunter** [microsoft/win32metadata#1291]
IDropSource::[QueryContinueDrag|GiveFeedback] methods can return alternative success codes and appear to meet criteria for PreserveSig.
Currently it is impossible to implement a working IDropSource in rust, as the DragDrop Operation never finishes with DRAGDROP_S_DROP or DRAGDROP_S_CANCEL
See:
https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-querycontinuedrag
https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-givefeedback

**Comment by mikebattista** [comment]
Windows.Win32.System.Ole.IDropSource.GiveFeedback :  => [PreserveSig]
Windows.Win32.System.Ole.IDropSource.QueryContinueDrag :  => [PreserveSig]
