### ISSUE TITLE
Bug: `EVT_HANDLE` is treated as an `isize` in the `Win32_System_EventLog` API

### ISSUE THREAD

**Issue by Soul85** [microsoft/win32metadata#1292]
### Which crate is this about?

windows

### Crate version

0.42

### Summary

All of the methods residing in the `Win32_System_EventLog` API expect and return `isize` instead of `EVT_HANDLE`. This means various `HANDLE` helper methods (such as `is_invalid`) are unavailable.

As a side note, `EventLog` constants are referred to as `i32` meaning it requires a rather ugly `EvtQueryChannelPath.0 as u32` to use them.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\user\\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)

### Reproducible example

```rust
use windows::{Win32::{System::EventLog::{EvtQuery, EvtQueryChannelPath, EvtClose}}, w};

fn main() {
    unsafe {
        // hQuery is isize. First parameter of EvtQuery is intended to be the session (also an isize)
        let hQuery = EvtQuery(0isize, w!("Security"), w!("Event/System[EventID=4624]"), EvtQueryChannelPath.0 as u32);
        EvtClose(hQuery);
    }
}
```

### Crate manifest

```toml
windows = { version = "0.42", features = ["Win32_Foundation", "Win32_Security", "Win32_System_EventLog"] }
```

### Expected behavior

`hQuery` should result in an `EVT_HANDLE` type.

### Actual behavior

`hQuery` currently results in as `isize`.

### Additional comments

This may very well be a `win32-metadata` issue realistically however I am not sure.

**Comment by mikebattista** [comment]
Windows.Win32.System.EventLog.Apis.EvtArchiveExportedLog : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtCancel : Object...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtClearLog : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtClose : Object...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtCreateBookmark : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtCreateRenderContext : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtExportLog : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtFormatMessage : Event...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtFormatMessage : PublisherMetadata...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetChannelConfigProperty : ChannelConfig...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetEventInfo : Event...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetEventMetadataProperty : EventMetadata...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetLogInfo : Log...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetPublisherMetadataProperty : PublisherMetadata...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtGetQueryInfo : QueryOrSubscription...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtNext : ResultSet...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtNextChannelPath : ChannelEnum...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtNextEventMetadata : EventMetadataEnum...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtNextEventMetadata : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtNextPublisherId : PublisherEnum...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenChannelConfig : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenChannelConfig : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenChannelEnum : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenChannelEnum : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenEventMetadataEnum : PublisherMetadata...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenEventMetadataEnum : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenLog : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenLog : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenPublisherEnum : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenPublisherEnum : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenPublisherMetadata : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenPublisherMetadata : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtOpenSession : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtQuery : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtQuery : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtRender : Context...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtRender : Fragment...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSaveChannelConfig : ChannelConfig...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSeek : Bookmark...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSeek : ResultSet...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSetChannelConfigProperty : ChannelConfig...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSubscribe : Bookmark...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSubscribe : return...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtSubscribe : Session...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtUpdateBookmark : Bookmark...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.Apis.EvtUpdateBookmark : Event...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.EVT_CHANNEL_REFERENCE_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_EXPORTLOG_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_FORMAT_MESSAGE_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_HANDLE added
Windows.Win32.System.EventLog.EVT_OPEN_LOG_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_QUERY_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_RENDER_CONTEXT_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_RENDER_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_RPC_LOGIN_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_SEEK_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_SUBSCRIBE_CALLBACK.Invoke : Event...IntPtr => EVT_HANDLE
Windows.Win32.System.EventLog.EVT_SUBSCRIBE_FLAGS.value__...System.Int32 => System.UInt32
Windows.Win32.System.EventLog.EVT_VARIANT._Anonymous_e__Union.EvtHandleVal...System.IntPtr => Windows.Win32.System.EventLog.EVT_HANDLE
