### ISSUE TITLE
`SetSecurityInfo` return type `WIN32_ERROR`

### ISSUE THREAD

**Issue by niluxv** [microsoft/win32metadata#1298]
`SetSecurityInfo`, `SetNamedSecurityInfoA` and `SetNamedSecurityInfoW` (and probably many other function in `AclAPI.h`) should have return type `WIN32_ERROR` instead of `DWORD` I think.

(The `Get` versions already seem to have this return type; at least from looking at the [`windows-rs` API documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Security/Authorization/fn.GetSecurityInfo.html).)

**Comment by mikebattista** [comment]
Windows.Win32.Security.Authorization.Apis.BuildSecurityDescriptorA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.BuildSecurityDescriptorW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.FreeInheritedFromArray : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetAuditedPermissionsFromAclA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetAuditedPermissionsFromAclW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetEffectiveRightsFromAclA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetEffectiveRightsFromAclW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetExplicitEntriesFromAclA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetExplicitEntriesFromAclW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetInheritanceSourceA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetInheritanceSourceW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.LookupSecurityDescriptorPartsA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.LookupSecurityDescriptorPartsW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.SetEntriesInAclA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.SetEntriesInAclW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.SetNamedSecurityInfoA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.SetNamedSecurityInfoW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.SetSecurityInfo : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.TreeResetNamedSecurityInfoA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.TreeResetNamedSecurityInfoW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.TreeSetNamedSecurityInfoA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.TreeSetNamedSecurityInfoW : return...UInt32 => WIN32_ERROR
