### ISSUE TITLE
OFNOTIFY metadata should be unified

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1299]
Currently we have:

``` C#
[SupportedArchitecture(Architecture.X64 | Architecture.Arm64)]
public struct OFNOTIFYW
{
	public NMHDR hdr;
	public unsafe OPENFILENAMEW* lpOFN;
	public PWSTR pszFile;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
[SupportedArchitecture(Windows.Win32.Interop.Architecture.X86)]
public struct OFNOTIFYW
{
	public NMHDR hdr;
	public unsafe OPENFILENAMEW* lpOFN;
	public PWSTR pszFile;
}

public struct NMHDR
{
	public HWND hwndFrom;
	public UIntPtr idFrom;
	public uint code;
}
```

Packing of 1 doesn't actually change the layout as there are no field gaps on 32 bit. Same goes for `OFNOTIFYA`, `OFNOTIFYEXA`, and `OFNOTIFYEXW`. This is preventing Windows Forms from consuming this type (through CSWin32) for our build (which is `AnyCPU`).

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/issues/1300#issuecomment-1468967300.
