### ISSUE TITLE
MessageBoxA/MessageBoxW

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#130]
This function's last parameter is of type `uint` in metadata but all of the constants developers are meant to use with it, like `MB_OK` and `MB_HELP` are signed `int` constants. This make it rather tedious to use. It would also be helpful if these constants were rolled into an unsigned "flags" enum as you've done for APIs like `CreateFileA`.

Not a high priority as this API is pretty old but may be worth considering.

**Comment by sotteson1** [comment]
This APIs are now using a MB_FLAGS enum.
