### ISSUE TITLE
OPENFILENAME structs should be unified

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1300]
Related to #1299. Packing of 1 for this struct does not change its layout and having two definitions prevents consuming it in Windows Forms which is `AnyCPU`.

Currently:

``` C#
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[SupportedArchitecture(Windows.Win32.Interop.Architecture.X86)]
public struct OPENFILENAMEW
{
	public uint lStructSize;
	public HWND hwndOwner;
	public HINSTANCE hInstance;
	[Const]
	public PWSTR lpstrFilter;
	public PWSTR lpstrCustomFilter;
	public uint nMaxCustFilter;
	public uint nFilterIndex;
	public PWSTR lpstrFile;
	public uint nMaxFile;
	public PWSTR lpstrFileTitle;
	public uint nMaxFileTitle;
	[Const]
	public PWSTR lpstrInitialDir;
	[Const]
	public PWSTR lpstrTitle;
	public OPEN_FILENAME_FLAGS Flags;                                  // 32 bit
	public ushort nFileOffset;
	public ushort nFileExtension;
	[Const]
	public PWSTR lpstrDefExt;
	public LPARAM lCustData;
	public LPOFNHOOKPROC lpfnHook;
	[Const]
	public PWSTR lpTemplateName;
	public unsafe void* pvReserved;
	public uint dwReserved;
	public OPEN_FILENAME_FLAGS_EX FlagsEx;                            // 32 bit
}
```

**Comment by mikebattista** [comment]
Related issue https://github.com/microsoft/win32metadata/issues/613.

**Comment by mikebattista** [comment]
@AaronRobinsonMSFT @tannergooding @AArnott @sotteson1 do you have any concerns with unifying the structs here? Is this safe to do for all projections? #613 has some related changes we made in this space.

@sotteson1 any advice for the best way to make this change if we agree it's the right thing to do?

**Comment by AArnott** [comment]
Also related to #1299, in that it seems the fix for one (if any) can be applied to both.

**Comment by AArnott** [comment]
@sotteson1's fix for #613 was to drop Pack=4 from x86 struct definitions before unifying, which allowed more structs to be seen as AnyCPU compatible. That makes sense if the CLR (and other languages) all default to Pack=4 on x86 when it isn't specified.

But if that was a good change (above), then I wonder how we can get away with _also_ dropping Pack=1, since that would suggest that Pack=1 and Pack=4 on x86 are equivalent. Are they?

I think we need to consider arm32, arm64, x64, and x86, etc. When we remove the Pack attribute, we need to know that every projection on that architecture will Do The Right Thing in the absence of the explicit Pack annotation.

**Comment by JeremyKuhne** [comment]
Natural packing for the Windows headers is [type aligned up to 8 bytes ](https://devblogs.microsoft.com/oldnewthing/20090422-00/?p=18493). Pack=1 and Pack=4 can be equivalent to the default _in some cases_. This either needs to be evaluated manually struct by struct or it needs to be programmatically determined. @tannergooding, does something like this already exist in ClangSharp?

**Comment by kennykerr** [comment]
This is similar to #380 that was never resolved.

**Comment by tannergooding** [comment]
`Pack=1` does change the layout here because it impacts the layout for `struct S { byte x; OPENFILENAMEW y; }`

For x86, when it is `Pack=1` then `y` exists at `offset 1`. However, for x64 where it has "natural packing" (in this case 8), then it will instead be at `offset 8`

**Comment by tannergooding** [comment]
I just gave a more concrete example on #380 as well, but will paste below for convenience.

The following [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:39,endLineNumber:26,positionColumn:39,positionLineNumber:26,selectionStartColumn:39,selectionStartLineNumber:26,startColumn:39,startLineNumber:26),source:'%23include+%3CWindows.h%3E%0A%23include+%3Cpshpack4.h%3E%0A%0Astruct+MINIDUMP_INCLUDE_MODULE_CALLBACK1+%7B%0A++++ULONG64+BaseOfImage%3B%0A%7D%3B%0A%0A%23include+%3Cpoppack.h%3E%0A%0Astruct+MINIDUMP_INCLUDE_MODULE_CALLBACK2+%7B%0A++++ULONG64+BaseOfImage%3B%0A%7D%3B%0A%0Astruct+Test1+%7B%0A+++BYTE+x%3B%0A+++MINIDUMP_INCLUDE_MODULE_CALLBACK1+y%3B%0A%7D%3B%0A%0Astruct+Test2+%7B%0A+++BYTE+x%3B%0A+++MINIDUMP_INCLUDE_MODULE_CALLBACK2+y%3B%0A%7D%3B%0A%0Aunsigned+M1()+%7B+return+offsetof(Test1,+y)%3B+%7D%0A%0Aunsigned+M2()+%7B+return+offsetof(Test2,+y)%3B+%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:34.24298014045191,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x64+msvc+v19.latest+(Editor+%231)',t:'0')),k:41.26329658304439,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x64+msvc+v19.latest',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),k:24.49372327650371,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) example gives a more concrete visualization of this.

That is the following code:
```cpp
#include <Windows.h>
#include <pshpack4.h>

struct MINIDUMP_INCLUDE_MODULE_CALLBACK1 {
    ULONG64 BaseOfImage;
};

#include <poppack.h>

struct MINIDUMP_INCLUDE_MODULE_CALLBACK2 {
    ULONG64 BaseOfImage;
};

struct Test1 {
   BYTE x;
   MINIDUMP_INCLUDE_MODULE_CALLBACK1 y;
};

struct Test2 {
   BYTE x;
   MINIDUMP_INCLUDE_MODULE_CALLBACK2 y;
};

unsigned M1() { return offsetof(Test1, y); }

unsigned M2() { return offsetof(Test2, y); }
```

Gives you:
```asm
unsigned int M1(void) PROC ; M1
  mov eax, 4
  ret 0
unsigned int M1(void) ENDP ; M1

unsigned int M2(void) PROC ; M2
  mov eax, 8
  ret 0
unsigned int M2(void) ENDP ; M2
```

**Comment by AArnott** [comment]
Thanks for responding, @tannergooding.

It sounds like you're pointing out that the `[Pack]` attribute might be important, not for the struct used alone, but just in case it appears as a field in some other struct, in which case it might be critical to proper memory layout. Is that right?

That would make sense then as to why most folks see that it doesn't matter, yet in the general case we must assume that it does. IMO our projections shouldn't make assumptions about how the structs will be used. It would be a very difficult thing to discover if CsWin32 (or the metadata) left out the Pack=1 attribute, and the generated struct usually worked, but sometimes didn't. And when it didn't, the bug would come back to the projection or the metadata for leaving that crucial detail out.

I can't think of a better solution to this than for CsWin32 to continue to refuse to declare this struct in AnyCPU compilations, and if specific cases (like WinForms) know they'll never use the struct in a field of another struct, then they can copy and paste the declaration from a CPU-specific config of their compilation into AnyCPU, at which point they own it and the risk from overriding the general guidance.

Does that sound right?

**Comment by tannergooding** [comment]
> It sounds like you're pointing out that the [Pack] attribute might be important, not for the struct used alone, but just in case it appears as a field in some other struct, in which case it might be critical to proper memory layout. Is that right?

Right. Packing is always relevant because it impacts many scenarios beyond just the fields that appear in the struct itself.

> IMO our projections shouldn't make assumptions about how the structs will be used.

Right. We need to ensure that `microsoft/win32metadata` in particular accurately exposes the metadata so that any downstream tools and/or languages can generate correct code, regardless of how that code is being used.

> I can't think of a better solution to this than for CsWin32 to continue to refuse to declare this struct in AnyCPU compilations

I tend to agree. Given the per platform differences, it would've been "more ideal" if the windows headers declared these "per architecture" and then picked the "right one" via some `typedef`. It actually does this in some cases such as having `typedef struct _ARM64_NT_CONTEXT` as defined for all platforms and then `typedef _ARM64_NT_CONTEXT CONTEXT` specifically for Arm64. However, it doesn't do this "everywhere" nor is it consistent about it across architectures.

**Comment by tannergooding** [comment]
TerraFX.Interop.Windows "gets around this" by manually declaring some helpers and other bits to abstract these differences. But that's then non-standard when it comes to such structs and it is a library specific convenience feature instead.

**Comment by mikebattista** [comment]
So is this and #1299 a Won't Fix?
