### ISSUE TITLE
CDN_* defines not in metadata

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1301]
These are used by Windows Forms to support old style dialogs.

https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/commdlg.h#L380-L393

**Comment by elachlan** [comment]
Related winforms PR: https://github.com/dotnet/winforms/pull/7933
