### ISSUE TITLE
TS_DEFAULT_SELECTION / TF_DEFAULT_SELECTION defines not in metadata

### ISSUE THREAD

**Issue by ekicyou** [microsoft/win32metadata#1303]
Constants used in [ITextStoreAnchor::GetSelection](https://learn.microsoft.com/en-us/windows/win32/api/textstor/nf-textstor-itextstoreanchor-getselection)

https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/TextStor.idl#L127

https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/msctf.idl#L956

**Comment by mikebattista** [comment]
Windows.Win32.UI.TextServices.Apis.TF_DEFAULT_SELECTION added
