### ISSUE TITLE
No enumeration generated for DXGI_USAGE?

### ISSUE THREAD

**Issue by atcarter714** [microsoft/win32metadata#1306]
No enumeration type seems to get generated for [DXGI_USAGE](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-usage) for me, I had to manually define my own C# enum for it because it seems to be omitted for some reason.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_BACK_BUFFER removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_DISCARD_ON_PRESENT removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_READ_ONLY removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_RENDER_TARGET_OUTPUT removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_SHADER_INPUT removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_SHARED removed
Windows.Win32.Graphics.Dxgi.Apis.DXGI_USAGE_UNORDERED_ACCESS removed
Windows.Win32.Graphics.Dxgi.DXGI_SWAP_CHAIN_DESC.BufferUsage...System.UInt32 => Windows.Win32.Graphics.Dxgi.DXGI_USAGE
Windows.Win32.Graphics.Dxgi.DXGI_SWAP_CHAIN_DESC1.BufferUsage...System.UInt32 => Windows.Win32.Graphics.Dxgi.DXGI_USAGE
Windows.Win32.Graphics.Dxgi.DXGI_USAGE added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_BACK_BUFFER added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_DISCARD_ON_PRESENT added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_READ_ONLY added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_RENDER_TARGET_OUTPUT added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_SHADER_INPUT added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_SHARED added
Windows.Win32.Graphics.Dxgi.DXGI_USAGE.DXGI_USAGE_UNORDERED_ACCESS added
Windows.Win32.Graphics.Dxgi.IDXGIDevice.CreateSurface : Usage...UInt32 => DXGI_USAGE
Windows.Win32.Graphics.Dxgi.IDXGIResource.GetUsage : pUsage...UInt32* => DXGI_USAGE*

**Comment by atcarter714** [comment]
@mikebattista If I'm understanding that correctly, you've removed any "loose" DXGI_USAGE_xxx values from the definitions and now it should generate proper enums in C# and languages which support some kind of enum construct? Not 100% sure what I'm reading here but it looks like it was dumping those identifiers in `Windows.Win32.Graphics.Dxgi.Apis` instead of building an enum for them in the correct place?

**Comment by mikebattista** [comment]
That's right. The constants were already scanned and emitted just not packaged into a friendly enum. If you add the constants to NativeMethods.txt today, C#/Win32 would generate them for you. Once the enum is in place, just asking for a function that depends on the enum will pull in the enum as well.

**Comment by atcarter714** [comment]
> That's right. The constants were already scanned and emitted just not packaged into a friendly enum. If you add the constants to NativeMethods.txt today, C#/Win32 would generate them for you. Once the enum is in place, just asking for a function that depends on the enum will pull in the enum as well.

Roger that, sir, got it!

I appreciate the quick response/fix to the issue and think this whole project is the most noble of efforts! Really enjoying exploring this, the benefits of WinMD and CsWin32 and utilizing DirectX in C# 11 code 😊
