### ISSUE TITLE
OpenProcess lost its enum parameter types

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#131]
It previously expected a `ProcessAccessRights` enum and now expects an `uint`.

**Comment by sotteson1** [comment]
10.0.19041.5-preview.5

**Comment by rgl** [comment]
@sotteson1, can the released versions have a git tag in the repository? that would make things easier to correlate between this source and the nuget package.

**Comment by kennykerr** [comment]
We use GitHub Releases for cppwinrt. They work great.
