### ISSUE TITLE
Missing error codes in WIN32_ERROR enum.

### ISSUE THREAD

**Issue by ArakawaHenri** [microsoft/win32metadata#1311]
## Actual behavior

The generated WIN32_ERROR enum is missing some error codes.

## Expected behavior

An enum containing [complete enumerated Win32 Error Codes](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes).

## Repro steps

For example, trying to determine whether the program is packaged:

1. `NativeMethods.txt` content:
```
GetCurrentPackageFullName
```

2. CSharp Code:

```
uint length = 0;

bool IsPackaged = PInvoke.GetCurrentPackageFullName(ref length, null) != Windows.Win32.Foundation.WIN32_ERROR.APPMODEL_ERROR_NO_PACKAGE;
```

But it seems that there isn't APPMODEL_ERROR_NO_PACKAGE (15700) in WIN32_ERROR:
![1](https://user-images.githubusercontent.com/17510335/195274317-52c6efa8-3361-4ffd-a24d-def4bef8dbd2.jpg)

### Context

- CsWin32 version: `0.2.63-beta`
- Target Framework: `net6.0-windows10.0.22621.0`

**Comment by elachlan** [comment]
API Reference: https://learn.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefullname

Should the `WIN32_ERROR` enum include `APPMODEL_ERROR_*` constants then?

Another issue is `WIN32_ERROR` is `uint` whereas the return type on `GetCurrentPackageFullName` is `long`.

**Comment by ArakawaHenri** [comment]
I think it should be included, as they are listed on [official docs](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--12000-15999-).
It seems that the generated code defines the type of the return value of the GetCurrentPackageFullName function as WIN32_ERROR, so that it may return a value that does not exist in the enumeration.
![](https://user-images.githubusercontent.com/17510335/195981838-3ae5cd94-d0b7-4ba5-8842-fd2bd98c1e65.png)
BTW, GetCurrentPackageFullName does return an Error Code as long, according to Microsoft's documentation. But the Error Code should be uint (GetLastError returns DWORD). I don't think there's anything we can do about this, since it's Microsoft's fault, and this doesn't seem to cause any problems, the type conversion happens automatically.
