### ISSUE TITLE
When to ignore out parameters based on return value?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1312]
In https://github.com/microsoft/CsWin32/issues/468, @alexrp aptly points out that CsWin32 is generating invalid code in its friendly overloads because it interprets the out parameters before returning, without regard to the return value of the extern method. Nowhere in the metadata does it say what the docs say, which is that the out parameters are undefined and should be disregarded when the method returns false. 

*Maybe* we could get away just assuming in the generated friendly overload that a bool-returning method fails when it returns false, but that sounds too broad to be correct in all cases.
What I'm thinking instead is the metadata could be annotated manually (via rsp file) to indicate when methods that return a type that isn't well documented as an error (bool, int that isn't HRESULT, etc) to indicate which value is an 'error' such that its out parameters should not be marshalled or otherwise interpreted.

Thoughts?

**Comment by kennykerr** [comment]
Generally, marshallers need to zero out the memory for out parameters before making the call so that the values are predictable even when the callee fails to initialize the memory.

**Comment by kennykerr** [comment]
Yep, there are a lot of cases where you need to be very careful. In C++/WinRT for example, I always zero out the memory for out parameters (because some callees do bad things with uninitialized memory) and even then, I don't assume the value is initialized unless the call is assured to have succeeded. But WinRT is far more predictable than Win32... 🤷‍♂️

**Comment by AArnott** [comment]
Thanks for more background and info. 
I don't think clearing memory used for out parameters before the call absolves me of the responsibility to ignore the out parameter after the call in an error condition though. Consider the CreatePipe doc:

> If CreatePipe fails, the contents of the output parameters are indeterminate. No assumptions should be made about their contents in this event.

That suggests to me that `CreatePipe` may in fact have mucked with the out params even in the failure case, but that I should assume it's garbage. To honor that, I'll have to recognize what failure looks like. And to @KalleOlaviNiemitalo's point, I need to know which functions behave in this way.
So in particular I need to know when a function's output parameters _should_ be ignored, based on its return value.

Functions may fail without this requirement, and those are outside the scope of this. It's only the functions and specific return values where the special consideration is required that needs to be labeled.

**Comment by AArnott** [comment]
How about a parameter attribute that matches against the return value to indicate whether to consider the output value?
I don't know if matching via allow or disallow list would be better. So for example:

```cs
BOOL CreatePipe([Out, IgnoreIfReturn(0)] HANDLE* hReadPipe, [Out, IgnoreIfReturn(0)] HANDLE* hWritePipe, [In, Optional] SECURITY_ATTRIBUTES* lpPipeAttributes, uint nSize)
```

This seems simple enough. But as some methods may have multiple error values, either offering a range or multiple error values may be better for general applicability. And/or allow `IgnoreUnlessReturn` attributes as well to flip it to require a specific result to indicate success.
Note the attributes are per parameter to handle @KalleOlaviNiemitalo's case.

**Comment by mikebattista** [comment]
> There are functions that store the required buffer length and return an error, if the provided buffer is too small. Like [RegQueryInfoKeyW](https://learn.microsoft.com/windows/win32/api/winreg/nf-winreg-regqueryinfokeyw) (returns ERROR_MORE_DATA) or [GetSystemCpuSetInformation](https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-getsystemcpusetinformation) (returns FALSE and sets ERROR_INSUFFICIENT_BUFFER as the last error). Perhaps the output parameters of these could have an attribute saying "this output is valid if the error code is as follows".

What about these examples? How would those be decorated?

**Comment by AArnott** [comment]
Both of those APIs probably don't need any attribution at all, as at least my reading of the docs suggest that the value of the output parameters is _always_ defined. Contrast this with `CreatePipe` which documents that the value of the output parameter may be *undefined* based on the return value. It's the undefined ones that are in desperate need of these attributes.

**Comment by mikebattista** [comment]
For `IgnoreIfReturn` I'm modeling it after `Constant` and `InvalidHandleValue`.

The type of the return value will be string like `Constant` to support arbitrary types. You'll need to infer the type from the context (return type in this case) like you do with `Constant`.

To declare multiple values, add multiple instances of the attribute like with `InvalidHandleValue`.
