### ISSUE TITLE
OpenPrinter is not being generated with a link to docs (or any XML docs)

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#1313]
The generated code has no XML docs, but it should at least have a link to the Microsoft docs page for the API:

```cs
        [DllImport("WINSPOOL", ExactSpelling = true, EntryPoint = "OpenPrinterW")]
        [DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
        internal static extern unsafe bool OpenPrinter(PWSTR pPrinterName, HANDLE*phPrinter, [Optional] PRINTER_DEFAULTSW*pDefault);
```

## Repro steps

1. `NativeMethods.txt` content:
```
OpenPrinter
```

### Context

- CsWin32 version: 0.4.422-beta
- Target Framework: net48
- `LangVersion`: 9

**Comment by mikebattista** [comment]
These will have the `[Documentation]` attribute with a link to the docs.

**Comment by mikebattista** [comment]
They're also now included in the Win32Docs package that C#/Win32 uses to populate its docs.
