### ISSUE TITLE
Remove `D3DCOMPILER_DLL` constant

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1317]
Just noticed the odd namespace placement of these similar constants. Is that intentional?

<img width="535" alt="image" src="https://user-images.githubusercontent.com/9845234/196277435-0b376ae1-95c3-4d63-a675-217ca8a8b02b.png">

**Comment by mikebattista** [comment]
@damyanp which namespace should these all live in?

**Comment by damyanp** [comment]
They should all be under the Direct3D.Fxc namespace.

**Comment by mikebattista** [comment]
So _A and _W are scraped from the headers while the unqualified version is manually defined and in the wrong namespace. Do we want this manual definition? Does it work correctly today if you pass it into an API that expects the _A version for example?

**Comment by damyanp** [comment]
The values of these defines are only intended to be passed in to LoadLibrary.  The UNICODE define picks the unsuffixed version:

```c++
// Current name of the DLL shipped in the same SDK as this header.
#define D3DCOMPILER_DLL_W L"d3dcompiler_47.dll"
#define D3DCOMPILER_DLL_A "d3dcompiler_47.dll"

// Current HLSL compiler version.
#define D3D_COMPILER_VERSION 47

#ifdef UNICODE
    #define D3DCOMPILER_DLL D3DCOMPILER_DLL_W 
#else
    #define D3DCOMPILER_DLL D3DCOMPILER_DLL_A
#endif
```

How have we been dealing with the other A/W suffixes?  eg OutputDebugString/OutputDebugStringW/OutputDebugStringA in other places in the metadata?  I expect we should follow whatever is done for these.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Hlsl.Apis.D3DCOMPILER_DLL => Windows.Win32.Graphics.Direct3D.Fxc.Apis.D3DCOMPILER_DLL

**Comment by mikebattista** [comment]
Turns out the manual definition was in fact unnecessary and removing it allowed the constant to naturally be scraped and placed in the right namespace. This is how other similar constants are handled.

**Comment by kennykerr** [comment]
The latest version has a new `D3DCOMPILER_DLL` constant. Just as we have no `CreateFile` function but instead have the actual `CreateFileA` and `CreateFileW` functions, it seems we should only have the `D3DCOMPILER_DLL_A` and `D3DCOMPILER_DLL_W` constants and not the redundant and `#ifdef UNICODE`-specific `D3DCOMPILER_DLL`.

**Comment by mikebattista** [comment]
The constant existed previously, we just changed the namespace with this bug. We can remove it if it's unnecessary.

**Comment by kennykerr** [comment]
Yep, just catching up. 😋 I didn't think of the inconsistency of its existing at all until I saw them all in the same namespace.
