### ISSUE TITLE
Incorrect field types in some structs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#132]
The fields of the `VBS_BASIC_ENCLAVE_SYSCALL_PAGE` struct should simply be delegates but are instead pointers to delegates. A delegate already implies a function pointer so this ends up being a pointer to a function pointer.

**Comment by kennykerr** [comment]
Any chance you can have a look at this soon? It's come up a few times as the affected APIs are completely unusable.

**Comment by sotteson1** [comment]
Sure, I'll see what I can do. ClangSharp gets confused when callbacks are defined without also being a pointer, so I'll have to figure out a way to get around it.
