### ISSUE TITLE
RegGetValue parameter refinements

### ISSUE THREAD

**Issue by fgimian** [microsoft/win32metadata#1324]
Hey again,

The [RegGetValueW](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluew) and [RegGetValueA](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluea) functions have a few little oddities at present.

1. I think that `pdwType` should be represented as `REG_VALUE_TYPE`, currently this returns a `u32` in Rust which is not ideal
2. The `dwFlags` parameter is correctly marked as `RRF_RT`, however, the following are not part of that enum: `RRF_NOEXPAND`, `RRF_SUBKEY_WOW6432KEY`, `RRF_SUBKEY_WOW6464KEY`, `RRF_ZEROONFAILURE` which may be used to set specific bits for this parameter according to the docs.  I also see `RRF_WOW64_MASK` defined but that's not mentioned on the page for `RegGetValue` so I'm not sure if this should also be a member.

The result of the current implementation means I have to do the following in Rust:

```rust
        // Get a value.
        let mut value_type = 0u32;
        let mut value_size = 0u32;
        let error = RegGetValueW(
            key,
            None,
            value_name,
            RRF_RT_ANY | RRF_RT(RRF_NOEXPAND),
            Some(&mut value_type),
            None,
            Some(&mut value_size),
        );
        if error != ERROR_SUCCESS {
            eprintln!("Could not get value");
            return;
        }

        match REG_VALUE_TYPE(value_type) {
            REG_SZ => {
        ...
```

Cheers
Fotis

**Comment by mikebattista** [comment]
Windows.Win32.System.Registry.Apis.RegGetValueA : dwFlags...RRF_RT => REG_ROUTINE_FLAGS
Windows.Win32.System.Registry.Apis.RegGetValueA : pdwType...UInt32* => REG_VALUE_TYPE*
Windows.Win32.System.Registry.Apis.RegGetValueW : dwFlags...RRF_RT => REG_ROUTINE_FLAGS
Windows.Win32.System.Registry.Apis.RegGetValueW : pdwType...UInt32* => REG_VALUE_TYPE*
Windows.Win32.System.Registry.Apis.RRF_NOEXPAND removed
Windows.Win32.System.Registry.Apis.RRF_SUBKEY_WOW6432KEY removed
Windows.Win32.System.Registry.Apis.RRF_SUBKEY_WOW6464KEY removed
Windows.Win32.System.Registry.Apis.RRF_WOW64_MASK removed
Windows.Win32.System.Registry.Apis.RRF_ZEROONFAILURE removed
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_NOEXPAND added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_ANY added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_DWORD added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_QWORD added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_BINARY added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_DWORD added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_EXPAND_SZ added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_MULTI_SZ added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_NONE added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_QWORD added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_SZ added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_SUBKEY_WOW6432KEY added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_SUBKEY_WOW6464KEY added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_WOW64_MASK added
Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_ZEROONFAILURE added
Windows.Win32.System.Registry.RRF_RT removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_ANY removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_DWORD removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_QWORD removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_BINARY removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_DWORD removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_EXPAND_SZ removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_MULTI_SZ removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_NONE removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_QWORD removed
Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_SZ removed

**Comment by fgimian** [comment]
> Windows.Win32.System.Registry.Apis.RegGetValueA : dwFlags...RRF_RT => REG_ROUTINE_FLAGS Windows.Win32.System.Registry.Apis.RegGetValueA : pdwType...UInt32* => REG_VALUE_TYPE* Windows.Win32.System.Registry.Apis.RegGetValueW : dwFlags...RRF_RT => REG_ROUTINE_FLAGS Windows.Win32.System.Registry.Apis.RegGetValueW : pdwType...UInt32* => REG_VALUE_TYPE* Windows.Win32.System.Registry.Apis.RRF_NOEXPAND removed Windows.Win32.System.Registry.Apis.RRF_SUBKEY_WOW6432KEY removed Windows.Win32.System.Registry.Apis.RRF_SUBKEY_WOW6464KEY removed Windows.Win32.System.Registry.Apis.RRF_WOW64_MASK removed Windows.Win32.System.Registry.Apis.RRF_ZEROONFAILURE removed Windows.Win32.System.Registry.REG_ROUTINE_FLAGS added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_NOEXPAND added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_ANY added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_DWORD added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_QWORD added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_BINARY added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_DWORD added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_EXPAND_SZ added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_MULTI_SZ added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_NONE added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_QWORD added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_RT_REG_SZ added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_SUBKEY_WOW6432KEY added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_SUBKEY_WOW6464KEY added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_WOW64_MASK added Windows.Win32.System.Registry.REG_ROUTINE_FLAGS.RRF_ZEROONFAILURE added Windows.Win32.System.Registry.RRF_RT removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_ANY removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_DWORD removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_QWORD removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_BINARY removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_DWORD removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_EXPAND_SZ removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_MULTI_SZ removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_NONE removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_QWORD removed Windows.Win32.System.Registry.RRF_RT.RRF_RT_REG_SZ removed

Beautiful, the new naming is much clearer too, thanks a lot!
