### ISSUE TITLE
IPersistFile.Load parameter dwMode should be STGM instead of DWORD?

### ISSUE THREAD

**Issue by fgimian** [microsoft/win32metadata#1326]
Hey there, as per [the docs](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-ipersistfile-load), `dwMode` should be a member of the STGM enumeration.

At present, this is defined as a plain `DWORD` which results in Rust code like this:

```rust
        persist_file.Load(path, STGM_READ.0)?;
```

Thanks heaps
Fotis

**Comment by mikebattista** [comment]
Windows.Win32.System.Com.IPersistFile.Load : dwMode...UInt32 => STGM

**Comment by fgimian** [comment]
> Windows.Win32.System.Com.IPersistFile.Load : dwMode...UInt32 => STGM

Thanks so much Mike! 😄
