### ISSUE TITLE
Performance counter errors use incorrect underlying type

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1328]
The error codes are meant to be a superset of `WIN32_ERROR` and unsigned:

https://learn.microsoft.com/en-us/windows/win32/perfctrs/pdh-error-codes

Yet, the constants in metadata are all signed values. I'm not suggesting we add them to `WIN32_ERROR`, but can we make them unsigned?

Then the corresponding functions that return such error codes (`PDH_FUNCTION`/`PDH_STATUS`) should also return an unsigned integer to match.

**Comment by mikebattista** [comment]
Windows.Win32.System.Performance.Apis.PDH_ACCESS_DENIED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_ASYNC_QUERY_TIMEOUT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_BINARY_LOG_CORRUPT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CALC_NEGATIVE_DENOMINATOR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CALC_NEGATIVE_TIMEBASE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CALC_NEGATIVE_VALUE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CANNOT_CONNECT_MACHINE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CANNOT_CONNECT_WMI_SERVER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CANNOT_READ_NAME_STRINGS...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CANNOT_SET_DEFAULT_REALTIME_DATASOURCE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_COUNTER_ALREADY_IN_QUERY...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_BAD_COUNTERNAME...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_INVALID_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_ITEM_NOT_VALIDATED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NEW_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NO_COUNTER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NO_COUNTERNAME...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NO_INSTANCE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NO_MACHINE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_NO_OBJECT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_CSTATUS_VALID_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_DATA_SOURCE_IS_LOG_FILE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_DATA_SOURCE_IS_REAL_TIME...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_DIALOG_CANCELLED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_END_OF_LOG_FILE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_ENTRY_NOT_IN_LOG_FILE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_FILE_ALREADY_EXISTS...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_FILE_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_FUNCTION_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INCORRECT_APPEND_TIME...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INSUFFICIENT_BUFFER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_ARGUMENT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_BUFFER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_DATASOURCE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_HANDLE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_INSTANCE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_PATH...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_SQL_LOG_FORMAT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_INVALID_SQLDB...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOG_FILE_CREATE_ERROR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOG_FILE_OPEN_ERROR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOG_FILE_TOO_SMALL...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOG_SAMPLE_TOO_SMALL...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOG_TYPE_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOGSVC_NOT_OPENED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_LOGSVC_QUERY_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_MEMORY_ALLOCATION_FAILURE...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_MORE_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_NO_COUNTERS...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_NO_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_NO_DIALOG_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_NO_MORE_DATA...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_NOT_IMPLEMENTED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_OS_EARLIER_VERSION...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_OS_LATER_VERSION...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_COLLECTION_ALREADY_RUNNING...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_COLLECTION_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_ALREADY_EXISTS...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_FILEPATH...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_NAME_TOO_LONG...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_NOSTART...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_SCHEDULE_ELAPSED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_SCHEDULE_OVERLAP...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_ERROR_TYPE_MISMATCH...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_SERVICE_ERROR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_VALIDATION_ERROR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_PLA_VALIDATION_WARNING...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_QUERY_PERF_DATA_TIMEOUT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_RETRY...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_ALLOC_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_ALLOCCON_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_ALTER_DETAIL_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_BIND_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_CONNECT_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_EXEC_DIRECT_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_FETCH_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_MORE_RESULTS_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_SQL_ROWCOUNT_FAILED...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_STRING_NOT_FOUND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_UNABLE_MAP_NAME_FILES...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_UNABLE_READ_LOG_HEADER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_UNKNOWN_LOG_FORMAT...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_UNKNOWN_LOGSVC_COMMAND...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_UNMATCHED_APPEND_COUNTER...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PDH_WBEM_ERROR...System.Int32 => System.UInt32
Windows.Win32.System.Performance.Apis.PdhAddCounterA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhAddCounterW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhAddEnglishCounterA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhAddEnglishCounterW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBindInputDataSourceA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBindInputDataSourceW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBrowseCountersA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBrowseCountersHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBrowseCountersHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhBrowseCountersW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCalculateCounterFromRawValue : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCloseLog : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCloseQuery : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCollectQueryData : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCollectQueryDataEx : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCollectQueryDataWithTime : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhComputeCounterStatistics : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhConnectMachineA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhConnectMachineW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCreateSQLTablesA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhCreateSQLTablesW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumLogSetNamesA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumLogSetNamesW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumMachinesA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumMachinesHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumMachinesHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumMachinesW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectItemsA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectItemsHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectItemsHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectItemsW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectsA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectsHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectsHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhEnumObjectsW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandCounterPathA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandCounterPathW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandWildCardPathA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandWildCardPathHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandWildCardPathHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhExpandWildCardPathW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhFormatFromRawValue : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetCounterInfoA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetCounterInfoW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetCounterTimeBase : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDataSourceTimeRangeA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDataSourceTimeRangeH : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDataSourceTimeRangeW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfCounterA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfCounterHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfCounterHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfCounterW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfObjectA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfObjectHA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfObjectHW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDefaultPerfObjectW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetDllVersion : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetFormattedCounterArrayA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetFormattedCounterArrayW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetFormattedCounterValue : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetLogFileSize : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetLogSetGUID : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetRawCounterArrayA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetRawCounterArrayW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhGetRawCounterValue : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhLookupPerfIndexByNameA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhLookupPerfIndexByNameW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhLookupPerfNameByIndexA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhLookupPerfNameByIndexW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhMakeCounterPathA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhMakeCounterPathW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhOpenLogA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhOpenLogW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhOpenQueryA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhOpenQueryH : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhOpenQueryW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhParseCounterPathA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhParseCounterPathW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhParseInstanceNameA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhParseInstanceNameW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhReadRawLogRecord : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhRemoveCounter : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSelectDataSourceA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSelectDataSourceW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSetCounterScaleFactor : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSetDefaultRealTimeDataSource : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSetLogSetRunID : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhSetQueryTimeRange : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhUpdateLogA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhUpdateLogFileCatalog : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhUpdateLogW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhValidatePathA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhValidatePathExA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhValidatePathExW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhValidatePathW : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhVerifySQLDBA : return...Int32 => UInt32
Windows.Win32.System.Performance.Apis.PdhVerifySQLDBW : return...Int32 => UInt32
