### ISSUE TITLE
Validate struct sizes against MSVC

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1330]
Since this isn't specific to Rust, it would be great if you have some kind of build validation that compared all struct sizes in metadata against MSVC.

_Originally posted by @kennykerr in https://github.com/microsoft/win32metadata/issues/1325#issuecomment-1290624646_

**Comment by mikebattista** [comment]
Since the only known failures here have been misapplied enums, we should consider extending the existing validation we have for methods to look at structs as well.

**Comment by kennykerr** [comment]
As a short-term solution, perhaps ClangSharp will give you the size of the original struct?

**Comment by mikebattista** [comment]
@chenss3 any updates on this?
