### ISSUE TITLE
`IWICImagingFactory.CreateDecoderFromFilename` parameter should be optional

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1332]
The `pguidVendor` should be optional. 

https://learn.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicimagingfactory-createdecoderfromfilename

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Imaging.IWICImagingFactory.CreateDecoderFromFilename : pguidVendor : [Const,In] => [Const,In,Optional]
