### ISSUE TITLE
DirectComposition functions are missing the `[ComOutPtr]` attribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1333]
Including:

* DCompositionCreateDevice
* DCompositionCreateDevice2
* DCompositionCreateDevice3

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.DirectComposition.Apis.DCompositionCreateDevice : dcompositionDevice : [Out] => [ComOutPtr,Out]
Windows.Win32.Graphics.DirectComposition.Apis.DCompositionCreateDevice2 : dcompositionDevice : [Out] => [ComOutPtr,Out]
Windows.Win32.Graphics.DirectComposition.Apis.DCompositionCreateDevice3 : dcompositionDevice : [Out] => [ComOutPtr,Out]
