### ISSUE TITLE
OLE_HANDLE Not Defined in Metadata

### ISSUE THREAD

**Issue by lonitra** [microsoft/win32metadata#1334]
`OLE_HANDLE` is currently not defined in metadata. Currently `IPicture::get_Handle()` takes a `uint*` as a param. Ideally it should take an `OLE_HANDLE` struct pointer

**Comment by mikebattista** [comment]
Is CloseHandle used to close OLE_HANDLEs or some other function?

**Comment by lonitra** [comment]
It closes `HANDLE` structs so it seems is closes any handle - not specific to OLE_HANDLEs. In WinForms code this is used to close thread handles and token handles.

**Comment by mikebattista** [comment]
Windows.Win32.System.Ole.IPicture.get_Handle : pHandle...UInt32* => OLE_HANDLE*
Windows.Win32.System.Ole.IPicture.get_hPal : phPal...UInt32* => OLE_HANDLE*
Windows.Win32.System.Ole.IPicture.SelectPicture : phBmpOut...UInt32* => OLE_HANDLE*
Windows.Win32.System.Ole.IPicture.set_hPal : hPal...UInt32 => OLE_HANDLE
Windows.Win32.System.Ole.OLE_HANDLE added
Windows.Win32.System.WindowsProgramming.IEditionUpgradeBroker.InitializeParentWindow : parentHandle...UInt32 => OLE_HANDLE
Windows.Win32.UI.TabletPC.IInkEdit.get_Hwnd : pohHwnd...UInt32* => OLE_HANDLE*

**Comment by mikebattista** [comment]
Right. We're just following the headers here.
