### ISSUE TITLE
[Regression] `BLUETOOTH_DEVICE_INFO_STRUCT` incorrectly named

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#1335]
Issue #296 seems to have regressed, unfortunately.

For a year or so, this was correctly named as `Windows.Win32.Devices.Bluetooth.BLUETOOTH_DEVICE_INFO`. 

Some point between v25.0 and v37.0 of the metadata, it has reverted back to `Windows.Win32.Devices.Bluetooth.BLUETOOTH_DEVICE_INFO_STRUCT`.

Same for `Windows.Win32.Devices.Bluetooth.BLUETOOTH_ADDRESS`.

**Comment by mikebattista** [comment]
Looks like https://github.com/microsoft/win32metadata/commit/4b6f47d4f5046a21ef04a38e4ac1bafaba8f73dc was the change.

@sotteson1 was this change intentional?

**Comment by timsneath** [comment]
Somehow I'm still seeing `BLUETOOTH_DEVICE_INFO_STRUCT` (rather than `BLUETOOTH_DEVICE_INFO`) in the latest generated winmd file, @mikebattista. Am I just getting a stale cache, or are you also seeing this?
