### ISSUE TITLE
Some C++ classes showing up incorrectly

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1338]
In the `Windows.Win32.Graphics.Direct2D` namespace, the `Matrix4x3F`, `Matrix4x4F`, `Matrix5x4F` structs are originally just C++ helper classes to simplify the construction of the underlying matrix structs like `D2D_MATRIX_4X3_F` but serve no purpose in metadata and should be removed.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Direct2D.Matrix4x3F removed
Windows.Win32.Graphics.Direct2D.Matrix4x4F removed
Windows.Win32.Graphics.Direct2D.Matrix5x4F removed
