### ISSUE TITLE
OS minimum version numbers are unreliable

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#1341]
I'd love to be able to trust the value of `SupportedOSPlatform`, but currently the data appears dangerously (!) inaccurate. This is super-hard, I know, but it would be better to not have it in the metadata than have unreliable data.

Some examples:

| Function | Documented minVer | Metadata minVer |
| -------- | ------- | ------- |
| winsock functions | [Windows Vista](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-closesocket) | 8.1 |
| `ClosePseudoConsole` and other<br> modern console functions | [17763](https://learn.microsoft.com/en-us/windows/console/closepseudoconsole) | none |
| `GetDisplayAutoRotationPreferences` | [Windows 8.0](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdisplayautorotationpreferences) | none |
| `GetMachineTypeAttributes` | [22000](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getmachinetypeattributes) | none |
| `GetTempPath2` | [20348](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2w) | none |
| `IsWow64Process2` | [10586](https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2) | 16299 |

**Comment by riverar** [comment]
Yeah most of the values are wrong. You should completely ignore this attribute until a major overhaul is completed.

**Comment by riverar** [comment]
Will close this for https://github.com/microsoft/win32metadata/issues/738. If you believe that's in error, just holler!

**Comment by timsneath** [comment]
I think we should either document that it's unreliable, or (preferably) remove the field from the database until it has some modicum of accuracy. 

(FWIW, I wasted an afternoon implementing this in my Dart projection instead of my artisanally handcrafted values  before I realized that it was a retrograde step.)

**Comment by riverar** [comment]
Agreed, and sorry! ☹️
