### ISSUE TITLE
Microsoft.Graphics.Canvas (Win2D) missing

### ISSUE THREAD

**Issue by coffeenotfound** [microsoft/win32metadata#1343]
Right now win2d seems to be missing completely. I suspect because it was some weird UWP only library for a time

Unfortunately, without win2d it's not possible to create a blurred window backdrop since that requires `Microsoft.Graphics.Canvas.Effects.GaussianBlurEffect`

In the meantime are there any workarounds? My project is in Rust, which probably doesn't help the situation, but I also can't figure out how to interact with the precompiled win2d dll

**Comment by kennykerr** [comment]
Win2D is not an OS API and this project is focused on describing all of the OS APIs, [well not all](https://github.com/microsoft/win32metadata/issues/401), so you won't find Win2D here. Instead, you can use the [windows-bindgen](https://crates.io/crates/windows-bindgen) crate to generate bindings for it.

**Comment by coffeenotfound** [comment]
Ah, that explains it. Thanks for the pointer!
