### ISSUE TITLE
[Regression] SFGAOF is incorrectly typed as `Uint64` instead of `Uint32`

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#1344]
```msil
.class public auto ansi sealed Windows.Win32.System.SystemServices.SFGAO_FLAGS
	extends [netstandard]System.Enum
{
	.custom instance void [netstandard]System.FlagsAttribute::.ctor() = (
		01 00 00 00
	)
	// Fields
	.field public specialname rtspecialname uint64 value__
	...
}
```

From `ShObjIdl_Core.h`:

```c
#define SFGAO_PKEYSFGAOMASK     0x81044000L     // Attributes that are masked out for PKEY_SFGAOFlags because they are considered to cause slow calculations or lack context (SFGAO_VALIDATE | SFGAO_ISSLOW | SFGAO_HASSUBFOLDER and others)
typedef ULONG SFGAOF;
```

Tested against v36 from Nuget.

**Comment by mikebattista** [comment]
The enum is typed as ULONG in the header and ULONG in the metadata. Why do you think it's wrong?

**Comment by kennykerr** [comment]
MSVC's ULONG is 32 bit.

**Comment by mikebattista** [comment]
Windows.Win32.System.SystemServices.SFGAO_FLAGS.value__...System.UInt64 => System.UInt32

**Comment by timsneath** [comment]
Given this is a regression, I wonder if there are other fields that have suffered the same fate, @mikebattista? This was showing as a 32-bit value as of a few months ago, so something has changed in the scraper... might be worth checking what changed?

**Comment by sotteson1** [comment]
> Given this is a regression, I wonder if there are other fields that have suffered the same fate, @mikebattista? This was showing as a 32-bit value as of a few months ago, so something has changed in the scraper... might be worth checking what changed?

The type comes from the manual enums.json, so it's not a scraper error.

**Comment by mikebattista** [comment]
That's right. It must have been changed at some point recently. It's fixed now.
