### ISSUE TITLE
LsaRegisterLogonProcess should not use HANDLE

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#135]
The `LsaRegisterLogonProcess` method should use a different handle struct that reflects its particular release rules.

**Comment by sotteson1** [comment]
I'm not sure when this was fixed, but this is what I'm seeing: 

public unsafe static extern NTSTATUS LsaRegisterLogonProcess([In] STRING* LogonProcessName, [Out] LsaHandle* LsaHandle, [Out] uint* SecurityMode);
