### ISSUE TITLE
`GetNumberOfPhysicalMonitorsFromHMONITOR` has wrong return type

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1352]
It should be `Windows.Win32.Foundation.BOOL`.

**Comment by kennykerr** [comment]
Same for a few other functions in that header that return the `_BOOL` alias:

`GetNumberOfPhysicalMonitorsFromHMONITOR`
`GetPhysicalMonitorsFromHMONITOR`
`DestroyPhysicalMonitor`
`DestroyPhysicalMonitors`

**Comment by mikebattista** [comment]
Windows.Win32.Devices.Display.Apis.DestroyPhysicalMonitor : return...Int32 => BOOL
Windows.Win32.Devices.Display.Apis.DestroyPhysicalMonitors : return...Int32 => BOOL
Windows.Win32.Devices.Display.Apis.GetNumberOfPhysicalMonitorsFromHMONITOR : return...Int32 => BOOL
Windows.Win32.Devices.Display.Apis.GetPhysicalMonitorsFromHMONITOR : return...Int32 => BOOL
