### ISSUE TITLE
`GetMessageA` and `GetMessageW` need the `CanReturnMultipleSuccessValuesAttribute` attribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1353]
These functions return multiple success values.

**Comment by mikebattista** [comment]
Windows.Win32.UI.WindowsAndMessaging.Apis.GetMessageA : [DllImport(USER32.dll,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows5.0)] => [CanReturnMultipleSuccessValues,DllImport(USER32.dll,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows5.0)]
Windows.Win32.UI.WindowsAndMessaging.Apis.GetMessageW : [DllImport(USER32.dll,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows5.0)] => [CanReturnMultipleSuccessValues,DllImport(USER32.dll,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows5.0)]
