### ISSUE TITLE
Updated LDR_DATA_TABLE_ENTRY struct

### ISSUE THREAD

**Issue by codecheck01** [microsoft/win32metadata#1357]
Would it be possible to update the [LDR_DATA_TABLE_ENTRY](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/WindowsProgramming/struct.LDR_DATA_TABLE_ENTRY.html) struct, so it is updated/fullfilled according to the latest windows versions.

I am actually using this struct: [LDR_DATA_TABLE_ENTRY](https://docs.rs/ntapi/latest/ntapi/ntldr/struct.LDR_DATA_TABLE_ENTRY.html) (**NTAPI**)

Thank you in advance.

**Comment by mikebattista** [comment]
The metadata is in sync with the SDK headers. If these other definitions are undocumented/unsupported then we wouldn't add them to the metadata.
