### ISSUE TITLE
Cannot convert type Windows.Win32.Foundation.__CHAR_260 to char

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1359]
The error occurs when using the `szExeFile` field of the `PROCESSENTRY32` structure

Example: 

`if (strCmp.IndexOf(procEntry.szExeFile) == 0) {}`

**Comment by kennykerr** [comment]
Are you using [CsWin32](https://github.com/microsoft/CsWin32)? The metadata for `PROCESSENTRY32` seems correct. @AArnott

**Comment by AArnott** [comment]
@vitkuz573, the `PROCESSENTRY32` struct is a narrow character struct. You can't convert a byte array to a char array, or otherwise treat bytes and chars, directly.
If you want to convert the szExeFile field to a char array, use `PROCESSENTRY32W` instead.
