### ISSUE TITLE
STATUS_SUCCESS constant missing, and should be typed as NTSTATUS

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#136]
The `STATUS_SUCCESS` constant should be added, typed as `NTSTATUS`.

**Comment by sotteson1** [comment]
Looking at ntstatus.h, NTSTATUS works more like HRESULT than WIN32_ERROR. It has bits like HRESULT and has a facility code like HRESULT. Should we model it the same way we do HRESULT? I could make them NTSTATUS constants that have int values like what we do with HRESULT.

**Comment by AArnott** [comment]
Yes, you're right: NTSTATUS should _not_ be an enum. I even realized this at https://github.com/microsoft/win32metadata/issues/159#issuecomment-787209808 but failed to update this issue.

So this is just about a missing constant then.
