### ISSUE TITLE
`ShellMessageBoxW` / `ShellMessageBoxA` need typed flags

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1363]
The docs indicate these functions accept the same flags as `MessageBoxW` / `MessageBoxA`.

https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellmessageboxw

So I'd expect the shell functions also to expect a `MESSAGEBOX_STYLE` parameter rather than `uint`.

**Comment by mikebattista** [comment]
Windows.Win32.UI.Shell.Apis.ShellMessageBoxA : fuStyle...UInt32 => MESSAGEBOX_STYLE
Windows.Win32.UI.Shell.Apis.ShellMessageBoxW : fuStyle...UInt32 => MESSAGEBOX_STYLE
