### ISSUE TITLE
Missing AlsoUsableFor on NCRYPT_PROV_HANDLE and NCRYPT_KEY_HANDLE

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1364]
[The `NCryptFreeObject` method](https://learn.microsoft.com/en-us/windows/win32/api/ncrypt/nf-ncrypt-ncryptfreeobject) accepts an `NCRYPT_HANDLE`, but in documentation this can actually be either an `NCRYPT_PROV_HANDLE` or `NCRYPT_KEY_HANDLE`. It seems then that `NCRYPT_HANDLE` is a 'base type' for these other two.

In that case, these two 'derived' types should have `[AlsoUsableFor("NCRYPT_HANDLE")]` metadata on each of them.

**Comment by mikebattista** [comment]
Windows.Win32.Security.Cryptography.NCRYPT_KEY_HANDLE : [InvalidHandleValue(0),NativeTypedef,RAIIFree(NCryptFreeObject)] => [AlsoUsableFor(NCRYPT_HANDLE),InvalidHandleValue(0),NativeTypedef,RAIIFree(NCryptFreeObject)]
Windows.Win32.Security.Cryptography.NCRYPT_PROV_HANDLE : [InvalidHandleValue(0),NativeTypedef,RAIIFree(NCryptFreeObject)] => [AlsoUsableFor(NCRYPT_HANDLE),InvalidHandleValue(0),NativeTypedef,RAIIFree(NCryptFreeObject)]
