### ISSUE TITLE
The `OpenInputDesktop` function has the `dwDesiredAccess` parameter of type `uint` instead of `ACCESS_MASK`.

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1366]
## Actual behavior

The `OpenInputDesktop` function has the `dwDesiredAccess` parameter of type `uint` instead of `ACCESS_MASK` for more convenient use.

```csharp
var inputDesktop = OpenInputDesktop_SafeHandle(0, true, 0x00020000);
```

## Expected behavior

```csharp
var inputDesktop = OpenInputDesktop_SafeHandle(0, true, ACCESS_MASK.READ_CONTROL);
```

## Repro steps

1. `NativeMethods.txt` content:
```
OpenInputDesktop
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.110-beta
- Win32Metadata version (if explicitly set by project): 37.0.34-preview
- Target Framework: net7.0-windows
- `LangVersion` (if explicitly set by project): 11

**Comment by mikebattista** [comment]
Windows.Win32.System.StationsAndDesktops.Apis.OpenInputDesktop : dwDesiredAccess...UInt32 => DESKTOP_ACCESS_FLAGS
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_CREATEMENU added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_CREATEWINDOW added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_DELETE added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_ENUMERATE added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_HOOKCONTROL added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_JOURNALPLAYBACK added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_JOURNALRECORD added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_READ_CONTROL added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_READOBJECTS added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_SWITCHDESKTOP added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_SYNCHRONIZE added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_WRITE_DAC added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_WRITE_OWNER added
Windows.Win32.System.StationsAndDesktops.DESKTOP_ACCESS_FLAGS.DESKTOP_WRITEOBJECTS added
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_CREATEMENU removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_CREATEWINDOW removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_ENUMERATE removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_HOOKCONTROL removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_JOURNALPLAYBACK removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_JOURNALRECORD removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_READOBJECTS removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_SWITCHDESKTOP removed
Windows.Win32.System.SystemServices.DESKTOP_ACCESS_FLAGS.DESKTOP_WRITEOBJECTS removed
