### ISSUE TITLE
`IPicture.set_hPal` method missing `[SpecialName]` flag

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1367]
The `IPicture` interface in the metadata correctly has `specialname` applied to its `get_hPal` method, but it's missing from the `set_hPal` method, causing a malfunction in CsWin32 when it's looking for all accessors for a given property. 
Below is the IL for these two methods.

```
	.method public hidebysig specialname newslot abstract virtual 
		instance valuetype [Windows.Win32.winmd]Windows.Win32.Foundation.HRESULT get_hPal (
			[out] valuetype Windows.Win32.System.Ole.OLE_HANDLE* phPal
		) cil managed 
	{
	} // end of method IPicture::get_hPal


	.method public hidebysig newslot abstract virtual 
		instance valuetype [Windows.Win32.winmd]Windows.Win32.Foundation.HRESULT set_hPal (
			[in] valuetype Windows.Win32.System.Ole.OLE_HANDLE hPal
		) cil managed 
	{
	} // end of method IPicture::set_hPal
```

Why is the flag applied to one and not the other? Can we make them consistent? And preferably by both getting the flag.

BTW, C# cannot express this as a property on COM interfaces because the accessors of a property in C# must be declared consecutively, but the VMT order of this property puts other methods between these two accessors. But this is merely a limitation in C# and should not prevent the metadata from expressing the special nature of this pair of methods. And in fact even in C# we *can* express these as accessors on a property when declared on a struct where we implement them ourselves.

**Comment by mikebattista** [comment]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_EnterpriseDisabled :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_EnterpriseUninstallable :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_IconPath :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_IsMdilMaintenanceNeeded :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_NotificationState :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_Title :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_UninstallableState :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMApplicationInfo.set_UpdateAvailable :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMBackgroundServiceAgentInfo.set_IsScheduleAllowed :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMBackgroundServiceAgentInfo.set_IsScheduled :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_AttemptCount :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_DownloadState :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_IntervalDuration :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_MaxRunCount :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_NextSchedule :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_RecurrenceType :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_RunCount :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_RunForever :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMLiveTileJobInfo.set_StartSchedule :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMTileInfo.set_IsAutoRestoreDisabled :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMTileInfo.set_IsRestoring :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMTileInfo.set_NotifiedState :  => [SpecialName]
Windows.Win32.System.ApplicationInstallationAndServicing.IPMTilePropertyInfo.set_Property :  => [SpecialName]
Windows.Win32.System.Ole.IPicture.set_hPal :  => [SpecialName]
Windows.Win32.System.Ole.IPicture2.set_hPal :  => [SpecialName]
