### ISSUE TITLE
IAudioProcessingObjectConfiguration.LockForProcess missing array attributes on parameters

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1368]
The `LockForProcess` method should have `[NativeArrayInfo]` attributes on parameters 2 and 4. 

```diff 
-unsafe HRESULT LockForProcess([In] uint u32NumInputConnections, [In] APO_CONNECTION_DESCRIPTOR** ppInputConnections, [In] uint u32NumOutputConnections, [In] APO_CONNECTION_DESCRIPTOR** ppOutputConnections);
+unsafe HRESULT LockForProcess([In] uint u32NumInputConnections, [In, NativeArrayInfo(CountParamIndex = 0)] APO_CONNECTION_DESCRIPTOR** ppInputConnections, [In] uint u32NumOutputConnections, [In, NativeArrayInfo(CountParamIndex = 2)] APO_CONNECTION_DESCRIPTOR** ppOutputConnections);
```

**Comment by mikebattista** [comment]
Windows.Win32.Media.Audio.Apo.IAudioProcessingObjectConfiguration.LockForProcess : ppInputConnections : [In] => [In,NativeArrayInfo(CountParamIndex=0)]
Windows.Win32.Media.Audio.Apo.IAudioProcessingObjectConfiguration.LockForProcess : ppOutputConnections : [In] => [In,NativeArrayInfo(CountParamIndex=2)]
