### ISSUE TITLE
IUnknown.QueryInterface should be tagged with [CanReturnErrorsAsSuccessAttribute]

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1371]
QI so often fails that it should be tagged with `[CanReturnErrorsAsSuccessAttribute]` so that projections can avoid throwing exceptions when a failing HRESULT would be preferred.

**Comment by mikebattista** [comment]
Windows.Win32.System.Com.IUnknown.QueryInterface :  => [CanReturnErrorsAsSuccess]
