### ISSUE TITLE
[SetWindowPos] Param about `hWndInsertAfter` but HWND_TOPMOST or HWND_NOTOPMOST not definition found

### ISSUE THREAD

**Issue by emako** [microsoft/win32metadata#1375]
I have always used the `SetWindowPos` parameter `HWND_ TOPMOST` or `HWND_ NOTOPMOST`, but CsWin32 is not defined it as an enum. In this case, I need to define by myself like following.

Is there any method that I don't need to define by myself?
Or where can I find out if it is already defined in CsWin32?
I have encountered many situations where non enum parameters need to be defined by myself.

```c#
// def by myself
public const int HWND_TOPMOST = -1;
public const int HWND_NOTOPMOST = -2;
```
```c#
// auto gen
[DllImport("USER32.dll", ExactSpelling = true, SetLastError = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
[SupportedOSPlatform("windows5.0")]
internal static extern winmdroot.Foundation.BOOL SetWindowPos(winmdroot.Foundation.HWND hWnd, winmdroot.Foundation.HWND hWndInsertAfter, int X, int Y, int cx, int cy, winmdroot.UI.WindowsAndMessaging.SET_WINDOW_POS_FLAGS uFlags);

```
---
Context
CsWin32 version: [e.g. 0.2.138-beta]
Win32Metadata version (if explicitly set by project):
Target Framework: [e.g. net6.0]
LangVersion (if explicitly set by project): [e.g. 10.0]

**Comment by mikebattista** [comment]
You should be able to list these constants in NativeMethods.txt to have them autogenerated. These HWND parameters are open ended so creating an enum with this closed set of reserved handles wouldn't be appropriate.
