### ISSUE TITLE
GetPrivateProfileIntW should return `int`

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1376]
The `GetPrivateProfileInt` method [is documented](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofileintw) as returning the value of its `nDefault` parameter in certain cases. `nDefault` is a signed integer. In fact the method name itself claims to return an `Int`. The headers are wrong to type the method as returning `UINT`. Can this be corrected at least in the metadata?

**Comment by riverar** [comment]
Agree with the change. But it's only _wrong_ if we cut off OS support after ~Windows 2.0. 🙃

`GetPrivateProfileInt` extends `GetProfileInt` and was introduced somewhere around Windows 3.0.

![image](https://user-images.githubusercontent.com/475132/203165196-55b63d9b-7a0d-43b3-8e77-a68f3cdb55d5.png)

`GetProfileInt` was introduced in Windows 1.0. `GetProfileInt` in that version of Windows does not support pulling out negative integers from initialization files.

![image](https://user-images.githubusercontent.com/475132/203183321-e808dd9b-8042-4dae-a4c5-ca9122754fee.png)
![image](https://user-images.githubusercontent.com/475132/203183322-54816bc1-6839-4adf-913e-129df3fae72e.png)

I suspect the API author kept the unsigned return type to make `GetPrivateProfileInt` an easy and compatible replacement for `GetProfileInt`.

**Comment by mikebattista** [comment]
Windows.Win32.System.WindowsProgramming.Apis.GetPrivateProfileIntW : return...UInt32 => Int32
