### ISSUE TITLE
COMPRESSION_FORMAT enum

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1379]
The `COMPRESSION_FORMAT_` prefixed constants should belong to a `COMPRESSION_FORMAT` enum.
That enum should be used as the type of the `FILE_COMPRESSION_INFO.CompressionFormat` field.

**Comment by mikebattista** [comment]
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_DEFAULT added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_LZNT1 added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_NONE added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_XP10 added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_XPRESS added
Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT.COMPRESSION_FORMAT_XPRESS_HUFF added
Windows.Win32.Storage.FileSystem.FILE_COMPRESSION_INFO.CompressionFormat...System.UInt16 => Windows.Win32.Storage.FileSystem.COMPRESSION_FORMAT
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_DEFAULT removed
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_LZNT1 removed
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_NONE removed
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_XP10 removed
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_XPRESS removed
Windows.Win32.System.SystemServices.Apis.COMPRESSION_FORMAT_XPRESS_HUFF removed
