### ISSUE TITLE
DsGetDcCloseW should take GetDcContextHandle as a parameter

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#138]
The `DsGetDcOpenW` method is documented as producing a `HANDLE` but the metadata appropriately substitutes with a `GetDcContextHandle` type because it must be freed by a call to `DsGetDcCloseW`. The problem is that `DsGetDcCloseW` itself still takes a `HANDLE` in the metadata instead of a `GetDcContextHandle`.

**Comment by sotteson1** [comment]
This was fixed a while ago.
