### ISSUE TITLE
INVALID_FILE_SIZE is missing from metadata

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1381]
This constant is [documented](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfilesize) and [in the headers](https://dev.azure.com/microsoft/OS/_search?action=contents&text=def%3AINVALID_FILE_SIZE%20ext%3Ah&type=code&filters=ProjectFilters%7BOS%7DRepositoryFilters%7Bos.2020%7D&pageSize=25&includeFacets=false&result=DefaultCollection/OS/os.2020/GBofficial/main//base/fs/test/Shared_Tests/Regression/Notify2/Regression/inc/notify.h), but is missing from the metadata.

**Comment by mikebattista** [comment]
Need to update the ConstantsScraper for this one. We detect `(DWORD)-1` but not `(DWORD)0x...` .

**Comment by riverar** [comment]
I had an issue somewhere tracking the need for evaluating expressions, but maybe that's overkill for this.

**Comment by mikebattista** [comment]
We already have a regular expression for `(DWORD)-1`, we just need to extend it to support `0x` values.
