### ISSUE TITLE
FILE_TYPE enum missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1382]
The `FILE_TYPE_*` prefixed constants should go into an enum that is then used as the return type from the [GetFileType](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype) method.

**Comment by mikebattista** [comment]
Windows.Win32.Storage.FileSystem.Apis.GetFileType : return...UInt32 => FILE_TYPE
Windows.Win32.Storage.FileSystem.FILE_TYPE added
Windows.Win32.Storage.FileSystem.FILE_TYPE.FILE_TYPE_CHAR added
Windows.Win32.Storage.FileSystem.FILE_TYPE.FILE_TYPE_DISK added
Windows.Win32.Storage.FileSystem.FILE_TYPE.FILE_TYPE_PIPE added
Windows.Win32.Storage.FileSystem.FILE_TYPE.FILE_TYPE_REMOTE added
Windows.Win32.Storage.FileSystem.FILE_TYPE.FILE_TYPE_UNKNOWN added
Windows.Win32.System.WindowsProgramming.Apis.FILE_TYPE_CHAR removed
Windows.Win32.System.WindowsProgramming.Apis.FILE_TYPE_DISK removed
Windows.Win32.System.WindowsProgramming.Apis.FILE_TYPE_PIPE removed
Windows.Win32.System.WindowsProgramming.Apis.FILE_TYPE_REMOTE removed
Windows.Win32.System.WindowsProgramming.Apis.FILE_TYPE_UNKNOWN removed
