### ISSUE TITLE
`SECURITY_DESCRIPTOR_CONTROL` should be a flags enum

### ISSUE THREAD

**Issue by fsavy-tehtris** [microsoft/win32metadata#1384]
The values associated with this set of bit flags are not regrouped as other bit flags enums are.

[`SECURITY_DESCRIPTOR_CONTROL` documentation](https://learn.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-control)

**Comment by mikebattista** [comment]
Windows.Win32.Networking.Clustering.CLUSPROP_SECURITY_DESCRIPTOR._Anonymous_e__Union.sd...Windows.Win32.System.SystemServices.SECURITY_DESCRIPTOR_RELATIVE => Windows.Win32.Security.SECURITY_DESCRIPTOR_RELATIVE
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_DACL_AUTO_INHERIT_REQ added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_DACL_AUTO_INHERITED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_DACL_DEFAULTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_DACL_PRESENT added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_DACL_PROTECTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_GROUP_DEFAULTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_OWNER_DEFAULTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_RM_CONTROL_VALID added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SACL_AUTO_INHERIT_REQ added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SACL_AUTO_INHERITED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SACL_DEFAULTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SACL_PRESENT added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SACL_PROTECTED added
Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL.SE_SELF_RELATIVE added
Windows.Win32.Security.SECURITY_DESCRIPTOR_RELATIVE added
Windows.Win32.Security.SECURITY_DESCRIPTOR.Control...System.UInt16 => Windows.Win32.Security.SECURITY_DESCRIPTOR_CONTROL
Windows.Win32.System.SystemServices.Apis.SE_DACL_AUTO_INHERIT_REQ removed
Windows.Win32.System.SystemServices.Apis.SE_DACL_AUTO_INHERITED removed
Windows.Win32.System.SystemServices.Apis.SE_DACL_DEFAULTED removed
Windows.Win32.System.SystemServices.Apis.SE_DACL_PRESENT removed
Windows.Win32.System.SystemServices.Apis.SE_DACL_PROTECTED removed
Windows.Win32.System.SystemServices.Apis.SE_GROUP_DEFAULTED removed
Windows.Win32.System.SystemServices.Apis.SE_OWNER_DEFAULTED removed
Windows.Win32.System.SystemServices.Apis.SE_RM_CONTROL_VALID removed
Windows.Win32.System.SystemServices.Apis.SE_SACL_AUTO_INHERIT_REQ removed
Windows.Win32.System.SystemServices.Apis.SE_SACL_AUTO_INHERITED removed
Windows.Win32.System.SystemServices.Apis.SE_SACL_DEFAULTED removed
Windows.Win32.System.SystemServices.Apis.SE_SACL_PRESENT removed
Windows.Win32.System.SystemServices.Apis.SE_SACL_PROTECTED removed
Windows.Win32.System.SystemServices.Apis.SE_SELF_RELATIVE removed
Windows.Win32.System.SystemServices.SECURITY_DESCRIPTOR_RELATIVE removed
