### ISSUE TITLE
DirectXMath support

### ISSUE THREAD

**Issue by zzwxh** [microsoft/win32metadata#1387]
### Motivation

direct3d needs DirectXMath

**Comment by mikebattista** [comment]
It looks like it's mostly inline code and has been excluded explicitly for this reason. The metadata doesn't support inlines.

https://github.com/microsoft/win32metadata/blob/22fe1a4839ac84129e4ac1ef24a97fcc1d863fe2/scripts/HeaderFileCoverageExceptions.csv#L149

**Comment by zzwxh** [comment]
so how do i use DirectXMath in rust

**Comment by kennykerr** [comment]
@robmikh or @damyanp in case they have any suggestions about using `directxmath.h` in Rust.

**Comment by damyanp** [comment]
@walbourn will probably have thoughts on this.

My 2c: As well as having a bunch of optimized SIMD code for various mathematical operations, part of the real value of directxmath comes from how it works with the C++ type system to allow natural looking code to keep values in SIMD registers where possible.  This is unlikely to translate directly to Rust.  I don't think any win32 APIs deal directly with directxmath types, so any Rust math library should be good for this.

Maybe there is room for a directxmath inspired math library for rust, but I think that this is out of the scope of win32metadata / windows-rs.

**Comment by walbourn** [comment]
DirectXMath is designed as a light-weight cross-platform API for the intrinsics functions for Intel SSE and ARM-NEON. There are 'no-intrinsics' code paths there as well, but mostly for validation and fallback and not intended for production use. It is a fully C++ inline header so there's no link library. Also, it does not make use of Windows Runtime (WinRT) so there is no ``winmd`` data.

You can make use of ``Windows.Foundation.Numerics`` but it's not aimed at the same graphics & game-centric use scenarios as DirectXMath.

There is also a C++ extension for DirectXMath called [SimpleMath](https://github.com/microsoft/DirectXTK/wiki/SimpleMath) which adds more C++ conversion operators and mimics the *XNA Game Studio* framework math library which is implemented using DirectXMath.

With all that background, one could port much of DirectXMath to Rust using the [Module::core::arch::x86_64](https://doc.rust-lang.org/1.29.1/core/arch/x86_64/index.html) intrinsics. DirectXMath is open source on [GitHub](https://github.com/microsoft/DirectXMath) subject to the [MIT license](https://github.com/microsoft/DirectXMath/blob/main/LICENSE) so you are free to cut & paste from it with attribution.
