### ISSUE TITLE
Bug: type error in D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION::pExports

### ISSUE THREAD

**Issue by zhouhang95** [microsoft/win32metadata#1388]
### Summary

```
pub struct D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION {
    pub pSubobjectToAssociate: *const D3D12_STATE_SUBOBJECT,
    pub NumExports: u32,
    pub pExports: *mut ::windows::core::PWSTR,
}
```
->
```
pub struct D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION {
    pub pSubobjectToAssociate: *const D3D12_STATE_SUBOBJECT,
    pub NumExports: u32,
    pub pExports: *mut ::windows::core::PCWSTR,
}
```

```
typedef struct D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION {
  const D3D12_STATE_SUBOBJECT *pSubobjectToAssociate;
  UINT                        NumExports;
  LPCWSTR                     *pExports;
} D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION;
```
https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_subobject_to_exports_association

**Comment by riverar** [comment]
@zhouhang95 In the future, please provide a summary of the problem you are reporting. It is difficult to understand what you are reporting with two code dumps and a `->`. (You can provide this summary in any language.)

**Comment by mikebattista** [comment]
There's logic in the build to assign const (`isConst` below) to `LPCWSTR`, but it may not be being applied to struct fields.

https://github.com/microsoft/win32metadata/blob/046f75bb597e9c2006072e35a01476df03de5384/sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs#L680-L691

+@sotteson1 / @chenss3 for any feedback here.
