### ISSUE TITLE
`BOOL` and `BOOLEAN` are defined as a `struct` whereas `VARIANT_BOOL` is defined as an `enum`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1389]
This leads to strange inconsistencies. Can `VARIANT_BOOL` also be a `[NativeTypedef] struct`?

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/pull/2206#discussion_r1036314179_

**Comment by mikebattista** [comment]
@elachlan what are your thoughts on this? `VARIANT_BOOL` is either `VARIANT_TRUE` or `VARIANT_FALSE` which is why this is an enum. The alternative is we make `VARIANT_BOOL` a `[NativeTypedef] struct` like bool typed as `short`, and `VARIANT_TRUE` and `VARIANT_FALSE` would be disconnected constants. How would this impact usability in WinForms?

**Comment by kennykerr** [comment]
The `BOOL` and `BOOLEAN` types also have true/false constants, although they appear to be missing from the metadata for some reason. 

https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types

**Comment by mikebattista** [comment]
TRUE and FALSE were [added](https://github.com/microsoft/win32metadata/commit/05fbdc91e95ee3814859afeb54988def57de589e) at one point but then removed based on feedback that projections were using their own true and false.

**Comment by kennykerr** [comment]
Ah right. In hindsight they're probably worth including. I've seen numerous requests for them as they are just so common in existing code/samples/docs that is ported to Rust.

**Comment by mikebattista** [comment]
Sure we can add them back. As long as @elachlan confirms WinForms is ok with the breaking change for VARIANT_BOOL.

**Comment by elachlan** [comment]
Currently where WinForms uses it is in [VARIANT.cs](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs). I don't believe it has been re-written yet. Since it would have been moved namespace wise.

CC: @AArnott & @JeremyKuhne

**Comment by elachlan** [comment]
This will break the current code though. So its not zero effort.

**Comment by mikebattista** [comment]
Do you agree with @kennykerr's proposal? If it's a better definition then we would make the change.

**Comment by JeremyKuhne** [comment]
@mikebattista Consistency is good. There are slight performance benefits to having an enum as far as .NET is concerned, which is why they're defined as such in the .NET runtime, but it is minimal. I personally prefer structs as we can provide cast operators that make going to/from `bool` easy and, more importantly, correct.

**Comment by elachlan** [comment]
Consistency is nice. We can also add extensions to it, which we do for `BOOL`. So in general its a good change.

**Comment by mikebattista** [comment]
Ok. Will change to struct then. I will add TRUE/FALSE back as well given that the most recent feedback is they are wanted.

**Comment by riverar** [comment]
Think it's important we provide VARIANT_TRUE/VARIANT_FALSE constants, esp. given true is not represented with integer 1.

**Comment by mikebattista** [comment]
Yes I will add those as well similar to https://github.com/microsoft/win32metadata/commit/05fbdc91e95ee3814859afeb54988def57de589e with a NativeTypeName for the struct.

**Comment by mikebattista** [comment]
@riverar if you get a chance could you validate usage of VARIANT_TRUE/FALSE in Rust? I defined them the same way as TRUE/FALSE but the definition in the metadata doesn't reference VARIANT_BOOL like TRUE/FALSE do with BOOL. They just show up as short.

**Comment by kennykerr** [comment]
Whatever type the metadata uses for these constants is what Rust will use. So, if the types of the constants are not `BOOL` and `VARIANT_BOOL` respectively then that won't work.

**Comment by mikebattista** [comment]
Everything looks correct except the VARIANT_TRUE/VARIANT_FALSE constants. Not sure why they're not getting typed as VARIANT_BOOL.

**Comment by riverar** [comment]
@mikebattista Here ya go https://github.com/microsoft/win32metadata/pull/1397

**Comment by mikebattista** [comment]
Thanks!
