### ISSUE TITLE
Various `DirectSoundXxx` functions missing the `[ComOutPtr]` attribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1391]

**Comment by mikebattista** [comment]
+@sotteson1 / @chenss3

Is there something in the headers that we aren't scanning properly? Or do we need to manually add this attribute every time this class of issue is reported?

**Comment by rkevingibson** [comment]
Would request to add the IDxcCompiler3::Compile/Disassemble functions to this list - there may be others in Dxcapi.h as well (it looks like a couple have already been fixed manually). 

It may be possible to automate this by looking for function prototypes which take a REFIID argument followed by a LPVOID* argument (especially if they're named riid and ppv which seems to be the pattern). I don't know if that would catch too many false positives to be worth it, but even printing the list of functions that match this and going over it manually may be a feasible fix?

**Comment by kennykerr** [comment]
I tried doing that for [windows-rs](https://github.com/microsoft/windows-rs) but there are some APIs that follow the same `GUID*, void**` pattern that have nothing to do with querying for a COM interface. That's why the `ComOutPtr` attribute is necessary.

**Comment by mikebattista** [comment]
If there's no pattern to scan, then please list the APIs that need to be changed.

**Comment by kennykerr** [comment]
I figured out how to detect the DirectSound ones without the attribute. That leaves only the two `IDxcCompiler3` methods since they're `void**` and those can't be inferred.

**Comment by mikebattista** [comment]
Can you share the pattern you used to detect this? We should update the metadata so other projections can benefit.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Direct3D.Dxc.IDxcCompiler3.Compile : ppResult : [Out] => [ComOutPtr,Out]
Windows.Win32.Graphics.Direct3D.Dxc.IDxcCompiler3.Disassemble : ppResult : [Out] => [ComOutPtr,Out]
