### ISSUE TITLE
`PROCESSOR_POWER_INFORMATION` exposes `u64` instead of `u32`

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/win32metadata#1394]
https://learn.microsoft.com/en-us/windows/win32/power/processor-power-information-str

In windows-rs: `windows::Win32::System::Power::PROCESSOR_POWER_INFORMATION`

```rust
#[repr(C)]
pub struct PROCESSOR_POWER_INFORMATION {
    pub Number: u64,
    pub MaxMhz: u64,
    pub CurrentMhz: u64,
    pub MhzLimit: u64,
    pub MaxIdleState: u64,
    pub CurrentIdleState: u64,
}
```

Probably a metadata issue ?

**Comment by ChrisDenton** [comment]
It's in the driver headers. See km/ntpoapi.h

**Comment by kennykerr** [comment]
Thanks Chris. Then it falls under the #401 issue.

**Comment by kennykerr** [comment]
Looks like its manually and incorrectly injected here: 

https://github.com/microsoft/win32metadata/blob/663ae1fd98ae2b727c407f9d4855e07b85778890/generation/WinSDK/manual/Power.cs

**Comment by ChrisDenton** [comment]
That leads down to #992:

> Also, while I'm on it: [PROCESSOR_POWER_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str) is missing a Rust binding as well (whereas other possible output types for CallNtPowerInformation, e.g. [SYSTEM_BATTERY_STATE](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Power/struct.SYSTEM_BATTERY_STATE.html#) have theirs...)

> SYSTEM_POWER_INFORMATION is also missing. From the [docs](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str#remarks) and scanning the kits, looks like they were never included in winnt.h so we'll need to define them manually.

So [`CallNtPowerInformation`](https://learn.microsoft.com/en-us/windows/win32/api/powerbase/nf-powerbase-callntpowerinformation) is in the Windows SDK but a couple of documented output types aren't. That's likely either an issue with the docs or the headers. But I'm not sure which.

**Comment by kennykerr** [comment]
There's just too much overlap with the WDK headers. We just need to get full coverage of these headers and all these problems should go away.

**Comment by elachlan** [comment]
Related: https://github.com/microsoft/win32metadata/issues/401, https://github.com/microsoft/win32metadata/issues/724, https://github.com/microsoft/win32metadata/issues/1093, https://github.com/microsoft/win32metadata/issues/1223, etc.

**Comment by mikebattista** [comment]
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.CurrentIdleState...System.UInt64 => System.UInt32
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.CurrentMhz...System.UInt64 => System.UInt32
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.MaxIdleState...System.UInt64 => System.UInt32
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.MaxMhz...System.UInt64 => System.UInt32
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.MhzLimit...System.UInt64 => System.UInt32
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION.Number...System.UInt64 => System.UInt32
Windows.Win32.System.Power.SYSTEM_POWER_INFORMATION.Idleness...System.UInt64 => System.UInt32
Windows.Win32.System.Power.SYSTEM_POWER_INFORMATION.MaxIdlenessAllowed...System.UInt64 => System.UInt32
Windows.Win32.System.Power.SYSTEM_POWER_INFORMATION.TimeRemaining...System.UInt64 => System.UInt32
