### ISSUE TITLE
Missing Windows.Win32.Interop diff

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1396]
Windows.Win32.Interop differences don't appear to be tracked/diffed/checked after build like Windows.Win32.winmd.

**Comment by mikebattista** [comment]
If we address #1467 by merging Interop into Windows.Win32.Foundation.Metadata in the main winmd, then we'll get these diffs for free.

**Comment by kennykerr** [comment]
Let's do it. 😊

**Comment by mikebattista** [comment]
I got pretty far with https://github.com/microsoft/win32metadata/tree/mikebattista/interop but the attributes for some reason are losing all of their properties and the Attribute inheritance when they are written to the main winmd, which is wrong and causes build failures.
