### ISSUE TITLE
ADDRESS_FAMILY should be typed as ushort

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1398]
ADDRESS_FAMILY should be typed as ushort.

_Originally posted by @mikebattista in https://github.com/microsoft/win32metadata/issues/1397#issuecomment-1336275785_

**Comment by riverar** [comment]
@mikebattista `ADDRESS_FAMILY` looks okay, no? APIs such as `inet_pton` expect an `INT`.

https://linux.die.net/man/3/inet_pton
https://learn.microsoft.com/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/pull/1397#issuecomment-1336278009.
