### ISSUE TITLE
Many enums are missing [flags] attributes

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#1401]
For example, CreatePackageDependencyOptions.

In the header this has:

```c++
DEFINE_ENUM_FLAG_OPERATORS(CreatePackageDependencyOptions)
```

However, it looks like the scanning code only detects an enum as being a flags enum if there is a semicolon at the end of the DEFINE_ENUM_FLAG_OPERATORS line.

**Comment by kennykerr** [comment]
https://github.com/microsoft/win32metadata/blob/d255e9d400009292d30ecb40b9a1696cb9edc6e4/sources/MetadataUtils/ConstantsScraper.cs#L56
