### ISSUE TITLE
Some `WTS_*` constants are missing

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1403]
Missing constants:

`WTS_CURRENT_SERVER_HANDLE`
`WTS_CURRENT_SERVER_NAME`
`WTS_CURRENT_SERVER`
`WTS_SECURITY_CURRENT_GUEST_ACCESS`
`WTS_SECURITY_USER_ACCESS`
`WTS_SECURITY_CURRENT_USER_ACCESS`
`WTS_SECURITY_ALL_ACCESS`

**Comment by vitkuz573** [comment]
But the constants `WTS_CURRENT_` were not added. I see only `WTS_SECURITY_FLAGS`.

**Comment by mikebattista** [comment]
Can you check how WTS_CURRENT_SERVER_NAME was defined in the commit above? I believe the HANDLEs are correct but not sure about WTS_CURRENT_SERVER_NAME given it's used as both LPSTR and LPWSTR for the -A and -W variants, and it's defined as just NULL in the headers.

**Comment by mikebattista** [comment]
Closing out. Please reactivate or file a new issue if there are any usability issues with how the constants are defined.
