### ISSUE TITLE
Threadpool API should use handles, not pointers to structs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1404]
Types like `PTP_WORK`, `PTP_TIMER`, `PTP_WAIT`, `PTP_IO` are all handle types (opaque pointers) and should be modeled as such. While there are some Threadpool types that are defined as structs, like `TP_CALLBACK_ENVIRON_V3`, most should be considered opaque handles.

```C++
typedef struct _TP_WORK TP_WORK, *PTP_WORK;
```

So for example, `TP_WORK` should not be defined at all. Instead, there should be a `PTP_WORK` struct with the `NativeTypeDef` attribute and the `InvalidHandleValue` attribute.

**Comment by kennykerr** [comment]
All of these have an "invalid handle value" of `0`.

**Comment by mikebattista** [comment]
Does the below look right? PTP_* are then remapped to the equivalent TP_* with a pointer.

```
  {
    "Namespace": "Windows.Win32.System.Threading",
    "Name": "TP_IO",
    "ValueType": "IntPtr",
    "InvalidHandleValues": [ 0 ]
  },
  {
    "Namespace": "Windows.Win32.System.Threading",
    "Name": "TP_TIMER",
    "ValueType": "IntPtr",
    "InvalidHandleValues": [ 0 ]
  },
  {
    "Namespace": "Windows.Win32.System.Threading",
    "Name": "TP_WAIT",
    "ValueType": "IntPtr",
    "InvalidHandleValues": [ 0 ]
  },
  {
    "Namespace": "Windows.Win32.System.Threading",
    "Name": "TP_WORK",
    "ValueType": "IntPtr",
    "InvalidHandleValues": [ 0 ]
  },

Windows.Win32.System.Threading.TP_IO :  => [InvalidHandleValue(0),NativeTypedef]    
Windows.Win32.System.Threading.TP_IO.Value added
Windows.Win32.System.Threading.TP_TIMER :  => [InvalidHandleValue(0),NativeTypedef] 
Windows.Win32.System.Threading.TP_TIMER.Value added
Windows.Win32.System.Threading.TP_WAIT :  => [InvalidHandleValue(0),NativeTypedef]  
Windows.Win32.System.Threading.TP_WAIT.Value added
Windows.Win32.System.Threading.TP_WORK :  => [InvalidHandleValue(0),NativeTypedef]  
Windows.Win32.System.Threading.TP_WORK.Value added
```

**Comment by kennykerr** [comment]
Right, the docs only mention the `PTP_X` names - stick with that.

**Comment by mikebattista** [comment]
Could you take a look at https://github.com/microsoft/win32metadata/tree/mikebattista/threadingptptypes?

It looks to be consistent now with how PTP_POOL was implemented but given the odd definitions and changes to the [In][Out] attributes in the diff, it needs to be tested to make sure the dev experience is what you expect.

**Comment by kennykerr** [comment]
Sorry, I'm not sure how to check this without a winmd.

**Comment by mikebattista** [comment]
I sent you one offline.
