### ISSUE TITLE
Create a wiki or set of test cases for projection authors to track "interesting" types and functions

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#141]
This should go somewhere other than this issue, but I'll start the list:

`Windows.Win32.Security.PWLX_DIALOX_BOX`
https://docs.microsoft.com/en-us/windows/win32/api/winwlx/nc-winwlx-pwlx_dialog_box
This is a delegate that refers to another delegate (`Windows.Win32.MenuRc.DLGPROC`).

`Windows.Win32.Gdi.DISPLAYCONFIG_VIDEO_SIGNAL_INFO`
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-displayconfig_video_signal_info
This struct has it all in the layout and scope department. An anonymous union, an unnamed (but not anonymous) struct, bitfields, and a field, `videoStandard` that has different definitions in the anonymous union and the unnamed struct.

`Windows.Win32.MenuRc.WNDCLASSEXW`
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-wndclassexw
This is a struct that has a delegate as a field.

`Windows.Win32.MenuRc.Apis.SetWindowLongW`
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw
This function (both the A and W variants, along with `GetWindowLongW`) has a different definition appear for 32-bit and 64-bit fields:
- 32-bit: Exports `SetWindowLong` and `#define`s `SetWindowLongPtr` as `SetWindowLong`.
- 64-bit: Exports both `SetWindowLong` and `SetWindowLongPtr` as distinct functions.

**Comment by reflectronic** [comment]
D3D9 has this very interesting quirk in `d3d9types.h`:
```cpp
#if defined(_X86_) || defined(_IA64_)
#pragma pack(4)
#endif
```

I discovered this when I was doing my own auto-generation for the Windows SDK after a generated test caught this inconsistency. In practice, it only causes layout differences between architectures for structs which have members that are >= 8 bytes. I believe those are
- `D3DADAPTER_IDENTIFIER9`
- `D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT`
- `D3DMEMORYPRESSURE`
- `D3DPRESENTSTATS`

Unfortunately, there is no way to express this in ECMA-335 metadata, so the generator (and particularly C#/Win32) are put in a very uncomfortable spot.
