### ISSUE TITLE
`LookupPrivilegeValue`: Use an enum instead of `string` for the `lpName` parameter for ease of use

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1417]
https://learn.microsoft.com/en-us/windows/win32/secauthz/privilege-constants

Is it possible to create an enumeration for this, for example: SE_FLAGS?

**Comment by mikebattista** [comment]
No we don't support string-based enums. We can move these constants over to a more appropriate namespace though to improve discoverability.
