### ISSUE TITLE
case "__int64" cannot match in EnsureEnumSizeMatchesOriginalSize

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/win32metadata#1418]
There is `case "__int64"` in the ClangSharpSourceWinmdGenerator.EnsureEnumSizeMatchesOriginalSize method:
<https://github.com/microsoft/win32metadata/blob/37e2421db765f92c50444b53d4d76bd5060ce4b5/sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs#L388>

However, the `switch` statement calls `ToUpperInvariant`, so even if the string is "__int64" originally, it gets transformed to "__INT64" and cannot match the `case`:
<https://github.com/microsoft/win32metadata/blob/37e2421db765f92c50444b53d4d76bd5060ce4b5/sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs#L353>

I don't know whether the scraper finds any `__int64`-based enums in practice.

**Comment by elachlan** [comment]
Good Catch!
