### ISSUE TITLE
Bug: OUTLINETEXTMETRICW struct is incorrectly sized

### ISSUE THREAD

**Issue by psy-fidelious** [microsoft/win32metadata#1420]
### Which crate is this about?

windows

### Crate version

0.43

### Summary

The struct size of OUTLINETEXTMETRICW  in C++ is 232 bytes instead of 264 which is what std::mem::size_of::<OUTLINETEXTMETRICW>() returns in rust. 
This seems to cause issues with GetOutlineTextMetricsW which fails in rust with a zero return value, when a reference to this struct with the corresponding size is passed to it. This doesn't seem to occur in C++.
Curiously, if you call GetOutlineTextMetricsW with a nullptr argument, you get a required size of 318 in both C++ and rust which is higher than the size of what both languages report for those structs. I suppose some alignment is done behind the scenes, but it's clear that the underlying code checks for this exact struct size as well.

### Toolchain version/configuration

windows rust 1.66

### Expected behavior

The struct sizes between C++ and rust should match

**Comment by mikebattista** [comment]
Looks like another case of https://github.com/microsoft/win32metadata/issues/1330.
