### ISSUE TITLE
Generating metadata for `IInspectable`-derived interfaces is broken

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1426]
For example, the following IDL will cause the generator to produce invalid interface definitions with duplicate vtable entries:

```C++
[
    object,
    uuid(7dc67935-9dfc-4129-a33a-3784b4250569)
]
interface IFoo : IInspectable
{
    HRESULT SetFoo();
}
```

**Comment by riverar** [comment]
Steps to reproduce

In a developer command prompt, ...

1. `git clone https://github.com/riverar/repro_2d66609dd405`
2. `cd repro_2d66609dd405`
3. `dotnet build`
4. Inspect `Output.winmd` with ILSpy or other tooling
5. Observe incorrect interface methods were emitted

```csharp
[Guid(2980787302u, 29309, 19891, 150, 162, 23, 97, 60, 61, 39, 34)]
public interface ISimple : IInspectable
{
	new unsafe HRESULT GetIids([Out] uint* iidCount, [Out][NativeArrayInfo(CountParamIndex = 0)] Guid** iids);
	new unsafe HRESULT GetRuntimeClassName([Out] HSTRING* className);
	new unsafe HRESULT GetTrustLevel([Out] TrustLevel* trustLevel);
	HRESULT DoSomethingSimple();
}
```
