### ISSUE TITLE
Make it possible to customize MIDL parameters

### ISSUE THREAD

**Issue by abolade** [microsoft/win32metadata#1428]
The problem: MetadataTasks.dll currently uses hard-coded parameters for MIDL compilation. However, certain IDL files require that /notlb be specified as a parameter (e.g. those using system_handle(...) parameters on interface methods), as otherwise midl.exe fails with an error.

The proposed solution: Provide a build directive that allows MIDL parameters to be customized in the CompileIdls task, e.g.:

```
namespace MetadataTasks
{
    public class CompileIdls : Task
    {
< snip >
        public string MidlSwitches
        {
            get; set;
        }
```

**Comment by BenJKuhn** [comment]
I only have a cursory understanding of TLBs. For our purposes, is there any reason we can't just always pass /notlb? Are there IDLs that require that we generate them? Allowing customization seems like a reasonable plan either way.

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/pull/1432#issuecomment-1396230501 for PR and comment on changing the default.
