### ISSUE TITLE
GetVcDirPath.ps1 fails due to dependency on missing scripts

### ISSUE THREAD

**Issue by abolade** [microsoft/win32metadata#1429]
The CompileIdls task calls [GetVcDirPath.ps1](https://github.com/microsoft/win32metadata/blob/573bd9a1168a99f35301b3f86a319fe553eb5c7c/scripts/GetVcDirPath.ps1) which relies on scripts (e.g. [Get-VSPath.ps1](https://github.com/microsoft/win32metadata/blob/573bd9a1168a99f35301b3f86a319fe553eb5c7c/scripts/Get-VSPath.ps1)) that appear to be missing from the nuget package. It looks like [the nuspec](https://github.com/microsoft/win32metadata/blob/573bd9a1168a99f35301b3f86a319fe553eb5c7c/sources/GeneratorSdk/nuget/BuildSdk.nuspec) might not have been updated as part of a prior change to how the toolchain detection works.

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/commit/ebdd5f3d5d55f6deca76fc5cea3dde77bc799783#r97520664. Need to check for other missing scripts.

**Comment by mikebattista** [comment]
The PR that introduced these new scripts is https://github.com/microsoft/win32metadata/pull/942/files#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16e. You can see that 4 scripts were added which I believe is the full closure of missing scripts here.

Added them all to the nuspec and confirmed they are all included in the WinmdGenerator package.

Would be great if you could verify it works for you as expected.
