### ISSUE TITLE
Windows.UI.Xaml.Interop.h is not an interop header

### ISSUE THREAD

**Issue by reflectronic** [microsoft/win32metadata#143]
Currently, the tool generates metadata from `Windows.UI.Xaml.Interop.h`:
https://github.com/microsoft/win32metadata/blob/dc071257239b848481dc3aae5dc2c5bf5c76831a/generation/Partitions/WinRt/main.cpp#L35
However, `Windows.UI.Xaml.Interop` is a WinRT namespace, and that header is produced by MIDLRT from WinRT IDL. It is not supposed to follow the interop pattern like most of the other `.Interop.h` headers are; its members should be accessed by using a normal language projection. This line should be deleted from the file.

---

Incidentally, the same mistake was made for `Windows.UI.Web.Interop`:
https://github.com/microsoft/win32metadata/blob/dc071257239b848481dc3aae5dc2c5bf5c76831a/generation/Partitions/WinRt/main.cpp#L36
However, `Windows.UI.Web.Interop` happens to use parameterized interfaces in its API, so MIDLRT generates a bunch of template specializations that don't work in C#. This comment can be deleted, too.

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.4.
