### ISSUE TITLE
`WTSEnumerateSessions`: Annotate `hServer` as `[Optional]`

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1436]
Similarly with issue #1435

**Comment by riverar** [comment]
@mikebattista Looks like it, but beware of APIs like `WTSQueryListenerConfig`, `WTSVirtualChannelOpen` which _always_ take `NULL` (i.e. should be `[Reserved])`.

(WTSSetUserConfig, PSTR pServerName will also need Optional status.)
