### ISSUE TITLE
Use latest DirectX-Headers

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#1437]
The latest version of many of the D3D headers can be found at https://github.com/microsoft/DirectX-Headers, and it would be great if win32metadata could use these rather than the ones currently found in https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/RecompiledIdlHeaders.

It's not obvious what the right approach is for this, so opening this issue for discussion before anyone starts on a PR.  Also this would be a good opportunity to validate that this is the right thing to do.

Some options:

1. Use a submodule?
2. Manually submit a PR to update the headers under RecompiledIdlHeader.  How would this work the next time the WinSDK is updated?
3. Manually submit a PR to update the headers under some other location.

Maybe there's some other approaches that might work?

**Comment by mikebattista** [comment]
When we ingest a new SDK, we run https://github.com/microsoft/win32metadata/blob/main/scripts/RecompileIdlFilesForScraping.ps1 on an [SDK NuGet package](https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP) which recompiles everything and drops the output into the repo at https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/RecompiledIdlHeaders.

This is a manual task at this point, so we could (1) replace the related headers from the SDK NuGet package we're ingesting with the latest versions from the Agility SDK before running the script or (2) update that script to exclude headers from the SDK NuGet package and instead pull the headers from the Agility SDK repo. Either way, if we can script the process of excluding the headers from the SDK NuGet package and instead pull in the headers from the Agility SDK, then we'd always have the latest D3D headers included in the Win32Metadata.

**Comment by MarijnS95** [comment]
Don't forget to keep "agility" in mind when progressing this. When I filed https://github.com/microsoft/DirectX-Headers/pull/82, and as mentioned in the comments, the intent to have a minimal `.winmd` and Rust crate - **automatically generated by CI** - greatly increases our Rust adoption rate for new and experimental APIs.

Would love to get rid of the [current namespace clash](https://github.com/microsoft/DirectX-Headers/pull/82#issuecomment-1399599211) between `Windows.` and the suggested `Microsoft.{DirectX,Direct3D}` namespace for this by having updated headers in `win32metadata` and windows-rs, as long as it's easy/obvious and properly documented how to do an ingest of header updates (in a local fork) straight away.

**Comment by damyanp** [comment]
> Don't forget to keep "agility" in mind when progressing this ... the intent to have a minimal .winmd and Rust crate - automatically generated by CI - greatly increases our Rust adoption rate for new and experimental APIs.

@jenatali can correct me if I'm wrong here, but I don't think that experimental APIs ever make it to DirectX-Headers.  DirectX-Headers is kept up to date with the latest stable APIs and so there is an incredibly low rate of churn in these APIs.

FWIW, I'm not a fan of any solution that has a duplicate copy of all the D3D APIs in another namespace.  This doesn't capture the truth about developers should think about these APIs - `Windows...ID3D12Device` is the same interface as `Microsoft...ID3D12Device`, and so they should have the same name.  Making them different causes downstream problems when we try and mix and match modules that might be built against different versions of these.  For example, DirectStorage and DirectML both use `ID3D12Device` and it'd be pretty unpleasant if we end up having to build multiple variations of these in order to just reference the appropriate Windows/Microsoft variant.


> ...as long as it's easy/obvious and properly documented how to do an ingest of header updates (in a local fork) straight away.

Anything we do that just involves DirectX-Headers won't help with ingesting experimental APIs. I've thought about some solutions to this but they get pretty complicated pretty quickly.  Might be fun projects to work on, but would probably have minimal value in real life.  Things like - maybe win32metadata should consume the headers from the nuget packages, rather than from DirectX-Headers - and then maybe it should consume all the 'active' versions of these packages and do some kind of a merge so that it can identify the unique experimental APIs/types and put them into some kind of versioned preview namespace.  I think that could probably be made to work, but I'm not sure it would be worth it.  

Maybe there's some value in making win32metadata consume the DirectX headers from the Agility SDK though - in which case switching to one of the preview packages in a local fork should be as easy as updating a version number in something like a `packages.config` file.

**Comment by jenatali** [comment]
> I don't think that experimental APIs ever make it to DirectX-Headers. DirectX-Headers is kept up to date with the latest stable APIs and so there is an incredibly low rate of churn in these APIs.

That's not quite true. When a preview Agility SDK release is posted, the relevant headers are published here as well. There's not currently a distinction in the header itself for whether an API is considered stable or not. For example, enhanced barrier APIs were present in the [v1.606.4](https://github.com/microsoft/DirectX-Headers/blob/v1.606.4/include/directx/d3d12.idl) headers, even though they were unusable in the corresponding 1.606.4 version of the NuGet package. They could be used in the paired preview release though, 1.706.4. As of 1.608.0, these APIs are now considered stable.

This is the same pattern that has been used with Windows insider SDKs in the past. Insider SDK headers can occasionally contain APIs that are not necessarily final.

**Comment by damyanp** [comment]
> When a preview Agility SDK release is posted, the relevant headers are published here as well.

Thanks @jenatali, TIL.  I'm going to start off some conversations with the team here to figure out what the right thing to do is.

**Comment by MarijnS95** [comment]
> FWIW, I'm not a fan of any solution that has a duplicate copy of all the D3D APIs in another namespace.

The original idea was to "shadow" them (maintaining the same namespace), but by doing that in a different crate we still end up with duplicate types, and various APIs consuming either Rust-type-incompatible variant. Not to mention codegen expecting all other `Windows.X` namespaces to be available within the same crate, using `super::` references instead of `::windows::...`.

> but I'm not sure it would be worth it.

We need updated / updatable Rust bindings for the Agility SDK. If this doesn't achieve that I'll have to keep maintaining a fork that generates local `.winmd` bindings and a minimal wrapper crate. Alternatively I might be able to prepend that `.winmd` to windows-rs generation to cause it to use the first type it encounters, or some hack like that.
