### ISSUE TITLE
THREADINFOCLASS declares only 2 of many enum values

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1439]
The `THREADINFOCLASS` enum in the metadata defines only two of many enum values:

metadata:
```cs
public enum THREADINFOCLASS
{
	ThreadIsIoPending = 16,
	ThreadNameInformation = 38
}
```

[source](https://dev.azure.com/microsoft/OS/_search?action=contents&text=type%3ATHREADINFOCLASS%20%20ext%3Ah&type=code&filters=ProjectFilters%7BOS%7DRepositoryFilters%7Bos.2020%7D&pageSize=25&includeFacets=false&result=DefaultCollection/OS/os.2020/GBofficial/main//onecore/com/netfx/windowsbuilt/iso_legacy/base/inc/sdk/ntpsapi_x.h)
```c
typedef enum _THREADINFOCLASS {
    ThreadBasicInformation,
    ThreadTimes,
    ThreadPriority,
    ThreadBasePriority,
    ThreadAffinityMask,
    ThreadImpersonationToken,
    ThreadDescriptorTableEntry,
    ThreadEnableAlignmentFaultFixup,
    ThreadEventPair_Reusable,
    ThreadQuerySetWin32StartAddress,
    ThreadZeroTlsCell,
    ThreadPerformanceCount,
    ThreadAmILastThread,
    ThreadIdealProcessor,
    ThreadPriorityBoost,
    ThreadSetTlsArrayAddress,
    ThreadIsIoPending,
    ThreadHideFromDebugger,
    ThreadBreakOnTermination,
    ThreadSwitchLegacyState,
    ThreadTebInformation,
    ThreadIoPriority,
    ThreadIsJoinedToReserve,
    ThreadResourceManagement,
    ThreadPagePriority,
    MaxThreadInfoClass
    } THREADINFOCLASS;
```

**Comment by mikebattista** [comment]
The 2 values that are there appear to be the only 2 values defined in the SDK header. Are the others coming from the WDK?

**Comment by AArnott** [comment]
I don't know how to tell whether a given header file is in the SDK or WDK. But the link in the issue description shows just how many places this is defined, and nearly all of them have a much longer list than the metadata. The only 'short' def I could find didn't match the metadata either.

**Comment by mikebattista** [comment]
The only headers that matter are the ones at https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/RecompiledIdlHeaders which we get from the public SDK NuGet packages.

**Comment by AArnott** [comment]
If that's the public SDK, how come [this doc](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntsetinformationthread?source=recommendations) documents more than what's in the public SDK?

**Comment by mikebattista** [comment]
Those are WDK docs. That may contain more definitions.

**Comment by AArnott** [comment]
When an enum has values that are split across two worlds like this, how do we see CsWin32 generating code when the WDK _is_ available, when the 2 metadata winmd's each contain subsets of the same enum type? If one is 'complete' and one is partial, we still need a definitive plan for how to merge them in code generation.

**Comment by kennykerr** [comment]
Unless the WDK is merged with the SDK metadata, overlapping types would presumably be moved entirely into the SDK and the WDK would then depend on the SDK e.g. `Windows.Wdk.winmd` would refer to `Windows.Win32.winmd`.

**Comment by mikebattista** [comment]
Yes I'd expect any overlapping definitions would need to move to the SDK metadata.

**Comment by mikebattista** [comment]
Keeping this issue here since shared definitions should be consolidated into the SDK metadata.

**Comment by mikebattista** [comment]
Are these enums supposed to be int or uint?

**Comment by AArnott** [comment]
That's hard to say sometimes. I _did_ find this in one of the Windows headers:

```
typedef int THREADINFOCLASS;
```

So maybe go with `int`.

**Comment by mikebattista** [comment]
Thanks.
