### ISSUE TITLE
XML output format

### ISSUE THREAD

**Issue by nnemkin** [microsoft/win32metadata#144]
Please consider adding an alternative, XML-based output format.

WinMD is hard to work with and most languages don't have a WinMD reader.

**Comment by mikebattista** [comment]
This project will use winmd for the canonical format as it provides many benefits. That said, if others want to provide tools that translate the winmd into other formats like XML, we don't object to that.

**Comment by marler8997** [comment]
@nnemkin I'm maintaining such a tool that projects the winmd file to JSON if you're interested: https://github.com/marlersoft/win32json
