### ISSUE TITLE
DesiredAccess and FILE_ACCESS_FLAGS enums

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1440]
These two enums are defined in the metadata, and they are _nearly_ identical.

```diff
 [Flags]
-public enum DesiredAccess : uint
+public enum FILE_ACCESS_FLAGS : uint
 {
 	FILE_READ_DATA = 1u,
 	FILE_LIST_DIRECTORY = 1u,
 	FILE_WRITE_DATA = 2u,
 	FILE_ADD_FILE = 2u,
 	FILE_APPEND_DATA = 4u,
 	FILE_ADD_SUBDIRECTORY = 4u,
 	FILE_CREATE_PIPE_INSTANCE = 4u,
 	FILE_READ_EA = 8u,
 	FILE_WRITE_EA = 0x10u,
 	FILE_EXECUTE = 0x20u,
 	FILE_TRAVERSE = 0x20u,
 	FILE_DELETE_CHILD = 0x40u,
 	FILE_READ_ATTRIBUTES = 0x80u,
 	FILE_WRITE_ATTRIBUTES = 0x100u,
-	FILE_ALL_ACCESS = 0xF01FFu,
+	FILE_ALL_ACCESS = 0x1F01FFu,
 	DELETE = 0x10000u,
 	READ_CONTROL = 0x20000u,
 	WRITE_DAC = 0x40000u,
 	WRITE_OWNER = 0x80000u,
 	SYNCHRONIZE = 0x100000u,
+	STANDARD_RIGHTS_REQUIRED = 0xF0000u,
 	STANDARD_RIGHTS_READ = 0x20000u,
 	STANDARD_RIGHTS_WRITE = 0x20000u,
 	STANDARD_RIGHTS_EXECUTE = 0x20000u,
+	STANDARD_RIGHTS_ALL = 0x1F0000u,
+	SPECIFIC_RIGHTS_ALL = 0xFFFFu,
 	FILE_GENERIC_READ = 0x120089u,
 	FILE_GENERIC_WRITE = 0x120116u,
 	FILE_GENERIC_EXECUTE = 0x1200A0u
 }
```

These enums look worthy of consolidating. I believe `FILE_ACCESS_FLAGS` is the preferred name, and that one already has all the members.

Particularly interesting however is how `FILE_ALL_ACCESS` has different values between these enums. I'm guessing that's a bug. In the header files, this value is defined as:

```c
#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)
#define SYNCHRONIZE                      (0x00100000L)
```

So it appears that one enum defines the `FILE_ALL_ACCESS` value with `SYNCHRONIZE` while the other leaves it out. I can't imagine why that would be intentional, as it appears that the header files consistently apply the `SYNCHRONIZE` flag.
So all the more reason to:

* [ ] Delete `DesiredAccess` and redirect all users of it over to `FILE_ACCESS_FLAGS`.

And speaking of users of this enum, [`NtCreateFile`](https://learn.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile) could use some love:
* [ ] `DesiredAccess` parameter is currently declared as `uint`, but it ought to be as this `FILE_ACCESS_FLAGS` enum.
* [ ] `FileAttributes` parameter should be declared as `FILE_FLAGS_AND_ATTRIBUTES`.

**Comment by mikebattista** [comment]
Where do you see DesiredAccess in the metadata?

**Comment by AArnott** [comment]
> Where do you see DesiredAccess in the metadata?

Doh! That's ILSpy for you, which keeps loading other dlls and then showing those types and making me think they came from the metadata. Sorry about that. 

@KalleOlaviNiemitalo may have a good point. Perhaps we need a unique enum type for the `FileAttributes` parameter. But at this point given my prior mistake about `DesiredAccess`, I'll close this issue and open a fresh one to discuss `NtCreateFile` enums.
