### ISSUE TITLE
winspool.drv APIs missing SetLastError attribute

### ISSUE THREAD

**Issue by rul3rst4** [microsoft/win32metadata#1446]
## Actual behavior

Some methods from the Winspool.drv are not generated with SetLastError true, even tho the docs says that they should generate errors.

## Expected behavior

The methods to be generated with SetLastError = true.

## Repro steps

Some examples:

![image](https://user-images.githubusercontent.com/37764417/213885102-dadfc5d9-5374-464a-afbb-56cf7d6c6aca.png)
This method is alright.

![image](https://user-images.githubusercontent.com/37764417/213885120-5d664d0f-687d-46ce-823c-ce2fc105e628.png)
But this one is not, and the docs says that it generates error in some cases: https://learn.microsoft.com/en-us/windows/win32/printdocs/addprinter

Does someone know why this happens? Should i fill an issue to the metadata team? Is this the expected behavior, and if so, why?

Thanks!

### Context

- CsWin32 version: [e.g. `0.4.422-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by riverar** [comment]
The linked AddPrinter documentation says nothing about setting the last error value. So this will require someone at Microsoft to go look at the implementation.

**Comment by kennykerr** [comment]
`AddPrinterW` does call `SetLastError`.

**Comment by riverar** [comment]
Great, thanks @kennykerr!

**Comment by mikebattista** [comment]
Is it just AddPrinter that needs a change?

**Comment by kennykerr** [comment]
I think we need a better way to figure out whether `SetLastError` is called by an API. For example, [GetProcessHeap](https://learn.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-getprocessheap)'s documentation says that it does but that function is guaranteed to succeed and never calls `SetLastError`.

**Comment by rul3rst4** [comment]
> Is it just AddPrinter that needs a change?

No, i was just cleaning a list that we have here at the company to give the methods that we are almost sure that call SetLastError because of the nature of the errors that they emit in specific scenarios:

Here is the list:
AddPort
AddMonitor
AddPrinter
AddPrinterDriver
ClosePrinter
DeleteMonitor
DeletePort 
DeletePrinter
EnumJobs
EnumPrinterDrivers
EnumPrinters
GetPrinter
GetSpoolFileHandle
OpenPrinter
SetPort
SetPrinter
