### ISSUE TITLE
SHFILEINFOW has `ushort[]` fields instead of `char[]` 

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#145]
SHFILEINFOW contains two fixed length char arrays, but the metadata represents each as `ushort` arrays instead. This is a huge usability problem for C# users.

**Comment by AArnott** [comment]
The `DISPLAY_DEVICEW` struct has the same problem.

**Comment by AArnott** [comment]
The `DEVMODEW` struct has the same problem.

**Comment by Herohtar** [comment]
Looking at the generated code, this seems to be a general problem with anything that has the type `WCHAR[]`.

**Comment by AArnott** [comment]
Ya, I'd very much like all the wchar types to be represented as `char` rather than `ushort`. The places where `ushort` in the metadata are correctly projected as `char` in C# do so because an attribute was added, but places are missing that attribute.
