### ISSUE TITLE
Bug: ID3D12GraphicsCommandList::ClearRenderTargetView pRects should be marked optional

### ISSUE THREAD

**Issue by chyyran** [microsoft/win32metadata#1453]
https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearrendertargetview

`pRects` is not indicated as optional

```cpp
void ClearRenderTargetView(
  [in] D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView,
  [in] const FLOAT [4]             ColorRGBA,
  [in] UINT                        NumRects,
  [in] const D3D12_RECT            *pRects
);
```

However in the documentation

> [in] pRects
> 
> Type: const D3D12_RECT*
>
> An array of D3D12_RECT structures for the rectangles in the resource view to clear. If NULL, ClearRenderTargetView clears the entire resource view.

Because it isn't marked optional, it is impossible to pass in `None` in windows-rs so the `NULL` behaviour is not obtainable.

**Comment by MarijnS95** [comment]
1.5 years later: it looks like you forgot about [`ID3D12GraphicsCommandList::ClearDepthStencilView()`](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-cleardepthstencilview), which has the same semantics.

https://github.com/microsoft/win32metadata/pull/1971
