### ISSUE TITLE
Type definitions for AttribiteUsageAttribute

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1455]
Compare and contrast ILSpy's display of the `AttributeUsage` attribute on these two functions (note the `System.` on the latter):

```csharp
// Windows.Win32.Interop.AgileAttribute
[AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = true)]
public sealed class AgileAttribute : Attribute
```

```csharp
// Windows.Foundation.Metadata.ActivatableAttribute
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
public sealed class ActivatableAttribute : Attribute
```

I'm uncertain of what is going on here but an underlying difference is that `Windows.winmd` contains an (extern) definition for `AttributeUsageAttribute` whereas `Windows.Win32.Interop.winmd` does not. `Windows.winmd` also contains a definition `AttributeTargets`, which is the first argument for `AttributeUsageAttribute`.

This means that `Windows.winmd` is somewhat more self-contained (you don't need to include the core lib just to parse the attribute). Whereas `Windows.Win32.Interop.winmd` requires an outside definition of `AttributeUsageAttribute`.

For this reason I prefer the `Windows.winmd` behaviour and would like to extend that to `Windows.Win32.Interop.winmd` if possible. That would make it easier to parse the metadata without also needing to source a core lib (either `mscorlib` or `System.Private.CoreLib`, the two winmd files disagree on this as well). And this would still allow finding the actual types, if needed.

### `AttributeUsage` (`Windows.Win32.Interop.winmd`)

```
Windows.Win32.Interop.AgileAttribute
Windows.Win32.Interop.ComOutPtrAttribute
Windows.Win32.Interop.CppAttributeList
Windows.Win32.Interop.FreeWithAttribute
Windows.Win32.Interop.InvalidHandleValueAttribute
Windows.Win32.Interop.NativeEncodingAttribute
Windows.Win32.Interop.NativeInheritanceAttribute
Windows.Win32.Interop.NativeTypeNameAttribute
Windows.Win32.Interop.RetValAttribute
Windows.Win32.Interop.StaticLibraryAttribute
Windows.Win32.Interop.SupportedOSPlatformAttribute
```

### `System.AttributeUsage` (`Windows.winmd`)

```
Windows.Foundation.Metadata.ActivatableAttribute
Windows.Foundation.Metadata.AllowForWebAttribute
Windows.Foundation.Metadata.AllowMultipleAttribute
Windows.Foundation.Metadata.ApiContractAttribute
Windows.Foundation.Metadata.AttributeNameAttribute
Windows.Foundation.Metadata.AttributeUsageAttribute
Windows.Foundation.Metadata.ComposableAttribute
Windows.Foundation.Metadata.ContractVersionAttribute
Windows.Foundation.Metadata.CreateFromStringAttribute
Windows.Foundation.Metadata.DefaultAttribute
Windows.Foundation.Metadata.DefaultOverloadAttribute
Windows.Foundation.Metadata.DeprecatedAttribute
Windows.Foundation.Metadata.DualApiPartitionAttribute
Windows.Foundation.Metadata.ExclusiveToAttribute
Windows.Foundation.Metadata.ExperimentalAttribute
Windows.Foundation.Metadata.FastAbiAttribute
Windows.Foundation.Metadata.FeatureAttribute
Windows.Foundation.Metadata.GCPressureAttribute
Windows.Foundation.Metadata.GuidAttribute
Windows.Foundation.Metadata.HasVariantAttribute
Windows.Foundation.Metadata.InternalAttribute
Windows.Foundation.Metadata.LengthIsAttribute
Windows.Foundation.Metadata.MarshalingBehaviorAttribute
Windows.Foundation.Metadata.MetadataMarshalAttribute
Windows.Foundation.Metadata.MuseAttribute
Windows.Foundation.Metadata.NoExceptionAttribute
Windows.Foundation.Metadata.OverloadAttribute
Windows.Foundation.Metadata.OverridableAttribute
Windows.Foundation.Metadata.PreviousContractVersionAttribute
Windows.Foundation.Metadata.ProtectedAttribute
Windows.Foundation.Metadata.RangeAttribute
Windows.Foundation.Metadata.RemoteAsyncAttribute
Windows.Foundation.Metadata.StaticAttribute
Windows.Foundation.Metadata.ThreadingAttribute
Windows.Foundation.Metadata.VariantAttribute
Windows.Foundation.Metadata.VersionAttribute
Windows.Foundation.Metadata.WebHostHiddenAttribute
Windows.UI.Xaml.StyleTypedPropertyAttribute
Windows.UI.Xaml.TemplatePartAttribute
Windows.UI.Xaml.TemplateVisualStateAttribute
Windows.UI.Xaml.Data.BindableAttribute
Windows.UI.Xaml.Markup.ContentPropertyAttribute
Windows.UI.Xaml.Markup.FullXamlMetadataProviderAttribute
Windows.UI.Xaml.Markup.MarkupExtensionReturnTypeAttribute
Windows.UI.Xaml.Media.Animation.ConditionallyIndependentlyAnimatableAttribute
Windows.UI.Xaml.Media.Animation.IndependentlyAnimatableAttribute
```

**Comment by riverar** [comment]
A related discussion: https://github.com/microsoft/win32metadata/issues/472

**Comment by ChrisDenton** [comment]
In that issue it seems that the types existed in Windows.Win32.Interop whereas these types do not.

Tbh I'm really all that concerned about precisely how the three metadata files are organised. But I would quite like to be able to read the generated metadata without needing to also obtain and parse .NET dlls or having to create my own definitions.

**Comment by kennykerr** [comment]
Unless you have a .NET parser, it's not very practical to deeply inspect the `System` types. In ECMA-335, all such `TypeRef`s should point to a row in the `AssemblyRef` table where you will typically find an assembly named `mscorlib` or `netstandard` but then you need to track that down somehow. I generally just enlighten my parsers with the knowledge of the base `System` types and treat them as special or speudo types and not bother to look up their definitions during parsing. That frees me from having a dependency on the .NET Framework. 

If you really want to do it, you can usually find an OS copy of mscorlib lying around that you can include. For example:

C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

**Comment by mikebattista** [comment]
I didn't do anything specific for this in the above PR. We're referencing .NET Attribute and AttributeUsage types like we reference other System types elsewhere.

**Comment by ChrisDenton** [comment]
That's brilliant, thanks!
