### ISSUE TITLE
`CreateFile` does not generate generic access flags

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/win32metadata#1457]
## Actual behavior

As the title implies, referencing `CreateFile` does not generate `GENERIC_READ` and `GENERIC_WRITE` for `FILE_ACCESS_FLAGS`. They don't exist, and I'm forced to create my own:

```cs
const FILE_ACCESS_FLAGS GENERIC_WRITE = (FILE_ACCESS_FLAGS)0x4000_0000;
const FILE_ACCESS_FLAGS GENERIC_READ = (FILE_ACCESS_FLAGS)0x8000_0000;
```

## Expected behavior

Said flags are generated into the enum.

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFileW
```

### Context

- CsWin32 version: `0.2.188-beta`
- Target Framework: `net7.0`

**Comment by mikebattista** [comment]
These generic constants are used across various ACCESS_FLAGS scenarios, and we can't define them in each enum, so generally the enums would have to each have a unique version of these with a prefix qualifier.

**Comment by AArnott** [comment]
Bummer. I guess an artificial prefix would be preferable to just omitting them though.

**Comment by mikebattista** [comment]
This enum already has `FILE_GENERIC_READ` and others which according to https://learn.microsoft.com/en-us/windows/win32/secauthz/generic-access-rights is the equivalent of `GENERIC_READ`. Am I missing something?

**Comment by mikebattista** [comment]
So is this existing FILE_GENERIC_READ no good? It comes directly from the headers, and it also is squatting on the good name we'd use for this.

**Comment by AArnott** [comment]
> This enum already has FILE_GENERIC_READ and others which according to https://learn.microsoft.com/en-us/windows/win32/secauthz/generic-access-rights is the equivalent of GENERIC_READ. 

I don't see `FILE_GENERIC_READ` mentioned in that doc at all. Where do you see that doc equate that to `GENERIC_READ`?

I'd _really_ like to see `GENERIC_READ` declared as a member of the `FILE_ACCESS_FLAGS` enum. The fact that some languages don't support enums and flatten them to constants that would collide shouldn't impair all the other languages, IMO. 
If we must add a distinguishing prefix to the name to add it to the enum, can we also add an attribute to that enum value to document what its original name was so that CsWin32 can restore it to its original name?

**Comment by mikebattista** [comment]
> For example, a Windows file object maps the GENERIC_READ bit to the READ_CONTROL and SYNCHRONIZE standard access rights and to the FILE_READ_DATA, FILE_READ_EA, and FILE_READ_ATTRIBUTES object-specific access rights.

`FILE_GENERIC_READ` is defined as exactly this.

**Comment by AArnott** [comment]
Oh, you're looking at the headers for the definition and realizing it's equal to another symbol. 

What do we gain by their having equal values today?

**Comment by mikebattista** [comment]
https://github.com/microsoft/win32metadata/blob/14af8148e46df4a203fd06ba1636f868240a34f6/generation/WinSDK/RecompiledIdlHeaders/um/winnt.h#L14324-L14328

It's encoded in the header. I didn't design the API.

**Comment by AArnott** [comment]
Oh no, I get it. I just wonder what solution to our metadata problem you were proposing based on their values being equal? I can't think of any.

**Comment by mikebattista** [comment]
FILE_GENERIC_READ is encoded in the headers and follows our guidelines for enums, duplicate constants, and preferred names, so I would recommend using that.

**Comment by AArnott** [comment]
But folks reading the docs will look for `GENERIC_READ`. There's nothing on the surface to tell them that `FILE_GENERIC_READ` makes an adequate substitute. It also doesn't put it inside the enum, so C# users will at best come up with a solution like @colejohnson66.

**Comment by colejohnson66** [comment]
In my case, I was opening a serial port (`lpFileName` being something like `"\\.\COM3"`). Using `FILE_GENERIC_READ | FILE_GENERIC_WRITE` did not work for my case. I think the HRESULT was access denied? Only when I used `GENERIC_READ | GENERIC_WRITE` did it work.

**Comment by mikebattista** [comment]
Ok. Thanks for clarifying.

These are loose constants today, so we could move them into FILE_ACCESS_RIGHTS if that would cover the majority case. For projections that promote enum members to global constants, that shouldn't have any impact. For projections that use the enums, if you want to use these GENERIC constants in other scenarios, you'll need to get them from this enum.

**Comment by kennykerr** [comment]
One problem is that the generic constants are typically used with a broader set of APIs, so lumping them inside some API-specific enum would make it harder to use with those other APIs.

**Comment by mikebattista** [comment]
> For projections that use the enums, if you want to use these GENERIC constants in other scenarios, you'll need to get them from this enum.

Yes that's what I meant by this.

We can either move these GENERIC constants into 1 enum and force everyone else to use this enum as well, or we keep them as loose constants. Right now they're in the SystemServices namespace, but we could move them to Windows.Win32.Foundation so they are more discoverable/accessible.

**Comment by AArnott** [comment]
Or we can define them in every applicable enum, with an artificial prefix plus an attribute so that projections have the option to remove the prefix.

**Comment by riverar** [comment]
CreateFile incorrectly describes the desired access parameter as some sort of file-specific enum (FILE_ACCESS_FLAGS). Remember CreateFile is used to access way more than just files.

I'm having a hard time following what the proposed solution here so I propose the following actions:

1. Create `GENERIC_ACCESS_RIGHTS` (or equiv.) uint enum containing
  * GENERIC_READ
  * GENERIC_WRITE
  * GENERIC_EXECUTE
  * GENERIC_ALL

2. Create `FILE_ACCESS_RIGHTS` (or equiv.) uint enum containing
  * FILE_READ_DATA
  * FILE_WRITE_DATA
  * ...

3. Change CreateFile to accept `uint`, not `FILE_ACCESS_RIGHTS`.

**Comment by mikebattista** [comment]
Don't you lose autocomplete and the ability to pull in the dependent constants automatically by doing that?

**Comment by AArnott** [comment]
Good point about CreateFile dealing with more than just files.

Your breakdown of enums makes sense, at least in isolation. But it makes the CreateFile experience in C# worse, IMO, for the reason @mikebattista just mentioned. I wish C# had union types and we could say "anything from either of these enums".

**Comment by mikebattista** [comment]
I agree the current naming is misleading and was part of the original confusion in this issue.

**Comment by AArnott** [comment]
I don't like what it does to C#, but @riverar's proposal feels like the most defensible solution. And while `uint` will make it a little harder for folks to use `CreateFile` (at least in C#), at least we can reason about the model and enum naming. And I don't know how to build a more usable API while still have a sound justification for how we model it.

**Comment by kennykerr** [comment]
There's no perfect solution. I think what Rafael suggested is at least better than the alternatives. Personally, I'd stick with the original API definitions and make these all `uint` constants, but what Rafael proposes at least gives you collections of constants - which C# seems to prefer - without going so far as to make life much more confusing for other languages.

**Comment by riverar** [comment]
This API is bad and has many overloaded scenarios, so trying to model it is going to be difficult. I'm not opposed to adding metadata to improve the C# authoring experience but let's take it one step at a time.

1. Clean up the definitions ([see earlier](https://github.com/microsoft/win32metadata/issues/1457#issuecomment-1468832445))
2. Explore adding metadata to assist with overload generation in C# (e.g. `[ThisParamCanAlsoBe(FileAccess, Generic, etc.)]` or maybe use some enum inheritance)

**Comment by colejohnson66** [comment]
You don't necessarily need an `Either` type. What's wrong with generating multiple overloads? Have one that's the current one, and another that takes a `GENERIC_ACCESS_RIGHTS`. Internally, it would cast to uint before P/Invoking.

**Comment by AArnott** [comment]
Multiple overloads is something we can look at, but the metadata doesn't do that today, and in general doing overloads for various parameter types could lead to a combinatorial explosion. So at least I tend to shy away from it.

The metadata certainly could include a hint attribute. But I'm not ready to commit that CsWin32 will consume it, as we have other higher priority work. Until we have a projection committed to consuming it, I lean against adding it to the metadata.
