### ISSUE TITLE
WinVerifyTrust API response type response constants don't have right type in rust

### ISSUE THREAD

**Issue by m0rv4i** [microsoft/win32metadata#1458]
Hi, 

For [WinVerifyTrust](https://learn.microsoft.com/en-us/windows/win32/api/wintrust/nf-wintrust-winverifytrust) the return value has been correctly redeclared as a long (u32 in rust) as opposed to a HRESULT (i32 in rust).

The `WinVerifyTrust` function and response constants (`TRUST_E_NOSIGNATURE` etc need redefining with the correct type of `u32`) .

**Comment by mikebattista** [comment]
@kennykerr / @riverar 

Could you clarify the spec here? These functions return int (long) in the metadata. And the TRUST_E constants are defined as HRESULTs (int) per the headers.

**Comment by m0rv4i** [comment]
Hey, thanks both. What I'm trying to say is that the type of HRESULT and any associated constants should be changed to a u32. Some of the response value constants are greater than i32 max value (0x7FFFFFFF), e.g. https://referencesource.microsoft.com/#System.Windows.Forms/parent/parent/parent/public/Internal/NDP/Inc/mansign.cs,67

**Comment by riverar** [comment]
The docs are confusing because WinVerifyTrust can (and commonly does these days) hand off to a third-party trust provider. And when those fail, they can return anything. The current return value (i32) looks correct to me.

**Comment by mikebattista** [comment]
Agreed. Everything looks correct to me.

**Comment by m0rv4i** [comment]
Apologies guys, just to check my understanding then how should this API be used?

The response values are greater than i32 and need to cast to u32 to be checked, e.g. this code errors:
![image](https://user-images.githubusercontent.com/20513519/222533266-d06c01ba-6544-4c76-b5df-b486062eaf88.png)

with the expected `literal does not fit into i32`:

![image](https://user-images.githubusercontent.com/20513519/222533407-be7ceea1-d152-4837-8d5b-a28bb6ade5a9.png)

Instead I need to cast it as here:

![image](https://user-images.githubusercontent.com/20513519/222533531-3076ba35-514c-443a-b41d-c40781709361.png)

Is this all as expected then? (Genuine question).

**Comment by riverar** [comment]
You can't do much here other than

```rust
match unsafe { WinVerifyTrust(HWND::default(), std::ptr::null_mut(), std::ptr::null_mut()) }
{
    0 => todo!(),
    _ => panic!("Failed.") 
}
```

Remember, it may return non-HRESULTs so comparing against them is not worth your time.

**Comment by m0rv4i** [comment]
In general for sure, in my case the the point of the tool is to detail invalid certs (and why they're invalid, if known!) hence the verbose output, but I understand your point. Thanks for responding!

**Comment by riverar** [comment]
@m0rv4i Ah. So perhaps something like

```rust
let return_value = unsafe { WinVerifyTrust(HWND::default(), std::ptr::null_mut(), std::ptr::null_mut()) };

// Warning: return_value may not be a valid HRESULT
match HRESULT(return_value)
{
    TRUST_E_SYSTEM_ERROR => panic!("Possible error: System error."),
    _ => todo!()
}
```
