### ISSUE TITLE
SHGetFileInfo needs flags

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/win32metadata#146]
The last parameter of `SHGetFileInfo` takes a flags argument. That needs metadata for it.

**Comment by E021ntox** [comment]
SHGetFileInfo is missing the intptr version.

```
[DllImport("shell32.dll", CharSet = CharSet.Auto)]
public static extern IntPtr SHGetFileInfo(
    **IntPtr** pszPath,
    uint dwFileAttributes,
    ref SHFILEINFO psfi,
    uint cbFileInfo,
    uint uFlags);
```

https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shgetfileinfoa#shgfi_pidl-0x000000008

@mikebattista @AArnott
