### ISSUE TITLE
LoadLibrary returns nint instead of SafeHandle

### ISSUE THREAD

**Issue by zgabi** [microsoft/win32metadata#147]
LoadLibrary generates the following:
`        public static unsafe nint LoadLibrary(string lpLibFileName)
`
The result should be a SafeHandle.

The PInvoke project contains the following:
`        public static extern SafeLibraryHandle LoadLibrary(string lpFileName);
`

**Comment by AArnott** [comment]
It looks like `HMODULE` is defined in headers but not in metadata. HMODULE should be annotated as being released via `FreeLibrary`.

**Comment by zgabi** [comment]
Same for the SetWindowsHookEx

**Comment by AArnott** [comment]
@zgabi, thanks for that extra feedback. Can you please create a new issue for each API? It makes it easier to track and thus less likely to slip between the cracks.

**Comment by AArnott** [comment]
Note while doing this that while `GetModuleHandle` also returns `HMODULE`, we do *not* want to return a SafeHandle in .NET because it does not increment the ref count on the module, and a SafeHandle would decrement the ref count leading to a module to be unloaded prematurely (https://github.com/dotnet/pinvoke/issues/563). So we need a way to annotate the return value so that the C# projection keeps `HMODULE` (once it too stops returning IntPtr) instead of replacing it with `SafeHandle`.

**Comment by zgabi** [comment]
Why don't you return SafeHandle for GetModuleHandle with ownsHandle=false... it won't release the handle in this case in the Dispose (or finalizer).
Of course it still needs an annotation that the return value owns the handle or not.

About SetWindowsHookEx: I'm creating a separate issue now.

**Comment by AArnott** [comment]
> Why don't you return SafeHandle for GetModuleHandle with ownsHandle=false

As discussed in the dotnet/pinvoke project, the .NET marshaler doesn't allow this. At least not with any built-in behavior. Maybe through a custom marshaler that could be achieved, I don't know. And yes, we could wrap the extern method with another that does the work.

Why would we do this though? It adds an unnecessary allocation to the call. Would it be so the return type can be readily used by other APIs that only take SafeHandle parameters?

**Comment by zgabi** [comment]
>  It adds an unnecessary allocation to the call.

This unnecessary allication is also there if it is created automatically by the marshaler.

My "problem" is that the module(*) parameter of this call is very long. So it should be simplified somehow.. maybe with adding some explicit or implicit operators to convert an IntPtr to each XXXSafeHandle.

```
                    _hCtrl = PInvoke.CreateWindowEx(Constants.WS_EX_NOPARENTNOTIFY,
                        "Button",
                        "&Settnigs",
                        Constants.WS_TABSTOP | Constants.WS_VISIBLE | Constants.WS_CHILD | Constants.WS_GROUP,
                        10, 10, 88, 24, _hDlg,
                        new DestroyMenuSafeHandle((IntPtr) 3, false),
                        new FreeLibrarySafeHandle(PInvoke.GetModuleHandle((string)null), false),
                        null);

```
(*) it is HINSTANCE instead of HMODULE, but they are the same in Win32.

**Comment by sotteson1** [comment]
> Note while doing this that while `GetModuleHandle` also returns `HMODULE`, we do _not_ want to return a SafeHandle in .NET because it does not increment the ref count on the module, and a SafeHandle would decrement the ref count leading to a module to be unloaded prematurely ([dotnet/pinvoke#563](https://github.com/dotnet/pinvoke/issues/563)). So we need a way to annotate the return value so that the C# projection keeps `HMODULE` (once it too stops returning IntPtr) instead of replacing it with `SafeHandle`.

Andrew, how do you want me to handle this for GetModuleHandle? Do I need to add an attribute to the return parameter that says the resource isn't owned?

**Comment by AArnott** [comment]
>  Do I need to add an attribute to the return parameter that says the resource isn't owned?

Yes, that way we can still return a richer handle type than `IntPtr` that projections can then have more options of what to do with. We may find `out` parameters or return values as well on other functions where we wish to indicate non-ownership (e.g. `GetCurrentProcess()`) to apply the attribute to as well.

**Comment by marler8997** [comment]
I've run into this issue. I want to make sure I understand the current plan.  As I understand it, the plan is to modify functions like `LoadLibrary` and `GetModuleHandle` to return the `HMODULE` type, but annotate the function to indicate the return type is not "owned".

**Comment by kennykerr** [comment]
`LoadLibrary` and `GetModuleHandle` are different. The former increments the reference count while the latter does not.

**Comment by AArnott** [comment]
@marler8997 See #244 for how we'll distinguish between owned and non-owned handles.

**Comment by sotteson1** [comment]
This was fixed by a recent change. LoadLibrary now return HINSTANCE. GetModule also return HINSTANCE but with the DoNotRelease attribute. HINSTANCE and HMODULE are equivalent and can be used in the same functions, so I just changed all the HMODULEs to be HINSTANCE in the metadata.

**Comment by marler8997** [comment]
@scotteson1 So the method gets annotated with `DoNotRelease`?  How would a projection know which parameter and/or return type the `DoNotRelase` attribute is applying to?  Does it indicate which parameter and/or if it applies to the return type?

**Comment by sotteson1** [comment]
> @scotteson1 So the method gets annotated with `DoNotRelease`? How would a projection know which parameter and/or return type the `DoNotRelease` attribute is applying to? Does it indicate which parameter and/or if it applies to the return type?

For GetModuleHandle it's on the return:

````C#

[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
[return: DoNotRelease]
public static extern HINSTANCE GetModuleHandleA([Optional][In][Const] PSTR lpModuleName);
````

**Comment by marler8997** [comment]
I see, the attribute is on the return type and/or parameter itself, not the method. Thanks.
