### ISSUE TITLE
D3D Pack attribute based on CPU architecture

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#148]
D3D9 has this very interesting quirk in `d3d9types.h`:
```cpp
#if defined(_X86_) || defined(_IA64_)
#pragma pack(4)
#endif
```

I discovered this when I was doing my own auto-generation for the Windows SDK after a generated test caught this inconsistency. In practice, it only causes layout differences between architectures for structs which have members that are >= 8 bytes. I believe those are
- `D3DADAPTER_IDENTIFIER9`
- `D3DAUTHENTICATEDCHANNEL_QUERYOUTPUTID_OUTPUT`
- `D3DMEMORYPRESSURE`
- `D3DPRESENTSTATS`

Unfortunately, there is no way to express this in ECMA-335 metadata, so the generator (and particularly C#/Win32) are put in a very uncomfortable spot.

_Originally posted by @reflectronic in https://github.com/microsoft/win32metadata/issues/141#issuecomment-764947167_

**Comment by AArnott** [comment]
Can we add an attribute to these types so projections can add the necessary code?
Although in this case, I suppose it makes it impossible for a consumer to target AnyCPU once they define these types.

**Comment by kennykerr** [comment]
Duplicate of #384

**Comment by AArnott** [comment]
@kennykerr I see other issues closed as duplicates, but you closed then reopened this one. Was that on purpose?

**Comment by kennykerr** [comment]
I meant to leave it for you to close, in case you had any further concerns. 😜

**Comment by AArnott** [comment]
Nah.
