### ISSUE TITLE
IWMDMEnumStorage::Next has faulty CountParamIndex attribute value

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1484]
[The `IWMDMEnumStorage::Next` method](https://learn.microsoft.com/en-us/windows/win32/api/mswmdm/nf-mswmdm-iwmdmenumstorage-next) is declared like this in the metadata:

```cs
HRESULT Next([In] uint celt, [Out][NativeArrayInfo(CountParamIndex = 2)] IWMDMStorage* ppStorage, [Out] uint* pceltFetched);
```

The `CountParamIndex = 2` suggests that the length of the array passed *in* is determined by an *out* parameter. It should be `CountParamIndex = 0`. 

As additional evidence, I call on all the other enumeration COM interfaces (there are many).

From `IEnumTASK` and a couple others:

```cs
HRESULT Next([In] uint celt, [Out][NativeArrayInfo(CountParamIndex = 0)] MMC_TASK* rgelt, [Out] uint* pceltFetched);
HRESULT Next([In] uint celt, [Out][NativeArrayInfo(CountParamIndex = 0)] BSTR* ppStrings, [Optional][In][Out] uint* pceltFetched);
HRESULT Next([In] uint celt, [Out][NativeArrayInfo(CountParamIndex = 0)] Guid* rgelt, [Optional][Out] uint* pceltFetched);
```

**Comment by mikebattista** [comment]
The SAL parser doesn't parse the original SAL annotations in the headers. It parses what ClangSharp outputs in the `CppAttributeList` attribute. Below is what we need to parse for `IWMDMEnumStorage::Next`.

```
Name=SAL_name; p1=\"__RPC__out_ecount_part\"; p2=\"\"; p3=\"1.2\"^
Name=SAL_begin^
Name=SAL_name; p1=\"__RPC__out_ecount\"; p2=\"\"; p3=\"1.2\"^
Name=SAL_begin^
Name=SAL_name; p1=\"_Out_writes_\"; p2=\"\"; p3=\"2\"^
Name=SAL_begin^
Name=SAL_name; p1=\"_Pre_cap_\"; p2=\"\"; p3=\"1.1\"^
Name=SAL_begin^
Name=SAL_pre^
Name=SAL_notref^
Name=SAL_null; p1=__no^
Name=SAL_pre^
Name=SAL_writableTo; p1=elementCount(celt)^
Name=SAL_end^
Name=SAL_post^
Name=SAL_valid^
Name=SAL_end^
Name=SAL_name; p1=\"_Post_writable_size_\"; p2=\"\"; p3=\"2\"^
Name=SAL_begin^
Name=SAL_post^
Name=SAL_writableTo; p1=elementCount(celt)^
Name=SAL_end^
Name=SAL_end^
Name=SAL_name; p1=\"_Post_readable_size_\"; p2=\"\"; p3=\"2\"^
Name=SAL_begin^
Name=SAL_post^
Name=SAL_readableTo; p1=elementCount(*pceltFetched)^
Name=SAL_post^
Name=SAL_valid^
Name=SAL_end^
Name=SAL_end
```

I found one bug here that fixes this instance but breaks others. Variations of `__RPC__` definitions seem to be problematic.

If anyone is a SAL expert, it would help to better understand the relationship between `pre`, `post`, `deref`, `writableTo`, and `readableTo` and how that relates to various SAL annotations like the `__RPC__` variations.

The general problem is that some SAL annotations result in multiple `writableTo` and `readableTo` attributes, and our current logic that generates the `NativeArrayInfo` attribute from these doesn't always pick the right one.
