### ISSUE TITLE
RPC_WSTR is not defined

### ISSUE THREAD

**Issue by ynkdir** [microsoft/win32metadata#1486]
RPC_WSTR (and RPC_CSTR) is not defined in metadata.  And ushort* is used for RPC_WSTR variable.

For example:

```
public unsafe static extern RPC_STATUS RpcStringBindingComposeW([Optional][In] ushort* ObjUuid, [Optional][In] ushort* ProtSeq, [Optional][In] ushort* NetworkAddr, [Optional][In] ushort* Endpoint, [Optional][In] ushort* Options, [Optional][Out] ushort** StringBinding);
```

It might be useful if RPC_WSTR is defined.  I'm not sure that it should be ushort* or wchar_t*.

**Comment by byehack** [comment]
not a bug from this repo, solved by https://github.com/ynkdir/py-win32more/issues/2#issuecomment-1465049680

**Comment by kennykerr** [comment]
Yes, `RPC_CSTR` maps to `PSTR` and `RPC_WSTR` maps to `PWSTR`.

**Comment by ynkdir** [comment]
Thank you.
