### ISSUE TITLE
Where is an MIT-licensed `Windows.Win32.winmd` file?

### ISSUE THREAD

**Issue by dagood** [microsoft/win32metadata#1488]
* https://github.com/microsoft/win32metadata/issues/766

That issue was partially resolved: https://github.com/microsoft/win32metadata/issues/766#issuecomment-1150295736

> * Yes, the NuGet is licensed weirdly (Windows SDK license). You can get the same files at https://github.com/microsoft/win32metadata/tree/main/scripts/BaselineWinmd to workaround that until it's changed.

That directory no longer exists as of https://github.com/microsoft/win32metadata/pull/1056, and I can't find any winmd files in the repo. [Microsoft.Windows.SDK.Win32Metadata/44.0.17-preview](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/44.0.17-preview) still only contains the Windows SDK license.

---

I'm working on using win32metadata to generate Go's Windows syscalls, but the license is a concern:

* https://github.com/golang/go/issues/43838

I believe Go needs to be able to have a reproducible build without online access, so needs to have the winmd file checked into Go repositories. (Or checking in the whole nuget package, etc.) Copying the source code and building from that doesn't seem reasonable to me, given the .NET dependency.

How can Go get the artifacts in a distributable form?

**Comment by kennykerr** [comment]
You can download the winmd files here: https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/ 

The nuget package is just a zip file containing the winmd files. 

If you need an explicit MIT/Apache license, the [windows-rs](https://github.com/microsoft/windows-rs) project provides a copy of the [winmd files here](https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default).
