### ISSUE TITLE
v45 has a number of regressions around parameter attributes

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1493]
A lot of churn in this release. Not sure why, but some are a little concerning. For example:

* `IMXNamespaceManager.getAllowOverride` was `[retval][out]` but is now `[in][out]`. Many more such examples like all of `IMXNamespacePrefixes`'s members. 
* `IEnumPortableDeviceConnectors.Next` incorrectly changes from 0 to 2. Another example is `IEnumPortableDeviceObjectIDs`. There are many others.
* A lot of new optional parameters that I don't see in the headers such as `IPortableDeviceContent.CreateObjectWithPropertiesOnly`.
* `IWSDServiceMessaging.SendResponse`'s `pOperation` parameter was `[in]` and now it's `[in][out]`.

Many many more regressions that I can't ingest this release.

**Comment by mikebattista** [comment]
The headers had many SAL annotation changes. I spot checked several and they all looked legit.

**Comment by mikebattista** [comment]
v45 included an update to the 22621 SDK (https://github.com/microsoft/win32metadata/issues/1049). From looking at the diffs, there were lots of SAL annotation changes in the headers.

I need to check if something happened during the ingestion of the SDK.

**Comment by mikebattista** [comment]
Yes it's primarily just SAL annotation changes with a handful of removals that seem ok looking at the original 22621 headers.

The new APIs that were requested are still there.

**Comment by mikebattista** [comment]
I'll push an update later once the latest main build completes.
