### ISSUE TITLE
Move rometadata APIs to `WinRT.Metadata`

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1494]
I would put these in a nested namespace like `WinRT.Metadata` since they're hardly ever needed (I never use them) whereas the WinRT types are often needed by WinRT interop APIs.

_Originally posted by @kennykerr in https://github.com/microsoft/win32metadata/issues/240#issuecomment-1470195998_

**Comment by mikebattista** [comment]
@kennykerr @timsneath 

To clarify, which of the below headers should move to a Metadata subnamespace?

https://github.com/microsoft/win32metadata/blob/e840d77c7077f674250a1e8b6655b14211d41d55/generation/WinSDK/Partitions/WinRT/settings.rsp#L14-L48

**Comment by kennykerr** [comment]
Also: 

* RoMetadataApi.h

**Comment by timsneath** [comment]
I think @kennykerr's list is complete. For me (selfishly), if you have the types in this folder, we will be all set: https://github.com/timsneath/winmd/tree/main/lib/src/com

**Comment by mikebattista** [comment]
Yes looks like we have all of those now.

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/commit/4d23306c81363d1dc5fe4f4766065ff20be6cf5e#diff-55fb5d5eced0797538c3656ccb571f46d8b46bddc0688f66ea459a6499e148fa.

**Comment by timsneath** [comment]
Y'all are on fire this week! Literally half the messages in my inbox this morning were related to long-requested improvements to Win32Metadata. Thank you x1000!
