### ISSUE TITLE
Add MSCoreEE exports to the metadata

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1495]
This was in #240, but that issue was hijacked to track something else. Let's have _this_ issue now actually track addition of metadata, whether in Win32Metada itself or another winmd, to describe the functions exported from MSCoreEE.

Example of functions from MSCorEE that we use in Visual Studio and would like to replace with projection-provided imports:
- `GetFileVersion`
- `GetRequestedRuntimeInfo`

You can see several more functions that people over the years have cared enough to contribute to dotnet/pinvoke by hand: https://github.com/dotnet/pinvoke/blob/main/src/MSCorEE/MSCorEE.cs

**Comment by kennykerr** [comment]
Sounds like these are .NET specific (not WinRT specific) APIs that ship with the OS? Are they even part of the Windows SDK?

<img width="456" alt="image" src="https://user-images.githubusercontent.com/9845234/225359601-99994efc-ab55-4417-8070-27c7ffcec3d8.png">

**Comment by kennykerr** [comment]
No objections to adding them - just curious.

**Comment by AArnott** [comment]
I don't know what constitutes proper Windows SDK vs. Windows-shipped binaries that are somehow not in the Windows SDK but are in others. 
But the question was originally discussed in #240 in the earlier comments, and it sounded like it was _not_ in the proper Windows SDK, though FWIW a bunch of .NET tools ship under "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64" which suggests to me that it _would_ be part of a Windows SDK, but whatever. The SDK boundaries in Windows is _not_ something I'm familiar with.

Anyway, that's why in the issue description above I mention I'm open to the header files being described in a distinct winmd apart from win32metadata. 

Given one of our goals is to replace the need for dotnet/pinvoke, and that describes mscoree, I'd love to get CsWin32 to generate mscoree bindings, but for that we need a winmd.
I believe this repo already builds more winmd's than just win32metadata, so in this issue I pose the question as to whether mscoree might also fit under this umbrella somewhere?

**Comment by mikebattista** [comment]
Could you clarify what headers and what libs are involved here and where they come from?

**Comment by AArnott** [comment]
From [here](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/clrcreateinstance-function) it looks like MetaHost.h and mscoree.lib are at least involved. And then [from another section](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/corbindtoruntimeex-function) I see references to MSCorEE.h.

As to where they come from, I'm not exactly sure since most of my use for these APIs are done in C# where .lib nor .h file are required.

**Comment by mikebattista** [comment]
Ok. What namespace do you think these APIs should live under?

**Comment by riverar** [comment]
I think stuffing those APIs into `Windows.Win32.System.LibraryLoader` makes a lot of sense, given more/less that's the function of the mscoree.dll shim/bootstrapper these days.

**Comment by AArnott** [comment]
I dunno, looking at the list of functions there are quite a few that don't seem to be load library related. And given some of the function names don't mention CLR in them in any way, if the namespace also didn't suggest such a thing, it might be hard to recognize that one of these functions is related to the CLR. 
What about `Windows.Win32.System.ManagedLibraryLoader` instead? Or `CorEE`?

**Comment by kennykerr** [comment]
Wouldn't something like "Win32.DotNet.Hosting" be more appropriate? 

https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/

**Comment by mikebattista** [comment]
Looking at the docs you linked, I'd recommend `Windows.Win32.System.ClrHosting` which aligns with the docs and is consistent with the `Windows.Win32.System.Diagnostics.ClrProfiling` namespace I already added.

**Comment by riverar** [comment]
I'd hate to burn "Clr" or "DotNet" on old inbox shims though. None of these APIs apply to current dotnet right? Just .NET Framework?

**Comment by mikebattista** [comment]
I'm not too concerned about that. `ClrHosting` is what I'd start with here.

**Comment by mikebattista** [comment]
I started this at https://github.com/microsoft/win32metadata/tree/mikebattista/clrhosting but hit a bunch of compilation errors if someone wants to take it from there.

**Comment by AArnott** [comment]
ClrHosting sounds good. "DotNet" definitely not. The CLR is decidely referencing the .NET Framework, whereas .NET is nowadays referring to Core CLR (behind .NET 6+ nowadays).

**Comment by riverar** [comment]
@mikebattista Pushed some changes to your branch https://github.com/microsoft/win32metadata/commit/57e769fcb525b42ab6e38d8a6b6f2d289b3bbf2c, compiles and emits but fails the duplicate constant test. How do you want to handle this one?

```
 Duplicate constants/enum names detected:
 EALL
   Windows.Win32.Media.Audio.EDataFlow
   Windows.Win32.System.ClrHosting.EApiCategories
```

**Comment by mikebattista** [comment]
Awesome. Thanks!

In this case I'll just add an exception in https://github.com/microsoft/win32metadata/blob/main/tests/Windows.Win32.Tests/assets/duplicateConstantsAllowList.rsp.

**Comment by AArnott** [comment]
Thank you, @riverar and @mikebattista!
