### ISSUE TITLE
Handles are discarding type information and turning into void*

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#15]
I thought that handles such as HANDLE, HWND, etc used the DECLARE_HANDLE macro to define them and their types, to protect against accidental mixing. So HWND isn't typedef'd as void*, but as

struct HWND__ { int unused; }; typedef HWND__* HWND;

Let's try to preserve this typing in some way.

**Comment by sotteson1** [comment]
Handles are strongly typed now.
