### ISSUE TITLE
Discussion:  IDEs and large module sizes

### ISSUE THREAD

**Issue by rasta-mouse** [microsoft/win32metadata#1500]
I'm raising this more as a discussion point, rather than a bug.  There are several namespaces within the metadata that are so large that IDEs struggle to handle intellisense and code analysis for them.  Although workarounds are possible within the IDEs, I wanted to open a discussion around the possibility of partitioning some of the larger ones, as suggested by @kennykerr.

Some related issues for reference:
- https://github.com/microsoft/windows-rs/issues/2368
- https://github.com/intellij-rust/intellij-rust/issues/9680

**Comment by mikebattista** [comment]
Which namespaces are problematic?

**Comment by riverar** [comment]
Or is IntelliJ's default of ~2.5MB just too low? Seems the community runs into this a lot https://stackoverflow.com/search?q=idea.max.intellisense.filesize

**Comment by kennykerr** [comment]
There are only a small handful of modules that end up over 2.5MB. These are the worst offenders:

* Windows.Win32.Media.DirectShow
* Windows.Win32.Media.MediaFoundation
* Windows.Win32.System.Diagnostics.Debug
* Windows.Win32.UI.Shell

**Comment by rasta-mouse** [comment]
@riverar Yeah, perhaps. I don't know if the same issue extends to other IDEs or if it's just JetBrains.  As I said, I just raised it as a discussion.  If the general consensus is that it's not worth it or too much work to address at this level, then I'm totally cool with that.

**Comment by mikebattista** [comment]
We could move the MsTv partition to Windows.Win32.Media.DirectShow.Tv.

**Comment by kennykerr** [comment]
`Windows.Win32.System.Diagnostics.Debug` is currently the most problematic as it comes up quite often and is just huge. The few headers included in that namespace are all very big. Could we experiment with putting each into its own sub namespace?

**Comment by mikebattista** [comment]
I could see moving the 2 debugger extension headers to a .Extensions subnamespace. I'll start with that for the next release.

**Comment by kennykerr** [comment]
That namespace also contains `IActiveScript` and friends. Those aren't even Windows APIs.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.interop?view=visualstudiosdk-2019

Can we move those out of `Debug` as well?

**Comment by mikebattista** [comment]
There's another partition in Debug that I missed earlier.

https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/Partitions/Debug/settings.rsp

I think the APIs you're talking about are coming from all the `activ*` headers. Are you saying we should just exclude those?

**Comment by mikebattista** [comment]
I don't know if the VS APIs you linked are the same, these seem to be related to Windows Script Host. In any case, I could move all those `activ*` headers to an .ActiveScript subnamespace.

**Comment by kennykerr** [comment]
Sounds good.

**Comment by mikebattista** [comment]
Debug and DirectShow have been refactored. The others will require some domain expertise to tease apart if at all, so I will leave them alone for now.

Closing for now as it sounds like the most problematic issues have been addressed. Feel free to reactivate if the changes aren't enough or you have more concrete feedback on the other namespaces.
