### ISSUE TITLE
Bug: BluetoothFindFirstDevice return value differs from MSDN doc

### ISSUE THREAD

**Issue by levigross** [microsoft/win32metadata#1507]
### Which crate is this about?

windows

### Crate version

0.46.0

### Summary

Hello,

Sorry if this isn't an issue and I just don't understand the windows API (thanks in advance for your patience and help)

The function `BluetoothFindFirstDevice` is declared as:
```
pub unsafe fn BluetoothFindFirstDevice( pbtsp: *const BLUETOOTH_DEVICE_SEARCH_PARAMS, pbtdi: *mut BLUETOOTH_DEVICE_INFO ) -> isize
```

Source: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Devices/Bluetooth/fn.BluetoothFindFirstDevice.html 

In MSDN it is listed as:

```
HBLUETOOTH_DEVICE_FIND BluetoothFindFirstDevice(
  const BLUETOOTH_DEVICE_SEARCH_PARAMS *pbtsp,
  BLUETOOTH_DEVICE_INFO                *pbtdi
);
```

https://learn.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice 

I think this is a bug, because that function should return `HBLUETOOTH_DEVICE_FIND`

### Toolchain version/configuration

 rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\user\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.68.0 (2c8cc3432 2023-03-06)

### Expected behavior

`BluetoothFindFirstDevice` returns `HBLUETOOTH_DEVICE_FIND`

### Actual behavior

`BluetoothFindFirstDevice` returns `isize`

**Comment by levigross** [comment]
Wow! Thanks for the amazing and fast turn around!!

Final question: when will this be released into the windows rust crate?

**Comment by kennykerr** [comment]
I can ingest it into the windows-rs repo as soon as there's another release of the Win32 metadata.

**Comment by levigross** [comment]
@kennykerr I really hope I am not bothering you. I really appreciate your hard work and don't want to be a nuisance. 

I believe that there was another release of win32metadata: https://github.com/microsoft/win32metadata/releases/tag/v47.0.26-preview . As I only see preview releases I am wondering if this release qualifies. 

Thanks!

**Comment by mikebattista** [comment]
Which regressions? There's only 1 change really since v47 and that was an updated fix to an API that was already broken.

**Comment by kennykerr** [comment]
I think the outstanding fix was #1509.

**Comment by mikebattista** [comment]
Right but weren't those APIs broken before the partial fix?

**Comment by kennykerr** [comment]
@levigross ok, was able to ingest the latest version here: https://github.com/microsoft/windows-rs/pull/2400

**Comment by levigross** [comment]
Thanks 😊
