### ISSUE TITLE
SetWindowsHookEx returns nint insead of SafeHandle

### ISSUE THREAD

**Issue by zgabi** [microsoft/win32metadata#151]
SetWindowsHookEx generates the following:
`internal static extern nint SetWindowsHookEx(int idHook, HOOKPROC lpfn, FreeLibrarySafeHandle hmod, uint dwThreadId);
`The result should be a SafeHandle.

**Comment by AArnott** [comment]
It appears the release function is `UnhookWindowsHookEx` and the handle name is HHOOK.

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.4.
