### ISSUE TITLE
Use modern naming conventions

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1510]
I've never liked the naming conventions used by Win32 APIs like using Hungarian notation for parameters or using all-caps names for types and enum values. These are painful to look at and not very modern. I believe this project is an opportunity to modernise everything, so please consider changing the naming convention.

**Comment by sylveon** [comment]
The metadata is generated from scrapping the Windows SDK header. Diverging from that sounds like recipe for problems and inconsistencies.

**Comment by riverar** [comment]
Hi @JaiganeshKumaran, I marked this as enhancement so we don't lose track of it. But am going to close this for now as it's not in scope of what win32metadata is trying to do. Right now, the team is focused on modeling the original APIs (aligned with headers and docs) and adding _metadata_ to make those APIs easier to use, project into other languages, etc.

**Comment by JaiganeshKumaran** [comment]
Another thing to consider is projections should use the normal naming convention used in the language. Both WinJS and Rust/WinRT did this though now because of Win32 APIs they have reversed the decision for Rust.

**Comment by JaiganeshKumaran** [comment]
It's also time to throw away most of the custom type aliases in Win32. Just write wchar_t const* instead of L(PCWSTR), uint32_t instead of DWORD (DWORD will probably remain 32-bit forever) etc...
