### ISSUE TITLE
Merge Win32 and WinRT Metadata

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1511]
In a WinRT component, I should be able to define both C-style types, classic COM types and WinRT types in an IDL file. This will make things more unified.

```cpp
namespace MyRuntimeComponent
{
   // picked up tools parsing Win32 Metadata
    void SomeCFunction();
    
    interface ISomeComInterface : IUnknown
    {
        Int32* Pointer { get; }; // [propget] HRESULT get_Pointer([out, retval] int* value);
    }
    
    interface ISomeWinRTInterface : IInspectable
    {
        Int32 Number { get; };
    }
}
```

Another idea that will reduce the need for manual interop interfaces is to enable declaring that a WinRT runtime class implements a COM interface in metadata. Language projections that don't deal with COM and only WinRT, should ignore it, but those which do should make it just work like a regular WinRT interface.

```idl
interface IInitializeWithWindow
{
    void Initialize(HWND windowHandle); // HRESULT Initialize(HWND windowHandle);
}

runtimeclass FileOpenPicker : IInitializeWithWindow
{
}

// In C++/WinRT
FileOpenPicker openPicker;
openPicker.Initialize(windowHandle); 
// Before: check_hresult(openPicker.as<IInitializeWithWindow (from interop header header)>()->Initialize(windowHandle);

// In JavaScript (no COM support without IDispatch)
let fileOpenPicker = FileOpenPicker()
fileOpenPicker.Initialize(windowHandle); // Error: initialize method doesn't exist.
```

**Comment by riverar** [comment]
Don't think there's anything actionable here for _Win32_ metadata, so closing for now. Will tag and add @mikebattista for awareness.
