### ISSUE TITLE
CreateThread function (processthreadsapi.h) constants are missing

### ISSUE THREAD

**Issue by wieslawsoltes** [microsoft/win32metadata#152]
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createthread

e.g.: CREATE_SUSPENDED etc.

and are not generated when put in NativeMethods.txt

**Comment by sotteson1** [comment]
I added a new enum THREAD_CREATION_FLAGS and mapped it to the parameter in CreateThread.
