### ISSUE TITLE
Add aliases for `RTL_CONDITION_VARIABLE`, `RTL_SRWLOCK` and `RTL_RUN_ONCE`

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1522]
Some Win32 types are simply aliases for NT types. Maybe we should preserve that in the metadata? Currently they are only named with their NT name, which is confusing if you're reading the docs (e.g. [SleepConditionVariableSRW](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepconditionvariablesrw)).

|Win32 name|NT name|
|--|--|
|`CONDITION_VARIABLE`|`RTL_CONDITION_VARIABLE`|
|`SRWLOCK`|`RTL_SRWLOCK`|
|`INIT_ONCE`|`RTL_RUN_ONCE`|

**Comment by mikebattista** [comment]
Need more details on how this would be represented in the metadata.

**Comment by mikebattista** [comment]
Related discussion at https://github.com/microsoft/win32metadata/issues/1517#issuecomment-1497753460.

**Comment by mikebattista** [comment]
It seems everywhere these are used they are referred to with the Win32 names. Should we just rename the RTL_ structs to remove the prefix?
