### ISSUE TITLE
Should `NTSTATUS` constants be collected together?

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1524]
Should `NTSTATUS` constants be collected into an enum? Or maybe grouped in some other way? I guess this is a question for projection authors.

From what I recall the reasons for not doing so in the past included:

* An `NTSTATUS` code is not really an integer. In C terms it's a bit-field struct, even though it's often treated as an integer. So projections may want to add extra methods for decomposing the bits rather than treating it strictly as an enumeration.
* `NTSTATUS` codes are open ended. Third parties can define new ones that won't be represented in the metadata.

Is that a fair summary?

I do feel that `NTSTATUS` codes should be collected in some way. And an enum makes sense to me, given the other sorts of open ended enums we have. But maybe there's a better way to namespace known values? Or maybe people feel the status quo is the best option?

**Comment by mikebattista** [comment]
They're already basically collected under Windows.Win32.Foundation and all begin with a predictable prefix `STATUS_`.

**Comment by ChrisDenton** [comment]
Hm, we do have an `WIN32_ERROR` enum. I guess projections could manually collect them together. Though that would require special casing.

**Comment by mikebattista** [comment]
WIN32_ERROR values today are uint. NTSTATUS is a typedef struct. Also currently we don't use enums for open ended sets.

**Comment by ChrisDenton** [comment]
Fair enough.
