### ISSUE TITLE
Missing constant for arm64 architecture

### ISSUE THREAD

**Issue by xverge** [microsoft/win32metadata#1529]
On windows-rs, in the Debug module there are processor architecture constants, [however it is lacking a constant for arm64](https://github.com/microsoft/windows-rs/blob/81b7b8cf3925dc589a5bc8dc5b6a750cf81654b2/crates/libs/windows/src/Windows/Win32/System/Diagnostics/Debug/mod.rs#L7718-L7731), which is [in the win32 documentation.](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info#:~:text=PROCESSOR_ARCHITECTURE_ARM64)

**Comment by riverar** [comment]
Isn't missing but rather in a different namespace https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/SystemServices/constant.PROCESSOR_ARCHITECTURE_ARM64.html
