### ISSUE TITLE
Typedefs appear to be lost in the translation

### ISSUE THREAD

**Issue by roblabla** [microsoft/win32metadata#153]
Hey all,

I was looking at the Win32 metadata in ILSpy, and the first thing that jumped at me is that many typedefs are missing from the new representation. To give just one example among many others: `MsiSetPropertyW`' is defined in the headers as:

```c
UINT WINAPI MsiSetPropertyW(MSIHANDLE hInstall,
	LPCWSTR   szName,       // property identifier, case-sensitive
	LPCWSTR   szValue);     // property value, null to undefine property
```

But in the WinMD file, it is defined as:

```cs
[DllImport("msi", ExactSpelling = true)]
public unsafe static extern uint MsiSetPropertyW(uint hInstall, [Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* szName, [Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* szValue);
```

Notice that hInstall is defined as simply being an `uint`. The typedefs here gives some nice information about the provenance of the handle, and could in theory be used to generate wrappers that wrap the uint into a struct to provide RAII semantics for instance.

**Comment by sotteson1** [comment]
Fixed with 10.0.19041.5-preview.5.
