### ISSUE TITLE
Ideally, there would be a distinct attribute for these "invented" handle types

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1533]
Ideally, there would be a distinct attribute for these "invented" handle types, like `MEMORYMAPPEDVIEW_HANDLE`, to distinguish them from native types defs that are actually defined in the Windows SDK. Without this, languages like C++ and Rust that aim to preserve the original definitions more faithfully are now stuck not being able to distinguish between something like `PSID` which is actually defined by the Windows SDK and `MEMORYMAPPEDVIEW_HANDLE` which is not. I thought this was what the `NativeTypeDef` attribute was for but perhaps I misunderstood.

_Originally posted by @kennykerr in https://github.com/microsoft/win32metadata/issues/561#issuecomment-1503504854_

**Comment by mikebattista** [comment]
There are many manufactured NativeTypeDefs. How would you want those treated?

**Comment by kennykerr** [comment]
Yes, I'm not sure how you'd untangle it as the metadata is increasingly tailored for the non-systems language consumers and you wouldn't want to break that. I may just fix this on my end.

**Comment by mikebattista** [comment]
Below are all the manufactured `[NativeTypeDef]` structs.

How do we want to handle these assuming we want to reserve `[NativeTypeDef]` only for cases where a native typedef exists in the headers?

These all should still support `AlsoUsableFor`, `RAIIFree`, and `InvalidHandleValue`. Should we just use a different attribute besides `[NativeTypeDef]` as I believe you were suggesting? What should we call it?

```
BoundaryDescriptorHandle
CONTROLTRACE_HANDLE
CreatedHDC
CriticalPolicySectionHandle
DnsContextHandle
EventLogHandle
EventSourceHandle
FilterFindHandle
FilterInstanceFindHandle
FilterVolumeFindHandle
FilterVolumeInstanceFindHandle
FindChangeNotificationHandle
FindFileHandle
FindFileNameHandle
FindStreamHandle
FindVolumeHandle
FindVolumeMountPointHandle
FIRMWARE_TABLE_ID
GetDcContextHandle
HdcMetdataEnhFileHandle
HdcMetdataFileHandle
HeapHandle
HwtsVirtualChannelHandle
IcmpHandle
LOADIMAGE_HANDLE
NamespaceHandle
NetEnumHandle
PerfProviderHandle
PerfQueryHandle
PROCESSTRACE_HANDLE
RELOGSTREAM_HANDLE
sa_family_t
ShFindChangeNotificationHandle
TimerQueueHandle
UPDATERESOURCE_HANDLE
```
