### ISSUE TITLE
`ReadFile(Ex)` has a different buffer type to `WriteFile(Ex)`

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1534]
Currently `ReadFile` uses a `void*` pointer to a byte buffer whereas `WriteFile` uses a `byte*` buffer. I believe they should both use a `byte*` buffer as they are both defined in terms of bytes. From the headers:
```c
// `void*` in the `ReadFile` metadata
_Out_writes_bytes_to_opt_(nNumberOfBytesToRead, *lpNumberOfBytesRead) __out_data_source(FILE) LPVOID lpBuffer,
```
```c
// `byte*` in the `WriteFile` metadata
_In_reads_bytes_opt_(nNumberOfBytesToWrite) LPCVOID lpBuffer,
```

The same goes for `ReadFileEx`.

**Comment by T-256** [comment]
> I believe they should both use a `byte*` buffer as they are both defined in terms of bytes.

I'm trying to pass structure as parameter but typechecker don't allow me to do it.
Current solution for me is custom imlementation where `lpBuffer: LPCVOID`.

**Comment by ChrisDenton** [comment]
Which typechecker? You should be able to cast to bytes. The only reason not to would be if the structure contains uninitialised padding (well you still can but for a lot of reasons you shouldn't).

**Comment by T-256** [comment]
> Which typechecker?

python projection ([win32more](https://github.com/ynkdir/py-win32more))


> You should be able to cast to bytes.

thanks, it worked:
```py
from ctypes import cast, pointer, sizeof, POINTER
from win32more import UInt32, Byte


def _cast(obj, ctype):
    return cast(pointer(obj), POINTER(ctype)).contents


def main()
    instance = ExampleStructure()
    written = UInt32()
    WriteFile(
        handle,
        _cast(instance, Byte),
        sizeof(instance),
        pointer(written),
        None,
    )
```

However, I'd like to have `VoidPtr` here, but no problem, I accept extra casting.
