### ISSUE TITLE
`FILE_RENAME_*` flags are missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1539]
A bunch of `FILE_RENAME_*` constants are missing from the metadata. 
They are documented here:
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information#members

I *do* see 3 of these flags, except their names have an injected `FLAG_` substring that isn't in the documentation, and made it difficult to find them in the metadata:

FILE_RENAME_FLAG_POSIX_SEMANTICS
FILE_RENAME_FLAG_REPLACE_IF_EXISTS
FILE_RENAME_FLAG_SUPPRESS_PIN_STATE_INHERITANCE

Can we rename these three, add the rest, and (bonus points) wrap them in an enum that's used in the structure documented above?

**Comment by ChrisDenton** [comment]
Those are the NT names. The Win32 names have the `_FLAG` part. This is a docs bug IMHO  The win32 types still aren't documented so people refer to the NT types.

**Comment by mikebattista** [comment]
Those constants are in the WDK metadata.
