### ISSUE TITLE
windows::Win32::System::Rpc::NdrClientCall2

### ISSUE THREAD

**Issue by byehack** [microsoft/win32metadata#1543]
Ref: https://learn.microsoft.com/en-us/windows/win32/api/rpcndr/nf-rpcndr-ndrclientcall2
1. PFORMAT_STRING not defined.
2. cannot set `...` parameter for client side call stack.

**Comment by kennykerr** [comment]
This is probably a `windows-rs` issue as I don't currently detect `vararg` functions.

**Comment by byehack** [comment]
> This is probably a `windows-rs` issue as I don't currently detect `vararg` functions.

True. `__arglist` parameter in winmd even isn't in method definition in rust [crate](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Rpc/fn.NdrClientCall2.html).

**Comment by kennykerr** [comment]
I started working on this (https://github.com/microsoft/windows-rs/pull/2457) but ran into a Rust compiler bug that's blocking this from actually rolling out (https://github.com/rust-lang/rust/issues/110505).

**Comment by kennykerr** [comment]
And I found a workaround that you can try here: https://github.com/microsoft/windows-rs/pull/2458
