### ISSUE TITLE
IKsPin missing IID?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1548]
If i'm not mistaken IKsPin seems to be missing it's IID (COM Implementation).

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ksproxy/nn-ksproxy-ikspin

`The IID for this interface is IID_IKsPin.`

**Comment by mikebattista** [comment]
What headers do you include to use ksproxy.h?

**Comment by Zerowalker** [comment]
I belive it's these:

`ks.h`, `ksmedia.h`

**Comment by mikebattista** [comment]
We include those already but there's an `#ifdef __STREAMS__` defined below that excludes most of the file.

https://github.com/microsoft/win32metadata/blob/cdbe515afad4f97205e941cffe35436c73d14392/generation/WinSDK/RecompiledIdlHeaders/shared/ksproxy.h#L269

Is that supposed to be set manually or included by some other header file?

**Comment by riverar** [comment]
To add to the confusion, it doesn't seem defined anywhere in the newer DirectX Agility SDK either.

**Comment by mikebattista** [comment]
I was able to get it working defining `__STREAMS__` manually and also including `strmif.h`.
