### ISSUE TITLE
Remove duplicate IIDs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1549]
These XmlLite GUIDs are already associated with the respective interfaces, so these can just be removed. 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/9845234/233407895-ef3734f2-dad5-4adf-95f0-cb94bc147cc3.png">

A quick scan reveals there are quite a few duplicate constants:

https://gist.github.com/kennykerr/3d332f03a4b64a6a1f21e81743e99f5f

Some may be valid but there are likely quite a few that are redundant. There are even some duplicates across Win32 and WDK metadata.

**Comment by mikebattista** [comment]
Duplication across SDK and WDK is expected at the moment. There should be other duplicate constants as well.

The rest just look like legitimate definitions in the headers.

**Comment by mikebattista** [comment]
Filed https://github.com/microsoft/wdkmetadata/issues/33 to track removing duplicate constants from the WDK metadata.
