### ISSUE TITLE
IMAGE_OPTIONAL_HEADER32 should have enum, whose constants are also missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#155]
The [IMAGE_OPTIONAL_HEADER32](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header32) struct defines 3 fields that should be represented as enums. The values for these enums are missing from metadata even as constants.

The `DataDirectory` field is a fixed size array with constants that define indexes into the array for well-known entries. The constants are missing from the metadata.

**Comment by sotteson1** [comment]
I think I accidentally mistook this for another IMAGE_ struct I fixed.
