### ISSUE TITLE
Missing FILE_ACCESS_FLAGS enum (regression?)

### ISSUE THREAD

**Issue by plonkaadam** [microsoft/win32metadata#1553]
After upgrading CsWin32 from version 0.2.188-beta (using metadata 40.0.14) to version 0.2.206-beta (metadata 46.0.5) it stopped generating code for `FILE_ACCESS_FLAGS` enum in `Windows.Win32.Storage.FileSystem`.

**Comment by riverar** [comment]
In the future, please file CsWin32 issues at https://github.com/microsoft/CsWin32.

@AArnott is there a metadata issue here?

**Comment by plonkaadam** [comment]
Last time I created issue in that repository and it got moved here.
I believe it's a problem with metadata as it still worked with metadata 44.0.17, after upgrading the metadata package alone to 45.0.21 or any newer it stops working.

**Comment by plonkaadam** [comment]
Ok after comparing the changes between releases https://github.com/microsoft/win32metadata/compare/v44.0.17-preview...v45.0.21-preview I see it got renamed to `FILE_ACCESS_RIGHTS` in https://github.com/microsoft/win32metadata/issues/1457

**Comment by AArnott** [comment]
@riverar this was indeed a metadata 'issue'. However it is by design as discussed in https://github.com/microsoft/CsWin32/issues/893.

**Comment by riverar** [comment]
Just wanted to make sure you get first crack at CsWin32 reports. 🖖
