### ISSUE TITLE
Bug: Unable to disambiguate between items with the same name in a namespace

### ISSUE THREAD

**Issue by Jake-Shadle** [microsoft/win32metadata#1554]
### Which crate is this about?

windows-bindgen

### Crate version

HEAD

### Summary

If 2 or more items have the same name within the same namespace, it's currently implementation defined which one will be emitted, and which ones will be skipped.

### Expected behavior

When binding `Windows.Win32.UI.Input.KeyboardAndMouse.VK_F` I expected to get the `VK_F: VirtualKey` constant.

### Actual behavior

The current standalone code walks items in this order:

1. Typedefs for enums/structs/unions.
2. Functions
3. Constants
4. Enum typedef fields -> Constants

So when binding `Windows.Win32.UI.Input.KeyboardAndMouse.VK_F`, the item that is found and emitted is not the `VK_F` virtual key code constant, but rather this struct (due to the current order), also in the same namespace.

```rust
pub struct VK_F {
    pub Vk: u8,
    pub NLSFEProcType: u8,
    pub NLSFEProcCurrent: u8,
    pub NLSFEProcSwitch: u8,
    pub NLSFEProc: [VK_FPARAM; 8],
    pub NLSFEProcAlt: [VK_FPARAM; 8],
}
```

**Comment by kennykerr** [comment]
Note that some of these (like `AE_XXX`) are legitimate, but some of the others, like `VK_F`, are [clearly invented](https://github.com/microsoft/win32metadata/commit/9b0f587b2d62e7695f5f86944c92fe146cdf3a4e) and should be removed. The [WDK duplicates](https://gist.github.com/kennykerr/cc09c97310941a48b34994fdb89adcbe) also need to be resolved. 

Languages will have to [deal with](https://github.com/microsoft/windows-rs/pull/2486) the legitimate overloads.

**Comment by mikebattista** [comment]
We can regress usability of the `VIRTUAL_KEY` enum here, but given you're planning to handle overloads elsewhere, can you not handle this case as well? The additional key codes were added based on customer requests to improve usability.

Thanks for the WDK conflicts. Those headers duplicate SDK definitions and those need to be manually excluded. I should be able to bulk exclude based on your query.

**Comment by kennykerr** [comment]
Yes I can handle the overloads regardless.

**Comment by mikebattista** [comment]
All of these are legitimate definitions in the headers other than `VK_F` which we'll keep per the discussion. Projections need to be able to handle this.

I fixed the WDK duplicates with https://github.com/microsoft/wdkmetadata/issues/33. I don't think there's anything left here.
