### ISSUE TITLE
(Msg)WaitFor(Single|Multiple)Object(s)(Ex) now return Result instead of WIN32_ERROR

### ISSUE THREAD

**Issue by mgroenhoff** [microsoft/win32metadata#1558]
microsoft/windows-rs#2476 transforms all `WIN32_ERROR` return values into `Result<()>` using `.ok()`; This does not fit the `WaitFor(Single|Multiple)Object(s)(Ex)` family of functions very well since they return `WAIT_FAILED` on failure and `.ok()` only returns `Ok(())` for `WAIT_OBJECT_0`. This might work only for `WaitForSingleObject(Ex)` but this is debatable. This doesn't work for `WaitForMultipleObject(s)(Ex)` since success values range from `WAIT_OBJECT_0` through `WAIT_OBJECT_0 + MAXIMUM_WAIT_OBJECTS`. I'd like to propose to exclude these functions from these transformations and have them return `WIN32_ERROR` values.

Note that `MsgWaitForMultipleObjects(Ex)` still returns `u32` instead of `WIN32_ERROR` or `Result<()>`

In the meantime I use this helper fn to convert the wait result into something more usable:
```rust
#[inline]
fn cvt_wait_result(result: windows::core::Result<()>) -> windows::core::Result<WIN32_ERROR> {
    match result {
        Ok(_) => Ok(WAIT_OBJECT_0),
        Err(err) => match WIN32_ERROR::from_error(&err) {
            None | Some(WAIT_FAILED) => Err(windows::core::Error::from_win32()),
            Some(err) => Ok(err),
        },
    }
}
```

**Comment by mikebattista** [comment]
Should these be marked with [CanReturnAlternateSuccessCodes] or [CanReturnErrorsAsSuccess]? We don't use preservesig.

**Comment by kennykerr** [comment]
Ah I forgot yes `CanReturnMultipleSuccessValuesAttribute` seems appropriate here.

**Comment by kennykerr** [comment]
I just meant that some functions returned `WIN32_ERROR` and some did not. That seems inconsistent. In Rust at least, you can easily get at the underlying value if you know the result is not actually an error code.

**Comment by mikebattista** [comment]
They all return WIN32_ERROR now so let me know if anything else needs to change.

**Comment by riverar** [comment]
> > Those functions should probably also return WIN32_ERROR consistently.
> 
> I don't think the wait functions should return WIN32_ERROR. For example, if you call WaitForMultipleObjects on six handles and the last of those is signaled, then it returns WAIT_OBJECT_0 + 5 = 5, but that does not mean ERROR_ACCESS_DENIED = 5.

I agree. I think we should split `WIN32_ERROR` into `WIN32_ERROR` and `WAIT_EVENT` and then the functions modified to only return `WAIT_EVENT`.

**Comment by kennykerr** [comment]
Yep, that sounds right. Those functions don't return arbitrary Win32 error codes.
