### ISSUE TITLE
GetProcessInformation's hProcess documentation specifies incorrect process access right

### ISSUE THREAD

**Issue by BinToss** [microsoft/win32metadata#1564]
The documentation states the process handle must be opened with `SET_PROCESS_INFORMATION`, but this will cause the operation to fail with ERROR_ACCESS_DENIED (5).
Passing a handle opened with `PROCESS_QUERY_INFORMATION` or `PROCESS_QUERY_LIMITED_INFORMATION` succeeds, however.

This is issue originates from [MicrosoftDocs/sdk-api](https://github.com/MicrosoftDocs/sdk-api/blob/docs/sdk-api-src/content/processthreadsapi/nf-processthreadsapi-getprocessinformation.md).
It was seemingly [first reported in 2019](https://github.com/MicrosoftDocs/feedback/issues/1182) with no response.

[Example project](https://github.com/BinToss/GetProcessInformation_hProcess)

**Comment by mikebattista** [comment]
I mentioned @stevewhims from the doc team who may be able to help resolve or route this. See https://github.com/MicrosoftDocs/feedback/issues/1182#issuecomment-1537499671.
