### ISSUE TITLE
`OBJECT_ATTRIBUTES` should have read-only fields

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1565]
According to [the docs](https://learn.microsoft.com/en-us/windows/win32/api/ntdef/ns-ntdef-_object_attributes) the pointers in the `OBJECT_ATTRIBUTES` struct should be read-only, but I'm not sure if that can be expressed in the metadata yet?

> All members of this structure are read-only. If a member of this structure is a pointer, the object that this member points to is read-only as well. Read-only members and objects can be used to acquire relevant information but must not be modified.

Also this struct should probably be moved to wdk

**Comment by mikebattista** [comment]
@kennykerr

There's no metadata to scrape for this so anything would have to be manually added. What did you have in mind here?

**Comment by kennykerr** [comment]
Sounds good, I think there are some other structs that already have such `const` attributes.

**Comment by ChrisDenton** [comment]
Yes, you have to be able to construct the `OBJECT_ATTRIBUTES`. I'm not intending to prevent that. However, the difference I'm looking for in Rust is:

```rust
#[repr(C)]
pub struct OBJECT_ATTRIBUTES {
    pub Length: u32,
    pub RootDirectory: HANDLE,
    pub ObjectName: *const UNICODE_STRING,
    pub Attributes: u32,
    pub SecurityDescriptor: *const c_void,
    pub SecurityQualityOfService: *const c_void,
}
```

Note the pointers are `*const` (as opposed to `*mut`). This is similar to e.g. `CreateFileW` where the first parameter takes a `[In][Const] PWSTR`.

**Comment by riverar** [comment]
And to save folks 30 seconds looking it up, here's the initialize macro. Nothing special here.

```cpp
#define InitializeObjectAttributes( p, n, a, r, s ) { \
    (p)->Length = sizeof( OBJECT_ATTRIBUTES );          \
    (p)->RootDirectory = r;                             \
    (p)->Attributes = a;                                \
    (p)->ObjectName = n;                                \
    (p)->SecurityDescriptor = s;                        \
    (p)->SecurityQualityOfService = NULL;               \
    }
```

Be aware this structure is used in user-mode (e.g., `NtOpenFile`) so not sure it warrants the move to wdk metadata.

**Comment by ChrisDenton** [comment]
Ah, I had somehow got the impression that `Nt*` functions were being moved too.

**Comment by kennykerr** [comment]
Me too. Aren't they? 🤔

**Comment by mikebattista** [comment]
They're moved.

**Comment by riverar** [comment]
Ah right https://github.com/microsoft/wdkmetadata/pull/37, thanks for reminder.
