### ISSUE TITLE
CreateDialogIndirectParamA

### ISSUE THREAD

**Issue by MRahilly** [microsoft/win32metadata#1568]
The docs for DLGTEMPLATE suggest using
#[repr(C, packed(2))]

I find I need to use
#[repr(C, packed(4))]
to get the children of my modeless dialog to work properly.

**Comment by mikebattista** [comment]
@kennykerr @riverar 

The metadata reflects the headers which indicates packing of 2. Are you suggesting the headers are wrong?

**Comment by ChrisDenton** [comment]
According to the header file:

> The following structures must NOT be `DWORD` padded because they are followed by strings, etc that do not have to be `DWORD` aligned.

So it seems they should be packed (to avoid trailing padding) but the struct itself still needs to be aligned.

The link you gives "cheats" by defining the trailing data in the same struct so the padding isn't a problem,

**Comment by mikebattista** [comment]
Is there anything actionable here in the metadata?

**Comment by MRahilly** [comment]
I read that the packing is the same for both DLGTEMPLATE and DLGITEMTEMPLATE i.e. #[repr(C, packed(2))]
Is that not wrong? Should one not be double the other?

**Comment by kennykerr** [comment]
The headers are the source of truth, and they say that packing is 2.

**Comment by ChrisDenton** [comment]
Yes, I don't think anything can be done here unfortunately. The needed alignment is [documented](https://learn.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-dialogboxindirectparama?redirectedfrom=MSDN):

> In a standard dialog box template, the [DLGTEMPLATE](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-dlgtemplate) structure and each of the [DLGITEMTEMPLATE](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-dlgitemtemplate) structures must be aligned on DWORD boundaries. The creation data array that follows a DLGITEMTEMPLATE structure must also be aligned on a DWORD boundary. All of the other variable-length arrays in the template must be aligned on WORD boundaries.

Basically the structs are `pack(2)` and `align(4)` but that's contradictory. So the way this is resolved in the headers is to use `pack(2)` and leave alignment up to the user.
