### ISSUE TITLE
`ID3D11Texture2D.SetEvictionPriority` should accept `DXGI_RESOURCE_PRIORITY` as the param type.

### ISSUE THREAD

**Issue by DiscreteTom** [microsoft/win32metadata#1573]
For now `ID3D11Texture2D.SetEvictionPriority` accept `u32` as the param type, but the `DXGI_RESOURCE_PRIORITY` is a struct, so I have to use `texture.SetEvictionPriority(DXGI_RESOURCE_PRIORITY_MAXIMUM.0)` which is not straight forward.

**Comment by damyanp** [comment]
Interesting. Strictly speaking all those methods should take uints since DXGI_RESOURCE_PRIORITY values are intended to be used as reference values, but it's considered valid to pass, say, `DXGI_RESOURCE_PRIORITY_MAXIMUM.0 - 1` to them.

**Comment by mikebattista** [comment]
So just delete the enum and revert the values back to constants?

**Comment by damyanp** [comment]
That seems like the right thing to do to me.
