### ISSUE TITLE
Question about typedefs such as ABORTPATH vs EMRABORTPATH?

### ISSUE THREAD

**Issue by Eoinocal** [microsoft/win32metadata#1576]
I’m generating a language projection and have encountered some differences between the C++ headers and the metadata. `ABORTPATH` and `EMRABORTPATH` are an example

The metadata contains `ABORTPATH`, but `wingdi.h` only exposes typedefs of that struct:

```
typedef struct tagABORTPATH
{
    EMR     emr;
} EMRABORTPATH,      *PEMRABORTPATH,
  EMRBEGINPATH,      *PEMRBEGINPATH,
  EMRENDPATH,        *PEMRENDPATH,
  EMRCLOSEFIGURE,    *PEMRCLOSEFIGURE,
  EMRFLATTENPATH,    *PEMRFLATTENPATH,
  EMRWIDENPATH,      *PEMRWIDENPATH,
  EMRSETMETARGN,     *PEMRSETMETARGN,
  EMRSAVEDC,         *PEMRSAVEDC,
  EMRREALIZEPALETTE, *PEMRREALIZEPALETTE;
```

As a result, my language projection doesn’t include the types like `EMRABORTPATH`, while the autogenerated tests for `ABORTPATH` on the C++ side cause a compiler error.

I notice, for example, the Rust projection also contains `ABORTPATH` but not `EMRABORTPATH`. So I’m wondering is this by design and that projections should not worry about defining `EMRABORTPATH` and similar typedefs?

Thanks

**Comment by mikebattista** [comment]
So far we just expose the struct with a primary name that the scraper recommends. I don't see a reason to expose the others especially if they aren't referenced by any APIs which these don't appear to be. We'd have to manually define these and I'd rather not go down that route unless there's clear value. The important part is the struct is usable in all the places you'd expect it to be.

What projection are you working on?

**Comment by Eoinocal** [comment]
That makes perfect sense, thanks for answering my question. The projection is for [flat assembler](https://flatassembler.net/), but it's very experimental at the moment.
