### ISSUE TITLE
CreateActCtx is returning the wrong SafeHandle

### ISSUE THREAD

**Issue by ptsoccer** [microsoft/win32metadata#1581]
## Actual behavior

I am running into an issue with https://github.com/ookii-dialogs/ookii-dialogs-wpf where upon closing the program, I get an SEHException on disposal of a SafeFileHandle. The HRESULT is 8000 4005 (unspecified error). I believe this is because CreateActCtx is returning a SafeFileHandle and thus CloseHandle is being called on the ctx rather than ReleaseActCtx.

## Expected behavior

The handle returned by CreateActCtx should close the handle with ReleaseActCtx

## Repro steps

This code, in a WPF or winforms app, along with version 5.0.1 of Ookii.Dialogs.Wpf should cause the error. I don't need it disabled, but disabling "Just my code" might also be necessary. 
```
using (var taskDialog = new TaskDialog()
                   {
                       Buttons =
                       {
                           new TaskDialogButton(ButtonType.Ok),
                       }
                   })
            {
                taskDialog.ShowDialog();
                Close();
            }
```

### Context

- CsWin32 version: [e.g. `0.2.63-beta`] https://github.com/ookii-dialogs/ookii-dialogs-wpf/blob/master/src/Ookii.Dialogs.Wpf/Ookii.Dialogs.Wpf.csproj#LL71C68-L71C79
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netframework4.6.2`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Yes, I can make cswin32 work with that.
