### ISSUE TITLE
Metadata is missing for CLR hosting API. 

### ISSUE THREAD

**Issue by chuckries** [microsoft/win32metadata#1582]
The Win32.System.ClrHosting API namespace is missing metadata to map the outparams to the COM interfaces they return.

Example (copied from ILSpy for Windows.Win32.winmd):

```
[DllImport("MSCorEE.dll", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern HRESULT CLRCreateInstance([In][Const] Guid* clsid, [In][Const] Guid* riid, [In][Out] void** ppInterface);
```

the `void** ppInterface` returned is known to be an `ICLRMetaHost`, whose COM interface definition is available. This causes projections (such as those provided by windows-rs) to not be ergonomic.

**Comment by kennykerr** [comment]
Also, various CLR interface methods, like `ICLRMetaHost.GetRuntime` and `ICLRRuntimeInfo.GetInterface` and others are also missing the `ComOutPtr` attribute.

**Comment by mikebattista** [comment]
So these all just need the `[ComOutPtr]` attribute? Do you have a full list of all the APIs that need it?

**Comment by kennykerr** [comment]
You can get a quick list by search `metahost.h` for `iid_is`.

**Comment by chuckries** [comment]
@mikebattista https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/metahost.idl

**Comment by mikebattista** [comment]
Perfect. Thanks.

**Comment by mikebattista** [comment]
metahost.idl and mscoree.idl from that repo appear to be missing APIs. Are there different versions of those files?

**Comment by chuckries** [comment]
The only thing I can find is "C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um\metahost.h", which is part of the desktop CLR sdk. The file I pointed you to is part of the modern .NET open source repo.

I'm not sure if there is a publicly available metahost.idl for desktop clr.
