### ISSUE TITLE
MetaData for `IKsPropertySet` missing

### ISSUE THREAD

**Issue by ShortDevelopment** [microsoft/win32metadata#1585]
## Actual behavior
Adding the `IKsPropertySet` to `NativeMethods.txt` does not result in the corresponding code being generated.
It seems like this interface is missing in the metadata.

## Expected behavior
Code generation for this interface.

## Context

- CsWin32 version: `0.3.2-beta`
- Target Framework: `net7.0-windows`

**Comment by riverar** [comment]
Looks like we explicitly drop that https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/Partitions/Audio.Apo/settings.rsp#L6

@mikebattista thoughts on why?

**Comment by riverar** [comment]
Ah, looks like to keep the bad interface out. From docs: https://learn.microsoft.com/en-us/windows/win32/directshow/ikspropertyset

> Another interface by this name exists in the dsound.h header file. The two interfaces are not compatible. The IKsControl interface, documented in the DirectShow DDK, is now the recommended interface for passing property sets between WDM drivers and user mode components.

So I guess the real issue here is that metadata doesn't cover the DirectShow DDK.

**Comment by mikebattista** [comment]
IKsControl is in the SDK metadata. So no issues here then?

**Comment by riverar** [comment]
Hm, not sure we should start omitting stuff from metadata based on _recommendations_. I think we should re-add it and let folks shoot themselves in the foot if mishandled (like most APIs).

**Comment by riverar** [comment]
Thanks @mikebattista! Now @ShortDevelopment, we recommend you not use this. 😆
