### ISSUE TITLE
Should `IDXGI*` types be marked as `[Agile]`?

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/win32metadata#1588]
#740 and #861 marked the `ID3D*` types `[Agile]` to have `Send` and `Sync` in Rust because all these types are (supposedly) synchronized internally and thus thread-safe. Is the same true for `DXGI` types, and if so can we add the same attribute to them too?

**Comment by riverar** [comment]
Sounds reasonable, thoughts @damyanp?

**Comment by damyanp** [comment]
I'm working on getting an answer to this, but it may take a few days.

**Comment by damyanp** [comment]
Word I've got back is that the IDXGI* interfaces are as agile as the D3D ones are.

**Comment by MarijnS95** [comment]
@damyanp lovely, thanks for getting back to me so quickly! (and concidentally right when I remembered I asked this question)

Will you submit a PR adding this or should I?

**Comment by riverar** [comment]
Happy to sign off on this as soon as your PR lands. Or Mike and I can take care of it too.

**Comment by damyanp** [comment]
Thanks!  I'm unlikely to find time to work on this any time soon I'm afraid.

**Comment by MarijnS95** [comment]
Done in #1591: `.\DoAll.ps1 -Clean` (which takes ages, by the way!) didn't report any changes, and the `[Agile]` attribute is not visible (on anything) in ILSpy, fwiw.

**Comment by riverar** [comment]
`[Agile]` seems to be broken at the moment, standby. (cc: @mikebattista for awareness)

**Comment by MarijnS95** [comment]
Strange, the regenerated branch has it working for `ID3D` types for example, as before.

**Comment by riverar** [comment]
@marignS95 And missing from IDWrite* interfaces, which is strange. Running through `bisect` now.

**Comment by riverar** [comment]
OK `bisect` shows it broke in https://github.com/microsoft/win32metadata/commit/62a25c42b54cae5f8a599f28b03dbd53948b8cf7, we'll get it patched up.
