### ISSUE TITLE
Using Microsoft.Windows.WinmdGenerator on Linux: cannot find Sdk.props (case sensitivity)

### ISSUE THREAD

**Issue by CarePackage17** [microsoft/win32metadata#1589]
I have an empty `Test.proj` like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.Windows.WinmdGenerator">

</Project>
```

When running `dotnet build` I get the following error:

```
MSBuild version 17.4.3+7e646be43 for .NET
/home/user/devel/winmd-gen-test/Test.proj : error MSB4019: The imported project "/home/user/.nuget/packages/microsoft.windows.winmdgenerator/0.52.65-preview/sdk/Sdk.props" was not found. Confirm that the expression in the Import declaration "/home/user/.nuget/packages/microsoft.windows.winmdgenerator/0.52.65-preview/sdk/Sdk.props" is correct, and that the file exists on disk.
```

It's possible to work around it by making a copy of the file that starts with an uppercase S.

After fixing that, the generator starts running, but fails quite early because it can't find `powershell.exe`.  
I do have `pwsh` on my system, but I guess getting those scripts to run on Powershell Core as opposed to 5.1 is a bigger task...

**Comment by MarijnS95** [comment]
@CarePackage17 I've tried this before (as it'd save me a round-trip to a Windows boot when contributing here) but it seems unlikely to work after fixing the `pwsh` issue, there's probably much more. I doubt it's intended to run on Linux, just like windows-rs.

Really curious what the consistency is supposed ot be with those `Sdk` capitalization imports - I've seen them multiple ways around (`sdk/sdk.{props,targets}`, `sdk/Sdk.{props,targets}`, `Sdk/sdk.{props,targets}`, `Sdk/Sdk.{props,targets}`).

**Comment by MarijnS95** [comment]
@CarePackage17 I agree, it'd be great if it just worked. Perhaps we have to start going over all the dependencies and fix their paths to be uppercase, and continue from there?

**Comment by CarePackage17** [comment]
Yeah, sounds good. I think it's just 3 NuGet packages with lowercase sdk (this one and 2 dependencies) IIRC.

**Comment by mikebattista** [comment]
We can rename the sdk files to Sdk. Is it just the filenames that are problematic?

**Comment by riverar** [comment]
@mikebattista Sounds like that's just the start of the problems. Don't see any value in fixing this one.

**Comment by mikebattista** [comment]
I have no intention of trying to get the whole pipeline running on Linux but if others want to try and changing the casing of the filenames is the first step, we can make the change.

**Comment by ChrisDenton** [comment]
Note that this will also help people (such as me) who uses a filesystem with case-insensitive on Windows.
