### ISSUE TITLE
Win32 error codes should be collected under an enum

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#159]
...and methods that return one should be typed as that enum.

See the [enum defined in dotnet/pinvoke](https://github.com/dotnet/pinvoke/blob/d91801e57fa98f15116b9c6b53dfee49c632334c/src/Windows.Core/Win32ErrorCode.cs)

**Comment by BertusGreeff** [comment]
If the general pattern is to model error codes as a enum, how would a projection deal with a function that returns a number that is not in the enum?  This could easily happen if I run a old program on a newer OS that added a new error value.

**Comment by AArnott** [comment]
@BertusGreeff The same way you might handle it without an enum: code defensively. An old program can always run on a newer OS that returns new error codes, and a well-written program will have a catch-all block for unrecognized error codes. In C# this might be a `default:` case in a `switch` statement.

**Comment by marler8997** [comment]
>  how would a projection deal with a function that returns a number that is not in the enum?

The Zig Programming Language has the concept of exhaustive and non-exhaustive enums (see https://ziglang.org/documentation/master/#Non-exhaustive-enum).  With a non-exhaustive enum, it forces developers to have a "default" case when switching on values of that enum, and also allows the enum to be set to values not listed in the definition.  I provide this example to show that there are users who could not only handle this type of enum, but could also make use of metadata that marks enums as exhaustive or non-exhaustive.

**Comment by BertusGreeff** [comment]
The point of win32metadata is to be projected into many languages.  Using enum as a return value, works as long as the language can handle values assigned to the enum where the enum do not have a member for that value.  C/C++ and C# for example supports that.  Is that going to be the case for all languages?  Expressing return values as a enum in the metadata is still fine as long as the language projection can handle it appropriately.  Does that require an attribute on the metadata to express that it is a return value?

**Comment by BertusGreeff** [comment]
Here is for example a warning from rust discriminant enums.  (https://doc.rust-lang.org/stable/reference/type-layout.html#the-c-representation)

Warning: There are crucial differences between an enum in the C language and Rust's field-less enums with this representation. An enum in C is mostly a typedef plus some named constants; in other words, an object of an enum type can hold any integer value. For example, this is often used for bitflags in C. In contrast, Rust’s field-less enums can only legally hold the discrimnant values, everything else is undefined behavior. Therefore, using a field-less enum in FFI to model a C enum is often wrong.

**Comment by kennykerr** [comment]
The [windows](https://github.com/microsoft/windows-rs) crate (for Rust) does not use Rust enums for Win32/WinRT enums (because those enums are not guaranteed to be unique), so this should work fine as a way to group an open-ended set of values.

**Comment by kennykerr** [comment]
It would be great if we can group errors code by category as well. The three main categories are HRESULT, Win32, and NT. Both Win32 and NT can be expressed as HRESULT values but developers often want to identify just the Win32 or NT status values. Then if we have the three distinct types we can have signatures return those types directly. We already do this for HRESULT but it would be nice to know when a function returns a Win32 or NT status code as well. `GetLastError` for example could return the Win32 type rather than just uint.

**Comment by kennykerr** [comment]
Much like HRESULT, there is a type for NT status codes already, NTSTATUS, but not one for Win32 error codes. A lot of the NT status codes can be found in ntstatus.h - they don't appear to be included right now.

**Comment by fredrikhr** [comment]
A Windows error code also includes information like the facility, the severity class and custom flag, so we'd need extension classes anyway, so maybe a helper class would actually be better (or even three, one each for HRESULT, NTSTATUS and Win32ErrorCode). But we really could use a list of named constants so that one could easily get the named symbol from an int returned by Win32 API

**Comment by kennykerr** [comment]
That bit-masking is specific to [HRESULT](https://en.wikipedia.org/wiki/HRESULT) and languages already support that natively. But yes the various collections of known codes is the key.

**Comment by AArnott** [comment]
HRESULT and NTSTATUS has structure (bit masks for various sub-meanings), making struct an appropriate choice IMO. Defining constants on that struct would allow for an enum + extra methods experience. But that is *out of scope* of this issue, which is just about win32 error codes. 

I haven't seen any docs to suggest win32 error codes have structure. On the contrary, [the docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d) suggest they are just monotonically increasing values, which is why an enum makes the most sense, IMO.

While HRESULT or NTSTATUS may be able to represent win32 error codes as well, they are not the same thing. Functions documented to return a win32 error code should be typed in the metadata as such.

**Comment by zaddach** [comment]
I agree that functions returning an win32 error code should be typed as such (I'd extend the definition of "returning" an error code for those functions that return a `BOOL` where you're supposed to check `GetLastError()` on `FALSE`, at least for the Rust `bindings::windows::Error` type).
There are some functions where the returned error is part of the API contract and can signal a successful return, such as [InitializeProcThreadAttributeList](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-initializeprocthreadattributelist) on the first invocation with a NULL pointer, or `ReadFile` in overlapped mode.
Things will get a bit more messy if you'll try to capture the same behavior for functions that usually return a type (e.g., [CreateFileMapping](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createfilemappinga) returns a NULL handle on error, which means it effectively returns `GetLastError()`). If you still could express this with the current metadata format, that would be awesome.

Overall, if you have a typed win32 error code, you can make a lot of error handling easier by making its numeric value accessible and coherent with error constants (The `ErrorCode` type in Rust and `GetLastError()` currently return an `u32`, while the WIN32 error constants such as `ERROR_IO_PENDING` are `i32`).

**Comment by weltkante** [comment]
I'd be very wary about strict enums, there are places in the Windows API where undocumented enum values exist or are accepted for compatibility without having explicit defines. Also newer versions may extend the enum and a projection generated against an older enum set must be able to deal with Windows returning newer unknown flags in structs or by reference (often its gated behind some versioning mechanism, like struct sizes, but not always)

**Comment by sotteson1** [comment]
My plan is:
* Gather Win32 errors in an enum, have GetLastError return it
* Gather WSA errors in an enum, have WSAGetLastError return it
* Gather RPC errors into an enum named RPC_STATUS (an already defined name but is a typedef to a long), which the RPC functions will automagically return because they already return RPC_STATUS
* Leave HRESULTs the way they are currently projected as HRESULT structs
