### ISSUE TITLE
CfReleaseTransferKey mistakenly has an out-parameter

### ISSUE THREAD

**Issue by goffrie** [microsoft/win32metadata#1592]
I'm not sure if cfapi.h is from an outdated copy or something, but the TransferKey parameter should be an in-parameter, as documented in https://learn.microsoft.com/en-us/windows/win32/api/cfapi/nf-cfapi-cfreleasetransferkey

**Comment by mikebattista** [comment]
The header has an `_Out_` SAL annotation here for some reason.
