### ISSUE TITLE
WSA functions should be marked SetLastError where appropriate

### ISSUE THREAD

**Issue by ansteele** [microsoft/win32metadata#1594]
Hello,

Many WSA functions call WSASetLastError as a means of returning error information. 
I believe WSASet/GetLastError is simply an alias of the regular Set/GetLastError therefore it would make sense that WSA functions be marked as SetLastError = true.

Many thanks

**Comment by riverar** [comment]
I was suspicious of this, so took a peek at `WSAGetLastError` under the hood and, well, see for yourself. 😂

```cpp
int __stdcall WSAGetLastError()
{
  return GetLastError();
}
```

**Comment by ChrisDenton** [comment]
Aye, see also `WSAWaitForMultipleEvents`, `WSASetEvent` and probably others too. On the one hand it's possible they'd want to reserve the right to change it again the future. On the other hand I wouldn't be surprised if people have come to rely on it.

**Comment by riverar** [comment]
Thankfully only [NEMA 10-30](https://www.mcmaster.com/products/nema-10-30-plugs/) folks use winsock. 😂

![image](https://github.com/microsoft/win32metadata/assets/475132/f581c9fa-55aa-4768-a082-b0da06337bdf)

**Comment by riverar** [comment]
For those interested, I dug through some very old documentation and here's some clarifying details:

> The use of the WSAGetLastError() function to retrieve the last error code, rather than relying on a global error variable (cf. errno), is required in order to provide compatibility with future multi-threaded environments.  
>
> Note that in a Win16 environment WSAGetLastError() is used to retrieve only Windows Sockets API errors.  In a Win32 environment, WSAGetLastError() will invoke GetLastError(), which is used to retrieve the error status for all Win32 API functions on a per-thread basis.  For portability, an application should use WSAGetLastError() immediately after the Windows Sockets API function which failed.
