### ISSUE TITLE
Unusual generation of the HOTKEYF_EXT constant on Windows

### ISSUE THREAD

**Issue by fgimian** [microsoft/win32metadata#1595]
## Actual behavior

I'm compiling on Windows and the generated constant is:

```c#
internal const uint HOTKEYF_EXT = 128U;
```

## Expected behavior

According to the [metadata](https://github.com/microsoft/win32metadata/blob/81344326b62096e7c7d62bc9905d4258103eef1d/generation/WinSDK/RecompiledIdlHeaders/um/CommCtrl.h#L2932) and [the relevant Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-sethotkey#parameters), this should be `0x08` on Windows systems.

## Repro steps

1. `NativeMethods.txt` content:

```
IShellLinkW
IPersistFile
ShellLink
MAX_PATH
SLGP_FLAGS
HOTKEYF_CONTROL
HOTKEYF_ALT
HOTKEYF_SHIFT
HOTKEYF_EXT
VIRTUAL_KEY
```

2. `NativeMethods.json` content (if present): N/A
3. Any of your own code that should be shared? N/A

### Context

- CsWin32 version: 0.3.2-beta
- Win32Metadata version (if explicitly set by project): N/A
- Target Framework: net7.0-windows
- `LangVersion` (if explicitly set by project): N/A

Thanks heaps in advance!
Fotis

**Comment by mikebattista** [comment]
The ConstantsScraper knows nothing about the conditional. We can just exclude this one from the scraper and define it manually.
