### ISSUE TITLE
Should `D3D12_DXIL_LIBRARY_DESC::pExports` be `const`?

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/win32metadata#1598]
This data should only be taken as input:

https://github.com/microsoft/win32metadata/blob/81344326b62096e7c7d62bc9905d4258103eef1d/generation/WinSDK/RecompiledIdlHeaders/um/d3d12.idl#L4319-L4325

Note that `PCWSTR *pExport`s below are marked as `const` pointers because of the type in the Rust bindings.

**Comment by mikebattista** [comment]
What's the requested change here and expected metadata?

**Comment by riverar** [comment]
Related: https://github.com/microsoft/win32metadata/pull/1480

Requested change is to make `D3D12_DXIL_LIBRARY_DESC::pExports` constant (i.e., add `[Const]`)

**Comment by mikebattista** [comment]
I don't see the correlation with the issue you linked or the reasoning why this should be Const. Can you clarify?

**Comment by riverar** [comment]
I'm not very familiar with DirectX but it appears this structure is used to describe a subobject containing a DXIL library and the exports the developer wishes to expose, akin to some sort of wrapper or proxy object. So to bubble up say 3 exported functions, I would stuff a `3` into `NumExports` and create an array of  `D3D12_EXPORT_DESC` structures with some metadata and store a pointer to that array in `pExports`. I think somewhere down the line you would pass this to a DirectX function to register your intent or perhaps call these exports (in shaders?).

I can't envision a scenario where it would be permitted for DirectX (or the dev) to change that pointer or change the data that pointer points to. So I'm thinking `pExports`  is a (C++) `const T* const ptr ...`, sound right @MarijnS95?

But it's not actually clear what `[Const]` means in metadata, at least when applied to a pointer. Is it indicating a const value? Const pointer to non-const value? Const pointer to const value? Or...?

**Comment by mikebattista** [comment]
`[Const]` generally means the definition had the `const` keyword on it.

**Comment by MarijnS95** [comment]
@riverar perfectly understood my request. Indeed, this API seems solely for the user to pass information into a D3D12 driver, without that driver modifying the data.

Right now in Rust I have to unnecessarily declare that the `D3D12_EXPORT_DESC` instance this pointer points to is `mut`able, and cope with the mutable scope.

It would however be `const D3D12_EXPORT_DESC* pExports;`, to allow the user to (re)assign the member rather than forcing it to be set at construction (and forgive me for being Rusty :smirk: :crab: on C++, `const T* const ptr;` might even require a `D3D12_EXPORT_DESC(...) : pExports(...)` constructor? Or would an initializer list like `D3D12_EXPORT_DESC { ..., pExports }` work here as well?).

**Comment by mikebattista** [comment]
@damyanp @kennykerr?

`[Const]` represents `const` from the headers which this field does not have.

There might be some other metadata or projection improvement here but I'm not convinced it's adding `[Const]`.

**Comment by jenatali** [comment]
We should just add `const` in our IDL, yeah.

**Comment by mikebattista** [comment]
Ok. I will close this out then as external. The metadata will emit `[Const]` once the corresponding header has `const`.

**Comment by MarijnS95** [comment]
Thanks, yeah fixing the IDL might normally take a bit longer but has my preference as well after contributing/requesting a bunch of changes that get overridden in the metadata, while improving the IDL also effects the experience for C(++) header consumers.

Strangely it didn't even occur to me that I could have immediately opened a PR for this to https://github.com/microsoft/DirectX-Headers, which would have been much faster. @jenatali can you fix this up (since IIRC there was also an internal repo to update for `DirectX-Headers`) or should I open a PR?

There I also found [`D3D12_EXISTING_COLLECTION_DESC` with a `D3D12_EXPORT_DESC* pExports` that could similarly be `const`ified](https://github.com/microsoft/DirectX-Headers/blob/3a57ee119e546006914d41470fbdabbc735d80ec/include/directx/d3d12.idl#L4326C16-L4331).

**Comment by jenatali** [comment]
The change is already in progress in our internal repo. It'll flow to `DirectX-Headers` with the next push.
