### ISSUE TITLE
Add ProcessPrng?

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1605]
[`ProcessPrng`](https://learn.microsoft.com/en-us/windows/win32/seccng/processprng) is fully documented but weirdly doesn't appear in headers. Can this be added to the metadata?

**Comment by riverar** [comment]
Looks like a SDK bug (ping @mikebattista). Can add it manually but would be nice if the SDK got updated too.

**Comment by kennykerr** [comment]
Note that `RtlGenRandom` is available and just calls `ProcessPrng`.

**Comment by ChrisDenton** [comment]
Yep, though it requires loading advapi.dll and the documentation strongly recommends using it. Most notably Chromium have recently switched from `RtlGenRandom` to `ProcessPrng`.

**Comment by kennykerr** [comment]
Well it's not going anywhere but yes, you can avoid the load and hop through `advapi32.dll` by linking `ProcessPrng` directly from `BCryptPrimitives.dll`. We do that internally as well. 😏
