### ISSUE TITLE
Possible bug in Win32 API for RealGetWindowClass

### ISSUE THREAD

**Issue by shravan2x** [microsoft/win32metadata#1607]
Hi, I use [RealGetWindowClass](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-realgetwindowclassw) in my application. There appears to be a bug with the Windows API where only the bottom two bytes or `cchClassNameMax` seem to be copied somewhere (i.e. the real method signature or implementation uses a uint16 instead).

I found the issue when passing in a buffer size of 32768. Passing in 32767 works fine for almost all cases. 32768 suddenly returns an ERROR_INSUFFICIENT_BUFFER. Increasing the buffer size by a 100 to 32868 also works as all class names on my PC are under 100 characters.

This isn't a bug with this library per-se, but maybe someone at Microsoft could file an issue internally?

**Comment by riverar** [comment]
When reporting bugs like this, it's important to provide a minimal, reproducible example. Here's one, written in Rust:

```rust
// Features: "Win32_Foundation", "Win32_UI_WindowsAndMessaging"

use windows_sys::Win32::{
    Foundation::{GetLastError, SetLastError, ERROR_SUCCESS},
    UI::WindowsAndMessaging::{GetDesktopWindow, RealGetWindowClassW},
};

fn main() {
    unsafe {
        for size in (u16::MAX as u32) - 2..=(u16::MAX as u32) + 10 {
            SetLastError(ERROR_SUCCESS);
            let mut buffer = Vec::<u16>::with_capacity(size as usize);
            let chars_copied =
                RealGetWindowClassW(GetDesktopWindow(), buffer.as_mut_ptr(), size as u32);
            let last_error = GetLastError();
            println!("RealGetWindowClassW(..., {size}) => {chars_copied} (gle: {last_error})");
        }
    }
}

```
```
RealGetWindowClassW(..., 65533) => 6 (gle: 0)
RealGetWindowClassW(..., 65534) => 6 (gle: 0)
RealGetWindowClassW(..., 65535) => 6 (gle: 0)
RealGetWindowClassW(..., 65536) => 0 (gle: 122)
RealGetWindowClassW(..., 65537) => 0 (gle: 122)
RealGetWindowClassW(..., 65538) => 1 (gle: 0)
RealGetWindowClassW(..., 65539) => 2 (gle: 0)
RealGetWindowClassW(..., 65540) => 3 (gle: 0)
RealGetWindowClassW(..., 65541) => 4 (gle: 0)
RealGetWindowClassW(..., 65542) => 5 (gle: 0)
RealGetWindowClassW(..., 65543) => 6 (gle: 0)
RealGetWindowClassW(..., 65544) => 6 (gle: 0)
RealGetWindowClassW(..., 65545) => 6 (gle: 0)
```

@mikebattista We're not fielding Win32 API bugs in this repository, right? There was [an effort by the Windows App SDK](https://github.com/microsoft/WindowsAppSDK/discussions/1876) folks to accept OS bugs there (@jonwis) but I don't think that took off. Perhaps [Microsoft Q&A (Win32 API tag)](https://learn.microsoft.com/en-us/answers/tags/224/windows-api-win32) is the best option here?

**Comment by jonwis** [comment]
Well that is super interesting. I've routed this to the folks who own it.  For reference, it's https://task.ms/45445589

**Comment by riverar** [comment]
Thanks @jonwis; will close this issue as there's nothing actionable for metadata at this time. Feel free to ping this thread again to check in from time to time.

**Comment by shravan2x** [comment]
Thanks for looking into it!
