### ISSUE TITLE
Documentation mappings false positives

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1609]
Haven't fully analyzed the situation but wanted to raise awareness quickly; the following mappings appear to be causing issues:

```
name=[Documentation("https://docs.microsoft.com/windows/win32/DirectShow/name-attribute")]
Name=[Documentation("https://docs.microsoft.com/windows/win32/TaskSchd/taskschedulerschema-name-headerfieldtype-element")]
NAME=[Documentation("https://docs.microsoft.com/windows/win32/DirectShow/name")]
```

Example:
```csharp
public extern AssociatedEnumAttribute(
[In]
[Documentation("https://docs.microsoft.com/windows/win32/TaskSchd/taskschedulerschema-name-headerfieldtype-element")]
string Name);
```

I don't think these mappings should be hitting on parameter **names** at all, so there's probably a deeper issue here.

(@mikebattista)

**Comment by mikebattista** [comment]
We should just remove the mappings like in https://github.com/microsoft/win32metadata/compare/main...mikebattista/clangsharp-16.0.

**Comment by riverar** [comment]
That should work in this case.

If my understanding is correct, we're looking at method parameter _names_ instead of confining ourselves to _type/method/struct names_. If so, I'm still concerned there are common words in the list (e.g., def, do, default, description, copyright, core, level, play, etc.) that might hit now or later.

**Comment by mikebattista** [comment]
Looking at this, I believe it's only constructor parameters that are impacted, and those are only used with the Attribute definitions.

Name/Value appear to be the two false positives that impact multiple Attributes, so I will just remove those mappings.
