### ISSUE TITLE
All types from Nvme.h are missing

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1610]
Reference: https://learn.microsoft.com/en-us/windows/win32/api/nvme/

**Comment by riverar** [comment]
How about `Windows.Win32.Storage.Nvme` to fall in line with the others? (e.g., Jet, Vhd, Vss, Xps, etc.)

**Comment by mikebattista** [comment]
Ok. Thanks.

**Comment by Nuklon** [comment]
Thanks for the quick PR 🚀

**Comment by Nuklon** [comment]
BTW, is there a daily nuget feed for the metadata? Similar to CsWin32 has.

**Comment by mikebattista** [comment]
No. When the next metadata NuGet package ships you can plug it into CsWin32 until it carries it by default.
