### ISSUE TITLE
GetMonitorInfo is missing MONITORINFOEX variant

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1613]
There are two ways to call [GetMonitorInfo](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow), one with MONITORINFO and one with MONITORINFOEX. Only the regular MONITORINFO exists.

**Comment by mikebattista** [comment]
Related #981

**Comment by mikebattista** [comment]
Related #124

**Comment by riverar** [comment]
Closing in favor of #124 which represents the latest round of discussions regarding the representation of overloaded functions. Will edit that issue to make sure we don't forget about GetMonitorInfo, thanks!
