### ISSUE TITLE
LoadResource generates an unexpected GlobalFreeSafeHandle

### ISSUE THREAD

**Issue by sharwell** [microsoft/win32metadata#1622]
## Actual behavior

```
internal static unsafe GlobalFreeSafeHandle LoadResource(SafeHandle hModule, winmdroot.Foundation.HRSRC hResInfo)
{
  // ...
  return new GlobalFreeSafeHandle(__result, ownsHandle: true);
}
```

## Expected behavior

One of the following:

1. Return a type which is _not_ `GlobalFreeSafeHandle`
2. Construct the `GlobalFreeSafeHandle` with `ownsHandle: false`

## Repro steps

1. `NativeMethods.txt` content:

```
LoadResource
```

3. `NativeMethods.json` content (if present):

```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "className": "PInvoke2"
}
```

4. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.3.18-beta`
- Win32Metadata version (if explicitly set by project):
- Target Framework: `netstandard2.0`
- `LangVersion` (if explicitly set by project): `preview`

**Comment by mikebattista** [comment]
We also have `[ReturnsUnownedHandle]`.

**Comment by mikebattista** [comment]
@kennykerr

Generally we try to avoid changing the type from what's declared in the headers. HGLOBAL is true to the headers.

**Comment by riverar** [comment]
I agree with annotating the `LoadResource` retval with `[DoNotRelease]`. `[ReturnsUnownedHandle]` is only used on one function (GetClipboardData), so it may be worth consolidating and deleting that attribute, preferring `[DoNotRelease]` instead.

(For those curious, `LoadResource` returns a pointer to the requested resource in the module. Subsequently, LockResource does nothing on current Windows targets.)

**Comment by AArnott** [comment]
I'm curious about the semantic difference between the two attributes myself. If there really isn't one, I support consolidating as @riverar proposed.

**Comment by mikebattista** [comment]
`[ReturnsUnownedHandle]` was discussed at https://github.com/microsoft/win32metadata/issues/792.

**Comment by mikebattista** [comment]
Is there a scenario where you would own a handle but still shouldn't free it? If the semantic distinction is important, then the two attributes make sense. Otherwise, we can consolidate on one.

**Comment by AArnott** [comment]
No, I can't think of any case where we need distinct concepts for ownership and the need to release a handle.

**Comment by riverar** [comment]
Agreed.
