### ISSUE TITLE
PrivilegeCheck pfResult is incorrect type

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1628]
https://learn.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-privilegecheck
This is specified as BOOL, but is defined as int in metadata

**Comment by riverar** [comment]
Hi @Nuklon, `BOOL` is an alias for `int`, see the following typedef found in the headers:
```cpp
typedef int   BOOL
```

**Comment by Nuklon** [comment]
BOOL is used throughout the metadata, but not for this. So you'd have to cast it to BOOL manually. Not a big problem, but it'd be easier if it just used BOOL :)
