### ISSUE TITLE
Do all functions taking in BSTR treat it as read-only?

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1632]
Since BSTR is simply a typedef to wchar_t*, functions taking BSTR as an in-parameter can modify the string. However, since there is no wchar_t const* typedef for constant, I'm wondering what the semantics implied here. Is it safe to assume that [in] BSTR means a read-only parameter? I also see some parameters with [In][Const] BSTR but wouldn't that mean wchar_t* const?

**Comment by JaiganeshKumaran** [comment]
I'm asking what is the convention really. What does `const BSTR` even mean since it is `wchar_t* const` and not `wchar_t const*` (const wchar_t*), which only tells you that the pointer cannot be modified inside the function but the actual data can be.

**Comment by mikebattista** [comment]
@kennykerr can probably answer.

**Comment by kennykerr** [comment]
It doesn't mean anything. The BSTR semantics are defined by the type and its accessor function.
