### ISSUE TITLE
RetValAttribute vs ComOutPtr

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1633]

**Comment by JaiganeshKumaran** [comment]
@riverar This is a doubt I have. Some APIs have RetValAttribute but others have ComOutPtrAttribute. Is there any difference between the two?

**Comment by riverar** [comment]
`RetValAttribute` is affixed to the parameter that receives the return value.

```csharp
HRESULT getRowCount([Out][RetVal] IntPtr* pcRows);
```

`ComOutPtrAttribute` is affixed to pointers to indicate the parameter receives a pointer to a COM interface implementation.

```csharp
unsafe HRESULT GetReport([Out][ComOutPtr] IMFRelativePanelReport* ppRelativePanelReport);
```
