### ISSUE TITLE
SP_* types don't always have to use different pack sizes

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1637]
This makes it much more difficult to integrate with Any CPU builds. Many types align identical on x86 and x64. 
For the types below there are current x86 (pack = 1) and x64 (default pack) definitions. Instead, they could use the default pack size. They all align naturally.

1.
SP_DEVINFO_DATA
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_devinfo_data
Basically this is OK: 
https://github.com/dotnet/pinvoke/blob/main/src/SetupApi/SetupApi%2BSP_DEVINFO_DATA.cs#L22

2.
SP_ALTPLATFORM_INFO_V1 + SP_ALTPLATFORM_INFO_V2. 
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_altplatform_info_v1
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_altplatform_info_v2
**Not V3, it aligns differently**

3.
SP_CLASSINSTALL_HEADER 
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_classinstall_header

4.
SP_CLASSIMAGELIST_DATA
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_classimagelist_data

5.
SP_DEVINFO_DATA
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_devinfo_data

6.
SP_DEVINSTALL_PARAMS_W
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_devinstall_params_w

7.
SP_DRVINFO_DATA_V1_W + SP_DRVINFO_DATA_V2_W
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_drvinfo_data_v1_w
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_drvinfo_data_v2_w

8.
SP_DRVINSTALL_PARAMS
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_drvinstall_params

9.
SP_FILE_COPY_PARAMS_W
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_file_copy_params_w

10.
SP_INF_SIGNER_INFO_V1_W + SP_INF_SIGNER_INFO_V2_W
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_inf_signer_info_v1_w
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_inf_signer_info_v2_w

11.
SP_PROPCHANGE_PARAMS
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_propchange_params

12
SP_REMOVEDEVICE_PARAMS
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/ns-setupapi-sp_removedevice_params

There are probably more, but I have checked these.

**Comment by kennykerr** [comment]
> There are probably more, but I have checked these.

What have you checked exactly? Changing packing can affect alignment.

**Comment by Nuklon** [comment]
Alignment of course :)

**Comment by kennykerr** [comment]
Cool, but setting packing to 1 for 64-bit builds would, for example, change the alignment of `SP_DEVINFO_DATA` such that it no longer matches the Windows SDK headers.

**Comment by Nuklon** [comment]
But the alignment stays the same as these types align naturally. It's very inconvenient like this as it pretty much blocks Any CPU builds.

**Comment by kennykerr** [comment]
The following repro seems to disagree.

```C++
#include <stdio.h>
#include <windows.h>
#include <SetupAPI.h>

int main()
{
    printf("sizeof %zd\n", sizeof(SP_DEVINFO_DATA));
    printf("alignof %zd\n", alignof(SP_DEVINFO_DATA));
}
```

**Comment by ChrisDenton** [comment]
Oh hm, it's quite weird:

```cpp
#if defined(_WIN64)
#include <pshpack8.h>   // Assume 8-byte (64-bit) packing throughout
#else
#include <pshpack1.h>   // Assume byte packing throughout (32-bit processor)
#endif
```

So it's 1 aligned on 32-bit only. I'm not sure the point of `pshpack8`. I guess it's to force 8 alignment if the struct doesn't contain a pointer or handle? Strange.

**Comment by Nuklon** [comment]
> The following repro seems to disagree.
> 
> ```c++
> #include <stdio.h>
> #include <windows.h>
> #include <SetupAPI.h>
> 
> int main()
> {
>     printf("sizeof %zd\n", sizeof(SP_DEVINFO_DATA));
>     printf("alignof %zd\n", alignof(SP_DEVINFO_DATA));
> }
> ```

The size is obviously different in x86 and x64 as the ULONG_PTR isn't the same size. But if you do Pack = 1 then the struct alignment is correct for x86 and x64. It matches cpp alignment.

**Comment by ChrisDenton** [comment]
On x64, `SP_ALTPLATFORM_INFO_V3` has an alignment of 4 and a size of 36.

If `pack = 1` then the alignment would be 1 and the size would be 35.

**Comment by kennykerr** [comment]
What is correct is whatever MSVC says is correct according to the Windows SDK headers and MSVC says `alignof(SP_DEVINFO_DATA)` is 1 for 32-bit processors and 8 for 64-bit processors.

**Comment by Nuklon** [comment]
> On x64, `SP_ALTPLATFORM_INFO_V3` has an alignment of 4 and a size of 36.
> 
> If `pack = 1` then the alignment would be 1 and the size would be 35.

That's why I mentioned that V3 aligns differently 👍 V1 and V2 align OK.

For many types the 1 and 8 pack results in the same alignment. That's why I opened this issue. It's very inconvenient to have a ton of double entries.

**Comment by kennykerr** [comment]
It may be inconvenient, but at least it is correct. 😅

**Comment by riverar** [comment]
This particular issue isn't very readable or coherent. Can you edit it to make it clear what changes you want to see with an example and rationale? (Do take into account the discussion that has already occurred.)

**Comment by Nuklon** [comment]
Is it OK now? I added some additional text at the top.

**Comment by riverar** [comment]
@Nuklon No, the list is still formatted incorrectly and it doesn't provide any examples.

**Comment by riverar** [comment]
I went through some of the structures you listed and don't see any changes needed to metadata. These structures are just not compatible with AnyCPU in dotnet. CsWin32 has a few issues tracking enhancements for AnyCPU developers that may interest you:
* https://github.com/microsoft/CsWin32/issues/366
* https://github.com/microsoft/CsWin32/issues/775
* https://github.com/microsoft/CsWin32/issues/882


| Structure | x86 s/a | x64 s/a | arm64 s/a |
|--------|--------|--------|--------|
| SP_DEVINFO_DATA | 28/1 | 32/8 | 32/8 |

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_DEVINFO_DATA

[StructSizeField("cbSize")]
[SupportedArchitecture(Architecture.X64 | Architecture.Arm64)]
public struct SP_DEVINFO_DATA
```

| Structure | x86 s/a | x64 s/a | arm64 s/a |
|--------|--------|--------|--------|
| SP_ALTPLATFORM_INFO_V1 | 20/1 | 20/4 | 20/4 |

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_ALTPLATFORM_INFO_V1

[StructSizeField("cbSize")]
[SupportedArchitecture(Architecture.X64 | Architecture.Arm64)]
public struct SP_ALTPLATFORM_INFO_V1
```

| Structure | x86 s/a | x64 s/a | arm64 s/a |
|--------|--------|--------|--------|
| SP_ALTPLATFORM_INFO_V2 | 28/1 | 28/4 | 28/4 |

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_ALTPLATFORM_INFO_V2

[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X64 | Windows.Win32.Foundation.Metadata.Architecture.Arm64)]
public struct SP_ALTPLATFORM_INFO_V2
```

| Structure | x86 s/a | x64 s/a | arm64 s/a |
|--------|--------|--------|--------|
| SP_ALTPLATFORM_INFO_V3 | 35/1 | 36/4 | 36/4 |

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_ALTPLATFORM_INFO_V3

[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X64 | Windows.Win32.Foundation.Metadata.Architecture.Arm64)]
public struct SP_ALTPLATFORM_INFO_V3
```

| Structure | x86 s/a | x64 s/a | arm64 s/a |
|--------|--------|--------|--------|
| SP_CLASSINSTALL_HEADER | 8/1 | 8/4 | 8/4 |

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_CLASSINSTALL_HEADER

[StructSizeField("cbSize")]
[SupportedArchitecture(Architecture.X64 | Architecture.Arm64)]
public struct SP_CLASSINSTALL_HEADER
```

Closing this issue for now, but feel free to create a new issue with one specific structure and the changes you'd like to see. Thanks!

**Comment by Nuklon** [comment]
Thanks (everyone), I guess it makes more sense to put in CsWin32.
