### ISSUE TITLE
MapViewOfFile desiredAccess parameter constants (and enum) are missing

### ISSUE THREAD

**Issue by zgabi** [microsoft/win32metadata#164]
https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile
(at the moment soemthing is wrong with docs.microsoft.com, since it returns 404, but this link shuold be correct)

**Comment by mikebattista** [comment]
Thanks for filing these issues. We do have some work to do to round out our enum support and will ensure these are addressed.
