### ISSUE TITLE
D3D11_CREATE_DEVICE_FLAG should be an unsigned enum

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#165]
It's underlying type is `int32` when it should be `uint32` since it represents flags that can be OR'd together.

**Comment by kennykerr** [comment]
It's also meant to be used with `D3D11CreateDevice`, which expects a `uint32` flags argument.

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.4.
