### ISSUE TITLE
WlanOpenHandle uses Microsoft.Win32.SafeHandles.SafeFileHandle

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1656]
## Actual behavior

WlanOpenHandle function uses the Microsoft.Win32.SafeHandles.SafeFileHandle handle, but this is incorrect. It needs to be closed using WlanCloseHandle.

## Repro steps

1. `NativeMethods.txt` content:
```
WlanOpenHandle
```

### Context

CsWin32 version: 0.3.18-beta+dc807e7787
Target Framework: net 6.0
LangVersion (if explicitly set by project): latest

**Comment by AArnott** [comment]
This issue needs to be fixed in the metadata.

**Comment by Nuklon** [comment]
> This issue needs to be fixed in the metadata.

I checked the metadata but it's just using a HANDLE:

```csharp
		[SupportedOSPlatform("windows6.0.6000")]
		[Documentation("https://docs.microsoft.com/windows/win32/api/wlanapi/nf-wlanapi-wlanopenhandle")]
		[DllImport("wlanapi.dll", ExactSpelling = true, PreserveSig = false)]
		public unsafe static extern uint WlanOpenHandle([In] uint dwClientVersion, [Reserved] [Optional] void* pReserved, [Out] uint* pdwNegotiatedVersion, [Out] HANDLE* phClientHandle);
```

**Comment by mikebattista** [comment]
We can add `RAIIFree` to the `HANDLE` parameter.
