### ISSUE TITLE
`CertOpenStore`'s `hCryptProv` parameter should get a `[Reserved]` attribute

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1658]
As @drauch points at in https://github.com/microsoft/CsWin32/discussions/1002?converting=1#discussioncomment-6565607, and backed by [our documentation](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certopenstore#parameters), `hCryptProv` is meant to be NULL for all users. Can we add the `[Reserved]` attribute to that parameter?

This will allow CsWin32's friendly overload to omit the parameter.

**Comment by riverar** [comment]
Warning: This is not valid for Windows Server 2003 and Windows XP. This runs into an ongoing open question of what OSes win32metadata is targeting. And that answer defines the scope of the supported OS attribute https://github.com/microsoft/win32metadata/issues/738

**Comment by AArnott** [comment]
Ah, I hadn't noticed that. Thanks for pointing it out. 

In general, if the parameter isn't _always_ reserved, we shouldn't attribute it, and instead leave it to the author to do the right thing.
But in the case of XP and 2003, I personally think we should only support Windows versions that Microsoft supports.

**Comment by mikebattista** [comment]
I'm fine keeping `Reserved` in this case.

**Comment by riverar** [comment]
I don't think we should be entangling metadata with whatever Microsoft's support policy is today. By marking a _possibly_ reserved parameter as `[Reserved]` we then create an issue where projections can't differentiate between this reserved parameter and one that truly is always null (even on Windows XP).
