### ISSUE TITLE
`HMODULE` should be a `void*`

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1659]
`HMOUDLE` is [documented](https://learn.microsoft.com/en-us/windows/win32/api/psapi/ns-psapi-moduleinfo#remarks) as being the load address of a module, rather than a traditional opaque handle value. Therefore it should be `void*` in the metadata rather than `IntPtr`.

**Comment by riverar** [comment]
I'd argue the author of that paragraph is over-sharing information on the implementation of the handle. `HMODULE` implementation has changed once before so I think it makes sense to continue treating it as an opaque handle. You may remember, in Windows 1.0 this was a non-pointer integer used as an index into a handle table. Developers were _supposed_ to be none the wiser but, well, here we are.

**Comment by mikebattista** [comment]
HMODULE is consistent with the header definition.

**Comment by ChrisDenton** [comment]
I don't think that's the only place that mentions this. And it's hardly the first time that an implementation detail ossified into a de facto API guarantee. I think a lot would break if this were changed now. We're a long way from 1.0 🙂

**Comment by riverar** [comment]
I don't like it, but it's hard not to agree--I can get behind the idea of changing all HINSTANCE/HMODULEs to void*, as a way of "correcting the mistake" so to speak.

**Comment by ChrisDenton** [comment]
> HMODULE is consistent with the header definition.

Not really. In C a `HMODULE` eventually resolves to `void*` so the distinction between being a handle or a pointer is less relevant. In the metadata the handle is a pointer-sized integer so the distinction does matter more.

**Comment by mikebattista** [comment]
By that logic, are you saying that anything defined as `DECLARE_HANDLE` should be `void*` instead of `IntPtr`? `HMODULE` uses this same definition that other `HANDLEs` use.

**Comment by ChrisDenton** [comment]
I mean, `HMODULE` is pretty unique amongst handle types. Usually they're either opaque handles or known values (pseudo handles). To my knowledge `HMODULE` is the only one that is an actual pointer.
