### ISSUE TITLE
IAMStreamConfig::GetStreamCaps returns single byte instead of array

### ISSUE THREAD

**Issue by andrekoehler** [microsoft/win32metadata#1661]
https://learn.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-iamstreamconfig-getstreamcaps
```
HRESULT GetStreamCaps(
  [in]  int           iIndex,
  [out] AM_MEDIA_TYPE **ppmt,
  [out] BYTE          *pSCC
);
```

The docs state that pSCC shall be an array allocated by the caller. The size of the array is returned by a prior call to the `IAMStreamConfig::GetNumberOfCapabilities` method.

However, CsWin32 generates the following code:
```
[PreserveSig()]
winmdroot.Foundation.HRESULT GetStreamCaps(int iIndex, out winmdroot.Media.MediaFoundation.AM_MEDIA_TYPE[] ppmt, out byte pSCC);
```
The generated code always assumes an array of size 1 Byte. I believe it would be better to just let the user pass a `void*` for `pSCC` since it can either contain a `VIDEO_STREAM_CONFIG_CAPS` structure or a `AUDIO_STREAM_CONFIG_CAPS` structure.

**Comment by mikebattista** [comment]
@aarnott

The metadata looks aligned with the header. Not sure what change you'd like to see and if it's a metadata change or a CsWin32 change.

**Comment by andrekoehler** [comment]
The metadata does reflect the C header, but in C there is ambiguity between a pointer to a single element and a pointer to the first element of an array. This ambiguity in C is the cause of this issue. My guess is that CsWin32 works as intended, so there probably has to be a change to the metadata, that's why I posted the issue here.

In the current state, the GetStreamCaps function is unusable. It expects either a pointer to a VIDEO_STREAM_CONFIG_CAPS struct or to a AUDIO_STREAM_CONFIG_CAPS struct. Both structs are way bigger than 1 byte. What makes this case a bit difficult is, that the caller does not have to provide the size of the array directly in this call.

**Comment by mikebattista** [comment]
Ok. So the proposal is to change `byte*` to `void*`? @aarnott would that result in the expected projection experience or is there a better option?

**Comment by AArnott** [comment]
An interesting case. I can't think of a precedent for this from prior cases we've looked at. I agree with @andrekoehler's take that this comes from an ambiguity in C. Maybe we should apply the `NativeArrayInfoAttribute` to this parameter. That will hopefully make CsWin32 "just work", and if not, we could fix it up to do so.
