### ISSUE TITLE
DXGI_ERROR_UNSUPPORTED

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#167]
This constant is defined in the `SystemServices` namespace rather than the `Dxgi` device. Seems wrong?

It is also the wrong type. It should be a `Windows.Win32.Com.HRESULT` constant and not an `int32` constant.

**Comment by DefaultRyan** [comment]
I've noticed that the vast majority (if not all) of the constants I've used seem to be defined in `SystemServices`. `WS_OVERLAPPED_WINDOW`, `CW_USEDEFAULT`. `SW_SHOWDEFAULT`, `WM_QUIT` and other WM_* messagaes. These all seem like they should be in `WindowsAndMessaging`.

**Comment by kennykerr** [comment]
For languages that rely on namespaces (C++ and Rust) this is a real usability issue.
