### ISSUE TITLE
DEVPROP_FALSE / DEVPROP_TRUE incorrect char type

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1675]
DEVPROP booleans are 8-bit, not Unicode 16-bit chars (ECMA-335). We should represent these as int8/byte consts instead.

devpropdef.h
```cpp
typedef CHAR DEVPROP_BOOLEAN, *PDEVPROP_BOOLEAN;
#define DEVPROP_TRUE  ((DEVPROP_BOOLEAN)-1)
#define DEVPROP_FALSE ((DEVPROP_BOOLEAN) 0)
```

Current metadata:
```
public const char DEVPROP_FALSE = '\0';
public const char DEVPROP_TRUE = '\uffff';
```

Related:
https://github.com/microsoft/win32metadata/issues/1621
https://github.com/microsoft/windows-rs/pull/2599

**Comment by mikebattista** [comment]
Let me know if the latest changes are what you expect.
