### ISSUE TITLE
WaitableTimer related functions' A/W variants are split across functions

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1676]
The timer related functions are split across namespaces in a poor way, leading to a poor CsWin32 experience (https://github.com/microsoft/CsWin32/discussions/1012).

![image](https://github.com/microsoft/win32metadata/assets/3548/4627e530-de7b-4bc3-8afe-a91bde10cf62)

- `CreateWaitableTimerA`/`CreateWaitableTimerW`
- `CreateWaitableTimerExA`/`CreateWaitableTimerExW`
- `OpenWaitableTimerA`/`OpenWaitableTimerW`

`SetWaitableTimer`/`SetWaitableTimerEx`/`CancelWaitableTimer` are all consistently in the `System.Threading` namespace. Let's get all these waitabletimer APIs into the same namespace.

Thanks to @Gavin-Williams for reporting the CsWin32 usability issue.

**Comment by ChrisDenton** [comment]
I think in practice "WindowsProgramming" ends up being a catchall for things that haven't been categorised yet. Although undoubtedly there are some functions that do belong there.

**Comment by mikebattista** [comment]
The A and W APIs are defined in different headers which are assigned to different namespaces. Just need to remap the As.
