### ISSUE TITLE
Investigate adding GDI+ APIs

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1678]
GDI+ is generally a collection of C++ classes but a flat API is available via `gdiplusflat.h` and impl. via `gdiplus.dll`.

We should take special note to use `#define GDIPVER 0x0110` to capture GDI+ version 1.1 APIs.

**Comment by mikebattista** [comment]
Duplicate of #1287

**Comment by riverar** [comment]
@mikebattista oops, thanks!
