### ISSUE TITLE
API sets can cause link errors (e.g. against api-ms-win-shcore-scaling-l1-1-1.lib)

### ISSUE THREAD

**Issue by iainnicol** [microsoft/win32metadata#168]
For example the API `GetScaleFactorForMonitor` ends up in the metadata with `DllImport("api-ms-win-shcore-scaling-l1-1-1", ExactSpelling = true)]`

Downstream, the Rust generator tries to link against `api-ms-win-shcore-scaling-l1-1-1.lib`, which does not exist (???), leading to build failures.

This problem would be sidestepped if it was `DllImport("Shcore")`.

(I wasn't sure where to open this - arguably this is an issue with either the upstream ClangSharp generator, or downstream in the Rust generator.)

**Comment by kennykerr** [comment]
There are two different issues here. The first is that the metadata should not refer to api set DLLs if at all possible. That's tracked by this issue: https://github.com/microsoft/win32metadata/issues/92

The second is that Rust doesn't yet support DLL imports and expects LIB imports. We're working on adding [support for DLL imports](https://github.com/rust-lang/rfcs/blob/master/text/2627-raw-dylib-kind.md) to the Rust compiler. In the mean time, the Rust `windows` crate fudges it and assumes there's a lib by the same name as the DLL name mentioned in metadata. This is clearly not right, but the best we can do for now. It mostly only falls apart when the metadata refers to API sets hence the value in fixing https://github.com/microsoft/win32metadata/issues/92.

**Comment by iainnicol** [comment]
Ah, gotcha. I was sort of aware of the dylib Rust stuff, but hadn't seen #92, which as you say would work around the problems. (In my defense you just renamed the latter issue! 😄)

I'll close this as a dupe then.

**Comment by kennykerr** [comment]
Yep, I realized a better title would have helped. 😜
