### ISSUE TITLE
Add FWP_ACTION_TYPE

### ISSUE THREAD

**Issue by HavenDV** [microsoft/win32metadata#1688]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
```
0>NativeMethods.txt(65,1): Warning PInvoke001 : Method, type or constant "FWP_ACTION_TYPE" not found
```
```xml
<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.18-beta">
```

**Comment by riverar** [comment]
@havenDV In the future, please spend a few more seconds to make this readable.
