### ISSUE TITLE
Remove redundant aliases for `UNICODE_STRING`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1692]
I had a quick look at this, but the Win32 metadata currently has three redundant aliases of `UNICODE_STRING`:

* Windows.Win32.Foundation.UNICODE_STRING
* Windows.Win32.Security.Authentication.Identity.LSA_UNICODE_STRING
* Windows.Win32.Storage.IscsiDisc.NTSCSI_UNICODE_STRING

We'd need to collapse these down to a single definition to practically deal with this issue.

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/issues/2566#issuecomment-1701248452_

**Comment by riverar** [comment]
Found another `RPC_UNICODE_STRING`. https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lsad/4b35e17e-405c-4e99-8ebe-8b28f047156f

**Comment by kennykerr** [comment]
There also appear to be all kinds of Ansi variants as well.

**Comment by elachlan** [comment]
Do we add these under remap in `scraper.settings.rsp`?

**Comment by riverar** [comment]
We're still chewing on this, but we may have to abandon unifying all these duplicate string types (to remain consistent with headers and docs, not create a namespace mess, etc.).

**Comment by mikebattista** [comment]
> We're still chewing on this, but we may have to abandon unifying all these duplicate string types (to remain consistent with headers and docs, not create a namespace mess, etc.).

I agree with the concerns. I'm going to close this out in the meantime. Reactivate if anything becomes actionable here.

**Comment by ChrisDenton** [comment]
The only actionable thing I can think of that sidesteps those concerns is to designate one type as the canonical type (e.g. `UNICODE_STRING`) and then use an attribute to annotate other types to reference the canonical type. That way it's up to projections if they want to experiment with different approaches, assuming that would be useful.
