### ISSUE TITLE
Manually rename union struct properties for `TASKDIALOGCONFIG`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1698]
Is there a way we can rename the union struct properties for `TASKDIALOGCONFIG`?

We used `mainIcon` and `footerIcon` in winforms.

https://learn.microsoft.com/windows/win32/api/commctrl/ns-commctrl-taskdialogconfig

Related Winforms Issue: https://github.com/dotnet/winforms/issues/9825

**Comment by riverar** [comment]
We want to faithfully represent what's in the headers; renaming beyond that is a projection specific choice. (I would recommend just using the original names in this case.)

**Comment by elachlan** [comment]
I guess when/if discriminated unions are implemented in C#, then it will be easier to represent them in Metadata/CsWin32?

https://github.com/dotnet/csharplang/issues/113

**Comment by mikebattista** [comment]
@aarnott? Should we move this issue to CsWin32?

**Comment by riverar** [comment]
For context, the reported issue is that devs don't want this ugly looking piece of code:

```csharp
var config = new TASKDIALOGCONFIG
{
    Anonymous1 = new TASKDIALOGCONFIG._Anonymous1_e__Union
    {
        // Option 1
        hMainIcon = new HICON(...),

        // Option 2
        pszMainIcon = new PCWSTR(...)
    },

    // ...
};
```

Not sure there's anything we can safely do here.

**Comment by elachlan** [comment]
Do unions usually follow the same naming convention of each option having similar names?

**Comment by AArnott** [comment]
We already have a CsWin32 issue tracking improving the union struct experience: https://github.com/microsoft/CsWin32/issues/408

I believe the metadata should represent the original names as recorded in the header files.

**Comment by mikebattista** [comment]
Agreed. Thanks.
