### ISSUE TITLE
Add a Broadcast property to `HWND` for clearer semantics

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#1699]
I've been working with the HWND structure and realized that it might be beneficial to have a Broadcast property directly in the HWND structure to represent the broadcast handle, rather than casting it manually each time using (HWND)0xFFFF.

Proposal:
Add a static property to HWND that represents the broadcast handle. This would make the code more readable and reduce the potential for errors.

`public static HWND Broadcast => new HWND(0xFFFF);`

**Comment by elachlan** [comment]
What projection are you using? That is usually done in those.

**Comment by vitkuz573** [comment]
I'm using CsWin32

**Comment by elachlan** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage

I guess we should add a new const in the metadata `HWND_BROADCAST ((HWND)0xffff)` similar to `HWND_TOP` and the others.

**Comment by elachlan** [comment]
It exists in the headers:
https://github.com/microsoft/win32metadata/blob/581c6390d6b4e83abe98b3a72a2c04f7252b70c7/generation/WinSDK/RecompiledIdlHeaders/um/WinUser.h#L4079-L4082

**Comment by elachlan** [comment]
The `ConstantsScraper` does not handle the value `0xffff`, if I replace the value in the header with `65535` it gets picked up.
