### ISSUE TITLE
`GpStatus` enum missing value and documentation link is wrong

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1712]
Actual documentation link: https://learn.microsoft.com/en-us/windows/win32/api/Gdiplustypes/ne-gdiplustypes-status

Missing value: `ProfileNotFound = 21`

Related: #1287 
Winforms tracking: https://github.com/dotnet/winforms/issues/7468

**Comment by riverar** [comment]
@elachlan Good catch on that one, hope that closes out all your GdiPlus issues?

**Comment by elachlan** [comment]
There are quite a few but I haven't had time to go through it all. Ill be doing a review around the API surface for system.drawing.common soon.
