### ISSUE TITLE
Invalid type: `FileSystem::WriteFile`, `lpBuffer`

### ISSUE THREAD

**Issue by T-256** [microsoft/win32metadata#1718]
- main header:
![image](https://github.com/microsoft/win32metadata/assets/132141463/6171817c-753d-424a-8103-4aed830851ae)

- win32metadata:
![image](https://github.com/microsoft/win32metadata/assets/132141463/4081f9a9-6837-4d76-bcb7-c4f193fa8223)

**Comment by mikebattista** [comment]
This is by design. See https://github.com/microsoft/win32metadata/issues/1534.
