### ISSUE TITLE
D Programming language 

### ISSUE THREAD

**Issue by Imperatorn** [microsoft/win32metadata#172]
Hi there!

What would it take to support D?

Thanks! 😊

**Comment by pjmlp** [comment]
Adding my vote for D, given its similarity with C#, it could be a very good companion language for .NET developers when doing systems programming related tasks on Windows.

**Comment by kennykerr** [comment]
See https://github.com/microsoft/win32metadata/issues/174#issuecomment-766284319

**Comment by mikebattista** [comment]
#183 captures the guidance for new language projection requests.

**Comment by pjmlp** [comment]
For anyone reading this closed issue, there is now ongoing community work for D.

https://github.com/rumbu13/windows-d

**Comment by CrazyPython** [comment]
Adding my vote for D as a natural evolution of beginner-friendly C that compiles faster and is a commercial-grade language.

**Comment by mikebattista** [comment]
Awesome. This is great to see and thanks for letting us know. I've added this project to the list of projections in our README to help with discovery and will do the same with other projects as they come online.

@rumbu13 let us know if you hit any issues with the metadata that block your progress or hinder the developer experience.
