### ISSUE TITLE
Missing metadata for SECURITY_MAX_SID_SIZE

### ISSUE THREAD

**Issue by joeloff** [microsoft/win32metadata#1721]
# Description
I'm using the `cswin32` package (0.3.46-beta). It failed to generate the proper constant for `SECURITY_MAX_SID_SIZE`.  I see the following error from the source generator: `warning PInvoke001: Method, type or constant "SECURITY_MAX_SID_SIZE" not found`

The constant is defined in `winnt.h`.

After talking with the package owner it was suggested this may be related to missing metadata and to file an issue here.

Thank you.

**Comment by mikebattista** [comment]
```
#define SECURITY_MAX_SID_SIZE  \
      (sizeof(SID) - sizeof(DWORD) + (SID_MAX_SUB_AUTHORITIES * sizeof(DWORD)))
```

If you tell me what this computes to, we can add it.

**Comment by kennykerr** [comment]
On x64 and x86 it evaluates to 68.
I can't test on ARM.

**Comment by robmikh** [comment]
It evaluates to 68 on ARM64 as well.
