### ISSUE TITLE
Allow using Nt* versions of Zw* APIs

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1722]
**Is your feature request related to a problem? Please describe.**
Many `Nt*` APIs are only documented under their `Zw*` variant. The docs clearly state that you should use the `Nt*` variant in user mode:

For [example](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwquerykey#remarks):

> If the call to this function occurs in user mode, you should use the name "NtQueryKey" instead of "ZwQueryKey".

**Describe the solution you'd like**
For any `Nt*` API request that doesn't already have metadata associated with it, look for a matching `Zw*` API and use that definition with the `Nt*` prefix.

**Comment by mikebattista** [comment]
All Nt* APIs are in the WDK metadata. If anything I'd rather expose these over there next to the Zw* APIs.

**Comment by riverar** [comment]
@mikebattista I don't see NtQueryKey, as an example. 

Also I tend to look at the WDK and its metadata as "for kernel devs". These would be user mode APIs and probably better homed here. But there's definitely other ways to slice it, so as long as they are _somewhere_ that's a good start!

**Comment by mikebattista** [comment]
From some analysis, it looks like below are all the Zw APIs currently in the metadata that don't have a corresponding Nt definition. Is the spec here to just clone the Zw definitions and change the prefix to Nt?

```
ZwAllocateLocallyUniqueId
ZwAllocateVirtualMemoryEx
ZwCancelTimer
ZwCommitRegistryTransaction
ZwCreateDirectoryObject
ZwCreateEvent
ZwCreateKey
ZwCreateKeyTransacted
ZwCreateRegistryTransaction
ZwCreateTimer
ZwDeleteFile
ZwDeleteKey
ZwDeleteValueKey
ZwDisplayString
ZwDuplicateObject
ZwEnumerateKey
ZwEnumerateValueKey
ZwFlushBuffersFile
ZwFlushKey
ZwFlushVirtualMemory
ZwLoadDriver
ZwMakeTemporaryObject
ZwMapViewOfSection
ZwNotifyChangeKey
ZwOpenDirectoryObject
ZwOpenEvent
ZwOpenKey
ZwOpenKeyEx
ZwOpenKeyTransacted
ZwOpenKeyTransactedEx
ZwOpenSection
ZwOpenSymbolicLinkObject
ZwOpenTimer
ZwQueryEaFile
ZwQueryFullAttributesFile
ZwQueryKey
ZwQuerySymbolicLinkObject
ZwQueryValueKey
ZwRestoreKey
ZwSaveKey
ZwSaveKeyEx
ZwSetEaFile
ZwSetEvent
ZwSetTimer
ZwSetTimerEx
ZwSetValueKey
ZwTerminateProcess
ZwUnloadDriver
ZwUnmapViewOfSection
```

**Comment by TSlivede** [comment]
@mikebattista Thank you for adding these!

As I mentioned in https://github.com/microsoft/wdkmetadata/issues/68, there are also some Nt* functions without corresponding Zw* metadata. Wouldn't it make sense to also add the corresponding Zw* declarations? (For discoverability and consistency...)

Nt* functions currently in metadata without corresponding Zw* (I checked via dumpbin, the Zw* exports do all exist in ntdll.dll):

```
NtAccessCheckAndAuditAlarm
NtAccessCheckByTypeAndAuditAlarm
NtAccessCheckByTypeResultListAndAuditAlarm
NtAccessCheckByTypeResultListAndAuditAlarmByHandle
NtAdjustGroupsToken
NtAdjustPrivilegesToken
NtCancelIoFileEx
NtCloseObjectAuditAlarm
NtCreateSectionEx
NtDeleteObjectAuditAlarm
NtFilterToken
NtImpersonateAnonymousToken
NtManagePartition
NtNotifyChangeMultipleKeys
NtOpenObjectAuditAlarm
NtOpenProcessToken
NtOpenRegistryTransaction
NtOpenThreadToken
NtPrivilegeCheck
NtPrivilegedServiceAuditAlarm
NtPrivilegeObjectAuditAlarm
NtPropagationComplete
NtPropagationFailed
NtQueryInformationProcess
NtQueryInformationThread
NtQueryMultipleValueKey
NtQuerySystemInformation
NtQuerySystemTime
NtQueryTimerResolution
NtRegisterProtocolAddressInformation
NtRenameTransactionManager
NtRollbackRegistryTransaction
```

**Comment by mikebattista** [comment]
Yes. Let me add those. Thanks for the feedback. I reopened the WDK issue where the changes are being made.
