### ISSUE TITLE
Missing PRINT_INFO_* struct.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [microsoft/win32metadata#1729]
Missing `PRINT_INFO_*` struct and `GetPrinter` function need optimization.

**Comment by riverar** [comment]
We can get those structs added.

The `_Out_ LPBYTE  pPrinter` parameter can point to `PRINTER_INFO_1`-`PRINTER_INFO_9` so might not be possible to make that more specific in metadata.

**Comment by MiyamuraMiyako** [comment]
Ok, thanks.

**Comment by mikebattista** [comment]
These already exist in the metadata in -A and -W versions.

You need to use those explicitly, or the projection you're using needs to abstract that away. For example, always offering the Unicode -W variant and removing the suffix. See https://github.com/microsoft/win32metadata/issues/711.
