### ISSUE TITLE
Missing EXCEPTION_CONTINUE_EXECUTION, etc.

### ISSUE THREAD

**Issue by vvoznesensky** [microsoft/win32metadata#1731]
No EXCEPTION_CONTINUE_EXECUTION, EXCEPTION_... of excpt.h in the metadata.

**Comment by mikebattista** [comment]
I see these in ksarm.h. Where are these constants used? Are they kernel-related?

What namespace would you expect them in? Should they be in the WDK metadata instead?

**Comment by vvoznesensky** [comment]
> I see these in ksarm.h. Where are these constants used? Are they kernel-related?
> 
> What namespace would you expect them in? Should they be in the WDK metadata instead?

I use them [here](https://github.com/vvoznesensky/tmfalloc/blob/9838ac1aae9b7b8c06be85232194b0b111649277/src/windows.rs#L235) in unhandled exception filter. Yes, I utilize memory violation in my userspace code.

I have no idea about the namespace, but probably in the same place where SetUnhandledExceptionFilter is located.

**Comment by mikebattista** [comment]
There is ksarm.h and ksarm64.h which have different values for different constants. How should we handle those?

**Comment by vvoznesensky** [comment]
> There is ksarm.h and ksarm64.h which have different values for different constants. How should we handle those?

I need constants from excpt.h

**Comment by mikebattista** [comment]
That header doesn't exist in the SDK.

**Comment by riverar** [comment]
@mikebattista Ships with MSVC (e.g., `VC\Tools\MSVC\14.37.32822\include\excpt.h`)

```cpp
// Defined values for the exception filter expression
#define EXCEPTION_EXECUTE_HANDLER      1
#define EXCEPTION_CONTINUE_SEARCH      0
#define EXCEPTION_CONTINUE_EXECUTION (-1)
```

**Comment by mikebattista** [comment]
We can add these.
