### ISSUE TITLE
Missing CLR_INVALID constant (wingdi.h)

### ISSUE THREAD

**Issue by verdie-g** [microsoft/win32metadata#1732]
[GetPixel](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getpixel) can return `CLR_INVALID`. Could you consider adding that macro. Thanks.

**Comment by mikebattista** [comment]
This appears to be in the metadata already.

**Comment by verdie-g** [comment]
I must have misunderstood how CsWin32 works for constants. I've added `CLR_INVALID ` to `NativeMethods.txt` but I can't find it generated anywhere 🤔

**Comment by mikebattista** [comment]
@aarnott could you please advise the proper usage in CsWin32?

**Comment by AArnott** [comment]
Quite right, @mikebattista. Sorry for not checking before forwarding.

@verdie-g `CLR_INVALID` is added to the `PInvoke` class when you add it to `NativeMethods.txt`.

**Comment by verdie-g** [comment]
Indeed, probably a typo on my side. Thanks!
