### ISSUE TITLE
SAPI Engine-Level Interfaces missing from Metdata

### ISSUE THREAD

**Issue by leonardder** [microsoft/win32metadata#1736]
When looking at the [SAPI 5.4 documentation](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee125663(v=vs.85)) on Microsoft learn, there are several interfaces listed that are part of the Win32 metdata, such as ISpObjectWithToken, and ISpVoice. However, it looks like the Engine-Level Interfaces, such as ISpTTSEngine and ISpTTSEngineSite are missing from the metadata. Could the engine level interfaces be added somehow?

**Comment by mikebattista** [comment]
https://github.com/microsoft/win32metadata/blob/61dde082add60e280331451104a733e3040fed13/generation/WinSDK/Partitions/Speech/main.cpp#L10

That would explain why they're missing. Are these headers meant to be used together? There are lots of duplicate definition errors.

**Comment by leonardder** [comment]
I think sapi53.h is wrong anyway. Sapi53.h is for version 5.3 whereas sapi.h/idl is for sapi 5.4, and sapiddk.h/idl include sapi.h/idl, respectively.
Will we loose anything if sapi53.h would be swapped for sapiddk.h?
