### ISSUE TITLE
`LCS_WINDOWS_COLOR_SPACE` and `LCS_sRGB` are missing for `LcsCsType` enum constants

### ISSUE THREAD

**Issue by rhysd** [microsoft/win32metadata#1740]
### Suggestion

`LOGCOLORSPACEA` struct has `lcsCSType` field. The field expects `LCS_CALIBRATED_RGB` or `LCS_sRGB` or `LCS_WINDOWS_COLOR_SPACE` enum constants.

https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logcolorspacea

windows-rs only defines [`LCS_CALIBRATED_RGB`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/constant.LCS_CALIBRATED_RGB.html). Can we add `LCS_sRGB` and `LCS_WINDOWS_COLOR_SPACE` constants?

winapi crate defines these constants:

- https://docs.rs/winapi/latest/winapi/um/wingdi/constant.LCS_WINDOWS_COLOR_SPACE.html
- https://docs.rs/winapi/latest/winapi/um/wingdi/constant.LCS_CALIBRATED_RGB.html
- https://docs.rs/winapi/latest/winapi/um/wingdi/constant.LCS_sRGB.html

**Comment by rhysd** [comment]
Thank you for handling this issue. I got it.

**Comment by mikebattista** [comment]
https://github.com/microsoft/win32metadata/blob/53c95c591ab0d6936ce0947a3acdbfb81401b42d/generation/WinSDK/RecompiledIdlHeaders/um/wingdi.h#L669-L675

Are these strings treated as ints? If so, what's their value?

**Comment by rhysd** [comment]
> what's their value?

According to winapi crate,

```rust
pub const LCS_sRGB: LCSCSTYPE = 0x7352_4742;
pub const LCS_WINDOWS_COLOR_SPACE: LCSCSTYPE = 0x5769_6E20;
```

**Comment by mikebattista** [comment]
Thanks. I will group these all into an LCSCSTYPE enum.
