### ISSUE TITLE
Update tools to .NET 8

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1746]
ADO hosted runners recently switched to .NET 8 workloads/components which broke our pipelines.

Switch to .NET 8 or update the pipeline to be compatible with the latest ADO runners.

**Comment by mikebattista** [comment]
Need to update to ClangSharp 17.0 but encountered a crashing bug with ClangSharp tests disabled. Working with @tannergooding to resolve.

**Comment by riverar** [comment]
The currently configured clangsharp uses .NET 7.0.14. (I had to install this on a fresh machine last night.) The net6/net8 targets in the tooling don't seem to have any bearing on that.

**Comment by mikebattista** [comment]
I've been fighting with the new ADO runner images since they updated to .NET 8 which broke our builds. For now I was able to get .NET 6 and ClangSharp 16 working again.

Once the ClangSharp 17 bug I encountered is fixed, I should be able to update everything to .NET 8.

**Comment by tannergooding** [comment]
This should have been fixed in the latest builds. Please let me know if you see any other issues.

**Comment by mikebattista** [comment]
Works great. Thanks for the fix!
