### ISSUE TITLE
`HtmlHelp.h` should use `hhctrl.ocx` not `htmlhelp.dll`

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1749]
We ran into an error in winforms `Unable to load DLL "htmlhelp.dll"`.
https://github.com/dotnet/winforms/issues/10410

This is the PInvoke generated using CsWin32/Win32metadata
```csharp
[DllImport("htmlhelp.dll", ExactSpelling = true, EntryPoint = "HtmlHelpW")]
static extern winmdroot.Foundation.HWND LocalExternFunction(winmdroot.Foundation.HWND hwndCaller, winmdroot.Foundation.PCWSTR pszFile, uint uCommand, nuint dwData);
```

This is the code pulled from ILSpy:
```Csharp
[DllImport("htmlhelp.dll", ExactSpelling = true, PreserveSig = false)]
[Unicode]
[Documentation("https://learn.microsoft.com/windows/win32/api/htmlhelp/nf-htmlhelp-htmlhelpw")]
public static extern HWND HtmlHelpW([Optional][In] HWND hwndCaller, [In][Const] PWSTR pszFile, [In][AssociatedEnum("HTML_HELP_COMMAND")] uint uCommand, [In] UIntPtr dwData);
```

It should probably point to `hhctrl.ocx` not `htmlhelp.dll`.

https://github.com/microsoft/win32metadata/blob/a5698d9a63cbf096f787425104f918f5a9cbcf7d/generation/WinSDK/libMappings.rsp#L26654-L26655

Related: #1345

**Comment by elachlan** [comment]
CC: @Tanya-Solyanik

**Comment by riverar** [comment]
Thanks, we'll get that patched up.

**Comment by Tanya-Solyanik** [comment]
@mikebattista @riverar  - When are you planning to do a release with these changes?
