### ISSUE TITLE
Incorrect features for `ConvertSidToStringSidW()`/`ConvertSidToStringSidA()`

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1750]
The [pages for the functions](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Security/Authorization/fn.ConvertSidToStringSidW.html) list `"Win32_Foundation"` as required features. But it only works with `"Win32_Security_Authorization"` (and *also* `"Win32_Foundation"`?).

**Comment by mikebattista** [comment]
@kennykerr is this a doc bug?

**Comment by riverar** [comment]
Not a doc bug, we're currently tracking this/discussing the way forward here: https://github.com/microsoft/windows-rs/issues/2717.

Workaround: Visit the [parent module](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Security/Authorization/index.html) for required dependent features.
