### ISSUE TITLE
Update to latest Windows SDK 10.0.22621.2428

### ISSUE THREAD

**Issue by coroiu** [microsoft/win32metadata#1751]
### Suggestion

I'm not sure what the process for generating new versions of Win32 APIs looks like, but if possible I would like to request an update of the WebAuthn related APIs. According to Microsofts GitHub repository the latest version of `MAKE_CREDENTIALS_OPTIONS` is version 7 (found here: https://github.com/microsoft/webauthn/blob/master/webauthn.h).

**Comment by mikebattista** [comment]
@akshayku does this repo contain newer versions of APIs in the Windows SDK?

Is the intent that these APIs will deviate or that the GitHub headers will eventually make their way back into the platform SDK?

**Comment by riverar** [comment]
@mikebattista Might want to reach out to `fido-dev` alias too

**Comment by jonesnl** [comment]
@mikebattista

I just downloaded the latest public SDK (10.0.22621.2428) from https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ and it has `WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_7` in the provided `webauthn.h` header.

Has the metadata used here been regenerated since the latest SDK release in October?

**Comment by mikebattista** [comment]
No that new SDK hasn't been incorporated yet. We can update.

I'm assuming it has all the other APIs wanted here as well? Updating to a new platform SDK is a different request than incorporating headers from an external repo.

**Comment by jonesnl** [comment]
It has the current public set of APIs that apps should consume, yes.

We don't generally want people consuming that header outside of the public SDK.

There is some exceptions with integration testing from web browsers (Chromium/Firefox) which is mostly why that repo exists.

All changes from that repo will end up in the public SDK when the changes reach stable Windows releases though, and early access to the same changes can be found in the [Insider SDK](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) for testing against insider builds.

**Comment by jonesnl** [comment]
So in short, no I don't think we should have any special treatment of the webauthn.h header for now.

**Comment by mikebattista** [comment]
Thanks. Working on the SDK update now.

**Comment by jonesnl** [comment]
Do note that with APIs that are added mid-release, you may run into some cases where a client is running on an old OS version that doesn't have the new library containing the new API yet: https://github.com/microsoft/windows-rs/issues/421

So while the new header will give you access to the new structs and version info, you may need to use DelayLoading or LoadLibrary/GetProcAddress if you are trying to access a new function in a way that can detect if the local OS doesn't have support for that function yet.

**Comment by riverar** [comment]
@jonesnl Hmm, how do devs learn if an API is available or not? Is that something we can get added to the docs @ https://learn.microsoft.com/windows/win32/api/webauthn/? Or get annotations/WINVER fences added to the headers themselves?
