### ISSUE TITLE
Functions missing `CanReturnMultipleSuccessValuesAttribute` or needing other treatment

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1754]
I encountered one and then found more via Google by searching for `S_OK` and `S_FALSE` and checking the functions in the crate documentation:

```
SHDefExtractIconW
SHDefExtractIconA
PathCchAddBackslash
PathCchAddBackslashEx
PathCchRemoveBackslash
PathCchStripToRoot
PathCchStripPrefix
CanUnloadNow
GetApplicationRecoveryCallback
SHGetAttributesFromDataObject
ScriptIsComplex
IFEDictionary::ExistWord
CoGetTreatAsClass
CoInitialize
CoInitializeEx
IPin::QueryAccept
IOleUndoManager::Close
ISyncMgrUIOperation::Run
IEnumUnknown::Next
IEnumConnectionPoints::Next
IEnumFullIDList::Next
ISyncMgrSyncItemInfo::IsConnected
IEnumOleUndoUnits::Next
IEnumFORMATETC::Next
IEnumConnections::Next
IEnumEventObject::Reset
ICodecAPI::IsModifiable
IPinConnection::IsEndPin
IMoniker::IsEqual
IBitsPeerCacheAdministration::SetMaximumContentAge
```

**Comment by mikebattista** [comment]
Is the request just to add the attribute or something else? What did you mean by "other treatment"?

**Comment by riverar** [comment]
@Enyium  Can you pare this list down to only items needing `CanReturnMultipleSuccessValuesAttribute`? We can handle the "other treatment" investigations separately.

**Comment by Enyium** [comment]
Needing `CanReturnMultipleSuccessValuesAttribute`:

```
SHDefExtractIconW
SHDefExtractIconA
PathCchAddBackslash
PathCchAddBackslashEx
PathCchRemoveBackslash
PathCchStripToRoot
PathCchStripPrefix
GetApplicationRecoveryCallback
ScriptIsComplex
IFEDictionary::ExistWord
CoGetTreatAsClass
CoInitialize
CoInitializeEx
IOleUndoManager::Close
ISyncMgrUIOperation::Run
IEnumFullIDList::Next
```

---

These functions are documented as returning only `S_OK` and `S_FALSE` and not any `E_...` error code:

```
SHGetAttributesFromDataObject
IPin::QueryAccept
IEnumUnknown::Next
IEnumConnectionPoints::Next
IEnumOleUndoUnits::Next
IEnumFORMATETC::Next
IEnumConnections::Next
IEnumEventObject::Reset
IPinConnection::IsEndPin
IBitsPeerCacheAdministration::SetMaximumContentAge
```

Is [`Result<()>`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/fn.SHGetAttributesFromDataObject.html) correct then?

---

Same, but then contains a mention of `E_INVALIDARG` in the "Implementation-specific Notes":

```
IMoniker::IsEqual
```

---

```
ISyncMgrSyncItemInfo::IsConnected
```

> Returns S_OK if the item is connected; otherwise, S_FALSE. An error returned by this method will be interpreted as S_OK.

---

```
ICodecAPI::IsModifiable
```

> Any errors besides those in the previous table [S_OK and S_FALSE] indicate an inability to process the call.
