### ISSUE TITLE
`IInkRecognizerContext::IsStringSupported()` has wrong return type

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1755]
I just saw this discrepancy in passing.

Official:

```
HRESULT IsStringSupported(
  HRECOCONTEXT hrc,
  ULONG        wcString,
  const WCHAR  *pwcString
);
```

(https://learn.microsoft.com/en-us/windows/win32/api/recapis/nf-recapis-isstringsupported)

`windows` Crate:

```
pub unsafe fn IsStringSupported<P0>(&self, string: P0) -> Result<VARIANT_BOOL>
where
    P0: IntoParam<BSTR>,
```

(https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/TabletPC/struct.IInkRecognizerContext.html#method.IsStringSupported)

```
#[repr(transparent)]
pub struct VARIANT_BOOL(pub i16);
```

Note that `IsStringSupported()` has multiple success values.

**Comment by riverar** [comment]
There are two APIs being conflated here.

```csharp
[Documentation("https://learn.microsoft.com/windows/win32/api/recapis/nf-recapis-isstringsupported")]
public static extern HRESULT IsStringSupported([In] HRECOCONTEXT hrc, [In] uint wcString, [In][Const] PWSTR pwcString);

// Windows.Win32.UI.TabletPC.IInkRecognizerContext
[Documentation("https://learn.microsoft.com/windows/win32/api/msinkaut/nf-msinkaut-iinkrecognizercontext-isstringsupported")]
unsafe HRESULT IsStringSupported([In] BSTR String, [Out] VARIANT_BOOL* Supported);
```

The HRESULT returned by `IInkRecognizerContext::IsStringSupported` is being captured by the `windows` crate and transformed into a [`Result<VARIANT_BOOL>`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/TabletPC/struct.IInkRecognizerContext.html#method.IsStringSupported).

No bug here!
