### ISSUE TITLE
Document how to update dependencies (Windows SDK, D3D Agility SDK, ClangSharp, etc.)

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/win32metadata#1759]
While trying to reconstruct/rebase #1597 on latest `main`, it took a while to figure out how to get the metadata to generate correctly. Bumping `Microsoft.Direct3D.D3D12` to `1.711.3-preview` and running `./DoAll.ps1 -Clean` no longer seemed to do the trick (I recall it doing that before).

Some poking and prodding later it turns out I had to manually run `./scripts/RecompileIdlFilesForScraping.ps1` before `DoAll.ps1` to get it to utilize new IDL files from the updated D3D12 package. I don't recall needing to do this before, was is perhaps invoked as part of `DoAll` previously and should it be invoked again? It seems this script is also called from `UpdateSDK.ps1`.

Should any of this be documented in `CONTRIBUTING.md` (under a dedicated "updating dependencies..." section) so that it is clear to contributors?

Thanks!

**Comment by mikebattista** [comment]
Yes we should document this.

**Comment by mikebattista** [comment]
I updated CONTRIBUTING.md. Let me know if you have any feedback.
