### ISSUE TITLE
Windows.Win32.Com.IPersistFile uses ushort for file names

### ISSUE THREAD

**Issue by craigktreasure** [microsoft/win32metadata#176]
The Windows.Win32.winmd contains the following definition for Windows.Win32.Com.IPersistFile:

```csharp
// Windows.Win32.Com.IPersistFile
using System.Runtime.InteropServices;
using Windows.Win32.Com;
using Windows.Win32.SystemServices;

[Guid("0000010B-0000-0000-C000-000000000046")]
public interface IPersistFile : IPersist
{
	HRESULT IsDirty();

	unsafe HRESULT Load([In][Out] ushort* pszFileName, uint dwMode);

	unsafe HRESULT Save([Optional][In][Out] ushort* pszFileName, BOOL fRemember);

	unsafe HRESULT SaveCompleted([Optional][In][Out] ushort* pszFileName);

	unsafe HRESULT GetCurFile([Out] ushort** ppszFileName);
}
```

You'll notice that file name parameters are represented as `ushort*`. This causes the C# projection in Microsoft.Windows.CsWin32 to represent file names as `ushort` instead of `string`.

See the documentation for the IPersistFile interface (objidl.h) [here](https://docs.microsoft.com/windows/win32/api/objidl/nn-objidl-ipersistfile) where file names are represented as text objects (LPCOLESTR).

**Comment by sotteson1** [comment]
Fixed in the latest version.
