### ISSUE TITLE
Attribute for units

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1764]
In my C++ projection I want to expose values with units whereëver appropriate instead of just an raw integer.

[Here](https://learn.microsoft.com/en-us/windows/win32/api/bits3_0/nf-bits3_0-ibackgroundcopyjob4-getmaximumdownloadtime) the value could be exposed as std::chrono::second, rather than just ULONG.

One idea is to create separate structs for each unit per se but this seems extreme. And also considering that most languages do not have unit-specific types, it is a better idea to have an attribute indicating the unit, which can be ignored by those projections that don't have a wrapper type for the unit.

**Comment by riverar** [comment]
I'm not sure if win32metadata wants to get into the business of mapping Win32 types to C++ std or any other type system. I think a better approach for your C++ projection is to generate raw bindings, then provide another layer of abstractions via helper classes/wrappers where needed.

Will leave this open for other opinions/thoughts.

**Comment by mikebattista** [comment]
I agree with @riverar.
