### ISSUE TITLE
Missing `ID...` constants

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1766]
The following constants from [this page](https://learn.microsoft.com/en-us/cpp/windows/win32-predefined-symbols?view=msvc-170) are missing:

```
IDC_STATIC
IDD_ABOUTBOX
IDI_PROJECTNAME
IDI_SMALL
IDM_ABOUT
IDM_EXIT
IDS_APP_TITLE
```

**Comment by riverar** [comment]
`IDC_STATIC` (-1) is worth adding but the others don't appear in any SDK header. They appear to be isolated to resource headers generated by Visual Studio when using the desktop Windows application templates.
