### ISSUE TITLE
Why is VALENT(A/W)::ve_valuename non-const

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1778]
I know that [VALENT(A/W)](https://learn.microsoft.com/en-us/windows/win32/api/winreg/ns-winreg-valentw)::ve_valuename is non-const in the SDK headers, but it should really not be that way.

**Comment by riverar** [comment]
Interestingly, Windows NT 3.5 (when `RegQueryMultipleValues` was introduced) describes this as

```cpp
typedef struct value_ent {  /* val */  
    LPCTSTR  ve_valuename; 
    DWORD    ve_valuelen; 
    DWORD    ve_valueptr; 
    DWORD    ve_type; 
} RECT; 
```

Now to find when that changed...

**Comment by riverar** [comment]
The docs don't appear to have ever been truly in sync with the original header definition from NT 3.5:

```cpp
// winreg.h
// ...
typedef struct value_entA {
    LPSTR   ve_valuename;
    DWORD ve_valuelen;
    DWORD ve_valueptr;
    DWORD ve_type;
}VALENTA, FAR *PVALENTA;
typedef struct value_entW {
    LPWSTR  ve_valuename;
    DWORD ve_valuelen;
    DWORD ve_valueptr;
    DWORD ve_type;
}VALENTW, FAR *PVALENTW;
#ifdef UNICODE
typedef VALENTW VALENT;
typedef PVALENTW PVALENT;
#else
typedef VALENTA VALENT;
typedef PVALENTA PVALENT;
#endif // UNICODE
```

**Comment by riverar** [comment]
Tried variations incl. remote registry servers, ANSI/UTF-16, etc. and could not see any issues. Looks to simply be an oversight, but I'm not sure it's appropriate for metadata to assert const here as it could change at any time.

**Comment by JaiganeshKumaran** [comment]
> The name of the value to be retrieved. Be sure to set this member before calling [RegQueryMultipleValues](https://learn.microsoft.com/en-us/windows/desktop/api/winreg/nf-winreg-regquerymultiplevaluesa).
This only implies that it is used as an in-parameter. You could maybe analyse the Windows codebase to ensure that it is always used only like that. Also, I speculate that lots of code simply const_cast's string literals to fill the structure and call RegQueryMultipleValues. Changing the behaviour will cause a lot of crashes.

**Comment by mikebattista** [comment]
I don't see enough justification here to deviate from the headers in the metadata.
