### ISSUE TITLE
`RegisterPowerSettingNotification` flags param missing association with REGISTER_NOTIFICATION_FLAGS

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1779]
The `flags` parameter of [`RegisterPowerSettingNotification()`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Power/fn.RegisterPowerSettingNotification.html#) is a `u32`, althought the constants that can be used for it ([`DEVICE_NOTIFY_WINDOW_HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/constant.DEVICE_NOTIFY_WINDOW_HANDLE.html#) and [`DEVICE_NOTIFY_SERVICE_HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/constant.DEVICE_NOTIFY_SERVICE_HANDLE.html#)) have the type [`REGISTER_NOTIFICATION_FLAGS`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/struct.REGISTER_NOTIFICATION_FLAGS.html). `flags` should also be of type `REGISTER_NOTIFICATION_FLAGS`.

**Comment by riverar** [comment]
Closing for same reason stated in https://github.com/microsoft/win32metadata/issues/1781

**Comment by riverar** [comment]
Reopening: `flags` is missing association with `REGISTER_NOTIFICATION_FLAGS`
