### ISSUE TITLE
Inappropriate field type in `WINDOWPLACEMENT`

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1781]
`GetWindowPlacement()` and `SetWindowPlacement()` handle a [`WINDOWPLACEMENT`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/struct.WINDOWPLACEMENT.html#) struct. `showCmd` is a `u32`, but it should be a `SHOW_WINDOW_CMD`, because the values that it may contain like, e.g., `SW_SHOWMINIMIZED` are of that type.

**Comment by riverar** [comment]
We can't do that, sadly. See related issue #1502 for the details.

The short version is: `showCmd` is `u32` while `SW_SHOWMINIMIZED` et al. are integer literals in C/C++ (i.e., `#define SW_SHOWMINIMIZED 2`), which defaults to `int`. We have to preserve these types for application binary interface (ABI) correctness.

Projections (e.g., C#, Rust) can opt into reading the associated enum and generate helper overloads, wrappers, etc.

```csharp
public struct WINDOWPLACEMENT
{
...
	[AssociatedEnum("SHOW_WINDOW_CMD")]
	public uint showCmd;
...
```

Closing for now but feel free to keep the discussion going.
