### ISSUE TITLE
Missing IsWindowArranged, other functions without headers/libs

### ISSUE THREAD

**Issue by Enyium** [microsoft/win32metadata#1782]
[`IsWindowArranged()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindowarranged) is missing completely. The docs say that you need to use `LoadLibrary()` and `GetProcAddress()`, but it seems that the `windows` crate already uses an approach that allows to access such functions without lib loading. I amateurishly tried to imitate your [`link!`](https://github.com/microsoft/windows-rs/blob/0a65f6cf7277d8d44b860821070e9b1d2ba7636b/crates/libs/targets/src/lib.rs) approach, as also [used](https://github.com/microsoft/windows-rs/blob/0a65f6cf7277d8d44b860821070e9b1d2ba7636b/crates/libs/sys/src/Windows/Win32/UI/WindowsAndMessaging/mod.rs#L254) for `IsWindowVisible()`, and it worked:

```rust
#[link(name = "user32.dll", kind = "raw-dylib", modifiers = "+verbatim")]
extern "system" {
    fn IsWindowArranged(hwnd: isize) -> i32;
    // fn IsWindowVisible(hwnd: isize) -> i32;
}

fn main() {
    let hwnd = 0x120cc2;
    let is_arranged = unsafe { IsWindowArranged(hwnd) } != 0;
    println!("hwnd 0x{hwnd:x} arranged: {is_arranged}");
}
```

So, wouldn't support be possible?

---

[`ConsoleControl()`](https://learn.microsoft.com/en-us/windows/console/consolecontrol) is another function that's missing - including the types on that page - where it's said you must use `LoadLibrary()` and `GetProcAddress()`.

**Comment by riverar** [comment]
Hm.

> At this time, this function does not have an associated header file or library file. Your application can call [LoadLibrary](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) with the DLL name (User32.dll) to obtain a module handle. It can then call [GetProcAddress](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress) with the module handle and the name of this function to get the function address.

Very strange to see this missing from the SDKs. We can probably get that defined here in metadata manually, good catch.

Looks like there may be a few more too. We should double-check these:
https://learn.microsoft.com/en-us/search/?terms=%22this%20function%20does%20not%20have%20an%20associated%20header%20file%20or%20library%20file.%22&category=Documentation

**Comment by LeonarddeR** [comment]
I know about some functions in magnification.dll that are even undocumented. Would those also fit in these list?
- MagSetLensUseBitmapSmoothing
- MagSetFullscreenUseBitmapSmoothing
For reference, see [this thread](https://stackoverflow.com/questions/67988506/magnification-windows-api-how-to-add-smoothing-anti-aliasing)

**Comment by mikebattista** [comment]
We won't add undocumented APIs but we can add the others.

**Comment by Enyium** [comment]
@mikebattista: [`ConsoleControl()`](https://learn.microsoft.com/en-us/windows/console/consolecontrol) and the types listed on that page weren't added.
