### ISSUE TITLE
WinSock missing a few constants

### ISSUE THREAD

**Issue by youknowone** [microsoft/win32metadata#1785]
### Suggestion

- SO_EXCLUSIVEADDRUSE: https://learn.microsoft.com/en-us/windows/win32/winsock/so-exclusiveaddruse
- INADDR_*: https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-sendto

**Comment by riverar** [comment]
Related: https://github.com/microsoft/win32metadata/issues/1650

**Comment by mikebattista** [comment]
Could you take a look at the changes and make sure all the constants you need are there and have the appropriate values?
