### ISSUE TITLE
`PSAPI_VERSION` support

### ISSUE THREAD

**Issue by ldm0** [microsoft/win32metadata#1789]
### Suggestion

For win32 api like `GetModuleInformation`, `GetPerformanceInfo`, there is a `PSAPI_VERSION` flag to conveniently redirecting them to `Kernel32.dll`. But there is no such equivalent in `windows` crate, which makes it hard for downstream users to remove `Psapi.dll`'s usage without forking every dependency. Normally crates won't call kernel32 apis directly(e.g. `K32GetModuleInformation`) for old Windows Version support(or the authors are not aware of that). It would be awesome to have a feature flag or cfg for kernel32 api redirection just like what `PSAPI_VERSION` does.

**Comment by riverar** [comment]
Do we need to do anything here? `windows` and win32metadata contain both variants.

```csharp
[DllImport("KERNEL32.dll", ExactSpelling = true, PreserveSig = false)]
[Documentation("https://learn.microsoft.com/windows/win32/api/psapi/nf-psapi-getmoduleinformation")]
public unsafe static extern BOOL K32GetModuleInformation([In] HANDLE hProcess, [In] HMODULE hModule, [Out] MODULEINFO* lpmodinfo, [In] uint cb);


[DllImport("PSAPI.dll", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
[Documentation("https://learn.microsoft.com/windows/win32/api/psapi/nf-psapi-getmoduleinformation")]
public unsafe static extern BOOL GetModuleInformation([In] HANDLE hProcess, [In] HMODULE hModule, [Out] MODULEINFO* lpmodinfo, [In] uint cb);
```

**Comment by kennykerr** [comment]
I don't have a strong opinion. One option would be to update the metadata for `GetModuleInformation` to point to `kernel32` and use the `K32GetModuleInformation` entry point.

**Comment by ldm0** [comment]
> One option would be to update the metadata for GetModuleInformation to point to kernel32 and use the K32GetModuleInformation entry point.

Worth noting that this change would make apps rely on win32metadata unusable on Windows XP & WIndows Vista. Since `K32GetModuleInformation` couldn't be found in kernel32.dll on such platofrms.

Providing a features flag for such direction might be better in terms of compatibility.

**Comment by ldm0** [comment]
BTW, it's vague that whether `win32metadata` supports WIndows XP / Windows Vista / Windows Server 2003. I tried but couldn't find a list of supported OSes. :-(

**Comment by mikebattista** [comment]
I don't believe there are any metadata changes here. Any feature flags would be in the projections.

**Comment by riverar** [comment]
@ldm0 If you link an app and can't get rid of the PSAPI import, let us know here. On the Rust side, I think we covered all the bases there so unused APIs no longer end up in the import table.
