### ISSUE TITLE
List of missing enums

### ISSUE THREAD

**Issue by dotMorten** [microsoft/win32metadata#179]
After working for a while with C#/Win32, I discovered quite a few places where I had to provide constants instead of an enum, and had to search the doc for those values. I'd prefer these were enums like the doc suggest they really are.

* [x] `MonitorFromWindow` - https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow
Parameter `dwFlags` uint enum:
 - `MONITOR_DEFAULTTONULL` = 0x00000000
 - `MONITOR_DEFAULTTOPRIMARY` = 0x00000001
 - `MONITOR_DEFAULTTONEAREST` = 0x00000002

* [x] `SetWindowPos` - https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos
Parameter `uFlags` uint flag enum:
 - `SWP_FRAMECHANGED` = 0x0020
 - `SWP_HIDEWINDOW` = 0x0080
 - `SWP_NOACTIVATE` = 0x0010
 - `SWP_NOCOPYBITS` = 0x0100
 - `SWP_NOMOVE` = 0x0002
 - `SWP_NOOWNERZORDER` = 0x0200
 - `SWP_NOREDRAW` = 0x0008
 - `SWP_NOREPOSITION` = 0x0200
 - `SWP_NOSENDCHANGING` = 0x0400
 - `SWP_NOSIZE` = 0x0001
 - `SWP_NOZORDER` = 0x0004
 - `SWP_SHOWWINDOW` = 0x0040

* [x] `RegisterClass`: The `WNDCLASSW.lpfnWndProc` callback method has a message parameter for the generated delegate `internal unsafe delegate *unmanaged[Stdcall]<HWND, uint, WPARAM, LPARAM, LRESULT>`. See https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms633573(v=vs.85)
The LPARAM value should be an enum of all the windows messages. This list is rather large, so here's just a few:
 - Mouse input notifications: https://docs.microsoft.com/en-us/windows/win32/inputdev/mouse-input-notifications
  - `WM_MOUSEMOVE` = 0x0200
  - `WM_LBUTTONDOWN` = 0x0201
  - `WM_RBUTTONDOWN` = 0x0204
  - `WM_RBUTTONUP`  = 0x0205
  - etc...
 - Keyboard input notifications: https://docs.microsoft.com/en-us/windows/win32/inputdev/keyboard-input-notifications
 - More links: https://docs.microsoft.com/en-us/windows/win32/winmsg/about-messages-and-message-queues?redirectedfrom=MSDN#system-defined-messages

Note: We decided not to make an enum for `WM_*` as part of https://github.com/microsoft/win32metadata/issues/121#issuecomment-861019538.

* [x] `Shell_NotifyIcon` - https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona
Parameter `dwMessage` dword enum:
- `NIM_ADD` = 0x00000000
- `NIM_MODIFY` = 0x00000001
- `NIM_DELETE` = 0x00000002
- `NIM_SETFOCUS` = 0x00000003
- `NIM_SETVERSION` = 0x00000004

* [x] `Shell_NotifyIcon` - `NOTIFYICONDATAW` structure - https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa
Parameter `uflags` uint flag enum:
 - `NIF_MESSAGE` = 0x00000001
 - `NIF_ICON` = 0x00000002
 - `NIF_TIP` = 0x00000004
 - `NIF_STATE` = 0x00000008
 - `NIF_INFO` = 0x00000010
 - `NIF_GUID` = 0x00000020
 - `NIF_REALTIME` = 0x00000040
 - `NIF_SHOWTIP` = 0x00000080
 * [x] Need to follow up on the x86 versions of the NOTIFYICONDATA structs which don't appear to be taking changes from enums.json

* [ ] [DibColors](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-emf/a5e722e3-891a-4a67-be1a-ed5a48a7fda1) seems to be missing as well.

* [x] [`GlobalAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalalloc) flags are missing as well (I can't even seem to find non-enum constants for them)

**Comment by mikebattista** [comment]
Thanks for providing these. We do have some work to do to round out the enum support. We will ensure these are addressed.

**Comment by knopp** [comment]
[DibColors](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-emf/a5e722e3-891a-4a67-be1a-ed5a48a7fda1) seems to be missing as well.

**Comment by weltkante** [comment]
[`GlobalAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalalloc) flags are missing as well (I can't even seem to find non-enum constants for them)

**Comment by mikebattista** [comment]
Thanks. Rounding out constant and enum support is high priority for us. We are exploring ways to automate extracting constants and DWORD params into enums in the metadata which should get us much broader coverage to work with.

**Comment by sotteson1** [comment]
All the constants are getting scraped, but not all of them are in enums yet. Reopening to finish it off.

**Comment by mikebattista** [comment]
> [DibColors](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-emf/a5e722e3-891a-4a67-be1a-ed5a48a7fda1) seems to be missing as well.

What APIs use this?

**Comment by mikebattista** [comment]
* [ ] Need to follow up on the x86 versions of the NOTIFYICONDATA structs which don't appear to be taking changes from enums.json

**Comment by mikebattista** [comment]
We decided not to make an enum for `WM_*` as part of https://github.com/microsoft/win32metadata/issues/121#issuecomment-861019538.

I think what's left here is DibColors.

**Comment by mikebattista** [comment]
Closing this out. Please file a new issue for DibColors with more details on where that comes from and where it should be applied.
