### ISSUE TITLE
CONFIGFLAG to enum

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1794]
CONFIGFLAG. This is a flagged enum.

```
#define CONFIGFLAG_*
```

**Comment by mikebattista** [comment]
Where is this used? Should it be applied to any APIs?

**Comment by Nuklon** [comment]
It's used by SetupDiGetDeviceRegistryProperty / SetupDiSetDeviceRegistryProperty when you pass in SPDRP_CONFIGFLAGS:
https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetdeviceregistrypropertya#spdrp_configflags

**Comment by mikebattista** [comment]
Thanks.
