### ISSUE TITLE
IEnumIDList::Next doesn't work properly

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1798]
### Summary

IEnumIDList::Next is supposed to retrieve pointers to `ITEMIDLIST`,
the function doesn't allow that but rather makes it so you initializes them yourself.
The result is that nothing seems to happen, no data is written.

### Crate manifest

```TOML
[package]
name = "test"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[target.'cfg(windows)'.dependencies]
windows = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_Shell_Common",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }
```

### Crate code

```Rust
fn main() -> windows::core::Result<()> {
    unsafe {
        CoInitializeEx(None, COINIT_MULTITHREADED | COINIT_DISABLE_OLE1DDE).unwrap();
        let shell: IShellWindows =
            CoCreateInstance(&ShellWindows, None, CLSCTX_LOCAL_SERVER).unwrap();
        let varloc = VARIANT::default();
        let varlocroot = VARIANT::default();
        let mut hwnd = 0;
        let mut dispatch = None;
        shell.FindWindowSW(
            &varloc,
            &varlocroot,
            SWC_DESKTOP,
            &mut hwnd,
            SWFO_NEEDDISPATCH,
            &mut dispatch,
        )?;
        let sprovider: IServiceProvider = dispatch.take().unwrap().cast()?;
        let browser: IShellBrowser = sprovider.QueryService(&IShellBrowser::IID)?;
        let active_shell = browser.QueryActiveShellView()?;
        let folder_view: IFolderView = active_shell.cast()?;
        let folder: IShellFolder = folder_view.GetFolder()?;

        let items: IEnumIDList = folder_view.Items(SVGIO_ALLVIEW)?;

        loop {
            let mut idlist = ITEMIDLIST::default();

            let mut f = 0;
// this should actually receive pointers that needs to be freed with CoTaskMemFree,
// so setup just seems wrong, i would expect it to be &mut[&mut Option<ITEMIDLIST>] like other similar enums.
            items.Next(&mut [&mut idlist], Some(&mut f)).ok()?;

            if f == 0 {
                break;
            }
// if something is grabbed this shouldn't be 0
            assert!({ idlist.mkid.cb > 0 });
        }
    }
}
```

**Comment by mikebattista** [comment]
Could you share what the metadata should be? It's already marked `[Out]` only.

Not sure if it's a metadata bug or a questionable interpretation of `NativeArrayInfo`.

**Comment by kennykerr** [comment]
Rereading the docs... https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ienumidlist-next

> The address of a pointer to an array of [ITEMIDLIST](https://learn.microsoft.com/en-us/windows/desktop/api/shtypes/ns-shtypes-itemidlist) pointers that receive the item identifiers. The implementation must allocate these item identifiers using [CoTaskMemAlloc](https://learn.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-cotaskmemalloc). The calling application is responsible for freeing the item identifiers using [CoTaskMemFree](https://learn.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-cotaskmemfree).

It is probably saying that the individual elements are allocated using `CoTaskMemAlloc` rather than the array itself, in which case the metadata and the Rust interpretation is correct.

**Comment by mikebattista** [comment]
Thanks. Is there any work here then? Original issue was an API not behaving as expected. Is it a usage error or something else wrong with the metadata?

**Comment by kennykerr** [comment]
I believe its correct. Here's an example (in C++) of how to use it: https://devblogs.microsoft.com/oldnewthing/20130318-00/?p=4933

Just port that to Rust and you should be good to go.
