### ISSUE TITLE
HtmlHelp API is marked with the wrong dll

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/win32metadata#1799]
`HtmlHelpW` and `HtmlHelpA` are shown as coming from `htmlhelp.dll`. They actually are in `hhctrl.ocx` as documented  https://learn.microsoft.com/windows/win32/api/htmlhelp/nf-htmlhelp-htmlhelpw.

**Comment by riverar** [comment]
Duplicate of #1749, fixed via #1752, should be in the next release!

**Comment by JeremyKuhne** [comment]
Sorry, didn't see the other when I searched. :)

**Comment by riverar** [comment]
@jeremykuhne No problem whatsoever, when it doubt feel free to file.
