### ISSUE TITLE
`CLSID_DxcUtils` is not included in metadata

### ISSUE THREAD

**Issue by chloekek** [microsoft/win32metadata#1812]
`CLSID_DxcUtils` is defined in `dxcapi.h` as follows:

```c
CLSID_SCOPE const GUID CLSID_DxcUtils = CLSID_DxcLibrary;
```

It is not included in the metadata. It could be defined the same way as `CLSID_DxcLibrary`.

**Comment by elachlan** [comment]
https://github.com/microsoft/win32metadata/blob/1ba2527a59da3f1c1b4809bb053d03f300af3c09/generation/WinSDK/RecompiledIdlHeaders/um/dxcapi.h#L674-L681
