### ISSUE TITLE
CLSID_GlobalOptions is Missing

### ISSUE THREAD

**Issue by shmuelie** [microsoft/win32metadata#1813]
## Actual behavior

Adding `CLSID_GlobalOptions` to `NativeMethods.txt` results in an error and no .NET member generated for it.

## Expected behavior

Adding `CLSID_GlobalOptions` to `NativeMethods.txt` to result in a `CLSID_GlobalOptions` member and no errors.

## Repro steps

1. `NativeMethods.txt` content:
```
CLSID_GlobalOptions
```

### Context

- CsWin32 version: `0.3.49-beta`
- Target Framework: `netstandard2.0;net8.0-windows10.0.22000.0`
- LangVersion: `12`

**Comment by mikebattista** [comment]
Where is this defined?

**Comment by riverar** [comment]
`cguid.h`

```cpp
extern const CLSID CLSID_GlobalOptions;
```

... which is set by `uuid.lib!cguid_i.obj`

```
0000034B-0000-0000-C000-000000000046
```

**Comment by mikebattista** [comment]
Thanks.
