### ISSUE TITLE
Metadata falsely represents native classes as typedef structs

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1821]
GDI+ defines several classes and defines functions that pass around *pointers* to those classes. For example `GpRegion*` and `GpRegion**` are parameter types that are often found in the headers.

The problem is that the win32metadata declares `GpRegion` as a typedef struct with just one pointer-sized field. This suggests that there is no harm in the projection or the consuming code dereferencing `GpRegion*` to get at the struct and/or copy it around. But this would be destructive behavior because in fact `GpRegion*` points to much more data than just a single pointer-sized field. It's essentially like a COM object, where it's always passed around by pointer and should never be dereferenced except to call to a function.

The metadata declares HWND and GpRegion exactly the same way, so CsWin32 cannot treat them differently. We want to treat them differently because we offer friendly overloads that remove pointers in favor of references, but that's invalid for `GpRegion`, although it's fine for HWND.

Can the metadata do _something_ to help CsWin32 and users avoid dereferencing a `GpRegion*`? Perhaps a custom attribute on the struct in addition to or instead of a `NativeTypedef` attribute? Or maybe drop the `IntPtr` field, making it an empty struct. That could be the hint that its content is unknown and thus a pointer should never be dereferenced.

This blocks https://github.com/microsoft/CsWin32/issues/1115

**Comment by mikebattista** [comment]
@riverar could you take a look at this? You did the work here for the GDI+ APIs.

**Comment by riverar** [comment]
```cpp
class GpRegion {};
```

```cpp
// ...
GpStatus WINGDIPAPI GdipCreateRegion(GpRegion **region);
GpStatus WINGDIPAPI GdipSetInfinite(GpRegion *region);
// ...
```

I'm leaning towards both:
* removing the `NativeTypeDef` attribute 
* emptying the struct

**Comment by AArnott** [comment]
`CREDENTIALW` is an interesting related case. It isn't _empty" in the metadata, nor should it be. But [`CredReadW`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw) returns a `PCREDENTIALW` that is important to not copy around. The original pointer is native allocated memory that must be freed via the original pointer. Further, the struct may point to addresses outside itself but within the same memory allocation. So it's important that projections _not_ simply copy the struct and/or release the memory and expect the copy to be self-contained.
I think these fall in with the native classes mentioned in the description, in that the metadata should be able to indicate that this type should never be dereferenced for purposes of copying around, as the original pointer is important.

**Comment by riverar** [comment]
I adjusted the GDI+ types for now per above. I think we should still capture your idea for follow up--perhaps some sort of non-copy-able/moveable attribute.
