### ISSUE TITLE
`--with-type` to remap `enum` type complains about duplicate types

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/win32metadata#1822]
I'm working on generating custom metadata for DirectStorage for https://github.com/Tsukisoft/direct-storage-rs because the included `.winmd` in its NuGet package has an unclarified license and is otherwise lacking some "niceties" (https://github.com/microsoft/DirectStorage/issues/38). However, in an attempt to reproduce its contents (niceties that _I am now still missing_), I am failing to change the type of `enum DSTORAGE_DEBUG` back to `uint`. Here's the example:

https://github.com/MarijnS95/direct-storage-rs/commit/ec85d7aaaff6cf6061de5aa64eae0b48c8156bc3#diff-2272e2c6b51d71e5826e9f30e59bba7c4c2285b4ba8c3be5e5f6e7a1bdb9f9d3

With `<ScraperRsp Include="scraper.settings.rsp"/>` in an `<ItemGroup>` and that file containing:

```rsp
--with-type
DSTORAGE_DEBUG=uint
```

The generator complains with:

```
Error in args for 'direct-storage-rs\.metadata\dstorage.cpp'
Error: A key with the given name already exists: DSTORAGE_DEBUG. Existing: uint
```

This seems to match what is documented in https://github.com/microsoft/win32metadata/blob/main/docs/generationOptions.md#with-type and used in https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/scraper.settings.rsp, anything I'm doing wrong?

**Comment by MarijnS95** [comment]
As a side-quest, which I don't think is worth a new issue on its own: the metadata contains a bunch of `E_DSTORAGE_*` constants that are `HRESULT` error codes:

1. Is scraping of `#define` constants supported, or should I hardcode them in a `*.Manual.Cs` file from https://learn.microsoft.com/en-us/windows/win32/dstorage/dstorage-constants?
2. How to add them to `HRESULT` (or since they're loose constants, this probably functions natively?)

**Comment by mikebattista** [comment]
Generally we trust the type that ClangSharp scrapes for an enum. Why are you changing it?

**Comment by riverar** [comment]
Correct, these are `int` in the headers and should not be `uint`.

```cpp
/// <summary>
/// Flags controlling DirectStorage debug layer.
/// </summary>
enum DSTORAGE_DEBUG {
    /// <summary>
    /// DirectStorage debug layer is disabled.
    /// </summary>
    DSTORAGE_DEBUG_NONE                 = 0x00,

    /// <summary>
    /// Print error information to a debugger.
    /// </summary>
    DSTORAGE_DEBUG_SHOW_ERRORS          = 0x01,

    /// <summary>
    /// Trigger a debug break each time an error is detected.
    /// </summary>
    DSTORAGE_DEBUG_BREAK_ON_ERROR       = 0x02,

    /// <summary>
    /// Include object names in ETW events.
    /// </summary>
    DSTORAGE_DEBUG_RECORD_OBJECT_NAMES  = 0x04
};
DEFINE_ENUM_FLAG_OPERATORS(DSTORAGE_DEBUG)
```

**Comment by MarijnS95** [comment]
@riverar how do you deduce from this definition that it should remain `int`?

If that is the correct choice, the `SetDebugFlags()` function which takes a bitmasked value of these flag bits is incorrectly taking `UINT32` and should be corrected instead: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/system/dstorage/interfaces/idstoragefactoryx/methods/idstoragefactoryx_setdebugflags

**Comment by mikebattista** [comment]
If there's a type mismatch between the enum definition and its usage, you should apply the `AssociatedEnum` attribute for the usage instead of remapping directly.

**Comment by MarijnS95** [comment]
I've done that and windows-rs generates correct code to perform the right conversion. It seems strange however that there are these (constant) type mismatches, which make it unnecessarily complicated to use these APIs correctly?

**Comment by MarijnS95** [comment]
Closing as "no longer needed" even though the type mismatches are still odd.

**Comment by mikebattista** [comment]
> I've done that and windows-rs generates correct code to perform the right conversion. It seems strange however that there are these (constant) type mismatches, which make it unnecessarily complicated to use these APIs correctly?

The metadata stays true to the headers and original ABI. Projections make things easier to use based on additional metadata like this.

**Comment by MarijnS95** [comment]
The question is whether the original headers are (accidentally) mixing up the types?

**Comment by mikebattista** [comment]
I don't believe so. As you said this is pretty common. The C++ compiler is just better at handling the differences with implicit conversions whereas we need to be explicit in the metadata.

**Comment by riverar** [comment]
> @riverar how do you deduce from this definition that it should remain `int`?
> 
> If that is the correct choice, the `SetDebugFlags()` function which takes a bitmasked value of these flag bits is incorrectly taking `UINT32` and should be corrected instead: https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/system/dstorage/interfaces/idstoragefactoryx/methods/idstoragefactoryx_setdebugflags

In Microsoft Visual C++ (MSVC) (until recently), the default underlying type of an unscoped enumeration was `int` https://learn.microsoft.com/cpp/build/reference/zc-enumtypes. There are a lot of Win32 and COM API warts like this due to _helpful_ implicit conversions.

**Comment by MarijnS95** [comment]
Right, I think `clang`/`gcc` used for Android (and/or the `libclang`-based `bindgen` tool) uses `uint`.
