### ISSUE TITLE
TreeView_SortChildren does not sort recursively

### ISSUE THREAD

**Issue by gonutz** [microsoft/win32metadata#1823]
Calling `TreeView_SortChildren` with the `recurse` argument set to `TRUE` as [described here](https://learn.microsoft.com/windows/win32/api/commctrl/nf-commctrl-treeview_sortchildren) does not sort the tree view's node children.

This bug was [desribed here in 2009](https://forum.powerbasic.com/forum/user-to-user-discussions/powerbasic-for-windows/41315-tvm_sortchildren-not-working-recursively) without an answer.

At the end of this post is a minimal example that creates a tree view like this:

```
Root
  |__Y
  |__X
      |__B
      |__A
```

and on the `Sort` button click, sorts the root node recursively. I would expect the tree to be this:

```
Root
  |__X
      |__A
      |__B
  |__Y
```

but it is really this:

```
Root
  |__X
      |__B
      |__A
  |__Y
```

Nodes `A` and `B` are not sorted.

Here is the minimal example:

```
#include <windows.h>
#include <CommCtrl.h>

HWND tree;
HTREEITEM root;

LRESULT WindowProc(HWND window, UINT message, WPARAM w, LPARAM l) {
	if (message == WM_DESTROY)
		PostQuitMessage(0);
	if (message == WM_COMMAND && l != 0) {
		TreeView_SortChildren(tree, root, TRUE);
	}
	return DefWindowProc(window, message, w, l);
}

int main() {
	WNDCLASS cls = {};
	cls.lpszClassName = L"window_class";
	cls.lpfnWndProc = WindowProc;
	RegisterClass(&cls);
	auto window = CreateWindow(L"window_class", L"", WS_VISIBLE | WS_OVERLAPPEDWINDOW, 0, 0, 400, 400, 0, 0, 0, 0);
	tree = CreateWindow(WC_TREEVIEW, L"", WS_VISIBLE | WS_CHILD | WS_BORDER | TVS_HASLINES | TVS_HASBUTTONS | TVS_LINESATROOT, 10, 10, 200, 200, window, HMENU(1), 0, 0);
	auto button = CreateWindow(WC_BUTTON, L"Sort", WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON, 10, 250, 80, 25, window, HMENU(2), 0, 0);
	
	TVINSERTSTRUCT node = {};
	node.hInsertAfter = TVI_ROOT;
	node.item.mask = TVIF_TEXT;
	node.item.pszText = LPWSTR(L"Root");
	root = TreeView_InsertItem(tree, &node);

	node = {};
	node.hParent = root;
	node.hInsertAfter = TVI_FIRST;
	node.item.mask = TVIF_TEXT;
	node.item.pszText = LPWSTR(L"Y");
	auto y = TreeView_InsertItem(tree, &node);

	node = {};
	node.hParent = root;
	node.hInsertAfter = y;
	node.item.mask = TVIF_TEXT;
	node.item.pszText = LPWSTR(L"X");
	auto x = TreeView_InsertItem(tree, &node);

	node = {};
	node.hParent = x;
	node.hInsertAfter = TVI_FIRST;
	node.item.mask = TVIF_TEXT;
	node.item.pszText = LPWSTR(L"B");
	auto b = TreeView_InsertItem(tree, &node);

	node = {};
	node.hParent = x;
	node.hInsertAfter = b;
	node.item.mask = TVIF_TEXT;
	node.item.pszText = LPWSTR(L"A");
	TreeView_InsertItem(tree, &node);

	MSG msg;
	while (GetMessage(&msg, 0, 0, 0)) {
		TranslateMessage(&msg);
		DispatchMessage(&msg);
	}
	return 0;
}
```

**Comment by mikebattista** [comment]
This sounds like an old API problem and not a metadata problem. Is that correct?

**Comment by riverar** [comment]
Not the right place for general OS bugs but I was curious...

It appears to be a bug in Common Controls v5 and v6, where the default TreeView sorting callback (`comctl32!TV_SortCB`) receives the recurse flag but, um, doesn't do anything with it.

I filed an issue in Feedback Hub https://aka.ms/AAom6io. Tagged @jonwis for visibility.

It's not likely this will get fixed, so I recommend you use `TreeView_SortChildrenCB` and implement the callback/sorting yourself.

**Comment by jonwis** [comment]
Yeah... completely not implemented. Unlikely to be fixed.

**Comment by gonutz** [comment]
Thank you guys for the investigation. I knew this was not the right place to ask, but I did not know what was. So I was secretly hoping someone would forward it to the right place. But I even have a real and definitive answer now, so thank you very much for your efforts! I really appreciate it :-)

**Comment by riverar** [comment]
Closing the loop here--the documentation change went through and should be live here shortly: https://learn.microsoft.com/windows/win32/api/commctrl/nf-commctrl-treeview_sortchildren
