### ISSUE TITLE
SP_DEVINSTALL_PARAMS_W issues

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1826]
See https://github.com/microsoft/CsWin32/issues/992#issuecomment-1892627315 for reference.
I'm not entirely sure if it's related to the metadata or CsWin32, but SP_DEVINSTALL_PARAMS_W uses a PSP_FILE_CALLBACK_W delegate, but this needs to be a pointer, otherwise SetupDiBuildDriverInfoList will fail when you use the DriverPath in combination with DI_ENUMSINGLEINF.

**Comment by riverar** [comment]
Delegates in metadata are effectively function pointers, so doesn't look like anything is wrong here. Let us know if we're missing something. Please also double-check metadata before filing issues.

```csharp
[StructLayout(LayoutKind.Sequential, Pack = 1)]
[Unicode]
[Documentation("https://learn.microsoft.com/windows/win32/api/setupapi/ns-setupapi-sp_devinstall_params_w")]
[StructSizeField("cbSize")]
[SupportedArchitecture(Windows.Win32.Foundation.Metadata.Architecture.X86)]
public struct SP_DEVINSTALL_PARAMS_W
{
	public uint cbSize;

	public uint Flags;

	public uint FlagsEx;

	public HWND hwndParent;

	public PSP_FILE_CALLBACK_W InstallMsgHandler;

	public unsafe void* InstallMsgHandlerContext;

	public unsafe void* FileQueue;

	public UIntPtr ClassInstallReserved;

	public uint Reserved;

	public char[] DriverPath;
}

[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
[Unicode]
public unsafe delegate uint PSP_FILE_CALLBACK_W([In] void* Context, [In] uint Notification, [In] UIntPtr Param1, [In] UIntPtr Param2);
```

**Comment by Nuklon** [comment]
The problem is that, at least with CsWin32, this doesn't work correctly. If you change the PSP_FILE_CALLBACK_W to a void*, it's working correctly.
