### ISSUE TITLE
make IMoniker::BindToStorage Option<T> where T: ComInterface?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#1829]
### Suggestion

Is it possible to make make `IMoniker::BindToStorage` cast the result to the appropriate type?

Currently as far as I can tell you have to use it like this:

```rust
 let base_filter = {
            let mut base_filter: MaybeUninit<IBaseFilter> = MaybeUninit::zeroed();
            unsafe {
                moniker.BindToObject(
                    None,
                    None,
                    &IBaseFilter::IID,
                    base_filter.as_mut_ptr() as *mut *mut _,
                )
            }?;
            unsafe { base_filter.assume_init() }
        };
```

The documentation specified the result (the 4th argument) to be an interface pointer.
Which Perhaps makes it possible to either have it an `&mut Option<T>` or make it like `CoCreateInstance`,
where the argument it skipped and used as a return value instead.

**Comment by kennykerr** [comment]
At least on this interface, both `BindToStorage` and `BindToObject` are missing the attribute.
