### ISSUE TITLE
Requests for New Language Projections

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#183]
In order to scale out support for more languages, we need the respective communities to build projections on top of the metadata that we produce.

While it is ok to file an issue here to start the discussion about supporting a new language, generating interest and demand in the respective communities directly may help with getting those projects started.

We will of course partner with any such projects to provide guidance and to ensure the metadata we produce supports the effort and delivers the best possible developer experience.

**Comment by timsneath** [comment]
Adding a reference here to two packages for Dart:

- https://github.com/timsneath/winmd provides a Dart reader for Windows metadata (`.winmd` files)
- https://github.com/timsneath/win32 provides a Dart projection of the Windows API, now using the above winmd project to generate a sizeable proportion of the Win32 API surface area (both C-style and COM APIs).

**Comment by mikebattista** [comment]
Thanks @timsneath. I added your Dart projection to the list of projections in our repo.

**Comment by MHumm** [comment]
There seems to be something available now. Maybe this is a candidate for the list on the start page?
[https://getitnow.embarcadero.com/windows-api-from-winmd/](https://getitnow.embarcadero.com/windows-api-from-winmd/)
