### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1831]
These function was dropped from the latest release. Was that intentional?

* StgConvertPropertyToVariant
* RegisterDeviceDualEnrollMmpcUsingAADDeviceCredentials

**Comment by riverar** [comment]
StgConvertPropertyToVariant: We missed fixing https://github.com/microsoft/win32metadata/issues/1566 so you'll need to keep this workaround in place https://github.com/microsoft/windows-rs/pull/2664#issuecomment-1742131763

RegisterDeviceDualEnrollMmpcUsingAADDeviceCredentials: TBD

**Comment by riverar** [comment]
`RegisterDeviceDualEnrollMmpcUsingAADDeviceCredentials` vanished from `MDMRegistration.h` when upgrading the SDK from `10.0.22621.755` to `10.0.22621.2428`.

@mikebattista Heads up

**Comment by mikebattista** [comment]
@jonwis this API appears to have been removed from the latest SDK. Was this a known change?

**Comment by jonwis** [comment]
I see the removal in the source, I'll have to figure out why. For my reference, it was PR#8889793

**Comment by jonwis** [comment]
To close out - this removal is by design. Thanks for checking!
