### ISSUE TITLE
UIAnimationManager in wrong namespace

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#184]
The `UIAnimationManager` struct representing the CLSID constant for the UI Animation Manager is in the wrong namespace. It should be in the `UIAnimation` namespace along with the rest of the UI Animation API but is instead in the `UPnp` namespace.

**Comment by kennykerr** [comment]
Also a number of other UI structs in the wrong namespace:

![image](https://user-images.githubusercontent.com/9845234/105763316-8031ef80-5f0a-11eb-8600-7e0c89065914.png)

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.4.
