### ISSUE TITLE
`HtmlHelpA` and `HtmlHelpW` are missing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1848]
Trying to update to the latest version and noticed these functions have disappeared. 

Related to #1345

**Comment by mikebattista** [comment]
Are you sure? I see them in the latest published as well as the latest dev build.

**Comment by kennykerr** [comment]
Oh, I see it moved from `htmlhelp.dll` to `hhctrl.ocx` - was that intentional?

**Comment by mikebattista** [comment]
Yes that looks intentional per https://github.com/microsoft/win32metadata/issues/1799.
