### ISSUE TITLE
RPC_S_ACCESS_DENIED has wrong value

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1857]
In MSVC (default configuration) the following holds true:

```C++
#include <rpc.h>

int main()
{
    static_assert(RPC_S_ACCESS_DENIED == ERROR_ACCESS_DENIED);
}
```

Both `ERROR_ACCESS_DENIED` and `RPC_S_ACCESS_DENIED` are 5 because `RPC_S_ACCESS_DENIED` is defined as `ERROR_ACCESS_DENIED` in `rpcnterr.h` (line 41).

But the Win32 metadata seems to choose the definition from `rpcnterr.h` (line 540) where `RPC_S_ACCESS_DENIED` is defined as `STATUS_ACCESS_DENIED`. The difference is whether `_KRPCENV_` is defined.

**Comment by kennykerr** [comment]
The RPC constants in Windows.Win32.Foundation are also incorrectly typed as `int` while the RPC constants in Windows.Win32.System.Rpc use the `RPC_STATUS` type. Can we get them all consolidated under the `Windows.Win32.System.Rpc.RPC_STATUS` enum?

**Comment by mikebattista** [comment]
The enum is typed as int. Should that be uint?

**Comment by kennykerr** [comment]
The sign bit does not appear to be used for `RPC_STATUS` so it behaves more like `WIN32_ERROR` but it is defined as `long` which is `int` so I don't have a problem with leaving it as is.
