### ISSUE TITLE
STREAM_SEEK not being used with IStream methods

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#186]
The enum values are meant to be used with `IStream`'s `Read` and Write` methods but the relevant parameter expects an unsigned integer.

**Comment by kennykerr** [comment]
And again it should be an unsigned enum.

**Comment by sotteson1** [comment]
Looking at the header and docs, it looks like the enum is used  with Seek and not Read/Write.

**Comment by sotteson1** [comment]
Fixed with 10.0.19041.5-preview.5.
