### ISSUE TITLE
`MOUSEINPUT` is of the wrong type

### ISSUE THREAD

**Issue by pentamassiv** [microsoft/win32metadata#1865]
### Summary

It is the same issue as https://github.com/microsoft/windows-rs/issues/2708. Even after updating the metadata in https://github.com/microsoft/windows-rs/commit/b62b802bae534fdaed3fa25b6838dc3001b6d084, the issue still persists.

In version 0.51, `windows::Win32::UI::Input::KeyboardAndMouse::MOUSEINPUT.mouseData` was of type `i32`. Starting in version 0.52, it is of type `u32`. According to the documentation, the type is DWORD. However it also states:

> If dwFlags contains MOUSEEVENTF_WHEEL, then mouseData specifies the amount of wheel movement. A positive value indicates that the wheel was rotated forward, away from the user; a negative value indicates that the wheel was rotated backward, toward the user. One wheel click is defined as WHEEL_DELTA, which is 120.

 ([source](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput)).

**Comment by mikebattista** [comment]
As long as we're ok deviating from the headers, we can change it back to int.

**Comment by kennykerr** [comment]
The type is clearly `uint` - I don't see a compelling reason to change it - the caller is clearly expected to cast a negative value.

**Comment by riverar** [comment]
I originally marked it as `int` long before we had ABI and codegen compatibility concerns/discussions (https://github.com/microsoft/win32metadata/pull/889). I now agree this should remain `uint` and the user should cast.

Metadata currently has this listed as `uint`, but then we have this in the emitter rsp... 🤔 https://github.com/riverar/win32metadata/blob/master/generation/WinSDK/emitter.settings.rsp#L464. Looks like something we need to clean up.

**Comment by mikebattista** [comment]
Everything looks correct to me in the latest builds.

**Comment by pentamassiv** [comment]
Okay, thank you for the quick response. I will cast the values.
