### ISSUE TITLE
1.613.0 AgilitySDK metadata update

### ISSUE THREAD

**Issue by amarpMSFT** [microsoft/win32metadata#1869]
Update metadata for latest AgilitySDK release 1.613.0:

https://devblogs.microsoft.com/directx/directx12agility/

**Comment by MarijnS95** [comment]
It took me some effort to reproduce the branch that I forgot to push, but a PR for this is now up at https://github.com/microsoft/win32metadata/pull/1870.

For Rust, branches with these bindings are up at https://github.com/Traverse-Research/windows-rs/tree/d3d12-agility-1.613.0 and https://github.com/Traverse-Research/windows-rs/tree/d3d12-agility-1.613.0-core-0.54.

Note that the D3D12/DXGI bindings need some annotation improvements, but I'm still waiting for comments/reviews/help from @riverar and @mikebattista in https://github.com/microsoft/win32metadata/pull/1757.

**Comment by riverar** [comment]
Will jump on that now, apologies for the delay. Have been overloaded as of late. 😵‍💫

**Comment by MarijnS95** [comment]
@riverar thanks for the review. Likewise it will take me some time and effort to boot into Windows some day to process the remaining review comments. I'll let you know when I need assistance again!

**Comment by riverar** [comment]
Sure thing, holler if you need anything. Can even stand up a temporary VM if needed.
