### ISSUE TITLE
Missing GetActivationFactory

### ISSUE THREAD

**Issue by FallingSnow** [microsoft/win32metadata#187]
[GetActivationFactory](https://docs.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-getactivationfactory) is not represented in windows-rs, however is RoGetActivationFactory. Why is GetActivationFactory not in windows-rs? Does this have to do something with the Combase.dll?

Also, why is [RoGetActivationFactory's](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/winrt/fn.RoGetActivationFactory.html) first parameter an `isize` when in the [Microsoft documentation](https://docs.microsoft.com/en-us/windows/win32/api/roapi/nf-roapi-rogetactivationfactory) it's an `HSTRING`?

**Comment by kennykerr** [comment]
I've transferred this issue to the metadata repo as the questions are not specific to Rust. 

The `GetActivationFactory` is a helper function specific to C++ and thus not suitable for metadata. The underlying `RoGetActivationFactory` function, as you noted, is present and all you need. Languages are free to wrap these functions to provide such conveniences in a language-specific way.

Steve has been adding special typedefs in metadata to replace many of the uses of `IntPtr`. In this case, we probably need an `HSTRING` typedef-like struct (`NativeTypedef`), much like what we have for `BSTR` and `HANDLE`.

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.4.

**Comment by kennykerr** [comment]
Thanks Steve, looks great!
