### ISSUE TITLE
Possibly add SEH wrapping through linked libs

### ISSUE THREAD

**Issue by RivenSkaye** [microsoft/win32metadata#1873]
### Suggestion

With the relatively new [`windows-targets`](https://github.com/microsoft/windows-rs/tree/master/crates/targets) crate already linking in target-specific libs, and all of the C definitions in the baseline dir, it should be possible to provide some wrapping mechanism similar to what [the stub in microSEH](https://github.com/sonodima/microseh/blob/master/src/stub.c) does with wrapping C calls in the corresponding `__try` blocks to translate SEH to Rust Errors. LLVM [already supports SEH on Windows](https://llvm.org/docs/ExceptionHandling.html#exception-handling-using-the-windows-runtime) and GCC supports it for AMD64 (there's some talk of x86 SEH online, but haven't dug too deep and if it's implemented it might not have a release yet). This would make a lot of things on Windows much more ergonomic (including a lot of `unsafe` functions in the `windows` and `windows-sys` crates) and less prone to crashing from an error generated outside of the Rust boundary.

Naturally different targets would come with different mechanisms for handling the exceptions, so the targets crate seems like a perfect place to add it in; all it'd need to do is send back a continue status to prevent further stack unwinding or crashing, and then it can forward the internal error information in a Rust struct (possibly `#[rep(C)]` so as to not need modifications to the underlying data)

**Comment by riverar** [comment]
Do you have some example APIs in mind?

**Comment by tim-weis** [comment]
[SEH](https://learn.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp) is a system service that requires compiler (and language/language runtime) support. This should be filed against [rustc](https://github.com/rust-lang/rust/issues?q=is%3Aissue+seh) for resolution.

@riverar This goes beyond (or underneath) API calls. [`MapViewOfFile()`](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile), for example, returns the equivalent of a region of memory. Dereferencing a pointer anywhere inside the reported valid range of the mapping can raise an SEH exception (e.g. when the file object backing the mapping becomes inaccessible).

The core issue here cannot be solved by annotating APIs alone, and a [cursory search](https://github.com/rust-lang/rust/issues?q=is%3Aissue+seh) didn't uncover any hope for a resolution over the [current workaround](https://github.com/microsoft/windows-rs/issues/2692#issuecomment-1783035244).

**Comment by RivenSkaye** [comment]
Not quite sure which end of the issue you'd want example API's for; the existing APIs where `__try`/`__except` are currently used, examples for the Rust end of things, or examples for the metadata definitions?

My initial request was aimed mostly at situations where the function call itself can reasonably cause these to be thrown, e.g. accessing networked locations can cause `EXCEPTION_IN_PAGE_ERROR` and in some situations, or for getting a generic function that allows users to register their own filter and handler functions; that said some of the SDK functions can also cause some of the recoverable ones to be thrown. The simple wrapper could look like
```cpp
// Code may not be perfect, I'm not experienced in passing around functions in C++
void TryUserFn(DWORD[] handles, *void callable, *void handler, *void outvar) {
    __try {
        *outvar = callable();
    }
    __except(arr_contains(handles, GetExceptionCode())) {
        handler();
        *outvar = NULL;
    }
    return 0;
}
```
as a bare method of allowing people to attempt recovery or warning users

**Comment by riverar** [comment]
Not aware of any APIs using SEH so closing this for now. Feel free to keep the discussion going and let one of us know if we need to re-open this. Thanks!
