### ISSUE TITLE
Add `StringCchCopyW` and other string safe functions from "strsafe.h"

### ISSUE THREAD

**Issue by wuweiran** [microsoft/win32metadata#1887]
### Suggestion

`windows::Win32::Globalization::lstrcpynW` is deprecated according to the [doc](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lstrcpynw). Need the replacement functions.

**Comment by riverar** [comment]
Does Windows ship with this inbox? Or is this a utility function that ships with the safe string lib? Not immediately finding it in the CRT/UCRT set of APIs...

**Comment by kennykerr** [comment]
Note that strsafe is mostly an inline header library so not suitable for Win32 metadata.

**Comment by riverar** [comment]
Hey @wuweiran, as Kenny pointed out, this function is a helper defined in `strsafe.h` and not part of the Win32 API surface, therefore not appropriate for Win32 metadata. Thanks for filing an issue though!
