### ISSUE TITLE
`RAIIFree` implies `InvalidHandleValue`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1891]
Taking another stab at supporting `RAIIFree` in Rust, but the following structs have the `RAIIFree` attribute but lack at least one `InvalidHandleValue` attribute. Is that intentional? Are we meant to assume that zero is thus the invalid value?

* HIORING
* PTP_CLEANUP_GROUP
* PTP_POOL
* SOCKET

**Comment by kennykerr** [comment]
Conversely, there are many structs that have at least one `InvalidHandleValue` attribute but lack a corresponding `RAIIFree` attribute. Is that intentional? 

- HCONN
- HCOMDB
- ADS_SEARCH_HANDLE
- HIFTIMESTAMPCHANGE
- HAMSICONTEXT
- HAMSISESSION
- JET_LS
- JET_OSSNAPID
- OLE_HANDLE
- HRSRC
- PSID
- HACCESSOR
- BCRYPT_ALG_HANDLE
- BCRYPT_HANDLE
- PRJ_DIR_ENTRY_BUFFER_HANDLE
- PRJ_NAMESPACE_VIRTUALIZATION_CONTEXT
- HCS_CALLBACK
- JET_API_PTR
- JET_HANDLE
- JET_INSTANCE
- JET_SESID
- JET_TABLEID
- HDC
- HGDIOBJ
- HMONITOR
- HCERTSTORE
- HCERTSTOREPROV
- HCRYPTPROV_LEGACY
- HCRYPTPROV_OR_NCRYPT_KEY_HANDLE
- NCRYPT_HANDLE
- NCRYPT_HASH_HANDLE
- NCRYPT_SECRET_HANDLE
- HIMC
- HIMCC
- HSAVEDUILANGUAGES
- CO_DEVICE_CATALOG_COOKIE
- CO_MTA_USAGE_COOKIE
- LPM_HANDLE
- RHANDLE
- HRASCONN
- HTASK
- HPSS
- HPSSWALK
- HACMDRIVER
- HACMDRIVERID
- HACMOBJ
- HACMSTREAM
- HMIDI
- HMIDIIN
- HMIDIOUT
- HMIDISTRM
- HMIXER
- HMIXEROBJ
- HWAVE
- HWAVEIN
- HWAVEOUT
- HCONV
- HCONVLIST
- HDDEDATA
- HSZ
- HTTP_PUSH_WAIT_HANDLE
- WEB_SOCKET_HANDLE
- HPTPROVIDER
- SERVICE_STATUS_HANDLE
- HRAWINPUT
- CF_CONNECTION_KEY
- FEATURE_STATE_CHANGE_SUBSCRIPTION
- FH_SERVICE_PIPE_HANDLE
- HWINWATCH
- PFLT_CONTEXT
- HGESTUREINFO
- HTOUCHINPUT
- HRECOALT
- HRECOCONTEXT
- HRECOGNIZER
- HRECOLATTICE
- HRECOWORDLIST
- HDROP
- HPSXA
- HUIAEVENT
- HUIANODE
- HUIAPATTERNOBJECT
- HUIATEXTRANGE
- AUTHZ_ACCESS_CHECK_RESULTS_HANDLE
- AUTHZ_AUDIT_EVENT_HANDLE
- AUTHZ_AUDIT_EVENT_TYPE_HANDLE
- AUTHZ_CAP_CHANGE_SUBSCRIPTION_HANDLE
- AUTHZ_CLIENT_CONTEXT_HANDLE
- AUTHZ_RESOURCE_MANAGER_HANDLE
- AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE
- HINTERACTIONCONTEXT
- HDPA
- HDSA
- HSYNTHETICPOINTERDEVICE
- DPI_AWARENESS_CONTEXT
- HANDLE_SDP_TYPE
- DHPDEV
- DHSURF
- HBM
- HDEV
- HDRVOBJ
- HFASTMUTEX
- HSURF
- HDIAGNOSTIC_DATA_QUERY_SESSION
- HDIAGNOSTIC_EVENT_CATEGORY_DESCRIPTION
- HDIAGNOSTIC_EVENT_PRODUCER_DESCRIPTION
- HDIAGNOSTIC_EVENT_TAG_DESCRIPTION
- HDIAGNOSTIC_RECORD
- HDIAGNOSTIC_REPORT
- NCRYPT_DESCRIPTOR_HANDLE
- NCRYPT_STREAM_HANDLE
- PSECURITY_DESCRIPTOR
- SAFER_LEVEL_HANDLE
- SC_HANDLE
- APARTMENT_SHUTDOWN_REGISTRATION_COOKIE
- HSTRING_BUFFER
- ROPARAMIIDHANDLE
- SPGRAMMARHANDLE
- SPPHRASEPROPERTYHANDLE
- SPPHRASERULEHANDLE
- SPRECOCONTEXTHANDLE
- SPRULEHANDLE
- SPSTATEHANDLE
- HCMNOTIFICATION
- SPTRANSITIONID
- SPWORDHANDLE
- HSWDEVICE
- HKL
- LPPROC_THREAD_ATTRIBUTE_LIST
- PTP_CALLBACK_INSTANCE
- PTP_IO
- PTP_TIMER
- PTP_WAIT
- PTP_WORK
- HDRVR
- HIC
- HMMIO
- HVIDEO
- HDWP

**Comment by riverar** [comment]
> * HIORING
Disassembling `kernelbase![...]::VerifyValidIoRingHandle` reveals it returns `INVALID_HANDLE_VALUE` when provided `-1` and `0`, so will add that.

> * PTP_CLEANUP_GROUP
Documented as an opaque struct pointer. We can minimally add `0` to the invalid handle value list here.

> * PTP_POOL
Same as above.

> * SOCKET
Will add `-1` per `INVALID_SOCKET`.

**Comment by riverar** [comment]
Regarding the longer list of types that have `InvalidHandleValue` markings but not `RAIIFree`, this is just an artifact of the RAII effort not being complete. Will try to get those all covered.

**Comment by kennykerr** [comment]
Found `REGHANDLE` - may want to add a test for this...

**Comment by riverar** [comment]
Good catch, will create a separate issue to track. Looks easy enough.
