### ISSUE TITLE
`RAIIFree` functions have wrong type

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1892]
* `COMPRESSOR_HANDLE`'s free function is `CloseDecompressor` and it should probably expect a `COMPRESSOR_HANDLE` parameter type instead of `IntPtr`.

* `WSAEVENT`'s free function is `WSACloseEvent` and it should probably expect a `WSAEVENT` parameter type instead of  `HANDLE`.

**Comment by riverar** [comment]
Note: `COMPRESSOR_HANDLE` should be tied to `CloseCompressor`, not `CloseDecompressor`

**Comment by mikebattista** [comment]
`WSAEVENT` is #1587.
