### ISSUE TITLE
DWRITE_PAINT_FEATURE_LEVEL is defined twice with one definition that's wrong

### ISSUE THREAD

**Issue by smourier** [microsoft/win32metadata#1896]
DWRITE_PAINT_FEATURE_LEVEL is defined in `Windows.Win32.Graphics.DirectWrite` like this:

```
public enum DWRITE_PAINT_FEATURE_LEVEL
{
	DWRITE_PAINT_FEATURE_LEVEL_NONE,
	DWRITE_PAINT_FEATURE_LEVEL_COLR_V0,
	DWRITE_PAINT_FEATURE_LEVEL_COLR_V1
}

```
which is correct

and in  `Windows.Win32.Graphics.Direct2D` like this

```
public enum DWRITE_PAINT_FEATURE_LEVEL
{
    // nothing here.... ???
}

```
which is incorrect. The latter one should be removed.

**Comment by riverar** [comment]
Thanks @smourier, should be fixed in the next release.
