### ISSUE TITLE
Document how developers can contribute missing APIs 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#19]
What are the steps, how to test changes, ideally how a CI build or at least a PR reviewer would validate changes, and how we ensure quality, coverage, and completeness.

**Comment by mikebattista** [comment]
I believe this is addressed now at https://github.com/microsoft/win32metadata/blob/master/CONTRIBUTING.md.

I intend to add a section on enums as well but need some feedback from @sotteson first.
