### ISSUE TITLE
Need Rust bindings for bcrypt_provider.h and ncrypt_provider.h

### ISSUE THREAD

**Issue by ajrzeznik** [microsoft/win32metadata#1907]
My team is writing a KSP Provider in Rust. Currently we need to use the following headers in our implementation of a KSP provider:

bcrypt.h
ncrypt.h
wincrypt.h
bcrypt_provider.h
ncrypt_provider.h
 
Based on our analysis, the first 3 headers are already covered by the windows-rs crate, but it seems that the last 2 headers, for the providers specifically, are not included. It would be great to get those eventually included to allow us to avoid our own bindgen completely for writing a KSP provider. Please let me know if you need any additional info or if there's anything else I can do to help. (Issue posted here after discussing with @jder )

**Comment by riverar** [comment]
Hi @ajrzeznik, can you provide some examples of APIs from the last two headers? Those headers don't seem to be in the SDK.

**Comment by riverar** [comment]
Oh I see, this is part of the Microsoft Cryptographic Provider Development Kit (CPDK).

**Comment by riverar** [comment]
I was able to generate a Rust crate using my steps documented at https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate/ (along with some elbow grease). But as expected, there's a great amount of overlap with the existing Win32 metadata--[only about 5 new functions and a handful of constants/types](https://gist.githubusercontent.com/riverar/4251f33270fd983d6857b0bbd387a102/raw/fb1771b49744b0da1706a0351a4f410d4899d838/bindings.rs).

@mikebattista Are you okay with me incorporating the Microsoft CPDK (https://www.microsoft.com/en-my/download/details.aspx?id=30688) into this repository for inclusion in our existing crypto partitions?
