### ISSUE TITLE
Annotation support for tagged unions

### ISSUE THREAD

**Issue by JesperTreetop** [microsoft/win32metadata#192]
A common pattern is tagged unions, ie for a struct to contain two related members: a union of alternative values, and a value specifying which union arm is being used. For example, see the [`FWP_VALUE0`](https://docs.microsoft.com/en-us/windows/win32/api/fwptypes/ns-fwptypes-fwp_value0) structure and its `FWP_DATA_TYPE` specifier.

Language wrappings and autogenerated interfacing code could add better error checking and type safety if there was a way to annotate a link between the possible values of the specifier and which arm of the union is populated. (Although it would likely come with some safety valve in case you wanted to use the union to do eg type punning; reading the first 16-bit integer of a 32-bit integer value and the like.)

The absolute best option would be to have this information in the SDK headers but that's probably unlikely to happen, but auxiliary notes in a project like win32metadata is the next best thing.

**Comment by mikebattista** [comment]
@kennykerr @aarnott @timsneath what kind of projection support would you implement here?

The current developer experience is check the data type specifier field against the docs to know with union arm to inspect.

**Comment by AArnott** [comment]
In the past I think we decided not to make this better than the docs and header files already present in C. Folks should read the docs to know which fields to read/write and in what order.

That said, I'm interested in seeing what usage pattern this 'tagged union' would enable. 

Also, the current C# experience for union structs is really quite bad, and there are already things we can do to make it much better. So @jespertreetop if that's where you were coming from, there's hope for the future.

**Comment by kennykerr** [comment]
I don't think I'd be able to benefit from this in systems languages.

**Comment by mikebattista** [comment]
Ok. I will close then.
