### ISSUE TITLE
It would be nice to have an `impl From<DEVPROPKEY> for PROPERTYKEY`

### ISSUE THREAD

**Issue by docwilco** [microsoft/win32metadata#1922]
### Suggestion

When getting properties for a device, all the constants (like `Properties::DEVPKEY_Device_FriendlyName`) are of type `DEVPROPKEY`, but `IPropertyStore::GetValue()` takes a `*const PROPERTYKEY`. 

I guess having `IPropertyStore::GetValue()` take an `Into<PROPERTYKEY>` of some form would be nice as well :)

As a workaround, I'm currently using:

```rs
static DEVICE_FRIENDLY_NAME: PROPERTYKEY = PROPERTYKEY {
    fmtid: Properties::DEVPKEY_Device_FriendlyName.fmtid,
    pid: Properties::DEVPKEY_Device_FriendlyName.pid,
};
```

**Comment by mikebattista** [comment]
I moved `DEVPROPKEY` and `PROPERTYKEY` to `Windows.Win32.Foundation` and added `AlsoUsableFor("PROPERTYKEY")` to `DEVPROPKEY` which should allow you to pass `DEVPROPKEYs` wherever `PROPERTYKEYs` are expected.
