### ISSUE TITLE
Update to 10.0.26100.1 SDK

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1930]
The new SDK didn't help with the exports and also the Hypervisor headers were changed to add AMD64 conditionals which requires some changes. It's confusing the cross-arch build of the partition and needs to be investigated.

_Originally posted by @mikebattista in https://github.com/microsoft/win32metadata/issues/1928#issuecomment-2179524422_

**Comment by riverar** [comment]
@mikebattista Did you want a hand with this one or is this a placeholder for your PR?

**Comment by mikebattista** [comment]
If you could take a look, that would be great. Here are the steps to follow to get to where I left off:

* Run `scripts\UpdateSDK.ps1 10.0.26100.1`.
* Fix the few reported libMappings.rsp errors related to multiple mappings by removing the alternative mappings
* The bottom of libMappings.rsp should have a hunk of removals as those are manual additions. Add them back by reverting the removal hunk in the git diff
* Remove "Hypervisor" from the below line given the changes to the Hypervisor headers in the latest SDK. You'll get a different error about a Hypervisor-related CloseApi not being found if you don't do this so things are broken either way
 https://github.com/microsoft/win32metadata/blob/948286f7c03b488f8665009224ad43898b950a7a/generation/WinSDK/Windows.Win32.proj#L51

* Run a [clean build](https://github.com/microsoft/win32metadata/blob/main/CONTRIBUTING.md#Full-builds)

You'll run into unresolved reference errors in the Hypervisor APIs. It looks like the referenced types are getting scraped during the arm64 and x64 passes which is expected given how the headers changed. The errors are reported in the Hypervisor.modified files which are generated by the crossarch part of the build.

![image](https://github.com/microsoft/win32metadata/assets/13860912/6d7c226a-494b-4ef4-b1a8-7fce53bd4d5d)

**Comment by riverar** [comment]
@mikebattista Hm, think there's something going on with the crossarch tree merging and maybe some bad assumptions about enumerations always existing in x86. Just my early thinking so far.

**Comment by riverar** [comment]
@mikebattista WIP if you want to take a peek: https://github.com/microsoft/win32metadata/pull/1934

Some changes:
* Restored any headers, mappings, etc. that would lead to breakage downstream (e.g. drop of AllJoyn, P2P, etc. APIs)
* Added enum support to cross-arch tree merger + tests
* Dropped enums ISC_REQ_FLAGS, ASC_REQ_FLAGS, DNS_QUERY_OPTIONS due to mixed constant sizes/types (we should address via #1933 first/separately)
* Updated `NTDDI_VERSION` for IDL passes

Am investigating some enum test failures now.

**Comment by mikebattista** [comment]
> @mikebattista Hm, think there's something going on with the crossarch tree merging and maybe some bad assumptions about enumerations always existing in x86. Just my early thinking so far.

Based on your changes, looks like you were exactly right about this. Looking good.

**Comment by riverar** [comment]
@mikebattista Current blocker is that the Hyper-V platform reuses enum names across architectures, such as:

```cpp
#if defined(_AMD64_)
typedef enum WHV_RUN_VP_EXIT_REASON
{
    WHvRunVpExitReasonNone                   = 0x00000000,
    WHvRunVpExitReasonMemoryAccess           = 0x00000001,
    // ...
}
#elif defined(_ARM64_)
typedef enum WHV_RUN_VP_EXIT_REASON
{
    WHvRunVpExitReasonNone                   = 0x00000000,
    WHvRunVpExitReasonUnmappedGpa            = 0x80000000,
    // ...
}
```

If we create architecture-specific types (e.g. `WHV_xxx_AMD64` and `WHV_xxx_ARM64)`, we then need to propagate that to any references (e.g. methods), which I don't think we support today. Attempting to merge any duplicate bitflag enums could work for the above example...

But then we'll run into the same problem with structures such as:

```cpp
typedef union WHV_CAPABILITY_FEATURES
{
    struct
    {
        UINT64 PartialUnmap : 1;
#if defined(_AMD64_)
        UINT64 LocalApicEmulation : 1;
        UINT64 Xsave : 1;
#else
        UINT64 ReservedArm0 : 2;
#endif
        UINT64 DirtyPageTracking : 1;
        UINT64 SpeculationControl : 1;
#if defined(_AMD64_)
        UINT64 ApicRemoteRead : 1;
#else
        UINT64 ReservedArm1 : 1;
#endif
        UINT64 IdleSuspend : 1;
        UINT64 VirtualPciDeviceSupport : 1;
        UINT64 IommuSupport : 1;
        UINT64 VpHotAddRemove : 1;
        UINT64 Reserved : 54;
    };

    UINT64 AsUINT64;
} WHV_CAPABILITY_FEATURES;
```

I believe a similar architecture-specific references change is needed to fix `CONTEXT` (#1044) and others too.

**Comment by mikebattista** [comment]
Related to https://github.com/microsoft/wdkmetadata/issues/23 as well.

**Comment by mikebattista** [comment]
So that we don't block on the SDK update, we could hold back the HyperVisor headers to the previous version until we have a proper fix for this.

**Comment by riverar** [comment]
Can explore that, but I'll be out until October. Just heads up.

**Comment by mikebattista** [comment]
I'll take a look.
