### ISSUE TITLE
Enable building with one less processor

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1931]
Running the various scripts, builds, consumes all processors creating a slow inner-loop Windows developer experience. (File Explorer can even time out and crash.) I don't think we'll see significant slowdowns with one less processor configured.

**Comment by mikebattista** [comment]
I believe the parallelism is handled via the below code.

https://github.com/microsoft/win32metadata/blob/97db7a1a021f1fb397ff52ab6df38cbbd88fcc1d/sources/GeneratorSdk/MetadataTasks/ScrapeHeaders.cs#L114-L141

I don't see MaxProcessors set anywhere, so in theory the build should only use half of your processors. Can you confirm what behavior you're seeing?
