### ISSUE TITLE
Native type defs changed from `IntPtr` fields to `void*`

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1936]
Was the change of handles from `IntPtr` to `void*` intentional in the v61 release of the metadata? It broke cswin32, and while I can make a change to accommodate this change, I wonder what value this change brought to the metadata or projections to confirm it will remain before I adjust CsWin32.

```diff
 [RAIIFree("CloseHandle")]
 [InvalidHandleValue(-1L)]
 [InvalidHandleValue(0L)]
 [NativeTypedef]
 public struct HANDLE
 {
-	public IntPtr Value;
+       public unsafe void* Value;
 }
```

**Comment by robmikh** [comment]
Related: #1924
