### ISSUE TITLE
IPropertyStoreCapabilities has no way to return its value

### ISSUE THREAD

**Issue by asklar** [microsoft/win32metadata#1941]
## Actual behavior
IPropertyStoreCapabilities::IsPropertyWritable returns S_OK or S_FALSE
However it is projected as returning void

## Expected behavior

ideally return true/false

**Comment by AArnott** [comment]
In the meantime, @asklar, you can use the NativeMethods.json file to add this method to the preserveSig methods so that you get the HRESULT back.

**Comment by riverar** [comment]
Fixed for next release.  As Andrew mentioned, an easy short term workaround is to disable CsWin32 signature transformation for this method, as such:

```json
{
    "$schema": "https://aka.ms/CsWin32.schema.json",
    "comInterop": {
        "preserveSigMethods": [
            "IPropertyStoreCapabilities.IsPropertyWritable"
        ]
    }
}
```
