### ISSUE TITLE
Where is InitPropVariantFromString?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#1946]
### Discussed in https://github.com/microsoft/CsWin32/discussions/1234

<div type='discussions-op-text'>

<sup>Originally posted by **optsing** July 10, 2024</sup>
If I add `InitPropVariantFromString` to `NativeMethods.txt`, I get the warning message 

> Method, type or constant "InitPropVariantFromString" not found. Did you mean  or "InitPropVariantFromStringVector" or "InitPropVariantFromStringAsVector"?
 
Why is this method missing? What is the correct way to create PROPVARIANT without it?</div>

It's missing from the metadata, but [it is a documented function](https://learn.microsoft.com/en-us/windows/win32/api/propvarutil/nf-propvarutil-initpropvariantfromstring).

**Comment by ChrisDenton** [comment]
From the "Requirements" section of the documentation page, it looks like it's a header-only function. So it's not actually exposed by any Windows DLLs.

**Comment by AArnott** [comment]
Interesting observation about being an inline function. I suspect that's why the clang scanner missed it. The metadata doesn't expect to include _macros_ most of the time, but I don't know about these inline functions.

**Comment by riverar** [comment]
`InitPropVariantFromString` is a header-only helper function. It's not available for use outside of C++.
