### ISSUE TITLE
Windows.Win32.Ual is empty

### ISSUE THREAD

**Issue by reflectronic** [microsoft/win32metadata#195]
It doesn't seem to have any APIs in it.
![Decompilation of Win32.Windows.winmd, showing an empty Windows.Win32.Ual namespace](https://user-images.githubusercontent.com/27514983/106064828-6938fc00-60c8-11eb-94f3-4317083e830c.png)

**Comment by sotteson1** [comment]
This is fixed in 10.0.19041.5-preview.2.
