### ISSUE TITLE
ICU functions should be imported from the "old" libraries

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/win32metadata#1956]
Hi,

First of all, I am not entirely sure whether this issue is for _win32metadata_ or for _windows-rs_, so please let me know if I should open it there instead.

According to the [(abandoned) documentation](https://learn.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-#history-of-changes-to-the-icu-library-in-windows), ICU was introduced in Windows 10 **v1703** (Creators Update) as two separate libraries, `icuuc.dll` and `icuin.dll`. It wasn't until Windows 10 **v1903** that they were combined into a new library, `icu.dll`. However, _windows-rs_ (and, I presume, _win32metadata_) links to `icu.dll`.

This makes built-in Windows ICU impossible to use on still supported OS's like Windows 10 LTSC 2019 or Windows Server 2019, because they're based on Windows 10 **v1809** which, according to the documentation, didn't include the combined `icu.dll` yet.

I would like to ask you to update _win32metadata_ in such a way that it links against the "old" `icuuc.dll` and `icuin.dll` libraries as they still exist in newer versions of Windows as DLL forwarders. Thanks!

/cc @kennykerr

**Comment by riverar** [comment]
![image](https://github.com/user-attachments/assets/ae7548a1-20b1-4a69-901e-8356e4f353d9)

Windows provides forwarders, but I'm concerned about `icuuc.dll` and `icuin.dll` being marked as _deprecated_. If we make this change, and then the next OS version drops the forwarders, we'll break the world. 🤔

Also related to metadata's lack of reliable/cross OS version information (#738, #1341, et al).

**Comment by Alovchin91** [comment]
> Windows provides forwarders, but I'm concerned about `icuuc.dll` and `icuin.dll` being marked as _deprecated_. If we make this change, and then the next OS version drops the forwarders, we'll break the world. 🤔

Those two DLLs have been public API between v1703 and v1903 at the very least, and they're still the only ones available in v1809 which is Windows Server 2019 and Windows 10 LTSC 2019, and those are supported until 2029.

Honestly, I just can't see how this can be a concern, given the track record of Windows backwards compatibility 🙂

That being said though, it might make sense to have an option to specify LIBs to link against manually, but I guess this is a feature request for _windows-rs_.

**Comment by kennykerr** [comment]
Forwarders exist and I can see nothing in the docs to indicate that they're going to be removed.

https://learn.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-

I would thus recommend using the original DLL names for compatibility.

**Comment by riverar** [comment]
I not convinced, but sure let's try it.

**Comment by riverar** [comment]
Another concern I have is that the forwarders are frozen/not tracking ICU API changes. (We already have ICU functions in metadata that are not present in the forwarders.) So if I remap all our APIs to the forwarders, we pollute our ICU namespace with old and renamed/new (possibly duplicate) APIs.

Instead, we should probably create an entirely separate partition for the frozen legacy ICU API surface, perhaps something like `Windows.Win32.Globalization.ICU##` (icu**.h), keeping the newer APIs in `Windows.Win32.Globalization.ICU` (icu.h). In my local testing, it appears to be a nice clean break. (I don't yet know what ICU version number to put into ## above.)

(These forwarders don't really offer much in terms of backwards compatibility. Apps using the older APIs will fail if/when the newer ICU library is updated, if they don't already. Real world example: `u_getIntPropertyMinValue` had its return values changed between ICU versions...)

**Comment by Alovchin91** [comment]
> (These forwarders don't really offer much in terms of backwards compatibility. Apps using the older APIs will fail if/when the newer ICU library is updated, if they don't already. Real world example: `u_getIntPropertyMinValue` had its return values changed between ICU versions...)

In that case, you might want to consider removing ICU support from the metadata altogether since what you're saying means that it's not guaranteed that apps compiled today will work on Windows tomorrow. And today _windows-rs_ is ultimately incompatible with still-supported older versions of Windows 🤷‍♂️

**Comment by kennykerr** [comment]
Agreed, if that's true it may be better to remove the APIs.

**Comment by riverar** [comment]
An update on the partitioning experiment--I was able to emit the following metadata. But it's unclear if these duplicates will cause problems downstream. Might present issues if someone flattens the tree?

```csharp
// Windows.Win32.Globalization.ICU.Apis
[DllImport("icu.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, PreserveSig = false)]
public unsafe static extern int utrans_toRules([In][Const] void** trans, [In] sbyte escapeUnprintable, [In][Out] ushort* result, [In] int resultLength, [In][Out] UErrorCode* status);

// Windows.Win32.Globalization.ICUXX.Apis
[DllImport("icuin.dll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true, PreserveSig = false)]
public unsafe static extern int utrans_toRules([In][Const] void** trans, [In] sbyte escapeUnprintable, [In][Out] ushort* result, [In] int resultLength, [In][Out] UErrorCode* status);
```

**Comment by kennykerr** [comment]
That's also problematic in Rust which doesn't like the idea of duplicate import names. It cannot disambiguate them at link time.

**Comment by kennykerr** [comment]
Neither can C++ for that matter.

**Comment by riverar** [comment]
Thanks for the sanity check Kenny. Multiple partition idea is out then, bummer.

We can turn a blind eye here and just remap to the forwarders (where we can), but the moment Windows ICU owners realize their error and replace the forwarders with backward-compatible wrappers, we'll be back here again 😂.

I'll put together a PR and include everyone here on it.
