### ISSUE TITLE
Create a newtype to handle Pdh* functions

### ISSUE THREAD

**Issue by GuillaumeGomez** [microsoft/win32metadata#1962]
Since the 0.58 version, functions like `PdhCollectQueryData` take a `isize` instead of a `HANDLE`. This is pretty bad as we there is no method available on `isize` to check if its value is correct or basically any helper. In addition, it makes it much harder when reading code what we're actually manipulating.

Would you be open in adding such a newtype to address these two problems?

Thanks in advance!

**Comment by riverar** [comment]
I don't see any indication this API ever took a specialized handle (from a metadata perspective). Happy to add it though.

**Comment by GuillaumeGomez** [comment]
It would be very welcome. :)

**Comment by GuillaumeGomez** [comment]
Awesome, thanks!
