### ISSUE TITLE
`wincrypt.h` metadata issues

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1963]
- `HCERTCHAINENGINE` is a typedef for `HANDLE` in the C headers so should have the same underlying type in the metadata.
- [`CERT_CHAIN_PARA`](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/ns-wincrypt-cert_chain_para) is missing the extra fields. It only defines the first two.
- ~~the type aliases for [`CRYPT_INTEGER_BLOB`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa381414(v=vs.85)) are missing~~

**Comment by mikebattista** [comment]
3 is https://github.com/microsoft/win32metadata/issues/1339. We don't support other type aliases.

**Comment by ChrisDenton** [comment]
Fair enough.
