### ISSUE TITLE
QueryOptionalDelayLoadedAPI is missing

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/win32metadata#1966]
[QueryOptionalDelayLoadedAPI](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi2/nf-libloaderapi2-queryoptionaldelayloadedapi) is missing from the metadata, so I have to manually import it to use as follows:

```rust
unsafe {
    QueryOptionalDelayLoadedAPI(
        crate::GetModuleInstanceHandle(),
        s!("api-ms-win-appmodel-runtime-l1-1-3.dll"),
        s!("GetCurrentPackagePath2"),
        0,
    )?
};
...
GetCurrentPackagePath2(PackagePathType_EffectiveExternal, length, PWSTR::from_raw(vec.as_mut_ptr()));
```

/cc @kennykerr @riverar

**Comment by riverar** [comment]
Thanks @Alovchin91 we'll get that fixed up.
