### ISSUE TITLE
Annotate `IDCompositionDesktopDevice/IDCompositionDevice::CreateSurfaceFromHandle()` to return `IDCompositionSurface`?

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/win32metadata#1968]
Currently `IDCompositionDesktopDevice::CreateSurfaceFromHandle()` and `IDCompositionDevice::CreateSurfaceFromHandle()` return `IUknown` (and it seems the same is true for their `CreateSurfaceFromHwnd()` counterparts). Unfortunately, calling `QueryInterface` on the returned COM interface returns `None` for `IDCompositionSurface`.

Digging in a debugger, the symbols for the returned pointer are from an internal class `DirectComposition::CCompositionSurfaceProxy`. And further stumbling upon [this official examle from Microsoft](https://github.com/microsoft/media-foundation/blob/a17adcfcee7c92c57eb2257aed1d4fa3fa99fa67/samples/MediaEngineDCompWin32Sample/src/ui/DirectCompositionLayer.cpp#L16C24-L17), it simply turns out that we have to _reinterpret the pointer_ to pretend it's an `IDCompositionSurface`.

I'm not sure what we should do here, but I assume `QueryInterface` is always supposed to be functional? Either:

1. `QueryInterface` fixed to be queriable for its own type (anticipating extensions later on), or;
2. A version of this function that takes an `IID` so that we can call it for the expected COM object type (similar to `DCompositionCreateDevice()`).

In the title I suggested to use the return type of `IDCompositionSurface` but that should trickle down into the internal bindings and doesn't allow other interfaces to be returned further down the road unless they derive from `IDCompositionSurface` (though that afaik relies on the caller passing in an `IID`?).

Thanks!

**Comment by kennykerr** [comment]
@robmikh may have some thoughts...

**Comment by riverar** [comment]
I don't believe it would be appropriate for metadata or windows-rs to make one-off changes in this situation. It might be more effective to address this with a warning in the composition documentation if needed.

**Comment by MarijnS95** [comment]
@riverar yes, I had hoped alarm bells would go off when a `reinterpret_cast()` is required to get a certain interface in/out of an API in an official sample. A warning would be nice, especially if `QueryInterface` is fixed in a future release (and developers see it working on their machine, and expect it to be working everywhere else).

**Comment by MarijnS95** [comment]
And not to forget, the [`IDCompositionDevice::CreateSurfaceFromHandle()` only vaguely mentions](https://learn.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositiondevice-createsurfacefromhandle) that this parameter will contain `The new composition surface object` and not at all explicitly that this will be `IDCompositionSurface` with an intra-documentation link. That should be clarified I think.

**Comment by riverar** [comment]
I suspect the sample is wrong and that function is correctly returning an opaque object for you to pass into subsequent methods. The sample doesn't call any methods hanging off `surface` so the bug escapes detection.

**Comment by MarijnS95** [comment]
@riverar you're on to something. I may have spent too much attempting to understand _what `surface`_ to cast the returned `IUnknown` into - and was happy to immediately find that example, without considering for a second that my "use case" only involves passing it into [`IDCompositionVisual::SetContent()`](https://learn.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositionvisual-setcontent) (to make an "external" swapchain visible in a hierarchy) which takes an `IUnknown` _anyway_.
