### ISSUE TITLE
GetCurrentThreadCompartmentId has incorrect return type

### ISSUE THREAD

**Issue by keithmattix** [microsoft/win32metadata#1972]
It should return a [compartment Id](https://github.com/microsoft/win32metadata/blob/ab7c817731474b7a0137dcac7f75ff818ee2c46f/generation/WinSDK/RecompiledIdlHeaders/shared/netioapi.h#L3028) and not just a [win32 error](https://github.com/microsoft/win32metadata/blob/ab7c817731474b7a0137dcac7f75ff818ee2c46f/generation/WinSDK/emitter.settings.rsp#L1235).  The default variant and really several of the compartment family of functions have the same issue: https://github.com/microsoft/win32metadata/blob/ab7c817731474b7a0137dcac7f75ff818ee2c46f/generation/WinSDK/emitter.settings.rsp#L1207

**Comment by riverar** [comment]
`ConvertCompartmentIdToGuid` looks okay; it returns error codes in user mode. Agreed on `GetCurrentThreadCompartmentId`, however. Will get that patched up!

**Comment by riverar** [comment]
Ah, here's the trickiness that probably tripped up the first pass:

```cpp
#ifdef __IPHLPAPI_H__

//
// User Mode.  This file should be included from iphlpapi.h
// User should include ws2ipdef.h to use these APIs.
//

#define NETIO_STATUS DWORD
#define NETIO_SUCCESS(x) ((x) == NO_ERROR)
#define NETIOAPI_API_ WINAPI
#define _NETIOAPI_SUCCESS_ _Success_(return==NO_ERROR)
#else

//
// Kernel Mode.
//

...

#define NETIO_STATUS NTSTATUS
#define NETIO_SUCCESS(x) NT_SUCCESS(x)
#define NETIOAPI_API_ NTAPI
#define _NETIOAPI_SUCCESS_
```

**Comment by mikebattista** [comment]
Can you provide the full list of functions that need to be fixed? Is it all `*Compartment*` APIs in `emitter.settings.rsp` except for `ConvertCompartmentIdToGuid`?

**Comment by riverar** [comment]
@mikebattista Oops, forgot to mention I was in the middle of building this. I added `NET_IF_COMPARTMENT_ID` as a native typedef and just going through the motions.

**Comment by keithmattix** [comment]
After @riverar's feedback, I think it's actually just the 2 that I pointed out
