### ISSUE TITLE
OpenPrinter/ClosePrinter

### ISSUE THREAD

**Issue by serj1980** [microsoft/win32metadata#1982]
## Actual behavior
OpenPrinter provide SafeFileHandle as out parameter. After use it should use ClosePrinter. ClosePrinter by documentation make handle invalid, but SafeFileHandle don't know about this (still IsValid) and finalizer try to dispose it, that throw exception.

## Expected behavior
SafeFileHandle should be invalid after call of ClosePrinter. 
Alternative should be generate own SafeHandle (f.e. SafePrinterHandle), that automatically call ClosePrinter by dispose self.

## Repro steps

1. `NativeMethods.txt` content:
```
OpenPrinter
ClosePrinter
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context
PInvoke.OpenPrinter(pPrinterName, out var printerHandle, null);
try
{}
finally
{
 PInvoke.ClosePrinter(printerHandle);
 // printerHandle.SetHandleAsInvalid();   // not sure that is correct workaround, but it prevent exception to throw 
}
- CsWin32 version: 0.3.106
- Win32Metadata version (if explicitly set by project):
- Target Framework: net462, net8.0-windows
- `LangVersion` (if explicitly set by project): 9

**Comment by riverar** [comment]
Note to us: [`DocumentEvent`](https://learn.microsoft.com/windows/win32/printdocs/documentevent) is not a Win32 API as documented / is missing from headers. There's a similar _method_ in prcomoem.h but we'll have to dig into this. Ignoring for this issue.

**Comment by AArnott** [comment]
@riverar what does `DocumentEvent` have to do with `OpenPrinter`?

**Comment by riverar** [comment]
I'm creating a PRINTER_HANDLE type and associating it with printer handle APIs/parameters. Just stumbled on that particular function to be weird and made a note for future self.
