### ISSUE TITLE
Missing FlushMenuThemes, SetPreferredAppMode

### ISSUE THREAD

**Issue by ghost1372** [microsoft/win32metadata#2003]
## Actual behavior

i want to use FlushMenuThemes, SetPreferredAppMode and RtlGetVersion methods but none of them exist, currently i can use them with dllimport:

```
[DllImport(ExternDll.UxTheme, EntryPoint = "#136", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
public static extern void FlushMenuThemes();

[DllImport(ExternDll.UxTheme, EntryPoint = "#135", SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
public static extern int SetPreferredAppMode(PreferredAppMode preferredAppMode);

[DllImport(ExternDll.NTdll)]
public static extern int RtlGetVersion(out RTL_OSVERSIONINFOEX lpVersionInformation);
```

but i can not access this methods because do not exist/available
## Expected behavior

we should be able to use FlushMenuThemes, SetPreferredAppMode, RtlGetVersion

## Repro steps

1. `NativeMethods.txt` content:
```
`RtlGetVersion`
`FlushMenuThemes`
`SetPreferredAppMode`
`136`
`135`
`#136`
`#135`
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.4.422-beta`] latest
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`] net8.0
- `LangVersion` (if explicitly set by project): [e.g. `9`] Latest

**Comment by riverar** [comment]
`RtlGetVersion` is already covered by WDK metadata.

`FlushMenuThemes` and `SetPreferredAppMode` appear to be undocumented, exported only by ordinal via uxtheme. While public, not sure those are a candidate for addition to metadata? @mikebattista

**Comment by ghost1372** [comment]
Thank You @riverar 
so what should i do? i am not familiar with WDK metadata. should  i install some nuget package to fix it?

**Comment by riverar** [comment]
@AArnott What's the official way to bring WDK metadata into CsWin32? Or does @ghost1372 need to manually add a reference like I did in https://github.com/microsoft/CsWin32/issues/1176?

**Comment by AArnott** [comment]
WDK metadata is brought in by default. `RtlGetVersion` is available already if you ask for it in NativeMethods.txt. It's generated as `Windows.Wdk.PInvoke.RtlGetVersion`

**Comment by ghost1372** [comment]
> WDK metadata is brought in by default. `RtlGetVersion` is available already if you ask for it in NativeMethods.txt. It's generated as `Windows.Wdk.PInvoke.RtlGetVersion`

tnx but its not working!

![image](https://github.com/user-attachments/assets/f7cfc715-186d-446f-82ef-291369cfd2d1)


![image](https://github.com/user-attachments/assets/499536b1-95f6-4f29-a40d-3d1a7b5a211f)

**Comment by riverar** [comment]
@ghost1372 Try just adding `RtlGetVersion` to `NativeMethods.txt`.

**Comment by ghost1372** [comment]
> `RtlGetVersion`

Tnx it is working fine!
It's very strange, I tried this before and it didn't work (my first post), but now it works without any problem, of course I have to say that I installed the following packages (In CSWin32, their versions are less)
```
    <PackageReference Include="Microsoft.Windows.SDK.Win32Metadata" Version="62.0.23-preview" />
    <PackageReference Include="Microsoft.Windows.WDK.Win32Metadata" Version="0.12.8-experimental" />
```
 but now that I have removed it, it still works.

**Comment by ghost1372** [comment]
I was globally using the following namespace, so PInvoke was always called from there
`global using Windows.Win32;`
Now I found that PInvoke is also available in the following namespace
`using Windows.Wdk;`

**Comment by AArnott** [comment]
I've dropped `RtlGetVersion` from the title since that's already there. 
That leaves the remaining two apparently undocumented functions for consideration.

**Comment by mikebattista** [comment]
I'm following up for some more context on these APIs. If they're internal/undocumented, then I won't add them here.

**Comment by mikebattista** [comment]
I confirmed these aren't ready for general use so will not be added here.
