### ISSUE TITLE
WINTRUST_SIGNATURE_SETTINGS_FLAGS should be a flagged enum

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#2008]
See https://learn.microsoft.com/en-us/windows/win32/api/wintrust/ns-wintrust-wintrust_signature_settings dwFlags for details.

**Comment by mikebattista** [comment]
The docs say the parameter can be one of the following values, not a combination.

**Comment by Nuklon** [comment]
It doesn't say that? 🤔

> dwFlags
> **Flags** that can be used to refine behavior.

It's absolutely working as a flag. See also https://github.com/NVIDIAGameWorks/Streamline/blob/f9fc648591a88d6accf859cd5c36010c25b6ab7b/include/sl_security.h#L413
https://github.com/brave/chromium/blob/4e22a93b12f76cc59ee084f7f6887afc232e2afd/components/device_signals/core/system_signals/win/win_platform_delegate.cc#L140

**Comment by mikebattista** [comment]
The doc you linked says "one of the following values".

**Comment by riverar** [comment]
The usage as flags seems to be codified in the official samples too https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Security/CodeSigning/cpp/codesigning.cpp#L70. Probably just another docs bug.

**Comment by Nuklon** [comment]
Yes, I also tried it myself and can confirm that it really is a flag.
