### ISSUE TITLE
Support for enum types in CreateFont method instead of casting to uint

### ISSUE THREAD

**Issue by vitkuz573** [microsoft/win32metadata#2009]
## Description

Currently, when calling `CreateFont`, it is necessary to cast enum values to `uint` for the following parameters:

- `iCharSet` (e.g., `FONT_CHARSET`)
- `iOutPrecision` (e.g., `FONT_OUTPUT_PRECISION`)
- `iClipPrecision` (e.g., `FONT_CLIP_PRECISION`)
- `iQuality` (e.g., `FONT_QUALITY`)
- `iPitchAndFamily` (e.g., `FONT_PITCH` and `FONT_FAMILY`)

Here is an example of the current call that requires casting:

```csharp
private static DeleteObjectSafeHandle CreateDefaultFont()
{
    return CreateFont(
        18, 
        0, 
        0, 
        0, 
        (int)FONT_WEIGHT.FW_NORMAL, 
        0, 
        0, 
        0, 
        (uint)FONT_CHARSET.ANSI_CHARSET, 
        (uint)FONT_OUTPUT_PRECISION.OUT_DEFAULT_PRECIS, 
        (uint)FONT_CLIP_PRECISION.CLIP_DEFAULT_PRECIS, 
        (uint)FONT_QUALITY.CLEARTYPE_QUALITY, 
        (uint)FONT_PITCH.DEFAULT_PITCH | (uint)FONT_FAMILY.FF_SWISS, 
        "Segoe UI"
    );
}
```

The need for casting detracts from the readability and safety of the code, since all these parameters are defined as enums in `win32metadata`.

### Suggested Improvement:

It would be ideal if the `CreateFont` method accepted these parameters as their corresponding enum types directly, instead of requiring a cast to `uint`. For example:

- `FONT_CHARSET` for `iCharSet`
- `FONT_OUTPUT_PRECISION` for `iOutPrecision`
- `FONT_CLIP_PRECISION` for `iClipPrecision`
- `FONT_QUALITY` for `iQuality`
- Consider creating a new enum `FONT_PITCH_AND_FAMILY` to replace the current separate `FONT_PITCH` and `FONT_FAMILY` values for `iPitchAndFamily`.

This enhancement would improve code clarity, type safety, and reduce the potential for casting errors.

**Comment by mikebattista** [comment]
Pitch and Family I believe need to be separate as they are meant to be joined in various combinations.
