### ISSUE TITLE
ISpellCheckerFactory::IsSupported takes an *mut i32 instead of *mut BOOL

### ISSUE THREAD

**Issue by rylev** [microsoft/win32metadata#201]
The metadata says that `ISpellCheckerFactory::IsSupported`'s second argument is an *mut i32 instead of *mut BOOL [like it should be](https://docs.microsoft.com/en-us/windows/win32/api/spellcheck/nf-spellcheck-ispellcheckerfactory-issupported).

Perhaps there is a wider issue with `BOOL` since #197 also seems to have a similar issue.

**Comment by sotteson1** [comment]
This is fixed in 10.0.19041.5-preview.2.
