### ISSUE TITLE
IContextMenu::QueryContextMenu returns multiple success values

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#2011]
`IContextMenu::QueryContextMenu` needs PreserveSig or ReturnsMultipleSuccessValues (or equivalent) to handle its unique return semantics https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-icontextmenu-querycontextmenu#return-value

**Comment by biplab5464** [comment]
Hi guys, 

We are planing to implement iContextMenu using windows-rs. Can we have time frame for the fix so we can make our plan according to it.
