### ISSUE TITLE
Does this project support third party DLL?

### ISSUE THREAD

**Issue by HppZ** [microsoft/win32metadata#2015]

**Comment by riverar** [comment]
Not sure what that means, closing for now but feel free to add more detail!

**Comment by HppZ** [comment]
I want to generate c# bindings for C dll automatically.

**Comment by riverar** [comment]
@HppZ Check out my article on generating metadata here https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate/. You can then swap out windows-rs and Rust for CsWin32 and C#.

**Comment by HppZ** [comment]
thank you!

how to customize `DefaultDllImportSearchPaths`, I want it to use `DllImportSearchPath.ApplicationDirectory`
```c#
[DllImport("testdll", ExactSpelling = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
internal static extern int add(int a, int b);
```

**Comment by riverar** [comment]
Use an assembly attribute instead:

```csharp
[assembly: DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
```

**Comment by HppZ** [comment]
I mean I want to change `DllImportSearchPath.System32` to `DllImportSearchPath.ApplicationDirectory` in this generated code. The generated code can't be edited.

![Image](https://github.com/user-attachments/assets/373ce933-6db0-4a14-acea-55979ecb62f2)

**Comment by HppZ** [comment]
I have to dig into source code of cswin32, but not resolved yet.

**Comment by HppZ** [comment]
> Use an assembly attribute instead:
> 
> [assembly: DefaultDllImportSearchPaths(DllImportSearchPath.System32)]

I added `AssemblyInfo.cs` to project and this line `[assembly: DefaultDllImportSearchPaths(DllImportSearchPath.ApplicationDirectory)]` at the bottom of `AssemblyInfo.cs`, but not work.

**Comment by riverar** [comment]
Ah, I didn't realize CsWin32 emits its own. @AArnott thoughts? Or should we file an issue over on CsWin32?

**Comment by HppZ** [comment]
> Ah, I didn't realize CsWin32 emits its own. [@AArnott](https://github.com/AArnott) thoughts? Or should we file an issue over on CsWin32?

https://github.com/microsoft/CsWin32/issues/1307

**Comment by HppZ** [comment]
How to customize access level of generated code?

![Image](https://github.com/user-attachments/assets/60464fe1-2f72-4302-af4a-7a4ef6eb9ccf)

**Comment by HppZ** [comment]
what if there are macros ( _WIN32, __cplusplus, __cpp_decltype ... ) in c++ header files? it seems `WinmdGenerator` can't handle it.

**Comment by HppZ** [comment]
any update?

**Comment by AArnott** [comment]
@HppZ You can make these public by a setting in NativeMethods.json. The README file has details.
