### ISSUE TITLE
BCrypt provider bindings haven't shipped yet

### ISSUE THREAD

**Issue by Amit-L** [microsoft/win32metadata#2016]
Hello!

In reference to [Issue](https://github.com/microsoft/wdkmetadata/issues/81) missing bindings for bcrypt_provider.h. I believe cswin32 will make use of wdkmetadata for functions in bcrypt_provider.h. Posting here to get more clarification.
At the moment [windows-rs](https://github.com/microsoft/windows-rs) do have these bindings ref- #1907 but still missing in [cswin32](https://github.com/microsoft/CsWin32).

**Comment by riverar** [comment]
Hey @Amit-L, current release is dated August. The functions you're looking for were merged in September https://github.com/microsoft/win32metadata/pull/1997. So you should see them in the next release.

cc: @mikebattista

**Comment by mikebattista** [comment]
I intend to fix a few more bugs and ship a release within the next week or two.

**Comment by mikebattista** [comment]
A new release has been published.

**Comment by riverar** [comment]
Thanks!
