### ISSUE TITLE
Missing IOCTL_CDROM_* constants

### ISSUE THREAD

**Issue by Stovent** [microsoft/win32metadata#2018]
### Summary

I noticed while trying to read from a CD drive that the IOCTL_CDROM_* constant for DeviceIoControl were missing in this crate, they do not show in the feature search page (version 0.58.0).
I'm referring to those codes [https://learn.microsoft.com/en-us/previous-versions/windows/drivers/storage/cd-rom-io-control-codes](https://learn.microsoft.com/en-us/previous-versions/windows/drivers/storage/cd-rom-io-control-codes).

**Comment by riverar** [comment]
Ideally you should use the `IOCTL_STORAGE_*` codes over `IOCTL_CDROM_*`. But yep, can confirm they're missing. We'll get them added.

**Comment by riverar** [comment]
@mikebattista I see you assigned youself here, if you'd like can use my branch as a start `rafael/additional-devices`

**Comment by Stovent** [comment]
Thank you for your quick response!

@kennykerr sorry to ping you but I'd like to know when this change will be available in windows-rs ? not necessarily a release but just a branch or commit I can use.

**Comment by riverar** [comment]
I can investigate that.

**Comment by Stovent** [comment]
Thanks, I can wait it's for a personal project, I'm not in a hurry

**Comment by riverar** [comment]
@stovent You can wire up your project to the `rafael/update-metadata` branch on windows-rs.

**Comment by Stovent** [comment]
Thank you very much! I've tested and it works
