### ISSUE TITLE
PowerShell functionality should be exposed in a module

### ISSUE THREAD

**Issue by StartAutomating** [microsoft/win32metadata#202]
The PowerShell portion of this project is a collection of scripts.  It appears that many of them are used to build the language projections.

PowerShell functionality should be included in module form and put onto the PowerShell Gallery:  this will make it easier for the project to be discovered/consumed interactively.

Additionally, it would be desirable to be able to produce a language projection _to PowerShell_ (even if it is merely inlining/linking to the C# language projection).

Would you be open to an experienced scripter helping out with some of this?

**Comment by mikebattista** [comment]
Regarding whether the PS scripts in this repo should be published to PS Gallery, we expect projections to consume the winmd output of this repo, not any scripts. Any scripts here are used to generate the winmd. That said, @sotteson1 may have additional thoughts.

In terms of building a PowerShell projection that shims the C#/Win32 projection, we'd love to see the community run with this.  As stated in #183 , the best way to scale out to more languages is to partner and collaborate with the community where possible.

If you'd like to start this project, I'd suggest creating a repo and sharing it with us. We can add it to our list of projections in this repo.

**Comment by StartAutomating** [comment]
I would think that it would make sense for most projects to online include the winMD that their project needs (if only to minimize their footprint).

As such, I think that it would make sense to make these scripts a little better so that this scenario would be possible.

>In terms of building a PowerShell projection that shims the C#/Win32 projection, we'd love to see the community run with this.  
>If you'd like to start this project, I'd suggest creating a repo and sharing it with us


Ok, I'll try to take a look at doing this.  There are quite a few cases where more P/Invoke would help PowerShell.  Do you have any naming conventions / recommendations / documentation about how this should be approached, or should I just use the C# as a reference implementation?

**Comment by mikebattista** [comment]
There's only 1 winmd here, and it's not meant for direct consumption. The projections provide the developer experience based on the metadata and often need to provide adaptations on top to make the calling conventions more idiomatic.

If you start a repo, I expect we would have design discussions over there about the best ways to approach things. Sounds like you're an experienced PowerShell user so I'd defer to you and others in the community on what the ideal developer experience for PowerShell should be. The important principle is that the projection provides a natural and idiomatic developer experience that would be familiar for users of the language.

If you're planning to shim C#/Win32, processing the metadata yourself would seem less relevant. If you intend to not shim C#/Win32 and parse the metadata yourself, then yes I would use C#/Win32 as a reference implementation.

**Comment by AArnott** [comment]
I suspect that powershell would have to consume a pre-built C# library. That's what we expect https://github.com/dotnet/pinvoke to evolve into: a projection from this winmd + CsWin32.

**Comment by mikebattista** [comment]
That's definitely a possibility. Once we understand what the expected PowerShell experience is, we can determine how to leverage C#/Win32 or a prebuilt library version of it.

Closing this issue out but feel free to continue the discussion here or in a dedicated repo if you decide to stand one up.
