### ISSUE TITLE
Why dllName in `DllImport("", ... )` is empty?

### ISSUE THREAD

**Issue by HppZ** [microsoft/win32metadata#2020]
`libmpv-2.dll`

\bin\Debug\net8.0\winmdProject\obj\generated\common\test.cs

![Image](https://github.com/user-attachments/assets/4e045d97-c4e9-4b96-aa0c-044192b2621b)

**Comment by HppZ** [comment]
`libmpv-2.dll` available here [mpv-dev-x86_64-20241111-git-ca7aeb7](https://github.com/zhongfly/mpv-winbuild/releases/download/2024-11-11-ca7aeb7/mpv-dev-x86_64-20241111-git-ca7aeb7.7z)

**Comment by riverar** [comment]
Missing library mappings. See https://github.com/microsoft/win32metadata/issues/1880#issuecomment-2030472053 for more info!
