### ISSUE TITLE
Please add the function `RtlDosPathNameToNtPathName_U_WithStatus` in `ntdll.dll`

### ISSUE THREAD

**Issue by viruscamp** [microsoft/win32metadata#2033]
### Suggestion

Please add the function `RtlDosPathNameToNtPathName_U_WithStatus` in `ntdll.dll`
https://learn.microsoft.com/en-us/windows/win32/devnotes/rtldospathnametontpathname_u_withstatus

**Comment by riverar** [comment]
This API already exists in wdkmetadata and is in the `master` windows-rs branch. You can either point your crate to master or wait for the next crate release. Hope that helps!

![Image](https://github.com/user-attachments/assets/59f27e4a-38c9-49e1-99e2-0e83afcb256e)
