### ISSUE TITLE
CLSIDFromProgID

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#204]
The API is defined as follows:

```C++
_Check_return_ WINOLEAPI
CLSIDFromProgID(
    _In_ LPCOLESTR lpszProgID,
    _Out_ LPCLSID lpclsid
    );
```

The `_In_ LPCOLESTR` is translating to `[In] ushort*` when it should be be something like `[In][Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort*`.

**Comment by sotteson1** [comment]
Fixed in 10.0.19041.5-preview.3.
