### ISSUE TITLE
Missing Enum Types for CREDENTIAL

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/win32metadata#205]
There are missing enum types for CREDENTIALA and CREDENTIALW:
https://docs.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala

Specifically: CRED_FLAGS, CRED_TYPE and CRED_PERSIST.

**Comment by mikebattista** [comment]
Thanks for reporting. We do have some work to do to round out our enum support and will make sure this is addressed.

**Comment by AliveDevil** [comment]
I [tried adding support for this](https://github.com/AliveDevil/win32metadata/commit/b4e09a9e88b7a42e16be8469cfa8362032c3e5e9) though it looks like some code generation needs a case handling for types in structs …
```
    public unsafe partial struct CREDENTIALA
    {
        [NativeTypeName("DWORD")]
        public CRED_FLAGSFlags;

        [NativeTypeName("DWORD")]
        public CRED_TYPEType;
```

**Comment by mikebattista** [comment]
@AArnott or @sotteson1 do you know what the issue is here?

**Comment by AArnott** [comment]
> some code generation needs a case handling for types in structs

@alivedevil What do you mean? Is the metadata build failing, or are you saying one of the projections fails when consuming the metadata that includes your changes?

**Comment by AliveDevil** [comment]
Getting type or namespace not found errors when running `BuildMetadataBin.cmd` for
* `IDispatcherQueueController`
* `IPropertyValue`
* `IGraphcsEffectSource`
* `ICompositionSurface`
* `ICompositionGraphicsDevice`
* `IDesktopWindowTarget`
* `ICompositor`
I assume I'm missing some dependency in VS, though 

Regardless:
For me the generated code in `Security.modified.cs` looks invalid. For my modification this is the generated code of `GenerateMetadataSource.cmd`:
```
public unsafe partial struct CREDENTIALA
{
    [NativeTypeName("DWORD")]
    public CRED_FLAGSFlags;

    [NativeTypeName("DWORD")]
    public CRED_TYPEType;
[NativeTypeInfo(UnmanagedType.LPStr, IsNullTerminated = true)]        public sbyte* TargetName;
[NativeTypeInfo(UnmanagedType.LPStr, IsNullTerminated = true)]        public sbyte* Comment;

    public FILETIME LastWritten;

    [NativeTypeName("DWORD")]
    public uint CredentialBlobSize;

    [NativeTypeName("LPBYTE")]
    public byte* CredentialBlob;

    [NativeTypeName("DWORD")]
    public CRED_PERSISTPersist;

    [NativeTypeName("DWORD")]
    public uint AttributeCount;

    [NativeTypeName("PCREDENTIAL_ATTRIBUTEA")]
    public CREDENTIAL_ATTRIBUTEA* Attributes;
[NativeTypeInfo(UnmanagedType.LPStr, IsNullTerminated = true)]        public sbyte* TargetAlias;
[NativeTypeInfo(UnmanagedType.LPStr, IsNullTerminated = true)]        public sbyte* UserName;
}
```
There is no space between the custom mapped enum type and field name for Type, Flags and Persist.

**Comment by AliveDevil** [comment]
The generated C#-code (Security.modified.cs) contains above part for CREDENTIALA and CREDENTIALW-type, making it look impossible to build, as the source is (for me) invalid C# (besides that my local build doesn’t find I
