### ISSUE TITLE
ISpellingError::get_Replacement

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#206]
The out parameter is a UTF16 string (internally) allocated with CoTaskMemAlloc and must be freed by the caller using CoTaskMemFree. This seems like a candidate for another "NativeTypedef" like BSTR and HSTRING, perhaps COSTRING?

spellcheck.h has a few other interfaces with the same pattern that would use this same typedef.

**Comment by kennykerr** [comment]
Alternatively, we could have an attribute that simply indicates that the returned pointer should be freed with `CoTaskMemFree` since there are other types that should be freed with this same function. In that case, we just need to also preserve the fact that this parameter is a UTF16 string and not merely a ushort*.

**Comment by kennykerr** [comment]
Has this been fixed in preview 15? I still see this:

```C#
unsafe HRESULT get_Replacement([Out][RetVal] PWSTR* value);
```

**Comment by sotteson1** [comment]
No, it's not in 15.
