### ISSUE TITLE
All the #define constants in cfgmgr32.h are not represented in metadata

### ISSUE THREAD

**Issue by BertusGreeff** [microsoft/win32metadata#208]
None of the #defines from cfgmgr32.h are present in the metadata.  Is metadata supposed to capture untyped #defines like this?  There are other headers that follow similar patters that also have their #defines missing such as setupapi.h.  Should I file separate issues per header?

Another area of interest is getting all the well know DEVPROPKEY values captured in metadata.

Examples are all the CR_ return values:
```
//
// Configuration Manager CONFIGRET return status codes
//

#define CR_SUCCESS                  (0x00000000)
#define CR_DEFAULT                  (0x00000001)
#define CR_OUT_OF_MEMORY            (0x00000002)
#define CR_INVALID_POINTER          (0x00000003)
#define CR_INVALID_FLAG             (0x00000004)
#define CR_INVALID_DEVNODE          (0x00000005)
#define CR_INVALID_DEVINST          CR_INVALID_DEVNODE
#define CR_INVALID_RES_DES          (0x00000006)
#define CR_INVALID_LOG_CONF         (0x00000007)
#define CR_INVALID_ARBITRATOR       (0x00000008)
#define CR_INVALID_NODELIST         (0x00000009)
#define CR_DEVNODE_HAS_REQS         (0x0000000A)
#define CR_DEVINST_HAS_REQS         CR_DEVNODE_HAS_REQS
#define CR_INVALID_RESOURCEID       (0x0000000B)
#define CR_DLVXD_NOT_FOUND          (0x0000000C)   // WIN 95 ONLY
#define CR_NO_SUCH_DEVNODE          (0x0000000D)
#define CR_NO_SUCH_DEVINST          CR_NO_SUCH_DEVNODE
...
```

**Comment by mikebattista** [comment]
Yes our goal is to convert #define constants like these into friendly enums.

We are exploring some automation to cover a broad set of these. For now, these enums are crafted manually so we don't have broad coverage yet.

**Comment by sotteson1** [comment]
10.0.19041.5-preview.5
