### ISSUE TITLE
`IWbemLocator` missing COM output marker on `ppNamespace` argument

### ISSUE THREAD

**Issue by mbilker** [microsoft/win32metadata#210]
I recently upgraded from `windows-rs` 0.2.1 to 0.3.1 and noticed that many of the WMI generated bindings incorrectly have the COM output pointer arguments interpreted as inputs. To check to make sure this was the case, I put the `Windows.Win32.winmd` into dnSpy to check the mapping on `IWbemLocator`.

```cs
	[Guid("DC12A687-737F-11CF-884D-00AA004B2E24")]
	public interface IWbemLocator : IUnknown
	{
		// Token: 0x0600ABB7 RID: 43959
		unsafe HRESULT ConnectServer([Const] ushort* strNetworkResource, [Const] ushort* strUser, [Const] ushort* strPassword, [Const] ushort* strLocale, int lSecurityFlags, [Const] ushort* strAuthority, IWbemContext pCtx, IWbemServices* ppNamespace);
	}
```

**Comment by kennykerr** [comment]
This is as a result of https://github.com/microsoft/win32metadata/issues/63 - the lack of directional parameter flags.

**Comment by sotteson1** [comment]
Unfortunately we're finding that many of these interfaces don't have an SAL attributes, so we will need to add mappings for them.

**Comment by kennykerr** [comment]
There are going to be a ton of these, so I hope that's not a manual process. 😉 

The headers are generated by MIDL with attributes as follows:

```C++
        virtual HRESULT STDMETHODCALLTYPE GetSessionEnumerator( 
            /* [retval][out] */ IAudioSessionEnumerator **SessionEnum) = 0;
```

Ideally you could parse these comments. Otherwise - since MIDL generates these - perhaps there's an option for MIDL to generate SAL annotations. @defaultryan do you know?

**Comment by sotteson1** [comment]
It looks like if I compile the .idl with /sal_local then I get the SAL annotations. So, the scraper needs to either be able to read the comments or first compile the .idl files into .h files using /sal_local and then scrape the resulting files instead of those in the SDK.

**Comment by sotteson1** [comment]
10.0.19041.5-preview.3 now has these correctly attributed.
