### ISSUE TITLE
IAudioSessionManager2::GetSessionEnumerator parameter should be an output.

### ISSUE THREAD

**Issue by agausmann** [microsoft/win32metadata#213]
The [current signature](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/core_audio/struct.IAudioSessionManager2.html#method.GetSessionEnumerator) of `GetSessionEnumerator`, as of 0.3.1, accepts an `&IAudioSessionEnumerator` or `&Option<IAudioSessionEnumerator>`:

```rust
pub unsafe fn GetSessionEnumerator<'a, T0__: Into<Param<'a, IAudioSessionEnumerator>>>(
    &self,
    session_enum: T0__
) -> ErrorCode
```

However, the [upstream documentation](https://docs.microsoft.com/en-us/windows/win32/api/audiopolicy/nf-audiopolicy-iaudiosessionmanager2-getsessionenumerator) says the parameter "Receives a pointer to the IAudioSessionEnumerator interface", and the [`IAudioSessionEnumerator` code example](https://docs.microsoft.com/en-us/windows/win32/api/audiopolicy/nn-audiopolicy-iaudiosessionenumerator#examples) demonstrates it being used as an out parameter. Therefore I think it should be a `*mut Option<IAudioSessionEnumerator>`

**Comment by kennykerr** [comment]
Transferring this issue to the win32metadata repo.

**Comment by sotteson1** [comment]
10.0.19041.5-preview.3 now has this parameter (and lots of others in APIs) marked with [Out][RetVal].

**Comment by seanyu0** [comment]
I still have the problem even in win32metadata the parameter have [out] and [retval]. In generated code, IAudioSessionManager2::GetSessionEnumerator still have no parameter.

**Comment by kennykerr** [comment]
Rust defines it as follows:

```rust
pub unsafe fn GetSessionEnumerator(&self) -> ::windows_core::Result<IAudioSessionEnumerator>;
```

That looks correct. Be sure to use the latest version of the `windows` crate.

**Comment by seanyu0** [comment]
> Rust defines it as follows:
> 
> ```rust
> pub unsafe fn GetSessionEnumerator(&self) -> ::windows_core::Result<IAudioSessionEnumerator>;
> ```
> 
> That looks correct. Be sure to use the latest version of the `windows` crate.

Thanks. Unfortunately I have this problem in C# and update to newest sdk metadata nuget package.
