### ISSUE TITLE
PAINTSTRUCT rgbReserved field is missing size

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#215]
The definition of `PAINSTRUCT` (see https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-paintstruct) is:
```C
typedef struct tagPAINTSTRUCT {
  HDC  hdc;
  BOOL fErase;
  RECT rcPaint;
  BOOL fRestore;
  BOOL fIncUpdate;
  BYTE rgbReserved[32];
} PAINTSTRUCT, *PPAINTSTRUCT, *NPPAINTSTRUCT, *LPPAINTSTRUCT;
```

However, the win32metadata definition of `PAINTSTRUCT` is missing the length of the `rgbReserved` array field:
```C#
public struct PAINTSTRUCT
{
	public HDC hdc;
	public BOOL fErase;
	public RECT rcPaint;
	public BOOL fRestore;
	public BOOL fIncUpdate;
	public byte[] rgbReserved;
}
```

Granted the Clr doesn't support statically sized arrays like C/C++.  However, as I understand from looking at other examples, this information can be represented using `NativeTypeInfoAttribute.SizeConst` (along with `LPArray` as the `UnmanagedType`).  I expect it would look something like this:

```C#
public struct PAINTSTRUCT
{
	public HDC hdc;
	public BOOL fErase;
	public RECT rcPaint;
	public BOOL fRestore;
	public BOOL fIncUpdate;
        [NativeTypeInfo(UnmanagedType.LPArray, SizeConst = 32)]
	public byte[] rgbReserved;
}
```

**Comment by AArnott** [comment]
> Granted the Clr doesn't support statically sized arrays like C/C++.

It does, actually. C# as a language has only limited support so when "decompiling" the metadata to C# you don't see it, but indeed the metadata does reflect the 32-byte fixed length of the inline array:

![image](https://user-images.githubusercontent.com/3548/107380616-4127a080-6aab-11eb-9960-752ea4e9db05.png)

When reading the metadata, be sure to use a parser that recognizes this.

**Comment by marler8997** [comment]
I stand corrected. Thanks for the info.

**Comment by marler8997** [comment]
I've found this this size information is available in the C# MetadataReader via the `ArrayShape` struct associated with the field type.  However, it seems odd that this information is not reported by ILSpy, maybe an issue should be filed for ILSpy to report `ArrayShape` information?  Then again, since ILSpy decompiles to C#, there's no way to represent this information in the language, so it might have to be in the form of a comment in the decompiled code?  Does this seem like a reasonable course or maybe it's not a big deal?

**Comment by AArnott** [comment]
The screenshot I included above comes from ILSpy. 
But yes, in C# decompiler mode, it could only express it as a code comment. Feel free to file a request against ILSpy separately.

**Comment by marler8997** [comment]
Oh I didn't know ILSpy had different decompile modes. Thanks for that.
