### ISSUE TITLE
Missing constants for SHChangeNotify arguments

### ISSUE THREAD

**Issue by jorgenpt** [microsoft/win32metadata#218]
I was attempting to call [SHChangeNotify](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shchangenotify), and while I can find the binding in [`windows::win32::shell::SHChangeNotify`](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/shell/fn.SHChangeNotify.html), I couldn't find the constants for the arguments declared anywhere. Specifically I was looking for constants like `SHCNF_FLUSH` and `SHCNE_ASSOCCHANGED`. I did search through https://microsoft.github.io/windows-docs-rs/doc/bindings/all.html without luck. Do these exist and I'm just missing them, or are the constants missing?

**Comment by sotteson1** [comment]
Fixed with 10.0.19041.5-preview.5.
