### ISSUE TITLE
JOBOBJECT_BASIC_LIMIT_INFORMATION flags are missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#219]
The flags for [the `JOBOBJECT_BASIC_LIMIT_INFORMATION` struct](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_basic_limit_information) are not in the metadata.

**Comment by sotteson1** [comment]
Fixed with 10.0.19041.5-preview.5.
