### ISSUE TITLE
HeapFree method is missing a flags enum

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#22]
The [HeapFree documentation](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapfree) define a flags parameter for which no enum is defined in the metadata.

We need either a flags enum or metadata to identify which constants may be used so we can create the enum in the projection. 
In this case, the `HEAP_NO_SERIALIZE` constant is not even found in the metadata anywhere.

**Comment by sotteson1** [comment]
This has since been fixed.
