### ISSUE TITLE
Missing constant values for KNOWNFOLDERID

### ISSUE THREAD

**Issue by jorgenpt** [microsoft/win32metadata#220]
The values for [KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid) do not seem to be included. E.g. `FOLDERID_LocalAppData`.

**Comment by AArnott** [comment]
These are guids, which I don't believe are a valid base type for enums. The best we could do here might be to collect them as static readonly fields on a static class named `KnownFolders`.

**Comment by jorgenpt** [comment]
@AArnott, that makes sense. I renamed the issue to be consistent with that.
