### ISSUE TITLE
Direct3D9 interfaces

### ISSUE THREAD

**Issue by pudingus** [microsoft/win32metadata#222]
The IDirect3D* interfaces and their methods from d3d9.h and functions `Direct3DCreate9`, `Direct3DCreate9Ex` are missing.

**Comment by sotteson1** [comment]
Are you sure? I'm looking at the latest version 10.0.19041.5-preview.4 and I see all of those using ilspy.exe. Which version of the metadata are you looking at, and what are you using to look for the types?

**Comment by kennykerr** [comment]
These APIs appear to be incorrectly nested in the `Windows.Win32.Direct2D` namespace.

**Comment by pudingus** [comment]
Oh you are right, they are in the wrong namespace

**Comment by sotteson1** [comment]
Oops, bad data in one of my files. This is an easy fix.

**Comment by sotteson1** [comment]
10.0.19041.5-preview.5
