### ISSUE TITLE
Fix signature for EnumDesktopProc callback 

### ISSUE THREAD

**Issue by LGUG2Z** [microsoft/win32metadata#223]
The CPP documentation specifies that this callback should have two arguments: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms682612(v=vs.85)

The equivalent function in this crate does not take any arguments: https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/menus_and_resources/type.DESKTOPENUMPROCW.html

**Comment by LGUG2Z** [comment]
Thanks for the quick response! Related to this, there may also be a bug in the metadata regarding one of the arg types for this callback, `LPTSTR`, which also doesn't appear in the windows crate docs right now: https://microsoft.github.io/windows-docs-rs/doc/bindings/index.html?search=LPTSTR

**Comment by sotteson1** [comment]
> Confirmed this is a bug in the metadata. Also, the delegate should probably be called `EnumDesktopProc` - rather than `DESKTOPENUMPROC` - since that's what its called in the docs.
> 
> Transferring this issue to the metadata repo.

The typedef is the all-caps name as per the docs, which is what's in the header too:

"The DESKTOPENUMPROC type defines a pointer to this callback function. EnumDesktopProc is a placeholder for the application-defined function name."

I'll fix the signatures which are wrong, though.

**Comment by sotteson1** [comment]
Fixed with 10.0.19041.5-preview.5.
