### ISSUE TITLE
Missing Authentication and Impersonation Levels

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#226]
Missing Authentication Levels enum from https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rpce/425a7c53-c33a-4868-8e5b-2a850d40dc73

Name | Value | Meaning
-- | -- | --
RPC_C_AUTHN_LEVEL_DEFAULT | 0x00 | Same as RPC_C_AUTHN_LEVEL_CONNECT
RPC_C_AUTHN_LEVEL_NONE | 0x01 | No authentication.
RPC_C_AUTHN_LEVEL_CONNECT | 0x02 | Authenticates the credentials of the client and server.
RPC_C_AUTHN_LEVEL_CALL | 0x03 | Same as RPC_C_AUTHN_LEVEL_PKT.
RPC_C_AUTHN_LEVEL_PKT | 0x04 | Same as RPC_C_AUTHN_LEVEL_CONNECT but also prevents replay attacks.
RPC_C_AUTHN_LEVEL_PKT_INTEGRITY | 0x05 | Same as RPC_C_AUTHN_LEVEL_PKT but also verifies that none of the data transferred between the client and server has been modified.
RPC_C_AUTHN_LEVEL_PKT_PRIVACY | 0x06 | Same as RPC_C_AUTHN_LEVEL_PKT_INTEGRITY but also ensures that the data transferred can only be seen unencrypted by the client and the server.

Also missing Impersonation Levels enum from https://docs.microsoft.com/en-us/windows/win32/com/com-impersonation-level-constants

Constant/value | Description
-- | --
RPC_C_IMP_LEVEL_DEFAULT `0` | DCOM can choose the impersonation level using its normal security blanket negotiation algorithm. For more information, see Security Blanket Negotiation.
RPC_C_IMP_LEVEL_ANONYMOUS `1` | The client is anonymous to the server. The server process can impersonate the client, but the impersonation token will not contain any information and cannot be used.
RPC_C_IMP_LEVEL_IDENTIFY `2` | The server can obtain the client's identity. The server can impersonate the client for ACL checking, but it cannot access system objects as the client.
RPC_C_IMP_LEVEL_IMPERSONATE `3` | The server process can impersonate the client's security context while acting on behalf of the client. This level of impersonation can be used to access local resources such as files. When impersonating at this level, the impersonation token can only be passed across one machine boundary. The Schannel authentication service only supports this level of impersonation.
RPC_C_IMP_LEVEL_DELEGATE `4` | The server process can impersonate the client's security context while acting on behalf of the client. The server process can also make outgoing calls to other servers while acting on behalf of the client, using cloaking. The server may use the client's security context on other machines to access local and remote resources as the client. When impersonating at this level, the impersonation token can be passed across any number of computer boundaries.

**Comment by AArnott** [comment]
@marler8997 which APIs do you expect to use enums that would contain these constants?

**Comment by marler8997** [comment]
The one I was using was CoInitializeSecurity (https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializesecurity)
