### ISSUE TITLE
Outdated D3D9 structs and enums

### ISSUE THREAD

**Issue by pudingus** [microsoft/win32metadata#227]
Some structs and enums from d3d9types.h in the Direct3D9 partition are being explicitly excluded in favor of types from d3dtypes.h (Base partition) with the same name, but that header is from DirectX 3 - 7 era and there are a lot of members missing and with old names.
That also begs the question why is it even in the SDK when d3d8 isn't.

And also `D3DCONTENTPROTECTIONCAPS` and `D3DOVERLAYCAPS` are from d3d9caps.h, so I believe they are put in `Windows.Win32.MediaFoundation` namespace incorrectly.

**Comment by mikebattista** [comment]
Thanks for filing. We'll take a look.

**Comment by pudingus** [comment]
Thank you as well for this awesome project!

**Comment by weltkante** [comment]
Also the actual D3D9 interfaces ended up in the Direct2D namespace, instead of the Direct3D9 namespace. Seems the D3D9 generator is currently broken.

Having outdated definitions in the Direct3D9 namespace and interfaces/structs ending up in the Direct2D namespace may be related, but if you want me to open a separate issue for the latter I can do that.

**Comment by sotteson1** [comment]
Hi @pudingus, it sounds like I shouldn't even be scraping d3dtypes.h. Do you agree with that?

**Comment by sotteson1** [comment]
> And also `D3DCONTENTPROTECTIONCAPS` and `D3DOVERLAYCAPS` are from d3d9caps.h, so I believe they are put in `Windows.Win32.MediaFoundation` namespace incorrectly.

The docs has them in Media Foundation, which is why we put them in there. See: https://docs.microsoft.com/en-us/windows/win32/api/d3d9caps/ns-d3d9caps-d3dcontentprotectioncaps

**Comment by sotteson1** [comment]
> Having outdated definitions in the Direct3D9 namespace and interfaces/structs ending up in the Direct2D namespace may be related, ~but if you want me to open a separate issue for the latter I can do that~.

Are you still using D3D9 stuff in the Direct2D namespace? I looked and didn't see any, but maybe I'm missing something. Let me know what you're seeing that seems wrong.

**Comment by weltkante** [comment]
> Are you still seeing D3D9 stuff in the Direct2D namespace?

No, the namespace issue seems to have been fixed as a side effect of something else I assume.

**Comment by sotteson1** [comment]
> Some structs and enums from d3d9types.h in the Direct3D9 partition are being explicitly excluded in favor of types from d3dtypes.h (Base partition) with the same name, but that header is from DirectX 3 - 7 era and there are a lot of members missing and with old names.
> That also begs the question why is it even in the SDK when d3d8 isn't.
> 
I tried removing d3dtypes.h but it's used by d3dhal.h. I'm not sure how important is to keep both of them around. But, I try favoring the definitions from d3d9types.h over d3dtypes.h. Are there types you see from d3dtypes.h that you think shouldn't belong in the metadata?

**Comment by weltkante** [comment]
> That also begs the question why is it even in the SDK when d3d8 isn't.

Also just for the record, I'd prefer the basic D3D9 stuff to not be removed entirely, its needed e.g. for WPF interop which doesn't support higher D3D versions yet. I don't really know about `d3dhal.h` though, so as long as the basic D3D9 device & resource interfaces are mapped along with whatever they need in their methods I'm probably fine.
