### ISSUE TITLE
Windows.Win32.ProcessStatus APIs incorrectly named

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#229]
The APIs in this scope are named with a `K32` prefix, but they are documented (and called) without the prefix. 

For example, see [`EnumProcesses`](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocesses), which is in the metadata as `K32EnumProcesses`.

ILSpy over Win32 metadata:

```
// Windows.Win32.ProcessStatus.Apis

[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
public static class Apis
{
	[DllImport("KERNEL32", ExactSpelling = true)]
	public unsafe static extern BOOL K32EnumProcesses
                ([Out][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 1)] uint* lpidProcess, 
                [In] uint cb, [Out] uint* lpcbNeeded);
}
```

Documented API:

```c
BOOL EnumProcesses(
  DWORD   *lpidProcess,
  DWORD   cb,
  LPDWORD lpcbNeeded
);
```

**Comment by sotteson1** [comment]
In the header EnumProcesses is a #define that maps to K32EnumProcesses, which is the real API name.

```C
#define EnumProcesses               K32EnumProcesses
#define GetProcessMemoryInfo        K32GetProcessMemoryInfo
#define GetModuleInformation        K32GetModuleInformation
#define GetModuleBaseNameA          K32GetModuleBaseNameA
#define GetModuleBaseNameW          K32GetModuleBaseNameW
#define GetModuleFileNameExA        K32GetModuleFileNameExA
#define GetModuleFileNameExW        K32GetModuleFileNameExW
```

The export would need to look like:

```C#
[DllImport("KERNEL32", EntryPoint = "K32EnumProcesses")]
public unsafe static extern BOOL EnumProcesses([Out][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 1)] uint* lpidProcess, [In] uint cb, [Out] uint* lpcbNeeded);
```

We need to make sure the language projections know how to handle that.

**Comment by kennykerr** [comment]
That should be fine.

**Comment by timsneath** [comment]
I think that makes sense. They're also exported from psapi.dll, which is where I load them from today, but there's some versioning weirdness as documented here: https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocesses

![image](https://user-images.githubusercontent.com/2319867/109235444-870a8700-7782-11eb-8def-905f4d5c9fd8.png)

**Comment by timsneath** [comment]
Closing as a dupe of #920
