### ISSUE TITLE
Functions questionably needing mutable strings

### ISSUE THREAD

**Issue by 1Dragoon** [microsoft/win32metadata#231]
Some functions that I'm using are asking for a mutable string where it doesn't make a lot of sense, I'm not sure whether this is a bug. Take for example:

```rust
        let mut filter: Vec<u16> = "(&(objectCategory=Person)(sAMAccountName=jsmith))".encode_utf16().collect();
        filter.push(0);

        let a: Vec<u16> = "description".encode_utf16().collect();
        a.push(0);
        let mut attr = [a];
        let mut hsearch: isize = 0;

        let dsearcher: IDirectorySearch = dsearcher.unwrap();

        let hr = dsearcher.ExecuteSearch(
            filter.as_mut_ptr(),
            attr.as_mut_ptr() as _,
            1,
            &mut hsearch
        );

        let mut col = ads_search_column::default();
        
        dsearcher.GetNextRow(hsearch).ok()?;
        dsearcher.GetColumn(
            hsearch,
            a.as_mut_ptr(),
            &mut col
        );
```

I don't think the method is going to modify those strings or the pointers. However, if it has to be that way, I initially was using HString::as_wide() which yields a borrowed value, so it can't be used here as it can't be made into .as_mut_ptr(), thus I went back to using &str::encode_utf16(). So could we get maybe an HString::into_wide() to yield an owned null terminated u16?

**Comment by 1Dragoon** [comment]
@kennykerr thanks! By the way, would getting an owned wide string from HString be out of scope for that struct?

Also to the maintainers of win32metadata, a few other methods are impacted by this, like IDirectorySearch::GetColumn's second param, and some others that I can't recall at the moment.

**Comment by sotteson1** [comment]
The in/out on these parameters look right now. There was some work a while back to better scrape the .idl files, so it looks like that worked fixed this issue. If you see others that look incorrect let me know.
