### ISSUE TITLE
CoTaskMemAlloc and CoTaskMemFree

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#232]
`CoTaskMemAlloc` returns a `void*` but `CoTaskMemFree` expects an `IntPtr`. These should be consistent. I'd vote for `void*` since it's a pointer and not a size.

**Comment by sotteson1** [comment]
I'm not seeing this on 10.0.19041.5-preview.20.

```C#
public unsafe static extern void* CoTaskMemAlloc([In] UIntPtr cb);
public unsafe static extern void CoTaskMemFree([Optional] void* pv);
```
