### ISSUE TITLE
OLECHAR missing NativeTypeInfo attribute

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#233]
`OLECHAR *` and `LPWSTR` are essentially the same thing:

```c
typedef _Null_terminated_ WCHAR *NWPSTR, *LPWSTR, *PWSTR;
typedef WCHAR OLECHAR;
```

However, while parameters typed `LPWSTR` have a `NativeTypeInfo` attribute that indicates a Unicode string, `OLECHAR *` parameters are simply expressed as `ushort *`, which makes it hard for projections to identify them as string types. 

See, for example, `SysAllocString`:

```c
BSTR SysAllocString(
  const OLECHAR *psz
);
```

which is represented in metadata as:
```
[DllImport("OLEAUT32", ExactSpelling = true)]
public unsafe static extern BSTR SysAllocString([Optional][In][Const] ushort* psz);
```

versus `FindExecutable`, which has the necessary type info:

```
[DllImport("SHELL32", ExactSpelling = true)]
public unsafe static extern HINSTANCE FindExecutableW(
  [In][Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* lpFile, 
  [Optional][In][Const][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* lpDirectory, 
  [Out][NativeTypeInfo(UnmanagedType.LPWStr, IsNullTerminated = true)] ushort* lpResult);
```

**Comment by sotteson1** [comment]
Fixed in latest release.
