### ISSUE TITLE
strongly typed HBITMAP

### ISSUE THREAD

**Issue by rumbu13** [microsoft/win32metadata#234]
HBITMAP is declared as struct in WindowsWin32.Gdi:

```
[RAIIFree("DeleteObject")]
[NativeTypedef]
public struct HBITMAP
{
  public IntPtr Value;
}
```

On the contrary, in Windows.Win32.SystemServices.Apis we have integer contants:

```
public const HBITMAP HBMMENU_CALLBACK = -1;
public const HBITMAP HBMMENU_SYSTEM = 1;
public const HBITMAP HBMMENU_MBAR_RESTORE = 2;
public const HBITMAP HBMMENU_MBAR_MINIMIZE = 3;
public const HBITMAP HBMMENU_MBAR_CLOSE = 5;
public const HBITMAP HBMMENU_MBAR_CLOSE_D = 6;
public const HBITMAP HBMMENU_MBAR_MINIMIZE_D = 7;
public const HBITMAP HBMMENU_POPUP_CLOSE = 8;
public const HBITMAP HBMMENU_POPUP_RESTORE = 9;
public const HBITMAP HBMMENU_POPUP_MAXIMIZE = 10;
public const HBITMAP HBMMENU_POPUP_MINIMIZE = 11;
```

I wonder how this is even possible.

**Comment by sotteson1** [comment]
HBITMAP follows the Win32 handle pattern. Handles in Win32 are usually the same size as a pointer, which in metadata is IntPtr. But we wanted to preserve strong types in the metadata, so you will see a similar pattern for lots of handle types in the metadata. If we didn't do that, all handle types would just be IntPtr and the types would get lost in the language projections.

In the case of HBITMAP, those constants act like magic numbers to the internal Windows code that deals with HBITMAPs. When it sees those numbers, it knows to treat them differently than it would a real HBITMAP which points to real bitmap data.

**Comment by rumbu13** [comment]
I understood the idea, but if you change the HBITMAP semantics, you must change also the constant semantics. The following code is illegal in C#, that's why I am wondering how is this even possible to declare it in metadata.

```
struct HBITMAP
{
    IntPtr value;
}
class Apis
{
    public const HBITMAP HBMMENU_SYSTEM = 1;
}

//CS0283 The type HBITMAP cannot be declared const.
//CS0289 Canoot implicitely convert type 'int' to 'HBITMAP'

```

The correct code should be:

```
class Apis
{
        public static readonly HBITMAP HBMMENU_SYSTEM = new HBITMAP { value = new IntPtr(1) };
}
```

**Comment by sotteson1** [comment]
Yes, you've got that right. We will have to represent that in metadata, although we don't yet.

**Comment by sotteson1** [comment]
Metadata can do things that C# can't. It would be up to the C# projection to project that in the way that is usable in C#, like in your second example.
