### ISSUE TITLE
Attribute store-banned APIs

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#238]
We need to know which APIs are banned from Windows Store apps so that projections can omit these when we know the compilation will be run through the API scanner for Store submission.

**Comment by kennykerr** [comment]
For the millionth time, we could just stop banning APIs. 😉

**Comment by AArnott** [comment]
If we can do that retroactively for Win8 apps too, that would be fine. But we should do one or the other so that `dotnet/pinvoke` can switch to this.

**Comment by AdamBraden** [comment]
While we should stop banning apis, we need *something* that helps an app run on different windows devices and highlights unsupported/missing apis on those devices. Granted that wouldn't be an issue for most desktop apps, but if you wanted to take that app to xbox, hololens or other devices.

**Comment by AArnott** [comment]
See also #279

**Comment by mikebattista** [comment]
Closing out as this is not a priority to address.

**Comment by riverar** [comment]
Also, the Microsoft Store happily accepts any API now (at least for centennial apps) in my experience.
