### ISSUE TITLE
dbghelp.h structs like LOADED_IMAGE (and methods?) are missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#239]
The [`LOADED_IMAGE` struct](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/ns-dbghelp-loaded_image) is missing from the metadata.

**Comment by timsneath** [comment]
I'm also seeing that the APIs themselves are missing -- `SymLoadModuleEx`, `SymEnumSymbols` etc.
