### ISSUE TITLE
Methods from MSCorEE missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#240]

**Comment by timsneath** [comment]
Just to add, this includes some COM interfaces: `IMetaDataDispenser`, `IMetaDataDispenserEx`, `IMetaDataImport` and `IMetaDataImport2`; ironically, these are what I need to parse the .winmd file itself. If these are added, I'll be able to remove all manual IDL parsing for COM objects and rely entirely on Win32Metadata for this purpose!

**Comment by kennykerr** [comment]
That's very meta. 😉

**Comment by sotteson1** [comment]
@AArnott, it looks like that lib is part the .NET SDK and not part of the Windows SDK. We haven't yet pulled in anything from outside the WinSDK into the metadata. @timsneath, the APIs you mentioned are in one of the WinSDK WinRT headers, but they require cor.h to be used which is in the .NET SDK.

**Comment by AArnott** [comment]
Ok. Shall we close this as out of scope then? It means we'll have to keep MSCorEE hand-authored in dotnet/pinvoke.

**Comment by timsneath** [comment]
Alternatively, is there any way that we could point the
GenerateMetadataSource tool at this folder somehow?

The header files are in CorHdr.h, certainly -- but the functions are in the
Windows directory, as far as I can make out:

https://docs.microsoft.com/en-us/windows/win32/api/rometadata/nf-rometadata-metadatagetdispenser

points to Rometadata.dll, which is in \Windows\System32 on my machine at
least.

**Comment by timsneath** [comment]
Just for the record, also, you acquire these interfaces from [`RoGetMetaDataFile`](https://docs.microsoft.com/en-us/windows/win32/api/rometadataresolution/nf-rometadataresolution-rogetmetadatafile), which is decidedly part of the Win32 API. The documentation is part of the Win32 API, the files are in the Windows folder, the header file is in the Windows SDK.

**Comment by weltkante** [comment]
I think the discussion is mixing up the Desktop Framework "mscoree" metadata API and the WinRT metadata API? "mscoree" sounds like the Desktop Framework API which lives outside the Windows SDK, but considering Desktop Framework is part of Windows I'd very much welcome it being included. There is also #305 which is asking for .NET Desktop Framework APIs.

**Comment by russcam** [comment]
> There is also #305 which is asking for .NET Desktop Framework APIs.

The Profiling APIs are for both Desktop CLR (Windows) and Core CLR (Cross-platform) 🙂 Not sure if this would have a bearing on inclusion, but I would also very much welcome them being included.

**Comment by weltkante** [comment]
Considering Core CLR headers are deployed separately I'd assume they need a separate project (or at least nuget package), unlike Desktop Framework they aren't going to be versioned with Windows anymore, might be hard to include them in `win32metadata` package/project because it requires updates whenever the dotnet runtime updates its headers.

**Comment by timsneath** [comment]
I just want to be clear that I'm talking about rometadata.dll, which is very much part of Windows, and Windows APIs like https://docs.microsoft.com/en-us/windows/win32/api/rometadataresolution/nf-rometadataresolution-rogetmetadatafile and https://docs.microsoft.com/en-us/windows/win32/api/rometadata/nf-rometadata-metadatagetdispenser. This has nothing to do with .NET or the CLR. 

Let me know if I need to open a new bug to disambiguate this?

**Comment by weltkante** [comment]
I think we have seen three separate requests in this issue
- mscoree (Desktop Framework, updated together with Windows, but the headers are in a separate folder not in the SDK, probably because historically it was installed and updated seperately)
- WinRT metadata API (part of Windows)
- .NET Core COM API (updated separately)

I may be mistaken but I think the WinRT metadata API is distinct from the Desktop Framework implementation, so depending on scenario either may be required. Desktop Framework of course came first, and I wonder if WinRT reusing the same names causes any compatibility problems (i.e. whether anything is defined differently between the mscoree headers and the WinRT winmd file)

**Comment by triniwiz** [comment]
Not sure if this is the best place (issue) to ask but I’ll do it since someone asked already, but I’d love to see `IMetaDataImport2`, `RoGetMetaDataFile` and others from `rometadataapi.h`. ( I was redirected to here from windows-rs)

**Comment by mikebattista** [comment]
With #468 I added a pattern for APIs that ship outside the Windows SDK but are tightly coupled and should be included here.

Check in the file to https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/AdditionalHeaders and also in https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/RecompiledIdlHeaders/um. The script we use to ingest new SDKs was also updated to copy over AdditionalHeaders but you don't need to run that if you just copy the files to both places.

Once the headers are in place, you should be able to include them in partitions like any other headers.

**Comment by mikebattista** [comment]
I got this working. Take a look at [the diff](https://github.com/microsoft/win32metadata/commit/0eb11853233d1d2d7dc012b40ebfd53d2270d791#diff-55fb5d5eced0797538c3656ccb571f46d8b46bddc0688f66ea459a6499e148fa) and let me know what you think.

**Comment by AArnott** [comment]
Thanks. I took a look at the diff.

Why would mscoree headers (a .NET Framework thing) get bucketed in the WinRT namespace, which came much later and has nothing to do with .NET Framework?
Or, if these aren't .NET Framework headers, why did this issue get closed with this PR?

**Comment by mikebattista** [comment]
These were missing Windows rometadata APIs which were already in the WinRT namespace.

**Comment by kennykerr** [comment]
I would put these in a nested namespace like `WinRT.Metadata` since they're hardly ever needed (I never use them) whereas the WinRT types are often needed by WinRT interop APIs.

**Comment by AArnott** [comment]
Then was mscoree even added by that commit? 

Just as an example, the function `GetRequestedRuntimeInfo` is exported from MSCorEE but doesn't appear in the diff's `ChangesSinceLastRelease.txt` file.

**Comment by mikebattista** [comment]
I changed the title of this bug to reflect the scope. The discussion conflated several scenarios. Please file a separate issue for anything else.

**Comment by AArnott** [comment]
I filed this issue in the first place, to track mscoree. It seems very odd that conflation occurred and now I have to file another issue for the same purpose. It seems like another issue should have been filed to track the conflation. But oh well. Sure. I'll file another issue.

**Comment by mikebattista** [comment]
Add a description with more details on the APIs you want. rometadata had clear ties to the Windows SDK. I'm not sure about what other scenarios you want and if they should be in here.

**Comment by kennykerr** [comment]
I thought this issue was about the RoMetadata.dll APIs - these are APIs that were originally provided by the .NET team but ship inside the OS to support WinRT.

**Comment by kennykerr** [comment]
We see what we want to see. 🤣
