### ISSUE TITLE
public user-mode Rtl functions not being generated

### ISSUE THREAD

**Issue by vatsan-madhavan** [microsoft/win32metadata#242]
Here are two examples. 

They're [both ](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlgetversion)[documented](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlverifyversioninfo) and available for use in user-mode applications, but CsWin32 doesn't seem to know how to generate these yet. 

```
\NativeMethods.txt(1,1): warning PInvoke001: Method or type "RtlGetVersion" not found. 
\NativeMethods.txt(2,1): warning PInvoke001: Method or type "RtlVerifyVersionInfo" not found. 
```

**Comment by sotteson1** [comment]
These are kernel mode APIs according to the docs. We're not currently supporting kernel mode APIs.

**Comment by vatsan-madhavan** [comment]
These are dual use API’s. We use them often in user mode because they’re designed to be used as such. 

In fact, we even explain how the dual-use is intended to work through ntdll.lib (for user mode) at https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/libraries-and-headers
