### ISSUE TITLE
Attribute to distinguish length of array in bytes vs element count 

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#243]
The [`VirtualQueryEx` method](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualqueryex)'s last parameter takes the length of the previous parameter *in bytes*, but the attribute on the previous parameter is equivalent to (and interpreted by CsWin32 as) how we annotate parameters for length of array _by element count_.

We need distinguishing metadata for the two cases: length of array in bytes vs length in element count.

As @Schwertregen reported in https://github.com/microsoft/CsWin32/issues/90.

**Comment by sotteson1** [comment]
Fixed in latest release.
