### ISSUE TITLE
CONTEXT structure is generated in x86 instead of x64

### ISSUE THREAD

**Issue by bastiflew** [microsoft/win32metadata#245]
The `CONTEXT` structure is generated with x86 registries instead of the x64 registries.
The expected result: https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-context

The project I'm using is in .NET 5.0, and the platform target is x64.

**Comment by AArnott** [comment]
The metadata should include the data sufficient to allow for projections to emit a unique struct based on the target architecture of the receiving project.

**Comment by sotteson1** [comment]
This has now been changed to 64 bit, but we also need a way to include both versions so that projections can project both 32 and 64 bit versions. See #384.
