### ISSUE TITLE
OLD_LARGE_INTEGER

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#246]
Can the metadata just remap this directly to `LARGE_INTEGER` (if its even used anywhere)? I can't think of a reason we'd want to include this. It appears to only be used to fix up some weird MIDL compiler issue:

```C++
#ifndef _DOMAIN_PASSWORD_INFORMATION_DEFINED
#define _DOMAIN_PASSWORD_INFORMATION_DEFINED
typedef struct _DOMAIN_PASSWORD_INFORMATION {
    USHORT MinPasswordLength;
    USHORT PasswordHistoryLength;
    ULONG PasswordProperties;
#if defined(MIDL_PASS)
    OLD_LARGE_INTEGER MaxPasswordAge;
    OLD_LARGE_INTEGER MinPasswordAge;
#else
    LARGE_INTEGER MaxPasswordAge;
    LARGE_INTEGER MinPasswordAge;
#endif
} DOMAIN_PASSWORD_INFORMATION, *PDOMAIN_PASSWORD_INFORMATION;
#endif
```

**Comment by AArnott** [comment]
FWIW, CsWin32 already maps this directly to `long`.

**Comment by kennykerr** [comment]
Yes I map LARGE_INTEGER the same way in Rust. I'd just like to keep that list as short as practical.
