### ISSUE TITLE
Release methods need semantic understanding

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#25]
In order to invoke the release methods properly, we need to understand whether they were successful. But they're all over the map on this. For example:

- `bool` [`FindClose`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findclose) returns non-zero (true) on success.
- `NTSTATUS` [`LsaDeregisterLogonProcess`](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-lsaderegisterlogonprocess) returns zero (`STATUS_SUCCESS`) on success.
- `DWORD` [`WNetCloseEnum`](https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetcloseenum) returns zero on success.
- `LSTATUS` [`RegCloseKey`](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regclosekey) returns zero on success.
- `byte` [`ClosePrivateNamespace`](https://docs.microsoft.com/en-us/windows/win32/api/namespaceapi/nf-namespaceapi-closeprivatenamespace) returns non-zero on success.

These is just a sampling. For each method, we need to know what constitutes success.

**Comment by Robo210** [comment]
I believe the release methods will also need to understand what constitutes a "invalid" or sentinel value as well. Some APIs use NULL while others use INVALID_HANDLE_VALUE, and the two aren't always equivalent (but sometimes they are). If a safe handle needs to condition the close on whether the handle value is valid, it will need to know what an invalid handle looks like.

[WIL's unique_any](https://github.com/microsoft/wil/blob/86353933d5fba0caf61503c8b09e10e182dccdfb/include/wil/resource.h#L417) is a good example of all the data that's actually required to build a safe handle around the numerous Win32 handle types.

**Comment by AArnott** [comment]
`ReleaseDC` is another odd case that takes two parameters.
