### ISSUE TITLE
GetDC incorrectly returns, and DrawIconEx incorrectly requires, a safe handle that calls DeleteDC instead of ReleaseDC

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#251]
Related, possible solution: https://github.com/microsoft/CsWin32/issues/111

[`GetDC`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdc) is paired with `ReleaseDC`, not `DeleteDC`.

[`DrawIconEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-drawiconex) and probably all other APIs taking hdc parameters do not care what kind of DC you pass it, so DeleteDC/ReleaseDC should not be encoded into the names of the types used by any of their parameters.

**Comment by sotteson1** [comment]
Ugh, CreateDC needs DeleteDC, and GetDC needs ReleaseDC. Any suggestions on how to represent that?

**Comment by AArnott** [comment]
I vaguely recall a proposal I made for expressing a hierarchy of handles in the metadata, such that projections could try to make them look polymorphic while still treating them differently. It might have been in the GDI context.
But as there are just two types here and no obvious "parent", yet all the consumers may accept either one, it seems we should create a name for a 'base' handle and use it for all inputs in the metadata. Then for the two "derived" handles, which are never used except as return types, we attribute these derived handle types with their base handle name so projections can make sure a derived handle can be used where the base handle appears as input.

**Comment by sotteson1** [comment]
Yeah, that makes sense. You could also use one as the base type and have the other be derived from it. It would be like overriding the destructor with the correct close function.

```C#
[RAIIFree("ReleaseDC")]
[NativeTypedef]
public struct HDC
{
	public IntPtr Value;
}

[RAIIFree("DeleteDC")]
[IsA("HDC")]
[NativeTypedef]
public struct HDC2
{
	public IntPtr Value;
}

HDC hdc = GetDC()
HDC2 hdc2 = CreateDC()

BitBlt(hdc, ...)
BitBlt(hdc2, ...)
```

So HDC2 "is a" HDC and can be used in the same places as HDC.

**Comment by AArnott** [comment]
Right. Technically structs can't derive from other structs in C# (or ECMA AFAIK), but let the projections worry about that.

**Comment by sotteson1** [comment]
It could also be implemented as an operator from one to another. Maybe the attribute could be called "ConvertsTo"?

**Comment by kennykerr** [comment]
Rust also doesn't support inheritance of any kind so an attribute would be preferable.

**Comment by AArnott** [comment]
> Maybe the attribute could be called "ConvertsTo"

That invites the question : "ok, *how?*"

No conversion is necessary. So how about `AlsoUsableForAttribute`?

**Comment by sotteson1** [comment]
I'm fine with that name.
