### ISSUE TITLE
DuplicateHandle should take a *mut HANDLE argument for lp_target_handle

### ISSUE THREAD

**Issue by zaddach** [microsoft/win32metadata#252]
The fourth argument of `DuplicateHandle` is currently a `*mut isize`, but should be a `*mut HANDLE`.

https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/windows_programming/fn.DuplicateHandle.html

**Comment by kennykerr** [comment]
In the original metadata, the `lpTargetHandle` parameter is `IntPtr*` when it should be `HANDLE*`.
