### ISSUE TITLE
Remove ComOutPtrAttribute 

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#257]
Per the conversation in #37, it sounds like `ComOutPtrAttribute` no longer serves a purpose. Yet its application is inconsistent. Shall we remove it, leaving just `[Out]` where it used to be applied to make projections' life easier?

**Comment by sotteson1** [comment]
ComOutPtr comes from a SAL annotation that API owners have applied inconsistently, like you said. One place I wonder if it's still useful is for when APIs have added it to void** parameters to show that what's coming out is a COM pointer. If you would rather just have that as "out" I can convert "COM out" to just be "out".

**Comment by AArnott** [comment]
Good point. Yes for `void**` we should keep it. That will allow CsWin32 to type it as `out object` when we have proper COM interface support.

**Comment by kennykerr** [comment]
Sounds good, but should we remove it for all but `GUID*, void**` parameters?

**Comment by AArnott** [comment]
meh. That sounds like work, and as we have to handle the attribute either way, I'm not sure it buys us anything.

**Comment by kennykerr** [comment]
😁 just trying to preempt confusion...

Question: "hey what should I do with this attribute on the `IConcrete*` out parameter?" 
Answer: "Nothing, its only meaningful in this other scenario."

**Comment by AArnott** [comment]
"Nothing" isn't quite the right answer though, is it? It should *always* be interpreted at least like an `[Out]` attribute.

**Comment by kennykerr** [comment]
Well, all parameters should have explicit in/out flags (#63) so this seems redundant.
