### ISSUE TITLE
Should BITMAPINFOHEADER.biCompression be an enum?

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#261]
The only value I want to use is `BI_RGB = 0`, but other constants exist such as `BI_BITFIELDS`, `BI_RLE8`, `BI_PNG`, etc.

https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader#members says that any DWORD is allowed, but it seems to be aimed at video formats. I think 
https://docs.microsoft.com/en-us/previous-versions/dd183376(v=vs.85)#members might be more accurate when BITMAPINFOHEADER is being used in conjunction with CreateDIBSection.

**Comment by mikebattista** [comment]
We should definitely define the constants somewhere. Need to look closer at the API you shared to understand if an enum in the API signature is appropriate.

**Comment by AArnott** [comment]
From the docs: 

> For compressed video and YUV formats, this member is a FOURCC code, specified as a DWORD in little-endian order. For example, YUYV video has the FOURCC 'VYUY' or 0x56595559

It looks like virtually any value may be specified here. That doesn't strike me as appropriate for an enum.
