### ISSUE TITLE
NativeTypedefAttribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#262]
Is there a list of types (in this repo) that use this attribute? Just need to do some validation and it would be helpful to have a list. I can scan the metadata, but if you happen to have a list that would be quicker. 😉

**Comment by sotteson1** [comment]
Check out sources/Win32MetadataSource/remap.rsp:

```csv
--autoTypes
Windows.Win32.Com,HRESULT,int,
Windows.Win32.DisplayDevices,HSEMAPHORE,IntPtr,EngDeleteSemaphore
Windows.Win32.TouchInput,HGESTUREINFO,IntPtr,
Windows.Win32.OpenGL,HGLRC,IntPtr,wglDeleteContext
...
```

**Comment by marler8997** [comment]
>  Just need to do some validation and it would be helpful to have a list.

This is one reason I made this project https://github.com/marlersoft/win32json. It's a "JSON" projection, which makes it easy to search through the data and see everything available.
