### ISSUE TITLE
CreateDIBSection docs page fails to mention that GetLastError should be used

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#269]
The docs page is wrong when it lists ERROR_INVALID_PARAMETER as a "return value" and fails to mention GetLastError: https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createdibsection#return-value

You can verify this by passing an invalid value to the `usage` parameter, such as 12345. CreateDIBSection then returns `0` and GetLastError returns ERROR_INVALID_PARAMETER.

Hans Passant (a reliable source in this area) says the same thing here: https://stackoverflow.com/questions/7932153/windows-gdi-context-createdibsection#comment9693188_7932153

The C# projection of the metadata currently results in DllImport being generated for CreateDIBSection without `SetLastError = true`.

**Comment by jnm2** [comment]
Submitted https://github.com/MicrosoftDocs/sdk-api/pull/679 to fix the docs.

**Comment by mikebattista** [comment]
Thanks for letting us know.

@sotteson1 is there an additional metadata change here required once the docs are updated? Or is this a case where we will detect this change from the docs? I'm assuming the C# and other projections will do the right thing once the metadata is updated.
