### ISSUE TITLE
Property getters and setters should be marked as SpecialName

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#270]
Per [ECMA-335](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf) §I.8.11.3 ("Property definitions"):

> CLS Rule 24: The methods that implement the `getter` and `setter` methods of a property shall be marked `SpecialName` in the metadata.

This is indeed how WinRT properties are marked: the [`CorMethodAttr.mdSpecialName`](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/cormethodattr-enumeration) bitflag is set. But this is not yet the case for COM properties in the `Windows.Win32.winmd` file generated by this repository.

**Comment by AArnott** [comment]
Does this adversely affect projections in some way?

**Comment by timsneath** [comment]
Well... I rely on the spec to tell me what to expect. The spec says that the properties should be marked with SpecialName. And that's what my existing implementation used.

**Comment by AArnott** [comment]
Also events (`add_`/`remove_` prefixed method names) should get this treatment.

**Comment by kennykerr** [comment]
For the record, WinRT adds this flag to add/remove/get/set/invoke (the latter is for delegates).
