### ISSUE TITLE
Missing DesiredAccess enum mapping for OpenProcessToken

### ISSUE THREAD

**Issue by TETYYS** [microsoft/win32metadata#272]

**Comment by mikebattista** [comment]
Thanks for filing. We are exploring some automation to generate more enums. We'll ensure this is addressed.

**Comment by AArnott** [comment]
@tetyys Can you please link to the doc or provide the list of enum values you expect to see? The [`OpenProcessToken` function docs](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocesstoken) don't list any.

**Comment by TETYYS** [comment]
Accepted const values are listed here https://docs.microsoft.com/en-us/windows/win32/secauthz/access-rights-for-access-token-objects
