### ISSUE TITLE
SetInformationToken not generated

### ISSUE THREAD

**Issue by TETYYS** [microsoft/win32metadata#273]
Can't find it in winmd file with ilspy either

**Comment by sotteson1** [comment]
I see NtSetInformationToken and ZwSetInformationToken in ntifs.h, but we excluded that file because it's used for kernel mode calls which we're not yet covering in metadata. Is there some other definition you're looking for? I don't see SetInformationToken anywhere else in the API docs.

**Comment by TETYYS** [comment]
oh, I was looking for NtSetInformationToken, thanks.
