### ISSUE TITLE
IRunningObject.GetObjectA

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#274]
For reasons I can't quite understand, this method on `IRunningObject` is projected with a `A` suffix:

```
// Windows.Win32.Com.IRunningObjectTable
using System.Runtime.InteropServices;

unsafe HRESULT GetObjectA([Optional][In][Out] IMoniker pmkObjectName, [Out] IUnknown* ppunkObject);
```

This doesn't match [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-irunningobjecttable-getobject) or the header file:

```c
        virtual HRESULT STDMETHODCALLTYPE GetObject( 
            /* [unique][in] */ __RPC__in_opt IMoniker *pmkObjectName,
            /* [out] */ __RPC__deref_out_opt IUnknown **ppunkObject) = 0
```

The same is true of `IProvideClassInfo.GetClassInfoA` and a search of ILSpy for objects matching `GetObjectA` picks up other candidate examples.

**Comment by kennykerr** [comment]
Those are macros trampling on the interface method names before the scraper parses the code. Steve should be able to undef these.
