### ISSUE TITLE
SupportedOSPlatform attributes so that API usage can be version-safe

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#279]
The .NET 5 platform compatibility analyzer uses SupportedOSPlatform attributes to warn you if you use an API for an OS version older than your project's minimum without safely checking first:
- https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer
- https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md

I accidentally used https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforwindow, not intending to limit my library to Windows 10 version 1607+ and prevent it from running on any version of Windows Server. If the generated `PInvoke.GetDpiForWindow` method had been annotated with `SupportedOSPlatform`, maybe I would have caught this right away instead of overlooking and first noticing by seeing EntryPointNotFoundExceptions in production.

**Comment by mikebattista** [comment]
Yes we do plan to add versioning information to the metadata specifically for scenarios like this. C#/Win32 then could add `SupportedOSPlatform` appropriately once the metadata includes that.

**Comment by jnm2** [comment]
A note I wanted to add that applies to the CsWin32 repo is that the source generator will have to synthesize the `SupportedOSPlatformAttribute` declaration on target frameworks that don't declare it. The synthesized attribute should be declared as internal (in the typical way that the C# compiler itself synthesizes some compiler-recognized attributes).

**Comment by mikebattista** [comment]
We had a discussion today with the .NET team about integrating C#/Win32 support with TFMs in the future, and versioning support will be required for that. Added this to our High Priority Issues list.

**Comment by sotteson1** [comment]
I'm looking at this page: https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer

It looks like I can do ```[SupportedOSPlatform("windows8.0")]``` and ```[SupportedOSPlatform("windows10.0.19041.0")]``` for Win8 and Win10. I'm wondering what I should do for XP, 7 and Vista. Does anyone know? I could use the actual Windows versions, for for Win8 the actual version was 6.2.9200 which doesn't match with the example they give to use windows8.0 for Win8.

**Comment by mikebattista** [comment]
It looks like they're matching the platform-specific component of the TFM. @clairernovotny is this correct?

**Comment by kennykerr** [comment]
I didn't realize they would be strings. 😛 Historically, this version information is generally only used by C#. I may have to write a post-processor to generate a more compact winmd for Rust consumption. https://github.com/microsoft/windows-rs/issues/605

**Comment by sotteson1** [comment]
The strings will be cached, so I think the bulk of the added size will come from adding the attribute to most APIs and interfaces. If the strings really did add a lot more, we could use an enum and then the C# projection could convert it into the C#-specific SupportedOSPlatform attribute.

**Comment by kennykerr** [comment]
Yep, string pooling should help a bunch.
