### ISSUE TITLE
GetIconInfo has an HICON overload but HCURSOR can't be passed to it

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#282]
I think I remember reading that HCURSOR has an "is-a" relationship to HICON. At any rate, GetIconInfo accepts either: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-geticoninfo#parameters

Depending on whether that relationship holds for all APIs, maybe it would be preferable to add an implicit conversion from HCURSOR to HICON rather than generating another overload to GetIconInfo.

**Comment by jnm2** [comment]
@AArnott Is there an open issue I can follow to know when CsWin32 gives HCURSOR an implicit cast to HICON?

**Comment by AArnott** [comment]
@jnm2 you can follow https://github.com/microsoft/CsWin32/issues/199
