### ISSUE TITLE
Rename SizeParamIndex to CountParamIndex

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#283]
The `NativeArrayInfoAttribute` has two fields that are related but carry important distinctions:

```cs
	public short SizeParamIndex;
	public short BytesParamIndex;
```

The Bytes named one is unambiguously named, but Size isn't, IMO. What if we renamed it to `CountParamIndex`, signifying that the one parameter indicates the size in bytes while the other indicates the size in _number of elements_?

**Comment by sotteson1** [comment]
Makes sense.

**Comment by sotteson1** [comment]
Heads up @kennykerr  and @timsneath, on NativeArrayInfoAttribute I'm changing SizeParamIndex to CountParamIndex and SizeConst to CountConst.

**Comment by timsneath** [comment]
Thanks. No problem here -- I'm reading this from the signature BLOB at present, rather than by parsing the attribute.

**Comment by kennykerr** [comment]
Same here. 😊
