### ISSUE TITLE
VirtualQueryEx 3rd parameter is not an array

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#284]
The [`VirtualQueryEx` method](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualqueryex)'s 3rd parameter is `MEMORY_BASIC_INFORMATION*` and is _not_ an array. Per the docs, only one struct is expected.

But the metadata attributes it with `[NativeArrayInfo(BytesParamIndex = 3)]` as if it were an array, leading to CsWin32 projecting it as `Span<MEMORY_BASIC_INFORMATION>`.

The 4th parameter is supposed to be the length of the struct (just one of them). Capturing this with an attribute (similar to `NativeArrayInfo` but without the *array* implication) would allow projections to drop the 4th parameter and auto-fill with the calculated size of the struct, as we're doing now while incorrectly treating it like an array.

**Comment by AArnott** [comment]
Searching the metadata for other uses of `BytesParamIndex` I ran across [`ReadCabinetState`](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-readcabinetstate) which also is incorrectly tagged with an array parameter that is actually a single struct, just like `VirtualQueryEx`'s case.

Same for `SHGetFileInfoA` and `SHGetFileInfoW`.

The only valid cases of `BytesParamIndex` I have found so far is for `void*` and `byte*` parameters. Which suggests maybe a pattern the header parser can use to detect whether the pointer parameter really is an array or not.

**Comment by sotteson1** [comment]
It seems like if I find I need to use BytesParamIndex, I should use a different attribute that just means how big in bytes the pointer points to. That would work for any types, including MEMORY_BASIC_INFORMATION*, void*, and byte*.

**Comment by sotteson1** [comment]
This will look like:

```C#
public unsafe static extern UIntPtr VirtualQueryEx([In] HANDLE hProcess, [Optional][In][Const] void* lpAddress, [Out][MemorySize(BytesParamIndex = 3)] MEMORY_BASIC_INFORMATION* lpBuffer, [In] UIntPtr dwLength);
```
