### ISSUE TITLE
`[ComOutPtr]` should not appear with `[In]`

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#288]
IUnknown::QueryInterface now tags the second parameter as `[In, Out, ComOutPtr]` when it should *not* include `[In]`.
Maybe regressed in #63, as this showed up in the upgrade from preview.22 to preview.26.

```cs
public interface IUnknown
{
	unsafe HRESULT QueryInterface([In][Const] Guid* riid, [In][Out][ComOutPtr] void** ppvObject);
}
```

This results in a regression in the CsWin32 experience as the projection now wants to see *ref* instead of *out* used to receive the COM object:
![image](https://user-images.githubusercontent.com/3548/109366728-7248f480-7851-11eb-9636-8d7d5a73948c.png)

**Comment by AArnott** [comment]
This also appears on `CoCreateInstance`, and probably other places.

**Comment by kennykerr** [comment]
I just noticed this as well. 😢
