### ISSUE TITLE
winmd assembly version isn't changing with each release

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#289]
Each release keeps the exact same assembly version, which seems odd. Have we no freedom to increment it?

![image](https://user-images.githubusercontent.com/3548/109366926-ed120f80-7851-11eb-8ab6-7478473fecb7.png)

**Comment by sotteson1** [comment]
This is by design. I'm matching the assembly version to the WinSDK nuget package version that I scrape from. I wish assemblies gave me more than just 4 numbers like what NuGet versions give us.
