### ISSUE TITLE
COM methods suffixed with 'A'

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#290]
#274 solved a specific instance of this problem, but not all instances. For example:
https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-iprovideclassinfo-getclassinfo

which still shows in ILSpy as:

```cs
[Guid(2979443331u, 47796, 4122, 182, 156, 0, 170, 0, 52, 29, 7)]
public interface IProvideClassInfo : IUnknown
{
	unsafe HRESULT GetClassInfoA([Out] ITypeInfo* ppTI);
}
```

**Comment by sotteson1** [comment]
If you know of others besides GetClassInfo, let me know.

**Comment by kennykerr** [comment]
There's also `GetUserNameA` in `Windows.Win32.Com.IUri` that should just be `GetUserName`.

**Comment by weltkante** [comment]
There seems to be plenty of mistakes here, inspired by above suggestions I ran a regex search in ILSpy `/^Get.*A$/` resp. `/^Set.*A$/` and ignored P/Invoke APIs, checking only COM interfaces against the docs. I omitted those that were correctly having the `A` suffix. I'm sure there is more than just getter/setter methods having these issues, but they are the easiest to search for:

`/^Get.*A$/`
* [Windows.Win32.Fax.IFaxIncomingQueue::GetJobA](https://docs.microsoft.com/en-us/windows/win32/api/faxcomex/nf-faxcomex-ifaxincomingqueue-getjob)
* [Windows.Win32.Fax.IFaxOutgoingQueue::GetJobA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxoutgoingqueue-getjob)
* [Windows.Win32.Fax.IFaxAccountIncomingQueue::GetJobA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxaccountincomingqueue-getjob)
* [Windows.Win32.Fax.IFaxAccountOutgoingQueue::GetJobA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxaccountoutgoingqueue-getjob)
* [Windows.Win32.BackgroundIntelligentTransferService.IBackgroundCopyManager::GetJobA](https://docs.microsoft.com/en-us/windows/win32/api/bits/nf-bits-ibackgroundcopymanager-getjob)
* [Windows.Win32.BackgroundIntelligentTransferService.IBackgroundCopyGroup::GetJobA](https://docs.microsoft.com/en-us/windows/win32/api/qmgr/nf-qmgr-ibackgroundcopygroup-getjob)
* [Windows.Win32.BackgroundIntelligentTransferService.IBackgroundCopyGroup::GetPropA](https://docs.microsoft.com/en-us/windows/win32/api/qmgr/nf-qmgr-ibackgroundcopygroup-getprop)
* [Windows.Win32.ActiveDirectory.IADsContainer::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-iadscontainer-getobject)
* [Windows.Win32.ActiveDirectory.IADsCollection::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-iadscollection-getobject)
* [Windows.Win32.HtmlHelp.IITDatabase::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/infotech/nf-infotech-iitdatabase-getobject)
* [Windows.Win32.Com.IRunningObjectTable::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-irunningobjecttable-getobject)
* [Windows.Win32.Com.IOleItemContainer::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-ioleitemcontainer-getobject)
* [Windows.Win32.Com.IGetVBAObject::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/vbinterf/nf-vbinterf-igetvbaobject-getobject)
* [Windows.Win32.SystemService.IVdsProviderPrivate::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/vdshwprv/nf-vdshwprv-ivdsproviderprivate-getobject)
* [Windows.Win32.Controls.IRichEditOle::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/richole/nf-richole-iricheditole-getobject)
* [Windows.Win32.BackgroundIntelligentTransferService.IBITSExtensionSetupFactory::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/bitscfg/nf-bitscfg-ibitsextensionsetupfactory-getobject)
* [Windows.Win32.ComponentServices.IServicePool::GetObjectA](https://docs.microsoft.com/de-at/windows/win32/api/comsvcs/nf-comsvcs-iservicepool-getobject)
* [Windows.Win32.Wmi.IWbemServices::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/wbemcli/nf-wbemcli-iwbemservices-getobject)
* [Windows.Win32.Shell.IShellFolderView::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-ishellfolderview-getobject)
* [Windows.Win32.Shell.ISyncMgrHandler::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/syncmgr/nf-syncmgr-isyncmgrhandler-getobject)
* [Windows.Win32.Shell.ISyncMgrSyncItem::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/syncmgr/nf-syncmgr-isyncmgrsyncitem-getobject)
* [Windows.Win32.Shell.IHlinkBrowseContext::GetObjectA](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767948(v=vs.85))
* [Windows.Win32.MediaFoundation.IMFAsyncResult::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/mfobjects/nf-mfobjects-imfasyncresult-getobject)
* [Windows.Win32.MediaFoundation.IMFTopologyNode::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/mfidl/nf-mfidl-imftopologynode-getobject)
* [Windows.Win32.MediaFoundation.IMFPMediaItem::GetObjectA](https://docs.microsoft.com/en-us/windows/win32/api/mfplay/nf-mfplay-imfpmediaitem-getobject)
* [Windows.Win32.Fax.IFaxIncomingArchive::GetMessageA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxincomingarchive-getmessage)
* [Windows.Win32.Fax.IFaxOutgoingArchive::GetMessageA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxoutgoingarchive-getmessage)
* [Windows.Win32.Fax.IFaxAccountIncomingArchive::GetMessageA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxaccountincomingarchive-getmessage)
* [Windows.Win32.Fax.IFaxAccountOutgoingArchive::GetMessageA](https://docs.microsoft.com/de-de/windows/win32/api/faxcomex/nf-faxcomex-ifaxaccountoutgoingarchive-getmessage)
* [Windows.Win32.Xblidp.IXblIdpAuthTokenResult::GetMessageA](https://docs.microsoft.com/de-de/windows/win32/api/xblidpauthmanager/nf-xblidpauthmanager-ixblidpauthtokenresult-getmessage)
* [Windows.Win32.Direct3D10.ID3D10InfoQueue::GetMessageA](https://docs.microsoft.com/en-us/windows/win32/api/d3d10sdklayers/nf-d3d10sdklayers-id3d10infoqueue-getmessage)
* [Windows.Win32.Dxgi.IDXGIInfoQueue::GetMessageA](https://docs.microsoft.com/en-us/windows/win32/api/dxgidebug/nf-dxgidebug-idxgiinfoqueue-getmessage)
* [Windows.Win32.Direct3D11.ID3D11InfoQueue::GetMessageA](https://docs.microsoft.com/en-us/windows/win32/api/d3d11sdklayers/nf-d3d11sdklayers-id3d11infoqueue-getmessage)
* [Windows.Win32.Direct3D12.ID3D12InfoQueue::GetMessageA](https://docs.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nf-d3d12sdklayers-id3d12infoqueue-getmessage)
* [Windows.Win32.Com.IUri::GetUserNameA](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775034(v=vs.85))
* [Windows.Win32.Com.IUriBuilder::GetUserNameA](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms774998(v=vs.85))
* [Windows.Win32.Com.IProvideClassInfo::GetClassInfoA](https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-iprovideclassinfo-getclassinfo)
* [Windows.Win32.Wmi.IWbemPath::GetClassNameA](https://docs.microsoft.com/en-us/windows/win32/api/wmiutils/nf-wmiutils-iwbempath-getclassname)
* Windows.Win32.HtmlHelp.IITWordWheel::GetLocaleInfoA (no doc ?)
* Windows.Win32.HtmlHelp.IStemmerConfig::GetLocaleInfoA (no doc ?)
* Windows.Win32.HtmlHelp.IWordBreakerConfig::GetLocaleInfoA (no doc ?)
* [Windows.Win32.DirectShow.IMediaSeeking::GetTimeFormatA](https://docs.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-imediaseeking-gettimeformat)
* [Windows.Win32.Packaging.IOpcDigitalSignature::GetTimeFormatA](https://docs.microsoft.com/en-us/windows/win32/api/msopc/nf-msopc-iopcdigitalsignature-gettimeformat)
* [Windows.Win32.Packaging.IOpcSigningOptions::GetTimeFormatA](https://docs.microsoft.com/en-us/windows/win32/api/msopc/nf-msopc-iopcsigningoptions-gettimeformat)
* [Windows.Win32.DirectWrite.IDWriteFontFace::GetGlyphIndicesA](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritefontface-getglyphindices)
* [Windows.Win32.Xps.IXpsOMGlyphsEditor::GetGlyphIndicesA](https://docs.microsoft.com/en-us/windows/win32/api/xpsobjectmodel/nf-xpsobjectmodel-ixpsomglyphseditor-getglyphindices)
* [Windows.Win32.Xps.IXpsOMGlyphs::GetGlyphIndicesA](https://docs.microsoft.com/en-us/windows/win32/api/xpsobjectmodel/nf-xpsobjectmodel-ixpsomglyphs-getglyphindices)
* [Windows.Win32.OfflineFiles.IOfflineFilesSyncErrorItemInfo::GetFileAttributesA](https://docs.microsoft.com/en-us/windows/win32/api/cscobj/nf-cscobj-iofflinefilessyncerroriteminfo-getfileattributes)
* [Windows.Win32.OfflineFiles.IOfflineFilesCache::GetDiskSpaceInformationA](https://docs.microsoft.com/en-us/windows/win32/api/cscobj/nf-cscobj-iofflinefilescache-getdiskspaceinformation)

`/^Set.*A$/`
* [Windows.Win32.OtherDeviceTechnologies.IWSDTransportAddress::SetPortA](https://docs.microsoft.com/en-us/windows/win32/api/wsdbase/nf-wsdbase-iwsdtransportaddress-setport)
* [Windows.Win32.Com.IUriBuilder::SetPortA](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775009(v=vs.85))
* [Windows.Win32.BackgroundIntelligentTransferService.IBackgroundCopyGroup::SetPropA](https://docs.microsoft.com/en-us/windows/win32/api/qmgr/nf-qmgr-ibackgroundcopygroup-setprop)
* [Windows.Win32.WindowsMediaFormat.IWMBackupRestoreProps::SetPropA](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/wmsdkidl/nf-wmsdkidl-iwmbackuprestoreprops-setprop)
* [Windows.Win32.HtmlHelp.IStemmerConfig::SetLocaleInfoA](https://docs.microsoft.com/en-us/windows/win32/api/infotech/nf-infotech-istemmerconfig-setlocaleinfo)
* Windows.Win32.HtmlHelp.IWordBreakerConfig::SetLocaleInfoA (no doc ?)
* [Windows.Win32.Shell.ICreateProcessInputs::SetEnvironmentVariableA](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-icreateprocessinputs-setenvironmentvariable)

**Comment by sotteson1** [comment]
> /^Get.*A$/

Woah, I didn't know ilspy lets you do regex searches!! That's great to know. Thanks @weltkante.

**Comment by mikestek** [comment]
ID2D1RenderTarget::DrawText is also incorrectly mapped to DrawTextA
