### ISSUE TITLE
WindowsCreateString PCNZWCH not represented as String

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#292]
This should be a Pointer to a WCHAR-style string, rather than a `ushort *`.

The [WindowsCreateString](https://docs.microsoft.com/en-us/windows/win32/api/winstring/nf-winstring-windowscreatestring) documentation is unclear whether this should be treated as null-terminated or not. In the _Parameters_ section, it says:

> A null-terminated string to use as the source for the new `HSTRING`.

but later, it says:

> If `sourceString` has embedded null characters, the `WindowsCreateString` function copies all characters to the terminating null character.

This latter statement is hard to interpret -- is the terminating null character the one that ends the string, or the first null character it finds? 

So, I don't know exactly how it should be represented without reading the source code or further experimenting, but one way or another it should be a string.

**Comment by kennykerr** [comment]
`WindowsCreateString` should use `const PWSTR` like `SysAllocStringLen` does. Both BSTR and HSTRING support embedded null characters although this is rarely used and not recommended as APIs that happen to use these string types rarely use the data beyond the first null.
