### ISSUE TITLE
CoInitializeSecurity PSECURITY_DESCRIPTOR not projected correctly

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#293]
Here's the header file:

```c
CoInitializeSecurity(
    _In_opt_ PSECURITY_DESCRIPTOR pSecDesc,
    _In_ LONG cAuthSvc,
    _In_reads_opt_(cAuthSvc) SOLE_AUTHENTICATION_SERVICE* asAuthSvc,
    _In_opt_ void* pReserved1,
    _In_ DWORD dwAuthnLevel,
    _In_ DWORD dwImpLevel,
    _In_opt_ void* pAuthList,
    _In_ DWORD dwCapabilities,
    _In_opt_ void* pReserved3
    );
```

The first parameter `pSecDesc` is being projected as `void *` instead of `SECURITY_DESCRIPTOR*`, as ILSpy shows:

```csharp
[DllImport("OLE32", ExactSpelling = true)]
public unsafe static extern HRESULT CoInitializeSecurity(
  [Optional][In] void* pSecDesc, 
  [In] int cAuthSvc, 
  [Optional][In][NativeArrayInfo(SizeParamIndex = 1)] SOLE_AUTHENTICATION_SERVICE* asAuthSvc,
  [Optional][In] void* pReserved1, 
  [In] uint dwAuthnLevel, 
  [In] uint dwImpLevel, 
  [Optional][In] void* pAuthList, 
  [In] uint dwCapabilities, 
  [Optional][In] void* pReserved3);
```

**Comment by timsneath** [comment]
Oh forget it. The headers declare:

```c
typedef PVOID PACCESS_TOKEN;            
typedef PVOID PSECURITY_DESCRIPTOR;     
typedef PVOID PSID;     
typedef PVOID PCLAIMS_BLOB;
```

which is annoyingly obtuse, but means that the projection is technically correct.

**Comment by AArnott** [comment]
We should be able to do better here though. `SECURITY_DESCRIPTOR` for example _is_ a struct defined in the metadata, so where `PSECURITY_DESCRIPTOR` appears, the metadata should ideally express it as `SECURITY_DESCRIPTOR*`. 
Reopening for consideration.

**Comment by timsneath** [comment]
Yeah, I considered that too, but I did see in the docs for [`CoInitializeSecurity`](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializesecurity) that this is also used for other random things that get thrown in there:

> The access permissions that a server will use to receive calls. This parameter is used by COM only when a server calls CoInitializeSecurity. Its value is a pointer to one of three types: an AppID, an IAccessControl object, or a SECURITY_DESCRIPTOR, in absolute format. 

Old decisions bite us in the long term... feels like this isn't really a `SECURITY_DESCRIPTOR` at all, but more of a dumping ground for 'miscellaneous'!
