### ISSUE TITLE
Windows.Win32.Mmc contains some weird enums

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#297]
For example:

```
Windows.Win32.Mmc.__MIDL___MIDL_itf_mmc_0000_0006_0001
```

![image](https://user-images.githubusercontent.com/2319867/109451458-59cc0c00-7a02-11eb-87dc-fe7b60656b2f.png)

**Comment by kennykerr** [comment]
Seems like more of this: https://github.com/microsoft/win32metadata/issues/89
