### ISSUE TITLE
Many typedefs not part of parent namespace

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#298]
I ran a little test of the Win32 metadata, since I was getting some weird results back, and I discovered quite a lot of typedefs that aren't part of the parent namespace. Written in Dart, but you can probably figure out what this does:

```dart
void initNamespaces(Scope scope) {
  final ns = <String>{};
  final scope = MetadataStore.getScopeForFile('tool/win32/Windows.Win32.winmd');
  for (final td in scope.typeDefs) {
    if (td.typeName.startsWith('Windows.Win32')) {
      ns.add(td.typeName.split('.')[2]);
    } else {
      print(td.typeName);
    }
  }
  namespaces = ns.toList();
}
```

A full list is here:
https://gist.github.com/timsneath/01aa8cf7526123e12aed1ecae9e5a6e5

Similar tests for Windows Runtime scopes don't return any typedefs that aren't part of the namespace, and I believe this is (at least technically) in violation of the spec.

**Comment by kennykerr** [comment]
Those are correct. They are actually the typedefs of nested classes.

**Comment by timsneath** [comment]
Got it. Thanks!
