### ISSUE TITLE
BSTR and PWSTR

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#299]
`PWSTR` has a `char*` member but `BSTR` has a `IntPtr` member. Can we make then both `char*`? Consistency...

**Comment by sotteson1** [comment]
I made in an IntPtr because it points to more than just a char*, but I can change it if it works better for projections.

**Comment by kennykerr** [comment]
It's not a big deal. It just seemed inconsistent since they both have the same underlying pointer type.

**Comment by AArnott** [comment]
The pointer does still point at the first character, so `char*` feels technically correct. The BSTR name comes with the implication that a prefix directly precedes that memory address, true, but I don't see that as a reason to avoid `char*` for the pointer itself.

If the field were `char*`, the data tip experience in the debugger would probably be better.
