### ISSUE TITLE
BuildMetadataBin.cmd fails if the display language is not English

### ISSUE THREAD

**Issue by krzysdz** [microsoft/win32metadata#315]
When looking for errors, if the `Id` is `"CS0246"` the diagnostic message is checked using a regular expression:

https://github.com/microsoft/win32metadata/blob/d32d7f44135f34b7c6788b564966cd4edb4bf89b/sources/ClangSharpSourceToWinmd/ClangSharpSourceCompilation.cs#L150-L163

The `GetMessage` function returns a localised message, so there is no match if language other than English is used and the command fails with multiple errors.

![.\BuildMetadataBin.cmd output with many CS0246 errors "Nie można znaleźć nazwy typu lub przestrzeni nazw..."](https://user-images.githubusercontent.com/12915102/110264266-3df3d780-7fb9-11eb-9db5-9f3ebff6936a.png)

Hopefully, this problem should be easy to fix, because an `IFormatProvider` can be passed as an argument to use the appropriate language - see https://github.com/krzysdz/win32metadata/commit/5b142922ebe17c8e6587a33471b2e1892308789b:

```cs
                    var symbolNameRegx = new System.Text.RegularExpressions.Regex(@"The type or namespace name '(\w+)'");
                    var culture = new System.Globalization.CultureInfo("en-US");
                    var match = symbolNameRegx.Match(diag.GetMessage(culture));
```

**Comment by sotteson1** [comment]
Thanks @krzysdz for the advice on the fix!
