### ISSUE TITLE
ERROR_IO_PENDING

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#318]
This is a signed integer but should be unsigned (to match what GetLastError returns).

**Comment by sotteson1** [comment]
Hmm, all of the error constants are marked as signed:

#define ERROR_IO_PENDING                 997L    // dderror

The scraper I'm working on is emitting these as signed because that's what they are in the headers. But maybe I should force them to be unsigned.

**Comment by kennykerr** [comment]
I think they're accidentally unsigned since they're defined by a macro and GetLastError actually returns an unsigned value. They're also meant to be folded into HRESULTs and having signed values would not make sense in that case.

**Comment by sotteson1** [comment]
HRESULT is signed. From ntdef.h:

```C
typedef LONG HRESULT;
```

**Comment by kennykerr** [comment]
Yes, but the sign bit is already used for something other than the error code. Throw in a signed error code and you have something that you cannot define.

https://en.wikipedia.org/wiki/HRESULT

**Comment by sotteson1** [comment]
Fixed with the latest changes.
