### ISSUE TITLE
Struct fields named event are named @event in the metadata

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#32]
In the latest version of the metadata, I'm having errors because `BANNER_NOTIFICATION` has a field named `@event`.

**Comment by sotteson1** [comment]
It looks like this is now fixed. Using ilspy it looks like the '@' is there in C# mode, but in IL mode you can see that it's gone. I also stepped through things in the debugger just to make sure when I call MetdataBuilder.GetOrAddString that the '@' isn't there.
