### ISSUE TITLE
FormatMessageW and FORMAT_MESSAGE_OPTIONS

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#320]
The FormatMessageW function resides in the Debug namespace but the FORMAT_MESSAGE_OPTIONS enum resides in the WindowsProgramming namespace. As far as I know, these constants aren't used with any functions other than FormatMessageA/FormatMessageW so it would be more convenient if they were in the same namespace.

**Comment by kennykerr** [comment]
It's used for error handling, which supports debugging, so I don't have a problem with the name. The debugging namespace also has various other error handling related functions like GetLastError, so whatever its called it would be nice to have these together.

**Comment by AArnott** [comment]
> It's used for error handling

So is the `if` keyword. 😛

`FormatMessageW` is a general-purpose sprintf-like string formatter, is it not?

**Comment by kennykerr** [comment]
It is *very* hard to use correctly - I would be surprised if anyone would choose to use it for anything other than to format a system error code. 😄

**Comment by Robo210** [comment]
It's not straightforward, but you need FormatMessageW if you want to get the message for an ETW event.
