### ISSUE TITLE
GetProcessHeap and HeapAlloc

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#322]
`GetProcessHeap` returns a `HANDLE` as expected by `HeapAlloc` (according to the original sources). However, `HeapAlloc`'s metadata description expects a `HeapHandle` - a type I had not come across before. 

It's very common to use `GetProcessHeap` and `HeapAlloc` together, so this makes it a little awkward.

**Comment by kennykerr** [comment]
Also, `GetProcessHeap` is also passed to `HeapFree` and it is properly described as expecting a `HANDLE`. So that's much cleaner. 

Can we make HeapAlloc the same?

**Comment by sotteson1** [comment]
The idea was to use a new type to get type safety and RAII info to be used with all the heap functions instead of using HANDLE (HeapCreate return HeapHandle). It seems like I should change GetProcessHeap to return HeapHandle.

**Comment by sotteson1** [comment]
GetProcessHeap will return ProcessHandleHeap which will have the AlsoUsableAs("HeapHandle") attribute on it.
