### ISSUE TITLE
Fields with arrays of COM objects should be annotated as such

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#324]
The [`DXVAHD_STREAM_DATA` struct](https://docs.microsoft.com/en-us/windows/win32/api/dxvahd/ns-dxvahd-dxvahd_stream_data) has three fields that involve COM objects. Two of them are pointers to arrays of COM objects. The metadata just represents a pointer to *a* COM object, but for marshaling this in .NET we must know that these fields represent arrays.

**Comment by sotteson1** [comment]
For methods we have been marking parameters like this to show they're arrays:

```[NativeArrayInfo(SizeParamIndex = 2)] DXVAHD_STREAM_DATA* pStreams```

This struct has fields that are used to show how big the arrays are. Would this make sense?

```C#
public struct DXVAHD_STREAM_DATA
{
    public BOOL Enable;

    public uint OutputIndex;

    public uint InputFrameOrField;

    public uint PastFrames;

    public uint FutureFrames;

    [NativeArrayInfo(SizeParamIndex = 3)]
    public unsafe IDirect3DSurface9* ppPastSurfaces;

    public IDirect3DSurface9 pInputSurface;

    [NativeArrayInfo(SizeParamIndex = 4)]
    public unsafe IDirect3DSurface9* ppFutureSurfaces;
}
```

It's kind of weird the name in the attribute is SizeParamIndex. Have we seen this kind of pattern on any other struct?

**Comment by AArnott** [comment]
Sure, that'll work.
