### ISSUE TITLE
Where are `propget` annotations on property accessors?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#325]
Similar to #207's adding of `retval` annotations, should there also be a `propget`/`propput` annotation to indicate when methods are ideally exposed as properties?

For instance *all* of the methods on this interface should be expressed as properties in .NET. IDL has a way to indicate this and it usually correlates with `get_` or `set_` prefixes on the method names I believe.

```cs
[Guid("B7C82D61-FBE8-4B47-9B27-6C0D2E0DE0A3")]
public interface ISpellingError : IUnknown
{
	unsafe HRESULT get_StartIndex([Out][RetVal] uint* value);

	unsafe HRESULT get_Length([Out][RetVal] uint* value);

	unsafe HRESULT get_CorrectiveAction([Out][RetVal] CORRECTIVE_ACTION* value);

	unsafe HRESULT get_Replacement([Out][RetVal][FreeWith("CoTaskMemFree")] PWSTR* value);
}
```

**Comment by kennykerr** [comment]
That's what @timsneath is asking for here: #270
