### ISSUE TITLE
Macros manually defined as functions are not included in the .winmd file

### ISSUE THREAD

**Issue by krzysdz** [microsoft/win32metadata#326]
In `Direct3D12.manual.cs` and `DirectWrite.manual.cs` there are 15 functions in the `Apis` class. These functions correspond to various `#define` macros from header files and (at least the ones that I've listed below) are described in the documentation.\
Unfortunately, the generated `Windows.Win32.winmd` file doesn't contain any of these functions.

Examples:

- `DWRITE_MAKE_OPENTYPE_TAG` - [definition](https://github.com/microsoft/win32metadata/blob/d32d7f44135f34b7c6788b564966cd4edb4bf89b/generation/emitter/manual/DirectWrite.manual.cs#L9) in `.cs`, [docs](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-dwrite_make_opentype_tag)
- `D3D12_GET_COARSE_SHADING_RATE_X_AXIS` - [definition](https://github.com/microsoft/win32metadata/blob/d32d7f44135f34b7c6788b564966cd4edb4bf89b/generation/emitter/manual/Direct3D12.manual.cs#L919) in `.cs`, [mention](https://docs.microsoft.com/en-us/windows/win32/direct3d12/vrs#shading-rates) in docs
- `D3D12_ENCODE_SHADER_4_COMPONENT_MAPPING` - [definition](https://github.com/microsoft/win32metadata/blob/d32d7f44135f34b7c6788b564966cd4edb4bf89b/generation/emitter/manual/Direct3D12.manual.cs#L878) in `.cs`, [mention](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_shader_component_mapping#remarks) in docs

The definitions in `*.manual.cs` files:
![Definitions in *.manual.cs files](https://user-images.githubusercontent.com/12915102/110554468-280e2000-813b-11eb-9d9f-f3c1990e20e9.png)

No results when searching in the `.winmd` file from `10.0.19041.5-preview.27` (same results in the manually generated one from the commit d32d7f44135f34b7c6788b564966cd4edb4bf89b):
![No results found when looking for one of the macros in the .winmd file](https://user-images.githubusercontent.com/12915102/110554773-b8e4fb80-813b-11eb-8591-31e592d0d6b7.png)

**Comment by sotteson1** [comment]
These functions are getting pulled out from the source soon, because we can't have actual code in the metadata. Today the emitter just skips any methods that have code in them, so what you're seeing is by design. Otherwise it would require projection authors to interpret IL which isn't what we expect projections to do.

**Comment by krzysdz** [comment]
So these macros won't be available in the projections and if someone wants to use them, they must find the definitions in docs/headers and write appropriate functions/macros manually in the language they are using (or use manually written bindings like `winapi-rs`, where these functions are present)?
