### ISSUE TITLE
DXGI_ERROR_INVALID_CALL

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#329]
Many DXGI constants are in the SystemServices namespace rather than the Dxgi namespace.

**Comment by sotteson1** [comment]
This was fixed in the latest release. You had another issue for this that I closed.

**Comment by kennykerr** [comment]
This is now in the `Com` namespace rather than the `Dxgi` namespace.

**Comment by kennykerr** [comment]
No, it's not - reading ILSpy wrong. 😄
