### ISSUE TITLE
varargs not being represented in metadata?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#33]
The `SetupWriteTextLog` method [documentation](https://docs.microsoft.com/en-us/windows/win32/api//setupapi/nf-setupapi-setupwritetextlog) says it takes a variable number of arguments. But the metadata doesn't have any hint of this.

**Comment by kennykerr** [comment]
More customer demand for this metadata feature:

* https://github.com/microsoft/windows-rs/issues/1592
* https://github.com/microsoft/win32metadata/issues/800 (duplicate?)

**Comment by kennykerr** [comment]
Any thoughts on this one?

**Comment by Berrysoft** [comment]
I remember there's a `varargs` in CIL, and there's a keyword `__arglist` in C#. They are designed to interop with functions like `printf`. Maybe we should decorate these APIs with `varargs` in metadata.

**Comment by Berrysoft** [comment]
@kennykerr I've added the support for varargs for ClangSharp.

Actually dotnet supports `varargs` calling convention: [`CallingConventions`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.callingconventions?view=net-6.0) , and I believe it could be retrieved from CIL. Would you like to have a try?

**Comment by kennykerr** [comment]
Sweet! I'll need someone like @sotteson1 or @riverar to add support in this repo and then I'll definitely plumb it through to Rust over in [windows-rs](https://github.com/microsoft/windows-rs).

**Comment by sotteson1** [comment]
Fix coming shortly. In the metadata, we will be setting the calling convention of these methods to vararg as per the ECMA-335 spec.
