### ISSUE TITLE
Single batch file to generate and test

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#330]
It's a trivial PR, but before I submit it -- is there support for having a single batch file that runs the three commands (generate / build / test) sequentially? 

Since the commands collectively take ~10 minutes to run, I'd like to run `git pull` and then `build` and go and make a cup of tea, rather than shepherd my machine through the process.

**Comment by sotteson1** [comment]
No, but there should be! I'll add a command for it today.
