### ISSUE TITLE
LoadLibraryEx_dwFlags, CreateProcessWith_dwLogonFlags, and others

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#331]
The name of the new enums for functions like `LoadLibraryExW` are well... quite ugly. 

Any chance LoadLibraryEx_dwFlags can be something like `LOAD_LIBRARY` or `LOAD_LIBRARY_FLAGS` instead. That at least would be more consistent with existing enums. 

These really aren't very usable for developers who have to type them in.

**Comment by kennykerr** [comment]
Chatted with Steve - he's working on examples like this.

**Comment by sotteson1** [comment]
These weird names are a clue that the enum scraper couldn't figure out a good name and that a human needs to provide a better name. I cleaned up some when doing the scraper work but there are a bunch to go. Fortunately they're easy to rename.

**Comment by kennykerr** [comment]
Another egregious example is `HeapAlloc`'s `HeapReAlloc_dwFlags`.

**Comment by kennykerr** [comment]
And `GetWindowLongPtr_nIndex` 😱

**Comment by kennykerr** [comment]
And `PeekMessage_wRemoveMsg`.
