### ISSUE TITLE
EXCEPINFO has field with bad type (10 pointers!)

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#332]
The [`EXCEPINFO` struct](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-excepinfo) includes this field:
```
ULONG_PTR pfnDeferredFillIn;
```

But the metadata (as of 10.0.19041.5-preview.27) for this field is:
```
	.field public valuetype [Windows.Win32.winmd]Windows.Win32.Com.HRESULT********** pfnDeferredFillIn
```

Where in the world did that come from?

**Comment by sotteson1** [comment]
From a bug. :)
