### ISSUE TITLE
Add Microsoft Speech APIs

### ISSUE THREAD

**Issue by dgalling** [microsoft/win32metadata#334]
Hello,

I'm interested in using the Microsoft Speech APIs through the windows-rs Rust crate, but as far as I can tell, this repo doesn't generate bindings for the speech APIs.

I think I've got the binding generation working on my machine, and I am able to call the APIs through the windows-rs crate.

Would you be willing to accept a PR adding the speech APIs? (Or better yet, to add them for me? I'm not certain that I can sign the CLA).

Thanks

**Comment by sotteson1** [comment]
We should be able to add them. I thought we had covered just about everything in the SDK but it looks like we missed that one.

**Comment by dgalling** [comment]
Sounds good, thanks.
