### ISSUE TITLE
Inconsistent use of pointers around COM interfaces

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#335]
The `CoCreateInstance` method takes a "raw" `IUnknown` parameter:

```
.method public hidebysig static pinvokeimpl("OLE32" nomangle winapi) 
	valuetype [Windows.Win32.winmd]Windows.Win32.Com.HRESULT CoCreateInstance (
		[in] valuetype [netstandard]System.Guid* rclsid,
		[in] [opt] class [Windows.Win32.winmd]Windows.Win32.Com.IUnknown pUnkOuter,
		[in] uint32 dwClsContext,
		[in] valuetype [netstandard]System.Guid* riid,
		[out] void** ppv
	)
```

Yet the `VARIANT` struct uses a pointer on COM interfaces:

```
	.field [0] public class [Windows.Win32.winmd]Windows.Win32.Com.IUnknown* ppunkVal
	.field [0] public class [Windows.Win32.winmd]Windows.Win32.Automation.IDispatch* ppdispVal
	.field [0] public valuetype [Windows.Win32.winmd]Windows.Win32.Automation.SAFEARRAY** pparray
	.field [0] public valuetype [Windows.Win32.winmd]Windows.Win32.Automation.VARIANT* pvarVal
```

Notice how it uses a pointer on VARIANT (a value type) as appropriate, but it also uses pointers on `IUnknown` and `IDispatch`, which are already reference types (being interfaces in the metadata), so no pointer should be needed here. 

This inconsistency is causing issues in CsWin32 where I seek to consistently assume that interface types will have an *implied* pointer or an explicit one in the metadata. I prefer the *implied* approach since it is what we would see in CLR metadata for references to interfaces.

Filed based on 10.0.19041.5-preview.27

**Comment by sotteson1** [comment]
I pretty sure that's by design because they are double pointers. Note that it's "ppunkVal". There's also a "punkVal" in the union which is correctly just IUnknown in the metadata.

**Comment by AArnott** [comment]
Oh. Thanks.
