### ISSUE TITLE
Missing VARTYPE constants used by VARIANT and PROPVARIANT

### ISSUE THREAD

**Issue by agausmann** [microsoft/win32metadata#338]
VT_EMPTY, VT_NULL, VT_I1, etc., which are defined in the [PROPVARIANT documentation](https://docs.microsoft.com/en-us/windows/win32/api/propidlbase/ns-propidlbase-propvariant). I don't know if that's a comprehensive list; I looked around for a list that was specific to VARIANT but couldn't find one.

**Comment by sotteson1** [comment]
There are in an enum: Windows.Win32.Automation.VARENUM
