### ISSUE TITLE
Missing STGM storage access constants / flags

### ISSUE THREAD

**Issue by agausmann** [microsoft/win32metadata#340]
Required for IMMDevice::OpenPropertyStore and IFunctionInstance::OpenPropertyStore.

- [STGM Constants](https://docs.microsoft.com/en-us/windows/win32/stg/stgm-constants)

**Comment by sotteson1** [comment]
I see these constants in the [latest version (39)](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/10.0.19041.5-preview.39).

**Comment by agausmann** [comment]
Oh I see, so this and #341 were probably fixed by #327 ? Sorry I didn't bother to check the latest release, I just noticed they were missing from windows-rs
