### ISSUE TITLE
Missing DEVICE_STATE_XXX constants

### ISSUE THREAD

**Issue by agausmann** [microsoft/win32metadata#341]
- [DEVICE_STATE_XXX Constants](https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-state-xxx-constants)

**Comment by sotteson1** [comment]
I see these constants in the [latest version (39)](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/10.0.19041.5-preview.39).
