### ISSUE TITLE
Direct3D9 imported into Direct2D namespace

### ISSUE THREAD

**Issue by weltkante** [microsoft/win32metadata#348]
I [mentioned](https://github.com/microsoft/win32metadata/issues/227#issuecomment-791031190) this as an offhand comment in #227 but considering its an incorrect import I'll re-raise as separate issue, so it can be priorized separately if necessary (it feels that a whole API in a wrong namespace is more important than sorting out the content of the API itself)

> The D3D9 interfaces (and some structs and API entry points) ended up in the Direct2D namespace, instead of the Direct3D9 namespace. Seems the D3D9 generator is currently broken.

**Comment by mikebattista** [comment]
Thanks for creating a separate issue.

We're working on a couple other issues first and then will get to both of these. I've added these to our High Priority Issues list.

**Comment by sotteson1** [comment]
Which stuff in Direct2D are you seeing that shouldn't be there? Looking with ILSpy I don't see anything that looks wrong, but I could be missing something.

**Comment by weltkante** [comment]
Seems to have been fixed by some other commit.
