### ISSUE TITLE
ID3DInclude should have a base interface type

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#349]
The `ID3DInclude` interface declares no base type:

```cs
public interface ID3DInclude
{
	unsafe HRESULT Open([In] D3D_INCLUDE_TYPE IncludeType, [In][Const] PSTR pFileName, [In][Const] void* pParentData, [In][Out] void** ppData, [In][Out] uint* pBytes);

	unsafe HRESULT Close([In][Const] void* pData);
}
```

Every(?) other interface ultimately derives from `IUnknown`. Why is this one different? Is this not a COM interface?

**Comment by kennykerr** [comment]
This is correct. Some API authors regrettably chose to deviate from COM conventions. This interfaces does not provide a way to control lifetime or interface discovery. There are a few other examples like this in the Windows API.

**Comment by AArnott** [comment]
Thanks. I guess this means the CLR couldn't produce an RCW for? I wonder what we would do instead.

@mikebattista Did we ever create a list of interesting cases so projection authors could verify correct behavior? If so, this API should probably be on it.

**Comment by kennykerr** [comment]
It's basically a group of callback functions. You presumably already support callbacks like `WNDENUMPROC`. This is basically the same thing but as member functions grouped in a vtable. Heap allocation is not required - you just need to ensure it outlives the API it is being used with.

**Comment by mikebattista** [comment]
Are there any changes required in the metadata here? Or is this just a special case that projections need to handle?

**Comment by kennykerr** [comment]
I think there's enough info here - there's not base interface - that's your clue.

**Comment by sotteson1** [comment]
It looks like this is an issue for language projections and not the metadata, so I'm closing it.
