### ISSUE TITLE
Duplicate Constant Definitions in Direct3D11

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#355]
In version 10.0.19041.5-preview.51, these constant values are duplicated in the Windows.Win32.Direct3D11 namespace:

* `WKPDID_D3DDebugObjectName`
* `WKPDID_D3DDebugObjectNameW`
* `WKPDID_CommentStringW`
* `D3D_TEXTURE_LAYOUT_ROW_MAJOR`
* `D3D_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE`

**Comment by AArnott** [comment]
This is still a problem even in preview.64 (which has your change). There are still duplicate constants: `WinUSB_TestGuid`
