### ISSUE TITLE
IUserConsentVerifierInterop method signature is not great

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#358]
The in/out flags for the last parameter as well as other attributes are missing or wrong, leading to poor codegen in CsWin32 (microsoft/CsWin32#141):

```diff
-actual
+expected

 [Windows.Win32.Interop.Guid(971002051u, 20084, 17434, 141, 192, 184, 17, 4, 223, 148, 156)]
 public interface IUserConsentVerifierInterop : IInspectable
 {
-  unsafe HRESULT RequestVerificationForWindowAsync([In] HWND appWindow, [In] HSTRING message, [In][Const] Guid* riid, [In][Out] void** asyncOperation);
+  unsafe HRESULT RequestVerificationForWindowAsync([In] HWND appWindow, [In] HSTRING message, [In][Const] Guid* riid, [Out, ComOutPtr, RetVal] void** asyncOperation);
 }
```

And what we ideally want to see is that the last parameter is typed as `Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.UserConsentVerificationResult>` to match what is apparently expected. 

Aside: is this interface really not defined in any existing WinRT ref assembly?

**Comment by kennykerr** [comment]
This is not a WinRT interface and cannot be defined or implemented purely as a WinRT interface because it depends on non-WinRT types (HWND). It must be expressed and implemented as a COM interface. The fact that it derives from IInspectable is red herring.

**Comment by AArnott** [comment]
What about the fact that it returns a generic interface? It isn't typed this way, but that's how it's used. I thought that was a WinRT-only capability.

**Comment by kennykerr** [comment]
```C++
    MIDL_INTERFACE("39E050C3-4E74-441A-8DC0-B81104DF949C")
    IUserConsentVerifierInterop : public IInspectable
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE RequestVerificationForWindowAsync( 
            /* [in] */ HWND appWindow,
            /* [in] */ HSTRING message,
            /* [in] */ REFIID riid,
            /* [iid_is][retval][out] */ void **asyncOperation) = 0;
        
    };
```

I don't know what you mean by generic interface. WinRT has generic interfaces but this isn't it. It may be that you query for a generic interface, but the signature is just a vanilla COM output parameter - exactly what you'd find on `CoCreateInstance`.

It's up to the caller to decide what they want to query for. Certainly if they want to query for `Windows.Foundation.IAsyncOperation<T>` then the caller needs to compute the GUID for that generic interface and pass it to the second-to-last parameter and so forth. Language projections that support both COM and WinRT can do this quite easily.

So in the sense that you need to know something about WinRT to *use* this interface effectively the answer is yes. But the interface itself is just a COM interface. C#/WinRT for example does not have any way to define this interface, so it would rely on something like C#/Win32 to do that.

**Comment by AArnott** [comment]
@mikebattista shared this as what we want to reproduce:

https://github.com/AdamBraden/WindowsInteropWrappers/blob/91f19c0a61299b27caed9e8adeb1bcd4131477bd/CoreWindowInterop/UserConsentVerifierInterop.cs#L23

Apparently this method returns an `IAsyncOperation<UserConsentVerificationResult>`, when that type richness can be expressed. But `IAsyncOperation` isn't even defined in the metadata (generic or not). Where is that interface defined?

**Comment by kennykerr** [comment]
You can find it's definition in the winmd files in this [nuget package](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) or on your computer's `C:\Windows\System32\WinMetadata` directory or copy it from [here in Rust](https://github.com/microsoft/windows-rs/tree/master/crates/gen/default).

**Comment by AArnott** [comment]
Then I guess the best we can do is either:
1. reference this winmd and type the API in the metadata to return this interface, OR
2. leave it to the user to figure this all out and cast `object` to `IAsyncOperation<UserConsentVerificationResult>`.

**Comment by kennykerr** [comment]
Also that example you shared is cheating. 😉 It lets you pass any GUID but jams the result into a vtable that may not match.

**Comment by kennykerr** [comment]
Yes, unless you provide integration with C#/WinRT I would just remove both trailing parameters and return an object that the caller can cast if they happen to also depend on C#/WinRT.

**Comment by AArnott** [comment]
The `riid` parameter may not be related to the returned object. You can see even in `CsWinRT` itself that it takes an `riid` but returns one typed interface unconditionally:

https://github.com/microsoft/CsWinRT/blob/0c7e84df3046e462092e794686125caabcc94704/src/Tests/TestComponentCSharp/TestComponentCSharp.idl#L362

**Comment by kennykerr** [comment]
That's also wrong. I had a quick look at the source code for this method inside the OS and it is a plain interface query.

**Comment by AArnott** [comment]
In that case, let this issue just track the attribute changes proposed for the out parameter in the diff of the issue description.

**Comment by mikebattista** [comment]
There are many similar interop APIs listed in #57. If there are changes required for this interop API, we should check if any similar changes are required in the others.

**Comment by mikebattista** [comment]
So after setting the TFM to get C#/WinRT and C#/Win32, will this code basically become:

`CoCreateInstance(
                    typeof(UserConsentVerifier).GUID,
                    null,
                    CLSCTX.CLSCTX_INPROC_SERVER,
                    typeof(IUserConsentVerifierInterop).GUID,
                    out IUserConsentVerifierInterop userConsentVerifierInterop).ThrowOnFailure();`

`await (IAsyncOperation<UserConsentVerificationResult>)userConsentVerifierInterop->RequestVerificationForWindowAsync(
                    (HWND)new WindowInteropHelper(Window.GetWindow(this)).Handle,
                    "Message");`

One issue I ran into stubbing out this code is that you can't await inside an unsafe context, which is currently required to interop here. Assuming we remove the need for unsafe in most cases, is the code above correct with the cast to IAsyncOperation<...>? Otherwise, would you need to store the returned operation outside the unsafe block, and then await outside the unsafe block? The code gets pretty messy there.

Also @AdamBraden and I just reviewed this and are considering adding friendly WinRT wrappers around this in Project Reunion. I think we would still support these COM interfaces for completeness and for those who want to just call these like any other COM API or not take a dependency on Project Reunion, but Reunion APIs that live in a similar namespace to the WinRT APIs they represent could provide a friendlier and/or more discoverable interface. In any case, in most cases I expect devs to just copy in whatever code our samples for the APIs recommend.
