### ISSUE TITLE
AS_ANY_TYPE contains enum value with no name

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#360]
```cs
public enum AS_ANY_TYPE : uint
{
	ASN_INTEGER = 2u,
	ASN_INTEGER32 = 2u,
	ASN_UNSIGNED32 = 71u,
	ASN_COUNTER64 = 70u,
	ASN_OCTETSTRING = 4u,
	ASN_BITS = 3u,
	ASN_OBJECTIDENTIFIER = 6u,
	ASN_SEQUENCE = 48u,
	 = 49u,
	ASN_IPADDRESS = 0x40u,
	ASN_COUNTER32 = 65u,
	ASN_GAUGE32 = 66u,
	ASN_TIMETICKS = 67u,
	ASN_OPAQUE = 68u,
	SNMP_EXCEPTION_NOSUCHOBJECT = 0x80u,
	SNMP_EXCEPTION_NOSUCHINSTANCE = 129u,
	SNMP_EXCEPTION_ENDOFMIBVIEW = 130u
}
```

**Comment by kennykerr** [comment]
Is there a build with this fix available?

**Comment by AArnott** [comment]
Yes, @kennykerr, this was fixed for https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/10.0.19041.5-preview.68

**Comment by kennykerr** [comment]
Thanks! Unfortunately 68 is unusable (for me) due to https://github.com/microsoft/win32metadata/issues/373. It doesn't look like there's yet a build for that.

**Comment by sotteson1** [comment]
75 just came out with a fix for both. Let me know if you run into issues. I'm about to leave town for a day but I'll keep on eye on how things are going.

**Comment by kennykerr** [comment]
And just like that it appears. Thanks @sotteson1!

**Comment by kennykerr** [comment]
That build looks great. Tested locally and it works well. But for some reason, GitHub doesn't like the new winmd binary and refuses to let me upload it. Very weird.

```
C:\git\windows-rs>git push
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 32 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 11.69 MiB | 168.63 MiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

**Comment by AArnott** [comment]
You're checking in binaries, @kennykerr? 😲

I'm afraid I have nothing more useful to offer. Maybe it finally got so big that github rejects it.

**Comment by kennykerr** [comment]
We don't have an alternative unfortunately. You're lucky in that .NET knows what a nuget package is. Rust has a different package format and to get something inside the package I need to stick it on GitHub. Think of GitHub as Rust's nuget.org backend. 

I believe GitHub's file limit is 100MB, so we have a way go to. 😄
