### ISSUE TITLE
PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#361]
There is a set of constants defined as follows:

```C++
#define PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION   2L
#define PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_1 1L
#define PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_2 2L
```

This is incorrectly being turned into an enum. What makes it worse, is that the `Windows.Win32.P2P` namespace contains both an enum named `PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION` and a constant (within the Apis class) with the same name. That confused me for a while. I was sure my parser was broken somehow. 😉

**Comment by kennykerr** [comment]
This false enum then goes and corrupts the `PEERDIST_STATUS_INFO` struct's definition. The idea is that the `PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION` constant is the value of the "current" version. I would suggest you don't turn this into an enum. 

But either way, there should be a validation check that forbids two definitions in the same namespace that have the same name. That's my biggest complaint here.

**Comment by sotteson1** [comment]
I agree there shouldn't be an enum and a constant named the same thing. I'm guarding against that happening with enum members but I need to check for enum type names too. But I can see why the scraper turned the two field members into an enum. The docs say both dwMinVer and dwMaxVer can only either be PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_1 or PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_2. Didn't the docs scraper make the right decision here?

So it seems like it should look like this:

```C#
public enum PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_VALUE : uint
{
	PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_1 = 1u,
	PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_2,
	PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION = PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_2
}

public struct PEERDIST_STATUS_INFO
{
	public uint cbSize;

	public PEERDIST_STATUS status;

	public PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_VALUE dwMinVer;

	public PEERDIST_RETRIEVAL_OPTIONS_CONTENTINFO_VERSION_VALUE dwMaxVer;
}
```

**Comment by kennykerr** [comment]
Yes, I didn't read the docs. That seems fine. So then the only bug is the inclusion of the constant (and guarding against that happening). Thanks!
