### ISSUE TITLE
BITMAPINFOHEADER should be in Windows.Win32.Gdi.Apis

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#366]
This is part of the GDI library:
   https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader

There are several copies in the metadata:

- `Windows.Win32.DirectShow.BITMAPINFOHEADER`
- `Windows.Win32.CoreAudio.KS_BITMAPINFOHEADER`
- `Windows.Win32.WindowsMediaDeviceManager._BITMAPINFOHEADER`

but its logical place is alongside its parent struct `Windows.Win32.Gdi.BITMAPINFO` and with APIs that use it like `CreateDIBitmap`.

**Comment by sotteson1** [comment]
I agree, Gdi would be a better place for BITMAPINFOHEADER. the KS_* structs appear to come from ksmedia.h, and those are correctly named as that's how they appear in the header. I don't know enough about that header to understand why they duplicated all those structs. The same is true for _BITMAPINFOHEADER which comes from mswmdm.h. I don't know why they duplicated the structs and put "_" in front of them, but someone did it intentionally. Maybe it's what they did to make their header co-exist with the existing GDI header without having some other things collide.

**Comment by sotteson1** [comment]
Hmm, on second thought after looking at the docs, this struct is used a lot in DirectShow video streaming. The struct could be in either DirectShow or Gdi as it's used by both. We picked DirectShow because that's what the docs page says it is:

UID: NS:wingdi.tagBITMAPINFOHEADER
title: BITMAPINFOHEADER (wingdi.h)
tech.root: dshow

**Comment by timsneath** [comment]
OK... 

I mean, it's in gdi.h, and it predates the existence of DirectShow -- it goes [at least as far back as Windows 3.1.](https://github.com/yeokm1/programming-win31/blob/a23b0b9bcd57dcaeaf14f93052b771b5b9392493/disk-files/CHAP13/SHOWDIB.C), but we can pretend it's part of DirectShow if you like 😛

**Comment by timsneath** [comment]
Ah... looking further, I think the documentation itself is broken. 

I think what might have happened is that the "original" version of this struct documentation has gotten orphaned, here: https://docs.microsoft.com/en-us/previous-versions/dd183376(v=vs.85)

The ["live" version of this page](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader) describes its use for video data, as per the note on that page. The ["original" version of this page](https://docs.microsoft.com/en-us/previous-versions/dd183376(v=vs.85)) includes some key information about the `biBitCount` and `biCompression` fields that is missing from the current version of the document. There's no reference to PNG or JPEG files on the live version of the doc, which instead talks about YUV video formats.

**Comment by kennykerr** [comment]
I would strongly vote for putting this in GDI - this is a very well-known and well-used GDI struct. It is still very relevant today while DirectShow is well ... I've never used it. 😉
