### ISSUE TITLE
SID struct not picked up correctly

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#367]
The `Windows.Win32.Security.SID` struct isn't used by APIs like `InitializeSid` or structs like `SECURITY_DESCRIPTOR`.

**Comment by sotteson1** [comment]
PSID is just void*:

winnt.h:
```typedef PVOID PSID;```

So there isn't really a structure to them. A pointer to the SID struct is defined as PISID in winnt.h. But I can turn the void*'s into native typedef structs named PSID with a single void*.

**Comment by timsneath** [comment]
Oh, that's interesting. The documentation says it's a pointer to [the `SID` structure](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-sid), but in fairness, the `SID` documentation _does_ say that you're not supposed to modify a SID directly. 

I withdraw my issue!

**Comment by sotteson1** [comment]
I always go to the headers first before the docs, as the headers are the real source of truth. :)
