### ISSUE TITLE
GetIconInfo improperly uses a 32-bit enum for the HICON parameter

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#368]
This can't be correct because the parameter should be handle-sized, not 32-bit.

Also, the parameter type should be called HICON like the other handle structs.
The enum members would be really nice as static readonly fields or properties on an HICON struct.

And eventually (https://github.com/microsoft/CsWin32/issues/199) there should be an implicit conversion from the HCURSOR I got from GetCursorInfo...CURSORINFO.hCursor, because I understand all HCURSORS are HICONS. I might be wrong about that absolute generalization, but at any rate, https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-geticoninfo#parameters explicitly says the HICON parameter is "A handle to the icon or cursor."

**Comment by sotteson1** [comment]
I could do that, but by the time I'm overriding types the enum has already been emitted, which we don't want. I would rather we weed it out of the json so the enum never gets written and it doesn't try to override the types. If you don't have a way to exclude it I can use my own exclusion list.

**Comment by jnm2** [comment]
Could enough information still be emitted so that CsWin32 can create static readonly struct members with the same names and values as the enum members would have been?

**Comment by sotteson1** [comment]
We are already emitting constants for thinks like IDC_WAIT. In this case, we just need to not emit an enum and not override the type for hIcon.

**Comment by sotteson1** [comment]
Debugging this some more, I'm realizing I need to know the type of the parameter/field before I can generate the enum so that I make sure the enum is based on the same type. Since I have to do this work anyway, I can throw away enums like this one that are trying to map values onto a non-integer type.
