### ISSUE TITLE
IMemoryBufferByteAccess is missing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#369]
This interface is missing. It should be in the WinRT namespace alongside the other WinRT interop APIs.

You can find its definition in `memorybuffer.h`.

**Comment by kennykerr** [comment]
A customer is asking about this missing interface. It's pretty important for WinRT I/O APIs and is blocking their adoption of metadata-based APIs.

**Comment by sotteson1** [comment]
I'll look into it.
