### ISSUE TITLE
ITypeLib.GetTypeComp is missing ComOutPtrAttribute

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#37]
I believe there may be many more methods that are missing the `ComOutPtrAttribute` attribute on its parameters.

**Comment by sotteson1** [comment]
This has an out as per its idl. Is good enough rather than turning it into ComOutPtr?

**Comment by kennykerr** [comment]
I just use in/out. I don't use ComOutPtrAttribute at all. I'm not sure why it exists.

**Comment by AArnott** [comment]
I think this was more relevant when the metadata expressed COM interfaces as structs (it did at one point, didn't it?). Now that it is obvious from the metadata that the out parameter type is an interface, I agree we don't need this.
