### ISSUE TITLE
MB_FLAGS should be unsigned flags

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#372]
* This enum is signed when it should be unsigned (the docs indicate the values are unsigned).
* This enum is a set of flags so should include the flags attribute.

**Comment by AraHaan** [comment]
I am bit by this as well.

**Comment by AraHaan** [comment]
@mikebattista any ETA until this might get fixed? No idea where it can be fixed at so far.

**Comment by AraHaan** [comment]
@sotteson1 was ID_TIMEOUT accidentally removed?

**Comment by sotteson1** [comment]
I don't think it belongs in this enum. It should be available as a constant. I see it at Windows.Win32.WindowsAndMessaging.Apis.IDTIMEOUT.

**Comment by AraHaan** [comment]
I see ok

**Comment by AraHaan** [comment]
Thanks for noticing a place where it is used 👌. Also will a new package with the change be pushed (I use it as a nuget package with CsWin32 as ``Version="*-*"`` where it auto consumes whatever the latest version is as soon as it's published to stay in sync).
