### ISSUE TITLE
ID2D1RenderTarget regression

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#373]
This is meant to be an interface not a struct. The latest version of the win32 winmd is completely broken for Rust.

```C#
[SupportedOSPlatform("windows6.1")]
[Guid(752420500u, 4834, 4572, 159, 237, 0, 17, 67, 160, 85, 249)]
public struct ID2D1RenderTarget
{
}
```

**Comment by kennykerr** [comment]
Maybe assert that interfaces don't derive from structs. I can't imagine C# likes that either. 😉 

![image](https://user-images.githubusercontent.com/9845234/111670672-52b04680-87d5-11eb-8c66-5bed25fd34a0.png)

**Comment by sotteson1** [comment]
Adding the SupportedOSPlatform attribute caused this bug. I already go to a lot of work to avoid this kind of thing happening (which is caused by interface forward declarations in the headers), but that code suddenly thought these weren't "empty" because of the extra attribute.

**Comment by marler8997** [comment]
The metadata broke pretty good with this change.  How was such a change able to get past testing?

**Comment by kennykerr** [comment]
@marler8997 this was fixed in the latest published version - it looks good to me. If you found a new problem please create a new issue.
