### ISSUE TITLE
Incorrect packing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#381]
CHOOSECOLORW has a packing of 1 when this only applies to 32 bit builds. It should not have any packing for 64 bit builds. Related to #363.

**Comment by sotteson1** [comment]
I should have always been building for 64-bit as I think that's the more common option, so I'll make that change.

But now that I can compare the builds between 32 and 64-bit, I'm worried that we are going to need two versions of the metadata, one for 32 and for 64. There a lot of differences between the two.

**Comment by kennykerr** [comment]
See this comment: https://github.com/microsoft/win32metadata/issues/363#issuecomment-801242146

**Comment by sotteson1** [comment]
I've read that. If we go the route of adding marker structs it's going to be a lot of work. Also, some APIs change their shape depending on 32 or 64 bit. Building a separate 32 bit winmd would get us there faster if 32 bit is a priority.

**Comment by kennykerr** [comment]
My main concern with that approach is that it's probably less than 1% of the winmd that's arch-specific. So we'd go from having 12 MB to 24 MB winmd overnight. That's a showstopper for me.

**Comment by sotteson1** [comment]
Isn't it like having arch-specific libs? It seems like a common way to do things. If someone only wants to build for 64-bit they can grab the 64-bit winmd, same for 32-bit. Just like with the WinSDK, you don't have to download both architectures (or more! ARM and ARM64) if you don't need them.

**Comment by kennykerr** [comment]
That's not the case for Rust. We don't have arch-specific packages. And we generate imports on the fly (like .NET). So we'd have to carry all of it all the time or force customers to build their own packages.

**Comment by sotteson1** [comment]
For now we'll be building the metadata for 64-bit. We need to figure out a 32-bit strategy, though.

**Comment by kennykerr** [comment]
Duplicate of #384
