### ISSUE TITLE
Nuget license and GitHub license are different

### ISSUE THREAD

**Issue by scottstephens** [microsoft/win32metadata#387]
The [license file in the repo](https://github.com/microsoft/win32metadata/blob/master/LICENSE) is the MIT License.

The license file link on the [nuget package page](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/) is [https://aka.ms/WinSDKPreviewLicenseURL](https://aka.ms/WinSDKPreviewLicenseURL). When I downloaded that today I got a preview_sdk_license.rtf file that forbids production use and that expired March 31, 2017.

**Comment by sotteson1** [comment]
I'm updating the license with the RTM WinSDK license. The license on GitHub and the metadata NuGet package are different because the metadata package is intended for use by apps the same way the WinSDK is used. The GitHub package doesn't have the same purpose so the license is different.
