### ISSUE TITLE
`LPPROC_THREAD_ATTRIBUTE_LIST` should be a Pointer, not an int

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#390]
See, for example:

```msil
.class public sequential ansi sealed beforefieldinit Windows.Win32.SystemServices.STARTUPINFOEXW
	extends [netstandard]System.ValueType
{
	// Fields
	.field public valuetype [Windows.Win32.winmd]Windows.Win32.SystemServices.STARTUPINFOW StartupInfo
	.field public native int lpAttributeList

} // end of class Windows.Win32.SystemServices.STARTUPINFOEXW
```

compared to:
```c
typedef struct _STARTUPINFOEXW {
  STARTUPINFOW                 StartupInfo;
  LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList;
} STARTUPINFOEXW, *LPSTARTUPINFOEXW;

typedef struct _PROC_THREAD_ATTRIBUTE_LIST *PPROC_THREAD_ATTRIBUTE_LIST, *LPPROC_THREAD_ATTRIBUTE_LIST;
```

**Comment by sotteson1** [comment]
"native int" is IL speak for IntPtr. After looking at the headers, I think I'll make a NativeTypedef for LPPROC_THREAD_ATTRIBUTE_LIST that wraps a void*.

**Comment by timsneath** [comment]
Yeah, there's a distinction in Dart (and potentially other languages), between an `IntPtr` (an int value that has the same width as a pointer address) and a `Pointer` (a smart pointer object). 

I believe ECMA-335 delineates between these two as `ELEMENT_TYPE_I` and `ELEMENT_TYPE_POINTER`. This one should be the latter, obviously.
