### ISSUE TITLE
SetWindowLongPtr/GetWindowLongPtr types are incorrect

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#392]
The return type of `GetWindowLongPtr` and the last parameter of `SetWindowLongPtr` are defined as `LONG_PTR` (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongptra) which is an integer type not a pointer type (a common mistake I've found).  However, in win32metadata it's defined as `IntPtr`.  What makes this a bit more convoluted is that `IntPtr` in the Clr can be used to represent both integer and pointer types.  However, win32metadata makes use of `IntPtr` to define the handle types which are pointer types ultimately defined as `PVOID`, so this reserves `IntPtr` to mean a "pointer type" rather than an integer type.

It's a bit of a mess and I actually don't know of a type that is equivalent to `LONG_PTR` in the CLR besides `IntPtr`.  One option would be to use actual pointer types for the handle types (and other various types) and reserve `IntPtr` and `UIntPtr` to be exclusive to integer types.

Another option is if win32metadata implements some way to restrict definitions to a particular architecture, then it could represent a type like `LONG_PTR` by providing architecture specific definitions (i.e. `Int32` for i386 and `Int64` for x86_64).

**Comment by marler8997** [comment]
Ok thanks for the clarification.  The fact that the metadata now uses the same type for handle types and LONG_PTR whereas before handle types were defined as `PVOID` may or may not pose some problems with some projections.  I'm going to close this issue and start treating `IntPtr` and `UIntPtr` as integral types.  If it causes problems to treat handles as integral types then I'll open a separate issue with the details.

**Comment by AArnott** [comment]
#21 may be relevant to your concerns, @marler8997.

**Comment by marler8997** [comment]
Thanks @AArnott that's exactly the issue I was describing.  Sounds like it's been solved for most cases.  The fact that handles use `IntPtr` and `UIntPtr` may or may not be an issue.  If I find an issue with it I'll report it there.
