### ISSUE TITLE
Define handle types as void* so they work with NULL

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#395]
Handles types in win32 are opaque for the most part, except for the `NULL` value.  In this case, the win32 documentation describes handle values as being `NULL` which in some languages is only compatible with pointer types (i.e. the return value of GetModuleHandle).  For this reason I propose that instead of defining handles types as `IntPtr` (which is an integer type, not a pointer type as it appears to be from its name), win32metadata defines them as `void*` (which is a type that is already used throughout the metadata).

As of today, these are the following handle values I've seen that this would apply to:

<details>
<pre>
HANDLE
HICON
HCURSOR
HBRUSH
HSYNTHETICPOINTERDEVICE
HPROPSHEETPAGE
HIMAGELIST
HTREEITEM
HCOLORSPACE
HCRYPTASYNC
HCERTCHAINENGINE
HCOMDB
HKEY
HWINWATCH
HWINSTA
HDESK
HSTRING
HSZ
HCONV
HCONVLIST
HDDEDATA
HRASCONN
HAMSICONTEXT
HAMSISESSION
HCMNOTIFICATION
HKL
HIFTIMESTAMPCHANGE
HWSAEVENT
HTASK
HWINEVENTHOOK
HUIANODE
HUIAPATTERNOBJECT
HUIATEXTRANGE
HUIAEVENT
HMIDI
HMIDIIN
HMIDIOUT
HMIDISTRM
HMIXER
HMIXEROBJ
HWAVE
HWAVEOUT
HWAVEIN
HMMIO
HDRVR
HACMDRIVERID
HACMDRIVER
HACMSTREAM
HACMOBJ
HIC
HVIDEO
HSWDEVICE
HINTERACTIONCONTEXT
HRAWINPUT
HRECOALT
HRECOCONTEXT
HRECOGNIZER
HRECOLATTICE
HRECOWORDLIST
HIMC
HIMCC
HSAVEDUILANGUAGES
HRSRC
HSURF
HINSTANCE
HPOWERNOTIFY
HUMPD
HSTR
HSPRITE
HSEMAPHORE
HLSURF
HFASTMUTEX
HDRVOBJ
HDEV
HBM
HPCON
HMENU
HACCEL
HDROP
HPSXA
HDC
HGDIOBJ
HBITMAP
HRGN
HPEN
HBRUSH
HFONT
HMETAFILE
HENHMETAFILE
HMONITOR
HPALETTE
HWND
HHOOK
HGESTUREINFO
HTOUCHINPUT
HGLRC
HFILTER
HPTPROVIDER
HPSS
HPSSWALK
</pre>
</details>

**Comment by AArnott** [comment]
Handles are not pointers. They are pointer-sized opaque values. To type them as pointers in the metadata would be inaccurate. If for a given language this leads to such a poor experience that you'd make the other call, that's a choice that should be made in that language projection.

I feel like this is already adequately discussed here: https://github.com/microsoft/win32metadata/issues/21#issuecomment-811157583

**Comment by marler8997** [comment]
> To type them as pointers in the metadata would be inaccurate. 

I don't understand, if they are not pointers then how do you account for all the documentation saying that they can be NULL?

**Comment by AArnott** [comment]
As is stated in the comment I linked to, `NULL` is *not* a pointer type in C. It's `0` (an integer)

**Comment by marler8997** [comment]
> As is stated in the comment I linked to, NULL is not a pointer type in C. It's 0 (an integer)

I've never heard of `NULL` being defined as the integer values `0`.  There may be implementations that define it that way.  I've seen it defined as `(void*)0`, but I've never heard of it being used intentionally as an integer type.  Everywhere I've seen it's described as the values of a "null pointer".  Can you point to where C defines `NULL` as `0`?  Or at least, where in the win32 documentation it describes `NULL` as being defined as `0`?  Also, why would all the documentation use `NULL` instead of just `0`?

**Comment by AArnott** [comment]
> I've never heard of developers using NULL to mean the integer value 0.

I haven't either. But it doesn't change the fact that handles are not pointers, or that `NULL` is an integer.

I can't say any of these points more clearly than has already been said here and in the comment linked, and I think expressing handles as pointers in the metadata would be a mistake. Again, you're welcome to translate them however you like in your projection.

**Comment by AArnott** [comment]
I didn't mean to close. If you'd like to, you're welcome to. Otherwise I'll leave it to another owner of the repo to weigh in.

**Comment by marler8997** [comment]
I think we should get someone from the `C++` projection and the `Rust` projection to weight in before we close.  If they agree that handles should be represented as integer values in the metadata then I'm clearly outvoted.

I've seen a couple people say they think using a pointer would be worse but I don't think I seen anyone explain why that is.  It seems that using a pointer would make the metadata match what the original win32 API does more closely, so I'm not understanding why it would we worse.

**Comment by marler8997** [comment]
> I haven't either. But it doesn't change the fact that handles are not pointers, or that NULL is an integer.

Again, where are you getting this?  Everywhere I've seen `NULL` is described as a pointer value not an integer value.

**Comment by marler8997** [comment]
I may have misunderstood something.  Is the currently accepted proposal that `IntPtr` be used for handle types an no other types?  If so then I would be fine with that, but then that would also mean modifying the definitions of SetWindowLongPtr and GetWindowLongPtr correct?

I feel like I'm ping-ponging back and forth a bit and getting contradictory answers. I originally opened this issue (https://github.com/microsoft/win32metadata/issues/142) which indicated that SetWindowLongPtr and GetWindowLongPtr were using the incorrect type `IntPtr` but I was told by @sotteson1 that `IntPtr` was an integer type, but then in #21 it sounds like it was established that `IntPtr` is not an integer type, but is actually a handle type.  If that's the case then re-reading (https://github.com/microsoft/win32metadata/issues/21#issuecomment-811157583) actually make sense now, I originally read it assuming that `IntPtr` was an integer type which is what was confusing me. So, is it the case that `SetWindowLongPtr` should be using `nint` instead of `IntPtr`, and that `IntPtr` is reserved for handles only?

**Comment by kennykerr** [comment]
@marler8997 can you clarify your concern here, perhaps with a few concrete examples from the languages you're concerned about?  Andrew and Steve are C# experts and I represent Rust and C++. We came up with the current approach for representing handles and think it works quite well in all of the languages we have worked with. If there is a concrete scenario that doesn't work we'd love to have a look at it.

**Comment by marler8997** [comment]
>  We came up with the current approach for representing handles and think it works quite well in all of the languages we have worked with.

It's not clear to me what the approach is, depending on what it is there may be no issue.  I think alot will be cleared up by clarifying what `IntPtr` is supposed to be.  Is it an integer type or exclusive to handle types or something else?

**Comment by kennykerr** [comment]
The metadata is defined by [ECMA-335](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/). There it states that an `IntPtr` is "Signed integer, native size". Languages can interpret this and represent it however they wish, provided the ABI (memory layout) is preserved. In Rust this translates to `isize` and in C++ it would be something like `ptrdiff_t`. It is used for handles but is not exclusive to handles.

**Comment by marler8997** [comment]
@kennykerr, ok, so then when using the `C++` and `Rust` projections, are you expecting developers to use `0` to set handles to `NULL`?

**Comment by kennykerr** [comment]
Rust preserves the handle type so you would write something like `HANDLE(0)` or `HANDLE::default()`. Here's an example:

https://github.com/microsoft/windows-rs/blob/443c8265cb53925a1637ecd665b25e51f414170b/examples/overlapped/src/main.rs#L11-L19

**Comment by marler8997** [comment]
@kennykerr, if Rust is able to preserve the handle type then there's clearly enough information to make this a non-issue.  How does the rust projection do that?  Does it handle all NativeTypedef's this way by making them wrappers around the underlying type?  Or maybe it handles some types that way and other types as direct aliases?

**Comment by kennykerr** [comment]
The metadata defines handles as structs. Rust represents those with the `NativeTypedef` attribute as tuple structs for convenience.

**Comment by marler8997** [comment]
I believe the metadata defines all `NativeTypedef`'s as structs.  So does that mean all your NativeTypedef's are wrapper types?  So `PWSTR` is a struct around `char*`?

**Comment by kennykerr** [comment]
Check it out for yourself. 😉

**Comment by marler8997** [comment]
I found this: https://github.com/microsoft/windows-rs/blob/443c8265cb53925a1637ecd665b25e51f414170b/examples/clock/src/main.rs

I see this `lpszClassName: PSTR(b"window\0".as_ptr() as _),` and this ` if wparam.0 != SIZE_MINIMIZED as usize {`.  So it looks like the answer is yes?  Can you confirm?

**Comment by marler8997** [comment]
The fundamental issue I see here is that both the `LONG_PTR` and handle types are being mapped to the same type `IntPtr` in the metadata.  This is a one-way mapping which means a projection can't determine whether an `IntPtr` type came from a `LONG_PTR` type (an integer type) or a Handle type.

Furthermore, it looks like the maintainers are fine with diverging from the win32 documentation and using `0` for handle values rather than the target language's value for null pointers.  In `C#` this would be `IntPtr.Zero` or `new IntPtr(0)` and in rust this would be `HANDLE(0)` or `HANDLE::default()`.  I'm not sure I agree with this choice but I can't change people's minds.  Since maintainers are ok with this, this issue becomes void so I'm closing it.

**Comment by kennykerr** [comment]
Yes, they're all strongly typed structs.
