### ISSUE TITLE
mshtml.h and Debug

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#396]
Doing some analysis on the metadata and I noticed that the `Debug` namespace is by far the largest. Then I noticed that it contains a bunch of stuff originating from `mshtml.h` that clearly has no business being there. Can we get rid of these or move them elsewhere?

**Comment by sotteson1** [comment]
Looks like this file is covered by some old docs, so our scraper didn't give us a good place for it. According to https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/hh801968(v=vs.85), it mshtml.h is for IE. How about Windows.Win32.InternetExplorer?

**Comment by kennykerr** [comment]
Sounds good to me - thanks!
