### ISSUE TITLE
FindClose receive a Handle type different than the returned by FindFirstFile

### ISSUE THREAD

**Issue by bsonnino** [microsoft/win32metadata#399]
When you start a file enumeration with FindFirstFile. it returns a handle of type FindCloseSafeHandle, but this type is not compatible with FindClose, which receives a handle of type HANDLE. So this code:
```C#
var handle = PInvoke.FindFirstFile("*.*", out var findData);
bool result;
do
{
    result = PInvoke.FindNextFile(handle, out findData);
} while (result);
PInvoke.FindClose(handle);
```
Doesn't compile. An alternative to it would be:
``` C#
using var handle = PInvoke.FindFirstFile("*.*", out var findData);
bool result;
do
{
    result = PInvoke.FindNextFile(handle, out findData);
} while (result);
```
But this is not as explicit as using FindClose

**Comment by bsonnino** [comment]
That was what I was expecting - FindFirstFile and FindClose use the same type of handle.

I think that, when the metadata is fixed, CsWin32 will generate the same type of handle, no ?

**Comment by AArnott** [comment]
Yes, CsWin32 will follow the metadata. But recent metadata updates may include breaking changes in other areas so updating the metadata version may require updates to CsWin32 as well.

**Comment by bsonnino** [comment]
Ok, thanks. If you need something from me, feel free to ask, as Win32 APIs is something I like to play :-)
