### ISSUE TITLE
COM methods suffixed with 'A'

### ISSUE THREAD

**Issue by weltkante** [microsoft/win32metadata#400]
Followup to #290 with some more offenders (I literally iterated over all methods not in an `Apis` type ending with captial `A`). I'm fairly confident thats all of them now. The check has been run against `10.0.19041.5-preview.122`

* [Windows.Win32.Mmc.IConsole::MessageBoxA](https://docs.microsoft.com/en-us/windows/win32/api/mmc/nf-mmc-iconsole-messagebox)
* [Windows.Win32.NetworkPolicyServer.ISdoServiceControl::StartServiceA](https://docs.microsoft.com/en-us/windows/win32/api/sdoias/nf-sdoias-isdoservicecontrol-startservice)
* [Windows.Win32.Tapi.ITRendezvous::CreateDirectoryA](https://docs.microsoft.com/en-us/windows/win32/api/rend/nf-rend-itrendezvous-createdirectory)
* [Windows.Win32.Com.IOleInPlaceActiveObject::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-ioleinplaceactiveobject-translateaccelerator)
* [Windows.Win32.Com.IOleInPlaceFrame::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-ioleinplaceframe-translateaccelerator)
* [Windows.Win32.Com.IOleControlSite::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-iolecontrolsite-translateaccelerator)
* [Windows.Win32.Com.IPropertyPage::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-ipropertypage-translateaccelerator)
* [Windows.Win32.Com.IPropertyPageSite::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/ocidl/nf-ocidl-ipropertypagesite-translateaccelerator)
* [Windows.Win32.WindowsMediaPlayer.IWMPPluginUI::TranslateAcceleratorA](https://docs.microsoft.com/en-us/previous-versions/aa391100(v%3Dvs.85))
* [Windows.Win32.Shell.IShellView::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellview-translateaccelerator)
* [Windows.Win32.Shell.IPreviewHandler::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ipreviewhandler-translateaccelerator)
* [Windows.Win32.Shell.IPreviewHandlerFrame::TranslateAcceleratorA](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ipreviewhandlerframe-translateaccelerator)
* [Windows.Win32.Shell.ISyncMgrSyncCallback::ReportEventA](https://docs.microsoft.com/en-us/windows/win32/api/syncmgr/nf-syncmgr-isyncmgrsynccallback-reportevent)
* [Windows.Win32.Debug.IHTMLEditDesigner::TranslateAcceleratorA](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa704060(v=vs.85))

**Comment by mikebattista** [comment]
Thanks for the analysis. We'll clean these up.

**Comment by sotteson1** [comment]
Thanks for find the rest of those @weltkante!
