### ISSUE TITLE
Native / NT API

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/win32metadata#404]
While it is not technically part of the win32 API, the native API (see ntdll.dll) is part of the usable API surface of windows, and is linked into every application.

I believe it should be included in the metadata distributed in this repo (maybe only optionally included in downstream libraries?) and it fits well with the "maximum API coverage" goal for this project.

Some potential use cases off the top of my head include kernel fuzzers and programs which need to start early in startup process as well as learning more about windows internals or just those wanting to create bare metal windows / extremely backwards compatible applications.

**Comment by kennykerr** [comment]
This seems related to #401

**Comment by Ben-Lichtman** [comment]
This is unrelated - the native api can be called in user mode or kernel mode.

**Comment by kennykerr** [comment]
Practically speaking, this project is limited to APIs that are published in headers shipped by some Microsoft product like the Windows SDK or the WDK. If you can point out where the APIs can be found (which headers) then Steve can comment on whether those can be added.

**Comment by Ben-Lichtman** [comment]
Some of the native API is exposed via winternal.h but that metadata seems to already be exposed.

For the rest there are no official headers to be found - there are unofficial headers if you go looking though...

So go guess the undocumented functionality will stay hidden?

**Comment by kennykerr** [comment]
Yes, we don't have the ability to publish undocumented APIs. If there are APIs you think are important to surface, you can probably get some visibility on that request by [creating an issue here](https://github.com/microsoft/ProjectReunion/issues).

**Comment by mikebattista** [comment]
Agreed that we will not add undocumented APIs.
