### ISSUE TITLE
`DEVMODEW` and `DEVMODEA` in different namespaces

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#405]
Respectively:

- `Windows.Win32.DisplayDevices.DEVMODEW`
- `Windows.Win32.Xps.DEVMODEA`

This struct is used by GDI for `CreateDC`, which long predates XPS. I would think they both belong in somewhere like `Windows.Win32.SystemServices`.

**Comment by sotteson1** [comment]
The docs has it under "Display Devices Reference" which is why DEVMODEW is under DisplayDevices. I'll move DEVMODEA to the same namespace.

**Comment by sotteson1** [comment]
This has been fixed with the latest version.
