### ISSUE TITLE
`HBITMAP` needs the `AlsoUsableFor("HANDLE")` attribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#406]
The result of `CreateCompatibleBitmap`, `HBITMAP`, is meant to be passed to `GetObjectA`, expecting a `HANDLE`.

**Comment by sotteson1** [comment]
Looking at the docs, I would say that GetObjectA/W should take an HGDIOBJ instead of a HANDLE, like GetObjectType/SelectObject do. I don't know why the original API takes a HANDLE but it seems wrong.
