### ISSUE TITLE
`RoParseTypeName` missing from metadata

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#408]
The `rometadataresolution.h` and `rometadataapi.h` headers aren't populated in the metadata. `roapi.h` and `roerrorapi.h` are there, however. 

See this page for an example that is missing:
https://docs.microsoft.com/en-us/windows/win32/api/rometadataresolution/nf-rometadataresolution-roparsetypename

**Comment by mikebattista** [comment]
@sotteson1 the headers are being scanned as part of the WinRT partition, but these functions are not being emitted. Do you know why that is?

**Comment by timsneath** [comment]
I tried to work on this over the weekend, but was unsuccessful. 

These header files are commented out:
https://github.com/microsoft/win32metadata/blob/4cbf805e7374307f5a46247eef7d7bae017d626f/generation/WinSDK/Partitions/WinRT/main.cpp#L31-L32

When uncommented, the issue is that they both depend on `Cor.h`:
```cpp
#include <cor.h>
```

But `Cor.h` is defined in the .NET Framework 4.8 SDK. What's worrying is that .NET 4.8 is now rapidly heading down the path of obsolescence, and the file is not included in modern .NET SDKs. As a result, we're rapidly getting to the point where the very unmanaged APIs required to use the generated WinMD file will be unavailable.

There's evidence that this was supposed to be resolved prior to some RTM deadline, but that this didn't occur. From cor.h itself:
```cpp
// <STRIP>The following definitions will get moved into <windows.h> by RTM but are
// kept here for the Alpha's and Beta's.</STRIP>
#ifndef _WINDOWS_UPDATES_
#include <corhdr.h>
#endif // <windows.h> updates
```

I also found this StackOverflow article which suggests that `Cor.h` was included in the Windows SDK for RS1, but has subsequently gotten removed. 
https://stackoverflow.com/questions/45391076/cannot-include-header-file-rometadataresolution-h 

It feels important that the Windows SDK unmanaged APIs which make it possible to load Windows metadata are available in the win32metadata project. 

Would it be possible to add the necessary files into https://github.com/microsoft/win32metadata/tree/main/generation/WinSDK/RecompiledIdlHeaders/um or something like that?

**Comment by mikebattista** [comment]
See https://github.com/microsoft/win32metadata/issues/240#issuecomment-1469479334.
