### ISSUE TITLE
LoadMenuIndirectW takes a `MENUTEMPLATEW *`, not a `void *`

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#412]
Weird one this. Technically, the metadata is accurate as per the C header:

```c
typedef VOID MENUTEMPLATEW;
```

But in practice,

> A menu template consists of a MENUITEMTEMPLATEHEADER structure followed by one or more contiguous MENUITEMTEMPLATE structures. ([source](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadmenuindirectw)) 

I suspect this could be defined as a `struct` that mirrors the documentation...

**Comment by sotteson1** [comment]
> Weird one this. Technically, the metadata is accurate as per the C header:
> 
> ```c
> typedef VOID MENUTEMPLATEW;
> ```
> 
> But in practice,
> 
> > A menu template consists of a MENUITEMTEMPLATEHEADER structure followed by one or more contiguous MENUITEMTEMPLATE structures. ([source](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadmenuindirectw))
> 
> I suspect this could be defined as a `struct` that mirrors the documentation...

But then the docs continue:
> An extended menu template consists of a MENUEX_TEMPLATE_HEADER structure followed by one or more contiguous MENUEX_TEMPLATE_ITEM structures.

I don't think I can model a struct that looks like both of these. That's probably why they use MENUTEMPLATEW* which like you said is defined to be a void*.

**Comment by timsneath** [comment]
Musing... you could do that as a `union`, couldn't you? 


Something like 


```c
struct MENUTEMPLATEW {
  union {
    struct {
      MENUITEMTEMPLATEHEADER mitHeader;
      MENUITEMTEMPLATE[] miTemplate;
    };
    struct {
      MENUEX_TEMPLATE_HEADER mexHeader;
      MENUEX_TEMPLATE_ITEM[] mexItem;
    };
  }
}
```

(Not a C programmer... I just play one at the weekends. 😀)

**Comment by mikebattista** [comment]
I could see us adding the extended menu item structures to the metadata since those aren't defined in headers, but I'm not sure about changing the signature away from void* as that would deviate from the original definition.

**Comment by mikebattista** [comment]
I added the extended structs as well as your union definition but didn't remap the API parameter for now. Try it out and if it works properly we can consider remapping the API to take the union.

```
public struct MENUTEMPLATEEX
{
	[StructLayout(LayoutKind.Explicit)]
	public struct _Anonymous_e__Union
	{
		public struct _Menu_e__Struct
		{
			public MENUITEMTEMPLATEHEADER mitHeader;

			[FlexibleArray]
			public MENUITEMTEMPLATE[] miTemplate;
		}

		public struct _MenuEx_e__Struct
		{
			public MENUEX_TEMPLATE_HEADER mexHeader;

			[FlexibleArray]
			public MENUEX_TEMPLATE_ITEM[] mexItem;
		}

		[FieldOffset(0)]
		public _Menu_e__Struct Menu;

		[FieldOffset(0)]
		public _MenuEx_e__Struct MenuEx;
	}

	public _Anonymous_e__Union Anonymous;
}
```
