### ISSUE TITLE
CreateHwndRenderTarget has ID2D1HwndRenderTarget* as last parameter, should be ID2D1HwndRenderTarget**

### ISSUE THREAD

**Issue by bastos80** [microsoft/win32metadata#415]
Direct2D's ID2D1Factory.CreateHwndRenderTarget signature seems to be wrong. It currently seems to take a `ID2D1HwndRenderTarget*` as a last parameter. I consume the metadata using CsWin32, where the parameter type is translated to an `object`. If I supply null in c#, the call understandably throws an exception. If I supply a boxed IntPtr, the runtime crashes.

**Expected behavior**

The last parameter is specified as `ID2D1HwndRenderTarget** hwndRenderTarget` in the API documentation. I.e: it should return the created rendertarget objects interface. I would expect the last parameter to be of the type `ID2D1HwndRenderTarget**`

**Most other Direct2D calls seem to have this problem as well.**

**Comment by sotteson1** [comment]
We encode interfaces with a level of indirection removed from the C signature, because an interface already implies a pointer. So if you see ID2D1HwndRenderTarget* this means if it were translated into C, it's a pointer to a pointer, or ID2D1HwndRenderTarget**. So, this is by design.
