### ISSUE TITLE
Missing EventDataDescCreate

### ISSUE THREAD

**Issue by Awfa** [microsoft/win32metadata#416]
I can't seem to find [EventDataDescCreate](https://docs.microsoft.com/en-us/windows/win32/api/evntprov/nf-evntprov-eventdatadesccreate) in the released metadata thru ILSpy.

Is this a missing API?

**Comment by sotteson1** [comment]
Looking at envtprov.h, this is a function with code in it, not a DLL import. Anything with code isn't a good fit for metadata, because we would need to emit IL and then language projections would have to decode the IL and convert it into their language.

```C
VNTPROV_PFORCEINLINE
VOID
EventDataDescCreate(
    _Out_ PEVENT_DATA_DESCRIPTOR EventDataDescriptor,
    _In_reads_bytes_(DataSize) const VOID* DataPtr,
    _In_ ULONG DataSize
    )
{
    EventDataDescriptor->Ptr = (ULONGLONG)(ULONG_PTR)DataPtr;
    EventDataDescriptor->Size = DataSize;
    EventDataDescriptor->Reserved = 0; // Reserved MUST be initialized.
    return;
}
```
