### ISSUE TITLE
Functions like `LoadCursorA` need a "DoNotRelease" attribute to indicate the return type should not be freed

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#422]

**Comment by AArnott** [comment]
Duplicate of #244, but you may want to add the functions you have in mind to that bug.

**Comment by kennykerr** [comment]
Steve asked me to add this.

**Comment by AArnott** [comment]
Does this mean we're now using *both* options debated in #244?

**Comment by kennykerr** [comment]
I think Steve just wanted a reminder to deal with this case as well, but I'm not sure what Steve's decided to do about such cases in general.
