### ISSUE TITLE
`DPI_AWARENESS_CONTEXT_*` values missing

### ISSUE THREAD

**Issue by robmikh** [microsoft/win32metadata#425]
Values used with [`SetProcessDpiAwarenessContext`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) appear to be missing from the latest metadata. [`DPI_AWARENESS_CONTEXT`](https://docs.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context) itself is defined, but is represented like other handles. Values like `DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2` or `DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED` are missing. It could be worth representing this as an enum.

**Comment by robmikh** [comment]
The `DPI_AWARENESS_CONTEXT_*` values can be found in windef.h

**Comment by sotteson1** [comment]
It's weird the API author modeled these as handles instead of an enum. Since the underlying size is IntPtr and not int or uint, I can't make it an eum. I will have to make these constants of type DPI_AWARENESS_CONTEXT.
