### ISSUE TITLE
Add HID Usages values

### ISSUE THREAD

**Issue by ajtribick** [microsoft/win32metadata#428]
It would be nice to have the `HID_USAGE_PAGE` and `HID_USAGE` values as described [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/hid-usages) to be generated, currently these enumerations appear to be missing.

**Comment by mikebattista** [comment]
@sotteson1 is this something the constant scraper should be scraping?

**Comment by sotteson1** [comment]
Yes once I write the code for it. I’ve been adding some new types the last couple days but I still need to do this one.
