### ISSUE TITLE
An attribute to indicate struct size fields

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#433]
Many structs like `WNDCLASSEXA` have a size field that should be initialized with the size of the struct. If there were an attribute on such fields, language projections could automatically initialize this field. 

First reported here: https://github.com/microsoft/windows-rs/issues/722

**Comment by AArnott** [comment]
Also requested here: https://github.com/microsoft/CsWin32/issues/108

**Comment by mikebattista** [comment]
If we do anything here, we could detect structs with `cbSize` and automatically add the attribute. We could then fix up the emitter manually for other cases.

**Comment by kennykerr** [comment]
We could place the attribute on the struct rather than on the field with the path to the size field. Perhaps something like: 

```C#
[StructSizeField("StartupInfo.cb")]
struct STARTUPINFOEXW { ... }
```

**Comment by mikebattista** [comment]
Is this instead of trying to automatically tag things with cbSize fields? We would add these attributes manually?

**Comment by AArnott** [comment]
I think @KalleOlaviNiemitalo is pointing out odd cases where the field isn't even on the struct itself. The assumption I was making when suggesting we just look at field name to get us 80% of the way there was that the field would be on the same struct it describes. But in the cases called out above, that isn't necessarily the case, so whatever mechanism the metadata may use to describe these fields should ideally be able to describe these corner cases, such that even if they have to be specially described in an .rsp file in this repo, the projections could then do the Right Thing.
