### ISSUE TITLE
D3D_FEATURE_LEVEL shouldn't be in Windows.Win32.Direct3D11 namespace

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#439]
This enum is shared between multiple versions of Direct3D (ie D3D11 and D3D12) and so shouldn't be tightly bound to one of them.  It should be possible to use D3D12 without using types from the D3D11 namespace.

This same comment probably applies to other types obtained from d3dcommon.h.  Maybe a Direct3D namespace would be the right thing?

**Comment by mikebattista** [comment]
Is the recommendation to move everything in d3dcommon.h to Windows.Win32.Graphics.Direct3D?

**Comment by mikebattista** [comment]
That's perfect. Yes it's very straightforward to assign a header file to a namespace. See https://github.com/microsoft/win32metadata/blob/master/CONTRIBUTING.md#Namespaces.

**Comment by mikebattista** [comment]
We could also use some review of https://github.com/microsoft/win32metadata/blob/master/generation/emitter/requiredNamespacesForNames.rsp which is the file that maps individual APIs to namespaces if they don't make sense where the header itself is assigned.

In particular, all the graphics and media-related mappings in this file like the d* headers as well as the mf* and mm* headers. Do you agree with where they're mapped? Or should we remove these mappings so they just follow the namespace of the header file? A lot of these were split off based on how the documentation categorized them as a starting point.

**Comment by damyanp** [comment]
Thanks!  It's looking like I'll be able to spend some more time on this in June.  We should probably find someone to comment on the mf* and mm* headers - I'll be more focused on the d* ones.

**Comment by mikebattista** [comment]
A few other headers that need analysis:

* d3dcaps.h
* d3dnthal.h
* d3dtypes.h
* ddrawgdi.h

These are all in namespaces that I'm trying to get rid of.

**Comment by damyanp** [comment]
@mikebattista / @kennykerr - I'm wondering about whether or not we should aim to make the D3D namespace dependencies by acyclic.  For the most part, this is the case, however there's at least one case where this isn't true - D3D11on12.h depends on D3D11 and D3D12 types.

I think this could come into play when language projections start thinking about providing pre-generated code and we try and figure out how we want to slice it.  Given a preference, we'd like to be able to separate D3D11 from D3D12 as much as possible.  This suggests to me that we'd want a separate D3D11on12 namespace.

Any thoughts on this?

**Comment by damyanp** [comment]
First pass proposals here: #579.

**Comment by kennykerr** [comment]
> This suggests to me that we'd want a separate D3D11on12 namespace

Yep, that seems to make sense. Avoiding cycles is a worthy goal.

**Comment by mikebattista** [comment]
@damyanp is there any more refactoring required here or can we close this out?
