### ISSUE TITLE
List view messages are missing

### ISSUE THREAD

**Issue by Balkoth** [microsoft/win32metadata#440]
Add LVM_GETHEADER to NativeMethods.txt, and the following error message is displayed with no constant being generated:

Warning	PInvoke001	Method or type "LVM_GETHEADER" not found.

**Comment by sotteson1** [comment]
It looks like they're there as constants. Are you looking to have them collected into an enum?

**Comment by Balkoth** [comment]
I think they should be handled just like the other constants. The CsWin32 project specifies the following: Constants are defined on the `Microsoft.Windows.Sdk.Constants` class. I don't know if its best to group such messages/constants together in an enum and leave that up for discussion.

For me the most important thing is consistency.

**Comment by sotteson1** [comment]
@AArnott, this constant is on the Windows.Win32.UI.Controls.Apis class. Should it be showing up in Microsoft.Windows.Sdk.Constants?

**Comment by AArnott** [comment]
Ah, this is simply a matter of the metadata version CsWin32 brings in didn't have it, but you have since added it.
@balkoth, this will be fixed when CsWin32 picks up the latest metadata.
