### ISSUE TITLE
OLEMISC_ACTSLIKEBUTTON

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#442]
`OLEMISC_ACTSLIKEBUTTON` constant appears in both `Apis` calls as well as in `OLEMISC` enum.

**Comment by sotteson1** [comment]
It looks like the headers define both the constant and the enum with the same value. Should I exclude the constants in favor of the enum?

**Comment by kennykerr** [comment]
Same for all the other `OLEMISC_xxx` constants. Yes, I think we should only have a single definition. Either typed constants or enums, but not both. The enums are probably preferred by most languages. 

I'm looking into C/C++ compat and I'm hitting a lot of issues like this that make it impossible to support. Ideally there's a test to flush out any enum fields that collide with namespace-level names, but I'll create a few more issues for what I uncover.

**Comment by sotteson1** [comment]
I do have a test that avoids duplicating scraped constants and enums we create from those constants, but when the headers expose both we expose both since that's what's in the headers. We'll have to manually exclude one or the other (I would think we would prefer the enums over the constants).

**Comment by kennykerr** [comment]
That would be great. I tried manually including both SDK headers in C++ and it fails to compile if you try to use both.

**Comment by kennykerr** [comment]
Here's an issue for when the synthesized enums introduce duplicates at namespace scope: https://github.com/microsoft/win32metadata/issues/443 ... a bunch of `None` constants are colliding.

**Comment by kennykerr** [comment]
Here's another example - this enum is defined in both `DbgHelp.h` and `ImageHlp.h`:

```C++
enum {
    sevInfo = 0,
    sevProblem,
    sevAttn,
    sevFatal,
    sevMax  // unused
};
```

The metadata has them defined both as constants in the `Apis` class and in a synthesized `IMAGEHLP_CBA_EVENT_SEVERITY` enum.

**Comment by kennykerr** [comment]
Another example from the SDK:

```C++
typedef enum
{
    WDS_CLI_MSG_START = 0,
    WDS_CLI_MSG_COMPLETE,
    WDS_CLI_MSG_PROGRESS,
    WDS_CLI_MSG_TEXT,
};
```

These show up as both constants in the `Apis` class and as members of a synthesized `PFN_WDS_CLI_CALLBACK_MESSAGE_ID` enum.

**Comment by kennykerr** [comment]
Another example is `IPPROTO_TCP` which shows up both a macro #define and a member of an enum. Prefer the enum - discard the macro. I'll stop reporting these unless - I suspect you can find the rest pretty easily.
