### ISSUE TITLE
Synthesized enums must have unique constant names

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#443]
Win32 enums are designed and named with the assumption that no qualification is required. This stems from how C-style enums work and manifests in developers expecting to write code like this:

```rust
let barrier_type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
```

Not having to qualify the code with `D3D12_RESOURCE_BARRIER_TYPE::D3D12_RESOURCE_BARRIER_TYPE_TRANSITION` makes it much easier to port existing code for languages like C++ and Rust. 

This works fine for Win32 enums defined in the Windows SDK but I've noticed that some of the synthesized enums don't conform and thus break compatibility with such languages. 

For example, the `NMHEADERW` is originally defined as follows:

```C++
typedef struct tagNMHEADERW
{
    NMHDR   hdr;
    int     iItem;
    int     iButton;
    HDITEMW *pitem;
} NMHEADERW, *LPNMHEADERW;
```

The `iButton` field is then changed to use a synthesized enum that's defined as follows metadata:

```C#
public enum HEADER_CONTROL_NOTIFICATION_BUTTON : uint
{
	None,
	iButton1,
	iButton2
}
```

The enum itself isn't a problem, but the names are problematic because they are not likely to be unique. I'm not sure why these names were chosen. The [documentation](https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-nmheaderw) simply refers to left/right/middle but at the very least they should be given names like `HEADER_CONTROL_NOTIFICATION_BUTTON_NONE`, `HEADER_CONTROL_NOTIFICATION_BUTTON1`, etc. That will ensure compat with languages like C, C++, and Rust where constants often end up sharing the namespace scope.

**Comment by kennykerr** [comment]
Thanks for marking #442 and #443 as blocking - indeed the use of enums to group large amounts of constants has become prohibitive as it forces the generation of often thousands of lines of unused code (e.g. `WIN32_ERROR`) when in most cases only a small number of constants, or none, are required. If we can ensure that these are unique, I can simply treat them as namespace level constants just like those that are generated in the `Apis` class and the developer can filter out what they need. It also ends up being far more usable in C++ and Rust when you don't have to rely on such long and wordy qualified constants.

**Comment by sotteson1** [comment]
What about enums that aren't synthesized? While working on this I noticed these two enums we scrape from MLOperatorAuthor.h that use identical field member names with different values:

````C++
enum class MLOperatorAttributeType : uint32_t 
{
    //! Undefined (unused)
    Undefined = 0,

    //! 32 bit floating point
    Float = 2,

    //! 64 bit integer
    Int = 3,

    //! String
    String = 4,

    //! Array of 32 bit floating point values
    FloatArray = 7,

    //! Array of 64 bit floating integer values
    IntArray = 8,

    //! Array of string values
    StringArray = 9
};

//! \enum MLOperatorTensorDataType
//! \brief Specifies the data type of a tensor.
//! Each data type numerically matches corresponding ONNX types.
enum class MLOperatorTensorDataType : uint32_t
{	
    //! Undefined (unused).
    Undefined = 0,

    //! IEEE 32 bit floating point 
    Float = 1,

    //! 8 bit unsigned integer
    UInt8 = 2,

    //! 8 bit signed integer
    Int8 = 3,

    //! 16 bit unsigned integer
    UInt16 = 4,

    //! 16 bit signed integer
    Int16 = 5,

    //! 32 bit signed integer
    Int32 = 6,

    //! 64 bit signed integer
    Int64 = 7,

    //! String (unsupported)
    String = 8,

    //! 8 bit boolean. Values other than zero and one result in undefined behavior.
    Bool = 9,

    //! IEEE 16 bit floating point
    Float16 = 10,

    //! 64 bit double-precision floating point
    Double = 11,

    //! 32 bit unsigned integer
    UInt32 = 12,

    //! 64 bit unsigned integer
    UInt64 = 13,

    //! 64 bit Complex type (unsupported)
    Complex64 = 14,

    //! 128 bit complex type (unsupported)
    Complex128 = 15
};
````

**Comment by kennykerr** [comment]
Sigh. So those use `enum class` rather than `enum`. This makes these enums explicitly incompatible with C as enum classes are new to C++11. Can we distinguish between traditional Win32 enums and these C++ enums perhaps with an attribute? C++11 enum classes are explicitly scoped like WinRT enums, whereas traditional C enums are explicitly unscoped. If there's an attribute to indicate that these are scoped enums then we can know that these don't have to be unique within the enclosing namespace.

**Comment by sotteson1** [comment]
>  If there's an attribute to indicate that these are scoped enums then we can know that these don't have to be unique within the enclosing namespace.

Sure, I can do that.

I found some non-class enums that have some generically-named members. These are just a few examples. The first both have "None" which fortunately is 0 in both cases, but "None" as a constant isn't a great name. A lot of these names as constants aren't too good either.

````C
typedef 
enum MetadataBit
    {
        None	= 0,
        IsValueHandle	= 0x1,
        IsPropertyReadOnly	= 0x2,
        IsValueCollection	= 0x4,
        IsValueCollectionReadOnly	= 0x8,
        IsValueBindingExpression	= 0x10,
        IsValueNull	= 0x20,
        IsValueHandleAndEvaluatedValue	= 0x40
    } 	MetadataBit;

typedef 
enum MSVidCCService
    {
        None	= 0,
        Caption1	= ( None + 1 ) ,
        Caption2	= ( Caption1 + 1 ) ,
        Text1	= ( Caption2 + 1 ) ,
        Text2	= ( Text1 + 1 ) ,
        XDS	= ( Text2 + 1 ) 
    } 	MSVidCCService;

typedef /* [v1_enum] */ 
enum CameraUIControlMode
    {
        Browse	= 0,
        Linear	= ( Browse + 1 ) 
    } 	CameraUIControlMode;

typedef /* [v1_enum] */ 
enum CameraUIControlLinearSelectionMode
    {
        Single	= 0,
        Multiple	= ( Single + 1 ) 
    } 	CameraUIControlLinearSelectionMode;

typedef /* [v1_enum] */ 
enum CameraUIControlCaptureMode
    {
        PhotoOrVideo	= 0,
        Photo	= ( PhotoOrVideo + 1 ) ,
        Video	= ( Photo + 1 ) 
    } 	CameraUIControlCaptureMode;

typedef /* [v1_enum] */ 
enum CameraUIControlPhotoFormat
    {
        Jpeg	= 0,
        Png	= ( Jpeg + 1 ) ,
        JpegXR	= ( Png + 1 ) 
    } 	CameraUIControlPhotoFormat;
````

**Comment by kennykerr** [comment]
Yes these are very unfortunate, but they exist in C and thus require the developer to be careful not to include colliding headers. We can mitigate that by having them in separate namespaces.

**Comment by kennykerr** [comment]
Or even better, you could somehow detect these and "promote" them to scoped enums! 😉

**Comment by sotteson1** [comment]
Here's the change I'm making:
* Add [ScopedEnum] to the enums above that have poorly named members.
* Do not emit constants that are already in enums.
* Modified the test to make sure constants and enum members don't conflict.

**Comment by kennykerr** [comment]
Thanks!

**Comment by sotteson1** [comment]
I just published a new one. Besides lots of fixes this version has a lot of namespace refactoring by @mikebattista.

**Comment by kennykerr** [comment]
Thanks! The latter is going to keep me busy for a while. 😉

**Comment by kennykerr** [comment]
@sotteson1 I tried creating a scoped enum for a test component but it doesn't appear to matter whether I use `enum` or `enum class` in C++ it always ends up unscoped. e.g.

https://github.com/microsoft/windows-rs/blob/e89054ab4a3ef55bfe5c5ca9ab1b4a89f4374ccd/tests/component/simple.h#L27-L31

**Comment by sotteson1** [comment]
Unfortunately the scraper doesn't predict whether an enum should have the ScopedEnum attribute. It has to be applied manually as data fed into the emitter. Let me see if there's a way to do that with a project using the external msbuild scraper and I'll let you know what I figure out.

**Comment by kennykerr** [comment]
And what about other types like those with the `NativeTypedef` attribute? How could I define my own? I tried something like this:

```C++
typedef void* SimpleHandle;
```

But that seems to be ignored.

**Comment by sotteson1** [comment]
Those also have to be defined manually. I'm working on some documentation for the different options you can add to response files that help facilitate things like this.

**Comment by kennykerr** [comment]
Any word on this?

**Comment by sotteson1** [comment]
I've added some more information here: https://github.com/microsoft/win32metadata/blob/master/docs/generationOptions.md

I am missing a couple things there like the autotypes, so I'll work on that.

But maybe the best way to see what's possible is looking at this sample: https://github.com/microsoft/win32metadata/tree/master/sources/GeneratorSdk/samples/GeneratorSampleDebug

I've tried to include all of the different things you can do, including adding handle types, enum, scraped constants, recompiled idl files, etc. It would probably be worth documenting this sample to show the options it's exercising.

Let me know if there's something in particular you would like to see better explained.
