### ISSUE TITLE
Move SystemServices namespace to System.SystemServices.

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#447]
I hit some errors trying to do this myself. This will make it consistent with the rest of the namespaces after the refactoring.

**Comment by marler8997** [comment]
> ... the refactoring.

What's the refactoring that I should be expecting?

**Comment by mikebattista** [comment]
You'll see in the next winmd build. Or you can build yourself and see what's there. We are reorganizing the namespaces.
