### ISSUE TITLE
`ITransactionImport`'s Import method should have `const` `Guid` parameter

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#449]
The `Windows.Win32.ComponentServices.ITransactionImport` has an `Import` method that behaves like `IUnknown`'s `QueryInterface` in that it lets you request a specific interface to be returned. The second-to-last `Guid` parameter should be `const` to match the pattern correctly and indicate that it is not mutable.

**Comment by sotteson1** [comment]
That's easy to fix. I was wondering, what's difference to your projection with a parameter marked [In] vs. [In][Const]? It seems like [In] without [Out] would also imply [Const] but maybe there's a difference.

**Comment by kennykerr** [comment]
Because the parameter - `[In] Guid* piid` - has a pointer then if there's no `const` it implies that the pointer is mutable. In Rust, you must declare every pointer either `mut` or `const`. If mutable, the caller assumes the function may change the memory in some way even if the pointer value itself is not changed. So I take the presence of pointers and the absence of `const` to mean a mutable pointer.
