### ISSUE TITLE
DhcpEnumSubnets, DHCP_IP_ARRAY issues

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#452]
The [`DhcpEnumSubnets` method](https://docs.microsoft.com/en-us/windows/win32/api/dhcpsapi/nf-dhcpsapi-dhcpenumsubnets) fourth parameter `EnumInfo` is an array:

```c
LPDHCP_IP_ARRAY* EnumInfo
```

but the metadata only describes it as

```cs
[In][Out] DHCP_IP_ARRAY** EnumInfo
```

As a result, in CsWin32 we declare it with `ref DHCP_IP_ARRAY*`, which makes it rather cumbersome to use.
In C# what I think would make the most sense is `out Span<DHCP_IP_ARRAY>`. To get there we need to strike the `[In]` attribute from the metadata, and attribute it as a native array rather than just a "pointer to one".

Also looking at `DHCP_IP_ARRAY`, its `Elements` member is an array but is only declared in metadata as `uint*`. It should be declared with `NativeArrayInfoAttribute` or something, shouldn't it? Then we could expose it as `uint[]` for a much more usable API.

**Comment by sotteson1** [comment]
I think it's doing the right thing with EnumInfo. It doesn't point to an array.
LPDHCP_IP_ARRAY is typedef'ed DHCP_IP_ARRAY*
So LPDHCP_IP_ARRAY* is DHCP_IP_ARRAY**. You give the API a pointer to a pointer (EnumInfo) and it allocates memory for it and sets EnumInfo to it. The caller then has to call DhcpRpcFreeMemory on *EnumInfo, according to the docs.

DHCP_IP_ARRAY::Elements needs [NativeArrayInfo(CountParamIndex = 0)] to show it's array like you say.

**Comment by AArnott** [comment]
Thanks. Yes, I agree with your analysis. But we still need a fix to remove the `[In]` attribute from that parameter.

**Comment by sotteson1** [comment]
The original SAL annotation is _Inout_, but it does seem like it should be just out.

**Comment by mikebattista** [comment]
@AArnott, is the only change here to remove [In]?

**Comment by mikebattista** [comment]
Windows.Win32.NetworkManagement.Dhcp.Apis.DhcpEnumSubnets : EnumInfo : [In,Out] => [Out]

**Comment by mikebattista** [comment]
Looks like DHCP_IP_ARRAY::Elements already has the NativeArrayInfo attribute.

```
public struct DHCP_IP_ARRAY
{
	public uint NumElements;

	[NativeArrayInfo(CountParamIndex = 0)]
	public unsafe uint* Elements;
}
```
