### ISSUE TITLE
Additional struct(s) missing

### ISSUE THREAD

**Issue by markterluun** [microsoft/win32metadata#453]
The occurrance that I came across was with the GetMonitorInfo function, which can take a parameter of either the MONITORINFO struct or the MONITORINFOEX struct. The source code generator only includes the MONITORINFO struct.

**Comment by mikebattista** [comment]
I see the ExA and ExW structs defined, but the GetMonitorInfo APIs only accept MonitorInfo. Is that what you're seeing?

**Comment by riverar** [comment]
`MONITORINFOEX` structure exists in metadata, so doesn't appear to be an issue here. Closing. Did you mean to file a report in CsWin32? https://github.com/microsoft/CsWin32
