### ISSUE TITLE
Unable to generate .winmd file

### ISSUE THREAD

**Issue by wmgries** [microsoft/win32metadata#454]
I am no longer able to generate the .winmd file. I'm not sure at what point this broke, but it's impacting my ability to keep my PR #438 up-to-date with master. 

I thought at first this issue was related to my PR, but I can repro it on master. When I execute the DoAll.ps1 script, I receive the following error along with the attached [output](https://github.com/microsoft/win32metadata/files/6403364/output.txt).

```
Write-Error: C:\Users\wgries\source\win32metadata\DoAll.ps1:37
Line |
  37 |  .\scripts\BuildMetadataBin.ps1 -arch $arch
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to build .winmd.
```

Aside from the errors all out the end, I didn't see any obvious issues along the build process that would explain what's going on. I also haven't made changes directly on my local master branch.

I have the most recent .NET previews installed:

```
PS> dotnet --list-sdks
2.1.815 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

PS> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I haven't had time to sit down and debug what's going on here, but it doesn't appear to be related to anything I'm doing. Any insight into what's going on? 

Happy to provide any additional information needed to troubleshoot.

**Comment by sotteson1** [comment]
It failed to write the .winmd because of all the errors in the output, such as:

````C:\Users\wgries\source\win32metadata\generation\emitter\obj\crossarch\generated\arm64\Http.modified.cs(214,55): error CS0234: The type or namespace name 'IServiceProvider' does not exist in the namespace 'Windows.Win32.SystemServices' (are you missing an assembly reference?)````

Recently Windows.Win32.SystemServices got changed to Windows.Win32.System.SystemServices, so the output makes me think you're missing an update or that a resolve went bad.

**Comment by mikebattista** [comment]
I just built master from https://github.com/microsoft/win32metadata/commit/efbbba9ca12b7e6ff1b6c0420804924f492b7004 and it built just fine. I did have to add `-Clean` to avoid some errors triggered by stale state on my system that conflicts with recent namespace refactoring. Can you try `./DoAll.ps1 -Clean`?

**Comment by wmgries** [comment]
I hit an error related to a small typo in a PowerShell script, however, I have fixed this, and am able to successfully build. Here's the PR for the PS fix: https://github.com/microsoft/win32metadata/pull/459.

I'll leave it to you on whether to close or leave open until this PR is resolved :)

**Comment by mikebattista** [comment]
I merged your bug fix. Closing out and glad to hear you can build now.
