### ISSUE TITLE
`enclaveapi.h` functions refer to wrong DLL in some cases

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#455]
The SDK libs have incorrect DLL entries for some of these functions. They should all be imported from `kernelbase` - ideally the metadata can correct these.

**Comment by kennykerr** [comment]
Or just exclude the APIs in `enclaveapi.h` as they aren't intended to be used.

**Comment by mikebattista** [comment]
Where do you see they aren't meant to be used?

There are 3 enclave headers in SystemServices that I was considering moving out to a Security.Enclave namespace: Winenclaveapi.h, Enclaveapi.h, ntenclv.h.

I don't see "don't use these" in any of the docs for these headers.

**Comment by mikebattista** [comment]
Followed up with Kenny and the feature team offline. These headers are very niche with some runtime and ecosystem oddities that means we're better off excluding them all for now.
