### ISSUE TITLE
Namespace balancing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#456]
Creating a separate issue because I don't want to detract from the great work that's been done to rename and organize namespaces. As I look at a recent internal build, there is still a very wide discrepancy in the size of some of the namespaces. Here are the ten largest Win32 namespaces:

Namespace | Entries
-- | --
Windows.Win32.System.SystemServices | 14139
Windows.Win32.Security | 6517
Windows.Win32.Media.Multimedia | 3972
Windows.Win32.UI.Shell | 3050
Windows.Win32.Globalization | 2898
Windows.Win32.UI.Controls | 2739
Windows.Win32.Media.MediaFoundation | 2609
Windows.Win32.Graphics.DirectShow | 2208
Windows.Win32.UI.WindowsAndMessaging | 2160
Windows.Win32.Media.Audio.CoreAudio | 2149

By contrast here are the largest WinRT namespaces:

Namespace | Entries
-- | --
Windows.UI.Xaml.Controls | 1219
Windows.UI.Xaml | 302
Windows.UI.Xaml.Automation.Peers | 297
Windows.UI.Composition | 275
Windows.UI.Xaml.Media.Animation | 250
Windows.Media.Capture | 237
Windows.UI.Xaml.Media | 223
Windows.Networking.NetworkOperators | 212
Windows.Devices.PointOfService | 209
Windows.Media.Core | 206

Even the monstrous Xaml.Controls namespace is barely over 1000 entries (and that's a problem for most languages today). 

I'm not sure what can be done to tame these huge namespaces, but its worth calling out.

**Comment by mikebattista** [comment]
I've gone through all the headers in SystemServices and believe that will cease to exist when I'm done with it.

Security has opportunity to align with how Windows.Security namespaces are defined.

Some of these others like MF, CoreAudio, Globalization, etc. might just be large areas that don't make sense to split up further.

What would be helpful is if you suggest how the headers that make up these namespaces should be factored out.

**Comment by kennykerr** [comment]
Sure, where can I see the headers?

**Comment by kennykerr** [comment]
And take those numbers with a grain of salt. WinRT lack functions and constants, so it looks worse than it is. 😉

**Comment by mikebattista** [comment]
In general, search for the namespace name in settings.rsp files in the repo. These files list header -> namespace mappings. For example, https://github.com/microsoft/win32metadata/blob/master/generation/scraper/Partitions/CoreAudio/settings.rsp for CoreAudio.

**Comment by kennykerr** [comment]
Thanks, I had a look but I'm not sure what more to suggest.

**Comment by mikebattista** [comment]
Ok. The API design reps may be able to help refactor things somewhat.

The two highest offenders (SystemServices and Security) will definitely be split up into smaller namespaces at least.

**Comment by kennykerr** [comment]
OK. Perhaps we should get another release going in the meantime, once any other planned renames have stabilized.

**Comment by mikebattista** [comment]
SystemServices, Security, and WindowsProgramming are the 3 biggest refactors I have planned.

**Comment by kennykerr** [comment]
Closing this issue as the namespaces seem to be settled.
