### ISSUE TITLE
Combining flags is inconvenient for some enum types

### ISSUE THREAD

**Issue by ennis** [microsoft/win32metadata#466]
For instance, the `BindFlags` field of `D3D11_TEXTURE2D_DESC` is defined as UINT, and expects a or-combination of `D3D11_BIND_FLAG` values.  However, the inner values of `D3D11_BIND_FLAG` are i32, which makes it a bit noisy to use. For instance:

```rust
let texture_desc = D3D11_TEXTURE2D_DESC {
            BindFlags: (D3D11_BIND_FLAG::D3D11_BIND_RENDER_TARGET.0
                | D3D11_BIND_FLAG::D3D11_BIND_SHADER_RESOURCE.0) as u32,
            MiscFlags: (D3D11_RESOURCE_MISC_FLAG::D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX.0
                | D3D11_RESOURCE_MISC_FLAG::D3D11_RESOURCE_MISC_SHARED_NTHANDLE.0) as u32,
   // ...
};
```

Instead, something along those lines would be ideal (along with the proposal of microsoft/windows-rs#727):
```rust
let texture_desc = D3D11_TEXTURE2D_DESC {
            BindFlags: D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE,
            MiscFlags: D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX |  D3D11_RESOURCE_MISC_SHARED_NTHANDLE,
   // ...
};
```
but I don't know how feasible this is.

**Comment by kennykerr** [comment]
Transferring to the `win32metadata` repo.

**Comment by MarijnS95** [comment]
:flags:

**Comment by ennis** [comment]
It seems that this is the case for most of the fields and parameters that take a combination of `D3D11_*_FLAG` enumerators.

**Comment by MarijnS95** [comment]
Bummer. Is this something that can be fixed in the windows headers (could be a breaking API change...) or is it all supposed to be overridden in the metadata?
