### ISSUE TITLE
Please add extsfns.h

### ISSUE THREAD

**Issue by dpaoliello** [microsoft/win32metadata#468]
Related to adding debugger support (#462), please add `extsfns.h`: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/extsfns/

This header allows a debugger extension to hook into the `!analyze` debugger extension.

**Comment by mikebattista** [comment]
Do you know what kit this comes from today? I don't see it in the SDK.

**Comment by mikebattista** [comment]
Ah. Thanks. I was looking under "Include" where everything else is including the other debugging related headers I added. Those seem to be duplicated in both places but extsfns.h is only under Debuggers.

**Comment by mikebattista** [comment]
@sotteson1 can we include this extsfns.h in our C++ SDK NuGet packages?

This is an outlier in that it's in the Debuggers folder not the Include folder so is not included in those packages today. We'd need to include this in the SDK packages before we can incorporate into the metadata.
