### ISSUE TITLE
cannot find type `userHMETAFILEPICT` in module `super::SystemServices`

### ISSUE THREAD

**Issue by ennis** [microsoft/win32metadata#469]
The bindings generated with: 
```
fn main() {
    windows::build!(
        Windows::Win32::Com::*,
    );
}
```
fail to compile, with the following errors:
```
error[E0412]: cannot find type `userHMETAFILEPICT` in module `super::SystemServices`
     --> target\debug\build\windows-rs-test-68d9817207d358cf\out/windows.rs:47256:64
      |
47256 |                 pub hMetaFilePict: *mut super::SystemServices::userHMETAFILEPICT,
      |                                                                ^^^^^^^^^^^^^^^^^ not found in `super::SystemServices`
error[E0412]: cannot find type `userHENHMETAFILE` in module `super::SystemServices`
     --> target\debug\build\windows-rs-test-68d9817207d358cf\out/windows.rs:47257:64
      |
47257 |                 pub hHEnhMetaFile: *mut super::SystemServices::userHENHMETAFILE,
      |                                                                ^^^^^^^^^^^^^^^^ not found in `super::SystemServices`
```

**Comment by kennykerr** [comment]
Also, I'm not sure if these userXxx types should even exist in metadata. `userSTGMEDIUM` is not a public type as far as I can tell. The documented type is `STGMEDIUM`. Perhaps this is similar to those other MIDL-generated types that should just get stripped out?

**Comment by kennykerr** [comment]
Any word on a fix for this? Ran into this again.

**Comment by sotteson1** [comment]
I think the scraper is correctly representing what's in objidl.h. I have no idea what the struct is trying to accomplish, but when I compile it with C++, I also only see the pUnkForRelease member.

````C++
typedef struct _userSTGMEDIUM
    {
    struct _STGMEDIUM_UNION
        {
        DWORD tymed;
        /* [switch_is] */ /* [switch_type] */ union __MIDL_IAdviseSink_0003
            {
            /* [case()] */  /* Empty union arm */ 
            /* [case()] */ wireHMETAFILEPICT hMetaFilePict;
            /* [case()] */ wireHENHMETAFILE hHEnhMetaFile;
            /* [case()] */ GDI_OBJECT *hGdiHandle;
            /* [case()] */ wireHGLOBAL hGlobal;
            /* [case()] */ LPOLESTR lpszFileName;
            /* [case()] */ BYTE_BLOB *pstm;
            /* [case()] */ BYTE_BLOB *pstg;
            } 	u;
        } 	DUMMYUNIONNAME;
    IUnknown *pUnkForRelease;
    } 	userSTGMEDIUM;
````

**Comment by KalleOlaviNiemitalo** [comment]
If `defined(NONAMELESSUNION) || !defined(_MSC_EXTENSIONS)`, then ntdef.h defines `DUMMYUNIONNAME` as `u`, and `userSTGMEDIUM` has the data members `u` and `pUnkForRelease`.

Otherwise, ntdef.h defines `DUMMYUNIONNAME` as nothing, and the only data member of `userSTGMEDIUM` is `pUnkForRelease`. The inner struct does not become the type of an [anonymous struct data member](https://docs.microsoft.com/en-us/cpp/build/reference/microsoft-extensions-to-c-and-cpp?view=msvc-160#data-declarations-and-definitions) because it has the `_STGMEDIUM_UNION` name.

I think it is a bug in ObjIdl.Idl; whether `NONAMELESSUNION` is defined should not affect sizeof(userSTGMEDIUM). The `_STGMEDIUM_UNION` name should not exist.

**Comment by sotteson1** [comment]
> I think it is a bug in ObjIdl.Idl; whether `NONAMELESSUNION` is defined should not affect sizeof(userSTGMEDIUM). The `_STGMEDIUM_UNION` name should not exist.

You're right, it looks like a bug in objidl.idl. Right above it, the definition for uSTGMEDIUM makes sure the size is the same for both when NONAMELESSUNION is defined and when it isn't. I can either exclude this type or make sure NONAMELESSUNION is set when scraping this type.

**Comment by mikebattista** [comment]
@sotteson1 where would you define NONAMELESSUNION?
