### ISSUE TITLE
Duplicate struct entries in Windows.Win32.UI.Shell

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#471]
![image](https://user-images.githubusercontent.com/2319867/117909809-c92a6b80-b28f-11eb-8db8-94f7516686a0.png)

Comparing the two instances of `NOTIFYICONDATAW`, for example, one struct is listed as packed (`.pack 1`), the other is missing packing information.

**Comment by marler8997** [comment]
The duplicates are expected.  They are variants with different architectures.  See the "SupportedArchitectureAttribute" to see which architectures the definitions are for.

Note that ILSpy may not print the architecture (mine says `/*Could not decode attribute arguments.*/`), you can checkout my JSON projection of the metadata to see the various definitions per architecture. https://raw.githubusercontent.com/marlersoft/win32json/main/api/UI.Shell.json

**Comment by kennykerr** [comment]
This should solve the ILSpy issue: https://github.com/microsoft/win32metadata/issues/472

**Comment by timsneath** [comment]
Gotcha -- thank you @marler8997. I missed that. And what new layer of Dante's hell is this where structs are packed on one architecture and not on another?! Going to have to think about whether I can easily wrap this for my target language, or whether I just give up on 32-bit altogether.
