### ISSUE TITLE
IMAGE_FILE_HEADER Machine field using enum with wrong bit width

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#473]
The `Machine` field in the `IMAGE_FILE_HEADER` struct is defined as a 16-bit `WORD` (see https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_file_header).  However, in the metadata, the `Machine` field is defined as an `IMAGE_FILE_MACHINE` enum, whose base integer type is a 32-bit `uint`.

My guess is either the `IMAGE_FILE_MACHINE` enum needs to use a `ushort` as its base integer type, or `IMAGE_FILE_HEADER` needs to use a different type for it's `Machine` field.

related issue: https://github.com/marlersoft/win32jsongen/issues/1

**Comment by mikebattista** [comment]
@sotteson1 is this possibly a systemic issue with the enum scraper where `WORD` fields are being mapped to `uint` enums?

Or is this just a matter of changing the type of the `IMAGE_FILE_MACHINE` enum?

**Comment by sotteson1** [comment]
The type of IMAGE_FILE_MACHINE just needs to be updated in enums.json.
