### ISSUE TITLE
Absence of some TSF constants

### ISSUE THREAD

**Issue by JeanCASPAR** [microsoft/win32metadata#478]
I was unabled to find in the doc the values that correspond to category constants, like GUID_TFCAT_TIP_KEYBOARD or 
GUID_TFCAT_DISPLAYATTRIBUTEPROVIDER, but it may be because they are not referenced, because the documentation doesn't reference them here : https://docs.microsoft.com/en-us/windows/win32/tsf/predefined-category-values, although there are referenced in other pages like https://docs.microsoft.com/en-us/windows/win32/api/msctf/ns-msctf-tf_inputprocessorprofile under catid.
I didn't find the CLSID_TF_InputProcessorProfiles and CLSID_TF_CategoryMgr constants either, among other.
These constants are all declared in the msctf.h header file.

Is there any way to find/use/add them ?

**Comment by mikebattista** [comment]
@sotteson1 we're scanning the header as part of the TSF partition. Any idea why these aren't getting picked up?

**Comment by sotteson1** [comment]
Unfortunately these are all defined in the header as extern GUIDs that come from a lib. They GUID values aren't in headers anywhere that we can parse these values in the SDK.

**Comment by sotteson1** [comment]
I'm going to add these manually since they aren't there in the headers to be scraped.
