### ISSUE TITLE
MEMORY_BASIC_INFORMATION, MEMORY_BASIC_INFORMATION32 and MEMORY_BASIC_INFORMATION64

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#479]
I can only find `MEMORY_BASIC_INFORMATION` in the public docs site. So why does the metadata contain this struct as well as `MEMORY_BASIC_INFORMATION32` and `MEMORY_BASIC_INFORMATION64` structs?

The `MEMORY_BASIC_INFORMATION` struct is declared twice, with an `[SupportedArchitecture]` attribute on each. But only the 64-bit one declares the `State` field with the enum type `VIRTUAL_ALLOCATION_TYPE` even though the field size is the same in both cases.

* [ ] Fix 32-bit declaration of `MEMORY_BASIC_INFORMATION.State` to be typed as `VIRTUAL_ALLOCATION_TYPE`.

Then we have the `MEMORY_BASIC_INFORMATION32` and `MEMORY_BASIC_INFORMATION64` struct declarations in the metadata which are more primitive, using non-pointer integer types and no enum types for fields. Why are these structs even present? And why does `MEMORY_BASIC_INFORMATION64` have an extra `__alignment2` field at the end that the 64-bit `MEMORY_BASIC_INFORMATION` struct lacks? Which is correct?

* [x] The `MEMORY_BASIC_INFORMATION` vs `MEMORY_BASIC_INFORMATION??` struct inconsistencies are fixed or one set are removed.

In fact generating multiple structs regardless of target CPU architecture is an [interesting area](https://github.com/microsoft/CsWin32/issues/264#issuecomment-841322768) but we should be consistent in the metadata as to whether we do it there or if projections should do it.

**Comment by mikebattista** [comment]
The second issue is by design. I'll fix the first issue with the enum not being used consistently.
