### ISSUE TITLE
Rename KNONVOLATILE_CONTEXT_POINTERS_ARM64 to KNONVOLATILE_CONTEXT_POINTERS

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#480]
The `KNONVOLATILE_CONTEXT_POINTERS_ARM64` struct is an oddity that should be renamed `KNONVOLATILE_CONTEXT_POINTERS` to match the x64 and x86 structs.

**Comment by kennykerr** [comment]
This may have regressed as the `KNONVOLATILE_CONTEXT_POINTERS_ARM64` type still exists.
