### ISSUE TITLE
Does SOCKET really need to use UIntPtr as its field type?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#481]
Typedef structs that represent handles traditionally use `IntPtr` as their field. `HANDLE` is a good example of this:

```cs
[RAIIFree("CloseHandle")]
[NativeTypedef]
public struct HANDLE
{
	public IntPtr Value;
}
```

But `SOCKET` (and maybe some others) have recently introduced using `UIntPtr` as their field type:

```cs
[RAIIFree("closesocket")]
[NativeTypedef]
public struct SOCKET
{
	public UIntPtr Value;
}
```

Since in CsWin32 we generate special code for typedef structs that represent handles, we would have to generate more custom code to support `UIntPtr`. Is there some reason we can't use `IntPtr` for all typedef handle structs?

**Comment by sotteson1** [comment]
This is how it's defined in the headers:

````typedef UINT_PTR        SOCKET;````

I don't think I care either way, but I've been trying to keep them consistent with the headers when it's obvious like this one.

**Comment by AArnott** [comment]
ok. I'll just update my projection to handle UIntPtr then. Thanks.
