### ISSUE TITLE
PEXCEPTION_FILTER delegate has suspiciously inconsistent signature across CPU architectures

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#485]
The `PEXCEPTION_FILTER` delegate has an inconsistent type for its second parameter, and the in/out direction attributes vary for it as well. 

```diff
 [StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
 [UnmanagedFunctionPointer(CallingConvention.Winapi)]
-[SupportedArchitecture(Windows.Win32.Interop.Architecture.X64)]
+[SupportedArchitecture(Windows.Win32.Interop.Architecture.Arm64)]
-public unsafe delegate int PEXCEPTION_FILTER([In][Out] EXCEPTION_POINTERS* ExceptionPointers, [In][Out] void* EstablisherFrame);
+public unsafe delegate int PEXCEPTION_FILTER([In][Out] EXCEPTION_POINTERS* ExceptionPointers, [In] ulong EstablisherFrame);
```

Both of these definitions are for 64-bit architectures, so `void*` and `ulong` both have 64-bit lengths and we should probably use the same type for both to make coding against both more compatible.
And similarly, I doubt the architecture really changes whether the parameter is just `in` or also `out`.

**Comment by sotteson1** [comment]
This is how they're defined in the headers. The header goes out of its way to create different signatures for the different architectures. x64 uses PVOID and arm64 uses DWORD64. There are no SAL attributes to get the real in/out, so when we see a pointer we guess that it's in/out. I could make it just [In] on the PVOID version.

**Comment by AArnott** [comment]
For the sake of consistency is there a way to override what we get from the header in order to use the pointer signature for both cases?

**Comment by sotteson1** [comment]
I could do that, but I don't think that's the right thing to do. I don't know why these were defined differently for x64 and arm64, but they were. I don't think we should second guess the signatures when they are explicitly different.

**Comment by sotteson1** [comment]
Looking at the kernel code, it does look like they're both pointers. I will make them consistent, but it's weird how they're not in the headers.
