### ISSUE TITLE
`_In_ LPTSTR` gets mapped as `PWSTR`

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#487]
[`OpenPrinter`](https://docs.microsoft.com/en-us/windows/win32/printdocs/openprinter) has a first parameter defined as `_In_  LPTSTR pPrinterName`, but CsWin32 0.4.422-beta is generating a method with the first parameter `PWSTR` with no friendly `string` overload because `PWSTR` is a pointer to modifiable char data. I think this might mean the metadata is incorrect.

This amounts to a usability issue when what you have is a string. My code has to look like this:

```cs
SafeFileHandle hPrinter;
unsafe
{
    fixed (char* printerNamePointer = printerName)
        PInvoke.OpenPrinter(printerNamePointer, out hPrinter, pDefault: null).ThrowLastErrorIfFalse();
}
```

But if a friendly `string` overload was generated, my code would look like this:
```cs
PInvoke.OpenPrinter(printerName, out var hPrinter, pDefault: null).ThrowLastErrorIfFalse();
```

/cc @AArnott

**Comment by sotteson1** [comment]
This looks right in the metadata:

public unsafe static extern BOOL OpenPrinterW([Optional][In] PWSTR pPrinterName, [Out] HANDLE* phPrinter, [Optional][In] PRINTER_DEFAULTSW* pDefault);

**Comment by jnm2** [comment]
Could there still be a problem with CsWin32 then, or has the metadata changed?

**Comment by AArnott** [comment]
Yes, it may be that CsWin32 isn't recognizing the `[In]` flag on the metadata. I'll move to CsWin32 and reactivate.
