### ISSUE TITLE
Handle types should share a namespace with their release functions

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#490]
`CloseHandle` is in the `Windows.Win32.System.WindowsProgramming` namespace while its only parameter (`HANDLE`) is in the `Windows.Win32.System.SystemServices` namespace. This means two namespaces are required for one method call that really should be tightly bound to its only parameter type.

Would it make sense as a general policy to say that a handle type should always be in the same namespace as its release function?

**Comment by mikebattista** [comment]
> Would it make sense as a general policy to say that a handle type should always be in the same namespace as its release function?

Yes. This should be resolved once these two namespaces disappear after refactoring.

Foundational types and APIs like HANDLE and CloseHandle will probably end up in a Windows.Win32.Foundation namespace together.

**Comment by sotteson1** [comment]
Mike, I could change the emitter to ensure that if a handle type has a closing function that it always uses that namespace. I think Kenny was asking for that kind of guarantee too.

**Comment by mikebattista** [comment]
Sounds great. So if we move HANDLE to Windows.Win32.Foundation later, the Close function will follow it.

I generally like types following the APIs that use them like how enums.json works if you omit a namespace. The more we can guarantee related APIs stay together the better.
