### ISSUE TITLE
IDelayedPropertyStoreFactory and its base IPropertyStoreFactory interface in different namespaces?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#491]
Why is this interface and its base interface in different namespaces, when it seems the base interface's namespace probably applies to the derived one?

Windows.Win32.UI.Shell.IDelayedPropertyStoreFactory
Windows.Win32.System.PropertiesSystem.IPropertyStoreFactory

**Comment by sotteson1** [comment]
I think everything in propsys.h should move into Windows.Win32.System.PropertiesSystem. I'm going to reopen this and remove the remaining items for propsys.h from the .rsp.
