### ISSUE TITLE
CreateFileMappingA

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#496]
Most of the memory mapping functions like `MapViewOfFile` and `CreateFileMappingW` are in the `Windows.Win32.System.Memory` namespace but a handful like `CreateFileMappingA` and `PAGE_TYPE` are in the `Windows.Win32.System.SystemServices` namespace.

Can we define them together?

**Comment by kennykerr** [comment]
`FILE_MAP` and `MapViewOfFileExNuma` are also in `Windows.Win32.System.SystemServices` when they should probably be together with the rest.

**Comment by mikebattista** [comment]
These are all fixed in latest builds.
