### ISSUE TITLE
win32metadata fails the BuildMetadataBin step

### ISSUE THREAD

**Issue by tannergooding** [microsoft/win32metadata#498]
The CI validation for ClangSharp is failing because the `BuildMetadataBin` step currently fails for win32metadata.

This appears to be failing for the existing 11.0.0-beta3 tool in active use and the newer 12.0.0 branch of ClangSharp.

The simplest repro is the following, which shows that the fully qualified enum name conflicts with a method name.
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoKgOwEMBbGAZwAc6wYACAdWxoAmEAO7MAdHxoBmYmICSNDDCgRWVAN5Uu2roSlcYNAK4MuAQShgAFtiVgMR2Fp2bKO91wAaqZ9oC+VAHUlHpczDB0uDACusRcAMpGrKzQSgIW1rYw9o4wZhgYUNjARkpcIOYFRSVKGr66+onJqdEZNnYOsPmFxaUwABSSQqIS/DLyisqqYm1ZObBcdJbt2Z0wAJRc6lxBQVQA2k0pUGmzHbmD/MPikuMKSiqsM8tza2LeKOsAulShRjTMOgAM247BO2EiYUKRnsXDk8SsMFwuAAItg2HQMNY6m4dKF+BheFcRMx+oQUAAqClcZLYASbAC8AD4uBgrCphFxjMiANyBIA===

Prefixing this with `global::` (as in `[SupportedArchitecture(global::Windows.Win32.Interop.Architecture.X64)]`) allows it to correctly resolve and is likely the simplest "quick" fix. A proper fix likely requires some analysis that the first part of the qualified name of an attribute parameter doesn't conflict with a method name in the type.

**Comment by mikebattista** [comment]
@tannergooding this bug is a bit stale. Is it still a problem?

If so, could you clarify what needs to change? I didn't quite follow the context here.

**Comment by mikebattista** [comment]
Closing out this stale issue. Feel free to reopen if this is still a problem and clarify what changes are needed.
