### ISSUE TITLE
ZeroMemory definition is not found

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#501]
Neither RtlZeroMemory nor ZeroMemory work. Here's how .NET Framework 4.8 p/invokes ZeroMemory: https://github.com/microsoft/referencesource/blob/master/mscorlib/microsoft/win32/win32native.cs#L779-L783

Motivation: On .NET Framework, an easy way to zero memory given a pointer and a length. Maybe the best alternative is to use slow span: `new Span<byte>(packedResultBuffer, (int)packedResultBufferSize).Clear();`

Version used: 10.0.19041.5-preview.68

**Comment by sotteson1** [comment]
According to the headers, both ZeroMemory and RtlZeroMemory map to memset. So, these aren't real Win32 APIs that we can include in the metadata.
