### ISSUE TITLE
RmStartSession `WCHAR [] strSessionKey` parameter is projected as `ushort*`

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#505]
https://docs.microsoft.com/en-us/windows/win32/api/restartmanager/nf-restartmanager-rmstartsession#parameters

This results in the CsWin32 friendly overload (which I want to use because of the other parameters) being unusable because it defines this parameter as `out ushort` instead of a `char*`-equivalent type.

(Version used: 10.0.19041.5-preview.68)

**Comment by sotteson1** [comment]
It's fixed on the latest version.
