### ISSUE TITLE
RM_PROCESS_INFO strings are projected as fixed ushort arrays instead of char arrays

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#506]
Definition (https://docs.microsoft.com/en-us/windows/win32/api/restartmanager/ns-restartmanager-rm_process_info):
```
  WCHAR             strAppName[CCH_RM_MAX_APP_NAME + 1];
  WCHAR             strServiceShortName[CCH_RM_MAX_SVC_NAME + 1];
```

(Version used: 10.0.19041.5-preview.68)

**Comment by sotteson1** [comment]
This has been fixed for a while in the code, but now it's in the latest release too.
