### ISSUE TITLE
Missing optional flag on some LPUNKNOWN parameters

### ISSUE THREAD

**Issue by xtian** [microsoft/win32metadata#508]
The documentation for [DirectSoundCreate](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708921(v=vs.85)) and [IDirectSound::CreateSoundBuffer](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708943(v=vs.85)) says the following about their final `LPUNKNOWN  pUnkOuter` parameters:

> - pUnkOuter
> Controlling unknown of the aggregate. Its value must be NULL.

However these parameters aren't marked as optional.

**Comment by mikebattista** [comment]
Windows.Win32.Media.Audio.DirectSound.Apis.DirectSoundCreate : pUnkOuter : [In] => [Optional]
Windows.Win32.Media.Audio.DirectSound.IDirectSound.CreateSoundBuffer : pUnkOuter : [In] => [Optional]
