### ISSUE TITLE
XAML Islands APIs seem to be missing

### ISSUE THREAD

**Issue by reflectronic** [microsoft/win32metadata#510]
`IDesktopWindowXamlSourceNative` and `IDesktopWindowXamlSourceNative2` do not seem to be present anywhere.

**Comment by mikebattista** [comment]
I believe I fixed this recently with #499 . I do see these in the metadata now.

**Comment by reflectronic** [comment]
Argh, I should have looked closer. Sorry for the trouble, I was going off of the NuGet package.
