### ISSUE TITLE
[...].SystemServices.OVERLAPPED member appears to contains invalid field TypeReference

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#511]
Built win32metadata from latest master.

The `Windows.Win32.System.SystemServices.OVERLAPPED` class contains the following fields:
```
...
.field public native uint Internal
.field public native uint InternalHigh
.field public valuetype [Windows.Win32.winmd]Windows.Win32.System.SystemServices._Anonymous_e__Union Anonymous
.field public valuetype [Windows.Win32.winmd]Windows.Win32.Foundation.HANDLE hEvent
```

The `Anonymous` field contains a TypeReference pointing to a type that does not appear to exist (`Windows.Win32.System.SystemServices._Anonymous_e__Union`).

Previous versions of Windows.Win32.winmd contain the following TypeReference:
```
.field [0] public valuetype [Windows.Win32.winmd]Windows.Win32.System.SystemServices.OVERLAPPED/_Anonymous_e__Union/_Anonymous_e__Struct Anonymous
```

Am I looking at this right? cc: @kennykerr

**Comment by kennykerr** [comment]
I had a quick look at the latest build and indeed this is regression. The `OVERLAPPED` struct is broken and would prevent this from being used with Rust.

**Comment by kennykerr** [comment]
Looks like this is affecting other nested structs: https://github.com/microsoft/windows-rs/pull/826

**Comment by sotteson1** [comment]
I'll try to get this resolved today.

**Comment by riverar** [comment]
@sotteson1 Curious, is this empty if block a typo?

https://github.com/microsoft/win32metadata/commit/2bbdcac05cb8ab02d3c8e91e63ac6606aebb5d9a#diff-4609e74b3faba3e0c9d92648c9805c8b055cf14483c24951d8c145de1ccbe6eaR1836-R1839

**Comment by sotteson1** [comment]
> @sotteson1 Curious, is this empty if block a typo?
> 
> [2bbdcac#diff-4609e74b3faba3e0c9d92648c9805c8b055cf14483c24951d8c145de1ccbe6eaR1836-R1839](https://github.com/microsoft/win32metadata/commit/2bbdcac05cb8ab02d3c8e91e63ac6606aebb5d9a#diff-4609e74b3faba3e0c9d92648c9805c8b055cf14483c24951d8c145de1ccbe6eaR1836-R1839)

Yes, I made another commit right after to fix it.
