### ISSUE TITLE
socket address family, type, protocol use signed types; constants are unsigned

### ISSUE THREAD

**Issue by dominiccooney** [microsoft/win32metadata#512]
Context: I'm using windows-rs. I guess this is a metadata problem. The parameters to `socket` are projected as `i32, i32, i32`; makes sense given the signature of `socket(int, int, int)`. However the `AF_*`, `SOCK_*` etc. constants (for example `SOCK_STREAM`) are unsigned.

It would be better if these constants and parameters were the same type so it's not necessary to cast these.

I realize there's no perfect answer here. For example the `AF_` constants are also used is `SOCKADDR` where they are unsigned shorts. But at the moment I think the `AF_` constants don't match anywhere they are used.

**Comment by mikebattista** [comment]
@keith-horton what types do you recommend we use here for these constants?

**Comment by keith-horton** [comment]
@mikebattista  , the parameters to pass to socket() and WSASocket() are defined as below.

#define SOCK_STREAM     1               /* stream socket */
#define SOCK_DGRAM      2               /* datagram socket */

#define AF_INET         2               // internetwork: UDP, TCP, etc.
#define AF_INET6        23              // Internetwork Version 6

typedef enum {
.
.
    IPPROTO_TCP           = 6,
.
.
    IPPROTO_UDP           = 17,



Sadly, these are also used in other types. e.g. sockaddr's do express AF_INET and AF_INET6 as ADDRESS_FAMILY - which is an unsigned short. What options do we have here?

If we define these as unsigned short, they would fit in a signed int - and thus not cause compilation issues or require casts. would that work?

**Comment by mikebattista** [comment]
If ushort would fit everywhere these constants are used and wouldn't require casting, that sounds like the best option.

**Comment by keith-horton** [comment]
I did a quick-and-dirty test and passing it as ushort to WSASocket compiled just fine.
Looks like this is probably preferred.

**Comment by mikebattista** [comment]
Sounds good. Thanks.

**Comment by mikebattista** [comment]
Should we keep these as constants? Or turn these into ushort enums and convert all the method parameters and struct fields to use the enums instead?

**Comment by sotteson1** [comment]
If we turn them to ushort enums and force socket(int, int, int) to use them, it will change its signature from int to ushort. We don't want to change the size of the parameters from 32 to 16 bits.

**Comment by mikebattista** [comment]
Ok. I'll keep as constants and just change to ushort.

**Comment by mikebattista** [comment]
Couple other questions:

* Should the `PF_` constants also be ushort? Looks like they are defined as "same as AF_" in the headers.
* Should we update the `protocol` parameter of socket to be of the enum type `IPPROTO` from ws2def.h? If so, where else should this enum be used?

**Comment by mikebattista** [comment]
Let me know if the changes I checked in are sufficient or if we need to change more types per my previous questions.

**Comment by dominiccooney** [comment]
I tried to ./DoAll.ps1 to build this, but it seems I'm missing a dependency?

> error NU1100: Unable to resolve 'clangsharppinvokegenerator (>= 11.0.0-beta3)' for 'net5.0'.
> error NU1100: Unable to resolve 'clangsharppinvokegenerator (>= 11.0.0-beta3)' for 'net5.0/any'.

Is there a more detailed setup guide than CONTRIBUTING.md?

**Comment by mikebattista** [comment]
It should be pulling this package from NuGet.org.

Can you check your NuGet package sources? Do you have more sources than NuGet.org?

**Comment by dominiccooney** [comment]
Looked at this briefly. I think the problem is I'm using PowerShell 5 and Install-DotNetTool needs PowerShell 7 for Select-String -Raw. Will keep poking at it.

**Comment by mikebattista** [comment]
If you just want to browse the latest metadata without building the repo, you can just open https://github.com/microsoft/win32metadata/blob/master/scripts/BaselineWinmd/Windows.Win32.winmd in ILSpy.

Though I would like to understand any challenges you might be having setting up your dev environment in case we need to add something to CONTRIBUTING.md.

**Comment by dominiccooney** [comment]
This is a fresh-ish machine. Problems so far:
- PowerShell 5, not 7. CONTRIBUTING.md does link to PowerShell stable tag, but I missed the distinction.
- I did not have https://api.nuget.org/v3/index.json as a Nuget package source so could not find ClangSharpPInvokeGenerator.

**Comment by mikebattista** [comment]
> This is a fresh-ish machine. Problems so far:
> 
> * PowerShell 5, not 7. CONTRIBUTING.md does link to PowerShell stable tag, but I missed the distinction.
> * I did not have https://api.nuget.org/v3/index.json as a Nuget package source so could not find ClangSharpPInvokeGenerator.

I added this to CONTRIBUTING.md.

Are there any other changes required here for the socket APIs?

**Comment by mikebattista** [comment]
Closing out this old issue. Please file new issues for any additional changes.
