### ISSUE TITLE
Versioning change rationale? (10.2.84-preview)

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#513]
Seems like we were in sync with Windows 10 target platform versioning (e.g. 10.0.19041.xxx) but this latest release is now 10.2.84.

Is this right? What does it mean?

@sotteson1

**Comment by sotteson1** [comment]
Yes, this was intentional. We changed it because we wanted to move away from being attached to the version of the Windows SDK in our own version. We want to use the second number to show when a breaking change has been made. Only having the last number available meant we didn't have a way to signal breaking changes for language projections.

**Comment by riverar** [comment]
@sotteson1 Hm. That's confusing, as it doesn't follow semver rules. Seems like incrementing to 11.x and then following semver would be clearer. Thoughts?

**Comment by mikebattista** [comment]
The goal is to use semantic versioning per https://github.com/microsoft/win32metadata/issues/419.

We can't start with 0.* since we started at 10.*, so need to start with something beyond that version. If the latest version isn't semver compliant, then that's a bug.

**Comment by kennykerr** [comment]
The previous version was `10.0`. The current version introduces breaking changes so it must be `11.0`, not `10.2`, which implies that it is compatible with `10.0`.

**Comment by AArnott** [comment]
I thought the plan was that while we're still in "prerelease" we would signify breaking changes as a courtesy as a minor version bump.
Once we ship a *stable* version on nuget.org, semver rules require that we bump the major version on breaking changes. 

Semver has nothing to say about breaking changes within a prerelease, which IMO are fully expected to contain breaking changes because all prereleases are inherently unstable.

**Comment by riverar** [comment]
@AArnott That would perhaps hold true if we were at major version zero `0.x`. But we're not, which certainly makes this discussion a bit awkward.

`10.2.84-preview` implies it's a preview release of what will eventually become `10.2.84`, but because it introduces breaking changes over `10.0.xx`, that's not an appropriate version number to apply / violates semver.

I think it would be easier if you just followed semver normally rather than try to continue forward with 0.x semantics. That boat has sailed.

**Comment by mikebattista** [comment]
It's unfortunate we can't start at 0.x which is really where we are currently. In any case, we'll address this in a future update.

**Comment by riverar** [comment]
One plan of action could be:
1. Increment to `11.0.0-preview.1` sometime soon
2. Iterate on the metadata as needed, incrementing the pre-release tag (e.g. `11.0.0-preview.402`), break whatever you want
3. Release `11.0.0` when ready

<details> 
  <summary>Spoiler</summary>
Just in time for Windows 11, right? 😉
</details>

(Have not validated that against Nuget's implementation of semver.)

**Comment by mikebattista** [comment]
This next update contains several breaking changes. @sotteson1 I suggest we start incrementing the major version now and then continue doing so for breaking changes going forward to follow semver.

**Comment by sotteson1** [comment]
The problem is just about every change we make is a breaking change. Anytime we move something from one namespace to another, for example. If we do this, the major number is going to get large in a hurry.

**Comment by kennykerr** [comment]
Every time I publish an update to the [Windows crate](https://crates.io/crates/windows) I bump the version for this reason - its now at 21. That's normal at this stage and a large number is not a bad thing. It's just a number.

**Comment by sotteson1** [comment]
OK, sounds good. I'll update it regularly as needed.

**Comment by riverar** [comment]
With the major maximum capped to 65535, and considering we're at 10 already, we have ~65,525 more numbers to use. Assuming we increment once _daily_, we have a runway of ~179 years. I hope we won't need this metadata for that long. 😆

**Comment by mikebattista** [comment]
Right and I think our ideal cadence is publishing updates once every week or two anyway.

**Comment by sotteson1** [comment]
We've update to version 11.0.x and we'll update the major version for releases with breaking changes.
