### ISSUE TITLE
MEMORY_BASIC_INFORMATION missing field types

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/win32metadata#514]
MEMORY_BASIC_INFORMATION::AllocationProtect and MEMORY_BASIC_INFORMATION::Protect should be of type Windows::Win32::System::SystemServices::PAGE_TYPE

Currently these fields are set to a u32 where they should be of type Windows::Win32::System::SystemServices::PAGE_TYPE

source: https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-memory_basic_information

```
AllocationProtect

The memory protection option when the region was initially allocated. This member can be one of the memory protection constants or 0 if the caller does not have access.
```

```
Protect

The access protection of the pages in the region. This member is one of the values listed for the AllocationProtect member.
```

Furthermore the Type field should potentially be a separate u32 wrapper type which could be one of MEM_IMAGE, MEM_MAPPED or MEM_PRIVATE

**Comment by kennykerr** [comment]
Transferred to the win32metadata repo as this is where the type information originates.

**Comment by MarijnS95** [comment]
FYI it's pretty easy to define new enumerations (wrapping `u32`) constants and followed by overriding what methods/structs take this type, see https://github.com/microsoft/win32metadata/blob/master/CONTRIBUTING.md#enums.

**Comment by mikebattista** [comment]
Need to look into the Type field.
