### ISSUE TITLE
ProcessorArchitecture not being used

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/win32metadata#515]
bindings::Windows::System::ProcessorArchitecture is included in the windows crate, yet is is not being used for things such as the field of SYSTEM_INFO, where instead there is a u16 to represent the architecture.

ProcessorArchitecture is also a 32 bit struct, but it could be made into a 16 bit struct to fit into this field - since it seems like none of the functions are directly dependent on this struct at the moment.

**Comment by kennykerr** [comment]
I don't think the win32metadata project will want to introduce artificial dependencies between the Win32 and WinRT metadata families, but I'll let them decide.

**Comment by Ben-Lichtman** [comment]
If not that type then maybe a different one with a similar associated const structure then?

**Comment by mikebattista** [comment]
You're referring to the `wProcessorArchitecture` field within the nested struct inside `SYSTEM_INFO`, right?

If so, yes there's a Win32 enum we can apply here, but need to first fix a bug in our enum tooling related to fields within nested structs. Assigning to @sotteson1 for that.
