### ISSUE TITLE
BSTR

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#517]
BSTR and its supporting functions are now in different namespaces (as of the latest release). This shows up in [odd ways](https://github.com/microsoft/windows-rs/pull/834) - I think it would make more sense for them to be in the same namespace.

**Comment by sotteson1** [comment]
Agreed, it should be in Windows.Win32.System.OleAutomation.

**Comment by mikebattista** [comment]
Is BSTR only ever used in OleAutomation APIs? String types were good candidates for Foundation.

**Comment by kennykerr** [comment]
No, many APIs use BSTR.

**Comment by mikebattista** [comment]
Ok. Then I'd prefer to move the supporting functions over to Foundation as well. Do you have those handy?

**Comment by kennykerr** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/string-manipulation-functions
