### ISSUE TITLE
Arch-specific structs need to have unique names

### ISSUE THREAD

**Issue by sotteson1** [microsoft/win32metadata#521]
I just found a problem with the way we use the same names for arch-specific structs. If an arch-specific struct has a nested struct and has a field that refers to that type, it can't be represented in metadata correctly. The typeref for the field will point to (parent struct name+nested struct name) but that will resolve to the first top level struct with that name, not the particular arch-specific struct.

This means the structs need to have unique names for arch-specific structs. I could add a magic suffix so that it looks something like:

KNONVOLATILE_CONTEXT_POINTERS
KNONVOLATILE_CONTEXT_POINTERS____1
KNONVOLATILE_CONTEXT_POINTERS____2

The projections would have to look for the magic suffix and remove them before projecting them. I'm open to other solutions, but without unique struct names, fields that use nested structs are broken. @AArnott and @kennykerr, what do you think? This is a bad breaking change but I don't know how else to fix it.

**Comment by kennykerr** [comment]
Can you provide an example? I just want to make sure I understand the problem. KNONVOLATILE_CONTEXT_POINTERS doesn't appear to refer to itself.

**Comment by sotteson1** [comment]
In our latest builds we're seeing the problem with KNONVOLATILE_CONTEXT_POINTERS:

````C#
[SupportedArchitecture(Architecture.X86)]
public struct KNONVOLATILE_CONTEXT_POINTERS
{
    public uint Dummy;
}

[SupportedArchitecture(Windows.Win32.Interop.Architecture.X64)]
public struct KNONVOLATILE_CONTEXT_POINTERS
{
    [StructLayout(LayoutKind.Explicit)]
    public struct _Anonymous1_e__Union
    {
...
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct _Anonymous2_e__Union
    {
...
    }

    public _Anonymous1_e__Union Anonymous1;

    public _Anonymous2_e__Union Anonymous2;
}

````

If you look at this in ILSpy with IL turned on, the two fields look like:

````
    // Fields
    .field public valuetype [Windows.Win32.winmd]Windows.Win32.System.SystemServices.KNONVOLATILE_CONTEXT_POINTERS/_Anonymous1_e__Union Anonymous1
    .field public valuetype [Windows.Win32.winmd]Windows.Win32.System.SystemServices.KNONVOLATILE_CONTEXT_POINTERS/_Anonymous2_e__Union Anonymous2
````
The typeref to KNONVOLATILE_CONTEXT_POINTERS can't specify which one. If it were uniquely named, then it could.

**Comment by mikebattista** [comment]
A couple other examples are `Windows.Win32.System.Diagnostics.Debug.CONTEXT` and `Windows.Win32.System.Kernel.SLIST_HEADER`.

**Comment by mikebattista** [comment]
@marler8997 and @timsneath for their thoughts.

**Comment by kennykerr** [comment]
Nested types are always relative to their enclosing type so this is fine. I think that just looks ambiguous in ILSpy but is not ambiguous if you read the metadata directly. The nested types are stored as a `TypeDef` mapping table in ECMA335 called `NestedClass`. This defines the relationship between nested and enclosing types. Since these are `TypeDef`s and not `TypeRef`s, they point to specific definitions and are thus unambiguous.

**Comment by kennykerr** [comment]
Sure, but the parser just needs to lookup up the type signature in the arch-specific definition for the target build. That's what I've been doing all along. The `TypeRef` won't have a namespace but will have a scope (field column of the `TypeRef` table). This `TypeRef` gives the qualified name of the enclosing type. You find the arch-specific `TypeDef` and then lookup the scope-relative `TypeDef` for the field.

**Comment by sotteson1** [comment]
If the projections are OK with that we can keep it. It confuses ILSpy and also the library I'm using for diffing. I'll have to figure out a way to disambiguate this kind of thing in the tests.

**Comment by marler8997** [comment]
The Zig projection is also fine here.  If the same symbol has multiple definitions for different arches, then this problem already has to be solved to avoid symbol conflicts.  It's not exactly the same but the Zig projection does what's equivalent to `ifdefs` around arch-specific symbols.

**Comment by AArnott** [comment]
CsWin32 has been fine resolving the ambiguity like @kennykerr described as well.

**Comment by mikebattista** [comment]
Thanks for the feedback. Sounds like we can keep the current design and just update the tooling that is currently having issues.
