### ISSUE TITLE
INTERNET_DEFAULT_PORT not compatible with some languages

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#522]
The following definitions...

```C++
#define INTERNET_DEFAULT_PORT           0           // use the protocol-specific default
#define INTERNET_DEFAULT_HTTP_PORT      80          //    "     "  HTTP   "
#define INTERNET_DEFAULT_HTTPS_PORT     443         //    "     "  HTTPS  "
```

Are grouped together in metadata as follows...

```C#
public enum INTERNET_DEFAULT_PORT : uint
{
	INTERNET_DEFAULT_HTTP_PORT = 80u,
	INTERNET_DEFAULT_HTTPS_PORT = 443u,
	INTERNET_DEFAULT_PORT = 0u
}
```

This is problematic for both Rust and C as the same symbol `INTERNET_DEFAULT_PORT` is used to refer to both the type name and one of its fields.

**Comment by kennykerr** [comment]
`PDH_VERSION` is another example.

**Comment by kennykerr** [comment]
Is this perhaps meant to signal the default value for such types? Just guessing here. 😊

**Comment by mikebattista** [comment]
* INTERNET_DEFAULT_PORT should just be INTERNET_PORT per the WinHttp headers
* PDH_VERSION could probably be changed to PDH_DLL_VERSION to keep the enum members consistent with the constants
* POWER_PLATFORM_ROLE_VERSION I'd prefer to keep the name of the enum and change the conflicting member name to _CURRENT_VERSION. This would deviate slightly from the original constant name, but I think this would be better.

**Comment by kennykerr** [comment]
Thanks, I'd appreciate another release once this is fixed as the Windows crate is currently [blocked on this bug](https://github.com/microsoft/windows-rs/pull/846).

**Comment by kennykerr** [comment]
I did a quick scan and these three are the only cases in the latest release.

**Comment by kennykerr** [comment]
I now have a workaround for this, so no rush. By the way, you can now browse the latest win32 metadata here:

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/index.html
