### ISSUE TITLE
Apply [Optional] to optional struct/union pointer fields

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#523]
I thought I would use the `Optional` attribute to determine whether or not a pointer could be `NULL` (see https://docs.microsoft.com/en-us/cpp/code-quality/annotating-function-parameters-and-return-values?view=msvc-160).  However I've come to realize that the metadata only includes this attribute on function parameters, but does not use the optional attribute on struct/union fields, even if it has a pointer field that can be null.

One solution I could do here is ignore the optional attribute and just make all pointers types nullable.  That would make the bindings work, but this would disable the type system's ability to catch `NULL` errors at compile-time.  But in order to make that work, I would need the same "optional" metadata to be specified not only for function arguments, but for struct fields as well.

Thoughts, suggestions, ideas?

**Comment by AArnott** [comment]
Which language are you generating for? (just curious)
Does that language let you add nullable annotations to some generated code and not others?
Would you generate a non-default constructor on these structs that would take the values required to initialize the required fields?

**Comment by marler8997** [comment]
> Which language are you generating for? (just curious)
> Does that language let you add nullable annotations to some generated code and not others?

I'm generating bindings for the Zig programming language which can be found here: https://github.com/marlersoft/zigwin32

By default Zig does not allow pointers to be null.  To accept null, they need to be marked as "optional" with `?`:

```zig
const a:  *u8 = null; // compile error, a is not optional
const b: ?*u8 = null; // OK, b is optional
```

Note that the bindings would "work" if we made all pointers optional, but the bindings would be better if they properly represented which parameters and fields can be null so that null errors would be caught by the type system at compile time.

If we decide that win32metadata is not going to provide information about which pointers can or cannot be null, then I'll supplement the metadata with this information in my projection.  This would be required to meet the goal of making the autogenerated bindings as good as hand-generated ones.

> Would you generate a non-default constructor on these structs that would take the values required to initialize the required fields?

I was only thinking about "nullability" when thinking about optional (not constructors), but Zig does also have "default field initializers" which could utilize this as well, i.e.

```zig
const Foo = struct {
    bar: ?*Bar = null,
};

const foo = Foo { }; // construct a new Foo struct, bar is set to null by default so we don't need to initialize it here
assert(foo.bar == null);
```

**Comment by AArnott** [comment]
C# 8 allows for nullable ref annotations as well. They don't apply to pointer types, but in some cases we represent pointers as non-pointer types in our C# projection, so I would be interested in some kind of annotations in the metadata as well.

**Comment by mikebattista** [comment]
> I've come to realize that the metadata only includes this attribute on function parameters, but does not use the optional attribute on struct/union fields, even if it has a pointer field that can be null.

Is this the main issue here? That [Optional] is not applied to optional struct/union fields? Do these optional struct/union fields have SAL annotations on them and we're just not emitting them? Are they missing SAL annotations? Could you provide some examples of fields you're finding that should be marked with [Optional]?

**Comment by marler8997** [comment]
The struct I ran into was `WNDCLASSW` (or `WNDCLASSA`).  It looks like it does not contain SAL annotations.  The `lpszMenuName` can be `NULL` and the handle values can also be `NULL`.

There are no "optional" SAL annotations on any struct/union field as far as I could see.  Extending SAL annotations from function parameters to struct/union fields seems a good way to extend an existing feature to accommodate knowing the nullability of all pointers in the metadata.  I'm certainly not opposed to alternative solutions other than leveraging SAL.  My guess is that other projections can also make use of knowing when pointers can and cannot be NULL so it seems like good information to include in the metadata in some form.

**Comment by marler8997** [comment]
Ping @kennykerr, how does the Rust projection handle nullability here?  Are you using the `Optional` attribute to determine nullability or are you just allowing all pointers to be `NULL`?

**Comment by kennykerr** [comment]
Everything supports a null/zero/optional value. I had proposed a non-nullable concept a while back but it was deemed impractical to go back and annotate the many existing APIs that are known to be non-null. The Windows ABI also depends on being able to pass blittable structs/arrays and marshal them in ways that in practice demand nullable fields in most cases. I have since made it much easier to deal with nullable values in Rust by leveraging its error handling model to deal with null values automatically. This is mostly transparent for parameters. Struct fields show up as the equivalent of `Option<T>`.

**Comment by sotteson1** [comment]
Windows headers only has SAL annotations on parameters. As here are thousands of structs in the SDK, I don't want our project to have to add that information without getting it from the API owners.

**Comment by marler8997** [comment]
Just FYI, this means that I'll be maintaining this information outside the metadata as a supplementary source of data because this information is necessary in order for the autogenerated bindings to be as accurate as hand-generated ones.  In my opinion, the purpose of the metadata is to make this information available to all projections so I don't agree with the decision to exclude it.
