### ISSUE TITLE
CreateSymbolicLink returns `byte` instead of `bool` for `BOOLEAN`

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#525]
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw#return-value

### Context

- CsWin32 version: [e.g. `0.1.422-beta`]
- Target Framework: [e.g. `net5.0-windows`]
- `LangVersion`: 9

**Comment by weltkante** [comment]
> I don't remember if the COM marshaller differs

yes, in interface signatures it treats `bool` as 2-byte `VARIANT_BOOL` ... booleans in C# interop are hell ;-)

**Comment by sotteson1** [comment]
I'm going to turn these into a NativeTypedef class named BOOLEAN like we did with BOOL. That way the data isn't lost that it's not just a byte but is meant to be a Win32 BOOLEAN (the byte version of BOOL which is an int).
