### ISSUE TITLE
RichTextBox and TextBox constants got mixed up

### ISSUE THREAD

**Issue by weltkante** [microsoft/win32metadata#527]
There are a few RichTextBox `EM_*` constants that also exist under the same name as TextBox constants, they have different values in `richedit.h` and `winuser.h`. For whatever reason the winmd file contains the constants from `richedit.h` even though normal inclusion order means `winuser.h` gets included before `richedit.h`, so normally C/C++ programs never see the richedit definitions unless they go out of their way to make them visible.

This affects `EM_GETLIMITTEXT`, `EM_POSFROMCHAR` and `EM_CHARFROMPOS` where `richedit.h` defines them as `WM_USER` based messages while `winuser.h` has them defined in the system message range.

I think
* if you have to chose a single definition you should prefer `winuser.h` over `richedit.h` because the `WM_USER` based messages are specific to RichTextBox and won't be understood by normal TextBox controls
* ideally you'd provide both constants in separate enums (#121 / [comment](https://github.com/microsoft/win32metadata/issues/121#issuecomment-860145258)) so people who really need the RichEdit version don't have to define them manually

You may also want to revisit your header inclusion order which caused this bug in the first place.

**Comment by mikebattista** [comment]
In #121, we decided against enums for message and style constants. Do we still want enums here?

Whether these are enums or constants, we can't have duplicate definitions of constants or enum members with the same time, otherwise they break some projections like Rust. We could go with your first option of only exposing the winuser values, but I'd prefer to support both if we can.

@kennykerr any suggestions here?

**Comment by kennykerr** [comment]
This bug is not specific to Rust. 

The problem is that the constants in metadata have the wrong values. In C++, the following holds true:

```C++
#include <Windows.h>
static_assert(EM_GETLIMITTEXT == 213);
```

But the metadata defines `EM_GETLIMITTEXT` as follows:

```C#
public const uint EM_GETLIMITTEXT = 1061u;
```

**Comment by mikebattista** [comment]
EM_GETLIMITTEXT and the others listed are defined with different values in different headers.

**Comment by kennykerr** [comment]
Even if I change my C++ example as follows:

```C++
#include <richedit.h>
static_assert(EM_GETLIMITTEXT == 213);
```

I still get the same value. You can use `/showIncludes` to observe that while `richedit.h` defines `EM_GETLIMITTEXT` as follows:

```C++
#ifndef EM_GETLIMITTEXT
#define EM_GETLIMITTEXT 		(WM_USER + 37)
#endif
```

It only does so after including `winuser.h` that defines it as follows:

```C++
#define EM_GETLIMITTEXT         0x00D5
```

So while there may be a roundabout way to get the other values, it doesn't seem to be the norm.

**Comment by mikebattista** [comment]
Very strange. So sounds like we just need to expose the values from winuser.h.

@weltkante do you agree?

**Comment by weltkante** [comment]
yes, including the ones from winuser.h are the ones you want in 99% of the cases. normal C/C++ programs need to go out of their way to access the richedit constants (by undef'ing the ones from winuser before including richedit)

The ones from richedit.h are for very special usecases, for example the WinForms framework needs them to talk to the richedit specifically. If you aren't going to have separate enums for TextBox and RichTextBox then just use the ones from winuser.h like normal inclusion of headers will select. Anyone who needs the special ones could define them themselves.
