### ISSUE TITLE
TRUE and FALSE constants removed

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#530]
It appears that the `TRUE` and `FALSE` constants have been removed?  Was this intentional?

**Comment by mikebattista** [comment]
There was feedback that the metadata shouldn't define constants like this that languages define themselves. I believe these were removed as part of addressing that.

**Comment by marler8997** [comment]
Ok thanks for the info, closing as removal was intended

**Comment by marler8997** [comment]
So for clarification, what criteria are we using to determine what constants go in the metadata and what ones don't?

**Comment by mikebattista** [comment]
Constants that projections will ignore in favor of native language constructs are good candidates for removal. There were a few obvious examples we removed.
