### ISSUE TITLE
D3D12_DEFAULT_DEPTH_BIAS has type uint (it should be int)

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#532]
Although D3D12_DEFAULT_DEPTH_BIAS appears as a macro defined as `(0)` in the header, and is declared as a `uint` in the IDL, it is intended to be passed in to `D3D12_RASTERIZER_DESC::DepthBias`, and so this type mismatch upsets strongly typed languages.

**Comment by mikebattista** [comment]
FYI I recently added https://github.com/microsoft/win32metadata/blob/master/CONTRIBUTING.md#Constants which details how to make changes like this to constants.
