### ISSUE TITLE
Does win32metadata mark methods as safe/unsafe?

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#533]
When I view the metadata in ilspy I see that some methods are marked safe and others unsafe.  For example:

```c#
public interface ID3D12CommandQueue : ID3D12Pageable
{
        // [...]
	unsafe void BeginEvent([In] uint Metadata, [Optional][In][Const][MemorySize(BytesParamIndex = 2)] void* pData, [In] uint Size);

	void EndEvent();

        // [...]
}
```

What does "unsafe" mean in this context?  Does this describe memory safety in a way that, say, the rust projection could take advantage of?

**Comment by KalleOlaviNiemitalo** [comment]
I guess `unsafe` is just required by C# for the pointer type in the `void* pData` parameter and not separately encoded in metadata.

**Comment by kennykerr** [comment]
Yes, I couldn't find any metadata that specifically marks the method "unsafe".

**Comment by kennykerr** [comment]
What was the conclusion to @damyanp's question? 

> What does "unsafe" mean in this context? Does this describe memory safety in a way that, say, the rust projection could take advantage of?

**Comment by mikebattista** [comment]
You all answered that, no?

**Comment by kennykerr** [comment]
I was hoping for something a little more definitive than "I guess..." 😉

**Comment by mikebattista** [comment]
There's nothing in the metadata that is tagging things as unsafe as you pointed out. ILSpy when rendering with C# will show unsafe per its [definition](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/unsafe). If you switch rendering to IL, you won't see unsafe on these definitions.

**Comment by kennykerr** [comment]
Thanks!
