### ISSUE TITLE
DVC Client api definitions missing

### ISSUE THREAD

**Issue by leonardder** [microsoft/win32metadata#535]
I'm not sure whether this is the proper place to report this, but it seems not yet possible to use the [Dynamic Virtual Channel client APIs](https://docs.microsoft.com/en-us/windows/win32/termserv/dvc-client-apis) yet. I tried adding `tsvirtualchannels.h.*` to my native methods file in a C# project without luck.

**Comment by mikebattista** [comment]
@AArnott 

I see those APIs in Windows.Win32.System.RemoteDesktop. For now you need to list the COM interfaces in NativeMethods.txt. https://github.com/microsoft/CsWin32/pull/300 will let you list the namespace to get everything.

Let me know if everything you need is there.

**Comment by leonardder** [comment]
Thanks a lot, listing these interfaces explicitly works for me.

Regarding the namespaces, are they documented somewhere, i.e. how to do the translation from a particular header or idl file (tsvirtualchannels) to a namespace name?

**Comment by mikebattista** [comment]
Awesome. For now, you can follow the links in the README to download the latest winmd file and load it in ILSpy where you can search for an API and see where it's defined.

Eventually we'll want namespace added to our API documentation along with header file like https://docs.microsoft.com/en-us/windows/win32/api/tsvirtualchannels/nn-tsvirtualchannels-iwtsplugin#requirements, but that doesn't exist yet.

Also the C# tooling ideally would help here, providing "add using" refactorings when you try to call an API you asked for in NativeMethods.txt. The request to fix that is tracked by https://developercommunity.visualstudio.com/t/C-Add-using-refactoring-not-offered-f/1428570. Feel free to upvote that to help prioritize that work.
