### ISSUE TITLE
IsValidSecurityDescriptor listed in WithSetLastError.rsp

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/win32metadata#537]
<https://github.com/microsoft/win32metadata/commit/0992cabd9f7d44c5375d133a44ddf18c17a4d694> added a script that scrapes the docs for GetLastError references and generates generation/WithSetLastError.rsp, which I guess is then translated to metadata. One of the functions listed there is [IsValidSecurityDescriptor](https://docs.microsoft.com/windows/win32/api/securitybaseapi/nf-securitybaseapi-isvalidsecuritydescriptor). However, its documentation actually says:

> There is no extended error information for this function; do not call GetLastError.

i.e. it mentions GetLastError but only to advise against calling that. I guess there may be more functions like that.

**Comment by mikebattista** [comment]
Thanks for pointing this out.
