### ISSUE TITLE
Add IWindowNative (microsoft.ui.xaml.window.h)

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#538]
[IWindowNative](https://docs.microsoft.com/en-us/windows/apps/winui/reference/iwindownative) is in a weird spot. It's in the realm of MUX and owned by their team but it's not an API they'll want to add to their metadata (Microsoft.UI.winmd) for, well, _HWND reasons_.

But [all MUX developers will need this](https://github.com/microsoft/microsoft-ui-xaml/issues/2564), if they want to perform basic window operations, such as resizing the window (overriding the non-ideal 50%-width-of-display behavior), setting window styles, or even a window title.

There is no indication WinUI 3 will support these operations in time for Project Reunion 1.0 GA.

**Comment by mikebattista** [comment]
Thanks. Sounds like another case of https://github.com/microsoft/win32metadata/issues/66 which is something we are working on. We'll look into it.

**Comment by kennykerr** [comment]
fyi @jonwis reunion/winui should ship a winmd with this definition.

**Comment by angelazhangmsft** [comment]
@riverar - FYI, for C#/.NET 5 we have [added COM interop APIs to the Windows SDK projections](https://github.com/microsoft/CsWinRT/pull/830), and this will ship in the July .NET 5 SDK update: 

This will make it easier to call interop functions in C#, for example:

```csharp
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
var folderPicker = new FolderPicker();
WinRT.Interop.InitializeWithWindow.Initialize(folderPicker, hwnd);
```

We are working on the documentation for these new APIs.

**Comment by kennykerr** [comment]
That helps C# but not any other language (like C++ or Rust) as that knowledge is baked/hardcoded into the C# projection. Ideally, we can have metadata that defines this for every language.

**Comment by riverar** [comment]
Any updates on this? Emission of IWindowNative in C#/WinRT is not helpful. Why is this such a weird wart? Politics?

**Comment by kennykerr** [comment]
It does seem awkward that the Win32 metadata includes `IInitializeWithWindow` but not `IWindowNative`. They're two sides of the same coin.

**Comment by sotteson1** [comment]
> Any updates on this? Emission of [IWindowNative helpers in C#/WinRT](https://github.com/microsoft/CsWinRT/blob/605f1122624c8b5d42530cc6af5a320210b5babd/src/cswinrt/strings/ComInteropHelpers.cs#L50-L56) is not helpful. Why is this such a weird wart? Politics?

Sorry we haven't made progress on this. It's not a problem of politics--we definitely want to have this available to projections. The problem is that this API isn't part of the Windows SDK which is what win32metadata scrapes into the main .winmd. We are working to have the Windows App SDK scrape its headers and provide additional .winmd files in its packages, but we aren't there yet. We're working on it and hope to have it available soon, but it won't show up in Windows.Win32.winmd, it will be in a .winmd that the Windows App SDK ships.

**Comment by riverar** [comment]
Just closing old issues. Since creating this issue, I was able to successfully generate any needed metadata for the entire Windows App SDK, so this isn't really needed anymore.
