### ISSUE TITLE
How to browse/search the metadata?

### ISSUE THREAD

**Issue by astraw** [microsoft/win32metadata#539]
I'm new to programming for Windows APIs. The instructions in the README about how to find a particular API definition are a bit sparse for me: "If you'd like to browse the metadata to see what we're emitting, download the NuGet package and load the included winmd file in ILSpy."

I have tried and failed to do this. I installed ILSpy using the Windows Store, which gives me ILSpy verion 7.1.0.6543. Then I downloaded the file `microsoft.windows.sdk.win32metadata.10.2.84-preview.nupkg` from the page linked in the README https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/ by clicking "Download package 4MB" in the right sidebar column. I open this .nuget file in ILSpy by the File->Open... menu. 

When I have opened the nuget file, I see in the left column the entry `microsoft.windows.sdk.win32metadata.10.2.84-preview` appear. But how can I find the API definitions I am looking for in there? For example, I have been successfully wrapping part of MediaFoundation with windows-rs and in rust can successfully build the bindings for `Windows::Win32::Media::MediaFoundation::MFCreateAttributes` but I cannot find this in ILSpy. There seems to be either be no search function in ILSpy where I can search for the `MFCreateAttributes` function or the nupkg file does not actually have this function. There is a search bar in ILSpy, but first it seems I need to know what category I am search for ("Types and Members" or "Type" or "Member" or "Method" or "Field" etc) and then if I paste in MFCreateAttributes nothing comes up. However, judging by my succesfully compiling windows-rs based program, I know this function is is present in the metadata.

Can the instructions be updated to give a bit more detail about how I would find API members using the linked resources?

I already filed a bug (https://github.com/microsoft/windows-rs/issues/882) in `windows-rs` about a specific instance in which having better visibility into the metadata would have helped, and now I'm afraid I'm hitting the same thing again - I am looking for the Guid `MFVideoFormat_RGB32` but cannot find it.

**Comment by mikebattista** [comment]
I updated the README to simplify things. Follow the links to download the winmd file and install the latest version of ILSpy. Once you load the winmd file in ILSpy, you'll find the search interface.

If you can't find a specific API, file a separate issue for that and we'll look into it.

**Comment by astraw** [comment]
Thank you. Using the updated instructions, I can indeed find `MFCreateAttributes` in the metadata using the search function of ILSpy.

**Comment by tim-weis** [comment]
Loading `Windows.Win32.winmd` into ILSpy is sufficient for discovering available API calls. It's not enough to get custom attributes resolved, though:

![notifyicondata](https://user-images.githubusercontent.com/23303506/122737534-6ca07000-d281-11eb-9a7d-55c56f7d4609.png)

For that you will need to load `Windows.Win32.Interop.dll` as well (or copy it next to the .winmd file for automatic discovery):

![notifyicondata_full](https://user-images.githubusercontent.com/23303506/122737690-98bbf100-d281-11eb-9b5e-cb11bb175edf.png)

Would this information be of general utility enough to have it in the README as well, @mikebattista?

**Comment by marler8997** [comment]
I've found my JSON projection is good for searching and analyzing the data.  Since it's in JSON, there are many tools you can use to parse/filter it and then process it with your favorite tools like awk/sed/grep/etc.

https://github.com/marlersoft/win32json

**Comment by mikebattista** [comment]
@tim-weis yes I added the interop dll to the instructions.
