### ISSUE TITLE
SAFEARRAY should have a type parameter

### ISSUE THREAD

**Issue by mwcampbell** [microsoft/win32metadata#540]
In at least some IDL definitions, `SAFEARRAY` has a type parameter. See for example the definition of `IRawElementProviderFragment::GetRuntimeId` in UIAutomationCore.idl. I notice though that MIDL doesn't include this information in the generated header file, so I understand that this might be difficult to implement.

**Comment by mikebattista** [comment]
`SAFEARRAY` in the metadata appears to mirror the documentation at https://learn.microsoft.com/en-us/windows/win32/api/oaidl/ns-oaidl-safearray.
