### ISSUE TITLE
Media Foundation video subtype GUIDs missing from metadata

### ISSUE THREAD

**Issue by astraw** [microsoft/win32metadata#541]
Missing from the metadata currently are the Media Foundation video subtype GUIDs:

- `MFVideoFormat_RGB8`
- `MFVideoFormat_RGB555`
- `MFVideoFormat_RGB32`
- `MFVideoFormat_L8`
- and more

**Comment by mikebattista** [comment]
Yes we need to add some code to recognize the pattern here. Assigning to Steve to help with that.

One missing piece is the ability to resolve constant values in the ConstantsScraper like:

```
DEFINE_MEDIATYPE_GUID( MFVideoFormat_RGB32,     D3DFMT_X8R8G8B8 );
DEFINE_MEDIATYPE_GUID( MFAudioFormat_DRM,               WAVE_FORMAT_DRM );
```
