### ISSUE TITLE
_Field_size_full_ struct member annotation is ignored

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#547]
For example:

```c++
typedef struct D3D12_ROOT_DESCRIPTOR_TABLE
    {
    UINT NumDescriptorRanges;
    _Field_size_full_(NumDescriptorRanges)  const D3D12_DESCRIPTOR_RANGE *pDescriptorRanges;
    } 	D3D12_ROOT_DESCRIPTOR_TABLE;
```

Becomes:
```c#
public struct D3D12_ROOT_DESCRIPTOR_TABLE1
{
	public uint NumDescriptorRanges;

	[Const]
	public unsafe D3D12_DESCRIPTOR_RANGE1* pDescriptorRanges;
}
```

It would be good to have some metadata here associating these two fields to allow projections to do the right thing.  See for example https://github.com/microsoft/windows-rs/issues/907.

**Comment by riverar** [comment]
What's the proposed change here? Are you looking to see something like this?

```csharp
public struct D3D12_ROOT_DESCRIPTOR_TABLE1
{
	public uint NumDescriptorRanges;

	[Const]
	[NativeArrayInfo(CountParamName = "NumDescriptorRanges")]
	public unsafe D3D12_DESCRIPTOR_RANGE1* pDescriptorRanges;
}
```

**Comment by kennykerr** [comment]
Any progress on this issue? Would love to bind this up in Rust so we can treat this as an array.

**Comment by kennykerr** [comment]
I noticed I have both https://github.com/microsoft/windows-rs/issues/907 and https://github.com/microsoft/windows-rs/issues/443 blocked on this issue.

**Comment by sotteson1** [comment]
> Any progress on this issue? Would love to bind this up in Rust so we can treat this as an array.

Would what @riverar suggested work? I haven't had a lot of time for this project lately, unfortunately. I'm not sure when I'll be able to get to this.

**Comment by kennykerr** [comment]
Yep, an attribute like that would be enough make it work - thanks!

**Comment by mikebattista** [comment]
I don't see any `CppAttributeList` for this annotation.

```c#
public unsafe partial struct D3D12_ROOT_DESCRIPTOR_TABLE
{
    public uint NumDescriptorRanges;

    [NativeTypeName("const D3D12_DESCRIPTOR_RANGE *")]
    public D3D12_DESCRIPTOR_RANGE* pDescriptorRanges;
}
```

@tannergooding SAL annotations are expected to surface in the `CppAttributeList` attribute right? That's how we process other SAL annotations but I don't see the attribute in this case.

**Comment by mikebattista** [comment]
There was a manageable enough set of these in d3d12.h that I defined them manually for now. We have `CountFieldName` for this scenario.

```
public struct D3D12_ROOT_DESCRIPTOR_TABLE
{
	public uint NumDescriptorRanges;

	[Const]
	[NativeArrayInfo(CountFieldName = "NumDescriptorRanges")]
	public unsafe D3D12_DESCRIPTOR_RANGE* pDescriptorRanges;
}
```

@tannergooding I filed a bug in your repo for generating CppAttributeList on structs so we can detect this automatically for the rest of the API surface.
