### ISSUE TITLE
Virtual Key Codes not Generated

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/win32metadata#551]
**Is your feature request related to a problem? Please describe.**
When adding [`SendInput`](https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-sendinput) as a native method, the list of [virtual keycodes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) accepted by the `INPUT` type is not auto-generated, so you have to find this document to do the mapping.

(It's also a bit weird to have to dig-in to the `Annoymous` sub-structure, assuming that's to aid in handling the backing union type not supported in C#?)

**Describe the solution you'd like**
When adding an `INPUT` structure (or similar) generate the virtual key-code enum values as well.

**Describe alternatives you've considered**
Having to dig through the docs to find the key-code table... 🙁

**Comment by mikebattista** [comment]
@sotteson1 @jnm2 @weltkante

We've got VK_ constants defined in winuser.h, kbd.h, and xinput.h.

Is the request to merge all of these into an enum and use that for the type of the wVk field in the [KEYBDINPUT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput) struct?

Will this have ramifications for APIs like GetKeyboardState as mentioned in #489? The documentation for that suggests it only supports the 256 values from winuser.h.

Need to determine if we should keep these as just constants, create one unified enum, or potentially multiple enums for different scenarios.

If we keep them as constants, we should move the 256 winuser.h constants over to Windows.Win32.UI.KeyboardAndMouseInput where SendInput is which would help with discoverability.

**Comment by AArnott** [comment]
For a closed set of constants, I'd tend to favor an enum.

**Comment by jnm2** [comment]
I'm not sure it's a good idea for these constants to become an enum because it's missing a lot of members that are currently passed via `KEYBDINPUT { wVk = '3' }`. Making the `wVk` field use an enum type would mean requiring explicit casts or generating `VK_3` etc which aren't in the metadata or documented. (Originally mentioned at https://github.com/microsoft/CsWin32/issues/267)

**Comment by mikebattista** [comment]
Why do you need to synthesize 36 constants? Are they not in the headers? Just missing from the metadata?

**Comment by jnm2** [comment]
I don't think they are in the headers. What I do know is both that they are not documented as existing and they are not in the metadata.

**Comment by jnm2** [comment]
Looked at WinUser.h:

```h

/*
 * VK_0 - VK_9 are the same as ASCII '0' - '9' (0x30 - 0x39)
 * 0x3A - 0x40 : unassigned
 * VK_A - VK_Z are the same as ASCII 'A' - 'Z' (0x41 - 0x5A)
 */
 ```

**Comment by mikebattista** [comment]
Got it. Thanks. We can add those to the metadata one way or another.

[XINPUT_KEYSTROKE.VirtualKey](https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_keystroke) definitely needs its own enum just for the xinput.h constants.

For KEYBDINPUT.wVk, should it contain all VK_ values from all headers (including xinput.h) as well as the synthesized values you listed?

**Comment by jnm2** [comment]
That's something I don't know how to verify, sorry. My knowledge on this is a subset of the docs.

**Comment by michael-hawker** [comment]
> Is the request to merge all of these into an enum and use that for the type of the wVk field in the [KEYBDINPUT](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput) struct?

Yeah, had to dig through the pages of documentation to get to the virtual key-code list, so if `wVk` was just an enum or something, then intellisense would make it pretty easy to grab most common keystrokes to populate the input array with.
 
> Will this have ramifications for APIs like GetKeyboardState as mentioned in #489? The documentation for that suggests it only supports the 256 values from winuser.h.

Seems like a few APIs could benefit from this, so happy with any solution that works for both. Even if they're constants, as long as there's some way to know they're there, then that's a step in the right direction.

e.g. would eventually some of the Win32 docs be updated for usage with these types of wrappers? (like if I selected the 'C#' language in the docs or a remarks section for generated usage) Then it could call out that the VK_ parts can be generated or added in the `SendInput` doc too.

**Comment by mikebattista** [comment]
Since we can't have the same enum member names across enums for certain projections, I think I'll create an enum for winuser.h values and set KEYBDINPUT.wVk to that, and then create a second enum for xinput.h and set XINPUT_KEYSTROKE.VirtualKey to that.

That should cover the majority scenarios and you can always cast values from the other enum if you need to.

**Comment by mikebattista** [comment]
Reopening to add the synthesized values.
