### ISSUE TITLE
Question: Does the GDK work with WinRT?

### ISSUE THREAD

**Issue by xgalaxy** [microsoft/win32metadata#552]
Title basically says it all. I'm curious if the GDK is an API that can be exposed to Rust via the work that is being done in this library?

Thanks.

**Comment by mikebattista** [comment]
This is another instance of #66 which is something we are working on.

It's in early stages, but the idea is to provide some tooling to help others produce metadata for their C-style APIs that could then be plugged into our projections like the windows crate.

**Comment by mikebattista** [comment]
Our tooling to support this has been available for some time now. The GDK owners would need to adopt it to provide metadata for their APIs. I'd recommend filing an issue over at https://github.com/microsoft/GDK to track the request.

https://github.com/microsoft/win32metadata/issues/998 tracks improving documentation in this area. @riverar has gone through this process a few times now.
