### ISSUE TITLE
Missing type / consts for CONTEXT.ContextFlags

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/win32metadata#556]
bindings::Windows::Win32::System::Diagnostics::Debug::CONTEXT as a field named ContextFlags.

The values that one may set for this are difficult to find though they seem to be documented here: https://github.com/tpn/winsdk-10/blob/master/Include/10.0.14393.0/km/ntddk.h#L493-L517

There should either be a struct for this field, or at least just some consts for setting it properly somewhere in the metadata

**Comment by mikebattista** [comment]
@sotteson1 CONTEXT is an architecture-specific struct and the enum for each would be different looking at the headers. Can this be modeled with enums.json today?

**Comment by elachlan** [comment]
It looks like the constants are defined in `winnt.h`, but aren't scraped.
https://github.com/microsoft/win32metadata/blob/dc9c0c41654bd9126dff768b0a44114877cd6406/generation/WinSDK/RecompiledIdlHeaders/um/winnt.h#L4111-L4154

We can just manually define them in `enums.json`.
