### ISSUE TITLE
Add an attribute for identifying methods and functions that return alternative success codes

### ISSUE THREAD

**Issue by knopp** [microsoft/win32metadata#559]
For example `DoDragDrop` returns `DRAGDROP_S_DROP` on successful drop. However there doesn't seem to be any way to retrieve this value, since windows-rs immediately calls `ok()` on the `HRESULT`. And given that `DRAGDROP_S_DROP` doesn't have the error bit set it is not passed as error in the `Result`.

Is this an oversight?

**Comment by knopp** [comment]
Didn't even know that was an option :) Sounds great, though I'm not clear on how this would work. I assume every call like this would need to be tagged manually, since there's no way to infer this from headers?

**Comment by mikebattista** [comment]
You want an attribute that indicates that a function doesn't return S_OK on success?

**Comment by damyanp** [comment]
This is for functions that return success HRESULTs that aren't S_OK.  So it might return S_OK, but they may also return S_FALSE, or some other >0 HRESULT to include additional data about the result.

Generally in projections we'd like to map HRESULTs to exceptions or whatever the idiomatic error handling scheme is for a language.  Most (if not all) of these assume that there only one possible way to indicate "success" and don't have a natural way to return "I succeeded, but....".  

We can build these things, but it's pretty unnatural and we think that for the vast majority of Win32/COM APIs it would be unnecessary, so we're looking for a way to only do this for the cases where we know that applications want to check for non-S_OK success codes.

**Comment by mikebattista** [comment]
What would you like to see in the metadata specifically? I understand the scenario but I'm not clear how you want to model this.

**Comment by damyanp** [comment]
I was thinking of a per-function attribute that indicates that applications might want to inspect successful HRESULTs.

**Comment by mikebattista** [comment]
So just a boolean? And not a list of all possible success HRESULTs?

**Comment by damyanp** [comment]
It might be possible for projections to make use of all the HRESULTs, but in practice I suspect most will opt to just pass the HRESULT back to the caller somehow, so a boolean would be fine.  @kennykerr might have thoughts on this.

**Comment by kennykerr** [comment]
Just an attribute on functions/methods that return HRESULT. The attribute doesn't need any values (not even bool). It just signals to the languages that the HRESULT has alternate status codes.

**Comment by mikebattista** [comment]
> Just an attribute on functions/methods that return HRESULT. The attribute doesn't need any values (not even bool). It just signals to the languages that the HRESULT has alternate status codes.

Ok. We can add support for an attribute but will likely need to crowd source where to apply it.

**Comment by kennykerr** [comment]
So for example:

```C#
[DllImport("OLE32", ExactSpelling = true)]
[SupportedOSPlatform("windows5.0")]
[AlternateSuccessCodes] // <-- add this
public unsafe static extern HRESULT DoDragDrop([In] IDataObject pDataObj, [In] IDropSource pDropSource, [In] uint dwOKEffects, [In][Out] uint* pdwEffect);
```

**Comment by kennykerr** [comment]
Yep I'm sure folks will be happy to help report/list APIs that need the attribute.

**Comment by mikebattista** [comment]
Ok. We can add support for an attribute but will likely need to crowd source where to apply it.

**Comment by kennykerr** [comment]
Great, thanks!

**Comment by AArnott** [comment]
For this particular requirement, I agree a mere attribute is enough. However if we can document which HRESULTs may be expected, then projections can automatically emit those HRESULTs as constants as well.
Same for Win32Error codes.

It bites if the user asks for one method, then has to explicitly ask individually for 8 other error codes to be generated as well where the projection could have anticipated that given info from the metadata.

**Comment by damyanp** [comment]
I was wondering if we should extend this concept to cover other error return mechanisms?  An extreme example would be WaitForSingleObject.  There are also various functions that use the "return bool, use GetLastError" pattern that would be nice to map to idomatic error handling.  Many IO functions follow this, but we expect developers to know that ERROR_IO_PENDING is not actually an error.

We could add a new attribute for each error reporting mechanism (in which case I think we'd need to document that some attributes are mutually exclusive) or we could have a single "error_handling" attribute that has a parameter to indicate how projections to interpret return codes.

**Comment by mikebattista** [comment]
> There are also various functions that use the "return bool, use GetLastError" pattern that would be nice to map to idomatic error handling.

This is https://github.com/microsoft/win32metadata/issues/536.

**Comment by damyanp** [comment]
I think your understanding is correct.  From my POV I don't have a firm requirement for a one-attribute-to-rule-them-all vs individual attributes to handle the various cases.  I thinking about the potential issues with mutually exclusive attributes (eg you maybe you can't have AlternateSuccessCodes along with SetLastError).  However, maybe there's extra expressiveness to be had by allowing these attributes to be combined?  So maybe ReadFile would be both SetLastError and AlternateSuccessCodes(ERROR_IO_PENDING).

**Comment by mikebattista** [comment]
ReadFile already has `SetLastError = true` and returns false when GetLastError should be called. I view that as being able to infer the failure condition from the types and don't think another attribute is necessary for that piece.

ERROR_IO_PENDING is returned by GetLastError, not by ReadFile itself. Is this the same for the other I/O APIs you mentioned that behave like this? That seems a little different than a function that returns S_FALSE for success, which is what the original issue here is about. How would projections want to handle this? Would we need to differentiate return codes vs. GetLastError codes in the attributes?

Reading through https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile#pipes, it looks like ReadFile with pipes can also return false with GetLastError() = ERROR_MORE_DATA which is similar to ERROR_IO_PENDING. Again, what would be a natural way for projections to provide a friendlier interface on top?

**Comment by kennykerr** [comment]
To avoid losing the original request in the discussion, can we focus this issue on simply _adding an attribute for identifying methods and functions that return alternative success codes_? Other enhancements can be tracked as separate issues.

**Comment by ArturKovacs** [comment]
What's the status of this? It's nothing urgent, just wanted to express that I'm affected by this.

**Comment by mikebattista** [comment]
I think the conclusion of this issue is to introduce an `[AlternateSuccessCodes]` attribute with no other values, and rely on community contributions to apply it. Other potential issues discussed here should be split out into separate issues for consideration.

I will add the attribute and make sure [CONTRIBUTING.md](https://github.com/microsoft/win32metadata/blob/master/CONTRIBUTING.md) is updated with instructions for how to apply attributes to APIs.

**Comment by kennykerr** [comment]
Thanks @mikebattista, did you add this attribute to any existing functions that folks can use as an example to follow?

**Comment by mikebattista** [comment]
I added it to DoDragDrop and updated CONTRIBUTING.md with the details.

**Comment by kennykerr** [comment]
Super! Any chance we can have another build with this change for me to test with Rust? I see we haven't had a build in almost two months...

**Comment by mikebattista** [comment]
@sotteson1 can you publish a new NuGet package please?

**Comment by sotteson1** [comment]
> @sotteson1 can you publish a new NuGet package please?

Done.

**Comment by kennykerr** [comment]
So how do we annotate a Win32-style function for a new API so that the WinmdGenerator adds the attribute?

And any thoughts about just using the `PreserveSig` bit (already defined by ECMA335) rather than using a custom attribute?

**Comment by sotteson1** [comment]
> So how do we annotate a Win32-style function for a new API so that the WinmdGenerator adds the attribute?
> 
> And any thoughts about just using the `PreserveSig` bit (already defined by ECMA335) rather than using a custom attribute?

I think using PreserveSig is a good idea. I'm reopening the issue so I can change to use PreserveSig instead of AlternateSuccessCodes. That doesn't answer your first question about how to annotate new C APIs, though. Any ideas?

**Comment by kennykerr** [comment]
We could mint a new SAL-style annotation. 

```C++
#define _WIN32_METADATA_PRESERVESIG_

_WIN32_METADATA_PRESERVESIG_
STDAPI TestFunction();
```

That would allow us to eventually add it to the Windows SDK for in-box APIs (if desired) but also start using it today for new components and validation without waiting for a new SDK.

**Comment by riverar** [comment]
Should we also take this opportunity to move the attribute back to function-level? It doesn't really make sense to me to attach this attribute to the _return type_ itself.

**Comment by kennykerr** [comment]
The ECMA 335 `PreserveSig` bit is a flag on the `MethodDef` table.

**Comment by riverar** [comment]
@kennykerr Ah great, fixed itself! 👍

**Comment by AArnott** [comment]
In CsWin32 we default to preserving non-preservesig signatures, but users can specifically choose PreserveSig for certain methods that return multiple success codes. Is the proposal here then that the metadata express that so users don't have to?

**Comment by kennykerr** [comment]
Yes.

**Comment by kennykerr** [comment]
Another customer blocked by this issue: https://github.com/microsoft/windows-rs/issues/1371

**Comment by mikebattista** [comment]
https://task.ms/37680914

**Comment by sotteson1** [comment]
I'm changing this to use the 

> The ECMA 335 `PreserveSig` bit is a flag on the `MethodDef` table.

My fix will be to use this instead of using the attribute I was using before.

**Comment by kennykerr** [comment]
Just tried this in the latest update. I see the `AlternateSuccessCodes` was removed and the `PreserveSig` bit is set in its place. 

The trouble is that hundreds of other functions also have this set. I don't know if they were set before but I can't see how I can use the new bit in place of `AlternateSuccessCodes` if its applied so liberally.

**Comment by riverar** [comment]
Yeah seems to be set for all APIs.

https://github.com/microsoft/win32metadata/blob/27d2eb97afca09820cb5c66c750a1a97a3d1e71b/sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs#L1182-L1187

Doesn't appear using `PreserveSig` is appropriate and we should restore the method attribute.

**Comment by kennykerr** [comment]
Or remove it from all methods and just apply it to those that actually need it.

**Comment by sotteson1** [comment]
> Or remove it from all methods and just apply it to those that actually need it.

Yes, that's the right way to fix it.
