### ISSUE TITLE
C# Process APIs provide IntPtr needing explicit cast for HWD methods

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/win32metadata#560]
_Was told to follow issue here from [this conversation](https://github.com/microsoft/CsWin32/issues/61#issuecomment-867972665)._

The C# Process APIs use the `IntPtr` type, for instance when trying to get the handle from a `Process` [here](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.mainwindowhandle).

When then making a Win32 call to something like `SetForegroundWindow` this needs to be explicitly cast to the generated `HWD` wrapper (which is unintuitive):

```cs
PInvoke.SetForegroundWindow((HWD)process.MainWindowHandle);
```

It'd be great if the generated methods could directly accept the `IntPtr` type from C# or the generated `HWD` helper to have an implicit converter setup to do the cast directly for the developer.

Thanks!

**Comment by mikebattista** [comment]
@andrewarnott I think this would be a request of the projection. The Process API referenced here is the .NET API not a Win32 API. The request is to accept IntPtr wherever HWND is accepted to avoid the (HWND) cast.

**Comment by AArnott** [comment]
Ah, I may have misunderstood the feedback. I thought the IntPtr was coming from the metadata, but I see now it's coming from a BCL type.
@michael-hawker, I'm sorry to misdirect you. I'll reply again on that discussion. Let's close this issue since there's nothing for the metadata repo to do.
