### ISSUE TITLE
MapViewOfFile should generate an overload returning SafeMemoryMappedViewHandle

### ISSUE THREAD

**Issue by sharwell** [microsoft/win32metadata#561]
## Actual behavior

`MapViewOfFile` only generates an overload returning `void*`. 

## Expected behavior

A separate overload, e.g. a generated `MapViewOfFile_SafeHandle` method, should return `SafeMemoryMappedViewHandle`.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.MapViewOfFile.cs#L12-L18

https://referencesource.microsoft.com/#System.Core/Microsoft/Win32/SafeHandles/SafeMemoryMappedViewHandle.cs,fbe85260617a73ea

## Repro steps

1. `NativeMethods.txt` content:
```
MapViewOfFile
```

2. `NativeMethods.json` content (if present):

N/A

3. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.1.506-beta`
- Win32Metadata version (if explicitly set by project): N/A
- Target Framework: net45
- `LangVersion` (if explicitly set by project): `9`

**Comment by mikebattista** [comment]
What exactly do you want to see MapViewOfFile return instead of void *?

**Comment by sharwell** [comment]
@mikebattista I would expect it to return `SafeMemoryMappedViewHandle`, which is the same return type used by P/Invoke definitions for `MapViewOfFile` inside the .NET Framework.

**Comment by mikebattista** [comment]
That's how it would be projected, but I'm asking about the metadata.

**Comment by sharwell** [comment]
@AArnott would need to answer that part. I'm not sure how the metadata relates to the CsWin32 project, and I'm only aware of the output from the latter.

**Comment by mikebattista** [comment]
For example, CreateFile returns the below in the metadata which C#/Win32 translates into a .NET SafeHandle. Other projections handle it differently.

```
[RAIIFree("CloseHandle")]
[NativeTypedef]
public struct HANDLE
{
	public IntPtr Value;
}
```

@aarnott sounded like you wanted something similar here but could you clarify what definition you expect?

**Comment by AArnott** [comment]
Apparently the value returned from this method is supposed to be released with `UnmapViewOfFile`, so returning a typedef with an `[RAIIReleaseAttribute("UnmapViewOfFile")]` may be appropriate. Doing this in the metadata would result in a SafeHandle being generated in the C# projection. We could then reuse .NET's existing SafeHandle type to improve interop.

**Comment by mikebattista** [comment]
@sotteson1 @kennykerr 

So something like this?

```
[RAIIFree("UnmapViewOfFile")]
[NativeTypedef]
public struct MemoryMappedViewHandle
{
	public IntPtr Value;
}
```

**Comment by AArnott** [comment]
Yes, that looks good.

**Comment by marler8997** [comment]
Somewhat related, the Zig projection would be able to make use of some way of knowing which types are "handles" and which aren't.

Reason being is that Zig distinguishes between handles that are "optional", allowing `NULL` or `0` to be assigned to them and disallowing this for non-optional handles.  My current solution is I maintain a list of all the types in the metadata that are handles (https://github.com/marlersoft/zigwin32gen/blob/main/src/handletypes.zig#L7), but having this information in the metadata would mean other projections could utilize it as well.  This could be done with an attribute like `[IsHandle]` but I'm not picky.

**Comment by kennykerr** [comment]
Seems ok. https://github.com/microsoft/win32metadata/issues/423#issuecomment-860926678

**Comment by AArnott** [comment]
FWIW CsWin32 figures out which structs are handle by convention, and a tiny hard-coded list of one: https://github.com/microsoft/CsWin32/blob/14443c08be185c26d91da5acac8c6acaccd37622/src/Microsoft.Windows.CsWin32/Generator.cs#L3114-L3132

**Comment by mikebattista** [comment]
There are several MapViewOfFile APIs. We need clarity on which Unmap function should be used for each and what to do about additional flags if anything.

* MapViewOfFile
* MapViewOfFile3
* MapViewOfFile3FromApp
* MapViewOfFileEx
* MapViewOfFileExNuma
* MapViewOfFileFromApp
* MapViewOfFileNuma2

Available Unmap functions:

* UnmapViewOfFile
* UnmapViewOfFile2
* UnmapViewOfFileEx

**Comment by AArnott** [comment]
Thanks, @kalleolaviniemitalo.
Hmmm... when a function returns a handle that may need to be released in a variety of ways depending on inputs, IMO that's grounds to say just return IntPtr and leave the user to manage it.

**Comment by mikebattista** [comment]
If we return a `MemoryMappedViewHandle` for all of these functions but without an `RAIIFree`, does that buy us anything? Right now they all return `void*`.

**Comment by AArnott** [comment]
That's an interesting idea, as it retains more discoverable types than IntPtr would.
Can we get that same typedef struct to be used in each of the release methods, even though `[RAIIFree]` isn't present on the struct?

**Comment by mikebattista** [comment]
Yes we could update `Unmap*` to take this new typedef struct.

**Comment by riverar** [comment]
Re-opening this issue as I don't think `MapViewOfFile` should be returning a `MEMORYMAPPEDVIEW_HANDLE`.

From the docs:
> If the function succeeds, the return value is the starting address of the mapped view.

**Comment by riverar** [comment]
Looking at the .NET code in the original post, it appears this is just a _handle_ by name and is just a RAII wrapper around the returned `void*` that calls `UnmapViewOfFile` during dispose.

So proposed actions include:
* Change to `void*/IntPtr/etc.` return type
* Add `return:RAIIFree(UnmapViewOfFile)` attribute if supported/desired (Optional)

**Comment by mikebattista** [comment]
We can keep the autotype but change it to `void*` rather than `DECLARE_HANDLE`.

**Comment by riverar** [comment]
@kennykerr Can you double-check me here? Believe this change will resolve https://github.com/microsoft/windows-rs/issues/2436

**Comment by sharwell** [comment]
Is there not a type to represent both cases? If this change is reverted, it appears we are right back to the start with MapViewOfFile returning the wrong type.

**Comment by mikebattista** [comment]
I believe both should still work. The underlying type becomes void* which is consistent with the original API, and the handle you get back can be passed to `Unmap` to close it in a more type-friendly way.

**Comment by riverar** [comment]
> Is there not a way to represent both cases? If this change is reverted, it appears we are right back to the start with MapViewOfFile returning the wrong type. The method returns a value which is both a pointer and a handle that needs to be closed.

There's no handle in play for this API. That's just some .NET boilerplate (read: gibberish) to help folks not leak mappings.

**Comment by riverar** [comment]
The following APIs deal with pointers, not handles

```
MapViewOfFile
MapViewOfFile3
MapViewOfFile3FromApp
MapViewOfFileEx
MapViewOfFileExNuma
MapViewOfFileFromApp
MapViewOfFileNuma2
UnmapViewOfFile
UnmapViewOfFile2
UnmapViewOfFileEx
```

.NET `SafeMemoryMappedViewHandle` is a `SafeHandleZeroOrMinusOneIsInvalid` specialization that overrides `Release` to call `UnmapViewOfFile`. Or in other words, just a .NET wrapper. The .NET code comments seem to indicate the developers were aware the API does not return handles and just invented one on the spot.

```
/*============================================================
**
** Class:  SafeMemoryMappedViewHandle
**
** Purpose: Safe handle wrapping a MMF view pointer
**
** Date:  February 7, 2007
**
===========================================================*/
```

So to remain language neutral, I argue the aforementioned APIs should return a void*/IntPtr/etc. type. I'm not opposed to additional metadata that would assist others in generating RAII wrappers (e.g. [RAIIFree](https://github.com/microsoft/win32metadata/issues/389)). (I recognize that work is not yet complete though.)

**Comment by mikebattista** [comment]
We have many cases like this where we add a typedef that is returned by one API and passed to another. Unless you're saying these APIs are unlike all the others where we have void* typedefs, I'm unclear on the problem.

**Comment by riverar** [comment]
Is something like this possible?

Source:
```cpp
WINBASEAPI
...
LPVOID
WINAPI
MapViewOfFile(
  _In_ HANDLE hFileMappingObject,
  _In_ DWORD dwDesiredAccess,
  _In_ DWORD dwFileOffsetHigh,
  _In_ DWORD dwFileOffsetLow,
  _In_ SIZE_T dwNumberOfBytesToMap
);
```

Target:
```csharp
/* ... */
[return: RAIIFree("UnmapViewOfFile")]
public static extern void* MapViewOfFile(
  [In] HANDLE hFileMappingObject,
  [In] FILE_MAP dwDesiredAccess,
  [In] uint dwFileOffsetHigh,
  [In] uint dwFileOffsetLow,
  [In] UIntPtr dwNumberOfBytesToMap
);
```

Folks can then choose to do something with the RAIIFree attribute if needed.

**Comment by riverar** [comment]
Or if you want/need to create a type, at least drop the handle suffix, e.g. `MEMORY_MAPPED_VIEW`. (This then segues into the question of _how do I know what's real and what metadata created for convienence?_ covered by #1533.)

**Comment by mikebattista** [comment]
Was it the HANDLE suffix that was the problem? Or the fact that there was a NativeTypeDef at all? What you're suggesting is how we use typedefs in many places but everyone said that was problematic here.

**Comment by riverar** [comment]
Yeah the _HANDLE_ suffix was bugging me since the API doesn't deal with handles and restarted handle provenance discussion in the Rust community 😂

There's a separate discussion to be had about NativeTypeDefs and whatnot, but am okay to punt that.

**Comment by mikebattista** [comment]
So if we add back a void* NativeTypeDef but remove the HANDLE suffix, that works for everybody?

**Comment by riverar** [comment]
I suggested `[return: RAIIFree("UnmapViewOfFile")]` first because we have an outstanding (admittedly long-standing) issue where projection authors are forced to emit these metadata-generated typedefs (e.g. MEMORYMAPPEDVIEW). They are currently indistinguishable from real typedefs (e.g. HFONT) and therefore cannot be conditionally unwrapped so to speak. I think this goes against the idea that metadata represents the true Windows API surface, with extra bits--like invalid handle values and min target version--available for folks that want it on an opt-in basis.

Ideally the resolution to https://github.com/microsoft/win32metadata/issues/1533 would guide the fix here.

**Comment by mikebattista** [comment]
Let me know if anything looks wrong. Below is the `MetadataTypedef` definition that you can happily ignore if you want.

```
[InvalidHandleValue(0L)]
[MetadataTypedef]
public struct MEMORY_MAPPED_VIEW_ADDRESS
{
	public unsafe void* Value;
}
```

**Comment by riverar** [comment]
That looks okay to me. 

Am wondering if we can go an extra step and return the APIs to their roots to keep the core definitions separate from metadata sugar. Maybe something like:

```
[MetadataTypedef]
public struct MEMORY_MAPPED_VIEW_ADDRESS
{
   public unsafe void* Value;
}

[return: XxxReturns("MEMORY_MAPPED_VIEW_ADDRESS")]
public static extern void* MapViewOfFile(
  [In] HANDLE hFileMappingObject,
  [In] FILE_MAP dwDesiredAccess,
  [In] uint dwFileOffsetHigh,
  [In] uint dwFileOffsetLow,
  [In] UIntPtr dwNumberOfBytesToMap
);```

I think we have a similar issue already being tracked, will poke around.

**Comment by mikebattista** [comment]
That shouldn't generally be true. In the MapViewOfFile case, you should unwrap the struct to the native type within.

CreateCompatibleDC is interesting because it returns a MetadataTypedef (CreatedHDC) that is AlsoUsableFor a NativeTypedef (HDC) and you'd want the function to return the NativeTypedef.

Is this an outlier? Or did you run into other examples of this case?

**Comment by kennykerr** [comment]
> That shouldn't generally be true. In the MapViewOfFile case, you should unwrap the struct to the native type within.

I'm happy to do that but then I need the native type within `CreatedHDC` to be `HDC`, not `IntPtr`.

**Comment by kennykerr** [comment]
> Is this an outlier? Or did you run into other examples of this case?

Since the metadata drops the original type information, I have no way to determine how widespread this problem is.

**Comment by kennykerr** [comment]
That sounds good to me - I was never able to get `RAIIFree` to work practically. I'd rather the metadata prioritize accurately describing the original APIs.

**Comment by mikebattista** [comment]
Will do.



> I was never able to get `RAIIFree` to work practically. I'd rather the metadata prioritize accurately describing the original APIs.

For that, please take a look at https://github.com/microsoft/win32metadata/issues/389#issuecomment-1542503681 and let me know what you think.

**Comment by kennykerr** [comment]
I won't be using `RAIIFree` regardless, but I have to use `AlsoUsableFor` only because of these invented types. If the metadata accurately described the original APIs, then I wouldn't have to use `AlsoUsableFor` either. It's just a band aid to get back to the original types.

**Comment by mikebattista** [comment]
> It's just a band aid to get back to the original types.

That's not true. In the latest builds, HINSTANCE and HMODULE both exist and are interchangeable. That relationship is defined by AlsoUsableFor. You're going to have problems if you don't support this.

**Comment by kennykerr** [comment]
That's only because the metadata has two types for the same thing. If that's all it's for, you should probably consider calling it a "type alias" so that they're interchangeable rather than having two distinct types that now have to point at each other and have languages have to track down all uses of one or the other and allow then to be used interchangeably. That's just way too contrived in practice. Just have one type say `HINSTANCE` and add an attribute that says something like `TypeAlias("HMODULE")`.

**Comment by mikebattista** [comment]
They're both NativeTypedefs that exist in the headers. AlsoUsableFor means support implicit conversion between the types. C# can handle this just fine. I'm assuming Rust can as well.
