### ISSUE TITLE
WINHTTP_STATUS_CALLBACK's dwcontext param is incorrect 

### ISSUE THREAD

**Issue by rylev** [microsoft/win32metadata#562]
The metadata for WINHTTP_STATUS_CALLBACK looks like the following:

```
[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public unsafe delegate void WINHTTP_STATUS_CALLBACK([In][Out] void* hInternet, [In] UIntPtr dwContext, [In] uint dwInternetStatus, [In][Out] void* lpvStatusInformation, [In] uint dwStatusInformationLength);
```

However, it looks like `dwcontext` is being translated as a usize instead of as a pointer type:

```rust
pub type WINHTTP_STATUS_CALLBACK = unsafe extern "system" fn(
    hinternet: *mut ::std::ffi::c_void,
    dwcontext: usize, // This should probably be `*const c_void`
    dwinternetstatus: u32,
    lpvstatusinformation: *mut ::std::ffi::c_void,
    dwstatusinformationlength: u32,
);
```

**Comment by mikebattista** [comment]
@keith-horton

**Comment by mikebattista** [comment]
@keith-horton what are your thoughts on this?

**Comment by sotteson1** [comment]
I would argue the metadata is correct. You don't have to use a pointer for this value. The definition in the header is a uint of pointer size, which is what the metadata includes. The docs are wrong for saying it's a pointer to a dword. That's not what the header says at all.

**Comment by mikebattista** [comment]
Closing based on @sotteson1 's comment. Please reopen if you think more discussion is required.
