### ISSUE TITLE
IcmpCloseHandle and friends missing from Handle to IcmpHandle remapping

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#565]
`IcmpCreateFile` currently has its HANDLEs remapped to an IcmpHandle type. 
https://github.com/microsoft/win32metadata/blob/58a4e118f2d658b97a52ac25d4dbc9e9ab223fdd/generation/emitter/remap.rsp#L206-L207

The following APIs were not updated, resulting in a mismatch of fundamental handle types:
* Icmp6ParseReplies
* Icmp6SendEcho2
* IcmpCloseHandle
* IcmpParseReplies
* IcmpSendEcho
* IcmpSendEcho2
* IcmpSendEcho2Ex

**Comment by riverar** [comment]
@mikebattista Well that fast 🔥, thanks!

**Comment by riverar** [comment]
@mikebattista Is `IcmpHandle=IcmpHandle` right? Or should that be `HANDLE=IcmpHandle`?

```
Icmp6SendEcho2::IcmpHandle=IcmpHandle
IcmpCloseHandle::IcmpHandle=IcmpHandle
IcmpSendEcho::IcmpHandle=IcmpHandle
IcmpSendEcho2::IcmpHandle=IcmpHandle
IcmpSendEcho2Ex::IcmpHandle=IcmpHandle
```

**Comment by mikebattista** [comment]
The first IcmpHandle is the name of the parameter whose type we're changing. The second IcmpHandle is the name of the type we want to use for that parameter.

You can see in the diff below from the build with these changes that the types changed from HANDLE to IcmpHandle.

Windows.Win32.NetworkManagement.IpHelper.Apis.IcmpCloseHandle : IcmpHandle...HANDLE => IcmpHandle
Windows.Win32.NetworkManagement.IpHelper.Apis.IcmpSendEcho : IcmpHandle...HANDLE => IcmpHandle
Windows.Win32.NetworkManagement.IpHelper.Apis.IcmpSendEcho2 : IcmpHandle...HANDLE => IcmpHandle
Windows.Win32.NetworkManagement.IpHelper.Apis.IcmpSendEcho2Ex : IcmpHandle...HANDLE => IcmpHandle
Windows.Win32.NetworkManagement.IpHelper.Apis.Icmp6SendEcho2 : IcmpHandle...HANDLE => IcmpHandle

**Comment by riverar** [comment]
@mikebattista Ah, got it, thanks again!
