### ISSUE TITLE
WriteConsole missing Optional attribute in lpReserved

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#567]
The `lpReserved` parameter in the WriteConsoleA/WriteConsoleW functions is a pointer that can be `NULL`.  According to my understanding, this means it should include the `Optional` attribute.

Issue originated from https://github.com/marlersoft/zigwin32/issues/2.

**Comment by mikebattista** [comment]
@sotteson1 do all `LPVOID lpReserved` parameters need the `[Optional]` attribute regardless of what SAL annotations are in the headers?

**Comment by sotteson1** [comment]
Instead of adding ````[Optional]```` I plan on adding a new ````[Reserved]````. IMO that better captures the original SAL.

**Comment by marler8997** [comment]
So am I to understand that the metadata will not be using Optional to indicate whether or not pointers can be NULL?  Also, what exactly does "Reserved" mean?
