### ISSUE TITLE
Why is FLASHWINFO in Windows.Win32.System.Diagnostics.Debug?

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#569]
(10.2.84-preview via CsWin32 0.1.506-beta)

`PInvoke.FlashWindowEx` is in `Windows.Win32`, but its [parameter](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex#parameters) `FLASHWINFO` is in `Windows.Win32.System.Diagnostics.Debug`. I expected `FLASHWINFO` to be in the same namespace as `PInvoke.FlashWindowEx`.

It would be nice if the only using directive I needed for the sample below was `Windows.Win32`.

```cs
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.System.Diagnostics.Debug;

var mainForm = new MainForm();
// ...

PInvoke.FlashWindowEx(new FLASHWINFO
{
    cbSize = (uint)Marshal.SizeOf<FLASHWINFO>(),
    dwFlags = FLASHWINFO_FLAGS.FLASHW_ALL | FLASHWINFO_FLAGS.FLASHW_TIMERNOFG,
    hwnd = (HWND)mainForm!.Handle,
});
```

**Comment by jnm2** [comment]
So it doesn't get missed: `WIN32_ERROR` has the same issue. (https://github.com/microsoft/CsWin32/issues/329)

**Comment by mikebattista** [comment]
Where would you recommend these live?

**Comment by jnm2** [comment]
With any other structures used by functions that take or return window handles? I don't recall what the problem would be (if there was one) with every struct in winuser.h going into a single namespace.

**Comment by mikebattista** [comment]
FlashWindow can move to Windows.Win32.UI.WindowsAndMessaging.

Where do you recommend WIN32_ERROR live? Would it be a good candidate for Windows.Win32.Foundation?

@kennykerr for some thoughts as well.

**Comment by kennykerr** [comment]
`WIN32_ERROR` is in the same namespace as the `GetLastError` function that is typically used to return `WIN32_ERROR`. Why should it be moved elsewhere?

**Comment by mikebattista** [comment]
I moved FlashWindow. WIN32_ERROR seems to be in a reasonable place. Please file a new issue for that and recommend a namespace if you feel it should be moved.

**Comment by jnm2** [comment]
A reason I would give for both WIN32_ERROR and GetLastError to be in the root namespace is because they are part of the API usage of many functions which have nothing else in common. Extra using directives at the top of the file for such a universal situation does not seem great.

**Comment by mikebattista** [comment]
@kennykerr, any objections to moving Get/SetLastError and WIN32_ERROR to .Foundation? I think we had considered this before but there was concern that all of the constants of WIN32_ERROR in .Foundation would be noisy.

**Comment by mikebattista** [comment]
Will open a new issue for moving the error APIs.
