### ISSUE TITLE
Include interop APIs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#57]
Similar to #17, we need to include the most common interop APIs to allow Win32 and WinRT APIs to play nicely together.

```C++
#include <windows.ui.composition.interop.h>
#include <ShellScalingAPI.h>
#include <DispatcherQueue.h>
```

**Comment by sotteson1** [comment]
This has been fixed for a while.

**Comment by mikebattista** [comment]
@sotteson1 / @AArnott how do I use IUserConsentVerifierInterop for example. Adding this to NativeMethods.txt does not enable it. An example is https://github.com/AdamBraden/WindowsInteropWrappers/blob/master/CoreWindowInterop/UserConsentVerifierInterop.cs.

Reopening until we confirm all the interop classes listed here are supported.

**Comment by kennykerr** [comment]
That requires interop between WinRT and Win32 - you can do that in C++ and Rust. C#/Win32 would need to interop with C#/WinRT.

**Comment by mikebattista** [comment]
I see, so all of these are defined in the metadata now, but the projection needs to do some work to support them?

How did you handle this in Rust? When you say "interop with C#/WinRT", you mean C#/Win32 would need to take a dependency on that? Or C#/Win32 can implement what it needs to, but then the developer would also need a reference to C#/WinRT to use it?

**Comment by kennykerr** [comment]
Yes, this issue should be closed because Steve did the work to properly reference WinRT metadata from Win32 metadata. In the same way, language projections must honor the metadata by referencing WinRT types when they are mentioned by Win32 APIs (it doesn't work the other way as WinRT APIs can't refer to non-WinRT APIs). So in Rust, you can simply refer to both `Windows.Win32.winmd` and `Windows.WinRT.winmd` and the Windows crate will automatically find the references from the one to the other and generate the necessary bindings. Here's an example:

https://github.com/robmikh/minesweeper-rs/blob/master/src/window_target.rs

**Comment by mikebattista** [comment]
Got it. Thanks. I'll close and file an issue on C#/Win32.
