### ISSUE TITLE
IFELanguage.GetJMorphResult() return broken MORRSLT struct

### ISSUE THREAD

**Issue by manju-summoner** [microsoft/win32metadata#571]
Calling `IFELanguage.GetJMorphResult()` returns a corrupted `MORRSLT` because the type of `MORRSLT.BLKBuff` is not specified correctly.
[Replacing the type of `MORRSLT.BLKBuff` with `void*` instead of `char`](https://github.com/manju-summoner/CsWin32GetJMorphResultTest/blob/2c07add462fef5b78b42db70b12608ea13018489/CsWin32GetJMorphResultTest/FixedCode/MORRSLT.cs#L37-L38) will return correct results.

```C#
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal partial struct MORRSLT
{
	internal uint dwSize;
	internal win32.Foundation.PWSTR pwchOutput;
	internal ushort cchOutput;
	internal win32.Globalization.MORRSLT._Anonymous1_e__Union Anonymous1;
	internal win32.Globalization.MORRSLT._Anonymous2_e__Union Anonymous2;
	internal unsafe ushort* pchInputPos;
	internal unsafe ushort* pchOutputIdxWDD;
	internal win32.Globalization.MORRSLT._Anonymous3_e__Union Anonymous3;
	internal unsafe ushort* paMonoRubyPos;
	internal unsafe win32.Globalization.WDD* pWDD;
	internal int cWDD;
	internal unsafe void* pPrivate;
	//internal char BLKBuff;      //generated code
	internal unsafe void* BLKBuff;//fixed
```

Broken MORRSLT:
![image](https://user-images.githubusercontent.com/57256282/125220282-6857f780-e301-11eb-83ef-4f5a0ac7f4b9.png)

Correct MORRSLT:
![image](https://user-images.githubusercontent.com/57256282/125220361-87ef2000-e301-11eb-8730-732dc0154a20.png)

Sample code:
https://github.com/manju-summoner/CsWin32GetJMorphResultTest/tree/master/CsWin32GetJMorphResultTest

Execution result:
![image](https://user-images.githubusercontent.com/57256282/125220461-b967eb80-e301-11eb-9bd0-53498ef7e170.png)

**Comment by mikebattista** [comment]
@aarnott this field is typed as char in the metadata. Is this a C#/Win32 issue?

From the shared code snippet, it looks like you explicitly remap it to void*.

**Comment by KalleOlaviNiemitalo** [comment]
In \<msime.h\>, it is a flexible array member `WCHAR       BLKBuff[];` so the `void*` replacement isn't right either. GetJMorphResult allocates this structure and does not tell the caller how large it actually is. I don't understand what goes wrong in the generated code, though.

**Comment by AArnott** [comment]
> this field is typed as char in the metadata. Is this a C#/Win32 issue?

@mikebattista the OP's point is that `char` is wrong. So if that's what's in the metadata, then the metadata is wrong. See this from the OP:

```
	//internal char BLKBuff;      //generated code
	internal unsafe void* BLKBuff;//fixed
```

Looking more at [the header definition](https://dev.azure.com/microsoft/OS/_git/os.2020?path=%2Fonecoreuap%2Fsdktools%2Fcommontest%2FImeAuto%2FNativeService%2Finc%2Fmsime.h&version=GBofficial%2Fmain&line=245&lineEnd=253&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents), it's not clear what this should be. I agree `void*` isn't right either. I think it's a variable-length, *inline* character array. I can't remember how the metadata should be describing it.

**Comment by mikebattista** [comment]
>Looking more at the header definition, it's not clear what this should be. I agree void* isn't right either. I think it's a variable-length, inline character array. I can't remember how the metadata should be describing it.

Ok. Thanks. @sotteson1 can you take a look?

**Comment by sotteson1** [comment]
It should be char[0], which we're using to imply a variable-length array. I'll fix it.

**Comment by manju-summoner** [comment]
I tried CsWin32 0.1.560-beta using win32metadata 10.2.163-preview but it still broken.
This may not be an array problem, but a Char marshalling problem.

If I set `CharSet=CharSet.Unicode` in StructLayout, it works fine.
```C#
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal partial struct MORRSLT
{
	/* ... */
	internal __char_1 BLKBuff;

	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] // <- 
	internal struct __char_1
	{
```

As well, in the previous implementation, specifying 'CharSet=CharSet.Unicode' worked fine.
```C#
[StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)] // <- 
internal partial struct MORRSLT
{
	/* ... */
	char BLKBuff;
}
```

**Comment by AArnott** [comment]
@manju-summoner This isn't expected to work in CsWin32 until https://github.com/microsoft/CsWin32/issues/387 is fixed.

**Comment by manju-summoner** [comment]
I understand. I'll wait for the fix.
