### ISSUE TITLE
GUID_TFCAT_TIPCAP_COMLESS is missing from Windows::Win32::UI::TextServices

### ISSUE THREAD

**Issue by saschanaz** [microsoft/win32metadata#575]
[The search result](https://microsoft.github.io/windows-docs-rs/doc/windows/fn.create_instance.html?search=GUID_TFCAT_TIPCAP) lacks `GUID_TFCAT_TIPCAP_COMLESS` but it exists both in the header and the docs (although [not directly](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itfthreadmgrex-activateex)).

```cpp
// msctf.h
EXTERN_C const GUID GUID_TFCAT_TIPCAP_SECUREMODE;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_UIELEMENTENABLED;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_INPUTMODECOMPARTMENT;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_COMLESS;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_WOW16;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_IMMERSIVESUPPORT;
EXTERN_C const GUID GUID_TFCAT_TIPCAP_SYSTRAYSUPPORT;
```

Other items exist but only COMLESS one is missing.

**Comment by saschanaz** [comment]
I also wonder where `GUID_TFCAT_TIPCAP_TSF3` is from, since it doesn't exist anywhere.

**Comment by saschanaz** [comment]
Oh BTW it exists here:

https://github.com/microsoft/win32metadata/blob/efa1cf39def85074e53b3b5f6aaa1cdf8483cd31/generation/emitter/manual/TextServices.Manual.cs#L64

**Comment by mikebattista** [comment]
@sotteson1 any idea why this 1 GUID isn't making it into the metadata while the others that are defined in the same way are?
