### ISSUE TITLE
How to handle D3D12 Agility SDK and DirectML redist

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#580]
The [DirectX 12 Agility SDK](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/) and [DirectML redist](https://github.com/microsoft/DirectML/blob/master/Releases.md) both ship their most recent versions of the APIs outside of the SDK.  

The model they use is that there's a single, non-branching, versioning of these APIs.  But there's a period of time where the most recent version is only available via the redists.  

For example, we might have Agility SDK v20 contain an interface that doesn't exist in the Windows SDK until v10.0.xxxxx.x.  But we'd want middleware built against Agility SDK v20 to be able to interoperate with applications build against Windows SDK v10.0.xxxxx.x.

**Comment by mikebattista** [comment]
@sotteson1 sounds like another scenario for enabling other SDKs to produce their own winmd for consumption from our projections (#66 ). Could we try to onboard these to the msbuild tooling?

**Comment by DBouma** [comment]
Currently running into the same issue, are there any updates on this?

**Comment by mikebattista** [comment]
@damyanp do you own these redists? The owners would need to use our tooling to produce metadata out of their repos.

**Comment by mikebattista** [comment]
Closing out as the corresponding kit owners would need to produce their own metadata. I'd recommend filing issues in the corresponding repos to track the request.

**Comment by MarijnS95** [comment]
This is related to #998, right? @mikebattista seems the tooling is all there but just waiting for @riverar to document it all?

Is this something external developers can piece together to bind to the Agility SDK in Rust via windows-rs, or should we "wait" for the Agility SDK developers to ship the metadata first? (And then is `windows-rs` already capable of generating usable bindings out of these files, while relying on / linking against the generated `windows` crate?)

**Comment by MarijnS95** [comment]
@mikebattista I opened an issue for the Agility SDK at https://github.com/microsoft/DirectX-Headers/issues/79, as requested. Unfortunately I lack the context to properly describe _what_ needs to happen in this repo for `.winmd` files to be generated (CC #998/@riverar again for _linkable_ docs) but I hope this gets the ball rolling as we're in need of these bindings for quite some time :)

**Comment by riverar** [comment]
I can assist with getting them started with metadata generation, will work with you in that other issue. 👍
