### ISSUE TITLE
Many string constants are not being scraped

### ISSUE THREAD

**Issue by tim-weis** [microsoft/win32metadata#587]
None of the BCrypt named constants (such as the [CNG Algorithm Identifiers](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-algorithm-identifiers)) wind up in the generated metadata. The same is true for named constants in Wincrypt (e.g. [Constants for CryptEncodeObject and CryptDecodeObject](https://docs.microsoft.com/en-us/windows/win32/seccrypto/constants-for-cryptencodeobject-and-cryptdecodeobject)). Having those in metadata, and ultimately in language projections would greatly help.

**Comment by mikebattista** [comment]
Thanks for filing. We'll add these and other string constants that are missing.

**Comment by mikebattista** [comment]
https://task.ms/37680910

**Comment by mikebattista** [comment]
#610 was not addressed by this. Some of the constants missing from #720 were addressed, but others were not.

Could you take a look at the linked issues and add support for those string constants as well?

**Comment by sotteson1** [comment]
> #610 was not addressed by this. Some of the constants missing from #720 were addressed, but others were not.
> 
> Could you take a look at the linked issues and add support for those string constants as well?

I think this latest fix addresses the ones I missed, but if you see some more let me know.

**Comment by mikebattista** [comment]
Looks great. Thanks!
