### ISSUE TITLE
Need more metadata for `ushort**` to interpret as `char**`

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#59]
Like #54, the `IDispatch::GetIDsOfNames` method is also missing metadata to describe the element of the array represented by its `rgszNames` parameter as a character, so in C# we're getting `ushort**` instead of `char**`.

Are there many of these? Can we fix them all together instead of filing issues for each individual API we happen to notice?

**Actual**

```cs
unsafe int GetIDsOfNames([In][Out][Const] Guid* riid, [In][Out][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 2)] ushort** rgszNames, uint cNames, uint lcid, [Out][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 2)] int* rgDispId);
```

**Expected**

```cs
unsafe int GetIDsOfNames([In][Out][Const] Guid* riid, [In][Out][NativeTypeInfo(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPWSTR, SizeParamIndex = 2)] ushort** rgszNames, uint cNames, uint lcid, [Out][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 2)] int* rgDispId);
```

**Comment by sotteson1** [comment]
Fixed in latest release.
