### ISSUE TITLE
UIA_HWND should be mapped to HWND

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#593]
The UIAutomation API has its own typedef for HWND:

```C++
typedef void *UIA_HWND;
```

This should be replaced with `Windows.Win32.UI.WindowsAndMessaging.HWND` in metadata because it is really just an `HWND` that would be returned by functions like `FindWindowA` or `CreateWindowExA`.

**Comment by kennykerr** [comment]
Oh, and the UI Automation APIs end up dropping the `UIA_HWND` and decaying to `void*`. 

```C#
// Windows.Win32.UI.Accessibility.IUIAutomation
unsafe HRESULT ElementFromHandle([In] void* hwnd, [Out][RetVal] IUIAutomationElement* element);
```

The original definition is:

```C++
        virtual HRESULT STDMETHODCALLTYPE ElementFromHandle( 
            /* [in] */ __RPC__in UIA_HWND hwnd,
            /* [retval][out] */ __RPC__deref_out_opt IUIAutomationElement **element) = 0;
```

Again, this should be using the common `Windows.Win32.UI.WindowsAndMessaging.HWND` type.

**Comment by mikebattista** [comment]
So all occurrences of UIA_HWND in UIAutomationClient.h should be remapped to HWND?

**Comment by kennykerr** [comment]
Yep.

**Comment by mikebattista** [comment]
Ok. I think I covered all occurrences in the metadata.
