### ISSUE TITLE
enum PROCESSOR_ARCHITECTURE has wrong size, breaks MINIDUMP_SYSTEM_INFO

### ISSUE THREAD

**Issue by gix** [microsoft/win32metadata#596]
`PROCESSOR_ARCHITECTURE` is declared as `enum PROCESSOR_ARCHITECTURE : uint`, even though he native constants fit into 16 bits.

This breaks `MINIDUMP_SYSTEM_INFO` because it uses the enum as the type for the `ProcessorArchitecture` field (which is only 16 bits large):
```
public struct MINIDUMP_SYSTEM_INFO
{
    public PROCESSOR_ARCHITECTURE ProcessorArchitecture;
```

**Comment by sotteson1** [comment]
Fixed with https://github.com/microsoft/win32metadata/commit/63b00686f47a32f8498223607604099bfb85dfc0.
