### ISSUE TITLE
Missing metadata for NERR_*

### ISSUE THREAD

**Issue by Guiguiprim** [microsoft/win32metadata#598]
`NetUserEnum` is documented as being able to return `NERR_Success`, `NERR_BufTooSmall` and `NERR_InvalidComputer`.
But they have no definition within win32 metadata.

`NetUserEnum` return is not typed, where it could be if those values where inside `WIN32_ERROR`

**Comment by mikebattista** [comment]
Do you think NERR_ values should be made part of the WIN32_ERROR enum? Either we do that and return WIN32_ERROR from NetUserEnum, or we add/keep them as constants and continue to return uint.

**Comment by mikebattista** [comment]
I kept these as constants for now.
