### ISSUE TITLE
Anonymous and underscore names

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#60]
All these names give me the feeling we shouldn't be referring to them. As if they're generated/mangled by some tool and not meant for consumption. For example, this one appears to [show up in docs with a different type name](https://docs.microsoft.com/de-de/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/reference/profiler-event-mask-enumeration) but the same values.

How do we think about these types?

![image](https://user-images.githubusercontent.com/9845234/101266395-4a8b3a00-3703-11eb-834a-326ee6d95888.png)

**Comment by sotteson1** [comment]
I believe this are fixed now. If you find some that don't look right let me know. At the very least I no longer see any __MIDL__ 
enums or AnonymousEnum.
