### ISSUE TITLE
Incorrect IMAGE_FILE_HEADER structure generated for rust.

### ISSUE THREAD

**Issue by rveldhoven** [microsoft/win32metadata#601]
Hi,

I initially opened this issue in windows-rs. But I think it's more likely that this is an upstream issue related to this project. 

I'm trying to access the PE header of an image in my rust program.

The IMAGE_FILE_HEADER structure in my bindings is incorrectly generated.

The IMAGE_FILE_HEADER structure is defined in the SDK as:
```
typedef struct _IMAGE_FILE_HEADER {
    WORD    Machine;
    WORD    NumberOfSections;
    DWORD   TimeDateStamp;
    DWORD   PointerToSymbolTable;
    DWORD   NumberOfSymbols;
    WORD    SizeOfOptionalHeader;
    WORD    Characteristics;
} IMAGE_FILE_HEADER, *PIMAGE_FILE_HEADER;
```
However, my bindings have generated a DWORD sized ```Characteristics``` field:
```
#[repr(transparent)]
pub struct IMAGE_FILE_CHARACTERISTICS(pub u32);
```

This field should be u16, as per the SDK, and PE files used on Windows.

**Comment by sotteson1** [comment]
It looks like when the work was done to make the enum, it was based on a u32 because most of the structs using it are u32. But for this particular struct, it's u16. I think we will need to use a different enum for this one, or just not use an enum for this field.

**Comment by riverar** [comment]
I'm not seeing any reason to keep `IMAGE_FILE_CHARACTERISTICS` as uint32. Would just change that back to uint16. Where are you seeing uint32 usage?

**Comment by rveldhoven** [comment]
@riverar It happens when I try to use code generated by https://github.com/microsoft/windows-rs in my rust program. I originally filed this issue there. But looking through similar old issues it's more likely in this project. I don't know much about how either project works, so maybe this issue is in the wrong place?

For example, the following rust code:
```
    let location : u64 = unsafe
    {
        LoadLibraryA("file.exe").0 as u64
    };

    let va_aop : u64 = unsafe
    {
        let ptr_dos_header : *const IMAGE_DOS_HEADER = location as *const _;

        let ptr_nt_headers : *const IMAGE_NT_HEADERS64 = (location + (*ptr_dos_header).e_lfanew as u64) as *const _;

        let image_optional_header : IMAGE_OPTIONAL_HEADER64 = (*ptr_nt_headers).OptionalHeader;

        println!("AOP: 0x{:x}", image_optional_header.AddressOfEntrypoint);
    }
```
Will copy 4 bytes into the OptionalHeader, leading to corrupted data. 

Now that I look at it again, I notice also IMAGE_OPTIONAL_HEADER_MAGIC has the wrong size:

```
#[repr(transparent)]
pub struct IMAGE_OPTIONAL_HEADER_MAGIC(pub u32);
```

While the SDK says:
```
 WORD        Magic;
```

@sotteson1 I'm not really familiar with this project. But in both C and C++ and windows itself the PE header struct is the same in memory as it is on disk. That makes it very easy to work with, since you don't need to parse the header, but you can just cast a header in memory, like in the code above. I think this struct should be the source of truth, since this is the structure that is actually present at the start of every executable file on windows and UEFI. Correcting the size of the enums allows one to use the structures like you would in C/C++ when dealing with PE headers.

**Comment by riverar** [comment]
Sorry, my question was for the metadata itself / @sotteson1

**Comment by sotteson1** [comment]
> I'm not seeing any reason to keep `IMAGE_FILE_CHARACTERISTICS` as uint32. Would just change that back to uint16. Where are you seeing uint32 usage?

LOADED_IMAGE.Characteristics is using the same enum, and that field is u32.

**Comment by sotteson1** [comment]
> Now that I look at it again, I notice also IMAGE_OPTIONAL_HEADER_MAGIC has the wrong size:

I agree with that. It does look like it's using the wrong size. I'll fix both of these today.

**Comment by sotteson1** [comment]
I just noticed that IMAGE_SUBSYSTEM and IMAGE_DLL_CHARACTERISTICS are wrong too. :( We need to be careful when these enums are made to use a type of the same size as the original field.

**Comment by riverar** [comment]
> LOADED_IMAGE.Characteristics is using the same enum, and that field is u32.

Ah dang. Frustrating!

**Comment by sotteson1** [comment]
> > LOADED_IMAGE.Characteristics is using the same enum, and that field is u32.
> 
> Ah dang. Frustrating!

I am going to make the build fail when we override a field with an enum that is bigger than the original field. I wouldn't be surprised if this flushes out more errors lurking in the metadata.

**Comment by riverar** [comment]
Was just going to say, #596 looks related as well.

**Comment by kennykerr** [comment]
Any progress on this? We're getting more Rust developers bumping into this issue.

**Comment by sotteson1** [comment]
Sorry I haven't finished this yet. I just wrote the code to detect the problem and there's about 15 cases that need to get fixed.
