### ISSUE TITLE
How to use HRESULT with functions returning i32

### ISSUE THREAD

**Issue by kiron1** [microsoft/win32metadata#603]
For example the function [`InitializeSecurityContextW`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Security/Authentication/Identity/Core/fn.InitializeSecurityContextW.html) returns an `i32` where the return status code should be tested for [`SEC_E_OK`](https://docs.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-initializesecuritycontextw) which is of type [`HRESULT`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Foundation/constant.SEC_E_OK.html) which is implemented as:

```rust
#[repr(transparent)]
pub struct HRESULT(pub u32);
```

Doing:

```rust
let status = InitializeSecurityContextW(...);
if status == SEC_E_OK.0 {
  todo!();
}
```

The above snippet will give compiler errors _error[E0308]: mismatched types_: since comparing `i32` against `u32`.

Did there already a pattern/idiom emerge how to handle such situations, or am I missing something here? It could be a good addition to the [FAQ](https://github.com/microsoft/windows-rs/blob/master/docs/faq.md).

**Comment by KalleOlaviNiemitalo** [comment]
> various SEC_XXXX codes are defined as `SECURITY_STATUS` values including `SEC_E_OK`

`SEC_E_INSUFFICIENT_MEMORY` is defined as `((SECURITY_STATUS)0x1300)` in \<IssPer16.h\> but `_HRESULT_TYPEDEF_(0x80090300L)` in \<winerror.h\>. Other SEC_… macros likewise have different values between these two files. \<IssPer16.h\>, which is included from \<security.h\> if `ISSP_LEVEL == 16`, but `ISSP_LEVEL` is defined only in \<sspi.h\>, where the value is always 32. I guess \<IssPer16.h\> is only for 16-bit operating systems and `SECURITY_STATUS` in win32 is the same as `HRESULT`.
