### ISSUE TITLE
Question : why does COM/WinRT exist now ?

### ISSUE THREAD

**Issue by ghost** [microsoft/win32metadata#604]
pasting https://github.com/microsoft/WindowsAppSDK/issues/1153#issuecomment-895820435

> @AdamBraden would you mind answering a Existential-crisis concern ?

> if "win32 metadata" can enable "projections into different langs" for C-based win32 apis

> **_then why was on earth COM and it's evolution WinRT even created in the first place ?_**
_**why does COM/WinRT and c#/winrt, c++/winnrt even exist ?**_
 **_Is it an longterm ongoing attempt to discard/trash the whole idea/mechanism of COM/WinRT and their corresponding APIs ?_**

>(yes, I'm now also wondering why does even winUI 3 is subset of winrt instead of win32 metadata ?/why does Windows App SDK APIs are COM based instead of win32 metadata based ?)

or I don't have any clue what I'm saying ? (therefore probably someone can correct the understanding ?)

**Comment by mikebattista** [comment]
Well COM existed long before WinRT or Win32 Metadata. It doesn't really make sense to go back and reimplement thousands and thousands of existing APIs when we can make them available to more languages via metadata. And this project uses many of the innovations and design principles that were established first with WinRT.

WinRT APIs are basically metadata-first APIs that are authored in metadata with modern design patterns. For net new innovative APIs, authoring them in WinRT still makes sense. We have to do a lot of work here to translate the classic Win32 C-style APIs into metadata that we don't need to do when the APIs are authored themselves in metadata, which WinRT APIs are.

Happy to discuss further if you have more questions.

**Comment by ImJustAGhost** [comment]
thanks. Just a little one 

Is it impossible for api authors if they wanted to  author net new innovative c++ APIs completely in win32metadata going forward in the future instead of WinRT ?

  (and thus only maintaining one api surface instead of two)

**Comment by mikebattista** [comment]
We've been working on enabling others to produce winmds from C APIs like we did which could then be consumed by Win32 projections. You'd still be authoring in C/C++ in that case and then integrating tooling that would convert it to a winmd. There are pros and cons to different approaches and you should use the right tool for the job when authoring new APIs.

**Comment by ImJustAGhost** [comment]
understood the reasoning behind all this and also corrected the understanding.    thanks.
