### ISSUE TITLE
WinmdGenerator expects all import libs to be in a subfolder named `\x64\`

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#605]
Guessing this check is here for a reason, so opening an issue before I attempt a PR. I've worked around this limitation for now, so it's not blocking me.

https://github.com/microsoft/win32metadata/blob/19d594c3ce8077fcecded074d5d4db5205ad0bb7/sources/msbuild/MetadataTasks/ScanLibs.cs#L50-L52

**Comment by kennykerr** [comment]
This is becoming an issue for the Windows crate that now uses the winmd generator for testing.

**Comment by sotteson1** [comment]
Should be fixed in the latest release.
