### ISSUE TITLE
Can't find error type definitions in Win32 API

### ISSUE THREAD

**Issue by dotSlashLu** [microsoft/win32metadata#608]
Hi, when I run the below program I got a return value of 111, problem is how can I know what does it mean? 

```rust
mod bindings {
    windows::include_bindings!();
}

use std::convert::TryInto;
use std::mem::size_of;

use bindings::Windows::Win32::NetworkManagement::IpHelper;

fn main() {
    let mut info: IpHelper::FIXED_INFO_W2KSP1 = IpHelper::FIXED_INFO_W2KSP1::default();
    let mut buflen: u32 = size_of::<IpHelper::FIXED_INFO_W2KSP1>().try_into().unwrap();

    let ret = unsafe { IpHelper::GetNetworkParams(&mut info, &mut buflen) };
    println!(
        "info: {:?} buflen: {:?} ret: {:?}",
        info.HostName, buflen, ret
    );
}
```

I checked the [Windows API documentation](https://docs.microsoft.com/zh-cn/windows/win32/api/iphlpapi/nf-iphlpapi-getnetworkparams?redirectedfrom=MSDN), it seems this function will return values like `ERROR_BUFFER_OVERFLOW`, but I can't find any reference about these constants in the bindings reference.

I'm guessing there may be something wrong with the `buflen` value?

**Comment by dotSlashLu** [comment]
Thanks for putting this in the right place. 

Also, may I ask why I'm getting this error? Though I suspect it's caused by the wrong `bufsize`, but I don't have any clue. As the doc reads, the parameter is just the size of `FIXED_INFO_W2KSP1`. Is it because the memory layout difference from rust to C++? Thanks.

**Comment by kennykerr** [comment]
The memory layout should be identical between Rust and C++. I don't know this particular API but you can find an example here that might help:

https://docs.microsoft.com/en-us/windows/win32/api/iptypes/ns-iptypes-fixed_info_w2ksp1

**Comment by riverar** [comment]
Well that was fast. 🤠 Thanks again @mikebattista.
