### ISSUE TITLE
Constants in processthreadsapi.h missing

### ISSUE THREAD

**Issue by StephenCleary** [microsoft/win32metadata#609]
Looks like `PROC_THREAD_ATTRIBUTE_GROUP_AFFINITY` and `PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE` are missing, at least.

This issue could possibly be fixed by #563, with the wrinkle that `PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE` is not currently documented.

**Comment by mikebattista** [comment]
Thanks for filing.

These are nontrivial #defines that require more work to scrape. Assigning to Steve to investigate automatically detecting these before we resort to manually defining them.

**Comment by mikebattista** [comment]
https://task.ms/37680908
