### ISSUE TITLE
Missing Privilege constants

### ISSUE THREAD

**Issue by skystedt** [microsoft/win32metadata#610]
The Privilege constants seems to be missing, for example: `SE_DEBUG_NAME`

_NativeMethods.txt: warning PInvoke001: Method or type "SE_DEBUG_NAME" not found._

https://docs.microsoft.com/en-us/windows/win32/secauthz/privilege-constants#constants

**Comment by mikebattista** [comment]
The fix will be similar to #587. String constants are missing.

**Comment by sotteson1** [comment]
Fixed with the latest commit.
