### ISSUE TITLE
ReadOnlySpan<byte> friendly overload for WriteFile

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#612]
(0.1.506-beta)

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile#parameters has `void* lpBuffer, uint nNumberOfBytesToWrite`. Since the second parameter explicitly defines the previous parameter in terms of bytes, it seems like the friendly overload could replace both parameters with `ReadOnlySpan<byte> buffer`.

The benefit would be avoiding adding unsafe + fixed around the call.

**Comment by AArnott** [comment]
The request for the metadata repo is to change the `void*` parameter to be `byte*` instead.
