### ISSUE TITLE
MSIDBOPEN_PATCHFILE etc. for MsiOpenDatabase

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/win32metadata#618]
[MsiOpenDatabaseW](https://docs.microsoft.com/windows/win32/api/msiquery/nf-msiquery-msiopendatabasew) documentation lists constants like MSIDBOPEN_CREATEDIRECT that can be passed in the LPCWSTR szPersist parameter, as an alternative to a file name. These constants don't seem to be included in the metadata yet, or at least I cannot find them in <https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/ApplicationInstallationAndServicing/index.html>. MsiOpenDatabaseW itself is there, though.

The tricky thing is that the five other constants are integers cast to LPCTSTR but MSIDBOPEN_PATCHFILE is intended to be added to them with pointer+integer addition, so the header file defines it as an integer whose value depends on sizeof(TCHAR). In projections then, it might be better to model this as enum+enum addition and only cast the result to a pointer type.

**Comment by KalleOlaviNiemitalo** [comment]
I filed this just because <https://github.com/microsoft/win32metadata/issues/610> reminded me about the unusual definition. I don't really need the constants myself.

**Comment by mikebattista** [comment]
These definitions are definitely interesting. Assigning to Steve to help with how we want to handle these.

**Comment by sotteson1** [comment]
Adding a little research: this blog post indicates that MSIDBOPEN_CREATEDIRECT should always be 32.
https://devblogs.microsoft.com/setup/opening-patch-files-when-compiled-for-unicode/

**Comment by KalleOlaviNiemitalo** [comment]
Of course it will fail if just pass `(LPCTSTR)MSIDBOPEN_PATCHFILE` to MsiOpenDatabase. But if you use `MSIDBOPEN_READONLY + MSIDBOPEN_PATCHFILE` as documented, then it means `(LPCTSTR)32` and works OK.

**Comment by mikebattista** [comment]
I exposed these as `[Const]PWSTR` and added `MSIDBOPEN_PATCHFILE` as an `int` with the `UNICODE` value of 16.
