### ISSUE TITLE
Generated method signature may not be completely correct for cfapi->CfConnectSyncRoot

### ISSUE THREAD

**Issue by stefan-agl** [microsoft/win32metadata#619]
## Actual behavior

The definition of method CfConnectSyncRoot in cfapi.h is as follows: 

```C
STDAPI
CfConnectSyncRoot (
    _In_ LPCWSTR SyncRootPath,
    _In_ CONST CF_CALLBACK_REGISTRATION *CallbackTable,
    _In_opt_ LPCVOID CallbackContext,
    _In_ CF_CONNECT_FLAGS ConnectFlags,
    _Out_ CF_CONNECTION_KEY *ConnectionKey
    );
```

generated C# method signature is respectively

```cs
[SupportedOSPlatform("windows10.0.16299")]internal static unsafe win32.Foundation.HRESULT CfConnectSyncRoot(
    string SyncRootPath, 
    in win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION CallbackTable,
    void* CallbackContext, 
    win32.Storage.CloudFilters.CF_CONNECT_FLAGS ConnectFlags, 
    out win32.Storage.CloudFilters.CF_CONNECTION_KEY ConnectionKey) 
{ ... } 
```

where 

`_In_ CONST CF_CALLBACK_REGISTRATION *CallbackTable` 

translates to 

`in win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION CallbackTable`

This parameter as the name suggests is used to pass in a table of typed callbacks to handle certain filesystem events, however I am not completely sure if I fail to understand how to properly call the method, or is the parameter's type not generated correctly.

I became more suspicious when I looked at the P/Invoke signature provided by the Vanara project for the same method, which I add for reference: 

```cs
 [PInvokeData("cfapi.h", MSDNShortId = "287DA978-9797-48DF-9C90-BA53BB82475C")]
 public static HRESULT CfConnectSyncRoot(
    string SyncRootPath,
    CF_CALLBACK_REGISTRATION[] CallbackTable, 
    IntPtr CallbackContext, 
    CF_CONNECT_FLAGS ConnectFlags, 
    out CF_CONNECTION_KEY ConnectionKey);
```
There we have an array to pass for CallbackTable. 

I would like to know:

1. is the method signature generated correctly 
2. if yes, what would be the correct idiom in C# to call it (as I am currently becoming a C# programmer by necessity It is highly likely that I am missing something obvious here so please, do not spare details in any explanations that would follow)

## Repro steps

1. `NativeMethods.txt` content:
```
CldApi.*
```

2. Try to call `Windows.Win32.PInvoke.CfConnectSyncRoot` 

### Context

- CsWin32 version: v0.1.506-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net5.0-windows10.0.19041.0

Thanks and regards,
Stefan

**Comment by mikebattista** [comment]
Thanks for reporting this.

The original header defines this as:

```STDAPI
CfConnectSyncRoot (
    _In_ LPCWSTR SyncRootPath,
    _In_ CONST CF_CALLBACK_REGISTRATION *CallbackTable,
    _In_opt_ LPCVOID CallbackContext,
    _In_ CF_CONNECT_FLAGS ConnectFlags,
    _Out_ CF_CONNECTION_KEY *ConnectionKey
    );
```

and the metadata defines this as:

```
public unsafe static extern HRESULT CfConnectSyncRoot([In][Const] PWSTR SyncRootPath, [In][Const] CF_CALLBACK_REGISTRATION* CallbackTable, [Optional][In][Const] void* CallbackContext, [In] CF_CONNECT_FLAGS ConnectFlags, [Out] CF_CONNECTION_KEY* ConnectionKey);
```

which appears to mirror the original definition.

@AArnott / @sotteson1, what change in the metadata do you need to project this correctly? Or is there a bug in the projection itself?

**Comment by AArnott** [comment]
`CallbackTable` should be an array in the metadata. The header file (and docs) don't make this clear, but the parameter name suggests it, and all the sample uses prove it.

**Comment by chirayuharyan** [comment]
Hi, 
I am also facing this issue. Are there any plans of getting this issue fixed in any recent updates?

**Comment by mikebattista** [comment]
@aarnott do we just need to add `[NativeArrayInfo]` to this parameter?

**Comment by AArnott** [comment]
@mikebattista Yes, that would do it I think.
