### ISSUE TITLE
Several unexpected types in `Windows.Win32.System.WinRT`

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#621]
None of these belong here, since this namespace is for unmanaged calls to Windows Runtime (e.g. `RoInitialize`):

- `Windows.Win32.System.WinRT.Apis.CastingSourceInfo_Property_ProtectedMedia`
- `Windows.Win32.System.WinRT.Apis.CreateDirect3D11DeviceFromDXGIDevice`
- `Windows.Win32.System.WinRT.Apis.CreateRandomAccessStreamOnFile`
- `Windows.Win32.System.WinRT.Apis.E_SURFACE_CONTENTS_LOST`
- `Windows.Win32.System.WinRT.Apis.PdfCreateRenderer`

There are a few other examples that I can't be bothered to copy but are self-evident if you look at the metadata.

```msil
.method /* 0600273D */ public hidebysig static pinvokeimpl("Windows.Data.Pdf" nomangle winapi) 
	valuetype [Windows.Win32.winmd]Windows.Win32.Foundation.HRESULT PdfCreateRenderer (
		[in] class [Windows.Win32.winmd]Windows.Win32.Graphics.Dxgi.IDXGIDevice pDevice,
		[out] class [Windows.Win32.winmd]Windows.Win32.System.WinRT.IPdfRendererNative* ppRenderer
	) cil managed preservesig 
{
} // end of method Apis::PdfCreateRenderer
```

**Comment by mikebattista** [comment]
These all come from headers intended for WinRT interop, so I believe they're in the right namespace.
