### ISSUE TITLE
WinmdGenerator doesn't support multi-arch

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#626]
Back in April https://github.com/microsoft/win32metadata/pull/435 work was completed. It appears the tooling was updated for multi-arch support, aside from the MSBuild SDK/targets.

The related tasks appear to still be x64-only.
https://github.com/microsoft/win32metadata/blob/master/sources/msbuild/MetadataTasks/ScanLibs.cs#L38

Using the WinmdGenerator as it is today, it does not appear possible to generate the appropriate structures for something as such:
```cpp
#if defined(_AMD64_)
#pragma pack(8)
#else
#pragma pack(1)
#endif
struct Foo {
  char a;
  int b;
};
```

**Comment by sotteson1** [comment]
This is unfortunately true. I need to add multi-arch support to the scraper for external projects.

**Comment by kennykerr** [comment]
Likewise, this is becoming an issue for https://github.com/microsoft/windows-rs that now uses the winmd generator for testing.

**Comment by sotteson1** [comment]
This should be fixed with the latest release. Let me know if you run into any issues.
