### ISSUE TITLE
Explicit input/output parameters

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#63]
ECMA-335 provides the `In` flag for identifying input parameters (I I.23.1.13 Flags for params [ParamAttributes]). 

WinRT uses this for all input parameters. It would make it a lot simpler if we could rely on this instead of having to infer based on the absence of some set of other attributes. For Rust I have combined support for Win32 and WinRT and such differences are making parsing a bit harder.

For example, the win32 metadata currently defines `WNDENUMPROC` as follows:

```C#
public delegate int WNDENUMPROC(IntPtr param0, IntPtr param1);
```

WinRT metadata would always decorate those attributes with the `In` flag as follows:

```C#
public delegate int WNDENUMPROC([In] IntPtr param0, [In] IntPtr param1);
```

Can we do the same here?

**Comment by kennykerr** [comment]
Gentle reminder - this continues to be a stumbling block.

**Comment by sotteson1** [comment]
Here's the plan for parameters that don't have SAL parameters:
If it's a primitive or a COM pointer, it's In.
If it's a pointer or a COM double pointer (e.g. IUnknown**) it's In, Out.

Does that sound right?

**Comment by kennykerr** [comment]
Slight tweak (as there are no in/out COM interface pointers).

* If it's a primitive or a COM pointer, it's In.
* If it's a pointer it's In, Out.
* If it's a COM double pointer (e.g. IUnknown**), it's Out.

**Comment by sotteson1** [comment]
And another case I found: if it's a pointer marked const with SAL, we know it's only In.
