### ISSUE TITLE
Dhcp types are duplicated and top level ones are empty

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#632]
In the `Windows.Win32.NetworkManagement.Dhcp` namespace, the following "top level" types in the metadata are empty:

```
DHCP_SUBNET_ELEMENT_UNION
DHCP_OPTION_ELEMENT_UNION
DHCP_OPTION_SCOPE_UNION6
DHCP_CLIENT_SEARCH_UNION
DHCP_SUBNET_ELEMENT_UNION_V4
DHCP_SUBNET_ELEMENT_UNION_V6
```

Each of these empty types have a corresponding type definition with the same name, but that is nested within another type and whose definition is not empty.

My guess is either the nested types should be removed and the top-level types fixed to include the fields, or, the top-level types need to be removed and only the nested types are to be used.

**Comment by mikebattista** [comment]
Assigning to @keith-horton and @sotteson1 to investigate the header definitions and how they are being scraped.
