### ISSUE TITLE
Microsoft.Dia.Win32Metadata should express its dependency on Windows.Win32

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#634]
All nuget packages that carry metadata should express a nuget dependency on any dependencies that its winmd has. 
For example the Dia metadata's package should depend on the win32metadata package.

By following this rule, anyone that brings in some metadata package will automatically get all the others they need as well, rather than get errors from projections due to the inability to follow type references.

**Comment by AArnott** [comment]
We should consider how/whether to express a dependency on the docs package as well, where it exists, as this improves the quality of the generated code for projections that support it. For the projections that *don't* support it but where customers use nuget to acquire the metadata, a dependency would mean downloading an unused docs package.

**Comment by mikebattista** [comment]
In general, NuGet packages should declare this dependency. The WDK Metadata does this.

I've noticed, though, that updating this dependency with every build triggers additional check-ins of the tracked nuspec file.

Is there a way to avoid this other than removing the dependency in this case? We can't just gitignore the nuspec file.

**Comment by AArnott** [comment]
Ick. Ya we shouldn't be hard-coding versions to other dependencies that are built from the same repo. We should make the build itself determine the version and inject it into the nuspec. There are a few ways to do this. 
Maybe reactivate the issue and let me know if you want some samples or pointers on how to do this.

**Comment by mikebattista** [comment]
It's already automatically updated, but basically every check-in has an associated nuspec change given how nbgv works, which is what I was asking about.

**Comment by AArnott** [comment]
Wow. How did you automate that? Still, my recommendation would be to remove that hard-coded version from source control by generating it during the build. It's up to you though. I'm happy to help if you want.

**Comment by mikebattista** [comment]
I just updated an existing script that was updating the WinmdGenerator package version.

https://github.com/microsoft/win32metadata/commit/67b8c7e945a884cd0b4ad6adbf9c74b309610a71#diff-9c945a44af955464473358e6faa4e7e08882c6162c506393eacae9e89f09f476
