### ISSUE TITLE
Should a metadata package depend on its docs package?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#635]
We should consider how/whether to express a dependency on the docs package as well, where it exists, as this improves the quality of the generated code for projections that support it. For the projections that don't support it but where customers use nuget to acquire the metadata, a dependency would mean downloading an unused docs package.

**Comment by mikebattista** [comment]
Projections that support the docs can declare the dependency on the package themselves like C#/Win32 does. I'd rather not declare the dependency given the potential undesirable downloading when it's not wanted.
