### ISSUE TITLE
The metadata is missing these functions

### ISSUE THREAD

**Issue by lygstate** [microsoft/win32metadata#639]
```
EnumProcessModulesEx
GetWsChangesEx
QueryWorkingSetEx
```
```
InterlockedCompareExchange64 for 32bit kernel.dll
```

**Comment by marler8997** [comment]
This title is a bit misleading, probably better to say, "The metadata is missing these functions".  You current title makes it sound like the functions are in the metadata but the win32json project "lost them", which would not be an issue for the metadata project.

I verified these functions are missing from the metadata.  You can also verify this for yourself by downloading the winmd nuget package (see https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/).  You can extract it like a zip file, then look at the winmd file with ILSpy.

**Comment by mikebattista** [comment]
These all have K32-prefixed equivalents. psapi.h is a bit weird here.

Assigning to @sotteson1 to look at how to address this.

**Comment by mikebattista** [comment]
Related issue: https://github.com/microsoft/win32metadata/issues/229.
