### ISSUE TITLE
RtlInstallFunctionTableCallback has questionable multi-arch definitions

### ISSUE THREAD

**Issue by lygstate** [microsoft/win32metadata#640]
```
Duplicated RtlAddFunctionTable
Duplicated RtlDeleteFunctionTable
Duplicated RtlInstallFunctionTableCallback
Duplicated RtlAddGrowableFunctionTable    
Duplicated RtlLookupFunctionEntry
Duplicated RtlVirtualUnwind
Duplicated ImageNtHeader
Duplicated ImageRvaToSection
Duplicated ImageRvaToVa
Duplicated JsCreateContext
Duplicated JsStartDebugging
Duplicated GetDeviceID
```

**Comment by marler8997** [comment]
These duplications are intentional because they have different architectures.

**Comment by marler8997** [comment]
`GetDeviceID` is an exception though.  It actually has 2 definitions, one in `Media.Audio.DirectMusic` and one in `System.TpmBaseServices`.  This might be the only symbol in all of win32 that is duplicated.

**Comment by lygstate** [comment]
> These duplications are intentional because they have different architectures.

Hi, I've seen the architecture things, but still they  can be merged into a single function:)
I seen other functions with multiple architecture also just have a single signature:)

**Comment by marler8997** [comment]
I see, yes some of these might be able to be merged more then they are.  For example, `RtlAddFunctionTable` has 2 different signatures for `X64` and `Arm64`, but they are both pretty much the same, the only difference being that one uses `UInt64` and the other uses `UIntPtr` which should be the same for these 64-bit systems.

On the other side, the next function you listed `RtlDeleteFunctionTable` looks like it has a legitimate difference in signature.  One takes `IMAGE_RUNTIME_FUNCTION_ENTRY` and the other takes `IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY` which look to be different structures.

So it looks like someone could go over these and see if there's something that can be done to consolidate signatures when possible.

**Comment by riverar** [comment]
Is there an issue this is causing?

**Comment by AArnott** [comment]
Where functions in the metadata are declared as unique per CPU architecture unnecessarily, it makes them inaccessible to CPU-agnostic compilers such as AnyCPU-targeting C#. So yes, if it's true that such functions could be merged into one declaration safely, we should endeavor to do so.

**Comment by riverar** [comment]
I'm confused because none of the listed APIs appear to be candidates for merging. They all differ in inputs (e.g. structures with different packing/alignment) or outputs. The API @marler8997 proposed as a candidate (`RtlAddFunctionTable`) has structure input differences.

What am I missing?

**Comment by AArnott** [comment]
I haven't looked into any of these myself, but according to @marler8997's comment above, `RtlAddFunctionTable` is effectively the same between ARM64 and X64, modulo one difference that shouldn't impact the ABI.

**Comment by AArnott** [comment]
I went through the whole list, and the only function that looks like legitimate candidate for merging across architectures is `RtlInstallFunctionTableCallback`.

![image](https://user-images.githubusercontent.com/3548/132593644-69f32dfe-04a4-476c-856c-4d187dcc599b.png)

**Comment by riverar** [comment]
I think that one may need more investigation. But it does appear collapsing into the `native uint` variant may work well here.

I hesitate because there appears to be an underlying bug that, when resolved, might resolve this issue automatically. That is, `RtlInstallFunctionTableCallback` is defined in amd64, arm, and arm64 contexts. But the metadata strangely has two `RtlInstallFunctionTableCallback` variants pointing to a `PGET_RUNTIME_FUNCTION_CALLBACK` that is annotated only with a `[SupportedArchitecture(Windows.Win32.Interop.Architecture.Arm64)]` attribute. I understand that arm is unsupported but it appears this is still bugged for amd64.

**Comment by marler8997** [comment]
> I'm confused because none of the listed APIs appear to be candidates for merging. They all differ in inputs (e.g. structures with different packing/alignment) or outputs. The API @marler8997 proposed as a candidate (RtlAddFunctionTable) has structure input differences.

> What am I missing?

Ah it appears I was the one missing something :)

**Comment by lygstate** [comment]
I've looking into these functions, I found they were different because depends on different struct type  such
 as

`IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY ` vs `IMAGE_RUNTIME_FUNCTION_ENTRY`
Maybe we need merge these types first?
As all of these functions are depends on different type have different layout on different architecture.
But the parameter count are the same

**Comment by lygstate** [comment]
`GetDeviceID` are import from different dll so that's not a issue

**Comment by AArnott** [comment]
@lygstate: where structs have different names in the native headers, we will not be merging them in the metadata.

**Comment by riverar** [comment]
@lygstate Are you hitting any problems with the metadata? Or are you just curious about the duplicates?

To provide a bit more background on @AArnott's comment, here are three variants of the structure you mentioned. Note how they represent different things! Also remember these structures may be aligned/packed differently depending on the architecture. I think it's fair to say these would be challenging to merge.

```cpp
typedef struct _IMAGE_RUNTIME_FUNCTION_ENTRY {
    DWORD BeginAddress;
    DWORD EndAddress;
    union {
        DWORD UnwindInfoAddress;
        DWORD UnwindData;
    } DUMMYUNIONNAME;
}
```

```cpp
typedef struct _IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY {
    DWORD BeginAddress;
    union {
        DWORD UnwindData;
        struct {
            DWORD Flag : 2;
            DWORD FunctionLength : 11;
            DWORD RegF : 3;
            DWORD RegI : 4;
            DWORD H : 1;
            DWORD CR : 2;
            DWORD FrameSize : 9;
        } DUMMYSTRUCTNAME;
    } DUMMYUNIONNAME;
}
```

```cpp
typedef struct _IMAGE_ARM_RUNTIME_FUNCTION_ENTRY {
    DWORD BeginAddress;
    union {
        DWORD UnwindData;
        struct {
            DWORD Flag : 2;
            DWORD FunctionLength : 11;
            DWORD Ret : 2;
            DWORD H : 1;
            DWORD Reg : 3;
            DWORD R : 1;
            DWORD L : 1;
            DWORD C : 1;
            DWORD StackAdjust : 10;
        } DUMMYSTRUCTNAME;
    } DUMMYUNIONNAME;
}
```

**Comment by lygstate** [comment]
> @lygstate Are you hitting any problems with the metadata? Or are you just curious about the duplicates?
> 
> To provide a bit more background on @AArnott's comment, here are three variants of the structure you mentioned. Note how they represent different things! Also remember these structures may be aligned/packed differently depending on the architecture. I think it's fair to say these would be challenging to merge.
> 
> ```c++
> typedef struct _IMAGE_RUNTIME_FUNCTION_ENTRY {
>     DWORD BeginAddress;
>     DWORD EndAddress;
>     union {
>         DWORD UnwindInfoAddress;
>         DWORD UnwindData;
>     } DUMMYUNIONNAME;
> }
> ```
> 
> ```c++
> typedef struct _IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY {
>     DWORD BeginAddress;
>     union {
>         DWORD UnwindData;
>         struct {
>             DWORD Flag : 2;
>             DWORD FunctionLength : 11;
>             DWORD RegF : 3;
>             DWORD RegI : 4;
>             DWORD H : 1;
>             DWORD CR : 2;
>             DWORD FrameSize : 9;
>         } DUMMYSTRUCTNAME;
>     } DUMMYUNIONNAME;
> }
> ```
> 
> ```c++
> typedef struct _IMAGE_ARM_RUNTIME_FUNCTION_ENTRY {
>     DWORD BeginAddress;
>     union {
>         DWORD UnwindData;
>         struct {
>             DWORD Flag : 2;
>             DWORD FunctionLength : 11;
>             DWORD Ret : 2;
>             DWORD H : 1;
>             DWORD Reg : 3;
>             DWORD R : 1;
>             DWORD L : 1;
>             DWORD C : 1;
>             DWORD StackAdjust : 10;
>         } DUMMYSTRUCTNAME;
>     } DUMMYUNIONNAME;
> }
> ```

Gocha, even though they  have different representation, but seems they were the same 3*4 bytes?
I am not sure if they were affected by the pack option

**Comment by KalleOlaviNiemitalo** [comment]
> seems they were the same 3*4 bytes?

_IMAGE_RUNTIME_FUNCTION_ENTRY is three DWORDs, but _IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY and _IMAGE_ARM_RUNTIME_FUNCTION_ENTRY are only two DWORDs each.

**Comment by mikebattista** [comment]
> I think that one may need more investigation. But it does appear collapsing into the `native uint` variant may work well here.
> 
> I hesitate because there appears to be an underlying bug that, when resolved, might resolve this issue automatically. That is, `RtlInstallFunctionTableCallback` is defined in amd64, arm, and arm64 contexts. But the metadata strangely has two `RtlInstallFunctionTableCallback` variants pointing to a `PGET_RUNTIME_FUNCTION_CALLBACK` that is annotated only with a `[SupportedArchitecture(Windows.Win32.Interop.Architecture.Arm64)]` attribute. I understand that arm is unsupported but it appears this is still bugged for amd64.

Given the discussion, is this the only remaining outstanding issue here?

**Comment by riverar** [comment]
@mikebattista Agreed.

**Comment by mikebattista** [comment]
Thanks. Assigning to @sotteson1 to look at how RtlInstallFunctionTableCallback is defined across architectures.
