### ISSUE TITLE
winmdgenerator: 0.2.185-preview nuget is broken

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#644]
MetadataTasks.dll is indeed missing https://nuget.info/packages/Microsoft.Windows.WinmdGenerator/0.2.185-preview

```
Sdk.targets(19,5): error MSB4062: The "MetadataTasks.CompileIdls" task could not be loaded from the assembly
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.185-preview\tools\net5.0\MetadataTasks.dll.

Could not load file or assembly
'C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.185-preview\tools\net5.0\MetadataTasks.dll'.

The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly
and all its dependencies are available, and that the task contains a public class that implements
Microsoft.Build.Framework.ITask.
```

**Comment by riverar** [comment]
@sotteson1 @AArnott Can you please attach the build artifacts when that's done? I'd like to try it out. (Or alternatively elevate my access 😁)

**Comment by AArnott** [comment]
Here you go: 
[NuGetPackages.zip](https://github.com/microsoft/win32metadata/files/7163637/NuGetPackages.zip)

**Comment by riverar** [comment]
Please re-open, this is still broken. @AArnott @sotteson1 

```
error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.
```

**Comment by sotteson1** [comment]
I'll take a look. I think it's because we moved to use global.json instead of specifying the version explicitly.

**Comment by AArnott** [comment]
Oh, that's interesting. @riverar could you try specifying the sdk version in a global.json file in your repo just to see if that unblocks you?

Something like this:
https://github.com/microsoft/win32metadata/blob/dd8c7462926a3b62c98c2b91e968387b3dcac649/global.json#L7-L8

@sotteson1 if your suspicion is correct, then I'd adjust my recommendation to relying on global.json to set the version everywhere except in files that ship to the customer.

**Comment by sotteson1** [comment]
Specifying the version of Microsoft.Build.NoTargets in the Import elements seems to fix it. I'll make a fix for it.

**Comment by riverar** [comment]
@AArnott That does unblock, thanks, but would prefer not to have this file.

**Comment by sotteson1** [comment]
> @AArnott That does unblock, thanks, but would prefer not to have this file.

This fix I'm making won't require that file.

**Comment by riverar** [comment]
Standing by to retry with new packages.

**Comment by sotteson1** [comment]
Try this one:

[NuGetPackages_latest.zip](https://github.com/microsoft/win32metadata/files/7174929/NuGetPackages_latest.zip)

**Comment by riverar** [comment]
@sotteson1 Works 👍

**Comment by riverar** [comment]
Heads up, the NuGet version hasn't been replaced nor a new version released yet.
