### ISSUE TITLE
COMBOBOX_STYLE and BUTTON_STYLE not avalilable anymore

### ISSUE THREAD

**Issue by zgabi** [microsoft/win32metadata#646]
## Actual behavior

COMBOBOX_STYLE and BUTTON_STYLE enums are not generated.
In the previous version it was there

## Expected behavior

COMBOBOX_STYLE and BUTTON_STYLE enum (or at least it's values) are available

## Repro steps

1. `NativeMethods.txt` content:
```
...
FindWindowEx
COMBOBOX_STYLE
BUTTON_STYLE
...
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.560-beta
- Target Framework: net5.0

**Comment by mikebattista** [comment]
I see the values in the metadata. If you list specific values in NativeMethods.txt, are they generated?

**Comment by zgabi** [comment]
Yes, If I add the calues, they are generated, but not the whole enum, as it was earlier.

**Comment by mikebattista** [comment]
Ok. Removing the enums was by design as part of #121 as Andrew pointed out. You can follow the discussion there for the reasoning.
