### ISSUE TITLE
Should FARPROC really be typed as an IntPtr-returning delegate?

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#651]
I thought a FARPROC would be a pointer to a function. But in the metadata it's defined as a delegate that returns an `IntPtr`. Is it really appropriate to give it a delegate type as if we knew the function signature?

**Comment by sotteson1** [comment]
We emit pointers to functions as delegates. Here's the definition in the header:

````
typedef INT_PTR (FAR WINAPI *FARPROC)();
````

**Comment by AArnott** [comment]
Ya, I saw that, but my C reading skills are rusty. I'll take your word for it that that's a pointer-returning function pointer.
Thanks.
