### ISSUE TITLE
Missing 22000 SDK era APIs (e.g. ioringapi.h)

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#660]
Folks are coming online with 22000.xxx (e.g. OEMs were given media), so just want to put this here to ensure 22000 is on the radar.

Example: [ioringapi.h](https://docs.microsoft.com/en-us/windows/win32/api/ioringapi/?WT.mc_id=WD-MVP-5002756)

**Comment by mikebattista** [comment]
Yes we will update to the latest SDK.
