### ISSUE TITLE
Requesting new winmdgenerator NuGet

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#662]
Am attempting to generate metadata for static libs but there are no current/working winmdgenerator packages at this time.

0.3-preview: ok [(not published)](https://github.com/microsoft/win32metadata/issues/644#issuecomment-920567545)
0.2.185-preview: broken
0.2.163-preview: broken (doesn't produce winmd files)
0.2.118-preview: ok (but doesn't support static libs)

**Comment by kennykerr** [comment]
@sotteson1 this is holding up [windows-rs](https://github.com/microsoft/windows-rs) - any chance you can take a look? It's also been a while since the last release of the win32 metadata itself.

**Comment by sotteson1** [comment]
I'm working on a big change to the generator that will allow for multi-arch support and all the other options that the main winsdk generator can use. I hope to have it out today.

**Comment by sotteson1** [comment]
Sorry this came a little later than I thought. Getting it over the finish line took longer than I thought it would. Let me know if you run into any issues.
