### ISSUE TITLE
NTDDI_WINTHRESHOLD has wrong value

### ISSUE THREAD

**Issue by roblabla** [microsoft/win32metadata#663]
https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/ApplicationInstallationAndServicing/constant.NTDDI_WINTHRESHOLD.html

This should be 0x0A000000. Instead it's 0x06040000.

**Comment by mikebattista** [comment]
I resolved the conflict with msi.h. You should find the correct values along with other constants from sdkddkver.h under Windows.Win32.System.SystemInformation going forward.
