### ISSUE TITLE
SIO_GET_EXTENSION_FUNCTION_POINTER missing constant

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#671]
Porting some code I came across this missing constant. 

```C++
#define SIO_GET_EXTENSION_FUNCTION_POINTER  _WSAIORW(IOC_WS2,6)
```

**Comment by kennykerr** [comment]
It is used with the `WSAIoctl` function.

**Comment by mikebattista** [comment]
Do these go in the `dwIoControlCode` parameter of `WSAIoctl` and `WSPIoctl`? Is https://docs.microsoft.com/en-us/windows/win32/winsock/winsock-ioctls the full set? Should this be an enum? @keith-horton

**Comment by kennykerr** [comment]
`dwIoControlCode`

**Comment by keith-horton** [comment]
Yes, what Kenny pointed out is indeed a dwIoControlCode to be passed to WsaIoctl. I just looked and it seems we have most, but not all, IOTCL control codes documented on that MSDN page.

Some are declared in mstcpip.h, some in mswsock.h, most in ws2def.h.
Then there are the bluetooth IOCTLs if someone creates a Bluetooth socket (Sockets can be created for things other than TCPIP sockets). those are in ws2bth.h.

This might be an easier developer story if it's an enum - the challenge being controlling how all of these get pulled in from different headers :(

**Comment by mikebattista** [comment]
Thanks. Consolidating across headers is easy. The harder part is teaching the tools how to scrape these constants that are defined with macros, but it's doable.

If you could provide the definitive list of all the values that need to be included in the enum and from what headers, that would help. Also, we should update the documentation to include any missing control codes.

**Comment by kennykerr** [comment]
Any chance we can wrap up these winsock issues I reported in September?

**Comment by keith-horton** [comment]
Sorry, I've had negative time since August to derive a definitive list. I'll talk internally how to farm this stuff out so I'm not the bottleneck for every networking API :(
