### ISSUE TITLE
PIPE_ACCESS_DUPLEX wrong namespace

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#672]
I think this should be in the `Windows.Win32.System.Pipes` namespace along with the other Named Pipe APIs, rather than in the `Windows.Win32.System.WindowsProgramming` namespace.

**Comment by kennykerr** [comment]
Same for `PIPE_UNLIMITED_INSTANCES`.

**Comment by kennykerr** [comment]
And a few others like `PIPE_ACCESS_INBOUND` etc.

**Comment by mikebattista** [comment]
Many of these were moved as part of https://github.com/microsoft/win32metadata/commit/f46775e2b61a419006e3338b9df7bd4c6911da10.

I think the only remaining one is PIPE_UNLIMITED_INSTANCES.
