### ISSUE TITLE
`SOCKADDR_IN`'s `sin_family` field should be `ADDRESS_FAMILY` type

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#673]

**Comment by kennykerr** [comment]
Just make sure you check the size. `sin_family` is 16 bits while `ADDRESS_FAMILY` is 32 bits. One of them is wrong.

**Comment by kennykerr** [comment]
Same with `SOCKADDR_IN6` and `sin6_family`.

**Comment by kennykerr** [comment]
And `SOCKADDR` and `sa_family`.

**Comment by mikebattista** [comment]
The `ADDRESS_FAMILY` enum in the metadata today is used by APIs like `GetTcpStatisticsEx` and `GetAdaptersAddresses` which are typed as `ULONG`. This enum also lives over in `Windows.Win32.NetworkManagement.IpHelper` while `SOCKADDR*` are under `WinSock`.

How should we handle this?

**Comment by mikebattista** [comment]
This appears to be fixed now.
