### ISSUE TITLE
HeapAlloc doesn't set the calling thread's last error code

### ISSUE THREAD

**Issue by tim-weis** [microsoft/win32metadata#674]
The documentation for [HeapAlloc](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) has the following paragraph in the *Return value* section:

> If the function fails, it does not call `SetLastError`. An application cannot call `GetLastError` for extended error information.

Conversely, this API call is [currently listed](https://github.com/microsoft/win32metadata/blob/b07213e28bcc48221c155024f9c5e0e1a92c6497/generation/WinSDK/WithSetLastError.rsp#L1588) in the *WithSetLastError.rsp* file. Is this intentional or an oversight that should be addressed?

**Comment by KalleOlaviNiemitalo** [comment]
Similar to <https://github.com/microsoft/win32metadata/issues/537>; the documentation mentions GetLastError, and the scraper does not understand English and assumes GetLastError should be called.

**Comment by KalleOlaviNiemitalo** [comment]
Also HeapReAlloc and HeapSize.
