### ISSUE TITLE
CreateNamedPipeA flags

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#677]
This function has flags, similar to CreateFileA, that are routinely OR'd together however the flags and parameters are currently just integers making that impractical.

**Comment by kennykerr** [comment]
Also, the `dwOpenMode` parameter can accept a combination of file and pipe flags. For example:

```C++
PIPE_ACCESS_DUPLEX | FILE_FLAG_FIRST_PIPE_INSTANCE | FILE_FLAG_OVERLAPPED
```

Some of them are already included in the synthesized win32 metadata's `FILE_FLAGS_AND_ATTRIBUTES` enum while some are not. It may be sufficient to just add the missing constants to this enum and then update the function to use `FILE_FLAGS_AND_ATTRIBUTES`.

**Comment by kennykerr** [comment]
For other parameters to this function, like `dwPipeMode`, there already appear to be enums, like `NAMED_PIPE_INFO_FLAGS`, but the function's signature isn't using them.

**Comment by sotteson1** [comment]
Sorry @mikebattista, I started already working on this when you assigned it to yourself. I should have assigned it to me first.
