### ISSUE TITLE
`WAIT_TIMEOUT` missing from `WIN32_ERROR`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#678]

**Comment by mikebattista** [comment]
It's part of `WAIT_RETURN_CAUSE` right now which the Wait* functions return. Is this used elsewhere as well?

**Comment by kennykerr** [comment]
Yes, it is also used as a general purpose error code.

**Comment by KalleOlaviNiemitalo** [comment]
Where is it used as an error code? In <https://github.com/MicrosoftDocs/sdk-api/search?q=WAIT_FAILED>, all the matches are for return values of wait functions.

**Comment by kennykerr** [comment]
That query is for `WAIT_FAILED` not `WAIT_TIMEOUT`. 

`WAIT_TIMEOUT` is used quite frequently as a Win32 error code. I came across it porting some production code. For example, `GetQueuedCompletionStatus` may fail and `WAIT_TIMEOUT` is reported via `GetLastError`.

**Comment by kennykerr** [comment]
You could just have the same value in both `WAIT_RETURN_CAUSE` and `WIN32_ERROR`

**Comment by mikebattista** [comment]
> You could just have the same value in both `WAIT_RETURN_CAUSE` and `WIN32_ERROR`

Won't this cause problems for you? We've avoided duplicating names across constants and/or enum members for projections like yours.

Or are you suggesting adding ERROR_WAIT_TIMEOUT to WIN32_ERROR rather than just WAIT_TIMEOUT?

**Comment by kennykerr** [comment]
It would need a unique name, but the more I look at this I don't think `WAIT_RETURN_CAUSE` should return at all. Those functions return an open-ended list of values. They should just return `uint` as the original functions do and let the caller deal with the variations.

**Comment by mikebattista** [comment]
> Those functions return an open-ended list of values.

Is that true? The docs suggest they return a closed set, and if WAIT_FAILED, then call GetLastError.

**Comment by kennykerr** [comment]
Yes, that's true. Only the absolute simplest case is `WAIT_RETURN_CAUSE` sufficient. See for example:

https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects#return-value

**Comment by mikebattista** [comment]
Ah I see. I missed the ranges. So we can remove WAIT_RETURN_CAUSE and move WAIT_TIMEOUT and WAIT_FAILED to WIN32_ERROR.

**Comment by kennykerr** [comment]
Yep that would be great.
