### ISSUE TITLE
SetupDiEnumDeviceInfo uses `[Out]` for parameter which caller must initialize

### ISSUE THREAD

**Issue by skystedt** [microsoft/win32metadata#683]
## Actual behavior
Some functions requires the caller to set the cbSize property of an struct.
But the friendly overload has in some cases the struct with an `out` modifier making it impossible to set the cbSize property.

One example is SetupDiEnumDeviceInfo
https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdienumdeviceinfo

The friendly overload is generated as:
`internal static unsafe bool SetupDiEnumDeviceInfo(void* DeviceInfoSet, uint MemberIndex, out win32.Devices.DeviceAndDriverInstallation.SP_DEVINFO_DATA DeviceInfoData);`

The documentation for the `DeviceInfoData` parameter says:
_A pointer to an SP_DEVINFO_DATA structure to receive information about an enumerated device information element. The caller must set DeviceInfoData.cbSize to sizeof(SP_DEVINFO_DATA)_

Setupapi has many functions with this behavior, not sure if it exists in other places as well

## Expected behavior

Either DeviceInfoData should be `ref` instead of `out` and I can set the cbSize property.
Or DeviceInfoData can continue being `out` but then the friendly overload itself must set the property.

## Repro steps

1. `NativeMethods.txt` content:
```
SetupDiEnumDeviceInfo
```
### Context

- CsWin32 version: `0.1.588-beta`

**Comment by jnm2** [comment]
> but I don't know how to achieve that assuming the metadata isn't buggy in this way.

The suggestion is: if it is a `ref` parameter for a struct with a `cbSize`-ish field, the friendly overload would use `out` and do this to call the DllImport overload:

```cs
theOutStructParameter = new THE_STRUCT { cbSize = Marshal.SizeOf<THE_STRUCT>(); };
TheDllImportOverload(ref theOutStructParameter);
```

**Comment by AArnott** [comment]
Yes, I get the suggestion, but that would require that CsWin32 assume that there is no other reason for the parameter to be `ref`. If some APIs actually *do* require more initialization than just `cbSize` of the struct, we don't want the friendly overload to block that.
But if you want to continue that conversation, please file another issue on CsWin32 since this issue now tracks the defect in metadata.

**Comment by jnm2** [comment]
Sorry about that, I was adding one more thought by editing after I posted.

**Comment by skystedt** [comment]
I looked manually and found the following that seems to be wrong:
```
SetupDiCreateDeviceInfo
SetupDiCreateDeviceInterface
SetupDiEnumDeviceInfo
SetupDiEnumDeviceInterfaces
SetupDiEnumDriverInfo
SetupDiGetDeviceInfoListDetail
SetupDiGetDeviceInstallParams
SetupDiGetDeviceInterfaceAlias
SetupDiGetDeviceInterfaceDetail
SetupDiGetSelectedDevice
SetupDiGetSelectedDriver
SetupDiOpenDeviceInfo
SetupDiOpenDeviceInterface
SetupDiRegisterDeviceInfo
```

**Comment by mikebattista** [comment]
The problematic parameters here are marked with `_Out_` or `_Out_opt_` in the headers, so the metadata is reflecting that. Are the headers wrong?

**Comment by skystedt** [comment]
They all require the cbSize property to be set

**Comment by AArnott** [comment]
Yes, the headers are wrong, if by `_Out_` it means the caller is not expected to initialize these values at all.

**Comment by jnm2** [comment]
Another one that is getting an `out` parameter as of CsWin32 0.1.588-beta is https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo. It always fails if the caller doesn't initialize cbSize.

**Comment by mikebattista** [comment]
Thanks. It's another case of the SAL annotations in the headers being wrong. We can add [In] in the metadata for these.
