### ISSUE TITLE
winmdgenerator: x86, arm64 libs are not scanned correctly resulting in missing metadata

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#689]
MetadataTasks scans import lib dumpbin output for function names. It's currently pulling out `Symbol name`, which may be decorated, depending on target platform (e.g. _Function@0 on x86, Function on x64, etc.). This should instead read the undecorated `Name` field.

https://github.com/microsoft/win32metadata/blob/832ff5798733fc292c3bdbc73c8ae81e7a0cda4b/sources/GeneratorSdk/MetadataTasks/ScanLibs.cs#L35

**Comment by sotteson1** [comment]
Hmm, when scanning the cabinet.lib for x86 I don't see the clean name at all:

````
  Version      : 0
  Machine      : 14C (x86)
  TimeDateStamp: E4BF7135
  SizeOfData   : 0000002B
  DLL name     : Cabinet.dll
  Symbol name  : _SetDecompressorInformation@16
  Type         : code
  Name type    : ordinal
  Ordinal      : 41
````

Advapi32.lib does have the nice name:

````
  Version      : 0
  Machine      : 14C (x86)
  TimeDateStamp: C2B5DC16
  SizeOfData   : 00000027
  DLL name     : ADVAPI32.dll
  Symbol name  : _TraceQueryInformation@24
  Type         : code
  Name type    : undecorate
  Hint         : 810
  Name         : TraceQueryInformation
````

So if I see the name type is "undecorate" I could use the Name, but on the example from cabinet, Name isn't an option.

**Comment by riverar** [comment]
Ah, drat. `IMPORT_OBJECT_ORDINAL` is going to be tricker then. Thinking.

**Comment by riverar** [comment]
Perhaps a minimum viable _hack_ would be some extra processing of the symbol name, e.g.

```csharp
var arm64ec = "#apple";
var x86 = "_banana@4";
var x64 = "cookie";

// Anchor to start of string
// Deal with optional prefaces
// Capture everything afterwards, sans @
// Stop at the first @ encountered
var expr = new Regex("^[#_]{0,1}([\\S-[@]]+)@*?");

Debug.Assert(expr.Match(arm64ec).Groups[1].Value == "apple");
Debug.Assert(expr.Match(x86).Groups[1].Value == "banana");
Debug.Assert(expr.Match(x64).Groups[1].Value == "cookie");
```
