### ISSUE TITLE
Need a way to deal with IDC_ARROW and other INTRESOURCEs

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#69]
`IDC_ARROW` and other resource ids defined with `MAKEINTRESOURCE` are represented in the headers as `wchar_t*`, so they can be used with functions like [LoadCursor](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadcursorw).

```c++
LoadCursor(instance, IDC_ARROW);
```

In the metadata, these resource ids are being represented as ushort, which is fine, in a way, because in the headers they really are an integer value reinterpreted as an address. But this will put the burden on app developers to deal with the type casting.
```c++
Win32::LoadCursor(instance, reinterpret_cast<wchar_t const*>(IDC_ARROW)); // Yuck
```

I think pywin32 dealt with this by manually converting certain parameters of certain functions, but that seems overly labor intensive and unreliable, to figure out all the possible places where these resources might be used in place of a string. If we can do it, great, but I'm skeptical.

Perhaps a more tractable approach would be to mark these resource id constants as "special" in the metadata, either by giving them an attribute, or by wrapping them in a different type. Either way, this would allow projections to project functions like `LoadCursror` as-is and do the type conversion from integer to "fake string" in a manner that works best for the projection.

As we all know, C++'s type system is... a bit flexible. So I'm curious about thoughts on how this would best serve C# and Rust, @AArnott and @kennykerr?

**Comment by kennykerr** [comment]
If `LoadCursorA`'s `lpCursorName` parameter just had an attribute that told us that, in addition to the default `PSTR`, it can also accept a `ushort` (the type of `IDC_ARROW` and friends) then I could make it work seamlessly in Rust, not requiring the caller to add a scary cast.

**Comment by sotteson1** [comment]
This was fixed a while ago by having them be int constants that are PWSTR objects like this:

```C#
public const PWSTR IDC_ARROW = 32512;
```
