### ISSUE TITLE
Missing `usbdef.h` and `usbioctl.h`

### ISSUE THREAD

**Issue by dorssel** [microsoft/win32metadata#691]
`usbdef.h` and `usbioctl.h` contain structures and constants for user-mode querying of USB device details, e.g. `FILE_DEVICE_USB`, `IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX`, and `USB_NODE_CONNECTION_INFORMATION_EX`.

Note that some other USB specific headers *are* scraped/supported, such as `usbiodef.h`, which contains e.g. `GUID_DEVINTERFACE_USB_HUB` and works fine.

**Comment by sotteson1** [comment]
I tried adding usbioctl.h but it doesn't compile with our tools. I'll need to look into it more.

**Comment by dorssel** [comment]
Interestingly enough, since 0.1.691-beta the ioctls (such as `IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX`) are working, but the structures (such as `USB_NODE_CONNECTION_INFORMATION_EX`) are not. Even though these are both in `usbiodef.h`. Looks like scraping this header now at least partially works...
