### ISSUE TITLE
rtlMoveMemory is missing ?

### ISSUE THREAD

**Issue by sancarn** [microsoft/win32metadata#694]
Can't find Kernel32's CopyMemory in here.

**Comment by marler8997** [comment]
It looks like `CopyMemory` may not be an actual function exported by kernel32.dll.  According to the docs:

> Its implementation is provided inline. 

That being said, it does look like `RtlCopyMemory` does exist, i.e.

```batch
> dumpbin /exports "c:\windows\System32\kernel32.dll" | grep CopyMemory
       1241  4D8 0003B4F0 RtlCopyMemory
```

And I'm not seeing `RtlCopyMemory` in the metadata.

**Comment by sancarn** [comment]
That line in the docs, as far as I know, is specifying `RtlCopyMemory` is a C macro which results in calls to `Kernel32`'s `CopyMemory`. [The `CopyMemory` function is definitely exported from `Kernel32`](https://www.pinvoke.net/default.aspx/urlmon/CopyMemory.html), though i know it's existence in pInvoke doesn't guarantee anything.

**Comment by mikebattista** [comment]
These all look like inlines to me which we don't support in the metadata especially if they defer to CRT APIs.

```c
#define RtlEqualMemory(Destination,Source,Length) (!memcmp((Destination),(Source),(Length)))
#define RtlMoveMemory(Destination,Source,Length) memmove((Destination),(Source),(Length))
#define RtlCopyMemory(Destination,Source,Length) memcpy((Destination),(Source),(Length))
#define RtlFillMemory(Destination,Length,Fill) memset((Destination),(Fill),(Length))
#define RtlZeroMemory(Destination,Length) memset((Destination),0,(Length))
```
