### ISSUE TITLE
Namespace dependencies need some cleaning up

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#700]
https://gist.github.com/kennykerr/cd45cf6473498707a469abec8dd9e71e

This is from a Rust toml file showing feature dependencies. They basically map to metadata namespaces. You can see that the Win32 namespaces need some work. Note that this only shows certain dependencies (there are many others that are omitted for this list).

Reducing these dependencies would have a huge impact on build time for consuming projects.

**Comment by kennykerr** [comment]
The WinRT namespaces are relatively clean by comparison. To give you a sense for how impactful this is, here are two examples. The first example uses a simple WinRT API while the second a simple Win32 API. The WinRT API actually requires hundreds of lines of code as it involves activation factories, required interfaces, and much more. The Win32 API just requires a single function definition.

The WinRT project just creates a Windows.Foundation.Uri object. Here you can see it builds in under 5 seconds:

```
C:\git\windows-api-rs\examples\winrt_uri>cargo build
   Compiling const-sha1 v0.2.0
   Compiling windows v0.21.1
   Compiling windows-api v0.21.1 (C:\git\windows-api-rs)
   Compiling winrt_uri v0.0.0 (C:\git\windows-api-rs\examples\winrt_uri)
    Finished dev [unoptimized + debuginfo] target(s) in 4.39s
```

The Win32 project just call the `GetTickCount` function. Here you can see it takes two minutes to build:

```
C:\git\windows-api-rs\examples\win32_tick_count>cargo check
    Checking const-sha1 v0.2.0
    Checking windows v0.21.1
    Checking windows-api v0.21.1 (C:\git\windows-api-rs)
    Checking win32_tick_count v0.0.0 (C:\git\windows-api-rs\examples\win32_tick_count)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 59s
```

This is because the `GetTickCount` function resides in the `Windows.Win32.System.SystemInformation` namespace, which has direct and indirect dependencies on many many other large namespaces including Direct3D9, OpenGL, and much more. 

This is probably one of the more egregious examples, but many other namespaces have similarly unnecessary dependencies that impact build time.

**Comment by sotteson1** [comment]
When you pull in an API from a namespace, do you generate code for the the entire namespace and any dependencies? CsWin32 only pulls in the API and any types it depends on, but maybe you can't do that in Rust. I just built in an app using CsWin32 that calls GetTickCount and it built pretty much instantly.

**Comment by KalleOlaviNiemitalo** [comment]
> each namespace is gated (much like you would use #ifdef or #include in C++) so you only compile the namespaces you actually request in your build.

Can you gate things other than namespaces? If not, is this a limitation of Rust or just a matter of letting the developers understand which gate they need to open to get the function they want?

The Windows SDK documentation lists the header files needed for functions and types. I presume the dependencies between the header files have been reviewed. Perhaps you could gate by them.

API sets might have been another alternative but e.g. GetTickCount doesn't seem to be part of any API set.

**Comment by kennykerr** [comment]
> Can you gate things other than namespaces? 

Namespace are the natural boundary for something like this. Otherwise, I don't see much point in having these synthesized namespaces for Win32 at all.

> Windows.Win32.System.Com scrapes ole.h, which includes:

Shouldn't `ole.h` be included in the existing `Windows.Win32.System.OleAutomation` namespace instead? Or at least in its own namespace? I think having smaller, more targeted namespaces would help a lot.

**Comment by sotteson1** [comment]
If at all possible, we try to deal in units of headers, not structs. We can move individual structs from one namespace to another but it gets hard to manage. Sometimes we have no choice like with winuser.h which is piled with all kinds of crap that doesn't belong together.

Just looking at these three types, they all come from ocidl.h and are mostly used by things in ocidil.h and ole*.h. We could move ocidl.h out to another namespace like with the ole*.h headers. Most of the stuff in there looks specific to controls, but not all of it. Did I mention the Windows headers aren't layered very well? :)

**Comment by sotteson1** [comment]
Who is moving things around after we get the .winmd? Our win32 metadata project isn't doing that.

**Comment by kennykerr** [comment]
> Who is moving things around after we get the .winmd? Our win32 metadata project isn't doing that.

No, I mean the win32 metadata already makes decisions about how different APIs get mapped to different namespaces. Right now that's predominantly based on original header grouping but that need not be that way. The original headers are not preserved.

> It's beginning to sound like a Rust projection-specific problem you want me to solve.

No, both C++ and Rust behave the same way. Structs must be fully defined because their size must be known at compile time. Functions are typically different because parameters, of reference/pointer types, don't need to be known ahead of time. So that can be deferred. 

I'm not suggesting your move all or even any specific headers around at all. I'm just suggesting you consider where there are cross-namespace dependencies that are undesirable that we clean those up as they negatively affect build time for languages like C++ and Rust. 

It's your call - I'm just trying to give you as much information as I have.

**Comment by kennykerr** [comment]
I think I'll just close this issue and open new issues for any specific dependency issues I come across like #701.
