### ISSUE TITLE
[Feature Request] Attribute for ANSI/Unicode Suffix

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#711]
It would be incredibly helpful if there was a way to programmatically identify structs and functions that have a `A` / `W` suffix that denotes whether a Win32 API is ANSI / Unicode. 

I mask this from consumers of my projection (as indeed, C does through the use of `#define` macros), which means that I strip off the suffix. But there's no easy heuristic for me to differentiate between (say) `Windows.Win32.UI.Controls.TBBUTTONINFOA` (an ANSI struct) and `Windows.Win32.Devices.BiometricFramework.WINBIO_UNIT_SCHEMA` (a struct that is neither). 

I could create an elaborate exclusion list of false positives in my projection, but this really belongs in the source metadata, I think.

**Comment by mikebattista** [comment]
Ansi variants are now decorated with `[Ansi]` and Unicode variants are now decorated with `[Unicode]`.
