### ISSUE TITLE
DllImportAttribute dllName not explicitly specified for bthprops.cpl

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#714]
Consider the `BluetoothAuthenticateDevice` API. This function lives in `bthprops.cpl`. Without an explicit `.cpl` suffix, callers may fail attempting to append system native `.dll`, `.a`, etc. instead.

Propose that all imports that stray from the defaults be generated with explicit dllNames.

```
// win32metadata 12.0.2.30863

[DllImport("bthprops", ExactSpelling = true)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern uint BluetoothAuthenticateDevice([Optional][In] HWND hwndParent, [Optional][In] HANDLE hRadio, [In][Out] BLUETOOTH_DEVICE_INFO* pbtbi, [Optional][In][NativeArrayInfo(CountParamIndex = 4)] PWSTR pszPasskey, [In] uint ulPasskeyLength);
```

Related: microsoft/windows-rs#1255

**Comment by kennykerr** [comment]
This also makes the printer APIs impossible to use - we need the file extension.  

Here's another customer blocked by this issue: 
https://github.com/microsoft/windows-rs/issues/1447
