### ISSUE TITLE
Unscoped enum JsDebugReadMemoryFlags contains rude None member

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#717]
Looks like per #443, we can slap a `ScopedEnumAttribute` on this.

```csharp
// win32metadata 13.0.2.56897

public enum JsDebugReadMemoryFlags
{
  None,
  JsDebugAllowPartialRead
}
```

Related: microsoft/windows-rs#1263

**Comment by riverar** [comment]
@mikebattista Is this a general pattern I can follow and help via PRs? Or would you rather I just file issues?

**Comment by mikebattista** [comment]
Yes feel free to file PRs.
