### ISSUE TITLE
System.FlagsAttribute no longer appears on any enum types

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#72]
The old metadata used to put the flags attribute on enums like `DXGI_ADAPTER_FLAG`. Now the attribute no longer appears.

This attribute is used by projections to generate bitwise operators for these enums.

**Comment by sotteson1** [comment]
I added Flags to DXGI_ADAPTER_FLAG and a couple others. I have to add them manually, so if you see anymore missing Flags, let me know.
