### ISSUE TITLE
Incorrect DllImport attribute for Windows 11 API TryCreatePackageDependency

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#723]
`TryCreatePackageDependency` does not exist in `kernel32.dll` on Windows 11 22000.194 or vNext 22489.1000. Isn't clear if this is an OS bug (missing forwarder?), SDK bug, and/or a metadata bug. Warrants investigation across the board.

```csharp
// win32metadata 14.0.2.15146

[DllImport("KERNEL32", ExactSpelling = true)]
public unsafe static extern HRESULT TryCreatePackageDependency([In] PSID user, [In][Const] PWSTR packageFamilyName, [In] PACKAGE_VERSION minVersion, [In] PackageDependencyProcessorArchitectures packageDependencyProcessorArchitectures, [In] PackageDependencyLifetimeKind lifetimeKind, [In][Const] PWSTR lifetimeArtifact, [In] CreatePackageDependencyOptions options, [Optional][Out] PWSTR* packageDependencyId);
```

```
C:\> dumpbin /exports c:\windows\sysnative\kernel32.dll | findstr /i TryCreatePackage
[nothing returned]
```

cc: @sylveon

**Comment by sylveon** [comment]
I can't seem to find a `.lib` in the Windows SDK I can link to to get the function either.

**Comment by mikebattista** [comment]
@DrusTheAxe is this yours?

**Comment by DrusTheAxe** [comment]
> @DrusTheAxe is this yours?

No. win32metadata is the Flat-C projection. The API is misattributed. It's in api-ms-win-appmodel-runtime-l1-1-5 and also exposed by kernelbase.

Why is this saying kernel32? However this was generated is wrong.

BTW [Docs ](https://docs.microsoft.com/windows/win32/api/appmodel/nf-appmodel-trycreatepackagedependency)list headers but don't list libs or dlls anymore? :-(

**Comment by sylveon** [comment]
Yeah, the reason we found this is I was trying to figure out which lib to use, and which DLL to probe with `GetProcAddress`, because docs didn't mention it.

I wanted to run downlevel on 10, so linking was okay for quick testing but not for the final code. I couldn't find the DLL so I asked @riverar; he looked at win32metadata and got `kernel32.dll`, but that obviously didn't end up working.

Currently I'm probing `kernelbase.dll` with `GetProcAddress` to get the MSIX Dynamic Dependencies functions (this issue affects all 4, not just `TryCreatePackageDependency`), should I switch to probing `api-ms-win-appmodel-runtime-l1-1-5.dll`?

**Comment by DrusTheAxe** [comment]
Idle thought... The api-ms-win-appmodel-runtime-l1 APIset has some unusual lineage

* Created in Win8, hosted by kernel32. Exported N functions
* Moved between Win8 and Win81 to kernelbase. Exported N functions, with forwarder stubs in kernel32 to preserve compat
* Repeatedly extended over the years (1-1, 1-2, ...). Exported by kernelbase but no new forwarder stubs added to kernel32. Kernel32 only has forwarder stubs for the handful of APIs originally present in Win8, nothing more.

Could be tooling is misidentifying this legacy kernel32 **fractional** support of 1-0 and presuming it means all versions?

**Comment by DrusTheAxe** [comment]
>The API is misattributed. It's in api-ms-win-appmodel-runtime-l1-1-5 and also exposed by kernelbase.

P.S. This is confirmed by local hackery

```
[d:\Tools\LoadLibrary] loadlibrary.exe kernel32 CreateFileW
Current directory = d:\Tools\LoadLibrary
Loaded 'kernel32' = 00007FFA0C570000
Module loaded = C:\WINDOWS\System32\KERNEL32.DLL
Function CreateFileW = 00007FFA0C591E20

[d:\Tools\LoadLibrary] loadlibrary.exe kernel32 TryCreatePackageDependency
Current directory = d:\Tools\LoadLibrary
Loaded 'kernel32' = 00007FFA0C570000
Module loaded = C:\WINDOWS\System32\KERNEL32.DLL
Error 127 (0x7F) in GetProcAddress
The specified procedure could not be found.

[d:\Tools\LoadLibrary] loadlibrary.exe kernelbase TryCreatePackageDependency
Current directory = d:\Tools\LoadLibrary
Loaded 'kernelbase' = 00007FFA0A330000
Module loaded = C:\WINDOWS\System32\KERNELBASE.dll
Function TryCreatePackageDependency = 00007FFA0A44FA50

[d:\Tools\LoadLibrary] loadlibrary.exe api-ms-win-appmodel-runtime-l1-1-5.dll TryCreatePackageDependency
Current directory = d:\Tools\LoadLibrary
Loaded 'api-ms-win-appmodel-runtime-l1-1-5.dll' = 00007FFA09360000
Module loaded = C:\WINDOWS\SYSTEM32\kernel.appcore.dll
Function TryCreatePackageDependency = 00007FFA09364DB0
```

**Comment by mikebattista** [comment]
Thanks for the investigation. @sotteson1 could you take a look?

**Comment by sylveon** [comment]
Also, which .lib do I need to use if I want to use delay-loading instead of manual GetProcAddress calls?

**Comment by DrusTheAxe** [comment]
> Yeah, the reason we found this is I was trying to figure out which lib to use

`onecore.lib` ?

>and which DLL to probe with `GetProcAddress`, because docs didn't mention it.

Yes, apparently docs _used to_ list header, lib and dll but now just header. I don't know why or when that happened but I too am saddened by it.

> Currently I'm probing `kernelbase.dll` with `GetProcAddress` to get the MSIX Dynamic Dependencies functions (this issue affects all 4, not just `TryCreatePackageDependency`), should I switch to probing `api-ms-win-appmodel-runtime-l1-1-5.dll`?

No need to switch. You can probe for `*PackageDependency()` in `kernelbase.dll` or `api-ms-win-appmodel-runtime-l1-...`. Both work and produce the same result.

APIsets are implemented as a library that's 'hosted' by a dll (that api-..1-5.dll is known to the Loader but it's not a physical file). They were invented in Vista to give Windows a way to refactor APIs (things had gotten quite messy by that point in terms of implementation and layering e.g. advapi32.dll was 5+ very different APIs cohabitating in one kitchen sink DLL) but without breaking compat. If you call some function exported by, say, advapi32.dll it could be physically (hosted) in advapi32.dll, or in another DLL with a forwarder stub in advapi32.dll for existing binaries to still work. This gave (and continues to give) Windows the ability to relocate code if/when needed -- for efficiency, layering or other reasons -- without breaking existing software.

I'm not aware of any guidance on when to use kernelbase vs api-... And we no longer have implicit guidance (public documentation mentioning .lib and .dll). @jonwis do we have guidance on the subject?

**Comment by kennykerr** [comment]
I don't recommend apisets as they make it harder to build apps that run on older versions of Windows where they may not be available. If I remember correctly, the OS loader also no longer requires apiset DLLs and handles forwarding automatically.

**Comment by sylveon** [comment]
Neither kernelbase.lib or api-ms-win-appmodel-runtime-l1.lib are in the Windows SDK. I generally prefer avoiding linking to onecore.lib because it brings literally everything, so makes it too easy to introduce unwanted dependencies.

Tried looking at the exports of all .lib files in the Windows SDK and the only ones provinding TryCreatePackageDependency are `onecore.lib`, `OneCoreUAP.lib`, `OneCoreUAP_apiset.Lib`, `windowscoreheadless.Lib` and `windowscoreheadless_apiset.Lib`, all of which also export plenty of other stuff.

The app in question supports Windows 10 as minimum OS, so API sets themselves not being available is not a major issue.

**Comment by sylveon** [comment]
Linking onecore.lib allows it to build, but then fails to launch the exe (and I am on Windows 11, so the API is present and GetProcAddress does resolve it):
![image](https://user-images.githubusercontent.com/6440374/140418291-4239a61c-db69-428b-b460-085b68a0a902.png)

**Comment by sylveon** [comment]
OneCore.lib tries to find it in kernel32.dll:
![image](https://user-images.githubusercontent.com/6440374/140418746-a92c7b1b-0a45-4e0a-9570-9b0b4ede11e9.png)

**Comment by sotteson1** [comment]
This looks like a bug in the lib in the public SDK. But we could make the metadata do the right thing and use kernelbase instead of kernel32.

**Comment by sylveon** [comment]
Sounds good to me - where should I report the issue for the public SDK?

**Comment by DrusTheAxe** [comment]
> This looks like a bug in the lib in the public SDK. But we could make the metadata do the right thing and use kernelbase instead of kernel32.

+ @AdamBraden for visibility

**Comment by kennykerr** [comment]
The win32 metadata intentionally avoids apisets: https://github.com/microsoft/win32metadata/issues/92

But you're not even using the win32 metadata - you're using the Windows SDK libs directly - I don't know how much we can alter those, beyond fixing the umbrella lib bugs. You can always create your own libs with the MSVC `lib` tool.

**Comment by DrusTheAxe** [comment]
I've confirmed the kernel32 reference is a bug due to a subtle source definition error. We're tracking the fix @ https://task.ms/36936434. Fixing that should flow down to fix the SDK

Thanks for reporting the issue!

**Comment by riverar** [comment]
I don't want to tie correcting the metadata to the SDK, however. The SDK isn't as nimble as win32metadata so hoping for a multi-pronged approach here.

**Comment by DrusTheAxe** [comment]
> I don't want to tie correcting the metadata to the SDK, however. The SDK isn't as nimble as win32metadata so hoping for a multi-pronged approach here.

@sotteson1 has this come up yet - a bug in SDK? Do we have a standardized solution if we don't want to wait for a fixed SDK? Yet? 😉

**Comment by sotteson1** [comment]
> > I don't want to tie correcting the metadata to the SDK, however. The SDK isn't as nimble as win32metadata so hoping for a multi-pronged approach here.
> 
> @sotteson1 has this come up yet - a bug in SDK? Do we have a standardized solution if we don't want to wait for a fixed SDK? Yet? 😉

We hack around stuff in the SDK a lot so this is just another one. :) I don't think we've had a problem with an incorrect export from a lib, but we can fix it at the win32metadata level.
