### ISSUE TITLE
4 types in System.Iis look like a Com Class IDs but they aren't?

### ISSUE THREAD

**Issue by marler8997** [microsoft/win32metadata#737]
Not sure what's going on here.  In my projection, any struct that has a `Guid` attribute is interpreted as a "ComClassID".  Com Class IDs don't have fields, but 4 of the types in `System.Iis` have both the `Guid` attribute and fields:

```
CONFIGURATION_ENTRY
LOGGING_PARAMETERS
PRE_PROCESS_PARAMETERS
POST_PROCESS_PARAMETERS
```

Here's `CONFIGURATION_ENTRY` as an example:
```C#
[Guid(2651071087u, 58252, 16798, 164, 72, 98, 222, 59, 58, 143, 67)]
public struct CONFIGURATION_ENTRY
{
	public BSTR bstrKey;

	public BSTR bstrValue;
}
```

Maybe my assumption about structs with Guids is wrong, or maybe there's something afoul with `CONFIGURATION_ENTRY` (and friends)?  I couldn't really find what `CONFIGURATION_ENTRY` is used for and it's also not referenced by any function in the metadata, so it's a mystery.

**Comment by kennykerr** [comment]
I came across this a while back as well. 😉 

This is just a weird API that has nothing to do with COM. The way I handle this is to only treat it as a CLSID if the struct has zero fields.

**Comment by kennykerr** [comment]
But it would be simpler if the CLSIDs were just constants.

**Comment by sotteson1** [comment]
This guids are there in the original headers, so we scrape and emit them that way. I'm not sure why the authors put them in the .idl.
