### ISSUE TITLE
Missing Get/SetWindowLongPtr functions

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/win32metadata#74]
These have a funny definition that are #defined as Get/SetWindowLong for 32-bit apps.

Basically, somewhat like this:

```c++
WINUSERAPI
LONG
WINAPI
SetWindowLongW(
    _In_ HWND hWnd,
    _In_ int nIndex,
    _In_ LONG dwNewLong);

#ifdef _WIN64

WINUSERAPI
LONG_PTR
WINAPI
SetWindowLongPtrW(
    _In_ HWND hWnd,
    _In_ int nIndex,
    _In_ LONG_PTR dwNewLong);

#else 

#define SetWindowLongPtrW   SetWindowLongW

#endif /* _WIN64 */
```

This is a weird case, as I don't know if it's actually harmful to call the `SetWindowLongPtr` export on a 32-bit app. We should decide whether or not every projection needs to do this weird mapping, or if it's fine to project both.

**Comment by sotteson1** [comment]
This is fixed, although the work item to distinguish them as win64 only is pending with #384.
