### ISSUE TITLE
Some Win32 interfaces should be marked with an agile attribute

### ISSUE THREAD

**Issue by damyanp** [microsoft/win32metadata#740]
For example, the various DirectX interfaces (the "nano-COM" ones) should all be marked as agile. This would allow the rust projection to mark them as implementing the Send and Sync traits.

**Comment by sotteson1** [comment]
How can I tell which interfaces should be marked agile? Also, is there an attribute I can use to indicate it's agile, or would I need to make one?

**Comment by damyanp** [comment]
I think we'll need to mark them manually.  Maybe something like "everything in d3d12.h should be agile"?

**Comment by kennykerr** [comment]
Any progress on this? We have more customer interest to resolve this here: https://github.com/microsoft/windows-rs/issues/1519

**Comment by sotteson1** [comment]
> I think we'll need to mark them manually. Maybe something like "everything in d3d12.h should be agile"?

Are we safe making that assumption, that all interfaces in d3d12.h are agile? What about the other d3d headers? Can we make the same assumption for those?

**Comment by damyanp** [comment]
Any d3d* header is definitely agile - these are all [Nano-COM](https://en.wikipedia.org/wiki/Component_Object_Model#Nano-COM_(a.k.a_XPCOM)) interfaces.

**Comment by sotteson1** [comment]
This was accidentally closed. I still need to do this one.

**Comment by marler8997** [comment]
I'm having a hard time finding information on what this `Agile` attribute means exactly.  Is anyone able to help me understand?

**Comment by riverar** [comment]
@marler8997 In this case, it denotes the backing Direct3D 12 objects can be used from any apartment/thread. You're not limited to the apartment/thread that created the object. This information is used by projections, such as Rust, to light up async capabilities.

Does that help at all?

**Comment by marler8997** [comment]
Yeah thanks for the explanation.
