### ISSUE TITLE
`Shell_NotifyIcon()` function missing

### ISSUE THREAD

**Issue by timokroeger** [microsoft/win32metadata#743]
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyicona
Found one related commit: https://github.com/microsoft/win32metadata/commit/094216a1ddb0daac0b344bb4c3fde9f557e1da10

**Comment by sotteson1** [comment]
This function follows a common Windows pattern of having Shell_NotifyIcon map to Shell_NotifyIconA or Shell_NotifyIconW depending on whether the program is compiled for Unicode or not. There isn't a Shell_NotifyIcon API in Windows, only Shell_NotifyIconA and Shell_NotifyIconW, which both are in the metadata.

From the header:

````C
#ifdef UNICODE
#define Shell_NotifyIcon  Shell_NotifyIconW
#else
#define Shell_NotifyIcon  Shell_NotifyIconA
#endif // !UNICODE
````

**Comment by timokroeger** [comment]
`Shell_NotifyIconA` nor `Shell_NotifyIconW` seem to be available in the rust projection.
I yet have to understand where all the API information comes from, that is why I (prematurely) assumed its missing from here.

**Comment by sabbyX** [comment]
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/fn.Shell_NotifyIconW.html

They do seems to exist.

**Comment by timokroeger** [comment]
Great! I just didn't manage to find them using doc.rs search. Sorry for the noise, closing the issue.
