### ISSUE TITLE
Type mismatch between STGM constants, various storage object method parameters

### ISSUE THREAD

**Issue by yan0lovesha** [microsoft/win32metadata#754]
OpenPropertyStore [here](https://github.com/microsoft/windows-rs/blob/4e28fd1ad7f080cc15968288bb8fac1429f6292f/src/Windows/Win32/Devices/FunctionDiscovery/mod.rs) has a parameter stgmaccess which is u32. But the constant like STGM_READ and STGM_Write [here](https://github.com/microsoft/windows-rs/blob/4e28fd1ad7f080cc15968288bb8fac1429f6292f/src/Windows/Win32/System/Com/StructuredStorage/mod.rs) is defined as i32.

**Comment by riverar** [comment]
Thanks again @mikebattista!
