### ISSUE TITLE
`WTD_CACHE_ONLY_URL_RETRIEVAL` not available in the crate

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/win32metadata#756]
This is a public constant if I'm not mistaken: https://docs.microsoft.com/en-us/windows/win32/api/wintrust/ns-wintrust-wintrust_data

**Comment by riverar** [comment]
Appears all of these constants are missing

https://github.com/microsoft/win32metadata/blob/beb18b9d045371cb1374a721be5f9d50fcdd4f45/generation/WinSDK/RecompiledIdlHeaders/um/WinTrust.h#L137-L152

**Comment by mikebattista** [comment]
I think all those spaces between the # and the define are causing the constant scraper to skip over them.
