### ISSUE TITLE
Functions from the avrt.h header?

### ISSUE THREAD

**Issue by HEnquist** [microsoft/win32metadata#759]
I wanted to experiment with raising the priority of my audio threads, so I wanted to call the `AvSetMmThreadCharacteristicsA`. But that doesn't seem to exist in the windows crate. Am I missing something?

This is the function I wanted to try:
https://docs.microsoft.com/en-us/windows/win32/api/avrt/nf-avrt-avsetmmthreadcharacteristicsa

**Comment by mikebattista** [comment]
The header is currently assigned to the System.Threading namespace but its content is not being scraped.

**Comment by mikebattista** [comment]
https://task.ms/37680868
