### ISSUE TITLE
Question: license of generated metadata

### ISSUE THREAD

**Issue by lb90** [microsoft/win32metadata#761]
Hello,

I'd like to know more about what possibilities are there for licensing the generated content. As an example, say I want to export types and API declarations to Python source code: would it be possible for me to license that Python code under the MIT license?

Thank you

**Comment by mikebattista** [comment]
We'd love to see projections for more languages built on this metadata. Python is one that has been requested (https://github.com/microsoft/win32metadata/discussions/374). Is that what you mean by "exporting types and API declarations to Python source code"?

**Comment by lb90** [comment]
Hi Mike, yes, exactly that. I wonder though if the resulting Python code is redistributable and can be licensed e.g. under MIT, or if instead users have to download the Win32 metadata and run the projection process themselves.

**Comment by mikebattista** [comment]
> I wonder though if the resulting Python code is redistributable and can be licensed e.g. under MIT

Yes. I'd expect users to only really need to interface with the projection. The metadata is more an implementation detail for projections. This is the model our other community projections follow.

There's also a [JSON representation](https://github.com/marlersoft/win32json) of our metadata if that would be easier for you to consume than a winmd. @marler8997 built this and also the [Zig projection](https://github.com/marlersoft/zigwin32) under the MIT license.

If you stand up a repo for this, please share it so we can follow progress and others in the community who have expressed interest in a Python projection can contribute.
