### ISSUE TITLE
Missing VDS interfaces 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#763]
A customer reported that some of the VDS interface, like `IVdsService` and `IVdsServiceLoader`, are missing in the [windows](https://github.com/microsoft/windows-rs) crate for Rust. This is because those interfaces are missing from the win32 metadata. Their absence makes it impossible to use this API. Oddy, some parts of the VDS API is available in the `Windows.Win32.Storage.VirtualDiskService` API, but not the foundational interfaces mentioned in the docs.

https://docs.microsoft.com/en-us/windows/win32/vds/loading-vds

**Comment by mikebattista** [comment]
Looks like there are some redefinitions across vds.h and vdshwprov.h that are problematic, and vds.h was commented out.

https://github.com/microsoft/win32metadata/blob/6b2be35aca1c1b8945dcbfa6300734a94eb0bbeb/generation/WinSDK/Partitions/VirtualDiskService/main.cpp#L9

@sotteson1 how do we work around this?

If we prefer vds.h over vdshwprov.h, all the missing core interfaces are added but we lose the below.

Windows.Win32.Storage.VirtualDiskService.IVdsProviderPrivate not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsHwProviderPrivate not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsHwProviderPrivateMpio not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsAdmin not found in 2nd winmd

**Comment by stas-bb** [comment]
hi guys, thanks for the crate, it's looking promising! :)

I'm the original reporter. Like Kenny pointed out, while some VDS interfaces are there, the main ones to load the service are missing. So I've managed to hack together something for `IVdsServiceLoader` manually which looks like:

```
#[repr(transparent)]
#[derive(:: core :: cmp :: PartialEq, :: core :: cmp :: Eq, :: core :: clone :: Clone, :: core :: fmt :: Debug)]
pub struct IVdsServiceLoader(pub ::windows::core::IUnknown);
impl IVdsServiceLoader {
}
unsafe impl ::windows::core::Interface for IVdsServiceLoader {
    type Vtable = IVdsServiceLoader_abi;
    const IID: ::windows::core::GUID = ::windows::core::GUID::from_u128(0xe0393303_90d4_4a97_ab71_e9b671ee2729);
}
impl ::core::convert::From<IVdsServiceLoader> for ::windows::core::IUnknown {
    fn from(value: IVdsServiceLoader) -> Self {
        value.0
    }
}
impl ::core::convert::From<&IVdsServiceLoader> for ::windows::core::IUnknown {
    fn from(value: &IVdsServiceLoader) -> Self {
        value.0.clone()
    }
}
impl<'a> ::windows::core::IntoParam<'a, ::windows::core::IUnknown> for IVdsServiceLoader {
    fn into_param(self) -> ::windows::core::Param<'a, ::windows::core::IUnknown> {
        ::windows::core::Param::Owned(self.0)
    }
}
impl<'a> ::windows::core::IntoParam<'a, ::windows::core::IUnknown> for &'a IVdsServiceLoader {
    fn into_param(self) -> ::windows::core::Param<'a, ::windows::core::IUnknown> {
        ::windows::core::Param::Borrowed(&self.0)
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IVdsServiceLoader_abi(

    // HRESULT LoadService(
    // [in]  LPWSTR      pwszMachineName,
    // [out] IVdsService **ppService
    // );

);
```

Which allowed me to run `CoCreateInstance` successfully here:
```
    let hw_provider: IVdsServiceLoader = unsafe {
        CoCreateInstance(&CLSID_VdsLoader, None, CLSCTX_ALL)?
    };
```

And now I'm trying to define the `IVdsServiceLoader::LoadService` function which is slightly more challenging so any help would be appreciated :-D

**Comment by mikebattista** [comment]
If we only included vds.h and excluded vdshwprv.h, would that meet your needs? vdshwprv.h contains "-Private" interfaces so it's not clear if the contents of that header are actually needed.

Below is what we'd lose from the metadata by doing this, but we'd include everything from vds.h that's currently missing.

Windows.Win32.Storage.VirtualDiskService.IVdsProviderPrivate not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsHwProviderPrivate not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsHwProviderPrivateMpio not found in 2nd winmd
Windows.Win32.Storage.VirtualDiskService.IVdsAdmin not found in 2nd winmd
