### ISSUE TITLE
Proposal: Attribute noreturn functions

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#764]
I propose that win32metadata emit an attribute (e.g. `Windows.Win32.Interop.NoReturnAttribute`) attached to functions and methods that do not return to the caller (e.g. [FatalExit](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-fatalexit?WT.mc_id=WD-MVP-5002756)). This will allow languages, such as Rust ([`never, !`](https://doc.rust-lang.org/std/primitive.never.html)), to generate smarter bindings, enabling better optimization of noreturn code paths, detection of _dead_ code paths (that is, code that is mistakenly placed after the call of a noreturn function), and other benefits.

Some noreturn APIs are already annotated in the source material.

Continuing with the `FatalExit` example:
```cpp
WINBASEAPI __analysis_noreturn VOID WINAPI FatalExit(
    _In_ int ExitCode
);
```

Some other forms found in the source material to be aware of:
```
_Analysis_noreturn_
DECLSPEC_NORETURN
__declspec(noreturn)
```

A theoretical example of how this could look in metadata:
```csharp
[NoReturn]
[DllImport("KERNEL32", ExactSpelling = true)]
[SupportedOSPlatform("windows5.1.2600")]
public static extern void FatalExit([In] int ExitCode);
```

**Comment by AArnott** [comment]
Bonus points if the metadata can reuse the [`DoesNotReturnAttribute'](https://apisof.net/catalog/1151d14c-d6d8-d4ee-c582-416b041773c3).

**Comment by riverar** [comment]
@AArnott Good catch. I was looking for an existing attribute and missed this one. I would definitely prefer this over a new one.

**Comment by mikebattista** [comment]
Assigning to @sotteson1 to see about scraping this from the headers and emitting as DoesNotReturnAttribute.

**Comment by sotteson1** [comment]
I'm wondering why a function that returns void needs an attribute to indicate it doesn't return anything. Isn't that what returning void means?

**Comment by kennykerr** [comment]
It's not that it doesn't return anything - it's that it doesn't return at all. Functions like `abort`, `std::terminate`, etc. will all result in some kind of process termination and compilers appreciate knowing this. Here's the C++ version of this:

https://en.cppreference.com/w/cpp/language/attributes/noreturn

**Comment by sotteson1** [comment]
Oh, go it.

**Comment by mikebattista** [comment]
https://task.ms/37680894

**Comment by kennykerr** [comment]
`RaiseException` is still lacking the `DoesNotReturn` attribute.
