### ISSUE TITLE
Request for ARM (32-bit) support

### ISSUE THREAD

**Issue by bdbai** [microsoft/win32metadata#765]
Arch-specific metadata generation introduced in #435 allows language projections to expose different interfaces for different target architectures. However, due to the lack of 32-bit Arm definition in [`Windows.Win32.Interop.Architecture`](https://github.com/microsoft/win32metadata/blob/master/sources/Win32MetadataInterop/SupportedArchitectureAttribute.cs#L8-L15) enum, the generated metadata contains no information about ARM targets, making downstream consumers like windows-rs unable to build for `thumbv7a-uwp-windows-msvc` any more. Is it possible to support 32-bit ARM architecture, so that the generated metadata could be utilized to target all 4 architectures supported by MSVC?

**Comment by riverar** [comment]
Hmm. I don't believe MSVC is supporting ARM32 going forward. Nor is there a mainstream supported version of Windows for ARM32 targets. Is there a reason you need this?

**Comment by bdbai** [comment]
Hi @riverar! We are currently working on a UWP app that is supposed to support both Windows Desktop and Windows Phone. I understand that Windows 10 Mobile is not officially supported any more, but the packaging wizard in Visual Studio still encourages developers to target all 4 architectures for better compatibility.

**Comment by AArnott** [comment]
Thanks for sharing what led to this, @bdbai.
If VS is encouraging developers to target an OS that is no longer supported, I would disregard that guidance and use Report a Problem in VS to draw our attention to it so the guidance can be updated.

**Comment by bdbai** [comment]
@AArnott thanks for your response! However, our work mainly targets Windows 10 Mobile, that is why we did not report anything working like a charm as a problem but instead turned to seeking help from other blockers.

**Comment by AArnott** [comment]
I don't imagine the win32metadata team will add support for an OS that Microsoft has already ended support for. But I can't speak for them. @mikebattista will probably be the one to make that call.

**Comment by mikebattista** [comment]
> I don't imagine the win32metadata team will add support for an OS that Microsoft has already ended support for. But I can't speak for them. @mikebattista will probably be the one to make that call.

That's right. It's not a priority to add ARM32 support in the metadata. Closing out.
