### ISSUE TITLE
WinRT interop

### ISSUE THREAD

**Issue by Alex-Gamper** [microsoft/win32metadata#770]
The interfaces within namespace WinRT.Composition reference types outside of the current winmd/metadata, Is this correct ? 
As an example the ICompositionSurface interface referenced below is defined in namespace "Windows.UI.Composition" which is part of WinRT

```
using System;
using System.Runtime.InteropServices;
using Windows.UI.Composition;
using Windows.Win32.Foundation;
using Windows.Win32.Interop;
using Windows.Win32.System.Com;

namespace Windows.Win32.System.WinRT.Composition
{
	// Token: 0x020058D8 RID: 22744
	[Guid(623476060U, 15060, 19612, 181, 207, 227, 106, 56, 81, 35, 48)]
	public interface ICompositorInterop : IUnknown
	{
		// Token: 0x0600DB4A RID: 56138
		unsafe HRESULT CreateCompositionSurfaceForHandle([In] HANDLE swapChain, [ComOutPtr] [Out] ICompositionSurface* result);

		// Token: 0x0600DB4B RID: 56139
		unsafe HRESULT CreateCompositionSurfaceForSwapChain([In] IUnknown swapChain, [ComOutPtr] [Out] ICompositionSurface* result);

		// Token: 0x0600DB4C RID: 56140
		unsafe HRESULT CreateGraphicsDevice([In] IUnknown renderingDevice, [ComOutPtr] [Out] CompositionGraphicsDevice* result);
	}
}
```

Also WinRT interface IInspectable  is referenced by the following, does not seem correct that mshtml is dependant on WinRT
I can ignore any namespaces named Windows.Win32.System.WinRT when doing a binding generation, BUT that then
results in errors due to the below reference. Not really a clean solution ? Any advice would be appreciated

```
using System;
using System.Runtime.InteropServices;
using Windows.Win32.Foundation;
using Windows.Win32.Interop;
using Windows.Win32.System.Com;
using Windows.Win32.System.WinRT;

namespace Windows.Win32.Web.MsHtml
{
	// Token: 0x02002CE2 RID: 11490
	[Guid(421319488U, 53046, 17663, 189, 83, 209, 183, 1, 121, 157, 155)]
	public interface IPrintTaskRequestHandler : IUnknown
	{
		// Token: 0x060098F2 RID: 39154
		HRESULT HandlePrintTaskRequest([In] IInspectable pPrintTaskRequest);
	}
}
```

**Comment by kennykerr** [comment]
The Win32 metadata includes interop interfaces that cannot be expressed in WinRT metadata. These may refer to WinRT types that you can resolve using the [WinRT metadata found here](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts). 

`IPrintTaskRequestHandler` isn't part of MSHTML so that's probably a bug on the part of the Win32 metadata.
