### ISSUE TITLE
[Question] Type dependencies  / Forward type declarations

### ISSUE THREAD

**Issue by Alex-Gamper** [microsoft/win32metadata#771]
Is it intended that binding generators for a language (as an example RUST) handle implied forward declarations within a namespace ?

As an example the System.Com namespace defines the beloved COM VARIANT struct, which however references IDispatch !
IDispatch (unlike IUnknown) is actually FULLY defined AFTER the VARIANT struct in the C header files (a Fwd typdef does exist)
but this cant/isnt reflected in the Winmd metadata

I had a brief look at the RUST bindings, But I could not see that this namespace was actually included ? (Note: I am a novice wrt RUST)

So am I correct in assuming that binding authors must pick and chose the namespaces that they want to present, and these must
align with the destination language capabilities (or be augmented with additional code to handle fwd declarations, as an example)

**Comment by kennykerr** [comment]
The concept of a C++ forward declaration is not universal. Rust in particular does not support forward declarations. Instead, Rust uses [features](https://doc.rust-lang.org/cargo/reference/features.html) to limit how much code is compiled for a given build.

**Comment by Alex-Gamper** [comment]
Hi Kenny, Thanks

I guess that I will need to handle forward declarations (If I want to bring in COM), luckily the language I am working on supports it

**Comment by kennykerr** [comment]
Yes, that's what [cppwinrt](https://github.com/microsoft/cppwinrt) does today for C++. It basically forward declares everything from metadata in layered headers to avoid compiling too much unnecessarily.
