### ISSUE TITLE
avrt.h AvSetMmThreadCharacteristicsA() is not available

### ISSUE THREAD

**Issue by mitchhentges** [microsoft/win32metadata#773]
I'd like to use the [`AvSetMmThreadCharacteristicsA` function](https://docs.microsoft.com/en-us/windows/win32/api/avrt/nf-avrt-avsetmmthreadcharacteristicsa), but I can't seem to use it via `windows-rs`.
Interestingly, [`win32metadata` already seems to define `AvSetMmThreadCharacteristicsA`](https://github.com/microsoft/win32metadata/blob/b07213e28bcc48221c155024f9c5e0e1a92c6497/generation/WinSDK/RecompiledIdlHeaders/um/avrt.h#L58) and [associate `avrt.h` with `Windows.Win32.System.Threading`](https://github.com/microsoft/win32metadata/blob/d8cb2c84072a256918584c72b754501bf8b74d66/generation/WinSDK/Partitions/Threading/settings.rsp#L13).

However, [the `windows-rs` docs don't show that `AvSetMmThreadCharacteristicsA` is available](https://microsoft.github.io/windows-docs-rs/doc/windows/?search=AvSetMmThreadCharacteristicsA), and attempting to `build!` with `Windows::Win32::System::Threading` fails with the error "`Windows.Win32.System.Threading` not found in metadata" (I'm perhaps missing some necessary preparation, or are misusing `build!`? Unsure 😄):
```
fn main() {
    windows::core::build! {
        Windows::Win32::System::Threading,
    };
}
```

My use case is: I'd like to be able to set a high-performance audio thread's characteristics as "Pro Audio" so that its priority can be increased more than the regular limit (as allowed by the win32 API).

Thanks for the good work on this project :)

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/win32metadata/issues/759> too covers avrt.h.

**Comment by riverar** [comment]
Thanks @KalleOlaviNiemitalo, dang. I did a search too and somehow missed this!

**Comment by mikebattista** [comment]
#759 is the correct duplicate. @sotteson1 needs to take a look at why the contents of that header aren't being scraped even though as you noted the header is assigned to the Threading namespace.
