### ISSUE TITLE
ASSOCF enumeration type is not included in metadata

### ISSUE THREAD

**Issue by shibayan** [microsoft/win32metadata#775]
The ASSOCF enumeration type information is missing from the generated metadata. As a result, the definition of the AssocQueryString function is incomplete.

The ASSOCF enumeration type is defined in docs.microsoft.com as follows

- [ASSOCF enumeration - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/shell/assocf_str)

```cpp
typedef enum  {
    ASSOCF_NONE                  = 0x00000000,  
    ASSOCF_INIT_NOREMAPCLSID     = 0x00000001,  
    ASSOCF_INIT_BYEXENAME        = 0x00000002,  
    ASSOCF_OPEN_BYEXENAME        = 0x00000002,  
    ASSOCF_INIT_DEFAULTTOSTAR    = 0x00000004,  
    ASSOCF_INIT_DEFAULTTOFOLDER  = 0x00000008,  
    ASSOCF_NOUSERSETTINGS        = 0x00000010,  
    ASSOCF_NOTRUNCATE            = 0x00000020,  
    ASSOCF_VERIFY                = 0x00000040,  
    ASSOCF_REMAPRUNDLL           = 0x00000080,  
    ASSOCF_NOFIXUPS              = 0x00000100,  
    ASSOCF_IGNOREBASECLASS       = 0x00000200,  
    ASSOCF_INIT_IGNOREUNKNOWN    = 0x00000400,  
    ASSOCF_INIT_FIXED_PROGID     = 0x00000800,  
    ASSOCF_IS_PROTOCOL           = 0x00001000,  
    ASSOCF_INIT_FOR_FILE         = 0x00002000
} ASSOCF;
```

The reason seems to be that ASSOCF is not defined as an enumerated type in the header file used to generate the metadata.

https://github.com/microsoft/win32metadata/blob/b07213e28bcc48221c155024f9c5e0e1a92c6497/generation/WinSDK/RecompiledIdlHeaders/um/Shlwapi.h#L1681

When using CsWin32 to generate the code for the AssocQueryString function, it is treated as a uint as shown below, and there is no way to generate the ASSOCF definition.

```csharp
[SupportedOSPlatform("windows5.0")]
public static unsafe winmdroot.Foundation.HRESULT AssocQueryString(uint flags, winmdroot.UI.Shell.ASSOCSTR str, string pszAssoc, string pszExtra, winmdroot.Foundation.PWSTR pszOut, ref uint pcchOut)
{
	fixed (uint* pcchOutLocal = &pcchOut)
	{
		fixed (char* pszExtraLocal = pszExtra)
		{
			fixed (char* pszAssocLocal = pszAssoc)
			{
				winmdroot.Foundation.HRESULT __result = PInvoke.AssocQueryString(flags, str, pszAssocLocal, pszExtraLocal, pszOut, pcchOutLocal);
				return __result;
			}
		}
	}
}
```

**Comment by mikebattista** [comment]
Due to the way this enum is defined in the header, we cannot use enums.json to group these into an enum.

We need to exclude the constants from being emitted in scraper.settings.rsp and then define the enum manually under the manual folder.
