### ISSUE TITLE
Missing structure `MEM_ADDRESS_REQUIREMENTS`

### ISSUE THREAD

**Issue by Zymlex** [microsoft/win32metadata#776]
Missing structure `MEM_ADDRESS_REQUIREMENTS` or `_MEM_ADDRESS_REQUIREMENTS`:
https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-mem_address_requirements

**Comment by mikebattista** [comment]
It's in SystemServices right now but should be moved to System.Memory.
