### ISSUE TITLE
Const by-reference

### ISSUE THREAD

**Issue by taufikrh** [microsoft/win32metadata#778]
I try to make projection for pascal, specially on free pascal.
Is any information how to make interface IUnknown QueryInterface parameter riid as TGuid not pointer to Guid (PGuid), because is appear in many places.
In pascal the syntax is look like :
function QueryInterface(const riid: TGuid; out ppvObject): HRESULT;

If i make translation from win32metadata is become :
function QueryInterface(const riid: PGuid; out ppvObject): HRESULT;

In C++ also appear as const byref.

Please make additional attribute ConstByRef or if is posible make the ParamSignature as ByRef (0x10), not ValueType (0x11)

**Comment by mikebattista** [comment]
@sotteson1 / @kennykerr / @AArnott could you provide some guidance on this one?

**Comment by AArnott** [comment]
The metadata defines it like this:

```cs
unsafe HRESULT QueryInterface([In][Const] Guid* riid, [Out][ComOutPtr] void** ppvObject);
```

So you see the `riid` parameter is already called out as `const` and `in` only. byref still means using a pointer, under the covers, so the metadata reflects that by typing as a pointer. But in other projections (like C#) this means we can expose without a pointer knowing that the impl should not change the value. In C# we can do this in the projection using the `in Guid riid` syntax, which effectively uses a pointer but without pointer syntax.

**Comment by taufikrh** [comment]
@AArnott thanks.

Yes, byref is still using a pointer, better is let the projections decide how expose the metadata.
allow cppwin32 using const byref and traditional __uuidof,
allow pascal using intrinsik guid ref,
allow c# using ref. and maybe useful for other language.

here another example on pascal (if the 3rd parameter is const Guid ref).
`D3D12CreateDevice(someAdapter, someFeatureLevel, ID3D12Device, outputDevice);`
If 3rd parameter is const Guid*, we cant pass ID3D12Device

**Comment by kennykerr** [comment]
Andrew is correct - different languages can map this however they wish.

**Comment by AArnott** [comment]
@taufikrh, I'm trying to decide whether your last comment agrees with me or is restating that you're asking for a change to the metadata. I believe the metadata is correct and carries enough semantic information that your projection should be able to emit the ideal code for your language, within the limits of being compatible with the underlying Win32 APIs, which we cannot change. If you agree, can you close this issue?

**Comment by taufikrh** [comment]
@kennykerr yes, this behavior is supported on `C++`, `Pascal` and maybe next other languages.
@AArnott yes Iam agree with you about `ByRef` is still using pointer.
Both `ByRef` and `TypedByRef followed with one number of pointer` is passing a address.
So, changging `TypedByRef followed with one number of pointer` to `ByRef` is not break how we expose Win32 Api metadata.
According `ECMA-335` specification :
section `I.12.4.1.5 Parameter passing`, its support reference parameter.
section `II.23.2.10 Param`, the diagram show about `ByRef followed with/o Type` and `TypedByRef` parameter.
![II 23 2 10 Param](https://user-images.githubusercontent.com/40443879/151504622-e0cebc61-6efc-4182-8f24-44c00a19ccc8.png)

If you don't mind, please change the metadata to support `ByRef` parameter
