### ISSUE TITLE
DEVPKEY_Device_InstanceId has the wrong type

### ISSUE THREAD

**Issue by marc-groundctl** [microsoft/win32metadata#782]
## Actual behavior

Calling `CM_Get_Device_Interface_Property` with `DEVPKEY_Device_InstanceId` fails to compile with `error CS1503: Argument 2: cannot convert from 'Windows.Win32.UI.Shell.PropertiesSystem.PROPERTYKEY' to 'in Windows.Win32.Devices.Properties.DEVPROPKEY'`

## Expected behavior

`CM_Get_Device_Interface_Property` can be called with `DEVPKEY_Device_InstanceId`

## Repro steps

1. `NativeMethods.txt` content:
```
DEVPKEY_Device_InstanceId
CM_Get_Device_Interface_Property
```

2. `NativeMethods.json` content (if present):
N/A

3. Any of your own code that should be shared?
```csharp
uint buf_size = 0;
PInvoke.CM_Get_Device_Interface_Property("", PInvoke.DEVPKEY_Device_InstanceId, out uint type, null, ref buf_size, 0);
```

### Context

- CsWin32 version: `0.1.619-beta`
- Win32Metadata version: `15.0.2-preview` (automatically set)
- Target Framework: `net5.0-windows10.0.19041.0`
- LangVersion: 9 (not overridden)

**Comment by KalleOlaviNiemitalo** [comment]
\<devpkey.h\> uses DEFINE_DEVPROPKEY to define DEVPKEY_Device_InstanceId.

**Comment by dorssel** [comment]
I ran into the same problem and solved it like this: https://github.com/dorssel/usbipd-win/blob/9218cbd881755f23c3e2b1172111ff861c17a313/UsbIpServer/ConfigurationManager.cs#L19-L31
