### ISSUE TITLE
Some COM interfaces are not faithfully preserved

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#784]
Examples like `IBidiRequest` lands up represented as a C style handle (`IBidiRequest`) and struct (`IBidiRequestVtbl`) rather than an interface as most interfaces like `IClassFactory` are.

**Comment by kennykerr** [comment]
Ah, @riverar pointed out that this has been fixed in the latest build. Now I just need a new build that includes #783 😉

**Comment by sotteson1** [comment]
Looks like our last couple builds failed because we need to use a different service connection name for signing. A new build is spinning, and I'll publish it once it's done.
