### ISSUE TITLE
IsWindows10OrGreater and IsWindowsServer functions missing

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#790]
See attached documentation: 

https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindowsserver
https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows10orgreater

**Comment by sotteson1** [comment]
Unfortunately, these are all inlined functions that we can't express in metadata.

**Comment by timsneath** [comment]
Boo :( that sucks. But it would be great if they could be catalogued anyway, so that language projections can create their own inlined functions? I don't know how many similar functions I'm blind to...
