### ISSUE TITLE
Windows SDK 22000+ missing __analysis_noreturn SAL

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#791]
I suspect this is what led to a few APIs [slipping under the radar](https://github.com/microsoft/win32metadata/issues/764#issuecomment-1026141641) when implementing noreturn support in metadata.

19042 winnt.h
```cpp
NTSYSAPI
__analysis_noreturn
VOID
NTAPI
RtlRaiseException(
    _In_ PEXCEPTION_RECORD ExceptionRecord
    );
```

22000.0 and 22000.120 winnt.h
```cpp
NTSYSAPI
VOID
NTAPI
RtlRaiseException(
    _In_ PEXCEPTION_RECORD ExceptionRecord
    );
```

@mikebattista Can we get an internal bug tracking this? Feel free to do what you wish with this issue afterwards. Thanks in advance!

**Comment by sotteson1** [comment]
I looked up the change, and it was changed on purpose. The change said:

  [EH] RaiseException can return but is decorated with __analysis_noreturn
  
  The commit said:
  Yes, it is perfectly legitimate for (Rtl)RaiseException to return.

So I guess it's possible for this function to return, although I don't know the specifics. I wonder if we should remove the attribute from the metadata to be consistent.

**Comment by kennykerr** [comment]
That's surprising. Adding @lzybkr who was also [expecting it not to return](https://github.com/microsoft/windows-rs/issues/1382). And @JamesMcNellis who knows all things about exceptions.

**Comment by KalleOlaviNiemitalo** [comment]
I suppose RaiseException will return normally if an exception filter returns EXCEPTION_CONTINUE_EXECUTION and dwExceptionFlags does not include EXCEPTION_NONCONTINUABLE.

**Comment by lzybkr** [comment]
Under normal conditions, `RtlRaiseException` finishes by setting the thread (register) context - not by returning. If something goes wrong in setting the context, `RtlRaiseException` raises a different non-continuable exception, so - in theory it shouldn't reach the return instruction, but maybe it's not impossible?

That said, @KalleOlaviNiemitalo points out a scenario where that may look like an ordinary return. To make this concrete - this following example prints `Hello world`.

```c++
#include <windows.h>
#include <stdio.h>

int main() {
    __try {
        RaiseException(0x12345678, 0, 0, 0);
        printf("Hello ");
    } __except(EXCEPTION_CONTINUE_EXECUTION) {
    }

    printf("world\n");
}
```

Based on this example, I'd agree that the prototype should not include `noreturn`, even knowing that `RtlRaiseException` is not actually returning.
