### ISSUE TITLE
Confusing WM_* constants in Win32.UI.Controls.RichEdit

### ISSUE THREAD

**Issue by JonnyDaft** [microsoft/win32metadata#795]
Would **WM_NOTIFY** be better as a "**Win32_UI_WindowsAndMessaging**" feature?
Just a thought ...
Have a great day :)

**Comment by riverar** [comment]
We should move all WM_* constants in the `Win32.UI.Controls.RichEdit` namespace to `Win32.UI.WindowsAndMessaging`, i.e.

```
WM_CONTEXTMENU
WM_NOTIFY
WM_PRINTCLIENT
WM_UNICHAR
```

**Comment by riverar** [comment]
@mikebattista Happy to make this change if you think it makes sense. These are generic window messages used throughout the system.

**Comment by mikebattista** [comment]
Yes you can move these. Assigning to you.
