### ISSUE TITLE
Feature request: Expose `Zw...` and `Nt...` APIs

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/win32metadata#802]
Those APIs are currently not exposed and would be a nice addition to the metadata.

Ref: https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/using-nt-and-zw-versions-of-the-native-system-services-routines

**Comment by mikebattista** [comment]
If any of these are defined in the SDK headers, they'll be included. Otherwise, this is a duplicate of #401 which covers producing metadata for other kits like the WDK to support kernel-mode and other scenarios.
