### ISSUE TITLE
`RAWINPUTDEVICE_FLAGS` not longer implements bitwise ops

### ISSUE THREAD

**Issue by Muon** [microsoft/win32metadata#804]
### Which crate is this about?

windows

### Crate version

0.32.0

### Summary

Trying to take an OR of members of `RAWINPUTDEVICE_FLAGS`, e.g. `RIDEV_DEVNOTIFY | RIDEV_INPUTSINK` stopped compiling, at least since 0.32.0, maybe earlier. Seems the implementation of BitOr got removed?

### Expected behavior

Compiles.

### Actual behavior

```
error[E0369]: no implementation for `RAWINPUTDEVICE_FLAGS | RAWINPUTDEVICE_FLAGS`
```

**Comment by mikebattista** [comment]
Sounds like we just need to add [Flags] to this enum.
