### ISSUE TITLE
SAL annotations are incorrectly being interpreted as `Optional`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#805]
The SAL annotation for `IWeakReferenceSource.GetWeakReference` indicates that its parameter is `__RPC__deref_out_opt`, which indicates that the caller must provide a valid pointer - it is not optional - but that it may return a null pointer back to the caller. The two canonical implementations (WRL and C++/WinRT) both treat it as required and will AV if a valid pointer is not provided. 

The metadata should remove the `[Optional]` attribute to correctly describe APIs with this annotation.

**Comment by kennykerr** [comment]
This seems to be a much larger problem of misapplying `[Optional]` to certain SAL annotations. For example, `IMLOperatorKernelContext.GetInputTensor` is said to have an optional out parameter but that's not what the `_COM_Outptr_result_maybenull_` annotation means. That [annotation means](https://docs.microsoft.com/en-us/cpp/code-quality/annotating-function-parameters-and-return-values?view=msvc-170) that the parameter is required but that null may be returned to the caller.

**Comment by riverar** [comment]
Think #803 is also related, and overall related to SAL annotation parser needing some tweaks.

https://github.com/microsoft/win32metadata/blob/e20e41468fcf7cc247c1c9ab7f6ad5de83b5d182/sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs#L779-L807
