### ISSUE TITLE
RmRegisterResources should indicate its arrays of strings are readonly

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#807]
The `RmRegisterResources` method [is documented](https://docs.microsoft.com/en-us/windows/win32/api/restartmanager/nf-restartmanager-rmregisterresources) as accepting `[in, optional] LPCWSTR []` for two parameters, but the parameter types in the metadata give no indication that the strings are constants as the docs/header file do. 

This results in a much poorer interop experience in C# because we cannot simply take a `string[]` from the user. Can the metadata be fixed for this and any other similarly impacted APIs?

_Originally posted by @jnm2 in https://github.com/microsoft/CsWin32/issues/506#issuecomment-1040769402_

**Comment by mikebattista** [comment]
@sotteson1 when LPCWSTR[] is converted to PWSTR*, are we losing the "constantness"? Can we update the scraper to address this in all cases?

**Comment by kennykerr** [comment]
There are plenty of such examples. What I've been doing is looking at the parameter direction in/out and infer that the resulting array is also in/out.

**Comment by mikebattista** [comment]
The current definition is:

`public unsafe static extern uint RmRegisterResources([In] uint dwSessionHandle, [In] uint nFiles, [Optional][In][NativeArrayInfo(CountParamIndex = 1)] PWSTR* rgsFileNames, [In] uint nApplications, [Optional][In][NativeArrayInfo(CountParamIndex = 3)] RM_UNIQUE_PROCESS* rgApplications, [In] uint nServices, [Optional][In][NativeArrayInfo(CountParamIndex = 5)] PWSTR* rgsServiceNames);`

So you think there's enough metadata here and projections should handle the rest?

**Comment by kennykerr** [comment]
Yes. There are hundreds of such examples and unless we're going to uniformly improve the metadata across all those APIs, I think that projections should just assume the direction of arrays as I've said and exceptions to the rule can be attributed as needed.

**Comment by AArnott** [comment]
Ah yes, I may have just overlooked the directional attributes/modifiers. CsWin32 can base on that too.
