### ISSUE TITLE
Support Embarcadero Delphi

### ISSUE THREAD

**Issue by MHumm** [microsoft/win32metadata#808]
This blog post says, that we can request to support other languages based on demand:
https://blogs.windows.com/windowsdeveloper/2021/01/21/making-win32-apis-more-accessible-to-more-languages/

So I'd demand support for Embarcadero Delphi, a popular solution for developing Windows applications.

**Comment by mikebattista** [comment]
Thanks for starting the discussion.

https://github.com/microsoft/win32metadata/issues/183 captures the guidance for new language projection requests.

Closing out and linking with #183 to track the request.
