### ISSUE TITLE
Commctrl.h notification message constants are missing

### ISSUE THREAD

**Issue by tim-weis** [microsoft/win32metadata#810]
While notification message constants for standard controls (such as the edit control) are included in the generated metadata this isn't the case for notification message constants of the common controls library (defined in *Commctrl.h*). The following notification message constants are missing:

* [ComboBoxEx](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-comboboxex-control-reference-notifications)
* [Date and Time Picker](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-date-and-time-picker-control-reference-notifications)
* [Header Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-header-control-reference-notifications)
* [IP Address](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-ip-address-control-reference-notifications)
* [List View](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-list-view-control-reference-notifications)
* [Month Calendar](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-month-calendar-control-reference-notifications)
* [Pager Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-pager-control-reference-notifications)
* [Property Sheet](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-property-sheets-reference-notifications)
* [Rebar Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-rebar-control-reference-notifications)
* [Status Bar](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-status-bars-reference-notifications)
* [SysLink Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-syslink-control-reference-notifications)
* [Tab Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-tab-control-reference-notifications)
* [Toolbar Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-toolbar-control-reference-notifications)
* [Tooltip Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-tooltip-control-reference-notifications)
* [Trackbar Control](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-trackbar-control-reference-notifications)
* [Tree View](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-tree-view-control-reference-notifications)
* [Up-Down](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-up-down-control-reference-notifications)

Could you have a look into what's needed to get those included in the metadata?

**Comment by mikebattista** [comment]
These all use math operations that refer to other macros, which the constant scraper doesn't recognize. Probably easiest to manually define these.

**Comment by tim-weis** [comment]
Easiest, maybe, but certainly not sustainable. A cursory look through the SDK headers evidenced that those constants have changed over time, even as recent as `NTDDI_WIN10_RS5` (I haven't looked into the Windows 11 SDK).

I would feel extremely uneasy about giving up the single-source-of-truth principle, just because it's easier.

**Comment by mikebattista** [comment]
We already have manual definitions where it makes sense so we wouldn't be breaking ground here.

When you say the constants have changed, I'm assuming you mean new constants were added. Otherwise, we're talking about breaking changes to APIs which usually doesn't happen especially for older API surfaces that are stable.

**Comment by mikebattista** [comment]
Are these constants supposed to be `uint` or `int`?

```
#define CBEN_FIRST              (0U-800U)       // combo box ex
#define CBEN_INSERTITEM          (CBEN_FIRST - 1)
```

Is `CBEN_FIRST` here `-800` or is it some unchecked overflowed `uint`? Same question for `CBEN_INSERTITEM`.

**Comment by tim-weis** [comment]
@mikebattista Both expressions are of type `unsigned int`.

`CBEN_FIRST` evaluates to `0xFFFFFCE0`, following the rules of unsigned overflow in C (which is well defined, as opposed to, say, signed integer overflow).

The expression `CBEN_FIRST - 1` has operands of type `unsigned int` and `signed int`, respectively. They are of different signedness but same rank, so the second operand gets converted to `unsigned int`, before the arithmetic operation is performed, yielding a value of `0xFFFFFCDF` with type `unsigned int` (refer to [implicit conversions](https://en.cppreference.com/w/c/language/conversion)).
