### ISSUE TITLE
`IWMDRMMessageParser.ParseLicenseRequestMsg` has odd `NativeArrayInfo` info

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#813]
This method appears to have an invalid NativeArrayInfo attribute. 

```C#
unsafe HRESULT ParseLicenseRequestMsg([In][NativeArrayInfo(CountParamIndex = 0)] byte* pbLicenseRequestMsg, [In] uint cbLicenseRequestMsg, [Out] INSSBuffer* ppDeviceCert, [Out] DRM_VAL16* pDeviceSerialNumber, [Out] BSTR* pbstrAction);
```

The first parameter refers to an index parameter at the same offset as itself. That seems wrong. Looks like it should be referring to the second parameter, but the SAL annotation is wrong.

**Comment by riverar** [comment]
@mikebattista Can we create a SDK bug too?

wmsdkidl.h
```diff
virtual HRESULT STDMETHODCALLTYPE ParseLicenseRequestMsg( 
-   /* [annotation][size_is][in] */ 
    _In_reads_(pbLicenseRequestMsg)  BYTE *pbLicenseRequestMsg,
    /* [annotation][in] */ 
    _In_  DWORD cbLicenseRequestMsg,
    /* [annotation][out] */ 
    _Out_  INSSBuffer **ppDeviceCert,
    /* [annotation][out] */ 
    _Out_  DRM_VAL16 *pDeviceSerialNumber,
    /* [annotation][out] */ 
    _Out_  BSTR *pbstrAction) = 0;
...
```

@sotteson1 How do you want to handle this? `--memberRemap`ing doesn't seem to support _replacing_ scraped/generated NativeArrayInfo attributes. (It throws with `'Duplicate 'NativeArrayInfo' attribute [...]`.) Should we perhaps change this behavior to first attribute instance wins (which effectively means emitter.rsp overrides)? Or introduce a new replacement flag? Or other?

**Comment by mikebattista** [comment]
Removing scraped attributes is now possible with Steve's latest fixes if we just want to remove the NativeArrayInfo attribute. There's an example of doing that at https://github.com/microsoft/win32metadata/blob/ffce351c40250e38069c6381a1ac6d4260ae2c24/generation/WinSDK/emitter.settings.rsp#L859.

**Comment by sotteson1** [comment]
I'll make it so the NativeArrayInfo in the .rsp wins out.
