### ISSUE TITLE
`INetCfgComponentUpperEdge.AddInterfacesToAdapter` has unusable metadata

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#814]
Another `NativeArrayInfo` example where the metadata makes no sense. The first parameter is supposedly an array, but it lacks a level of indirection. If it were an array of COM interface pointers it would need to be a pointer to a COM interface pointer. Looking at the docs, the method the parameters are "Reserved for system implementation" and the API itself is deprecated. 

I suggest we just remove the interface from metadata.

**Comment by mikebattista** [comment]
> I suggest we just remove the interface from metadata.

Ok.
