### ISSUE TITLE
`GetSecurityInfo` has `PSECURITY_DESCRIPTOR` projected as `**SECURITY_DESCRIPTOR`- Inaccurate?

### ISSUE THREAD

**Issue by tigercat2000** [microsoft/win32metadata#821]
This issue is very similar to #293

`PSECURITY_DESCRIPTOR` is currently projected as `**SECURITY_DESCRIPTOR` in `GetSecurityInfo`, but I believe this isn't a correct mapping.

The reason I think this is from the following test case using windows-rs, derived from here.
This test case shows `GetSecurityInfo` return a "security descriptor" that doesn't appear to make sense.
Passing a file with a request for `OWNER_SECURITY_INFORMATION` outputs a `ppsecuritydescriptor` with a blank `Owner` field, which is definitely not valid, but it gives the `ppsidowner` argument a `PSID` wrapping a pointer that definitely points to the `0x16` field of whatever struct is actually in `ppsecuritydescriptor`, and that *is* valid.
https://gist.github.com/tigercat2000/17be760d86010d2b2a6e9ef58674818a

Unlike in #293, [`GetSecurityInfo`](https://docs.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-getsecurityinfo) does not specifically say that `PSECURITY_DESCRIPTOR` may be one of x types- the only real hints are [A blog post talking about how weird it is](https://devblogs.microsoft.com/oldnewthing/20151223-00/?p=92701) and [`SECURITY_DESCRIPTOR`](https://docs.microsoft.com/en-us/windows/win32/api/Winnt/ns-winnt-security_descriptor) stating
> Because the internal format of a security descriptor can vary, we recommend that applications not modify the SECURITY_DESCRIPTOR structure directly. For creating and manipulating a security descriptor, use the functions listed in See Also.

From all this, it seems unclear what a `PSECURITY_DESCRIPTOR` actually represents in the context of `GetSecurityInfo`.
Any ideas?

**Comment by riverar** [comment]
> `PSECURITY_DESCRIPTOR` is currently projected as `**SECURITY_DESCRIPTOR` in `GetSecurityInfo`, but I believe this isn't a correct mapping.

Agreed. Will get this fixed up.

> From all this, it seems unclear what a PSECURITY_DESCRIPTOR actually represents in the context of GetSecurityInfo. Any ideas?

It's an opaque handle, don't look behind the curtain! (Peeking behind the curtain, it does seem to align with what Raymond said -- a blob that could be relative or absolute or some mishmash of the two.)
