### ISSUE TITLE
`IActivationFactory.ActivateInstance`'s parameter is not optional

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#833]
This is another example of incorrect SAL interpretation by the win32 metadata. 

For example, the IDL definition for this method looks as follows:

```C++
HRESULT ActivateInstance([out] IInspectable** instance);
```

And the MIDL-generated C++ definition looks as follows:

```C++
virtual HRESULT STDMETHODCALLTYPE ActivateInstance( 
    /* [out] */ __RPC__deref_out_opt IInspectable **instance) = 0;
```

Although the SQL annotation includes `opt` that just means that RPC may not return a value (upon failure), not that the parameter itself is optional. 

SAL-related issues include: #803, #805, #820

**Comment by sotteson1** [comment]
I found this comment in rpcsal.h to be very helpful:

```C++
// 5. The placement of _opt when using _deref is important:
//      __RPC__deref_opt_...      : Input may be NULL
//      __RPC__deref_..._opt      : Output may be NULL
//      __RPC__deref_opt_..._opt  : Both input and output may be NULL
```

Our Optional attribute would be emitted for __RPC__deref_opt_... but not for __RPC__deref_..._opt. Following this rule would fix this problem.

**Comment by kennykerr** [comment]
Nice! 👍🤯

**Comment by sotteson1** [comment]
Fixed in latest version
