### ISSUE TITLE
Add PSECURITY_DESCRIPTOR as NativeTypeDef

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#835]
Now that we removed the incorrect PSECURITY_DESCRIPTOR mapping (see #821), let's fill in the gap with a PSECURITY_DESCRIPTOR NativeTypeDef so we're not just left with a naked pointer.

**Comment by kennykerr** [comment]
This is a pretty big regression in the API surface described by the latest win32 metadata release. It would be great if we can resolve this quickly so I can retest and stabilize.
