### ISSUE TITLE
DirectStorage Support

### ISSUE THREAD

**Issue by atynagano** [microsoft/win32metadata#836]
DirectStorage API was officially released on March14, 2022. Is there a plan to add it?

https://devblogs.microsoft.com/directx/directstorage-api-downloads/

**Comment by mikebattista** [comment]
This is a separate SDK from the Windows SDK so they would need to use [our tooling](https://www.nuget.org/packages/Microsoft.Windows.WinmdGenerator/) to produce their own metadata. I'd suggest filing an issue in [their repo](https://github.com/microsoft/DirectStorage) requesting this.

**Comment by atynagano** [comment]
> This is a separate SDK from the Windows SDK so they would need to use [our tooling](https://www.nuget.org/packages/Microsoft.Windows.WinmdGenerator/) to produce their own metadata. I'd suggest filing an issue in [their repo](https://github.com/microsoft/DirectStorage) requesting this.

But this repo contains a [dxcompiler](https://github.com/microsoft/DirectXShaderCompiler) metadata, that is not a part of Windows SDK. I don't know the difference.
