### ISSUE TITLE
Various `IsDirty` methods on COM interfaces need `PreserveSig`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#838]
Interfaces including `IPersistMemory`, `IPersistStreamInit`, `IPersistPropertyBag2` have an `IsDirty` method that may return either `S_OK` or `S_FALSE` and thus need the `PreserverSig` attribute to allow language projections to handle this correctly.

**Comment by mikebattista** [comment]
Closed with 9d538bca5810dee87f0625533c36a09f9dc75ef1.
