### ISSUE TITLE
`AF_INET` and `AF_INET6` should not be exclusive to `Win32::NetworkManagement::IpHelper`

### ISSUE THREAD

**Issue by Jake-Shadle** [microsoft/win32metadata#845]
For some reason, both the `AF_INET` and `AF_INET6` constants are not part of `Win32::Networking::Winsock` like all of the other address family constants, but are rather exclusively part of the `Win32::NetworkManagment::IpHelper` module. This means one must (in Rust) enable that module when creating basic TCP/UDP sockets (the overwhelming use case), which is fairly ridiculous given the [size](https://docs.rs/windows-sys/latest/windows_sys/Win32/NetworkManagement/IpHelper/index.html) of that module.

I propose the constants should either be moved to `WinSock`, or at the very least available in both locations.

**Comment by kennykerr** [comment]
This is now included in the 0.35.0 release: https://github.com/microsoft/windows-rs/releases/tag/0.35.0
