### ISSUE TITLE
Cannot access alternative success `HRESULT` values returned by IEnumExplorerCommand::*

### ISSUE THREAD

**Issue by kaivol** [microsoft/win32metadata#852]
### Which crate is this about?

windows

### Crate version

0.34.0

### Summary

I'm trying to implement an custom explorer context menu entry, and in the progress I came across the  [`IEnumExplorerCommand::Next`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ienumexplorercommand-next) method. 
According to the documentation `Next` only returns `S_OK` on success, and consequently has the return type `Result<()>` in [windows-rs](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/trait.IEnumExplorerCommand_Impl.html), but I suspect that the documentation is incorrect (see e.g. this [sample](https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/Win7Samples/winui/shell/shellextensibility/explorerdataprovider/FVCommands.cpp#L87)). 

Is there some workaround that allows to return other `HRESULT` values like `S_FALSE`?

**Comment by kennykerr** [comment]
[0.36.0](https://github.com/microsoft/windows-rs/releases/tag/0.36.0) of the `windows` crate has been released and includes this fix.
