### ISSUE TITLE
Is `PVOID64` correctly interpreted for 32-bit applications?

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#866]
The docs for [`ReadFileScatter`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfilescatter#remarks) use `PVOID64` for the `Buffer`

> The [`FILE_SEGMENT_ELEMENT`](https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_file_segment_element) union is defined as follows:
>
> ```cpp
> typedef union _FILE_SEGMENT_ELEMENT {
>    PVOID64 Buffer;
>    ULONGLONG Alignment;
> }FILE_SEGMENT_ELEMENT, *PFILE_SEGMENT_ELEMENT;
> ```
> Assigning a pointer to the `Buffer` member will sign-extend the value if the code is compiled as 32-bits; this can break large-address aware applications running on systems configured with [4-Gigabyte Tuning](https://docs.microsoft.com/en-us/windows/desktop/Memory/4-gigabyte-tuning) or running on under WOW64 on 64-bit Windows. Therefore, use the `PtrToPtr64` macro when assigning pointers to `Buffer`.

However in the metadata `FILE_SEGMENT_ELEMENT` simply uses `void*` instead of `PVOID64`:

```csharp
[StructLayout(LayoutKind.Explicit)]
public struct FILE_SEGMENT_ELEMENT
{
	[FieldOffset(0)]
	public unsafe void* Buffer;

	[FieldOffset(0)]
	public ulong Alignment;
}
```

For 64-bit applications these are the same thing. ~However, for 32-bit applications I think the union will be smaller than expected?~

**Comment by KalleOlaviNiemitalo** [comment]
The size of the union will be correct anyway, because of the 64-bit `Alignment` member. However, there might be a risk that the incorrect type of `Buffer` causes an application to set only the low 32 bits of the pointer and leave some uninitialized garbage in the high 32 bits.

**Comment by riverar** [comment]
Don't think there's an error here. `PVOID64` ultimately traces back to built-in type `__ptr64`.

> On a 32-bit system, a pointer declared with __ptr64 is truncated to a 32-bit pointer. On a 64-bit system, a pointer declared with __ptr32 is coerced to a 64-bit pointer. - [(Microsoft Docs)](https://docs.microsoft.com/cpp/cpp/ptr32-ptr64?view=msvc-170&WT.mc_id=WD-MVP-5002756)

**Comment by ChrisDenton** [comment]
Sure but `__ptr64` is not the same as `void*` on 32 bit systems? Like, on a 32bit system in C++ `sizeof(PVOID64)` will be equal to 8 rather than 4.

**Comment by riverar** [comment]
Fair, yep. Will get this fixed!

**Comment by mikebattista** [comment]
What type should this field be in metadata terms?

**Comment by riverar** [comment]
Think the best we can do here is declare this as `int64` for both architectures or add a 32-bit variant with `int64` and a 64-bit variant with `void*` (as-is). @ChrisDenton @KalleOlaviNiemitalo thoughts?

**Comment by ChrisDenton** [comment]
I've been thinking more about this. If the Windows implementation ignores the padding then the definition is fine as is. But I'm not sure if this would be safe to assume even if it does currently.

Otherwise I think the current definition is more or less correct but it should somehow indicate that `Alignment` must be zero initialized on construction and not set afterward. At least for 32 bit applications.

I'm not sure if that's an API documentation issue or a metadata issue. Or both.

I do think it's important we use actual pointer types here. Rust can be particularly sensitive about using pointer types for pointers.

**Comment by kennykerr** [comment]
I think this is a case where the metadata is as explicit/accurate/correct as it can be, and it is up to callers to use the API correctly. Even in C++, it takes care to use this correctly e.g. double casting is required.

**Comment by ChrisDenton** [comment]
Yes, I think I'll close this issue but it can be reopened if anyone has any objections.

For fun I did create a hand rolled version that has the same layout but helps avoid misuse. However it diverges from the C definition by not being a union and thus also not having `Alignment`.

<details><summary>pardon my rust</summary>

```rust
use std::ffi::c_void;

// This is really two structs: one for 32-bit and one for 64-bit.
#[repr(C, align(8))]
pub struct FILE_SEGMENT_ELEMENT {
    pub Buffer: *mut c_void,

    #[cfg(target_pointer_width="32")]
    // 32-bit implementation
    // MUST be initialized to zero.
    // This is private but set by a public constructor function.
    _reserved: u32,

    #[cfg(target_pointer_width="64")]
    // 64-bit implementation
    // Private zero sized type to prevent construction.
    // This is just for consistency with the 32-bit implementation.
    _reserved: (),
}
impl FILE_SEGMENT_ELEMENT {
    // public constructor
    pub const fn new(buffer: *mut c_void) -> FILE_SEGMENT_ELEMENT {
        FILE_SEGMENT_ELEMENT {
            Buffer: buffer,
            #[cfg(target_pointer_width="32")] _reserved: 0,
            #[cfg(target_pointer_width="64")] _reserved: (),
        }
    }
}
```

</details>
