### ISSUE TITLE
`SysAllocStringByteLen` missing the `NativeArrayInfo` attribute

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#868]
`SysAllocStringLen` correctly attributes the parameter as an array:

```C#
public static extern BSTR SysAllocStringLen([Optional][In][Const][NativeArrayInfo(CountParamIndex = 1)] PWSTR strIn, [In] uint ui);
```

But `SysAllocStringByteLen` lacks the attribute, making it harder to call:

```C#
public static extern BSTR SysAllocStringByteLen([Optional][In][Const] PSTR psz, [In] uint len);
```

**Comment by mikebattista** [comment]
Windows.Win32.Foundation.Apis.SysAllocStringByteLen : psz : [Optional,In,Const] => [Optional,In,Const,NativeArrayInfo(CountParamIndex=1)]
