### ISSUE TITLE
UpdateProcThreadAttribute should use u32 for 'attribute' argument

### ISSUE THREAD

**Issue by zaddach** [microsoft/win32metadata#872]
The argument `attribute` to [UpdateProcThreadAttribute](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/fn.UpdateProcThreadAttribute.html) is a `usize`, even though the attributes (such as [PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/constant.PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES.html) are `u32`.

**Comment by mikebattista** [comment]
I'm not sure how to handle this one.

The API is defined as accepting a `DWORD_PTR` so the function definition in the metadata is true to the headers.

The constants are defined in https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/Partitions/Threading/main.cpp if someone can recommend how they should be changed to align with the API.

**Comment by riverar** [comment]
There's a mismatch but I don't think we can do much here, due to ABI compatibility constraints.

**Comment by riverar** [comment]
I think we had a similar discussion in https://github.com/microsoft/win32metadata/issues/1502#issuecomment-1476945576 where we discussed how various structures, enumerations, etc. may be used in third party code (e.g. libs) and deviating from the definitions may cause unintended side effects. (There were some godbolt examples in there demonstrating some optimizer shortcuts that would fail.)

**Comment by ChrisDenton** [comment]
I absolutely agree we shouldn't be changing the ABI. Both of functions and structs. I'm less clear on integer widths of `#define`s though. They're already a bit weird (preprocessor magic) and when combined with C/C++'s integer promotion rules I'm not sure how meaningful the size is on its own. I mean, purely in terms of bitwidth. Signed/unsigned might be a bit more meaningful.

**Comment by mikebattista** [comment]
Closing for now. Reactivate if there's something actionable here.
