### ISSUE TITLE
Metadata Namespace Windows.Win32.Graphics.Direct2D.Common

### ISSUE THREAD

**Issue by gerhard17** [microsoft/win32metadata#874]
What is the reason that the interface ID2D1GeometrySink is in the namespace Windows.Win32.Graphics.Direct2D - while the interface ID2D1SimplifiedGeometrySink is in the namespace Windows.Win32.Graphics.Direct2D.<ins>Common</ins>?

Maybe the deeper question is: Why is the Windows.Win32.Graphics.Direct2D.<ins>Common</ins> namespace generated at all?

At least I was surprised, because I didn't find the ID2D1SimplifiedGeometrySink interface, which I expected in Windows.Win32.Graphics.Direct2D after reading the Microsoft Docs.

https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1geometrysink
https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nn-d2d1-id2d1simplifiedgeometrysink

**Comment by gerhard17** [comment]
This sounds a little bit artificial. Driven by a single concrete language projection.

- What is the criteria that an interface, enum or an struct lands into a "Common" namespace?
- Can I flatten out every "Common" namespace into its parent namespace and I will get the Windows API surface clustered like the description at https://docs.microsoft.com/ ?
- Are such namespaces always named "Common"?
Seeing Windows.Win32.Graphics.Imaging and Windows.Win32.Graphics.Imaging.D2D - what algorithm applies to them?

Would it be possible to apply attributes to the metadata...?

- either that a "Common" namespace is really part of a "Parent" namespace (which one?) 
- or the other way around, removing such namespaces and mark individual members as "common"?
This would allow a simple code generation, structured like described in https://docs.microsoft.com/ and individual projections can go their way with sub namespaces or whatever.
- or at least some form of taxative list, which namespaces are splited in such a way (and how).

**Comment by gerhard17** [comment]
I can see there is a [dcommon.h](https://docs.microsoft.com/en-us/windows/win32/api/dcommon/) header. So I can understand a motivation for Direct2D.Common. But if this header is treated as a namespace, why are in the docs significant fewer items (17), than in this repo (29)?

Especially I cannot understand the ID2D1GeometrySink / ID2D1SimplifiedGeometrySink difference.

**Comment by mikebattista** [comment]
From notes in the build (below), sounds like some APIs were moved to Common to avoid circular dependencies between D2D and DWrite and make it easier to include simple types without pulling in the entire D2D namespace.

https://github.com/microsoft/win32metadata/blob/a18ade906ba1306acc001bbea7106e1cf972ae41/generation/WinSDK/requiredNamespacesForNames.rsp#L86-L113

I don't see a need for additional metadata here.
