### ISSUE TITLE
Missing DEBUG_PROCESS debug process creation flags

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/win32metadata#880]
In the DEBUG_CREATE_PROCESS_OPTIONS struct, the field for CreateFlags has several possible flags. the flag DEBUG_ONLY_THIS_PROCESS is available in the windows crate as DEBUG_PROCESS_ONLY_THIS_PROCESS, however the DEBUG_PROCESS  flag does not seem to have a similar variable, so I need to use a 1 literal instead.

**Comment by riverar** [comment]
The flag you're looking for lives in `Windows.Win32.System.Threading`, i.e. `PROCESS_CREATION_FLAGS.DEBUG_PROCESS` (C#) or [`Win32::System::Threading::DEBUG_PROCESS`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/constant.DEBUG_PROCESS.html) (Rust).

If I misunderstood your report, feel free to comment/re-open!
