### ISSUE TITLE
Add struct to HSTRING_HEADER union

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#886]
_Originally requested by @taufikrh in https://github.com/microsoft/win32metadata/issues/871_

> If possible please inject additional union member (struct) for `HSTRING_HEADER`.
> This kind of struct is useful for referencing `HSTRING_HEADER` from `wchar_t*`
> see `__Platform_Details_HSTRING_HEADER` (vccorlib.h) and `hstring_header` (winsdkInc\cppwinrt\winrt\base.h)

```cpp
#define hstring_reference_flag 1 // int

typedef struct HSTRING_HEADER
{
    union {
        PVOID Reserved1;
#if defined(_WIN64)
        char Reserved2[24];
#else
        char Reserved2[20];
#endif
        struct {
            int             flags;             // Bit flags which used for storing extra information
            unsigned int    length;            // length of string's unicode code point
            unsigned int    padding;           // padding for future use
            unsigned int    morepadding;       // padding for future use
            __wchar_t*      stringRef;         // An address pointer which points to a string buffer.
        };
    } Reserved;
} HSTRING_HEADER;
```

**Comment by kennykerr** [comment]
For what it's worth, I've never found the union helpful in implementing `HSTRING` semantics. Here's how I defined this [header in C++/WinRT](https://github.com/microsoft/cppwinrt/blob/c4a8e24472cd652a6f85a8f71180d5ccc2569de5/strings/base_string.h#L50-L57) and here's how I defined it in the [Windows crate for Rust](https://github.com/microsoft/windows-rs/blob/ecd65e16e0024611c8cff7a10bf4490d24aaf1bc/crates/libs/windows/src/core/hstring.rs#L398-L406).
