### ISSUE TITLE
`JOB_OBJECT_NET_RATE_CONTROL_FLAGS` is not tagged as `Flags`

### ISSUE THREAD

**Issue by fabalchemy** [microsoft/win32metadata#895]
The `JOB_OBJECT_NET_RATE_CONTROL_FLAGS` enumeration is not tagged as a `Flags`.
Associated struct: [JOBOBJECT_NET_RATE_CONTROL_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-jobobject_net_rate_control_information).

**Comment by FabAlchemy** [comment]
I've looked around to propose a fix like in #887 but both enumerations are not treated similarly.

In #887, the `ControlFlags` member of `JOBOBJECT_CPU_RATE_CONTROL_INFORMATION` is declared as a `DWORD` and the values are `#define`d.

https://github.com/microsoft/win32metadata/blob/7501f19d0015b59ab843a17aed6c9392d478ff8e/generation/WinSDK/RecompiledIdlHeaders/um/winnt.h#L13213-L13223

https://github.com/microsoft/win32metadata/blob/7501f19d0015b59ab843a17aed6c9392d478ff8e/generation/WinSDK/RecompiledIdlHeaders/um/winnt.h#L13477-L13485

However, `JOB_OBJECT_NET_RATE_CONTROL_FLAGS` is correctly declared as an `enum` and does not appear in `enums.json`.

https://github.com/microsoft/win32metadata/blob/7501f19d0015b59ab843a17aed6c9392d478ff8e/generation/WinSDK/RecompiledIdlHeaders/um/winnt.h#L13229-L13234

**Comment by mikebattista** [comment]
enums.json is used to collect loose constants into enums. The net rate control enum is properly defined as an enum in the original header so would not be defined in enums.json. The CPU rate constants are just loose constants so are collected into an enum in enums.json.

You can add flags to existing enums from headers by listing them under --enumMakeFlags in emitter.settings.rsp. I made the changes.
