### ISSUE TITLE
Feature request: Add CreateVssBackupComponents

### ISSUE THREAD

**Issue by TechThupport** [microsoft/win32metadata#897]
### Motivation

Add some of the functions from vss apis

### Drawbacks

Can do this by loading vssapi.dll, might be not needed

**Comment by mikebattista** [comment]
This is an inline function calling an Internal API. Not sure how/if that could be represented in metadata.

```
inline HRESULT  CreateVssBackupComponents
    (
    _Out_ IVssBackupComponents **ppBackup
    )
{
    return CreateVssBackupComponentsInternal(ppBackup);
}
```

**Comment by mikebattista** [comment]
We don't support inline functions in the metadata.
