### ISSUE TITLE
Consider removing general numeric constants

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#90]
All of the languages we support provide constants for common values like NaN and friends. The metadata doesn't not need to include stuff like this:

```C++
DECLSPEC_SELECTANY extern const float POSITIVE_INFINITY = ((float)(1e308 * 10));
DECLSPEC_SELECTANY extern const float NEGATIVE_INFINITY = ((float)(-1e308 * 10));
DECLSPEC_SELECTANY extern const float NaN = ((float)((1e308 * 10)*0.));
```

**Comment by mikebattista** [comment]
Are all examples of these under UI.TouchInput? I don't see them anywhere else.

**Comment by kennykerr** [comment]
Also `Windows.Win32.System.WindowsProgramming.INFINITE`
