### ISSUE TITLE
Unmapped Type

### ISSUE THREAD

**Issue by taufikrh** [microsoft/win32metadata#900]
__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0001=MFVirtualCameraType
__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0002=MFVirtualCameraLifetime
__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0003=MFVirtualCameraAccess

__MIDL___MIDL_itf_imgerror_0000_0000_0001=ImgErrorInfo
__MIDL___MIDL_itf_mmdeviceapi_0000_0008_0002=AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE
__MIDL___MIDL_itf_rdpencomapi_0000_0027_0001=RDPENCOMAPI_CONSTANTS **(typo in scraper.settings)**
__MIDL___MIDL_itf_jscript9diag_0000_0007_0001=JS_NATIVE_FRAME

__MIDL___MIDL_itf_mtxadmin_0107_0001=MTSPackageInstallOptions
__MIDL___MIDL_itf_mtxadmin_0107_0002=MTSPackageExportOptions
__MIDL___MIDL_itf_mtxadmin_0107_0003=MTSAdminErrorCodes

__MIDL_ITargetFrame2_0001=FINDFRAME_FLAGS
__MIDL_ITargetFrame2_0002=FRAMEOPTIONS_FLAGS

__MIDL_ITargetFrame_0001=NAVIGATEFRAME_FLAGS

**Comment by mikebattista** [comment]
Windows.Win32.Media.Audio.Apo.AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_NOTIFICATION.propertyStoreType...Windows.Win32.Media.Audio.__MIDL___MIDL_itf_mmdeviceapi_0000_0008_0002 => Windows.Win32.Media.Audio.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE
Windows.Win32.Web.MsHtml.__MIDL_ITargetFrame2_0001 not found in 2nd winmd
Windows.Win32.Web.MsHtml.__MIDL_ITargetFrame2_0002 not found in 2nd winmd
Windows.Win32.Web.MsHtml.__MIDL_ITargetFrame_0001 not found in 2nd winmd
Windows.Win32.System.DesktopSharing.__MIDL___MIDL_itf_rdpencomapi_0000_0027_0001 not found in 2nd winmd
Windows.Win32.System.TransactionServer.__MIDL___MIDL_itf_mtxadmin_0107_0001 not found in 2nd winmd
Windows.Win32.System.TransactionServer.__MIDL___MIDL_itf_mtxadmin_0107_0002 not found in 2nd winmd
Windows.Win32.System.TransactionServer.__MIDL___MIDL_itf_mtxadmin_0107_0003 not found in 2nd winmd
Windows.Win32.Media.Audio.__MIDL___MIDL_itf_mmdeviceapi_0000_0008_0002 not found in 2nd winmd
Windows.Win32.Media.Audio.IAudioSystemEffectsPropertyChangeNotificationClient.OnPropertyChanged : type...__MIDL___MIDL_itf_mmdeviceapi_0000_0008_0002 => AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE
Windows.Win32.System.Diagnostics.Debug.__MIDL___MIDL_itf_jscript9diag_0000_0007_0001 not found in 2nd winmd
Windows.Win32.System.Diagnostics.Debug.IEnumJsStackFrames.Next : pFrames...__MIDL___MIDL_itf_jscript9diag_0000_0007_0001* => JS_NATIVE_FRAME*
Windows.Win32.Media.MediaFoundation.__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0001 not found in 2nd winmd
Windows.Win32.Media.MediaFoundation.__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0002 not found in 2nd winmd
Windows.Win32.Media.MediaFoundation.__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0003 not found in 2nd winmd
Windows.Win32.Graphics.Printing.__MIDL___MIDL_itf_imgerror_0000_0000_0001 not found in 2nd winmd
Windows.Win32.Graphics.Printing.IImgErrorInfo.DetachErrorInfo : pErrorInfo...__MIDL___MIDL_itf_imgerror_0000_0000_0001* => ImgErrorInfo*
Windows.Win32.Graphics.Printing.IImgCreateErrorInfo.AttachToErrorInfo : pErrorInfo...__MIDL___MIDL_itf_imgerror_0000_0000_0001* => ImgErrorInfo*
Windows.Win32.Web.MsHtml.FINDFRAME_FLAGS not found in 1st winmd
Windows.Win32.Web.MsHtml.FRAMEOPTIONS_FLAGS not found in 1st winmd
Windows.Win32.Web.MsHtml.NAVIGATEFRAME_FLAGS not found in 1st winmd
Windows.Win32.System.DesktopSharing.RDPENCOMAPI_CONSTANTS not found in 1st winmd
Windows.Win32.System.TransactionServer.MTSPackageInstallOptions not found in 1st winmd
Windows.Win32.System.TransactionServer.MTSPackageExportOptions not found in 1st winmd
Windows.Win32.System.TransactionServer.MTSAdminErrorCodes not found in 1st winmd
Windows.Win32.Media.Audio.AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE not found in 1st winmd
Windows.Win32.System.Diagnostics.Debug.JS_NATIVE_FRAME not found in 1st winmd
Windows.Win32.Media.MediaFoundation.MFVirtualCameraType not found in 1st winmd
Windows.Win32.Media.MediaFoundation.MFVirtualCameraLifetime not found in 1st winmd
Windows.Win32.Media.MediaFoundation.MFVirtualCameraAccess not found in 1st winmd
Windows.Win32.Graphics.Printing.ImgErrorInfo not found in 1st winmd
Windows.Win32.Media.MediaFoundation.Apis.MFCreateVirtualCamera : type...__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0001 => MFVirtualCameraType
Windows.Win32.Media.MediaFoundation.Apis.MFCreateVirtualCamera : lifetime...__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0002 => MFVirtualCameraLifetime
Windows.Win32.Media.MediaFoundation.Apis.MFCreateVirtualCamera : access...__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0003 => MFVirtualCameraAccess
Windows.Win32.Media.MediaFoundation.Apis.MFIsVirtualCameraTypeSupported : type...__MIDL___MIDL_itf_mfvirtualcamera_0000_0000_0001 => MFVirtualCameraType
