### ISSUE TITLE
Visual styles headers are missing

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#901]
Lots of UX theme stuff in the `vsstyle.h` and `Vssym32.h` headers that need to be captured as Windows metadata. For more, see
https://docs.microsoft.com/en-us/windows/win32/controls/parts-and-states#parts-and-states-of-standard-controls-and-windows

Here's an example of how this is used:
https://github.com/grassator/win32-window-custom-titlebar/blob/c0babc525414daf916ab19911f063c89e4b3e395/main.c#L98

**Comment by mikebattista** [comment]
Everything from vssym32.h appears to be under Windows.Win32.UI.Controls.

vsstyle.h is not being scanned. I'll add it to the same namespace.

**Comment by mikebattista** [comment]
Windows.Win32.UI.Controls.AEROWIZARDPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TITLEBARSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERAREASTATES not found in 1st winmd
Windows.Win32.UI.Controls.CONTENTAREASTATES not found in 1st winmd
Windows.Win32.UI.Controls.BUTTONPARTS not found in 1st winmd
Windows.Win32.UI.Controls.PUSHBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.RADIOBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CHECKBOXSTATES not found in 1st winmd
Windows.Win32.UI.Controls.GROUPBOXSTATES not found in 1st winmd
Windows.Win32.UI.Controls.COMMANDLINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.COMMANDLINKGLYPHSTATES not found in 1st winmd
Windows.Win32.UI.Controls.PUSHBUTTONDROPDOWNSTATES not found in 1st winmd
Windows.Win32.UI.Controls.COMBOBOXPARTS not found in 1st winmd
Windows.Win32.UI.Controls.COMBOBOXSTYLESTATES not found in 1st winmd
Windows.Win32.UI.Controls.DROPDOWNBUTTONRIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DROPDOWNBUTTONLEFTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TRANSPARENTBACKGROUNDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BORDERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.READONLYSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CUEBANNERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DROPDOWNITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.COMMUNICATIONSPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TABSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CONTROLPANELPARTS not found in 1st winmd
Windows.Win32.UI.Controls.HELPLINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TASKLINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CONTENTLINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SECTIONTITLELINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DATEPICKERPARTS not found in 1st winmd
Windows.Win32.UI.Controls.DATETEXTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DATEBORDERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SHOWCALENDARBUTTONRIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DRAGDROPPARTS not found in 1st winmd
Windows.Win32.UI.Controls.COPYSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MOVESTATES not found in 1st winmd
Windows.Win32.UI.Controls.UPDATEMETADATASTATES not found in 1st winmd
Windows.Win32.UI.Controls.CREATELINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.WARNINGSTATES not found in 1st winmd
Windows.Win32.UI.Controls.NONESTATES not found in 1st winmd
Windows.Win32.UI.Controls.EDITPARTS not found in 1st winmd
Windows.Win32.UI.Controls.EDITTEXTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BACKGROUNDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BACKGROUNDWITHBORDERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.EDITBORDER_NOSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.EDITBORDER_HSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.EDITBORDER_VSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.EDITBORDER_HVSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.EXPLORERBARPARTS not found in 1st winmd
Windows.Win32.UI.Controls.HEADERCLOSESTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERPINSTATES not found in 1st winmd
Windows.Win32.UI.Controls.IEBARMENUSTATES not found in 1st winmd
Windows.Win32.UI.Controls.NORMALGROUPCOLLAPSESTATES not found in 1st winmd
Windows.Win32.UI.Controls.NORMALGROUPEXPANDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SPECIALGROUPCOLLAPSESTATES not found in 1st winmd
Windows.Win32.UI.Controls.SPECIALGROUPEXPANDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FLYOUTPARTS not found in 1st winmd
Windows.Win32.UI.Controls.LABELSTATES not found in 1st winmd
Windows.Win32.UI.Controls.LINKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BODYSTATES not found in 1st winmd
Windows.Win32.UI.Controls.LINKHEADERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERPARTS not found in 1st winmd
Windows.Win32.UI.Controls.HEADERSTYLESTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERITEMLEFTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERITEMRIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERSORTARROWSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERDROPDOWNSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADERDROPDOWNFILTERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HEADEROVERFLOWSTATES not found in 1st winmd
Windows.Win32.UI.Controls.LISTBOXPARTS not found in 1st winmd
Windows.Win32.UI.Controls.BORDER_HSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BORDER_HVSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BORDER_NOSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BORDER_VSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.ITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.LISTVIEWPARTS not found in 1st winmd
Windows.Win32.UI.Controls.LISTITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.GROUPHEADERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.GROUPHEADERLINESTATES not found in 1st winmd
Windows.Win32.UI.Controls.EXPANDBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.COLLAPSEBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MENUPARTS not found in 1st winmd
Windows.Win32.UI.Controls.BARBACKGROUNDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BARITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.POPUPCHECKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.POPUPCHECKBACKGROUNDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.POPUPITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.POPUPSUBMENUSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SYSTEMCLOSESTATES not found in 1st winmd
Windows.Win32.UI.Controls.SYSTEMMAXIMIZESTATES not found in 1st winmd
Windows.Win32.UI.Controls.SYSTEMMINIMIZESTATES not found in 1st winmd
Windows.Win32.UI.Controls.SYSTEMRESTORESTATES not found in 1st winmd
Windows.Win32.UI.Controls.NAVIGATIONPARTS not found in 1st winmd
Windows.Win32.UI.Controls.NAV_BACKBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.NAV_FORWARDBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.NAV_MENUBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.PROGRESSPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TRANSPARENTBARSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TRANSPARENTBARVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FILLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FILLVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.REBARPARTS not found in 1st winmd
Windows.Win32.UI.Controls.CHEVRONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CHEVRONVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SPLITTERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SPLITTERVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SCROLLBARPARTS not found in 1st winmd
Windows.Win32.UI.Controls.ARROWBTNSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SCROLLBARSTYLESTATES not found in 1st winmd
Windows.Win32.UI.Controls.SIZEBOXSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SPINPARTS not found in 1st winmd
Windows.Win32.UI.Controls.UPSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DOWNSTATES not found in 1st winmd
Windows.Win32.UI.Controls.UPHORZSTATES not found in 1st winmd
Windows.Win32.UI.Controls.DOWNHORZSTATES not found in 1st winmd
Windows.Win32.UI.Controls.STATUSPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TABPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TABITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TABITEMLEFTEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TABITEMRIGHTEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TABITEMBOTHEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOPTABITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOPTABITEMLEFTEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOPTABITEMRIGHTEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOPTABITEMBOTHEDGESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TASKDIALOGPARTS not found in 1st winmd
Windows.Win32.UI.Controls.CONTENTPANESTATES not found in 1st winmd
Windows.Win32.UI.Controls.EXPANDOBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TEXTSTYLEPARTS not found in 1st winmd
Windows.Win32.UI.Controls.HYPERLINKTEXTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CONTROLLABELSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOOLBARPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TOOLBARSTYLESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TOOLTIPPARTS not found in 1st winmd
Windows.Win32.UI.Controls.CLOSESTATES not found in 1st winmd
Windows.Win32.UI.Controls.STANDARDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BALLOONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.BALLOONSTEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.WRENCHSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TRACKBARPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TRACKBARSTYLESTATES not found in 1st winmd
Windows.Win32.UI.Controls.TRACKSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TRACKVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBBOTTOMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBTOPSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBLEFTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.THUMBRIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TICSSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TICSVERTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TREEVIEWPARTS not found in 1st winmd
Windows.Win32.UI.Controls.TREEITEMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.GLYPHSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HOTGLYPHSTATES not found in 1st winmd
Windows.Win32.UI.Controls.USERTILEPARTS not found in 1st winmd
Windows.Win32.UI.Controls.HOVERBACKGROUNDSTATES not found in 1st winmd
Windows.Win32.UI.Controls.TEXTSELECTIONGRIPPERPARTS not found in 1st winmd
Windows.Win32.UI.Controls.GRIPPERSTATES not found in 1st winmd
Windows.Win32.UI.Controls.WINDOWPARTS not found in 1st winmd
Windows.Win32.UI.Controls.FRAMESTATES not found in 1st winmd
Windows.Win32.UI.Controls.CAPTIONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MAXCAPTIONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MINCAPTIONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HORZSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HORZTHUMBSTATES not found in 1st winmd
Windows.Win32.UI.Controls.VERTSCROLLSTATES not found in 1st winmd
Windows.Win32.UI.Controls.VERTTHUMBSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SYSBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MINBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MAXBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.RESTOREBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.HELPBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.CLOSEBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SMALLCLOSEBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FRAMEBOTTOMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FRAMELEFTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.FRAMERIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SMALLCAPTIONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SMALLFRAMEBOTTOMSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SMALLFRAMELEFTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.SMALLFRAMERIGHTSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MDICLOSEBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MDIMINBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.MDIRESTOREBUTTONSTATES not found in 1st winmd
Windows.Win32.UI.Controls.Apis.TMTVS_RESERVEDLOW not found in 1st winmd
Windows.Win32.UI.Controls.Apis.TMTVS_RESERVEDHIGH not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_AEROWIZARDSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_AEROWIZARD not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_BUTTONSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_BUTTON not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_COMBOBOXSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_COMBOBOX not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_COMMUNICATIONSSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_COMMUNICATIONS not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_CONTROLPANELSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_CONTROLPANEL not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_DATEPICKERSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_DATEPICKER not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_DRAGDROPSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_DRAGDROP not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_EDITSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_EDIT not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_EXPLORERBARSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_EXPLORERBAR not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_FLYOUTSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_FLYOUT not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_HEADERSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_HEADER not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_LISTBOXSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_LISTBOX not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_LISTVIEWSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_LISTVIEW not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_MENUSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_MENU not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_NAVIGATION not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_PROGRESSSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_PROGRESS not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_REBARSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_REBAR not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_SCROLLBARSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_SCROLLBAR not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_SPINSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_SPIN not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_STATUSSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_STATUS not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TABSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TAB not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TASKDIALOGSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TASKDIALOG not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TEXTSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TOOLBARSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TOOLBAR not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TOOLTIPSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TOOLTIP not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TRACKBARSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TRACKBAR not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TREEVIEWSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TREEVIEW not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_USERTILE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_TEXTSELECTIONGRIPPER not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_WINDOWSTYLE not found in 1st winmd
Windows.Win32.UI.Controls.Apis.VSCLASS_WINDOW not found in 1st winmd
