### ISSUE TITLE
DiInstallDevice only generated to take SP_DRVINFO_DATA_V2_A

### ISSUE THREAD

**Issue by dorssel** [microsoft/win32metadata#903]
In version 22.0.14-preview, `DiInstallDevice` could (should?) take SP_DRVINFO_DATA_V2_W.

I'm not entirely sure if this API exists in both A and W variants. The newdev.h include file isn't very clear on that. There it takes a SP_DRVINFO_DATA_V2, which turns into either SP_DRVINFO_DATA_V2_W or SP_DRVINFO_DATA_V2_A depending whether compiling with UNICODE.

Maybe (again ... not sure), `DiInstallDevice` determines the TCHAR type depending on cbSize? In any case, for C++ I always compile with UNICODE, and then `DiInstallDevice` definitely takes a SP_DRVINFO_DATA_V2_W. But CsWin32 generates only a SP_DRVINFO_DATA_V2_A signature. The only way to use it is to use the unsafe pointer signature (and use a cast); the safe call doesn't work.

Also: not sure if this is a problem with win32metadata, or with CsWin32.

**Comment by Kogotoro** [comment]
it's probably because the inf file is not in unicode (utf-16)... 
and SetupDiBuildDriverInfoList or SetupDiEnumDriverInfo do mess when get wrong encoded inf file...
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/general-unicode-requirement

**Comment by mikebattista** [comment]
So you just want this API to take the W struct and not the A struct?

**Comment by dorssel** [comment]
I found out that `DiInstallDevice` does *not* come in an 'A' and a 'W' variant. There is just plain `DiInstallDevice` exported by `newdev.dll` (unlike `DiInstallDriver`, which exists as `DiInstallDriverA` and `DiInstallDriverW`). This is a bit weird, since normally all functions that take strings (or pointers to structs that contain strings, etc.) have the A and W version of the function.

What I also know is that `DiInstallDevice` definitely accepts a `SP_DRVINFO_DATA_V2_W`, which is what I would like to use (I cannot see why anyone would want to use the ANSI/OEM structure `SP_DRVINFO_DATA_V2_A` in 2023). Maybe (just maybe) `DiInstallDevice` actually accepts either. I haven't tested that, since I always compile with UNICODE defined. But if that were the case then there should be two wrappers, one for each. But currently there is only one, which accepts `SP_DRVINFO_DATA_V2_A`.

So, (TL;DR): yes, I would like it to take a `SP_DRVINFO_DATA_V2_W`, but maybe it should take either.

**Comment by mikebattista** [comment]
I think what I'll do here is exclude the original definition and add -A and -W variants like the other APIs. That's probably how it should have been implemented to begin with. We can update the EntryPoint on each of these variants to call the original API but each would accept a different struct.

**Comment by mikebattista** [comment]
This is now defined as the below in the metadata. Notice the -A and -W definitions with the EntryPoint set to the original function.

```
[DllImport("newdev.dll", EntryPoint = "DiInstallDevice", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern BOOL DiInstallDeviceA([Optional][In] HWND hwndParent, [In] HDEVINFO DeviceInfoSet, [In] SP_DEVINFO_DATA* DeviceInfoData, [Optional][In] SP_DRVINFO_DATA_V2_A* DriverInfoData, [In] uint Flags, [Optional][Out] BOOL* NeedReboot);

[DllImport("newdev.dll", EntryPoint = "DiInstallDevice", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern BOOL DiInstallDeviceW([Optional][In] HWND hwndParent, [In] HDEVINFO DeviceInfoSet, [In] SP_DEVINFO_DATA* DeviceInfoData, [Optional][In] SP_DRVINFO_DATA_V2_W* DriverInfoData, [In] uint Flags, [Optional][Out] BOOL* NeedReboot);
```

@aarnott @kennykerr @timsneath @marler8997 FYI on this change in case projections don't already account for this scenario.

**Comment by riverar** [comment]
There is no ANSI variant of `DiInstallDevice`; this function assumes the W variant and passes it onto SetupDiSetSelectedDriverW and friends.

I recommend we:
* rename the API back to `DiInstallDevice` to realign with docs
* (optional) drop the ANSI variants of the SP_DRVINFO_DATA_V1 and SP_DRVINFO_DATA_V2 structures

**Comment by mikebattista** [comment]
The original API accepts either depending on whether UNICODE is defined. When UNICODE is not defined is effectively the "ANSI variant".

```
#ifdef UNICODE
typedef SP_DRVINFO_DATA_V1_W SP_DRVINFO_DATA_V1;
typedef PSP_DRVINFO_DATA_V1_W PSP_DRVINFO_DATA_V1;
typedef SP_DRVINFO_DATA_V2_W SP_DRVINFO_DATA_V2;
typedef PSP_DRVINFO_DATA_V2_W PSP_DRVINFO_DATA_V2;
#else
typedef SP_DRVINFO_DATA_V1_A SP_DRVINFO_DATA_V1;
typedef PSP_DRVINFO_DATA_V1_A PSP_DRVINFO_DATA_V1;
typedef SP_DRVINFO_DATA_V2_A SP_DRVINFO_DATA_V2;
typedef PSP_DRVINFO_DATA_V2_A PSP_DRVINFO_DATA_V2;
#endif
```

**Comment by mikebattista** [comment]
Thanks for the investigation. I'll remove the -As and update the original function to take -W structs.
