### ISSUE TITLE
Unsigned vs. signed types in WinSock APIs

### ISSUE THREAD

**Issue by sunfishcode** [microsoft/win32metadata#904]
The `getsockopt` and `setsockopt` functions are declared with `level` and `optname` parameters with type `i32`. The constants used with these functions, such as `SO_TYPE`, `SOL_SOCKET`, `IP_TTL`, `IPV6_V6ONLY`, and several others, have type `u32`.

The `events` and `revents` fields of `WSAPOLLFD`  have type `i16`. The constants used with these fields, such as `POLLIN`, `POLLOUT`, and several others, have type `u16`.

The `socket` function is ddeclared with an `af` parameter with type `i32`. The constants used with this function, such as `AF_INET`, `AF_INET6`, `AF_UNSPEC`, and several others, have type `u32`.

These differences lead to extra casting. The corresponding POSIX APIs use signed types, so for portable code, it would be convenient if the constants were changed to have signed types.

This is in windows-sys 0.36.0.

**Comment by sunfishcode** [comment]
My code already had casts for these so I didn't initially notice them,, but it looks like `SOCK_STREAM``and the other socket type constants, and `IPPROTO_IP` and the other protocol constants also don't match the corresponding `socket` parameters.

**Comment by mikebattista** [comment]
https://github.com/microsoft/win32metadata/issues/675 addressed socket options.
