### ISSUE TITLE
Duplicate Items

### ISSUE THREAD

**Issue by taufikrh** [microsoft/win32metadata#906]
`Windows.Win32.UI.WindowsAndMessaging.Apis.COLOR_BTNHILIGHT`
`Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX._COLOR_BTNHILIGHT`

`Windows.Win32.UI.WindowsAndMessaging.Apis.COLOR_BTNHIGHLIGHT`
`Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX._COLOR_BTNHIGHLIGHT`

**Comment by mikebattista** [comment]
Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX._COLOR_BTNHIGHLIGHT not found in 2nd winmd
Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX._COLOR_BTNHILIGHT not found in 2nd winmd
Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX.COLOR_BTNHIGHLIGHT not found in 1st winmd
Windows.Win32.UI.WindowsAndMessaging.SYS_COLOR_INDEX.COLOR_BTNHILIGHT not found in 1st winmd
Windows.Win32.UI.WindowsAndMessaging.Apis.COLOR_BTNHIGHLIGHT not found in 2nd winmd
Windows.Win32.UI.WindowsAndMessaging.Apis.COLOR_BTNHILIGHT not found in 2nd winmd
