### ISSUE TITLE
Missing `TOKEN_READ`, `TOKEN_WRITE` and `TOKEN_EXECUTE` constants

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#908]
These constants appear in winnt.h but I can't find them in the metadata:

```cpp
#define TOKEN_READ       (STANDARD_RIGHTS_READ      |\
                          TOKEN_QUERY)


#define TOKEN_WRITE      (STANDARD_RIGHTS_WRITE     |\
                          TOKEN_ADJUST_PRIVILEGES   |\
                          TOKEN_ADJUST_GROUPS       |\
                          TOKEN_ADJUST_DEFAULT)

#define TOKEN_EXECUTE    (STANDARD_RIGHTS_EXECUTE)

#define TOKEN_TRUST_CONSTRAINT_MASK    (STANDARD_RIGHTS_READ  | \
                                       TOKEN_QUERY  |\
                                       TOKEN_QUERY_SOURCE )

#if (NTDDI_VERSION >= NTDDI_WIN8)

#define TOKEN_ACCESS_PSEUDO_HANDLE_WIN8 (TOKEN_QUERY | TOKEN_QUERY_SOURCE)

#define TOKEN_ACCESS_PSEUDO_HANDLE TOKEN_ACCESS_PSEUDO_HANDLE_WIN8

#endif
```

**edit** narrowed the scope of the header file

**Comment by ChrisDenton** [comment]
Yep, I found the ones in your screenshot. But I can't find of the ones in the code I posted. I'm specifically interesting in:

* `TOKEN_READ`
* `TOKEN_WRITE`
* `TOKEN_EXECUTE`

But presumably others such as `TOKEN_ACCESS_PSEUDO_HANDLE_WIN8 ` will be useful to people too.

**Comment by ChrisDenton** [comment]
I edited the quoted code to concentrate on the ones that aren't found.

**Comment by mikebattista** [comment]
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_READ not found in 1st winmd
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_WRITE not found in 1st winmd
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_EXECUTE not found in 1st winmd
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_TRUST_CONSTRAINT_MASK not found in 1st winmd
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_ACCESS_PSEUDO_HANDLE_WIN8 not found in 1st winmd
Windows.Win32.Security.TOKEN_ACCESS_MASK.TOKEN_ACCESS_PSEUDO_HANDLE not found in 1st winmd
