### ISSUE TITLE
Bug: impossible to get HRESULT code from successful completion

### ISSUE THREAD

**Issue by ancwrd1** [microsoft/win32metadata#910]
### Which crate is this about?

windows

### Crate version

0.36.1

### Summary

Some raw API functions which return HRESULT are wrapped into the Rust's `Result` pattern returning `Result<()>`.
From that result it is impossible to get an actual return code which is needed in many cases.
Example: `InitializeSecurityContextW` which may return many successful codes.

I think it's better to revert it to previous behavior of returning plain HRESULT instead of Result.

### Toolchain version/configuration

Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\testuser\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by mikebattista** [comment]
Is `InitializeSecurityContextW` the only API that needs to be updated?

**Comment by ancwrd1** [comment]
Sorry for late reply, in the SChannel context there are at least 3 functions which check the HRESULT:

`AcceptSecurityContext`
`InitializeSecurityContext`
`DecryptMessage`

**Comment by ancwrd1** [comment]
Actually EncryptMessage may also return different codes.

**Comment by mikebattista** [comment]
Windows.Win32.Security.Authentication.Identity.ACCEPT_SECURITY_CONTEXT_CONTEXT_REQ not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.ISC_REQ_FLAGS not found in 1st winmd
Windows.Win32.Security.Authentication.Identity.ASC_REQ_FLAGS not found in 1st winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_DELEGATE not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_MUTUAL_AUTH not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_REPLAY_DETECT not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_SEQUENCE_DETECT not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_CONFIDENTIALITY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_USE_SESSION_KEY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_PROMPT_FOR_CREDS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_USE_SUPPLIED_CREDS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_ALLOCATE_MEMORY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_USE_DCE_STYLE not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_DATAGRAM not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_CONNECTION not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_CALL_LEVEL not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_FRAGMENT_SUPPLIED not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_EXTENDED_ERROR not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_STREAM not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_INTEGRITY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_IDENTIFY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_NULL_SESSION not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_MANUAL_CRED_VALIDATION not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_RESERVED1 not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_FRAGMENT_TO_FIT not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_FORWARD_CREDENTIALS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_NO_INTEGRITY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_USE_HTTP_STYLE not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_UNVERIFIED_TARGET_NAME not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_CONFIDENTIALITY_ONLY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_MESSAGES not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ISC_REQ_DEFERRED_CRED_VALIDATION not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_MUTUAL_AUTH not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_CONFIDENTIALITY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_USE_SESSION_KEY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_SESSION_TICKET not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_USE_DCE_STYLE not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_DATAGRAM not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_CALL_LEVEL not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_FRAGMENT_SUPPLIED not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_INTEGRITY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_LICENSING not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_IDENTIFY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_ALLOW_NULL_SESSION not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_ALLOW_NON_USER_LOGONS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_ALLOW_CONTEXT_REPLAY not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_FRAGMENT_TO_FIT not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_NO_TOKEN not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_PROXY_BINDINGS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_ALLOW_MISSING_BINDINGS not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.ASC_REQ_MESSAGES not found in 2nd winmd
Windows.Win32.Security.Authentication.Identity.Apis.InitializeSecurityContextW : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows5.1.2600)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windows5.1.2600)]
Windows.Win32.Security.Authentication.Identity.Apis.InitializeSecurityContextW : fContextReq...UInt32 => ISC_REQ_FLAGS
Windows.Win32.Security.Authentication.Identity.Apis.InitializeSecurityContextA : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows5.1.2600)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windows5.1.2600)]
Windows.Win32.Security.Authentication.Identity.Apis.InitializeSecurityContextA : fContextReq...UInt32 => ISC_REQ_FLAGS
Windows.Win32.Security.Authentication.Identity.Apis.AcceptSecurityContext : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows6.0.6000)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windows6.0.6000)]
Windows.Win32.Security.Authentication.Identity.Apis.AcceptSecurityContext : fContextReq...ACCEPT_SECURITY_CONTEXT_CONTEXT_REQ => ASC_REQ_FLAGS
Windows.Win32.Security.Authentication.Identity.Apis.EncryptMessage : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows5.1.2600)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windows5.1.2600)]
Windows.Win32.Security.Authentication.Identity.Apis.DecryptMessage : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows5.1.2600)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windows5.1.2600)]
Windows.Win32.Security.Authentication.Identity.Apis.SaslInitializeSecurityContextW : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windowsServer2003)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windowsServer2003)]
Windows.Win32.Security.Authentication.Identity.Apis.SaslInitializeSecurityContextW : fContextReq...UInt32 => ISC_REQ_FLAGS
Windows.Win32.Security.Authentication.Identity.Apis.SaslInitializeSecurityContextA : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windowsServer2003)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windowsServer2003)]
Windows.Win32.Security.Authentication.Identity.Apis.SaslInitializeSecurityContextA : fContextReq...UInt32 => ISC_REQ_FLAGS
Windows.Win32.Security.Authentication.Identity.Apis.SaslAcceptSecurityContext : [DllImport(SECUR32,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windowsServer2003)] => [DllImport(SECUR32,ExactSpelling=True),SupportedOSPlatform(windowsServer2003)]
Windows.Win32.Security.Authentication.Identity.Apis.SaslAcceptSecurityContext : fContextReq...UInt32 => ASC_REQ_FLAGS
