### ISSUE TITLE
Several HTTP Server API is incorrect parameter attribute (IN/OUT/OPTIONAL)

### ISSUE THREAD

**Issue by taufikrh** [microsoft/win32metadata#911]
```cs
[DllImport("HTTPAPI", ExactSpelling = true, PreserveSig = false)]
[SupportedOSPlatform("windows6.0.6000")]
public unsafe static extern uint HttpSendHttpResponse(
    [In] HANDLE RequestQueueHandle,
    [In] ulong RequestId,
    [In] uint Flags,
    [In][Out] HTTP_RESPONSE_V2* HttpResponse,
    [In][Out] HTTP_CACHE_POLICY* CachePolicy,
    [In][Out] uint* BytesSent,
    [In][Out][Reserved] void* Reserved1,
    [In][Reserved] uint Reserved2,
    [In][Out] OVERLAPPED* Overlapped,
    [In][Out] HTTP_LOG_DATA* LogData
    );
```

```cpp
HTTPAPI_LINKAGE
ULONG
WINAPI
HttpSendHttpResponse(
    IN HANDLE RequestQueueHandle,
    IN HTTP_REQUEST_ID RequestId,
    IN ULONG Flags,
    IN PHTTP_RESPONSE HttpResponse,
    IN PHTTP_CACHE_POLICY CachePolicy OPTIONAL,
    OUT PULONG BytesSent OPTIONAL,
    _Reserved_ PVOID Reserved1,
    _Reserved_ ULONG Reserved2,
    IN LPOVERLAPPED Overlapped OPTIONAL,
    IN PHTTP_LOG_DATA LogData OPTIONAL
    );
```

The following list is incorrect
```
HttpCreateHttpHandle
HttpCreateRequestQueue
HttpReceiveClientCertificate
HttpCreateServerSession
HttpAddUrl
HttpCreateUrlGroup
HttpPrepareUrl
HttpReceiveHttpRequest
HttpReceiveRequestEntityBody
HttpSendHttpResponse
HttpSendResponseEntityBody
HttpWaitForDisconnect
HttpWaitForDisconnectEx
HttpCancelHttpRequest
HttpWaitForDemandStart
HttpFlushResponseCache
HttpAddFragmentToCache
HttpReadFragmentFromCache
HttpSetServiceConfiguration
HttpUpdateServiceConfiguration
HttpDeleteServiceConfiguration
HttpQueryServiceConfiguration
```

**Comment by mikebattista** [comment]
Windows.Win32.Networking.HttpServer.Apis.HttpAddFragmentToCache : CachePolicy : [In,Out] => [In]
Windows.Win32.Networking.HttpServer.Apis.HttpAddFragmentToCache : DataChunk : [In,Out] => [In]
Windows.Win32.Networking.HttpServer.Apis.HttpAddFragmentToCache : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpCancelHttpRequest : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateHttpHandle : RequestQueueHandle : [In,Out] => [Out]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateRequestQueue : Flags : [In] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateRequestQueue : Name : [Const,In] => [Const,In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateRequestQueue : RequestQueueHandle : [In,Out] => [Out]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateRequestQueue : SecurityAttributes : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateServerSession : ServerSessionId : [In,Out] => [Out]
Windows.Win32.Networking.HttpServer.Apis.HttpCreateUrlGroup : pUrlGroupId : [In,Out] => [Out]
Windows.Win32.Networking.HttpServer.Apis.HttpFlushResponseCache : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpReadFragmentFromCache : ByteRange : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpReadFragmentFromCache : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpReceiveClientCertificate : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpReceiveHttpRequest : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpReceiveRequestEntityBody : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendHttpResponse : BytesSent : [In,Out] => [Optional,Out]
Windows.Win32.Networking.HttpServer.Apis.HttpSendHttpResponse : CachePolicy : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendHttpResponse : HttpResponse : [In,Out] => [In]
Windows.Win32.Networking.HttpServer.Apis.HttpSendHttpResponse : LogData : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendHttpResponse : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : BytesSent : [In,Out] => [Optional,Out]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : EntityChunkCount : [In] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : LogData : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : Reserved1 : [In,Out,Reserved] => [Optional,Reserved]
Windows.Win32.Networking.HttpServer.Apis.HttpSendResponseEntityBody : Reserved2 : [In,Reserved] => [Optional,Reserved]
Windows.Win32.Networking.HttpServer.Apis.HttpWaitForDemandStart : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpWaitForDisconnect : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpWaitForDisconnectEx : Overlapped : [In,Out] => [In,Optional]
Windows.Win32.Networking.HttpServer.Apis.HttpWaitForDisconnectEx : Reserved : [In,Reserved] => [In,Optional,Reserved]
