### ISSUE TITLE
IAssocHandler.IsRecommended should be annotated with CanReturnMultipleSuccessValues

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/win32metadata#918]
## Actual behavior

CsWin32 generates method signature `void IsRecommended();` for 
```
[Guid("F04061AC-1659-4A3F-A954-775AA57FC083"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
public interface IAssocHandler
```
which is invalid per documentation:
```
/// <summary>Indicates whether the application is registered as a recommended handler for the queried file type.</summary>
/// <returns>
/// <para>Type: <b>HRESULT</b> Returns S_OK if the program is recommended; otherwise, S_FALSE.</para>
/// </returns>
```

Win32 metadata project contains only
```
HRESULT IsRecommended();
```

## Expected behavior

IsRecommended correctly returns either HRESULT as-is or returns Windows.Win32.Foundation.BOOL or System.Boolean.

## Repro steps

1. `NativeMethods.txt` content:
```
IAssocHandler
```

### Context

- CsWin32 version:  `0.1.635-beta`
- Target Framework:  `net472`

**Comment by mikebattista** [comment]
@aarnott based on our latest discussion [re:PreserveSig](https://github.com/microsoft/win32metadata/issues/1315#issuecomment-1287275248), how does that change the recommendation here?

**Comment by AArnott** [comment]
The API should have `[CanReturnMultipleSuccessValues]` applied.

**Comment by mikebattista** [comment]
Ok. Thanks.

**Comment by mikebattista** [comment]
Windows.Win32.UI.Shell.IAssocHandler.IsRecommended :  => [CanReturnMultipleSuccessValues]
