### ISSUE TITLE
Missing documentation for WM_ constants and enums

### ISSUE THREAD

**Issue by HavenDV** [microsoft/win32metadata#919]
## Actual behavior

Generated code for WM_CONTEXTMENU:
```cs
internal static partial class PInvoke
{
    internal const uint WM_CONTEXTMENU = 123U;
}
```

## Expected behavior

Should contain documentation like this
https://docs.microsoft.com/en-us/windows/win32/menurc/wm-contextmenu

## Repro steps

1. `NativeMethods.txt` content:
```
WM_CONTEXTMENU
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.1.635-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by mikebattista** [comment]
Constants like these will have the `[Documentation]` attribute with a link to the docs.

**Comment by mikebattista** [comment]
They're also now included in the Win32Docs package that C#/Win32 uses to populate its docs.
