### ISSUE TITLE
Avoid API set names in metadata

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#92]
[The doc](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775098(v=vs.85)) says this function is exported from `urlmon.dll` but the metadata says `ext-ms-win-core-iuri-l1-1-0`. Even if that works up-level, we should prefer the original DLL names as that provides compatibility down-level and "just works" everywhere.

**Comment by DaLynX** [comment]
I am having the same issue with `MiniDumpWriteDump` which is in `DbgHelp.dll` and documented as such but gets linked with `api-ms-win-core-debug-minidump-l1-1-0.dll`.

**Comment by sotteson1** [comment]
The scraper is trying to use the non-api set whenever it exists. It looks like both of these methods have been fixed by that change. Let me know if you see others you think shouldn't be using an api set.
