### ISSUE TITLE
EnumProcesses alias (PSAPI) not generated for K32EnumProcesses

### ISSUE THREAD

**Issue by TheNewJavaman** [microsoft/win32metadata#920]
## Actual behavior

When I add `EnumProcesses` to `NativeMethods.txt`, EnumProcesses isn't generated.

## Expected behavior

The function should be available after building the project.

## Repro steps

1. `NativeMethods.txt` content:
```
EnumProcesses
```

2. `NativeMethods.json` content (if present):
Not present
```json
```

3. Any of your own code that should be shared?
Not relevant
### Context

- CsWin32 version: 0.1.635-beta
- Win32Metadata version (if explicitly set by project): Not set
- Target Framework: net6.0-windows10.0.19041.0
- `LangVersion` (if explicitly set by project): Not set, using project defaults as of February 2022

**Comment by riverar** [comment]
`EnumProcesses` is only an alias on Windows 7 and up. It's not clear to me what OS minver metadata targets. If it doesn't cover Windows Vista, then seems like there's no work to be done here.

**Comment by timsneath** [comment]
When we discussed this last time (https://github.com/microsoft/win32metadata/issues/229), it seemed we were aligned that these _should_ be added. There's some weirdness in the history here, obviously, but the set of K32* prefixed APIs are arbitrary and non-intuitive (how would I know that it's `K32GetPerformanceInfo`) to a user. There's a reason that they're documented without the prefix.

**Comment by riverar** [comment]
These APIs are actually documented in both forms, but I generally agree it's confusing.

Here's my thinking:

We have to resolve what minimum OS version metadata targets, before we can make any decisions on aliases.

If the team says metadata targets Windows Vista and up, then we must consider the missing `EnumProcesses` API as a **bug**. We'd have to make changes to generate metadata for v1 and v2 APIs. (This renders this alias discussion moot as there will be no room for an alias and we'll have to figure out how to resolve that awkward UX.)

If the team says metadata targets Windows 7 (or higher) and up, then the addition of `EnumProcesses` as an alias becomes an **enhancement**. Making changes to emit the entrypoint as outlined by @sotteson1 in https://github.com/microsoft/win32metadata/issues/229#issuecomment-785542754 seems reasonable.

Expected outcome: Metadata minver is Windows 10 and aliases will be added. Developers **cannot** use metadata to target Windows Vista, Windows 7, etc.

@mikebattista @kennykerr @AArnott Thoughts?

**Comment by kennykerr** [comment]
Personally, I'm not too interested in these aliases being added. This could be solved with better docs.

**Comment by AArnott** [comment]
@riverar: the metadata already can express APIs that are unique to specific versions of Windows. We have attributes that designate the Windows version that introduces each API.

**Comment by mikebattista** [comment]
The PSAPI_VERSION 1 definition is the most portable and doesn't contain the K32 prefix. Should we just expose the v1 versions of these APIs and ignore the K32 variants?

**Comment by mikebattista** [comment]
Windows.Win32.System.ProcessStatus.Apis.EmptyWorkingSet added
Windows.Win32.System.ProcessStatus.Apis.EnumDeviceDrivers added
Windows.Win32.System.ProcessStatus.Apis.EnumPageFilesA added
Windows.Win32.System.ProcessStatus.Apis.EnumPageFilesW added
Windows.Win32.System.ProcessStatus.Apis.EnumProcesses added
Windows.Win32.System.ProcessStatus.Apis.EnumProcessModules added
Windows.Win32.System.ProcessStatus.Apis.EnumProcessModulesEx added
Windows.Win32.System.ProcessStatus.Apis.GetDeviceDriverBaseNameA added
Windows.Win32.System.ProcessStatus.Apis.GetDeviceDriverBaseNameW added
Windows.Win32.System.ProcessStatus.Apis.GetDeviceDriverFileNameA added
Windows.Win32.System.ProcessStatus.Apis.GetDeviceDriverFileNameW added
Windows.Win32.System.ProcessStatus.Apis.GetMappedFileNameA added
Windows.Win32.System.ProcessStatus.Apis.GetMappedFileNameW added
Windows.Win32.System.ProcessStatus.Apis.GetModuleBaseNameA added
Windows.Win32.System.ProcessStatus.Apis.GetModuleBaseNameW added
Windows.Win32.System.ProcessStatus.Apis.GetModuleFileNameExA added
Windows.Win32.System.ProcessStatus.Apis.GetModuleFileNameExW added
Windows.Win32.System.ProcessStatus.Apis.GetModuleInformation added
Windows.Win32.System.ProcessStatus.Apis.GetPerformanceInfo added
Windows.Win32.System.ProcessStatus.Apis.GetProcessImageFileNameA added
Windows.Win32.System.ProcessStatus.Apis.GetProcessImageFileNameW added
Windows.Win32.System.ProcessStatus.Apis.GetProcessMemoryInfo added
Windows.Win32.System.ProcessStatus.Apis.GetWsChanges added
Windows.Win32.System.ProcessStatus.Apis.GetWsChangesEx added
Windows.Win32.System.ProcessStatus.Apis.InitializeProcessForWsWatch added
Windows.Win32.System.ProcessStatus.Apis.K32EmptyWorkingSet removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumDeviceDrivers removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumPageFilesA removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumPageFilesW removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumProcesses removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumProcessModules removed
Windows.Win32.System.ProcessStatus.Apis.K32EnumProcessModulesEx removed
Windows.Win32.System.ProcessStatus.Apis.K32GetDeviceDriverBaseNameA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetDeviceDriverBaseNameW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetDeviceDriverFileNameA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetDeviceDriverFileNameW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetMappedFileNameA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetMappedFileNameW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetModuleBaseNameA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetModuleBaseNameW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetModuleFileNameExA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetModuleFileNameExW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetModuleInformation removed
Windows.Win32.System.ProcessStatus.Apis.K32GetPerformanceInfo removed
Windows.Win32.System.ProcessStatus.Apis.K32GetProcessImageFileNameA removed
Windows.Win32.System.ProcessStatus.Apis.K32GetProcessImageFileNameW removed
Windows.Win32.System.ProcessStatus.Apis.K32GetProcessMemoryInfo removed
Windows.Win32.System.ProcessStatus.Apis.K32GetWsChanges removed
Windows.Win32.System.ProcessStatus.Apis.K32GetWsChangesEx removed
Windows.Win32.System.ProcessStatus.Apis.K32InitializeProcessForWsWatch removed
Windows.Win32.System.ProcessStatus.Apis.K32QueryWorkingSet removed
Windows.Win32.System.ProcessStatus.Apis.K32QueryWorkingSetEx removed
Windows.Win32.System.ProcessStatus.Apis.QueryWorkingSet added
Windows.Win32.System.ProcessStatus.Apis.QueryWorkingSetEx added

**Comment by timsneath** [comment]
Splendid! Thanks!

**Comment by riverar** [comment]
I re-opened this--the K32 variants are newer and are what users should be calling. By only including the non-K32 variants we've doomed folks to pre-Windows 7 code which is not correct.

**Comment by mikebattista** [comment]
The logic for the change still stands. These are documented without the prefix and the aliases effectively define them without the prefix everywhere.

**Comment by riverar** [comment]
How about something like this? https://github.com/microsoft/win32metadata/commit/21bb0c97365be0577616961f9876026ea3da8692
(I haven't resolved the `--exclude` not working here resulting in duplicate structures.)

This change would emit all K32* variants into the `Windows.Win32.System.ProcessStatus` namespace, and put the older variants into `Windows.Win32.System.ProcessStatus.Legacy`. I recognize this is a bit confusing for folks that land [on the docs](https://learn.microsoft.com/windows/win32/api/psapi/nf-psapi-enumprocesses) but the docs are old and use a C/C++ lens to describe language neutral APIs. I think forcing the users to unlock the .Legacy namespace to hit psapi.dll is a better _default_ in the long run.

Open to everyone's thoughts of course.

**Comment by mikebattista** [comment]
I'm not sure about a Legacy namespace as the unprefixed variants are the primary way to call the APIs to many.

I'm curious, though, if you use a second partition to emit the K32 APIs like you did, but then assign/remap them back to the ProcessStatus namespace, does that emit both variants in the ProcessStatus namespace? I'd be more open to emitting both variants in the ProcessStatus namespace.

You could also use the second partition to generate the C# definitions, then copy those K32 definitions to a manual file inside the ProcessStatus namespace for the same effect.

**Comment by kennykerr** [comment]
I'd be happy with both K32 and non-K32 functions living in the same namespace. Folks comfortable with whichever variant (both of which are documented) can easily find and use that variant. That at least ensures that the metadata fully describes all functions.

**Comment by riverar** [comment]
> I'm curious, though, if you use a second partition to emit the K32 APIs like you did, but then assign/remap them back to the ProcessStatus namespace, does that emit both variants in the ProcessStatus namespace? I'd be more open to emitting both variants in the ProcessStatus namespace.

Hm, let me try that.

**Comment by riverar** [comment]
Got both partitions emitting into the namespace, no remapping needed. https://github.com/microsoft/win32metadata/pull/1515

This puts all the APIs into `Windows.Win32.System.ProcessStatus`.

**Comment by mikebattista** [comment]
Excellent. Thanks!
