### ISSUE TITLE
Incorrect type in some DX types

### ISSUE THREAD

**Issue by hntd187** [microsoft/win32metadata#924]
Already discussed at https://github.com/microsoft/windows-rs/issues/1741 some of these types are u32 for inputs but they should be the related structs . 

```
D3D11_TEXTURE2D_DESC1
D3D11_TEXTURE3D_DESC1
D3D11_BUFFER_DESC
D3D11_TEXTURE1D_DESC
D3D11_TEXTURE2D_DESC
D3D11_TEXTURE3D_DESC
```

They all should have `D3D11_BIND_FLAG` instead of u32.

**Comment by mikebattista** [comment]
Windows.Win32.Graphics.Direct3D11.D3D11_BUFFER_DESC.BindFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_BIND_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_BUFFER_DESC.CPUAccessFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_CPU_ACCESS_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_BUFFER_DESC.MiscFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_RESOURCE_MISC_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE1D_DESC.BindFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_BIND_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE1D_DESC.CPUAccessFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_CPU_ACCESS_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE1D_DESC.MiscFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_RESOURCE_MISC_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC.BindFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_BIND_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC.CPUAccessFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_CPU_ACCESS_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC.MiscFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_RESOURCE_MISC_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE2D_DESC1.BindFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_BIND_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE2D_DESC1.CPUAccessFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_CPU_ACCESS_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE2D_DESC1.MiscFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_RESOURCE_MISC_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC1.BindFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_BIND_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC1.CPUAccessFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_CPU_ACCESS_FLAG
Windows.Win32.Graphics.Direct3D11.D3D11_TEXTURE3D_DESC1.MiscFlags...System.UInt32 => Windows.Win32.Graphics.Direct3D11.D3D11_RESOURCE_MISC_FLAG
