### ISSUE TITLE
WinUsb_* APIs missing attribute DllImport(SetLastError=true)

### ISSUE THREAD

**Issue by Thog** [microsoft/win32metadata#925]
As per documentation of [winusb.h](https://docs.microsoft.com/en-us/windows/win32/api/winusb/), when ``WinUsb_*`` APIs report an error, ``GetLastError`` can be used to get the error code.

However, current metadatas don't ``SetLastError`` to true rendering those APIs unusable.

NOTE: The only exception to the rule here is ``WinUsb_Free``.

**Comment by mikebattista** [comment]
Windows.Win32.Devices.Usb.Apis.WinUsb_Initialize : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetAssociatedInterface : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetDescriptor : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_QueryInterfaceSettings : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_QueryDeviceInformation : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_SetCurrentAlternateSetting : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetCurrentAlternateSetting : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_QueryPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_QueryPipeEx : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_SetPipePolicy : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetPipePolicy : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ReadPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_WritePipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ControlTransfer : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ResetPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_AbortPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_FlushPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_SetPowerPolicy : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetPowerPolicy : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetOverlappedResult : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ParseConfigurationDescriptor : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ParseDescriptors : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetCurrentFrameNumber : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetAdjustedFrameNumber : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_RegisterIsochBuffer : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_UnregisterIsochBuffer : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_WriteIsochPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ReadIsochPipe : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_WriteIsochPipeAsap : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_ReadIsochPipeAsap : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows8.1)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows8.1)]
Windows.Win32.Devices.Usb.Apis.WinUsb_StartTrackingForTimeSync : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows10.0.10240)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows10.0.10240)]
Windows.Win32.Devices.Usb.Apis.WinUsb_GetCurrentFrameNumberAndQpc : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows10.0.10240)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows10.0.10240)]
Windows.Win32.Devices.Usb.Apis.WinUsb_StopTrackingForTimeSync : [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False),SupportedOSPlatform(windows10.0.10240)] => [DllImport(WINUSB,ExactSpelling=True,PreserveSig=False,SetLastError=True),SupportedOSPlatform(windows10.0.10240)]
