### ISSUE TITLE
`WSAAddressToStringA` return type mismatch

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#929]
According to metadata, this function returns `int` but the error codes it returns are actually contained within the `WSA_ERROR` enum. Perhaps the signature could be updated to make error handling more concise.

**Comment by taufikrh** [comment]
Look like the syntax is correct. We should call [WSAGetLastError](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsagetlasterror) to get extended error code.

[WSAAddressToStringA Return value](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaaddresstostringa#return-value)

**Comment by kennykerr** [comment]
Good catch, I missed that in the docs.
