### ISSUE TITLE
Missing CreateUri flags

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#93]
While the [CreateUri](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775098(v=vs.85)) function is present in metadata, none of the constants (like `Uri_CREATE_ALLOW_RELATIVE`) needed to call this function appear to be present.

**Comment by sotteson1** [comment]
This was fixed a while ago.
