### ISSUE TITLE
SetupDiGetClassDevs should return a typedef handle

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#930]
Per the [docs for the method](https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw), the `SetupDiGetClassDevs` method should have metadata indicating that it returns a typedef struct for a handle that is released with [SetupDiDestroyDeviceInfoList](https://docs.microsoft.com/en-us/windows/desktop/api/setupapi/nf-setupapi-setupdidestroydeviceinfolist). 
At present, it returns `void*`.

**Comment by taufikrh** [comment]
Looks like it's fixed in [#856](https://github.com/microsoft/win32metadata/issues/856)

**Comment by AArnott** [comment]
Duplicate of #856
