### ISSUE TITLE
IDirectorySearch is missing typedef handle for CloseSearchHandle

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#931]
The `IDirectorySearch` interface has several members that produce or consume a handle that is ultimately released via [CloseSearchHandle](https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-idirectorysearch-closesearchhandle). The metadata should represent this handle via an attributed typedef struct so that projections can facilitate releasing the memory (e.g. CsWin32 uses SafeHandles).

**Comment by mikebattista** [comment]
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.ExecuteSearch : phSearchResult...IntPtr* => ADS_SEARCH_HANDLE*
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.AbandonSearch : phSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.GetFirstRow : hSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.GetNextRow : hSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.GetPreviousRow : hSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.GetNextColumnName : hSearchHandle...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.GetColumn : hSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.IDirectorySearch.CloseSearchHandle : hSearchResult...IntPtr => ADS_SEARCH_HANDLE
Windows.Win32.Networking.ActiveDirectory.ADS_SEARCH_HANDLE not found in 1st winmd

**Comment by mikebattista** [comment]
Autotype was generated with https://github.com/microsoft/win32metadata/commit/f0e58e5da7b4e62a363dbb94897e2468348448c5. Will not be implementing #982 so this type won't have a RAIIFree API.
