### ISSUE TITLE
Windows.Win32.Interop.dll not updated

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#936]
The version of the interop DLL in Scripts\BaselineWinmd is missing newly added attributes such as `Windows.Win32.Interop.InvalidHandleValueAttribute`. 

Compare the supplied version (10.2.x.y):
![image](https://user-images.githubusercontent.com/2319867/168962830-53f70fb6-16ce-4402-a6fc-90edbc6f2c1a.png)

with a manually generated version (23.0.x.y):
![image](https://user-images.githubusercontent.com/2319867/168962866-ce2b2bbd-23c8-4e99-8443-67e43ef59be0.png)

**Comment by sotteson1** [comment]
We no longer keep around a baseline .winmd, and this file has been deleted too.
