### ISSUE TITLE
ETW API pain points

### ISSUE THREAD

**Issue by nico-abram** [microsoft/win32metadata#937]
I've been using the ETW API, and I found a few things that seem odd in the generated bindings. I'm not sure if these are windows-rs problems, or metadata problems. First:

 - `windows::Win32::System::SystemServices::SE_SYSTEM_PROFILE_NAME` and other strings next to it are `&str`'s, but the APIs that it's used with require a null terminator, so I had to manually add it (For example `LookupPrivilegeValueA`)
 - Same thing for `windows::Win32::System::Diagnostics::Etw::KERNEL_LOGGER_NAMEA`

That seemed like the biggest problem and the only thing I encountered that clearly looks wrong. Then there's some things that surprised me and could maybe be improved but that are not necessarily wrong:

- [x]  `windows::Win32::System::Diagnostics::Etw::TraceSetInformation` returns a u32. This is what it is documented as returning in https://docs.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-tracesetinformation but since the return value must be checked against ERROR_SUCCESS which in windows-rs is a separate WIN32_ERROR type, it makes things a bit awkward
- [x] Same thing for `windows::Win32::System::Diagnostics::Etw::ControlTraceA` and `StartTraceA`
- [x] Trace session handle use a u64, for example in `StartTraceA` and `ControlTraceA`. On msdn they're documented as using "TRACEHANDLE" which probably typedefs to that. I'm not sure if it'd be a good idea to add a TRACEHANDLE wrapper type (Like `HANDLE`), but I'm mentioning in case that's desireable.
- [x] I was not able to find the GUIDs from https://docs.microsoft.com/en-us/windows/win32/etw/nt-kernel-logger-constants defined anywhere in windows-rs, so I just manually defined them.
- [x] I was not able to find the ETW trace event type constants anywhere in windows-rs. For example, https://docs.microsoft.com/en-us/windows/win32/etw/stackwalk mentions `EVENT_ENABLE_PROPERTY_STACK_TRACE` should be 32.
- [x] I was not able to find the `ClientContext` clock resolution constants from https://docs.microsoft.com/en-us/windows/win32/etw/wnode-header anywhere in windows-rs. I'm not sure they're even present in the headers.
  - Won't Fixing this for now. This ClientContext can be used in other contexts so an enum just for ETW would not cover all scenarios. Will keep loosely typed for now.
- [x] I was not able to find the event structs anywhere, for example https://docs.microsoft.com/en-us/windows/win32/etw/stackwalk-event and https://docs.microsoft.com/en-us/windows/win32/etw/sampledprofile

**Comment by idigdoug** [comment]
One additional more here. Etw unfortunately used TRACEHANDLE with two different apis that sound related but are not. StartTrace and ControlTrace use the same meaning of TRACEHANDLE, which is distinct from the handle of OpenTrace/ProcessTrace/CloseTrace. A projection would hopefully fix this.

**Comment by mikebattista** [comment]
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.QueryAllTracesW : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.QueryAllTracesA : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTrace : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx2 : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.EnumerateTraceGuidsEx : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.TraceSetInformation : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.TraceQueryInformation : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.CreateTraceInstanceId : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.TraceEvent : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.EnumerateTraceGuids : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.ProcessTrace : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.CloseTrace : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceProcessingHandle : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.SetTraceCallback : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.RemoveTraceCallback : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessage : return...UInt32 => WIN32_ERROR
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessageVa : return...UInt32 => WIN32_ERROR

**Comment by mikebattista** [comment]
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.AddLogfileTraceStream : TraceHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.AddRealtimeTraceStream : TraceHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.CreateEventInstance : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.TRACEHANDLE not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceW : TraceHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceA : TraceHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceW : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceA : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceW : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceA : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceW : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceA : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceW : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceA : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceW : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceA : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTrace : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx2 : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceSetInformation : SessionHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceQueryInformation : SessionHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceEvent : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceEventInstance : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.RegisterTraceGuidsW : RegistrationHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.RegisterTraceGuidsA : RegistrationHandle...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.UnregisterTraceGuids : RegistrationHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceLoggerHandle : return...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceEnableLevel : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceEnableFlags : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.OpenTraceW : return...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ProcessTrace : HandleArray...UInt64* => TRACEHANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.CloseTrace : TraceHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceProcessingHandle : ProcessingHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.OpenTraceA : return...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessage : LoggerHandle...UInt64 => TRACEHANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessageVa : LoggerHandle...UInt64 => TRACEHANDLE

**Comment by mikebattista** [comment]
Windows.Win32.System.Diagnostics.Etw.Apis.ALPCGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.DiskIoGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.FileIoGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.ImageLoadGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.PageFaultGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.PerfInfoGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.ProcessGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.RegistryGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.SplitIoGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.TcpIpGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.ThreadGuid not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.UdpIpGuid not found in 1st winmd

**Comment by mikebattista** [comment]
Windows.Win32.System.Diagnostics.Etw.TRACEHANDLE not found in 2nd winmd
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.AddLogfileTraceStream : TraceHandle...TRACEHANDLE* => RELOGSTREAM_HANDLE*
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.AddRealtimeTraceStream : TraceHandle...TRACEHANDLE* => RELOGSTREAM_HANDLE*
Windows.Win32.System.Diagnostics.Etw.ITraceRelogger.CreateEventInstance : TraceHandle...TRACEHANDLE => RELOGSTREAM_HANDLE
Windows.Win32.System.Diagnostics.Etw.PROCESSTRACE_HANDLE not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.CONTROLTRACE_HANDLE not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.RELOGSTREAM_HANDLE not found in 1st winmd
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceW : TraceHandle...TRACEHANDLE* => CONTROLTRACE_HANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.StartTraceA : TraceHandle...TRACEHANDLE* => CONTROLTRACE_HANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceW : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.StopTraceA : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceW : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceA : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceW : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.UpdateTraceA : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceW : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.FlushTraceA : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceW : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ControlTraceA : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTrace : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.EnableTraceEx2 : TraceHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceSetInformation : SessionHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceQueryInformation : SessionHandle...TRACEHANDLE => CONTROLTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceEvent : TraceHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.TraceEventInstance : TraceHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.RegisterTraceGuidsW : RegistrationHandle...TRACEHANDLE* => UInt64*
Windows.Win32.System.Diagnostics.Etw.Apis.RegisterTraceGuidsA : RegistrationHandle...TRACEHANDLE* => UInt64*
Windows.Win32.System.Diagnostics.Etw.Apis.UnregisterTraceGuids : RegistrationHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceLoggerHandle : return...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceEnableLevel : TraceHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.GetTraceEnableFlags : TraceHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.OpenTraceW : return...TRACEHANDLE => PROCESSTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.ProcessTrace : HandleArray...TRACEHANDLE* => PROCESSTRACE_HANDLE*
Windows.Win32.System.Diagnostics.Etw.Apis.CloseTrace : TraceHandle...TRACEHANDLE => PROCESSTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.QueryTraceProcessingHandle : ProcessingHandle...TRACEHANDLE => PROCESSTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.OpenTraceA : return...TRACEHANDLE => PROCESSTRACE_HANDLE
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessage : LoggerHandle...TRACEHANDLE => UInt64
Windows.Win32.System.Diagnostics.Etw.Apis.TraceMessageVa : LoggerHandle...TRACEHANDLE => UInt64

**Comment by mikebattista** [comment]
@idigdoug please review the above diff.

**Comment by idigdoug** [comment]
Looks good.

**Comment by kennykerr** [comment]
Note that the `windows` and `windows-sys` crates now provide the original encoding for string constants: https://github.com/microsoft/windows-rs/pull/2101

Most or all of the remaining issues appear to be resolved and have made their way into the Rust project.

**Comment by mikebattista** [comment]
Thanks. Will close this out then.
