### ISSUE TITLE
Missing CSecureChannelClient in Media::DeviceManager

### ISSUE THREAD

**Issue by quinnjr** [microsoft/win32metadata#939]
It looks like the current metadata generation of the `Media::DeviceManager` module does not include `CSecureChannelClient`, which I'm trying to use to authenticate my application for using the Media Device Manager. 

Following the guide currently found at: https://docs.microsoft.com/en-us/windows/win32/wmdm/authenticating-the-application

**Comment by mikebattista** [comment]
That's a C++ class which the metadata doesn't support.
