### ISSUE TITLE
missing C runtime routines (CRT) from io.h: _get_osfhandle, _open_osfhandle

### ISSUE THREAD

**Issue by matu3ba** [microsoft/win32metadata#945]
Looking into winmd with ILSpy, I see that the routines of `ioapiset.h` (GetOverlappedResult, CancelIoEx, CancelSynchronousIo) are included in `Windows.Win32.Systems.IO`.
However, the file handling routines (in `io.h`) like `_get_osfhandle`, `_fileno` are not.

These are part of the [C runtime library](https://docs.microsoft.com/en-us/cpp/c-runtime-library/file-handling?view=msvc-170).
This is very unfortunate, because sometimes serializing and deserializing file handles (to file descriptors) is necessary.
In my case to provide non-standard pipes to a child process.

1. As these are relative fundamental things: Is there any program or way to get implementation and test coverage?
2. Is there an overview, what users of win32metadata can expect to be (eventually) fully covered and which parts not? The roadmap is old (predates 2022) and does not include a measurable status nor planned status to manage user expectations.

related issue https://github.com/marlersoft/zigwin32/issues/13
related pr https://github.com/ziglang/zig/pull/11701

Sidenode: I am abit surprised that the filename of CRT stuff is not reserved in this case.

**Comment by mikebattista** [comment]
CRT is separate from the Windows SDK and is not in scope for this metadata.
