### ISSUE TITLE
LPBSTR parameters should retain metadata about their being BSTRs

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#947]
The [`QueryPathOfRegTypeLib` function](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-querypathofregtypelib) is documented as having a last parameter that is an `[out] LPBSTR`. But in the metadata, we just get `[out] uint16**` as the parameter type. This blocks projections from providing friendly methods (e.g. returning a `string`).
Can the metadata be fixed as has been done with other APIs that accept BSTR for example, so that projections can offer better APIs?

**Comment by AArnott** [comment]
Whoa, that's quite the doc mistake. How do you know it's a doc bug? 
I *was* surprised that if the caller was supposed to allocate the string that the docs didn't indicate how large the buffer must be or that the length wasn't passed in as an argument.

**Comment by kennykerr** [comment]
> How do you know it's a doc bug?

I looked up the implementation. 😏

**Comment by AArnott** [comment]
I sent feedback on that doc. Do you suppose they should use `SysFreeString`?

**Comment by mikebattista** [comment]
Per feedback from @kennykerr, remapping all LPBSTR occurrences to BSTR* would be better than introducing PBSTR.
