### ISSUE TITLE
IRunningObjectTable::Register first parameter should be an enum

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#948]
The [Register](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-irunningobjecttable-register) method should use an enum for its first parameter.

**Comment by mikebattista** [comment]
Windows.Win32.System.Com.IRunningObjectTable.Register : grfFlags...UInt32 => ROT_FLAGS
Windows.Win32.System.Com.ROT_FLAGS not found in 1st winmd
Windows.Win32.System.SystemServices.Apis.ROTFLAGS_REGISTRATIONKEEPSALIVE not found in 2nd winmd
Windows.Win32.System.SystemServices.Apis.ROTFLAGS_ALLOWANYCLIENT not found in 2nd winmd
