### ISSUE TITLE
Feature request: Missing function LookupAccountSidLocal

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/win32metadata#950]
### Motivation

[lookupaccountsidlocalw](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountsidlocalw)

The functions is similar to [LookupAccountSid](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountsidw) which does exist, but it restricts it to the local machine.

### Drawbacks

None

### Rationale and alternatives

It can be preferred for compared to LookupAccountSid  for multiple cases (simplicity, security for example),
even though you can manually restrict it with this function it seems unnecessary as there already is a function to do just that.

### Additional context

Couldn't find anything, it's odd it's not already implemented, I am hoping it just happens to have gone under the radar and it's a simple matter to just add it:)

**Comment by mikebattista** [comment]
Windows.Win32.Security.Apis.LookupAccountNameLocalA added
Windows.Win32.Security.Apis.LookupAccountNameLocalW added
Windows.Win32.Security.Apis.LookupAccountSidLocalA added
Windows.Win32.Security.Apis.LookupAccountSidLocalW added

**Comment by kennykerr** [comment]
Mike, did you actually check that this is correct? ADVAPI32.dll doesn't appear to export these functions.

**Comment by mikebattista** [comment]
I followed the docs. What binary do you think they come from?

**Comment by kennykerr** [comment]
See my comment here: https://github.com/microsoft/windows-rs/issues/2169#issuecomment-1317803616
