### ISSUE TITLE
CERT_INFO.rgExtension metadata isn't consistent with docs

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#951]
The metadata describes `CERT_INFO.rgExtension` as a pointer to a `CERT_EXTENSION` struct. But [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/ns-wincrypt-cert_info) indicates the field is "An array of pointers to [CERT_EXTENSION](https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/ns-wincrypt-cert_extension) structures", suggesting this last field is actually an inline array of pointers instead of just one pointer.

**Comment by riverar** [comment]
Perhaps we should add another field to `NativeArrayInfoAttribute` to track which struct field contains length information (e.g. `CountFieldName`)
