### ISSUE TITLE
PROCESS_MACHINE_INFORMATION.ProcessMachine should be typed as an enum

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#953]
[The docs](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-process_machine_information) indicate that the `PROCESS_MACHINE_INFORMATION.ProcessMachine` field is one of several values defined as constants.

**Comment by AArnott** [comment]
It looks like an IMAGE_FILE_MACHINE enum already exists. It just isn't used by this field.

**Comment by mikebattista** [comment]
Windows.Win32.System.Diagnostics.Debug.IMAGE_FILE_MACHINE not found in 2nd winmd
Windows.Win32.System.Threading.PROCESS_MACHINE_INFORMATION.ProcessMachine...System.UInt16 => Windows.Win32.System.SystemInformation.IMAGE_FILE_MACHINE
Windows.Win32.System.Diagnostics.Debug.IMAGE_FILE_HEADER.Machine...Windows.Win32.System.Diagnostics.Debug.IMAGE_FILE_MACHINE => Windows.Win32.System.SystemInformation.IMAGE_FILE_MACHINE
Windows.Win32.System.SystemInformation.IMAGE_FILE_MACHINE not found in 1st winmd
Windows.Win32.System.SystemInformation.Apis.GetSystemWow64Directory2A : ImageFileMachineType...UInt16 => IMAGE_FILE_MACHINE
Windows.Win32.System.SystemInformation.Apis.GetSystemWow64Directory2W : ImageFileMachineType...UInt16 => IMAGE_FILE_MACHINE
Windows.Win32.System.SystemInformation.Apis.IsWow64GuestMachineSupported : WowGuestMachine...UInt16 => IMAGE_FILE_MACHINE
Windows.Win32.System.Threading.Apis.IsWow64Process2 : pProcessMachine...UInt16* => IMAGE_FILE_MACHINE*
Windows.Win32.System.Threading.Apis.IsWow64Process2 : pNativeMachine...UInt16* => IMAGE_FILE_MACHINE*
