### ISSUE TITLE
`WAVEFORMATEX`, `VIDEOINFOHEADER`, `BITMAPINFOHEADER` duplicated

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#954]
These three structs are listed in both Windows.Win32.Media.DeviceManager and Windows.Win32.Media.Audio (the former with a `_` prefix). They are the same struct, and should be deduplicated.

**Comment by mikebattista** [comment]
Windows.Win32.Media.DeviceManager._WAVEFORMATEX not found in 2nd winmd
Windows.Win32.Media.DeviceManager._BITMAPINFOHEADER not found in 2nd winmd
Windows.Win32.Media.DeviceManager._VIDEOINFOHEADER not found in 2nd winmd
Windows.Win32.Media.DeviceManager.IWMDMStorage.SetAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMStorage.GetAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMStorage2.SetAttributes2 : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMStorage2.SetAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IWMDMStorage2.GetAttributes2 : pAudioFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMStorage2.GetAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IWMDMOperation.GetObjectAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMOperation.SetObjectAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMOperation2.SetObjectAttributes2 : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMOperation2.SetObjectAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IWMDMOperation2.GetObjectAttributes2 : pAudioFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IWMDMOperation2.GetObjectAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IWMDMDevice.GetFormatSupport : ppFormatEx..._WAVEFORMATEX** => WAVEFORMATEX**
Windows.Win32.Media.DeviceManager.IWMDMDevice2.GetFormatSupport2 : ppAudioFormatEx..._WAVEFORMATEX** => WAVEFORMATEX**
Windows.Win32.Media.DeviceManager.IWMDMDevice2.GetFormatSupport2 : ppVideoFormatEx..._VIDEOINFOHEADER** => VIDEOINFOHEADER**
Windows.Win32.Media.DeviceManager.IWMDMDeviceControl.Record : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPDevice.GetFormatSupport : pFormatEx..._WAVEFORMATEX** => WAVEFORMATEX**
Windows.Win32.Media.DeviceManager.IMDSPDevice2.GetFormatSupport2 : ppAudioFormatEx..._WAVEFORMATEX** => WAVEFORMATEX**
Windows.Win32.Media.DeviceManager.IMDSPDevice2.GetFormatSupport2 : ppVideoFormatEx..._VIDEOINFOHEADER** => VIDEOINFOHEADER**
Windows.Win32.Media.DeviceManager.IMDSPDeviceControl.Record : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage.SetAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage.GetAttributes : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage.CreateStorage : pFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.CreateStorage2 : pAudioFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.CreateStorage2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.SetAttributes2 : pAudioFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.SetAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.GetAttributes2 : pAudioFormat..._WAVEFORMATEX* => WAVEFORMATEX*
Windows.Win32.Media.DeviceManager.IMDSPStorage2.GetAttributes2 : pVideoFormat..._VIDEOINFOHEADER* => VIDEOINFOHEADER*
