### ISSUE TITLE
Better support for generating (flagged) enums

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#958]
**Is your feature request related to a problem? Please describe.**
I found this happens with various methods, but one example is ```CM_Get_DevNode_PropertyW``` (https://docs.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_get_devnode_propertyw). This has an out parameter of ```DEVPROPTYPE```. With CsWin32 this gets generated as an uint. This is not as convenient as it can be.  The syntax on MSDN has a ```DEVPROPTYPE``` as output type, and while these types are not originally defined as an enum, they would be useful to be generated as an enum in C#.

**Describe the solution you'd like**
Some check would be useful to see if there are defined fields for such properties and converting them to (flagged) enums.

**Comment by KalleOlaviNiemitalo** [comment]
`DEVPROP_TYPEMOD_ARRAY`, `DEVPROP_TYPEMOD_LIST`, `DEVPROP_TYPE_EMPTY`, and other constants that start with `DEVPROP_TYPE_` should be members.

`DEVPROP_MASK_TYPE` and `DEVPROP_MASK_TYPEMOD` could be either members or free constants, but they should have this type.

Not sure about `MAX_DEVPROP_TYPE` and `MAX_DEVPROP_TYPEMOD`. Perhaps better not to make them members.

**Comment by Nuklon** [comment]
> It looks like you're saying the `DEVPROPTYPE *PropertyType` parametr is typed as `uint*` but would be better if `DEVPROPTYPE` were actually used, and declared as an enum type. What would its members be? All constants beginning with `DEVPROP_TYPE`?

Yes, correct. For example:
```csharp
 public enum DEVPROP_TYPE : uint
 {
        DEVPROP_TYPE_EMPTY = 0x00000000,
        DEVPROP_TYPE_NULL = 0x00000001,
        ...
}
```

There are a lot of functions and types where variables aren't generated as enums (in other apis also, such as IpHlpApi). For example https://docs.microsoft.com/en-us/windows/win32/api/ws2ipdef/ns-ws2ipdef-sockaddr_inet `si_family` is generated as ushort, whereas it could generate an ADDRESS_FAMILY enum. 

I don't have a list for all these methods but there are a lot of them. I think most can be found by comparing the declared type vs generated type. For example with the SOCKADDR_INET the type says ADDRESS_FAMILY but is generated as ushort. Also with CM_Get_DevNode_PropertyW the type says DEVPROPTYPE whereas uint is generated.

**Comment by AArnott** [comment]
> could be either members or free constants, but they should have this type

If the set of constants in the enum isn't fixed or well-defined, we may do better to use a typedef struct for it. There's no way for a constant to be typed as an enum without being a member of that enum. But we _do_ achieve something like that with a typedef struct. In CsWin32 we even (nowadays) define such constants as members of the typedef struct, so it feels something like an enum, but without conveying the idea of a closed set. This works well for HRESULT, for example.

**Comment by Nuklon** [comment]
A struct is not as convenient though as an enum as you miss a useful ToString for example (especially when flagged) and if you want to print the native constant name, you'd have to do a lot of comparisons with all possible constants. Almost all of these members do have their possible values well defined, such as the ones I've linked to. You can pass in different value than the defined values when you cast it, although there's also a possibility to also generate an uint/ushort/etc export for such cases.

**Comment by KalleOlaviNiemitalo** [comment]
> There's no way for a constant to be typed as an enum without being a member of that enum.

Is that a winmd restriction? ECMA-335 (CLI) and ECMA-334 (C#) have no such requirement.

**Comment by AArnott** [comment]
Oh, I guess it's possible via a cast in the constant definition. What's more, we already have rather bizarre constant definitions in the metadata where casts would be required in C# to make it valid. Still, I think it would be weird to define an enum but intentionally leave out valid values from it.

**Comment by KalleOlaviNiemitalo** [comment]
`MAX_DEVPROP_TYPE` and `MAX_DEVPROP_TYPEMOD` are sentinel values. [Enum Design](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/enum) recommends not including those, but I don't know whether that guidance applies to WinMD.

**Comment by Nuklon** [comment]
Another example is CfgMgr32, such as https://docs.microsoft.com/en-us/windows/win32/api/cfgmgr32/ns-cfgmgr32-io_des#members, the IOD_DesFlags are just generated as uint. This also happens with all the other _DES and _RANGE structs.

**Comment by mikebattista** [comment]
How to contribute to enums is covered at https://github.com/microsoft/win32metadata/blob/main/CONTRIBUTING.md#Enums if you'd like to contribute. These are good first issues for getting started with the repo.
