### ISSUE TITLE
IShellFolder.GetDisplayNameOf flags uint => SHGDNF

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#960]
From Rust Discord (#windows-dev)

* IShellFolder.GetDisplayNameOf could have its `flags` parameter better typed
* `_SHGDNF` also appears to be incorrectly typed as `int` (should be `uint`) per `shobjidl.h`:
```cpp
typedef DWORD SHGDNF;
```

**Comment by mikebattista** [comment]
Windows.Win32.UI.Shell._SHGDNF not found in 2nd winmd
Windows.Win32.UI.Shell.IShellFolder.GetDisplayNameOf : uFlags...UInt32 => SHGDNF
Windows.Win32.UI.Shell.IShellFolder.SetNameOf : uFlags...UInt32 => SHGDNF
Windows.Win32.UI.Shell.SHGDNF not found in 1st winmd
