### ISSUE TITLE
HIDP_ constants missing from metadata

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#964]
@Slion reports at https://github.com/microsoft/CsWin32/discussions/583

> I'm trying to use [HidP_GetUsageValueArray](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/nf-hidpi-hidp_getusagevaluearray). The returned value is declared as NTSTATUS, are the constant values it can take declared somewhere? If I put them in NativeMethods.txt is says it can't find them.

Indeed, it appears that none of the return values documented for this API are declared in the metadata. Since the method itself _is_ in the metadata, it seems the return values should be as well.

**Comment by Slion** [comment]
Looks like the DIGCF_* flags are missing too.

See:
https://github.com/microsoft/CsWin32/discussions/590
https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw

**Comment by Slion** [comment]
While you are at it looks like DEVPROP_TYPE* are missing too.

**Comment by KalleOlaviNiemitalo** [comment]
Adding DEVPROP_TYPE* was requested in <https://github.com/microsoft/win32metadata/issues/958>.

**Comment by elachlan** [comment]
Found them in the headers, I think.
[generation\WinSDK\RecompiledIdlHeaders\shared\hidpi.h](https://github.com/microsoft/win32metadata/blob/fb4ec4180a7f6df1a4649ee869ffa017406a89ed/generation/WinSDK/RecompiledIdlHeaders/shared/hidpi.h#L2000-L2032)

**Comment by elachlan** [comment]
This one will be hard I think since they are macros:
```C
#define HIDP_ERROR_CODES(SEV, CODE) \
        ((NTSTATUS) (((SEV) << 28) | (FACILITY_HID_ERROR_CODE << 16) | (CODE)))

#define HIDP_STATUS_SUCCESS                  (HIDP_ERROR_CODES(0x0,0))
```

Does clangsharp handle that?

**Comment by mikebattista** [comment]
The [ConstantsScraper](https://github.com/microsoft/win32metadata/blob/main/sources/MetadataUtils/ConstantsScraper.cs) handles this. We'd need to update it to handle this pattern.
