### ISSUE TITLE
Incorrect values in MOUSEHOOKSTRUCTEX_MOUSE_DATA

### ISSUE THREAD

**Issue by HavenDV** [microsoft/win32metadata#965]
## Actual behavior

https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msllhookstruct
```cs
[Flags]
internal enum MOUSEHOOKSTRUCTEX_MOUSE_DATA : uint
{
  XBUTTON1 = 0x00000001,
  XBUTTON2 = 0x00000002,
}
```
The current code assumes use in the form:
```cs
var isXButton1 = value.mouseData.HasFlag(MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON1);
var isXButton2 = value.mouseData.HasFlag(MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON2);
```
But that won't work because the values of the constants are wrong.

Code that works for me at the moment(Because the high-order word is used):
```cs
var specialKey = (((uint)value.mouseData) >> 16) switch
{
    1 => Key.MouseXButton1,
    2 => Key.MouseXButton2,
    _ => Key.MouseNone,
};
```

## Expected behavior
```cs
var isXButton1 = value.mouseData.HasFlag(MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON1);
var isXButton2 = value.mouseData.HasFlag(MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON2);
```
should return correct values

## Repro steps

1. `NativeMethods.txt` content:
```
MSLLHOOKSTRUCT
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.1.635-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by mikebattista** [comment]
So we just need to change the type of the enum to ushort and then remove it from being applied to the struct field (since it's only part of the value)?

**Comment by AArnott** [comment]
You know now that read the docs again, I see this that these 2 constants are only used in the high order word. So another 'fix' would be to bit-shift the values and call it a day:

```cs
[Flags]
public enum MOUSEHOOKSTRUCTEX_MOUSE_DATA : uint
{
	XBUTTON1 = 0x10000,
	XBUTTON2 = 0x20000,
}
```

That would allow folks to skip the bit shifting and just look for the flags. That would be easier.

But IMO we shouldn't do that. That would significantly deviate the usage pattern from the docs and the headers.

So yes, as you say @mikebattista, I believe we should stop declaring the enum entirely, and change the constants to be declared as `ushort` constants.

**Comment by mikebattista** [comment]
Windows.Win32.UI.WindowsAndMessaging.Apis.XBUTTON1 added
Windows.Win32.UI.WindowsAndMessaging.Apis.XBUTTON2 added
Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX_MOUSE_DATA removed
Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON1 removed
Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX_MOUSE_DATA.XBUTTON2 removed
Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX.mouseData...Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX_MOUSE_DATA => System.UInt32
Windows.Win32.UI.WindowsAndMessaging.MSLLHOOKSTRUCT.mouseData...Windows.Win32.UI.WindowsAndMessaging.MOUSEHOOKSTRUCTEX_MOUSE_DATA => System.UInt32
