### ISSUE TITLE
Feature request: Match types of `FOREGROUND_BLUE` etc. with `SetConsoleTextAttributes`

### ISSUE THREAD

**Issue by sunfishcode** [microsoft/win32metadata#967]
### Motivation

[`SetConsoleTextAttribute`](https://docs.rs/windows-sys/latest/windows_sys/Win32/System/Console/fn.SetConsoleTextAttribute.html)' `wattributes` argument is declared with type `u16`.

The [character attributes](https://docs.microsoft.com/en-us/windows/console/console-screen-buffers#character-attributes) that one passes to it, such as [`FOREGROUND_BLUE`](https://docs.rs/windows-sys/latest/windows_sys/Win32/System/Console/constant.FOREGROUND_BLUE.html), are declared with type `u32`.

It would be convenient if these constants were declared with type `u32` to obviate the need for casting.

### Additional context

In the winapi crate, [`FOREGROUND_BLUE`](https://docs.rs/winapi/latest/winapi/um/wincon/constant.FOREGROUND_BLUE.html) is declared with type `WORD` aka `u16`.

**Comment by mikebattista** [comment]
Windows.Win32.System.Console.CONSOLE_SCREEN_BUFFER_INFO.wAttributes...System.UInt16 => Windows.Win32.System.Console.CONSOLE_CHARACTER_ATTRIBUTES
Windows.Win32.System.Console.CONSOLE_SCREEN_BUFFER_INFOEX.wAttributes...System.UInt16 => Windows.Win32.System.Console.CONSOLE_CHARACTER_ATTRIBUTES
Windows.Win32.System.Console.CONSOLE_CHARACTER_ATTRIBUTES not found in 1st winmd
Windows.Win32.System.Console.Apis.FOREGROUND_BLUE not found in 2nd winmd
Windows.Win32.System.Console.Apis.FOREGROUND_GREEN not found in 2nd winmd
Windows.Win32.System.Console.Apis.FOREGROUND_RED not found in 2nd winmd
Windows.Win32.System.Console.Apis.FOREGROUND_INTENSITY not found in 2nd winmd
Windows.Win32.System.Console.Apis.BACKGROUND_BLUE not found in 2nd winmd
Windows.Win32.System.Console.Apis.BACKGROUND_GREEN not found in 2nd winmd
Windows.Win32.System.Console.Apis.BACKGROUND_RED not found in 2nd winmd
Windows.Win32.System.Console.Apis.BACKGROUND_INTENSITY not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_LEADING_BYTE not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_TRAILING_BYTE not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_GRID_HORIZONTAL not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_GRID_LVERTICAL not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_GRID_RVERTICAL not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_REVERSE_VIDEO not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_UNDERSCORE not found in 2nd winmd
Windows.Win32.System.Console.Apis.COMMON_LVB_SBCSDBCS not found in 2nd winmd
Windows.Win32.System.Console.Apis.SetConsoleTextAttribute : wAttributes...UInt16 => CONSOLE_CHARACTER_ATTRIBUTES
