### ISSUE TITLE
SHRegDuplicateHKey return type is incorrect

### ISSUE THREAD

**Issue by zhong-b** [microsoft/win32metadata#973]
msdn:
HKEY SHRegDuplicateHKey(
  [in] HKEY hkey
);

windows-sys:
pub unsafe extern "system" fn SHRegDuplicateHKey(
    hkey: HKEY
) -> WIN32_ERROR

**Comment by riverar** [comment]
Transferred to win32metadata

**Comment by mikebattista** [comment]
Windows.Win32.UI.Shell.Apis.SHRegDuplicateHKey : return...WIN32_ERROR => HKEY
Windows.Win32.UI.Shell.Apis.SHRegGetBoolUSValueA : return...WIN32_ERROR => BOOL
Windows.Win32.UI.Shell.Apis.SHRegGetBoolUSValueW : return...WIN32_ERROR => BOOL
