### ISSUE TITLE
FILE_FLAGS_AND_ATTRIBUTES is missing FILE_FLAG members

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#98]
`FILE_FLAG_DELETE_ON_CLOSE` and other `FILE_FLAG_*` enums are missing from `FILE_FLAGS_AND_ATTRIBUTES`.

See [CreateFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) docs.

**Comment by sotteson1** [comment]
These were fixed a while ago.
