### ISSUE TITLE
Missing access rights enums for synchronization objects

### ISSUE THREAD

**Issue by alexrp** [microsoft/win32metadata#984]
As far as I can tell, all of the access rights specific to synchronization objects are missing enums: https://docs.microsoft.com/en-us/windows/win32/sync/synchronization-object-security-and-access-rights

**Comment by mikebattista** [comment]
Windows.Win32.System.Threading.SYNCHRONIZATION_ACCESS_RIGHTS not found in 1st winmd
Windows.Win32.System.SystemServices.Apis.EVENT_MODIFY_STATE not found in 2nd winmd
Windows.Win32.System.SystemServices.Apis.SEMAPHORE_MODIFY_STATE not found in 2nd winmd
Windows.Win32.System.SystemServices.Apis.TIMER_QUERY_STATE not found in 2nd winmd
Windows.Win32.System.SystemServices.Apis.TIMER_MODIFY_STATE not found in 2nd winmd
Windows.Win32.System.Threading.Apis.MUTEX_MODIFY_STATE not found in 2nd winmd
Windows.Win32.System.Threading.Apis.OpenMutexW : dwDesiredAccess...UInt32 => SYNCHRONIZATION_ACCESS_RIGHTS
Windows.Win32.System.Threading.Apis.OpenEventA : dwDesiredAccess...UInt32 => SYNCHRONIZATION_ACCESS_RIGHTS
Windows.Win32.System.Threading.Apis.OpenEventW : dwDesiredAccess...UInt32 => SYNCHRONIZATION_ACCESS_RIGHTS
Windows.Win32.System.Threading.Apis.OpenSemaphoreW : dwDesiredAccess...UInt32 => SYNCHRONIZATION_ACCESS_RIGHTS
Windows.Win32.System.Threading.Apis.OpenWaitableTimerW : dwDesiredAccess...UInt32 => SYNCHRONIZATION_ACCESS_RIGHTS
