### ISSUE TITLE
ID3D11Device::CheckFeatureSupport pFeatureSupportData is not only [out]

### ISSUE THREAD

**Issue by estchd** [microsoft/win32metadata#985]
According to the [Documentation](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-checkfeaturesupport), the pFeatureSupportData parameter of the ID3D11Device::CheckFeatureSupport function is only used for output.

But, when querying for the D3D11_FEATURE_FORMAT_SUPPORT or D3D11_FEATURE_FORMAT_SUPPORT2 Feature data, the pFeatureSupportData pointer has to point to a [D3D11_FEATURE_DATA_FORMAT_SUPPORT](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_feature_data_format_support) or [D3D11_FEATURE_DATA_FORMAT_SUPPORT2](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_feature_data_format_support2) struct filled with sensible data to select the Format that is queried, making it an [in] parameter as well.

**Comment by mikebattista** [comment]
The metadata appears to reflect the signature in the header. Am I missing something?

Header:
```
HRESULT CheckFeatureSupport(
    D3D11_FEATURE Feature,
    [annotation("_Out_writes_bytes_(FeatureSupportDataSize)")] void* pFeatureSupportData,
    UINT FeatureSupportDataSize );
```

Metadata
```
unsafe HRESULT CheckFeatureSupport([In] D3D11_FEATURE Feature, [Out][MemorySize(BytesParamIndex = 2)] void* pFeatureSupportData, [In] uint FeatureSupportDataSize);
```

**Comment by mikebattista** [comment]
Please clarify why you think a change is required and reactivate if necessary.
