### ISSUE TITLE
`FILE_DISPOSITION_INFO`'s `DeleteFile` boolean renamed to `DeleteFileA`

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#986]
The [`FILE_DISPOSITION_INFO`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_disposition_info) struct is defined as:

```c
typedef struct _FILE_DISPOSITION_INFO {
  BOOLEAN DeleteFile;
} FILE_DISPOSITION_INFO, *PFILE_DISPOSITION_INFO;
```

However the metadata renames the boolean to `DeleteFileA`:

```csharp
public struct FILE_DISPOSITION_INFO
{
	public BOOLEAN DeleteFileA;
}
```

**Comment by mikebattista** [comment]
Not sure what's triggering this. Assigning to @sotteson1.
