### ISSUE TITLE
SignerFreeSignerContext function missing

### ISSUE THREAD

**Issue by virzak** [microsoft/win32metadata#987]
Seems to be missing

https://docs.microsoft.com/en-us/windows/win32/seccrypto/signerfreesignercontext

**Comment by timsneath** [comment]
That's because of [this note in the docs](https://docs.microsoft.com/en-us/windows/win32/seccrypto/signerfreesignercontext):

> This function has no associated header file or import library. To call this function, you must create a user-defined header file and use the [LoadLibrary](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) and [GetProcAddress](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress) functions to dynamically link to Mssign32.dll.

**Comment by mikebattista** [comment]
This whole family of APIs needs to be manually defined if they aren't in the headers. I defined SignerFreeSignerContext as an example with #987 if someone else wants to run with it and define the rest.
