### ISSUE TITLE
Wrong output type for CallNtPowerInformation

### ISSUE THREAD

**Issue by daladim** [microsoft/win32metadata#990]
[`CallNtPowerInformation` original signature](https://docs.microsoft.com/en-us/windows/win32/api/powerbase/nf-powerbase-callntpowerinformation#return-value) says it returns an `NTSTATUS`

However, [its Rust binding](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Power/fn.CallNtPowerInformation.html) returns an int (`i64`, instead of [the proper `NTSTATUS` type](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.NTSTATUS.html))

I haven't digged into win32metadata, but I think I'm creating an issue at the right place. If not, please tell me.

Thanks

**Comment by kennykerr** [comment]
Yes, this is the right place. Thanks for reporting!

**Comment by daladim** [comment]
All right :)

Also, while I'm on it: [PROCESSOR_POWER_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str) is missing a Rust binding as well (whereas other possible output types for `CallNtPowerInformation`, e.g. [`SYSTEM_BATTERY_STATE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Power/struct.SYSTEM_BATTERY_STATE.html#) have theirs...)

**Comment by kennykerr** [comment]
Thanks, I'll reference this in a new issue. In future, please create a new issue. It's easy to lose sight of unrelated issues in comments.

**Comment by mikebattista** [comment]
Windows.Win32.System.Power.Apis.CallNtPowerInformation : return...Int32 => NTSTATUS
