### ISSUE TITLE
Why did SND_FLAGS move in v24?

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#991]
Just making sure this was intentional as I can't spot a reason for this. 

It's from an old audio API and used to reside in Win32.Media.Audio but is now in the gargantuan Win32.System.SystemServices namespace.

**Comment by mikebattista** [comment]
Looks like a bug in https://github.com/microsoft/win32metadata/pull/940. @aarnott can you fix this?

The SND_FLAGS enum is not properly applied to PlaySoundA and -W variants so the enum is likely getting defaulted to the wrong namespace.

**Comment by AArnott** [comment]
Oh dear. Yes, I'll get that sorted out. Sorry.
