### ISSUE TITLE
`PROCESSOR_POWER_INFORMATION` is missing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#992]
All right :)

Also, while I'm on it: [PROCESSOR_POWER_INFORMATION](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str) is missing a Rust binding as well (whereas other possible output types for `CallNtPowerInformation`, e.g. [`SYSTEM_BATTERY_STATE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Power/struct.SYSTEM_BATTERY_STATE.html#) have theirs...)

_Originally posted by @daladim in https://github.com/microsoft/win32metadata/issues/990#issuecomment-1178157573_

**Comment by mikebattista** [comment]
`SYSTEM_POWER_INFORMATION` is also missing. From the [docs ](https://docs.microsoft.com/en-us/windows/win32/power/processor-power-information-str#remarks) and scanning the kits, looks like they were never included in `winnt.h` so we'll need to define manually.

**Comment by mikebattista** [comment]
Windows.Win32.System.Power.POWER_COOLING_MODE not found in 1st winmd
Windows.Win32.System.Power.PROCESSOR_POWER_INFORMATION not found in 1st winmd
Windows.Win32.System.Power.SYSTEM_POWER_INFORMATION not found in 1st winmd
