### ISSUE TITLE
`HSTRING` invalid handle values are invalid

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#993]
It's defined as follows:

```C#
[RAIIFree("WindowsDeleteString")]
[InvalidHandleValue(-1L)]
[InvalidHandleValue(0L)]
[NativeTypedef]
public struct HSTRING
{
	public IntPtr Value;
}
```

The trouble is that `-1` is never used as an invalid handle value for `HSTRING`. Further, `0` is not an invalid handle value either since that is the underlying representation for an empty string. If you're using `InvalidHandleValue` to decide whether to call `WindowsDeleteString` then I suppose the `0` value is acceptable since an empty string does not need to be freed.

**Comment by AArnott** [comment]
Ooh, that's an interesting distinction between a valid handle and one that doesn't need to be freed. Those are indeed two different things. 
The CsWin32 projection uses `InvalidHandleValue` to implement the `SafeHandle.IsInvalid` property. I'd prefer the existing metadata attribute continue to serve as an *invalid* indicator, given its name. If there are special values that must not be freed, perhaps a new attribute to list those? We'd only need to list them when the value is also valid. 
Also, if it's harmless to call `WindowsDeleteString(0)`, maybe we can just ignore the fact that it needn't be called (resulting in some unnecessary calls in projections that automate freeing them).

It sounds like at the very least, `0` should be removed from the invalid value list. 
@kennykerr, is there no well-defined invalid value for this handle type?

**Comment by riverar** [comment]
[Documentation confirms](https://docs.microsoft.com/windows/win32/winrt/hstring#:~:text=No%20distinct%20value%20exists%20to%20represent%20an%20HSTRING%20that%20is%20uninitialized.) there is no distinct value to represent an HSTRING that is uninitialized. Agree with nixing both values. Was likely a copy-paste bug on my part. 😊

**Comment by kennykerr** [comment]
> @kennykerr, is there no well-defined invalid value for this handle type?

No, there is not.

The APIs for creating (or duplicating) an `HSTRING` all report failure via an `HRESULT`. The `HSTRING` itself has no invalid values. If the `HSTRING` value is non-null it should be freed using `WindowsDeleteString`, but a null value is not in itself an invalid `HSTRING` but merely the ABI representation of an empty string.
