### ISSUE TITLE
Doc: How to generate my own `.winmd` from `.h` files and create a Rust crate depending on this one

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/win32metadata#998]
# Doc request

I have header files in C that use the windows API through `windows.h`. I would like to generate `.winmd` metadata and then generate a Rust crate that would depend on this one (preferably `windows` but I can live with `windows-sys`).

I suspect, as this crate see more and more adoption, other people will want to do this. If this could be documented in somewhat-reproducible steps, it would be very nice.

# Where I am at the moment

I managed to install `ClangSharpPInvokeGenerator` on Linux (somewhat long to get everything, but not that hard).

Now when I do `ClangSharpPInvokeGenerator -o testgen -n my-company-crate -f my_company_header.h --language c`, I get an error saying `windows.h` has not been found.

I suppose I can get past that by doing all this in a Windows VM (slow, but at least it will work easier I think).

How do I generate Rust code after that ?

# Meta

I'm not sure if this is the correct place for such an issue, I saw nothing in the README about a place to discuss such "meta-issues"

**Comment by riverar** [comment]
https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate is now up @poliorcetics, feedback welcome!

**Comment by mikebattista** [comment]
@riverar I added an [FAQ ](https://github.com/microsoft/win32metadata/blob/main/docs/faq.md) linking to your docs. Nice work!

**Comment by MarijnS95** [comment]
@riverar thanks for that write-up! Will you be doing a followup (perhaps requiring `windows_bindgen` changes) to (re)generate namespaces _within_ `Windows.`? That's what we need in https://github.com/microsoft/DirectX-Headers/pull/82 where it currently uses a whole bunch of `super::` relations to (`Foundation::` and other) modules/types that I do not want to generate as part of that crate (and should instead come from `::windows::...`). It is probably non-trivial to tell the generator exactly what symbols or entire namespaces (all part of the same namespace tree) are built locally, and let everything else be sourced externally?

**Comment by riverar** [comment]
@marijnS95 Hm, wasn't planning on that. I think the DirectX crate work you're doing needs to root at `Microsoft.` not the windows crate reserved `Windows.`.

**Comment by MarijnS95** [comment]
@riverar sure, thinking of it that might immediately solve all these problems at once... As long as I generate the `.winmd` to use a different namespace.

**Comment by poliorcetics** [comment]
I have read the post, though I'll only have time to test next week (I hope not later), but it seems very well put together, congratulations and many thanks!

I wonder if this would work in a nix environment with the windows SDK installed (with the proper variables set as necessary), but I can live with having to compile bindings on windows once in while if it means getting read of manually written bindings 🎉

**Comment by MarijnS95** [comment]
@riverar and indeed, it pretty much does; I now have a Rust bindings crate that trivially compiles over at https://github.com/MarijnS95/DirectX-Headers/commit/05196341f9f090de50c72808958e413268051c8a :tada:, thanks so much for this idea! Now all it takes it to clean it up and PR it atop https://github.com/microsoft/DirectX-Headers/pull/82, and see if @kennykerr can publish this to https://crates.io/crates/windows-directx in due time.

There's one remaining problem, however. The individual partitions I created do not cross-reference each-other but keep referencing into `Windows.Win32.Graphics`. We're well of tracks here for context to this specific issue, but is there a way (e.g. in `settings.rsp`) to "rename" a namespace / point it somewhere else?

**Comment by riverar** [comment]
@marignS95 Might be metadata tooling running with the first type it found. Maybe you can workaround that with something similar to https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/requiredNamespacesForNames.rsp

**Comment by riverar** [comment]
> and see if @kennykerr can publish this to https://crates.io/crates/windows-directx in due time.

The `windows` prefix, like in namespaces, is ideally best left for _Windows_ OS APIs. For this upcoming crate, `microsoft-directx` seems more fitting for an official crate (e.g. [microsoft-dia](https://crates.io/crates/microsoft-dia))

**Comment by MarijnS95** [comment]
> @MarijnS95 Might be metadata tooling running with the first type it found. Maybe you can workaround that with something similar to https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/requiredNamespacesForNames.rsp

That sounds like a lot of work to keep up to date unless it can be used to remap whole namespaces at once.

More complicated/inconvenient is the fact that only `Dxgi.Common` (defining `DXGI_FORMAT` etc) is provided by `DirectX-Headers` (and used in `Direct3D12`). `Dxgi` members inside `windows-rs` would still use their own `Dxgi.Common` type; and there are more such overlapping definitions across the `windows-rs` and proposed `microsoft-directx` crates (i.e. stuff from `Direct3D`).

---

> The `windows` prefix, like in namespaces, is ideally best left for _Windows_ OS APIs. For this upcoming crate, `microsoft-directx` seems more fitting for an official crate (e.g. [microsoft-dia](https://crates.io/crates/microsoft-dia))

Agreed, I've squatted `microsoft-directx` for now and published my first attempt, and am fine maintaining this going forward. To alleviate the above, would there be plans to strip this `DirectX` subsection from `windows-rs` and only provide it in a `microsoft-directx` crate?

**Comment by damyanp** [comment]
> The windows prefix, like in namespaces, is ideally best left for Windows OS APIs. 

The APIs described in the DirectX headers are Windows OS APIs though and I'm not sure that they're really the same case as microsoft-dia which really is a separate SDK.

I think that the overlapping definitions problem is one that we're going to have to tackle head on.

**Comment by riverar** [comment]
@damyanp Hmm interesting.

Seems odd for DirectX team to ship out of band headers if it's truly part of the OS? That would normally be covered by the Windows SDK right? Or are these not really Windows OS APIs but rather part of a DirectX runtime that happens to ships inbox? Can DirectX inbox be used w/o any additional dependencies? (Every single game I play seems to suggest that isn't possible <grin>)

**Comment by riverar** [comment]
Marked my comment as outdated, as we're discovering the Agility SDK is just a faster moving ship vehicle https://github.com/microsoft/DirectX-Headers/pull/82#issuecomment-1400813560

**Comment by MarijnS95** [comment]
Would love to mark most/my comments as off-topic and restrict the discussion to DirectX-Headers issues/PRs, sorry for the noise here!
